### ISSUE TITLE
[iOS] Missing NSAppTransportSecurity for http calls

### ISSUE THREAD

**Issue by Laumania** [UXDivers/Grial-UI-Kit-Support#1]
The "About" page isn't working, as you make a call for http content, from iOS 9, iOS only supports https, unless, the below is added to the info.plist file.

``` xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

**Comment by jpbrocca** [comment]
Great, thank you very much Mads!

**Comment by james-lavery** [comment]
A small comment on this I'm sure you know this, but the recommendation is not to bypass NTS completely with the above NSAllowsArbitraryLoads key, but to allow insecure communication on a domain-by-domain basis as follows:

```xml
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>yourserver.com</key>
    <dict>
      <!--Include to allow subdomains-->
      <key>NSIncludesSubdomains</key>
      <true/>
      <!--Include to allow HTTP requests-->
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      <!--Include to specify minimum TLS version-->
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>
```

**Comment by Laumania** [comment]
Awesome answer and I totally agree. Whitelisting is the best solution.

I just need to allow everything in my app as I'm reading in images from
dynamic sources/domains, which I don't know a head of time.

:)

Den 29. nov. 2015 kl. 17.54 skrev james-lavery <notifications@github.com>:

A small comment on this I'm sure you know this, but the recommendation is
not to bypass NTS completely with the above NSAllowsArbitraryLoads key, but
to allow insecure communication on a domain-by-domain basis as follows:

<key>NSAppTransportSecurity</key>
<dict>
  <key>NSExceptionDomains</key>
  <dict>
    <key>yourserver.com</key>
    <dict>
      
      <key>NSIncludesSubdomains</key>
      <true/>
      
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
</dict>

—
Reply to this email directly or view it on GitHub
<https://github.com/UXDivers/Grial-UI-Kit-Bugs-1.1.0/issues/1#issuecomment-160431786>
.
