### ISSUE TITLE
We need to make explicit how Fontawesome is used on Grial

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Grial-UI-Kit-Support#10]
Another good suggestions form **@james-lavery**:

_"One comment on the documentation. I think you need to document more fully how Fontawesome is used in the system. I've got it worked out now, but it took me some digging to work out that I need to have the ttf font included as a resource/asset etc."_

**Comment by Laumania** [comment]
Extra info. On iOS add the ttf file to Resources and set it to "Always copy". Just like in the sample app.
Then add this to your Info.plist:

```
<key>UIAppFonts</key>
	<array>
		<string>fontawesome-webfont.ttf</string>
	</array>
```

Then it seems to work :)

**Comment by Laumania** [comment]
For Android:

Create a class /Renderers/CustomFontLabelRenderer.cs take the content from the sample project.

Add the fontawesome-webfont.ttf to the /Assets/ folder. Select the file, and make sure the Build Action is set to "AndroidAsset" in the Properties tab. Should be like that by default.

...this still isn't enought...I'll update this entry as I discover more :)

**Comment by carlosgtzrdz** [comment]
Could I update the font file to fontawesome-webfont.ttf to 4.6 awesome version??

**Comment by jpbrocca** [comment]
Hi,
Yes, sure.

Make sure to put the .ttf files in the right placer and check the file name is the same linked in Grial or you will need to update that in more places.

Also, keep in mind that if in this version the icons changed their character  you will need to update templates too.

Let me know if you need more help.

**Comment by nodoid** [comment]
Hello, 

Do you want to take a look at  the coolest things ever? Here  is  the link <http://date.wodingdong.com/aecspeq>

paul

**Comment by lerrie** [comment]
Hi,
I would like to implement FontAwesome also with Grial UI Kit, where can i get the content for /Renderers/CustomFontLabelRenderer.cs ? Somehow it is not in my sample project. Thanks in advance.

**Comment by jpbrocca** [comment]
Hi @lerrie,

This is an old thread, please have a look at Grial 2.0 docs about working with icons:
https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons

Best,
JP
