### ISSUE TITLE
Device orientation in Android

### ISSUE THREAD

**Issue by davidvasquezr** [UXDivers/Grial-UI-Kit-Support#102]
Hello, I purchased GrialUI few months ago, I developed my application but I have a problem with navigation on Android. When I change the orientation of the device then the application is directed to the main view. I downloaded UIKit Grail from the Play Store and see that the application fails when the device orientation changes. There is a mishandling of this event in Android or I've developed something wrong?

"Grial UIKit" is crashed when device orientation is changed 
https://www.youtube.com/watch?v=mjN-XWfQ_5c&feature=youtu.be

My app
https://www.youtube.com/watch?v=gO83E9kkikc&feature=youtu.be

**Comment by jpbrocca** [comment]
Hi @davidvasquezr,

can you send me an email to:
jpbrocca@uxdivers.com

with the order number and the name of the person who purchased the license?

Then show me your MainActivity.cs, Grial and Xamarin Forms version number and please provide as much details as possible.
If you want to send it in Spanish that is OK.

Best regards,
JP

**Comment by davidvasquezr** [comment]
The solution is:

Put the line above in MainActivity class:

ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize

![image](https://cloud.githubusercontent.com/assets/18266371/19497249/11cf1982-9551-11e6-9a1a-320b6517761f.png)

Thanks Grial-UI-Kit-Support.

**Comment by douglassimaodev** [comment]
You need to rebuild your android apk demo as I downloaded it and it is crashing so not good for marketing...
