### ISSUE TITLE
error during PlayStore upload - ERROR getting 'android:icon' attribute

### ISSUE THREAD

**Issue by bbbdev** [UXDivers/Grial-UI-Kit-Support#103]
Hello, 
I have a problem during the upload of my app to the Google Playstore.

I build a android apk in Xamarin Studio using your standard package (version 1.5) without any changes (just open Grial.sln from samples dir | build Grial.Droid , Release version | Archive for Publishing | Sign and Distribute | Upload to Google.

I get the following error message:
W/ResourceType(  816): No known package when getting value for resource number 0x0106000d
ERROR getting 'android:icon' attribute: attribute is not a string value

I get the same error if I test the apk using aapt:

```
/Library/Developer/Xamarin/android-sdk-macosx/build-tools/25.0.0/aapt dump badging com.artina.grial.uikit.apk
.....
application-label-zh-TW:'Grial UIkit'
application-label-zu:'Grial UIkit'
application-icon-160:'res/drawable/icon.png'
application-icon-240:'res/drawable/icon.png'
application-icon-320:'res/drawable/icon.png'
application-icon-480:'res/drawable/icon.png'
application-icon-640:'res/drawable/icon.png'
application: label='Grial UIkit' icon='res/drawable/icon.png'
W/ResourceType(  816): No known package when getting value for resource number 0x0106000d
ERROR getting 'android:icon' attribute: attribute is not a string value

```

Any idea how to fix this issue? I know, there can be a lot of reasons for this error.

Thanks a lot for your help.

PS: I am using Xamarin Studio 6.1.1 (build 15) at MacOS Sierra; I get the same error at my Windows10, VisualStudio15 Update3 machine

**Comment by bbbdev** [comment]
I fixed the problem by myself (at least it works for me now).

The problem is in the file Droid/MainActivity.cs :

`[Activity (
		Label = "Artina Grial",
		Theme = "@style/AppTheme",
		Icon="@android:color/transparent",
		MainLauncher = false)
	]`

Google doesn't like @android:color/transparent 

I changed it to:

`[Activity(
		Label = "Artina Grial",
		Theme = "@style/AppTheme",
		Icon = "@drawable/icon",
		MainLauncher = false)
	]`
and now everything is fine.

[More details here](http://stackoverflow.com/questions/20800633/getting-androidicon-attribute-attribute-is-not-a-string-value-error-while)

I suggest to improve the standard code.
Hope this helps somebody else as well.

**Comment by jpbrocca** [comment]
Hi @bbbdev,

thanks for your suggestion!
We will add this fix on the code and also to our known issues.

Regards and thanks!
JP

**Comment by dirivero** [comment]
This is part of Grial thanks to @bbbdev suggestion from a long time ago so I will close this issue now. Thanks again!
