### ISSUE TITLE
Android Font Icon on Label

### ISSUE THREAD

**Issue by po0kie** [UXDivers/Grial-UI-Kit-Support#106]
I have a strange bug when i change the design time established icon on Label with another FontIcon
on Android after changing the text the icon gets like unregonized.

Is there something I am missing?

**Comment by jpbrocca** [comment]
Hi @po0kie,

Are you previewing your XAML through Gorilla Player ? I assume you are using the Gorilla SDK to preview the custom renderer for the icons so when you changed the font you will also need to recompile in order to get the latest font previewed.
Also, when you change the font you need to make sure to update the char that matches your icon on the new font.

Best,
JP

**Comment by po0kie** [comment]
No, I am not using Gorilla Player.
and as I said, on ios its working its just happening on Android.

Default value -> a unchecked Icon. ...user tabs Icon -> i change the icon to check icon and on ios it works but on Android the icon gets drawed like a "x"

**Comment by jpbrocca** [comment]
Hi again @po0kie,
I thought you changed the font, sorry for the misunderstanding.

So you actually changed the character and it does not work on Android, right ?
Can you tell me which is the specific character that is causing this issue and which page are you trying with ?

Thanks,
JP

**Comment by po0kie** [comment]
Hi,

I am doing it on my own project. Had no time to try it on Grial Project.
The point is the following:

When I construct a Label with Spans, and later on – on events I change the Span Text (incluing just the Text span and not the Icon span)
then the Icon gets “rendered” bad. So the only workaround I have at this moment is to put the label splitted into 2 labels and inside a StackLayout
in Horizontal Orientation.  After that I can change the Label Text without any problem, but I cant change the Icon…

Is there a way to call some function on “Device” or on the Label to try to “re-render” the control?

Best regards
Marc

De: jpbrocca [mailto:notifications@github.com]
Enviado el: miércoles, 26 de octubre de 2016 20:30
Para: UXDivers/Grial-UI-Kit-Support <Grial-UI-Kit-Support@noreply.github.com>
CC: po0kie <marc@interpalma.com>; Mention <mention@noreply.github.com>
Asunto: Re: [UXDivers/Grial-UI-Kit-Support] Android Font Icon on Label (#106)


Hi again @po0kie<https://github.com/po0kie>,
I thought you changed the font, sorry for the misunderstanding.

So you actually changed the character and it does not work on Android, right ?
Can you tell me which is the specific character that is causing this issue and which page are you trying with ?

Thanks,
JP

**Comment by pars2307** [comment]
Hi @po0kie ,

I have the same problem. Have you find a solution?

Thanks

**Comment by po0kie** [comment]
Hi @pars2307  
Nope, still the same issue.

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for a couple of years.
Please reopen if you still encounter this issue with the latest Grial version.
Thanks
