### ISSUE TITLE
UXdivers.Artina.Grial.iOS.dll

### ISSUE THREAD

**Issue by rafasaints** [UXDivers/Grial-UI-Kit-Support#107]
Hi, sorry if my question is dummy but i'm trying to create a new project using grial follow the website instructions but on the kit dont find the UXdivers.Artina.Grial.iOS.dll ??

Tanks ?

**Comment by rafasaints** [comment]
Sorry, i see now, the file is another now, not the one you have on website.

**Comment by SamArmand** [comment]
And which file is that?

**Comment by jpbrocca** [comment]
These are the right references that should be included:

### PCL project
![image](https://cloud.githubusercontent.com/assets/15996999/22119580/e09d8f26-de5a-11e6-90c6-ca4fd719d6ad.png)

### Android project
![image](https://cloud.githubusercontent.com/assets/15996999/22119664/31cdb312-de5b-11e6-84ac-f6791243bf79.png)

### iOS project
![image](https://cloud.githubusercontent.com/assets/15996999/22119690/4af7d462-de5b-11e6-8da9-24a2fd24b18a.png)
