### ISSUE TITLE
ExportedColors

### ISSUE THREAD

**Issue by rafasaints** [UXDivers/Grial-UI-Kit-Support#108]
When i build i have the following error : 

Error -CS0103   The name 'ExportedColors' does not exist in the current context.

This concerns the Appearance.cs file that i put on my IOS project.

**Comment by jpbrocca** [comment]
Hi @rafasaints,
please have a look at this page:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Can't-compile-T4-templates

Best,
JP
