### ISSUE TITLE
Question about New Version or Update

### ISSUE THREAD

**Issue by Millardh77** [UXDivers/Grial-UI-Kit-Support#110]
I am currently using version 1.2.2 of the Grial Kit and was thinking about upgrading to 1.5.  Should I go ahead and upgrade or wait for 2.0?  Also is it worth the effort to upgrade to 1.5 anyway?

**Comment by jpbrocca** [comment]
HI @Millardh77,

upgrading to 1.5 should be easy.
The main addition was the AppCompat support.
That means you will need to update some stuff on your Android project resources (themes).

Grial 2.0 will take some time until it is released so I would suggest to go for 1.5.

Best,
JP

**Comment by Millardh77** [comment]
Thanks JP.  Sounds good.  Do I just need to update the libraries?  Or are there changes to any of the other objects?  Is there any update roadmap?

**Comment by jpbrocca** [comment]
Hi @Milkardh77.

Please check this Link:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/44

Look for Ed Hubel's comments about the files needed to update besides de dlls.

Best
JP

**Comment by tilutza** [comment]
Hi Mr Rocca,


I have the 1.5 version, but is there any update available for download?
I sent you an email for this, but I didn;t get any reply.

**Comment by jpbrocca** [comment]
Hi @tilutza,
we have recently made an update to support latest Xamarin Forms version.
You should have received the link to this update (was sent just a few minutes ago).
Best,
JP

**Comment by homerokzam** [comment]
With new features?

Thanks,
Homero

**Comment by jpbrocca** [comment]
Hi Homero,
No, just fixes un order to run Grial sample with latest xamarin forms version.

Regards,
JP

**Comment by kinkok** [comment]
Hi 

Will Grial be supporting xamarin form 2.3.4 and  Xamarin Android Support nugets up to 25.1.0?

Thanks

**Comment by jpbrocca** [comment]
Hi @kinkok,
We will be supporting latest stable version of Xamarin Forms and same for its Android dependencies.
The version you mentioned is still in pre release.

Best,
JP

**Comment by t4lm1d** [comment]
Hi,

I would also like to receive the version that runs on the latest Forms version.  What can I do to receive?  Does this version update also include KitKat support.  I noticed on the website, it looks like you now support KitKat?

Thanks!

Eric

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for a couple of years.
