### ISSUE TITLE
Bad image when the device is rotated in iOS

### ISSUE THREAD

**Issue by davidvasquezr** [UXDivers/Grial-UI-Kit-Support#111]
Hello,

I have developed a view that has a background image. When the device is in portrait mode the image is shown well, but when the device is in landscape mode the image is shown incomplete. Android expands the image to the full width of the screen, the problem is only in IOS.

- I put the background image with the code below in WelcomePage.xaml:
<ContentPage
  xmlns="http://xamarin.com/schemas/2014/forms"
  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
  x:Class="MyApp.View.Navigation.WelcomePage"
  BackgroundImage="{ StaticResource WelcomeBackgroundImage }"
  xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
  xmlns:local="clr-namespace:MyApp"
  xmlns:commonViews="clr-namespace:UXDivers.Artina.Grial;assembly=MyApp">

- In App.xaml:
<FileImageSource x:Key="WelcomeBackgroundImage">welcome_bg.png</FileImageSource>

- The Resources folder in MyApp contains the images:
![image](https://cloud.githubusercontent.com/assets/18266371/19982018/4de32cbe-a1d2-11e6-8b1c-b41495dbc7c3.png)
(The same image but different name)

The images below represents my problem.

In landscape mode.
![img_0026](https://cloud.githubusercontent.com/assets/18266371/19982292/882e60c2-a1d3-11e6-8200-54e66b4acbb7.PNG)

In portrait mode.
![img_0025](https://cloud.githubusercontent.com/assets/18266371/19982293/88376b54-a1d3-11e6-9ebc-55fc42d3db8f.PNG)

**Comment by jpbrocca** [comment]
No @davidvasquezr,
Using the BackgroundImage won't give much control over the image aspect.
You could:
- add an absolute layout or grid with just an <Image> then make sure you overlap your content.
- change your image proportions to make it fit using the image aspect of the <Image>.

Best
JP

**Comment by davidvasquezr** [comment]
I found this in the template. I tried that and that was the solution. Thanks.
