### ISSUE TITLE
Style ignored on iOS 

### ISSUE THREAD

**Issue by snoova** [UXDivers/Grial-UI-Kit-Support#112]
Hi @jpbrocca,

we are new on using GrialKit.
We get it to work on Android, but having style problems on iOS (simulator & device).
I read the how-to (https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files#ios) but find no solution yet.

I seems to me, that all "artina" flagged style properties are ignored on iOS completly.

As you can see on the screenshot, the AccentTextColor is set correctly, however "BorderStyle", "BorderColor" is ignored.

iOS version: 10.1
Win/Visual Studio 2015 (Update 3)
Xamarin.Forms version: 2.3.2.127 (last stable)
Views are defined in Shared Projects

If you need any further information please do not hesitate to contact me!

Thanks,
snoova
![login](https://cloud.githubusercontent.com/assets/23309847/20054948/4831833c-a4df-11e6-8744-c0f96113e8a2.png)

**Comment by jpbrocca** [comment]
Hi @snoova,

we have reproduced this issue.
It seems this is happening on iOS10.
We will fix it asap and let you know.

Best,
JP

**Comment by kiapwnz** [comment]
Any update on this?

**Comment by jpbrocca** [comment]
Hi @snoova,
are you using an <artina:Entry> or just an <Entry>?

Best,
JP

**Comment by snoova** [comment]
@jpbrocca 

XAML
```
                    <Entry
                        Grid.Row="1"
                        VerticalOptions="StartAndExpand"
                        Placeholder="{lang:Translate password}"
                        Text="{Binding Password}"
                        IsPassword="true"
                        Style="{ DynamicResource ArtinaLoginEntryStyle }" />
```

App.xaml
```
            <Style
                x:Key="ArtinaLoginEntryStyle"
                TargetType="Entry"
                BasedOn="{ StaticResource LoginEntryStyle }">
                <Setter
                    Property="artina:EntryProperties.BorderStyle"
                    Value="BottomLine" />
                <Setter
                    Property="artina:EntryProperties.BorderColor"
                    Value="{ StaticResource TranslucidWhite }" />
                <Setter
                    Property="artina:EntryProperties.PlaceholderColor"
                    Value="{ StaticResource PlaceholderColorEntry }" />
                <Style.Triggers>
                    <Trigger
                        TargetType="Entry"
                        Property="IsFocused"
                        Value="True">
                        <Setter
                            Property="artina:EntryProperties.BorderColor"
                            Value="{ StaticResource AccentColor }" />
                    </Trigger>
                </Style.Triggers>
            </Style>
```

**Comment by jpbrocca** [comment]
Hi @snoova and @kiapwnz,

could you guys send your purchase information (name, order number, etc.) to:
 
`hello@uxdivers.com`

so we can send you the update with the fix ?

Regards and thanks,
JP

**Comment by jpbrocca** [comment]
Hi @snoova and @kiapwnz,
You have received the update and I assume everything is working so I am closing this issue now.
Feel free to reopen in case it is necessary.

Best,
JP

**Comment by cw90** [comment]
Hi @jpbrocca 
After the update the styles are still ignored on iOS

Best regards,
cw

**Comment by jpbrocca** [comment]
@cw90 I don't have you here on this thread, so I am not sure if you received the update or not.
Can you send an email to hello@uxdivers.com with your purchase info?

Best,
JP

**Comment by cw90** [comment]
Sorry I forgot to say that I'm a colleague of @snoova .
I've sent you an email with our purchase info.

Regards,
cw

**Comment by LeoHere** [comment]
Is the Entry's custom renderer exported in your iOS project?

You should have something like this:

~~~
[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Artina.Shared.ArtinaEntryRenderer))]
~~~

**Comment by cw90** [comment]
Thank you very much!
That fixed our problem.

Best regards,
cw
