### ISSUE TITLE
Prism MVVM

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#113]
Hi,

Anyone has experience to use GrialKit with Prism Mvvm?

I am not able to get it works, seem like GrialKit come with default navigation mechanism. Anyway I can disable this and replace with Prism Mvvm deep linking?

Thanks,
Dennis

**Comment by ShiroYacha** [comment]
The Prism navigation uses its own navigation service based on Xamarin. You can use constructor injection on the view model to obtain them. I don't have any issues using it without disabling the Grialkit navigation.
