### ISSUE TITLE
App crashes on horizontal position

### ISSUE THREAD

**Issue by douglassimaodev** [UXDivers/Grial-UI-Kit-Support#114]
I have samsung  note 4 android 6.0 and always when I rotate my phone to horizontal app closes

**Comment by jpbrocca** [comment]
Hi please see:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/102

Please remember to close this issue after you fix it.

Best,
JP

**Comment by douglassimaodev** [comment]
I downloaded you demo android app so you need to rebuild it as it is not
good for marketing...

**Comment by jpbrocca** [comment]
Oh, you are right!
Thanks for letting me know!
Best,
JP
