### ISSUE TITLE
The WebView is showing wrong when I rotate my view in iOS.

### ISSUE THREAD

**Issue by davidvasquezr** [UXDivers/Grial-UI-Kit-Support#115]
Hi Grial UI Kit Support,

Currently, I have a problem with iOS WebView rotation. If my view is loaded in portrait mode and the view is rotated to landscape mode then the WebView is showed wrong (Shorter than the screen width). 
The same case occurs when the view is loaded in landscape mode.

The images below represents my problem.
In portrait mode:
![portrait](https://cloud.githubusercontent.com/assets/18266371/20795145/92b35ad6-b79d-11e6-8257-134f7257a1f5.png)

In landscape mode:
![landscape](https://cloud.githubusercontent.com/assets/18266371/20795177/bee830fe-b79d-11e6-8e33-d8fe1584c4cb.png)

Thanks in advance.

**Comment by jpbrocca** [comment]
Hi @davidvasquezr, how are you ?

Please see the following for a possible solution:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/80

Best,
JP

**Comment by davidvasquezr** [comment]
This solution does not work for me. I tried with this:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyMintApp.View.WebServiceCharts.ServiceChart">
  <StackLayout 
      BackgroundColor="Navy">

      <BoxView 
          Style="{StaticResource Horizontal1ptLineStyle}" />

      <!-- MAIN PARAGRAPH -->
      <WebView x:Name="viewJupyter"
              HeightRequest="400"
              VerticalOptions="FillAndExpand" />
  </StackLayout>
</ContentPage>
```

And I get this:
Portrait mode
![portrait](https://cloud.githubusercontent.com/assets/18266371/20797607/818a1bb2-b7a9-11e6-878f-11f57291cba0.png)

Landscape mode
![landscape](https://cloud.githubusercontent.com/assets/18266371/20797618/96da725a-b7a9-11e6-99ea-21d8665bfac0.png)

**Comment by jpbrocca** [comment]
Then you will need to add some on your code behind to make the webview to
"grow" to the right size detecting the orientation change.

I can't think on any other way if the previous didn't work but maybe you
could find some workaround on xamarin forums.

Best,
JP
ᐧ






*Juan Pablo Brocca*
UXDivers Co Founder
uxdivers.com


*XAML preview for Xamarin Forms*
gorillaplayer.com


*Ready made Xamarin Forms screens in XAML*
grialkit.com

2016-12-01 11:40 GMT-03:00 davidvasquezr <notifications@github.com>:

**Comment by jpbrocca** [comment]
Hi @davidvasquezr, how are you?
I found this on xamarin forum which could help you:

https://forums.xamarin.com/discussion/20418/ios-webview-doesnt-resize-width-on-device-rotation

And here is the bug on Xamarin Forms causing this issue:
https://bugzilla.xamarin.com/show_bug.cgi?id=30047

best,
JP

**Comment by davidvasquezr** [comment]
I tried this; I implemented the custom renderer and added the line "webView.AutoresizingMask = UIViewAutoresizing.FlexibleDimensions;" but it doesn't work for me. Then, I solved this with a not so elegant solution (reloading the WebView component when the device orientation changes).
