### ISSUE TITLE
Grial on Xamarin.Forms 2.3.3.168

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#116]
Hi Grial Kit Support,

Recently updated the my Grial Project with Xamarin.Forms 2.3.3.168.

It gives error message below during the build.

========================================
Now the project not able to compile and show error message below.
: error : Member 'System.DateTime' is declared in another module and needs to be imported

	 4 Warning(s)
	 1 Error(s)

========================================

It took me sometime (few days) to identify which packages could cause the issue, by removing my packages one by one. Until I started another brand new Grial Sample Project. Change nothing but update the Xamarin.Forms to 2.3.3.168. Then the issue mentioned surfaced.

Any new update with the Grial package or workaround?

Please advice.
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung,
This problems occurs on "ThemePage.xaml" when XAMLC is enabled (in our sample).

You will need to remove the following:
`"xmlns:sys="clr-namespace:System;assembly=mscorlib""`

then you will need to remove this:
`"Date="{x:Static sys:DateTime.Now}"`

If you need that for some reason you will need to find another way to set the Date property (like for instance through a Binding).

Regards,
JP

**Comment by jpbrocca** [comment]
Hi @denfung,
did you try with the proposed solution ?

If it worked, please close this issue.

Thanks a lot!
JP

**Comment by denfung** [comment]
Hi @jpbrocca ,

Yes, this work. 

Thanks,
Dennis
