### ISSUE TITLE
Error: Member 'System.DateTime' is declared in another module and needs to be imported (Grial)

### ISSUE THREAD

**Issue by mrctito** [UXDivers/Grial-UI-Kit-Support#117]
Error when building the sample provided by Grial Ui Kit installation zip file:

Error: Member 'System.DateTime' is declared in another module and needs to be imported (Grial)

Please, help me.

**Comment by mrctito** [comment]
I would like to give you one more information.

This error starts after I update the packages to new version of Xamarin.Forms to 2.3.3.168.

Thank you,

**Comment by jpbrocca** [comment]
Hi @mrctito, 
please check the following link:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/116

Best,
JP

**Comment by mrctito** [comment]
Thank you
