### ISSUE TITLE
Grial may slow down your iPhone 

### ISSUE THREAD

**Issue by mrctito** [UXDivers/Grial-UI-Kit-Support#118]
Dear sirs,

How about this warning?

![image](https://cloud.githubusercontent.com/assets/809686/20847619/15ec4002-b8b6-11e6-92ae-4f95ef98ff31.png)
![glass_e_iphone_6_ _ios_10_1__14b72_](https://cloud.githubusercontent.com/assets/809686/20848722/753dfc86-b8ba-11e6-971b-1926129d7baf.png)

**Comment by cbartonnh** [comment]
This message is displayed when the app is only built for 32-bit. Default debug configuration for iOS Simulator is only 32-bit but default for Release builds is 32 & 64. You can change your setting in project options -> iOS Build -> Supported Architecture if you want to make this message go away.

**Comment by mrctito** [comment]
Thank you!

2016-12-02 18:22 GMT-02:00 cbartonnh <notifications@github.com>:

> This message is displayed when the app is only built for 32-bit. Default
> debug configuration for iOS Simulator is only 32-bit but default for
> Release builds is 32 & 64. You can change your setting in project options
> -> iOS Build -> Supported Architecture if you want to make this message go
> away.
>
>

**Comment by jpbrocca** [comment]
Hi @mrctito,

please remember to close the issue if the fix works for you.

Thanks a lot @cbartonnh for your help! We really appreciate it!

Best regards,
JP
