### ISSUE TITLE
Support Jelly Bean and KitKat for Android

### ISSUE THREAD

**Issue by omanuke** [UXDivers/Grial-UI-Kit-Support#12]
The share of both version is still high.
No support for both versions will restrict adoption of UI Kit for Android.
If some feature can't be used ,it's OK. But no support is very annoying.

**Comment by jpbrocca** [comment]
Hi Omanuke, thanks for your feedback.

Our original goal was to support such versions and higher.

The main problem was related to AppCompat issues on Xamarin which limits us on what can be done in regards the theme.
So we had to reduce our scope to Android 5.0+, though in an effort to make Grial available for Kit Kat -as requested by one customer- we did our best to override Holo theme to match Grial look and feel.

We are currently working on an update for Grial and part of our tasks is to review new AppCompat support on Xamarin. If that finally works then we could support Jelly Bean and Kit Kat with better theme support.

**Comment by omanuke** [comment]
Great.
I hope it'll work.

**Comment by jpbrocca** [comment]
Good news omanuke :)
So far it seems to work on Jelly Bean + :)


![image](https://cloud.githubusercontent.com/assets/15996999/12140383/4147389e-b446-11e5-8f4d-a51737ceb857.png)

There are some other things I will need to tweak -seems it will take some hard work- but it looks promising :)

**Comment by ShiroYacha** [comment]
Hi,
Somehow the tabbed page action bar is not colored in AccentColor in KitKat. It works on my device (API21) but shows a gray background in the KitKat emulator. Is there a way to fix this?
Thanks!

**Comment by jpbrocca** [comment]
Hi @ShiroYacha we currently don't provide support to TabbedPage in Grial.
Are you using AppCompat with Grial ?
Can you attach a screenshot of how it looks on your device?

Thanks.
JP

**Comment by ShiroYacha** [comment]
Hi @jpbrocca thanks for the quick response! No i'm not using AppCompat... I thought that its the implicit theme that renders the bar as it works on my Lollipop device... Here is a screen shot on my emulator (I don't have access to my Lolipop device now). 
![tabbedpagebar](https://cloud.githubusercontent.com/assets/4082699/13631390/a691d4e6-e5e4-11e5-8c99-67e16c2c0525.png)

**Comment by jpbrocca** [comment]
You are welcome @ShiroYacha :)

Yes, the problem here is the Holo theme used by KitKat.
Is not that easy to style it since for instance the sky blue bottom line can only be changed through bitmaps so you will need to provide those.

Here are some tools that could help you to get what you need but you will need to manually adapt the Android theme for that:

http://goo.gl/Q3Dt56
http://goo.gl/gNjBO

Regards,
JP

**Comment by ShiroYacha** [comment]
@jpbrocca Thanks, I will give it a try :)

**Comment by jpbrocca** [comment]
@ShiroYacha Ok, let me know how it goes.

**Comment by jpbrocca** [comment]
Closing this issue since through AppCompatV7 support introduced in Grial 1.5 this is now possible.
