### ISSUE TITLE
Binding Grial Grid to Command

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#121]
Hello, 

The default dashboard sample of Grial handle the taps through an event. Following the MVVM guidelines, we want to use the command instead of the event. However, it seems that the grid is having some issues with binding to commands on the TapGesture. I have pasted a sample below where I have 2 content views with tap gestures bound to the same command. The bottom one is in a Grial Grid and the top one is outside the grid. The outside one works without any issues but the one inside the grid doesn't connect to the command. Is there any additional configuration required for this? Thanks in advance for your help.

 ` <StackLayout>
   
    <ContentView BackgroundColor="Blue" >
      <ContentView.Content>
        <Label Text="This is outside the grid" />
      </ContentView.Content>
      <ContentView.GestureRecognizers>
        <TapGestureRecognizer  **Command="{Binding  GridTestCommand}" />**
      </ContentView.GestureRecognizers>
    </ContentView>
 
  <artina:GridOptionsView
                     ColumnCount="2"
                     RowCount="2"
                     ColumnSpacing="1"
                     RowSpacing="1"
                     Padding="0"
                     VerticalOptions="FillAndExpand"
                     BackgroundColor="#e7ebed"
      
                     ItemsSource="{Binding Dashboard.DashboardWindows}">
    <artina:GridOptionsView.ItemTemplate>
      <DataTemplate>
        <ContentView BackgroundColor="Blue" >
          <ContentView.Content>
            <Label Text="{Binding Title}" />
          </ContentView.Content>
          <ContentView.GestureRecognizers>
            <TapGestureRecognizer  Command="{Binding  GridTestCommand}" />
          </ContentView.GestureRecognizers>
        </ContentView>
      </DataTemplate>
    </artina:GridOptionsView.ItemTemplate>
  </artina:GridOptionsView>
      </StackLayout>
</ContentPage>`

**Comment by LeoHere** [comment]
I think the problem might be in where you defined the ```Command``` property. In order for the provided XAML to work, you need a ```GridTestCommand``` property defined in the page's view model (```ContentView``` scenario) and in the view model returned by the ```Dashboard.DashboardWindows``` (```GridOptionsView``` scenario). Please remember that the ```GridOptionsView``` is analogous to a ```ListView``` in the sense that the ```ItemSource``` property would define the list of items to be renderer. The ```GridOptionsView``` would instantiate the ```ItemTemplate``` for each item and set its binding context to the corresponding item.

In order to adapt the Dashboard samples to use commands instead of events you will need to change the ```DashboardViewMode``` view with something like this: 
~~~
using System.Collections.Generic;
using System.Linq;
using Xamarin.Forms;

namespace UXDivers.Artina.Grial
{
	public class DashboardViewModel
	{
		public DashboardViewModel(INavigation navigation)
		{
			Items = SamplesDefinition.SamplesCategoryList.Select((sc) => new DashboardItemViewModel(sc, navigation));
		}

		public IEnumerable<DashboardItemViewModel> Items { get; }
	}

	public class DashboardItemViewModel
	{
		private readonly SampleCategory _category;

		public DashboardItemViewModel(SampleCategory category, INavigation navigation)
		{
			_category = category;

			ItemSelectedCommand = new Command(async () => await SamplesListFromCategoryPage.NavigateToCategory(category, navigation));
		}

		public Command ItemSelectedCommand { get; }

		public char Icon
		{
			get
			{
				return _category.Icon;
			}
		}

		public string Name
		{
			get
			{
				return _category.Name;
			}
		}

		public Color BackgroundColor
		{
			get
			{
				return _category.BackgroundColor;
			}
		}

		public string BackgroundImage
		{
			get
			{
				return _category.BackgroundImage;
			}
		}
	}
}
~~~

Please take into account that by using commands instead of events you will loose the item tapped animation.

**Comment by scorpio2000** [comment]
Hi LeoHere,

I didn't realize that the items source was being used as the binding context for the command.  Now that I know that, I got a really simple way to resolve it. I explicitly set the source for the command property for the gesture to the binding context of the page. It worked like a charm :)

  var tapGr = new TapGestureRecognizer();
                //tapGr.Tapped += OnWidgetTapped;
               tapGr.SetBinding(TapGestureRecognizer.CommandProperty, new Binding("GridTestCommand", source:this.BindingContext));

Thanks so much for your help.
