### ISSUE TITLE
TabsPage icons

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#123]
Hi GrialUI Support,

I would like to know is there an option to change the Tab icons shown on the TabsPage.

I changed the icons ("tabs0_icon.png", "tabs0_icon@2x.png", and "tabs0_icon@3x.png") in the Resources folder under iOS project. But that does not help.

Please advice where the icon "tabs0_icon" in the TabsPage.xaml get from?

Thanks,
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung,

I am not sure I understood your question, if you wanted to change the icon images what you did should work.

If you want to set the icons per each tab, then please check the TabbedPage documentation:
https://developer.xamarin.com/guides/xamarin-forms/user-interface/navigation/tabbed-page/

Basically each "Tab" is a ContentPage so simply by setting its Icon property you will be able to set the icon you need on each tab.

Best,
JP

**Comment by denfung** [comment]
Hi @jpbrocca ,

I would like to change the icon on the tabs.

<img width="465" alt="screen shot 2016-12-05 at 10 32 24 pm" src="https://cloud.githubusercontent.com/assets/23342040/20888740/1e9e8200-bb3b-11e6-94cb-3ebab3aef322.png">


I found those images in the Resource (iOS Project) folder. But changing them does not help. I did clear the project and rebuild. Still not working.

Can we use FontAwsome? So the vector font is sharper as compare to image icon.

Please advice.
Dennis

**Comment by denfung** [comment]
Hi @jpbrocca,

It works now. My bad. I was replacing the image with the same name. Some how it cached the old images, even I clean and rebuild the iOS project. Hence thought it is not working.

Now I added "monkeyicon.png", it grabs that new icon in the built project.

Thanks,
Dennis

**Comment by jpbrocca** [comment]
Ok, sounds good!

Closing this issue now.

Regards,
JP
