### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'UXDivers.Artina.Shared' or one of its dependencies

### ISSUE THREAD

**Issue by RobertLynch** [UXDivers/Grial-UI-Kit-Support#125]
I am just starting with Grial and have about a month experience with Xamarin.  I am trying to add the UI Kit to an existing project.  When I attempt to run it on iOS, I get the error above.  Reading through the other threads here I found the advice to add this to AppDelegate.cs:

var workaround = typeof(UXDivers.Artina.Shared.CircleImage);

However, this produces:

The type or namespace name 'CircleImage' does not exist in the namespace 'UXDivers.Artina.Shared' (are you missing an assembly reference?)

**Comment by LeoHere** [comment]
There seems to be an issue with your references to ```UXDivers.Artina.Shared```. Please double check that you have correctly referenced our shared assemblies:
* ```UXDivers.Artina.Shared.dll``` should be referenced from your PCL, iOS and Droid projects
* ```UXDivers.Artina.Shared.iOS.dll``` should be referenced form your iOS project
* ```UXDivers.Artina.Shared.Droid.dll``` should be referenced from your Droid project

**Comment by RobertLynch** [comment]
I was missing the UXDivers.Artina.Shared.dll reference in the iOS project.

Thank you.
