### ISSUE TITLE
How to change dashboard icon target page?

### ISSUE THREAD

**Issue by abuzaforfagun** [UXDivers/Grial-UI-Kit-Support#126]
Hi, I want to navigate specific pages on navigation with Dashboard icons. And how can I do this? Can you explain?

Suppose I want to navigate Itempage when licked on social icon. How can I do that?
Thanks

**Comment by davidmalach** [comment]
I have the same question.  Please respond if possible.  Thank you.

**Comment by jpbrocca** [comment]
Hello @davidmalach how are you?

Please check this related issue:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207

Regards 
JP
