### ISSUE TITLE
DisplayAlert shows title twice

### ISSUE THREAD

**Issue by tellamon** [UXDivers/Grial-UI-Kit-Support#127]
DisplayAlert() function shows title twice in Droid project as shown below.

UXDivers.Artina.Shared 1.5.0.12366
UXDivers.Artina.Shared.Droid 1.5.0.12799

![screenshot 2016 12 19 12_31_19](https://cloud.githubusercontent.com/assets/1867602/21300437/4fafc91a-c5e7-11e6-8f71-e7911aa6fb2b.jpg)

**Comment by jpbrocca** [comment]
Hi @tellamon,

Please check this solution:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/75

Best
JP

**Comment by tellamon** [comment]
@jpbrocca  That works.
Thank you.

**Comment by jpbrocca** [comment]
Hi @tellamon,

you are welcome.

Please remember to help us keeping things tidy by closing issues after you get the resolution ;)

Thanks!
JP
