### ISSUE TITLE
Adding icon to navigation bar

### ISSUE THREAD

**Issue by davidvasquezr** [UXDivers/Grial-UI-Kit-Support#129]
Hi Grail-UI-Kit-Support

I am trying to add an icon in the navigation bar and I have achieved it with the following code:

```
var settings = new ToolbarItem
{
   Icon = "star_filled.png",
   Text = "Settings"
};
this.ToolbarItems.Add(settings);
```

The star icon is yellow but when added to the navigation bar is shown in blue. How can I change just the color of that icon?
Also, the icons here are blurry :( 

![lalala](https://cloud.githubusercontent.com/assets/18266371/21393528/d15cf542-c762-11e6-875a-d952cd47e712.png)

This is the original star icon:
![star_filled](https://cloud.githubusercontent.com/assets/18266371/21393552/ea03af3c-c762-11e6-96cc-a145dd9fef86.png)

**Comment by davidvasquezr** [comment]
Now, I'm trying with SetTitleIcon but it does not work, this puts an icon replacing the title text. I forgot to say that the problem occurs only in iOS, in Android, it works fine.

`NavigationPage.SetTitleIcon(this, "star_filled.png");`

![lalala](https://cloud.githubusercontent.com/assets/18266371/21402768/02124c62-c788-11e6-896b-96bad3c86016.png)

**Comment by Goldstrike** [comment]
@davidvasquezr 
Hi David, could you explain me how you did to display the TitleIcon on Android?
Did you use this?
```
<ImageView
        android:src="@drawable/my_logo"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
/>
```

**Comment by dirivero** [comment]
Xamarin forms now provides a nice way of adding any Xaml as a title view:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical#displaying-views-in-the-navigation-bar
