### ISSUE TITLE
Java.Lang.UnsupportedOperationException: Can't convert to color: type=0x1

### ISSUE THREAD

**Issue by henriquedrumond** [UXDivers/Grial-UI-Kit-Support#130]
Hi,

I tried install the Grial UI Kit in my Samsung Galaxy Tab E. I am using Visual Studio with Android 4.4 - Api 19 and this error is informed to me.

What happens?

**Comment by jpbrocca** [comment]
Hi @henriquedrumond,

What is the error you get?

**Comment by henriquedrumond** [comment]
This error is that title of this message.

**Comment by jpbrocca** [comment]
Yes, I needed more details to be sure but take a look at the following issue:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/124

If your error is like that then please send an email to hello@uxdivers with your purchase info (name, order number, etc.) so we can send you the fix.

Thanks,
JP

**Comment by henriquedrumond** [comment]
@jpbrocca I sent this email. Tks a lot.

**Comment by henriquedrumond** [comment]
The update resolved this problem. Tks a lot!
