### ISSUE TITLE
App crashes frequetly

### ISSUE THREAD

**Issue by adeoriolowo** [UXDivers/Grial-UI-Kit-Support#131]
The app i am developing crashes very frequently with no apparent reason, the sample demo that ships with the kit also exhibit same problem. Please what should i do?

**Comment by jpbrocca** [comment]
Hi @adeoriolowo,
can you provide more details?

- What devices are you using?
- Which platform are you testing with?
- Which is your Grial version?
- It happens on the same page or randomly?

Thanks,
JP

**Comment by adeoriolowo** [comment]
- Visual Studio Emulator for Android was used (API Level 19 and 23)
- The Testing is done using Visual Studio 2015
- The Grail  Version is 1.5.0
- The App never goes beyond the Splash screen

**Comment by jpbrocca** [comment]
Hi @adeoriolowo,

I think your issue could be related to this:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/61

Which version of Xamarin Forms are you testing with?
If that is the case then updating to latest version of Xamarin Forms package should fix that.

Best,
JP

**Comment by jpbrocca** [comment]
Hi @adeoriolowo,
Did you try with the above link?

Best,
JP

**Comment by dirivero** [comment]
I'm closing this as we didn't get further information and it's very old. Feel free to contact us again if you need help.
