### ISSUE TITLE
GridOptionsView ItemsSource databinding does not work.

### ISSUE THREAD

**Issue by IDispose** [UXDivers/Grial-UI-Kit-Support#132]
I am using Grial kit version 1.2
My View Model has an ObservableRangeCollection property named MyItems that's bound to the GridOptionsView's ItemsSource property. In the codebehid for the view, I override the OnAppearing event and execute a method to load the collection. However this does not populate the template items.

If I change the MyItems type to a simple List and hardcode the List in the property declaration, the grid view correctly binds the items. 

Upgraded to version 1.5 and still not luck.
DataBinding to ObservableCollection does not seem to work. 

Is this a bug?

**Comment by jpbrocca** [comment]
Hi @IDispose,
Is there any chance you could send me your sample to jpbrocca@uxdivers.com?

Meanwhile, @LeoHere is there any workaround for this that you can think of?

Regards and thanks,
JP

**Comment by LeoHere** [comment]
It is a bug indeed. I will work on this and let you know as soon as it is done.

**Comment by jpbrocca** [comment]
Hi @IDispose, how are you?

I have the fix made by @LeoHere.

Can you send an email to:
hello@uxdivers.com
...with your purchase info (order number, name, date, etc) so I can send you the fix?

Regards and thanks,
JP

**Comment by IDispose** [comment]
Thanks @LeoHere for the fix. @jp I'll send the email 

Looking forward to checking out the fix

**Comment by IDispose** [comment]
This issue has been revolved with the build sent to me.
