### ISSUE TITLE
I keep getting exception once I run the project

### ISSUE THREAD

**Issue by danialbakhsheshi** [UXDivers/Grial-UI-Kit-Support#133]
I keep getting this exception when I run my project and there is no build errors
Xamarin.Forms.Xaml.XamlParseException: Position 158:13. Can't resolve artina:TableViewProperties

**Comment by jpbrocca** [comment]
Hi,
Can you provide more info?
- which xamarin forms version are you using?
- which is your Grial version?
- does this issue happen on our sample or un your app?
- are you on an emulator or a real de vice?

Thanks!
JP

**Comment by dirivero** [comment]
I'm closing this it's very old and no further info was provided.
