### ISSUE TITLE
Push notification error 

### ISSUE THREAD

**Issue by mostafamarji** [UXDivers/Grial-UI-Kit-Support#134]
I am integrating push notification using azure push notification  , when I click on the notification I got this error  `Java.Lang.IllegalStateException: Activity has been destroyed` . After investigation about the error I found that Grial library is the problem when I remove the dll error is gone. 

Thank you for wasting my time on this silly bug , and I hope you fix it as soon as possible.

My code for push notification is based on this link : https://theconfuzedsourcecode.wordpress.com/2015/06/19/so-i-just-implemented-push-notifications-in-awesome-xamarin-forms/

**Comment by jpbrocca** [comment]
Hi @mostafamarji,
is there any chance you could send us a sample with the error so we can move faster with the fix?

Best,
JP

**Comment by LeoHere** [comment]
Also, 
1) what version of XF are you using?
2) besides removing the references to Shared assemblies, what else did you commented/removed? I mean custom renderers, commented all App.xaml, etc

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for a couple of years.
