### ISSUE TITLE
The name 'AssemblyGlobal' does not exist in current context - Sample App

### ISSUE THREAD

**Issue by spinteractive** [UXDivers/Grial-UI-Kit-Support#136]
Hello,
Trying to build sample and I am stuck on this. Any ideas what to do?
Screenshot .. 
![2017-02-09 4](https://cloud.githubusercontent.com/assets/20608738/22799053/57f35d80-eed2-11e6-9f22-e0275c6518d6.png)

**Comment by spinteractive** [comment]
I found it. It was a pathing issue. Could not find the UXDriver.Artina DLL cause I moved things around a bit.

**Comment by jpbrocca** [comment]
Hi @spinteractive,

I was going to tell you about the last error which could be causing issues, but you were faster than me :)

Please remember to close bugs to help us keeping things tidy.

Thanks!
JP

**Comment by spinteractive** [comment]
Working through it all. Thanks for your fast support!

**Comment by jpbrocca** [comment]
You are welcome :)
