### ISSUE TITLE
<artina:GridOptionsView  - properties help

### ISSUE THREAD

**Issue by spinteractive** [UXDivers/Grial-UI-Kit-Support#137]
Hello,
I want the text to be near the bottom. Here's it's in the center. How would I do that?

Also, the BackgroundColor property makes it kinda dark. If I remove it it becomes very light. How do I just make it normal?

<artina:GridOptionsView
        ColumnCount="2"
        RowCount="3"
        ColumnSpacing="0"
        RowSpacing="0"
        Padding="0"
        VerticalOptions="FillAndExpand"
        ItemsSource="{Binding Items}">
            <artina:GridOptionsView.ItemTemplate>
              <DataTemplate>
                <uikit:DashboardItemTemplate
                    ShowBackgroundImage="true"
                    ShowBackgroundColor="false"
                    ShowiconColoredCircleBackground="false"
                    BackgroundColor="Black"
                    TextColor="White"
                    />
              </DataTemplate>
            </artina:GridOptionsView.ItemTemplate>
          </artina:GridOptionsView>

![image](https://cloud.githubusercontent.com/assets/20608738/22812283/d63c0676-ef11-11e6-9850-055d9e4778f2.png)

**Comment by jpbrocca** [comment]
Hi @spinteractive, how are you?
Great job! It is looking awesome! :)

You need to find the template for this (`DashboardItemTemplate.xaml`).
This file is located inside the folder:
```
Views
  L Dashboards
    L Templates
       L DashboardItemTemplate.xaml
```

Once you open that file you will get access to the whole XAML for this template, then you could change whatever you need. 

Also depending on what your needs are, you can find the associated styles and only affect those without changing the template.

Best,
JP

**Comment by spinteractive** [comment]
Perfect go it thank you!
