### ISSUE TITLE
Added Gorilla Player support / SampleData.json file added to improve preview

### ISSUE THREAD

**Issue by JarJarBinkz** [UXDivers/Grial-UI-Kit-Support#14]
I have found in the version 1.2.0 no sampledata.json file . Therefore, the Gorilla player shows me no data.

**Comment by jpbrocca** [comment]
Hi @JarJarBinkz, thanks for reporting this issue.

While we find the cause of this issue, here is the missing file:
[SampleData.zip](https://github.com/UXDivers/Grial-UI-Kit-Support-And-Issues/files/105269/SampleData.zip)

Regards and thank you,
JP

**Comment by JarJarBinkz** [comment]
Thank you and best regards

**Comment by JamesPetras** [comment]
Is there any reason for naming differently lists of date to actual page names. Out of box when you start the Grial project with Gorilla player it will not work on e.g. ArticlesFeedPage.xaml as in the SamplesData.json array is named ArticlesFeed.xaml.

**Comment by jpbrocca** [comment]
Hi @JamesPetras, how are you?

No, there should not be different names than the pages, so you are right and thanks for letting me know about this issue.
I think there was an issue with the merge.

Please use the file attached instead (remember to rename it to SampleData.json).

Regards and thanks,
JP

[SampleData.json.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/454380/SampleData.json.txt)

**Comment by JamesPetras** [comment]
Thank you!

**Comment by jpbrocca** [comment]
You are welcome :)
I will let this issue open in case anyone el se wants to get the file.

Best,
JP
