### ISSUE TITLE
How do I change the global font to calibri?

### ISSUE THREAD

**Issue by spinteractive** [UXDivers/Grial-UI-Kit-Support#144]
How do I change the global font to calibri?

**Comment by jpbrocca** [comment]
Hi @spinteractive,
Basically, you will need to add the font you want to your projects and depending on the platform you will need to go a little bit further (iOS is easier, in Android you will need to add it to the `CustomFontLabel.cs` renderer file).

Check this document:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/How-to-add-icons-to-your-project

Once the font is available you can add it to `App.xaml` theme for instance to control all the Label elements. Remember to use the right FontFamily name.

Here is a very nice article -more general- about this topic:
https://blog.verslu.is/xamarin/xamarin-forms-xamarin/using-custom-fonts-on-ios-and-android-with-xamarin-forms/

Best,
JP
