### ISSUE TITLE
Upgrade Grial V2

### ISSUE THREAD

**Issue by adamlonsdale** [UXDivers/Grial-UI-Kit-Support#147]
Hi,

I purchased a licence fro Grial, but this has never made it into a released app as I ran into a number of problems and missing features. I was wondering if you would be able to upgrade my single licence to Grial V2 somehow so I can start evaluating it again. 

Thanks

**Comment by jpbrocca** [comment]
Hi @adamlonsdale,

please send an email with your order detail to hello@grialkit.com.

Thanks!
JP

**Comment by adamlonsdale** [comment]
Just as a side note - I've emailed a couple of times about this but not had a reply so I fear my emails may be going to your spam folder. I sent it from a @me.com email address.
