### ISSUE TITLE
Toolbar in Social Pages - Change text

### ISSUE THREAD

**Issue by stringo** [UXDivers/Grial-UI-Kit-Support#148]
Hi, 

I'm using the social page in a project. I have a doubt in the tool bar, it uses a label with FormattedText however I need update the text of the second Span. I'm using MVVM, I know that I can't bind the Text (as per Xamarin Forms design). Is there a way to preserve the style and be able to bind the text property?

Maybe some XAML changes are needed (removing the spans and add two labels or something like that), but I'm not good with it. Could you please help me?

Thanks in advance.

```
<Label Grid.Column="3" 
	VerticalTextAlignment="Center"
	HorizontalTextAlignment="Center">
	<Label.FormattedText>
		<FormattedString>
			<FormattedString.Spans>
				<Span 
					Text="&#xf006; " 
					FontSize="{StaticResource BaseFontSize}" 
					ForegroundColor="{StaticResource AccentColor}" 
					FontFamily="{x:Static artina:FontAwesome.FontName}" />
				<Span 
					Text="2963" 
					FontSize="{StaticResource BaseFontSize}"  
					ForegroundColor="White" />
			</FormattedString.Spans>
		</FormattedString>
	</Label.FormattedText>
</Label>
```

**Comment by jpbrocca** [comment]
Hi @stringo,
Yes, you will need to replace each <Span> with a single <Label> to get the bindings working.
Also, you will need some layout element to make the labels look OK and replace the <Span> properties with their equivalent for <Label>...something like the following:

```
<StackLayout
    Grid.Column="3"
    Orientation="Horizontal"
    VerticalOptions="Center"
    HorizontalOptions="Center"
    Spacing="0">

    <Label
        VerticalTextAlignment="Center" 
        HorizontalTextAlignment="Center"
        Text="&#xf006; "
        FontFamily="{ x:Static artina:FontAwesome.FontName }"
        TextColor="{ DynamicResource AccentColor }"/>

    <Label
        VerticalTextAlignment="Center" 
        HorizontalTextAlignment="Center"
        Text="{ Binding YOUR_BINDING_HERE }"
        FontSize="{ StaticResource BaseFontSize }"  
        TextColor="White" />
        
</StackLayout>
```

Best,
JP

**Comment by stringo** [comment]
Thanks! @jpbrocca 

One more question:

I just bought Grial UI last week. I can see however, that there's an upgrade to V2 and I would like to install it. Are there any specific guidelines to upgrade to V2? are there any breaking changes?

Congratulations guys for the V2!

**Comment by jpbrocca** [comment]
Hi @stringo,

If the proposed fix worked please remember to close this issue.

About your second questions just send an email to hello@grialkit.com with your order details and we will help you.

Best,
JP
