### ISSUE TITLE
"InitializeComponent does not exists in the current context" when opening starter project

### ISSUE THREAD

**Issue by SamyCode** [UXDivers/Grial-UI-Kit-Support#154]
Hi UXDivers

We just bought your pro license. When I open the starter project, it compiles and run, but for some reason, if I go to the App.xaml on the Portable project, the InitializeComponent method is underlined red and the error says that it doesn't exists. Still, the project seems to run fine.

What is the use of this method and why the project runs fine without it? How do I know that this will not be a problem in the future?

Thanks

**Comment by jpbrocca** [comment]
Hi @SamyCode,

Could you provide more info:
- about your IDE (are you on Visual Studio or Xamarin Studio?...version?)
- is this happening in Android or iOS, or in both?
- did you try with Clean and rebuild, then running the project again?

Sometimes this error is displayed but it is just a false alarm from the IDE. 

Best,
JP

**Comment by johncdoherty** [comment]
Sounds like the xaml and xaml.cs namespaces don't match. You might want to confirm the values you set when you set up the project in the admin portal

**Comment by SamyCode** [comment]
@johncdoherty, the namespaces between the .xaml and .cs matches :/

@jpbrocca heres the info that you need:

1. This happens on Visual Studio 2015 on a Windows 10 64bits machine. I have Visual Studio 2017 installed too. I don't know if it would happen on Xamarin.

2. This is happening on the portable project.

3. We definitely tried to clean and rebuild the solution, without avail. Actually it builds and runs without problem, but I don't even know how that's possible considering that the red line under InitializeComponent() and the error persists. My issue here is regarding of what's coming next. How much of a problem this could be in the future?

Looking forward to your answer.

**Comment by jpbrocca** [comment]
Hi @SamyCode,

thanks for the info.
To my knowledge this is something that is more a false alarm since you can build and run. This is happening in VS more than in XS.

Take a look at comment 26 from Jason Smith on this bug report from Xamarin about this issue:
https://bugzilla.xamarin.com/show_bug.cgi?id=33181

You can also find there some possible workarounds.
I don't think this should be a problem in the future...we had to live with this issue some time ago on some projects.
In any case this is more a xamarin issue.

Best,
JP

**Comment by jpbrocca** [comment]
Found some more possible workarounds here:
https://forums.xamarin.com/discussion/68679/the-name-initializecomponent-does-not-exist-in-the-current-context

**Comment by SamyCode** [comment]
@jpbrocca the workaround in the last link worked. It also removed the errors on my Gorilla Player. Many thanks.

**Comment by SamyCode** [comment]
@jpbrocca I still have problems trying to install the new Gorilla though. More info about the problem is written in the email that I'm sending to you now.

**Comment by jpbrocca** [comment]
@SamyCode, 
Could be interesting that you share your workaround so other guys could also benefit from your experience :)

I am answering your email now, but I suggest you take a look at Gorilla support site to find related solutions:
https://github.com/UXDivers/Gorilla-Player-Support

Thanks,
JP

**Comment by M-caves** [comment]
While Creating New Project, on the area where it provides to select android, ios or both, there at right side there will be Code Sharing Strategy. On that code sharing strategy select .Net Standard. Then this problem will be solved. Thank You!

**Comment by ajaykeshri** [comment]
The namespace and class names need to match so they are both part of a partial class

namespace XXX
{
///


/// Interaction logic for MainWindow.xaml
///
public partial class MainWindow
{
//...
}
}
