### ISSUE TITLE
Fatal error at build time for .NET Standard 1.4 project

### ISSUE THREAD

**Issue by jgoelten** [UXDivers/Grial-UI-Kit-Support#155]
Hello UXDivers

I'm facing a problem when integrating GrialKit (V2.0.35) into my own solution. The build fails with a fatal error. Its origin is coming from the UxDivers.Artina.Shared.targets build task **PropagateThemeTask**. I've added all resources according to the starter demo. The main difference is that I'm targeting the new .NET Platform Standard (.NET Standard 1.4) project type instead of the previous Portable Class Library using profile descriptors.

Have you already tested it using the .NETStandard library type? It seems as if the build tasks fails due to some project type differences.

```
4>Target "GrialTheme: (TargetId:164)" in file "C:\repos\DemoApp\DemoApp_Client\packages\UXDivers.Artina.Shared.2.0.35\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\UXDivers.Artina.Shared.targets" from project "C:\repos\DemoApp\DemoApp_Client\DemoApp.Client.Droid\DemoApp.Client.Droid.csproj" (target "Build" depends on it):
4>Using "PropagateThemeTask" task from assembly "C:\repos\DemoApp\DemoApp_Client\packages\UXDivers.Artina.Shared.2.0.35\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\UXDivers.Grial.Build.Tasks.dll".
4>Task "PropagateThemeTask" (TaskId:92)
4>  Task Parameter:SourceProject=C:\repos\DemoApp\DemoApp_Client\DemoApp.Client.Droid\DemoApp.Client.Droid.csproj (TaskId:92)
4>  [Grial] Initiating Syncrhonization for project 'C:\repos\DemoApp\DemoApp_Client\DemoApp.Client.Droid\DemoApp.Client.Droid.csproj' (TaskId:92)
4>  [Grial] Error occurred 'Fatal error, see inner exception for details.' StackTrace:    at UXDivers.Daas.Engine.EngineExecutor.ExecuteCommands(CommandBase[] commands, ExecutionContext context)
4>     at UXDivers.Daas.Engine.EngineExecutor.Execute(ExecutionSession session, Dictionary`2 sideEnvironment, Boolean ignoreSessionEnv, String[] variablesToKeep)
4>     at UXDivers.Grial.Build.Tasks.PropagateThemeTask.Execute() (TaskId:92)
4>  [Grial] Error occurred 'Fatal error, see inner exception for details.' - StackTrace:    at UXDivers.Daas.Engine.EngineExecutor.ExecuteCommands(CommandBase[] commands, ExecutionContext context)
4>     at UXDivers.Daas.Engine.EngineExecutor.Execute(ExecutionSession session, Dictionary`2 sideEnvironment, Boolean ignoreSessionEnv, String[] variablesToKeep)
4>     at UXDivers.Grial.Build.Tasks.PropagateThemeTask.Execute() (TaskId:92)
4>MSBUILD : Themes error Grial: Fatal error, see inner exception for details. (project 'C:\repos\DemoApp\DemoApp_Client\DemoApp.Client.Droid\DemoApp.Client.Droid.csproj').
4>  [Grial] Terminating Syncrhonization (TaskId:92)
4>Done executing task "PropagateThemeTask" -- FAILED. (TaskId:92)
4>Done building target "GrialTheme" in project "DemoApp.Client.Droid.csproj" -- FAILED.: (TargetId:164)
```

Thanks for your support!
Jan

**Comment by jpbrocca** [comment]
Hi @jgoelten,

I confirm it is not tested under .Net Standard 1.4.
Are you trying to integrate Grial over an existing project?

Best,
JP

**Comment by johncdoherty** [comment]
@jgoelten I'm able to compile the full starter project using .NET Standard 1.4. Be sure you have the following in your project.json:
`"frameworks": {
    "netstandard1.4": {
      "imports": [        
        "portable-net45+win8+wp8"
      ]
    }
  }`

Also, I do notice several (150 or so) warnings after migrating to .NET Standard. The application runs fine, but I'm apprehensive that runtime errors could occur in certain scenarios.

@jpbrocca do you have any suggestions on how to avoid the warnings like below?
Thanks,
John

`Warning XA0106: Skipping MyApp.Resource.Attribute.mediaRouteControllerSecondaryTextStyle. Please check that your Nuget Package versions are compatible. (XA0106) (DDMobile.Droid)`

**Comment by jpbrocca** [comment]
Hi @johncdoherty,
thanks for your help!

About warnings: we will be checking Grial over .Net Standard 1.4 and will review these warnings. We will let you know our findings/solutions.

Best regards and thanks!
JP

**Comment by johncdoherty** [comment]
Thanks @jpbrocca, after looking at this further the warnings show up after updating the Xamarin.Android.Support packages from 23.3.0 to 25.1.1. I'm going to post a separate issue

**Comment by jgoelten** [comment]
@jpbrocca thanks for your quick answer. Yes, I'm trying to integrate Grial over an existing project.
@johncdoherty the framework imports that you mentioned are already part of the json since it would not allow me to reference any portable packages in my netstandard project. I'll take a close look in my integration part since you could manage to get the starter sample work. Thanks for your help.

**Comment by jgoelten** [comment]
@johncdoherty I was able to run the starter project by converting the original portable into a netstandard 1.4 project. Unfortunately I am still having issues when integrating grialkit into my own solution. I've crosschecked all resources, styles, namespaces, folder hierarchies and settings with the ones from the starter project. But still I'm getting the following fatal error:
```
3>MSBUILD : Themes error Grial: Fatal error, see inner exception for details. (project 'C:\repos\.....\DemoApp.Client.csproj').
```

**Reproduce Issue**
I was able to reproduce the same issue in the starter project by simply unloading and renaming the iOS project folder. In that case the build task seems not to find a kind of theme-reference in the iOS project and crashes. In my own project I checked twice if the Colors.xml (Droid) and ThemeColors.cs (iOS) are present with the corresponding build action configuration.

**Theme.json**
I also followed your instructions on _Theme Compilation Troubleshooting_ without success. Adding the AppXAMLPath, AndroidProjectPath and iOSProjectPath did not make any difference to the build process.

Do you have further information what could lead into this error? It would be helpful to know, what the build task is actually looking for in the other native projects for Droid and iOS.

Thanks for your help!
Jan

**Comment by johncdoherty** [comment]
@jgoelten  do you by chance have any solution folders in your solution?… I recall having an issue with that and ended up removing them all when I started

**Comment by LeoHere** [comment]
@jgoelten, @johncdoherty can you confirm the issues reported here are fixed? Please, close the issue if so.

**Comment by jgoelten** [comment]
@LeoHere I can confirm that the reported issues are fixed. The portable library can be successfully replaced using a plain netstandard 1.4 project. Thanks for your demand.
