### ISSUE TITLE
Appearance.cs

### ISSUE THREAD

**Issue by adamlonsdale** [UXDivers/Grial-UI-Kit-Support#159]
Hello,

The documentation specifies Appearance.cs needs to be copied in on the iOS side, but my starter / full projects don't contain such a file. It also says I need to call Appearance.Configure() but as I don't have the file I cannot call that. 

Thanks

**Comment by jpbrocca** [comment]
Hi @adamlonsdale,

It would be helpful to understand what is your scenario:
it looks like if you are migrating from Grial 1.5 to Grial 2.0?...if that is not the case then please explain.

About your questions:

- `Appearance.cs` was used in Grial 1.5 and it has been renamed to `ThemeColors.cs`
- You need to call it from AppDelegate.cs with this code:
```
UXDivers.Artina.Shared.GrialKit.Init(new ThemeColors(), "UXDivers.Artina.Grial.GrialLicense");
```
Let me know if you need more help.

Oh! And thanks for helping me to find the outdated block on the docs! 

Cheers,
JP

**Comment by adamlonsdale** [comment]
Cool, I already had the ThemeColors in there, so I guess it was just outdated docs, thanks!
