### ISSUE TITLE
Mac OS - Error on new Grial Starter download on Xamarin Studio and Visual Studio

### ISSUE THREAD

**Issue by ombinar** [UXDivers/Grial-UI-Kit-Support#161]
Error Grial: iOS theme colors definition file (ThemeColors.cs) not found in project '/Users/xxx/Desktop/Grial-2/app1/app1.csproj'. (project '/Users/xxx/Desktop/Grial-2/app1/app1.csproj'). (Grial) (app1) Themes

This is from Grial Starter.

**Comment by LeoHere** [comment]
@ombinar does this error occurs in the Starter project without any modification?

The error you are experiencing is related to a build task (called ```PropagateThemeTask```)  included by Grail Nuget packages.

There is a new version of the Nuget packages (currently in pre release). These packages includes several changes to the ```PropagateThemeTask``` like:
- reimplemented theme sync to support Shared projects too
- improved error reporting
- improved logging/feedback

The new version is available in the PreRelease channel. You will need the "Show pre-release packages" checkbox to be checked in order to install them. 

Can you please update your packages with this new release? You should update them across the all your projects.

**Comment by ombinar** [comment]
Sorry I'm new to Mac and can't find where to switch the Nuget mode. I know how to do this in Windows.

**Comment by ombinar** [comment]
Well I found out that the ThemeColor.cs is under iOS project and the error says can't find it under PCL project. So I moved it under PCL and got a fatal error now -

Building: xxx.iOS (Debug|iPhoneSimulator)
Build started 4/7/2017 8:29:03 AM.
__________________________________________________
Project "/Users/user/Desktop/Grial-2/xxx/xxx.csproj" (Build target(s)):

Target GrialTheme:
    [Grial] Initiating Syncrhonization for project '/Users/user/Desktop/Grial-2/xxx/xxx.csproj'
    [Grial] Error occurred 'Fatal error, see inner exception for details.' StackTrace:   at UXDivers.Daas.Engine.EngineExecutor.ExecuteCommands (UXDivers.Daas.CommandBase[] commands, UXDivers.Daas.Engine.ExecutionContext context) [0x00172] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session, System.Collections.Generic.Dictionary`2[TKey,TValue] sideEnvironment, System.Boolean ignoreSessionEnv, System.String[] variablesToKeep) [0x001ab] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session, System.Collections.Generic.Dictionary`2[TKey,TValue] sideEnvironment, System.Boolean ignoreSessionEnv) [0x00001] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session) [0x00001] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Grial.Build.Tasks.PropagateThemeTask.Execute () [0x00044] in <aaba165818ee4e029748d7510ce82eb4>:0
    [Grial] Error occurred 'Fatal error, see inner exception for details.' - StackTrace:   at UXDivers.Daas.Engine.EngineExecutor.ExecuteCommands (UXDivers.Daas.CommandBase[] commands, UXDivers.Daas.Engine.ExecutionContext context) [0x00172] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session, System.Collections.Generic.Dictionary`2[TKey,TValue] sideEnvironment, System.Boolean ignoreSessionEnv, System.String[] variablesToKeep) [0x001ab] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session, System.Collections.Generic.Dictionary`2[TKey,TValue] sideEnvironment, System.Boolean ignoreSessionEnv) [0x00001] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session) [0x00001] in <7b14a7d3b37f43c288962017a6cc1745>:0
      at UXDivers.Grial.Build.Tasks.PropagateThemeTask.Execute () [0x00044] in <aaba165818ee4e029748d7510ce82eb4>:0
    MSBUILD : Themes error Grial: Fatal error, see inner exception for details. (project '/Users/user/Desktop/Grial-2/xxx/xxx.csproj').
    [Grial] Terminating Syncrhonization
Done building target "GrialTheme" in project "xxx.csproj" -- FAILED.

Done building project "xxx.csproj" -- FAILED.

Build FAILED.

MSBUILD : Themes error Grial: Fatal error, see inner exception for details. (project '/Users/user/Desktop/Grial-2/xxx/xxx.csproj').
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.09

---------------------- Done ----------------------

Build: 1 error, 0 warnings

**Comment by johncdoherty** [comment]
You can add Nuget sources under Xamarin Studio > Preferences. It's an application setting, not solution/project setting. I would suggest moving the ThemeColor.cs to where it originally was

**Comment by ombinar** [comment]
I had that already set and I moved the CS back.

Just a note, if I create new solution from a template and no issues. I have latest Xamarin Studio updates.

I still don't know how to switch to this mode:

> The new version is available in the PreRelease channel. You will need the "Show pre-release packages" checkbox to be checked in order to install them.

**Comment by jpbrocca** [comment]
Just go to a platform project (iOS for instance), then add nueget packages:

![image](https://cloud.githubusercontent.com/assets/15996999/24811860/3b211528-1b9e-11e7-8752-c681ed9c5467.png)

Then select on the dropdown your private source of Grial nugets that you configured on Grial Admin, and select the checkbox at the bottom:
![image](https://cloud.githubusercontent.com/assets/15996999/24811909/653cc9a6-1b9e-11e7-918e-b97673fbd62e.png)

Finally simply select the version you want to add:
![image](https://cloud.githubusercontent.com/assets/15996999/24812025/dcfbce24-1b9e-11e7-83a4-70b3aeb4d996.png)

**Comment by LeoHere** [comment]
@ombinar please try with version 2.0.43-RC

**Comment by ombinar** [comment]
Sorry I tried and still ThemeColors.cs not found error on Xamarin Studio.


Thanks,

Ricky Ombina

**Comment by LeoHere** [comment]
@ombinar are you getting the exact same error? Can you send me the ```.csproj``` of your PCL/Droid/iOS projects by email (l r o d r i g u e z at uxdivers.com)?

**Comment by robertmclaws** [comment]
@ombinar Updating to 2.0.50-RC fixed it for me. I would suggest moving the ThemeColors.cs file back to the iOS project and rebuild the iOS project only.

**Comment by jpbrocca** [comment]
Hi @ombinar, how are you?
This issue is fixed on `2.0.52.0` released today.

For more info, please check:
http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html

I am closing this issue to keep things tidy, but feel free to reopen as necessary.
Thanks!

JP
