### ISSUE TITLE
Generated Project Namespaces Are Incorrect

### ISSUE THREAD

**Issue by robertmclaws** [UXDivers/Grial-UI-Kit-Support#163]
There is a problem in the namespace customization from the online portal. These are my settings in the portal:

![image](https://cloud.githubusercontent.com/assets/1657085/24841208/5ee0bed2-1d4c-11e7-9bb0-a395c1b58c98.png)

This is the unmodified, generated result: 
![image](https://cloud.githubusercontent.com/assets/1657085/24841213/77e98184-1d4c-11e7-836a-16e8ee4db44d.png)

And these are the project settings:
![image](https://cloud.githubusercontent.com/assets/1657085/24841219/ab9c4fb6-1d4c-11e7-9c5e-1167f4db8f67.png)

I believe this is causing several problems relating to other active tickets. I opened its own ticket so the resolution can be tracked.

Thanks!

**Comment by wiltwitt** [comment]
This is exactly the problem I have as well.

**Comment by LeoHere** [comment]
@robertmclaws @wiltwitt thanks for reporting this. We will fix this ASAP.

**Comment by jpbrocca** [comment]
Hi all,
this issue is fixed on 2.0.52.0 released today.

For more info, please check:
http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html

I am closing this issue to keep things tidy, but feel free to reopen as necessary.
Thanks!

JP
