### ISSUE TITLE
Issue with compilation on Full Sample project

### ISSUE THREAD

**Issue by robertmclaws** [UXDivers/Grial-UI-Kit-Support#167]
In `PCL/Views/Walkthroughs/Templates/WalkthroughGradientItemTemplate.xaml` There are two controls with `id="img"`, one on like 14 and one on line 59. I would suggest changing line 59 to read `id="circle_img"` or something.

This prevents compilation after #164 was fixed.

Thanks!

**Comment by LeoHere** [comment]
@robertmclaws yes you are right. Actually you can remove the ```id="img"``` from the ```CircleImage```. This issue will be fixed in the next release.

**Comment by jpbrocca** [comment]
@LeoHere, is this fix available on 2.0.52.0 released today?

**Comment by LeoHere** [comment]
Yes it is. Closing the issue.
