### ISSUE TITLE
Unable to compile Full version due to the ThemeColors.cs 

### ISSUE THREAD

**Issue by didiermook** [UXDivers/Grial-UI-Kit-Support#168]
Hi there

In spite of all the troubleshooting recommendations, the full version is not working. So we were not able to use the app. How can we get refunded?

**Comment by jpbrocca** [comment]
Hi @didiermook,
sorry about that.

Did you check the fix from this thread?
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/164

Best,
JP

**Comment by didiermook** [comment]
Hi JP

We tried and seem to have other errors popping in. We really do not have time to start fixing this especially if that license is available on for one app.

At this stage we would like to ask if we can be refunded and what this process will require from us.

Please let me know.

Thanks,
Didier

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by jpbrocca** [comment]
Hi @didiermook,

Today we released version 2.0.52.0 which fixes this issue. More info here:http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html

Could you give it a try and let us know? If it you still want to be refunded, then please send an email to hello@uxdivers.com with your purchase number so we can process the refund.

Best regards and thank you,
JP
