### ISSUE TITLE
Cannot build starter project even after upgrading nuget packages to 2.0.50-RC.

### ISSUE THREAD

**Issue by MrRenaud** [UXDivers/Grial-UI-Kit-Support#170]
I first had the issue #166 and I followed the solution by upgrading to 2.0.50-RC in both three projects.
Now I'm facing an other issue. I can't build the PCL and have several build errors : 

- The "PropagateThemeTask" task could not be initialized with its input parameters.
- The "FailOnError" parameter is not supported by the "PropagateThemeTask" task. Verify the parameter exists on the task, and it is a settable public instance property.

This happens on Visual Studio 2017, with the starter project I just unzipped.

**Comment by LeoHere** [comment]
@MrRenaud so far we were not able to reproduce the issues you mentioned. We have just released an update ```2.0.52.0``` for Nuget packages and Grial sample app. Can you please download the Starter/Full projects again from the Admin site and tell us if you are still experiencing the issues you mentioned?

**Comment by MrRenaud** [comment]
Thanks, it solved the issue!
