### ISSUE TITLE
Moving from trial to purchased version

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Grial-UI-Kit-Support#172]
We've had a trial which has now expired - so we've purchased a Standard version, and downloaded the zip.

How do we apply the purchased version/licence to our _Existing_ application?

**Comment by LeoHere** [comment]
@james-lavery if the App Name (iOS and Android), android package name and bundle identifier in you solution matches those set in the Admin site before download the license, you just need to replace the old ```GrialLicense``` files with those you just downloaded. Once you do this, be sure to do a clean & rebuild.
