### ISSUE TITLE
Message Chat List - iOS Keybord overlay on text field

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#173]
Hi,

I am comparing the message chat list templates between the iOS and Android. Notice that the Text Field (Type your message...) is covered by the keyboard on iOS but not Android.

It this something to be fixed?  

**Screenshot on iOS**
![ios](https://cloud.githubusercontent.com/assets/23342040/25300509/728939ea-2743-11e7-8978-0bac77b897e9.png)

**Screenshot on Android**
![android](https://cloud.githubusercontent.com/assets/23342040/25300517/8d83b02c-2743-11e7-8e77-d1eb0dac1e84.png)

Thanks,
Dennis

**Comment by denfung** [comment]
Hi @JP & Grial Team,

Would like to know is this the design of the Grial UI or a bug.

Any idea? Anyone has the same problem?


Please advice.
Dennis

**Comment by johncdoherty** [comment]
I wouldn't mind knowing how to fix this also, though I anticipate that it's a platform (Xamarin) issue. Any workarounds?

**Comment by joselacerdasoares** [comment]
I have the same problem.
Grial???

**Comment by dirivero** [comment]
Hi, 

Can you try including the following plugin in your iOS project that fixes this issue with Xamarin.Forms + iOS?

https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/KeyboardOverlap

Thanks
Diego

**Comment by joselacerdasoares** [comment]
Thanks Diego.
It Works.

[mail_ant]
