### ISSUE TITLE
Shared library support?

### ISSUE THREAD

**Issue by Jeremywhiteley** [UXDivers/Grial-UI-Kit-Support#174]
Can I use the grial ui as a Shared Library instead of a PCL?   We are using documentdb, which isn't supported as a PCL app yet with Xamarin forms.   Is there anything I need to do for a shared library?   Do you have an example as shared library?  

Thank you!

**Comment by jpbrocca** [comment]
Hi Jeremy,

Shared Projects are not officially supported. However, Grial should work in such context.
We will add support for shared projects in the future.

Best,
JP
