### ISSUE TITLE
GrialShapesFont not displayed!

### ISSUE THREAD

**Issue by maquiavelli** [UXDivers/Grial-UI-Kit-Support#177]
After updating the icons are not displayed.

**Comment by jpbrocca** [comment]
HI @maquiavelli,

Can you provide more info about your issue?
What have you updated and where?

Thanks,
JP

**Comment by Zoso221** [comment]
I also have this issue...

What appears to be japanese characters are rendered

![20170613_095511](https://user-images.githubusercontent.com/22526065/27086022-eb9fc62e-501e-11e7-9c87-af735c6ba769.jpg)

**Comment by LeoHere** [comment]
@Zoso221 can you share the XAML you are using to render those characters? What font is the ```Label``` using?

**Comment by Zoso221** [comment]
@LeoHere 

I have resolved it.  Gotta make sure the build action is set and the renderer is exported properly!

thank you
