### ISSUE TITLE
Masking on textbox

### ISSUE THREAD

**Issue by SamyCode** [UXDivers/Grial-UI-Kit-Support#179]
We were wondering if GRIAL has or you have in development any phone number masking for textboxes on Xamarin Forms. We really need this and we don’t find any mask from your product nor around the web. 

Any thoughts?

Regards

- Sam

**Comment by jpbrocca** [comment]
Hi @SamyCode,
no, we don't provide such control.

What is your target platform? I ask because I am sure I have seen this at least for iOS, so you could make a custom renderer for such case.

Best,
JP
