### ISSUE TITLE
.net standard library?

### ISSUE THREAD

**Issue by Jeremywhiteley** [UXDivers/Grial-UI-Kit-Support#181]
Is Grial compatible with the new .net standard library solution with Xamarin Forms?  We are using the new Azure ComosDB which is not compatible with a PCL solution with Xamarin Forms unfortunately.

**Comment by Jeremywhiteley** [comment]
?   Hello?  I am paid customer!

**Comment by LeoHere** [comment]
We don't officially support this yet. However, you should be able to use Grial in a .NET Standard project. The assemblies included in Grial dependencies are all PCLs libraries, thus you will need configure your .NET Standard project to support referencing non .NET Standard assemblies as explained [here](https://xamarinhelp.com/dot-net-standard-pcl-xamarin-forms/) and [here](https://xamarinhelp.com/visual-studio-2017-net-standard-xamarin/).

Hope it helps and sorry for the late response.
