### ISSUE TITLE
GrailKit portion of DLL not loading in project

### ISSUE THREAD

**Issue by frankdfitzgerald** [UXDivers/Grial-UI-Kit-Support#182]
I have all of the dependencies loaded but in both my IOS and android app UXDivers.Artina.Shared.GrialKit does not exist. I have tried using Nuget and I have tried using the direct DLLs in the starter application but there seems to be some other dependency that is not loading up or causing a problem. I was using the older version before I just bought the pro version and I removed all of the DLLs associated with the older version and re added them but that has not helped as well. Any help would be appreciated.

**Comment by frankdfitzgerald** [comment]
Attaching Screen shots of two projects with object browsers using the same DLL.
![does not have grailkit](https://cloud.githubusercontent.com/assets/28925741/26405922/ffc48dca-4096-11e7-83f8-7eb72257c84e.JPG)
![has grail kit](https://cloud.githubusercontent.com/assets/28925741/26405921/ffb485b0-4096-11e7-8891-df215ee83d6f.JPG)

**Comment by LeoHere** [comment]
I guess somehow you are still referencing the old assemblies. 

Please proceed as follows:
1. Remove all references to Grial Nuget Packages (if any) from all your projects.
2. Remove all references to Grial Shared individual assemblies (if any) from all your projects.
3. Perform a clean in the Solution.
4. Add the following Nuget Packages to:
    - PCL project. ```UXDivers.Artina.Shared``` (will automatically add ```UXDivers.Artina.Shared.Base```), ```UXDivers.Artina.Controls.Repeater```, ```UXDivers.Artina.Controls.Tab```.
    - iOS project. ```UXDivers.Artina.Shared``` (will automatically add ```UXDivers.Artina.Shared.Base```)
    - Droid project. ```UXDivers.Artina.Shared``` (will automatically add ```UXDivers.Artina.Shared.Base```)
5. Build your solution.

Now all Grial Shared dependencies should be in place and ```GrialKit``` should be available from your  ```AppDelegate.cs``` and ```MainActivity.cs```.

**Comment by thE-iNviNciblE** [comment]
i've the same problem i see under nuGet Packages the "UXDrivers.Artina.Shared" and "UXDrivers.Artina.Shared.Base" both are not available... under nuget but "UXDrivers.Effects" is available...

i can't restore the setup after downloading the grial ui kit... i can't compile anything!

How to get the right Package Source? 2.0.52 (Artina, it says installed, but not available)... can't find it under references to add.

**Comment by frankdfitzgerald** [comment]
Remove everything. If you had any local references to the first grail DLL anywhere in your project or packages make sure they are fully removed before starting again. Delete your bin and obj folders as well. Clean the solution and rebuild. I had a local ref to the old dll.

**Comment by LeoHere** [comment]
@thE-iNviNciblE are you migrating from Grial 1.5 (as @frankdfitzgerald) or are you having this issue with your brand new Grial 2.0 solution?

If it is the latter, did you configure the Grial Nuget Package Source? (See [Setting up UXDivers nuget source)](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-setting-up-uxdivers-nuget-source)

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it if you need so.
