### ISSUE TITLE
UXDivers.Artina.Shared.Base and UXDivers.Artina.Shared not available???

### ISSUE THREAD

**Issue by thE-iNviNciblE** [UXDivers/Grial-UI-Kit-Support#185]
Hello,
i'm new to grial ui kit 2.0 i've downloaded the sample files both starter and full aren't working!

i've setup the private nuget package source http://user:pwd@nuget.uxdrivers.com/grial/  (http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-setting-up-uxdivers-nugget-source) - under visual studio no password promt are there, with or without username and password i can't access Artina 2.0.52. In Nuget it is said the the package isn't available. 

How to solve this problem?

i can't compile because of broken references (not existing).

i would be glad if someone knows the solution!

**Comment by LeoHere** [comment]
Hi! Please try registering the Package Source without credentials, i.e. http://nuget.uxdivers.com/grial as shown in the image bellow:

![image](https://cloud.githubusercontent.com/assets/16000584/26493406/c1766c46-41ef-11e7-9d6f-dc1775a1038d.png)

You will be prompted for credentials once you try to access the Package Source.

**Comment by johncdoherty** [comment]
You can also define your own Nuget.config file with the password embedded
