### ISSUE TITLE
Can't solve to give a chinese app name

### ISSUE THREAD

**Issue by shengguow** [UXDivers/Grial-UI-Kit-Support#186]
Hello JP,
I can't change my app name to a Chinese name, could you fix this issue?

You can take a look at the issue by viewing this photo:
https://mupaste.com/HHYpp7Ji.png

(I can only use a English based app name for now.)

**Comment by LeoHere** [comment]
@shengguow the issue has been fixed and deployed to production. Please, perform a full page refresh before trying again.

**Comment by shengguow** [comment]
@LeoHere Thanks for the effort.
Now it's fine to update the app name in Grial Admin panel, but there is the other issue, I am can't update the new license file, got a "can't read griallicense...." error, could you provide the steps for updating a new license file?

**Comment by LeoHere** [comment]
Good!

You should replace the license file included in your Android and iOS project with the newly downloaded license. Make sure the license file (i.e. ```GrialLicense```) has build Action ```Embedded Resource``` and is included at the root of your Android&iOS project.

Also check that the app name / package name in your solution matches those specified in the Admin Portal. Please read the [License Troubleshooting](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-troubleshooting-license-issues) guide in the documentation for a detailed explanation.

**Comment by shengguow** [comment]
@LeoHere  Thanks!
It's working!

**Comment by shengguow** [comment]
Hello Leonardo,
Is it possible to change my app name, I would like to replace my app name “com.trisched” with the new one “com.trippertag”, could you help me? Thanks!

從 Windows 10 的郵件傳送

寄件者: Leonardo Rodríguez
傳送時間: 2017年5月30日 上午 12:57
收件者: UXDivers/Grial-UI-Kit-Support
副本: shengguow; Mention
主旨: Re: [UXDivers/Grial-UI-Kit-Support] Can't solve to give a chinese appname (#186)

Good!
You should replace the license file included in your Android and iOS project with the newly downloaded license. Make sure the license file (i.e. GrialLicense) has build Action Embedded Resource and is included at the root of your Android&iOS project.
Also check that the app name / package name in your solution matches those specified in the Admin Portal. Please read the License Troubleshooting guide in the documentation for a detailed explanation.

**Comment by LeoHere** [comment]
@shengguow, sorry I didn't understand the problem you are experiencing. When you said "I would like to replace my app name...", where are you trying to do that? In the admin? In your solution? What specific problem are you facing?

**Comment by shengguow** [comment]
I'm sorry it is not an issue. I'll send you an email later, 
I just reply the message via my outlook and it seems to be posted on here.

GitHub newbie....Sorry...
