### ISSUE TITLE
Xamarin.GooglePlayServices.Location does not support?

### ISSUE THREAD

**Issue by shengguow** [UXDivers/Grial-UI-Kit-Support#190]
Hello guys,
Recently, I tried to add a Google Location service to my app and I found that 
Xamarin.GooglePlayServices.Location seems not compatible with Grial, or I should say I can't upgrade my Xamarin.GooglePlayServices.Location to desired version, for example, the latest version of Google Play services that are compatible with Grial is 29.0.0.2, but when I installed Xamarin.GooglePlayServices.Location 29.0.0.2, everything looks fine, but my project can not be compiled with the component, to reproduce my issue by simply following the steps:

1. Open the Grial.Starter
2. Install Xamarin.Forms.GoogleMaps 29.0.0.2 (against above version, will return a java exit code 2 error)
3. Install Xamarin.GooglePlayServices.Location 29.0.0.2 
4. Compile it.

My project needs to work with this component, could you help me, thanks!

**Comment by LeoHere** [comment]
@shengguow I was not able to reproduce the issue so far. Can you please clarify what version of ```Xamarin.Forms.GoogleMaps``` must be installed?  

When you said that ```Xamarin.GooglePlayServices.Location``` with Grial, you mean that the version you want to install is not compatible with the version of XF Grial is using by default?

**Comment by shengguow** [comment]
@LeoHere  I found it is my problem, I finally deleted the obj folder, files in Bin/Debug and clean my solution, now it's working, thanks for the reply.
