### ISSUE TITLE
GridOptionsView - DataTemplate taking too much space

### ISSUE THREAD

**Issue by stringo** [UXDivers/Grial-UI-Kit-Support#191]
Hi guys,

I'm using a GridOptionsView in XAML. Here's the code:

```
<artina:GridOptionsView 
	Padding="0" 
	ColumnSpacing="0" 
	RowSpacing="0" 
	VerticalOptions="Fill" 

	TranslationX="20"
		
	BackgroundColor="White"  
	ColumnCount="1"
	RowCount="{Binding payment_methods_row_count}"
	ItemsSource="{Binding current_business.payment_methods}">

	<artina:GridOptionsView.ItemTemplate>
		<DataTemplate>
			<Label Text="{Binding description, StringFormat='{}&#x2022; {0}'}" HorizontalOptions="Start" VerticalOptions="Start" FontSize="14" />	
		</DataTemplate>
	</artina:GridOptionsView.ItemTemplate>
</artina:GridOptionsView>

```
There's no code behind in the ContentPage. I'm not sure why it's taking so much space, do you have any clue why? Is this something related to the behaviour of the GridOptionsView?

The RowCount property is correct for both cases below (2 and 1):

**1.-**
<img width="373" alt="screen shot 2017-06-12 at 5 02 30 pm" src="https://user-images.githubusercontent.com/1963433/27057326-53f23ed4-4f91-11e7-85dc-f09a486485bf.png">

**2.-**
<img width="374" alt="screen shot 2017-06-12 at 5 12 20 pm" src="https://user-images.githubusercontent.com/1963433/27057628-9a2e0878-4f92-11e7-8460-bd16d3fedbbc.png">

**Comment by LeoHere** [comment]
@stringo can you provide XAML for the full page  so I can better understand its context? You are using the ```GridOptionsView``` to render the "Acepta pagos con" itemize, right?

**Comment by stringo** [comment]
Hi Leo,

Thanks for the reply. That's right I'm using the GridOptionsView in order to render the items of "Acepta pagos con".

Please share an email so I can send the full XAML code of the ContentPage.

Thanks in advance for the valuable help.

**Comment by LeoHere** [comment]
@stringo write me to l r o d r i g u e z @ uxdivers.com

**Comment by LeoHere** [comment]
The ```GridOptionsView``` can't adapt to the content size as you are trying to. It was not designed with that scenario in mind. However, is seems to be a useful feature, therefore we will extend the control with two additional properties ```ItemHeightAuto``` and ```ItemWidthAuto``` which allows to control if the item Height/Width should adjust to the content.

We will implement it and let you know when the feature hits the nuget packages, so you can test it. It should not take long (couple of days top).

**Comment by LeoHere** [comment]
@stringo the new properties are available in the Nuget packages ***55-RC2***. Please update all ```UXDivers.Artina.*``` packages in the 3 projects, then do a clean + rebuild.

**Comment by stringo** [comment]
Thanks ! I'll try that, I'll close the issue.
