### ISSUE TITLE
Not able to bind the repeater control with ObservableRangeCollection

### ISSUE THREAD

**Issue by crakhi** [UXDivers/Grial-UI-Kit-Support#192]
I created a page with your repeaterControl and a normal ListView control. I binded both of them with a ObservableRangeCollection object and on the OnAppearing event I am trying to populate the ObservableRangeCollection. 
The ListView is getting the updated values but the repeater control is not getting updated.

This seems to be the same as [Issue#132](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/132) but the solution is not provided there. But in my case I am using the latest version of Grial2.0. Can you please help me with this.

**Comment by LeoHere** [comment]
@crakhi there is a new version of the Nuget packages (55-pre1) that solves this issue. You will need to check the "Show pre-release packages" in order to see it.

**Comment by crakhi** [comment]
I updated with 55-RC and still I am facing the same issue.

**Comment by LeoHere** [comment]
Please be sure to update the 4 packages in the 3 projects. Then do clean and rebuild.

**Comment by crakhi** [comment]
Clean & Re-Build worked! Thanks!
