### ISSUE TITLE
artina style not applied to buttons

### ISSUE THREAD

**Issue by damiondaly** [UXDivers/Grial-UI-Kit-Support#194]
Hi
We have installed the correct packages and are using the namespace
xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
in our XAML, but when we try to create an artina button no style is applied to it other than a standard button

`<artina:Button
				Grid.Row="2"
				Margin="20"
				Style="{DynamicResource PrimaryActionButtonStyle}"
				x:Name="PrimaryActionButton"
				BackgroundColor="#FFFFFF"
                TextColor="#2980B9"
				VerticalOptions="End"
				Command="{Binding MoveNextCommand}"
				Text="Login"/>`

**Comment by LeoHere** [comment]
@damiondaly in which platform are you experiencing this issue, Android or iOS?

If it is Android, did you declared the custom renderer in your Android project?

~~~
[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.Button), typeof(UXDivers.Artina.Shared.ArtinaButtonRenderer))]
~~~

You can see all the declared custom renderers in ```Properties\AssemblyInfo.cs``` of your Android and iOS projects.

**Comment by damiondaly** [comment]
Thanks for the quick reply,
Yes it's in the Android project - should the declaration you mention be placed in AssemblyInfo.cs, or do we declare elsewhere?  Apologies for the simplicity of the questions, we are relatively new to Xamarin

**Comment by damiondaly** [comment]
Hi, thanks, we got it working
cheers
