### ISSUE TITLE
Licence BundleIdentifier error

### ISSUE THREAD

**Issue by damiondaly** [UXDivers/Grial-UI-Kit-Support#195]
We have developed an app using Grial which works fine with Android.  We just tested in iOS and it failed with the license exception:

"The BundleIdentifier does not match the license's"
on line:
UXDivers.Artina.Shared.GrialKit.Init(new ThemeColors(), "[our app].iOS.GrialLicense");

We have downloaded a new generated license and removed the app from the simulator but still get the error, can you give us any info to help sort it out?

thanks

**Comment by LeoHere** [comment]
@damiondaly please ensure that:
1. The Bundle Identifier in the Admin matches the one of your app. See the [License Verification](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-license-verification) section in the documentation for more information.
2. Did you replaced the iOS License file with the new downloaded license?

After replacing the license please do a clean&rebuild, to ensure the new license gets packed.

**Comment by damiondaly** [comment]
Hi,

that's it sorted, the bundle display name was wrong.

thanks

**Comment by LeoHere** [comment]
Great! Closing the issue.
