### ISSUE TITLE
TabControl's TabItem with ContentPage

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#198]
Hi,

I am working on TabControlSamplePage.

It is possible to use ContentPage under the TabItem? The sample is using "ffimageloading:CachedImage". Can this element replace by a ContentPage from another XAML?

The reason I need to use ContentPage is to get the benefit of using Prism MVVM framework which it does't work well with ContentView.

Please advice.

Dennis

**Comment by LeoHere** [comment]
@denfung  the ```TabControl``` is meant to display Views not ```ContentPages```. You should use a ```TabbedPage``` if you want to include full pages within.
