### ISSUE TITLE
QUESTION: artina:CircleImage with FFImageLoading

### ISSUE THREAD

**Issue by stringo** [UXDivers/Grial-UI-Kit-Support#199]
Hi guys, thanks for all the help that you haver provided for my app recently.

My question is very simple:

How can I have the artina:CircleImage style with a CachedImage of the FFImageLoading? I would like to take advantage of both sides.

Thanks in advance for any response!

**Comment by jpbrocca** [comment]
Hi @stringo, how are you?

Unfortunately, `FFImage` is still not used for our `CircleImage`. We did a lot of work on more critical areas and this was postponed on Grial 2.

You can add it in your templates by checking their wiki, just look for the Circle Transformation:
https://github.com/luberda-molinet/FFImageLoading/wiki/Transformations-Guide#circletransformation

You could try replacing your `CircleImage` for `FFImageLoading` and use the `CircleTransformation` to render a border on your image.

You can use it as follows:
`public CircleTransformation(double borderSize, string borderHexColor)
`

Best,
JP
