### ISSUE TITLE
Getting started should be splitted in two files

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Grial-UI-Kit-Support#2]
Current Getting started file is missing important info for users who are adding Grial to their current projects.

There's no easy way for them to make all the needed steps to make their project work with Grial.
So we need to clearly document all those steps for them.
In that sense, we will need to split our getting started in two files:
- **Getting started on a new project based on Grial sample**
- **Getting started adding Grial to an existing project**

**Thanks James Lavery from 
http://www.microsec.co.uk/ 
for your help!!**

**Comment by Laumania** [comment]
Sounds like great idea. Guess most people would like to use this on an existing project.

**Comment by jpbrocca** [comment]
Yes, absolutely, it's a great idea :)

**Comment by james-lavery** [comment]
An addition for the 'adding Grial to an existing project' documentation.

The iOS project needs a AssemlyInfo.cs file which exports the renderers and the static WorkaroundLoadingCustomRenderersFromExternalAssemblies class defined.

**Comment by jpbrocca** [comment]
James, congratulations! You hit the nail with that last part!

Our friend Mads Laumann was having similar issues to those you reported and thanks to your feedback he could make his project work! 

**AWESOME HELP!**
**Thanks a lot James! :)**

**Comment by Laumania** [comment]
Yeah thanks a lot @james-lavery for that tip.

I'll put a version of it on the wiki later.
