### ISSUE TITLE
The appName does not match the license's.

### ISSUE THREAD

**Issue by marcelloaz** [UXDivers/Grial-UI-Kit-Support#202]
I use developer license mode. But that thows exceptions.
GrialLicense
UXDivers.Artina.Shared.LicenseException: The appName does not match the license's.

The problema occurred after I replace file **grial_animation**
After I download the source file again everything works!

thanks.

**Comment by marcelloaz** [comment]
How can I replace grial_animation for one item of
Https://www.lottiefiles.com?

**Comment by LeoHere** [comment]
@marcelloaz please take a look at the [Troubleshooting License Issues](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-troubleshooting-license-issues) section in the documentation.

**Comment by marcelloaz** [comment]
Ok, thanks. Works now. :-)



2017-07-11 18:16 GMT-03:00 Leonardo Rodríguez <notifications@github.com>:
