### ISSUE TITLE
I Have a problem in Preview

### ISSUE THREAD

**Issue by joselacerdasoares** [UXDivers/Grial-UI-Kit-Support#203]
I can't preview:

<img width="576" alt="screen shot 2017-07-11 at 11 16 36" src="https://user-images.githubusercontent.com/6877437/28073236-875a96e4-662b-11e7-8944-003dd17071c8.png">

**Comment by LeoHere** [comment]
@joselacerdasoares that seems to be an issue of the previewer. You might want to report it to Xamarin.

You can use Gorilla Player to preview Grial. Send me an email to l r o d r i g u e z at uxdivers.com and I will share with you the last version of Gorilla (not released yet).
