### ISSUE TITLE
No font icons being displayed

### ISSUE THREAD

**Issue by jperkins85** [UXDivers/Grial-UI-Kit-Support#205]
Hello,

I just purchased the Pro kit. I am using the example solution and I have successfully built the solution and deployed it to a Genymotion emulator running the Gorilla SDK. Everything looks great with the exception of the icons not displaying on any of the forms. For the simpleLogin example x:Static local:GrialShapesFont.Lock and other font symbols aren't displaying. I have verified that the build actions are set to AndroidAsset. Within Gorilla SDK it says I am missing possible libraries, I can't find any errors in the log even with Verbose logging enabled. Below is my Gorilla.json. Any help is appreciated. Thank you.

{
  "knownAssemblies": [
    {
      "name": "UXDivers.Artina.Shared",
      "types": null
    },
    {
      "name": "UXDivers.Artina.Shared.Base",
      "types": null
    },
    {
      "name": "UXDivers.Artina.Shared.Repeater",
      "types": null
    },
    {
      "name": "UXDivers.Effects",
      "types": null
    },
    {
      "name": "UXDivers.Artina.Shared.Base",
      "types": null
    },
    {
      "name": "FFImageLoading.Transformations",
      "types": null
    },
    {
      "name": "FFImageLoading.Forms",
      "types": null
    },
    {
      "name": "FFImageLoading.Platform",
      "types": null
    },
    {
      "name": "Lotti.Forms",
      "types": null
    }
  ],

    "navigationPage": {
        "all": true
    }
}

**Comment by LeoHere** [comment]
Which version of Gorilla Player are you using? If it is 1.0.0.15 (i.e. the last one, published last Friday) try removing the ```knownAssemblies``` from the ```Gorilla.json```. This property is optional starting 1.0.0.15. 

You might need to restart Gorilla for the change to take effect.

**Comment by LeoHere** [comment]
Icons are not being displayed probably because the assembly where the Font helpers are is not included among the ```knownAssemblies```. By removing the ```knownAssemblies``` Gorilla will include all the referenced assemblies by default, probably fixing the issue.

**Comment by jperkins85** [comment]
I'm using 1.0.0.15 so I removed the knownAssemblies. It is loading the same with the error "The previewed page make use of assemblies not available in the current SDK setup." I have cleaned and rebuilt the project after making the change and restarted Gorilla, Emulator and VS.

**Comment by LeoHere** [comment]
Did you configured the SDK yourself or did you downloaded the Gorilla enabled version from the Grial Admin site?

**Comment by jperkins85** [comment]
I downloaded the Gorilla enabled version.

**Comment by jperkins85** [comment]
I just found this in the log,

{"level":"info","message":"Gorilla Server: info: Xaml processing warning Summary:\"Setter for property \"Text\"  was removed\"; Message:\"Setter for property \"Text\"  was removed because it references a x:Static member from an unknown assembly (\"local:GrialShapesFont.Circle\").\" processingIssue=true, issueType=warning, file=C:\\Users\\*****\\Documents\\*****\\GrialKit\\Grial\\starter\\*****\\App.xaml, hasPosition=true, line=511, column=80, position=21574, area=Xaml, scope=Req, contextInstanceId=2, targetId=1, sampleDataId=0\r\n","timestamp":"2017-07-15T14:55:41.070Z"}

**Comment by LeoHere** [comment]
That error implies that the assembly of your PCL project (which is were the ```GrialShapesFont``` is located) is somehow not being considered as a known assembly.

The version you download from Grial Admin does not includes the ```knownAssemblies```. If the property is not defined, Gorilla will consider all the assemblies referenced from the PCL project as known, including the PCL assembly itself . Did you do any additional change to the solution you downloaded from the Grial Admin site (beside adding ```knownAssemblies```) ?

Can you please try doing as follows?
1) Restart Gorilla Desktop App
2) Download the starter with Gorilla integrated
3) Open it
4) Switch to Gorilla Configuration
5) Deploy it to the simulator (i.e. you will be deploying Gorilla SDK) 
6) From the app in the simulator, connect to the server in the list
7) From your IDE open the ```WelcomeStarterPage.xaml```. You might need to ```Click Tools->Gorilla Player->Connect``` if needed.

After doing so you should see the Welcome page previewed in Gorilla, Do you still get the same error after doing this?

**Comment by jperkins85** [comment]
After doing this it appears Gorilla SDK is no longer deploying but the android app, where the interface works fine.

**Comment by jperkins85** [comment]
I got the SDK working and all the icons are now showing in the viewer. I had to make the following changes to the MainActivity.cs. When the two GorillaSdkHelper lines were not commented I was getting a "The name 'GorillaSdkHelper' does not exist in the current context", I'll want to use tab control is future how can I fix this?


//#if GORILLA
			LoadApplication(
				UXDivers.Gorilla.Droid.Player.CreateApplication(
					this,
					new UXDivers.Gorilla.Config("Good Gorilla")
						// Shared.Base
						.RegisterAssemblyFromType<UXDivers.Artina.Shared.NegateBooleanConverter>()
						// Shared
						.RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>()
						// Tab Control
						//.RegisterAssembly(GorillaSdkHelper.TabControlType.Assembly)
						// Repeater Control
						//.RegisterAssembly(GorillaSdkHelper.RepeaterControlType.Assembly)

						// Effects
						.RegisterAssembly(typeof(UXDivers.Effects.Effects).Assembly)

						// // FFImageLoading.Transformations
						.RegisterAssemblyFromType<FFImageLoading.Transformations.BlurredTransformation>()
						// FFImageLoading.Forms
						.RegisterAssemblyFromType<FFImageLoading.Forms.CachedImage>()

						// Grial Application PCL
						.RegisterAssembly(typeof(Now.App).Assembly)
					));
//#else
            //LoadApplication(new App());
//#endif

**Comment by jperkins85** [comment]
Nevermind I uncommented the section in GorillaSdkHelper and it works fine now. Thank you.
