### ISSUE TITLE
Menu a la derecha

### ISSUE THREAD

**Issue by jpeker** [UXDivers/Grial-UI-Kit-Support#208]
Is it possible to put the menu's icon to the right, with the options from the right side of the screen?

**Comment by jpbrocca** [comment]
Hi @jpeker,
Please post your issues in English so all users will benefit from the answers!
I have translated your question here.

So about the menu, you cannot put the menu to right by default.
You will need a custom renderer to achieve that.
Depending on what you are trying to achieve you can use the CustomNavBar to change the icon position:

![image](https://user-images.githubusercontent.com/15996999/28478200-b33faf10-6e2d-11e7-83a4-de4b420beacf.png)

Best,
JP
