### ISSUE TITLE
Picker styling not implemented?

### ISSUE THREAD

**Issue by rellistheopportunity** [UXDivers/Grial-UI-Kit-Support#209]
I was wondering when picker styling will be added. Issue #72 mentioned that it will be in version 2.0, but we are now 2 versions into 2.0 and I still cannot figure out how to style a picker. If it isn't being added within the next week or two, I need to know so that I can write my own implementation for a project I am working on.

**Comment by LeoHere** [comment]
@rellistheopportunity Grial 2 includes some properties that allows to affect the picker in iOS (Android is not supported). Those properties are:

~~~
artina:PickerProperties.BorderStyle="Rect" 
artina:PickerProperties.BorderWidth="2" 
artina:PickerProperties.BorderColor="Red" 
artina:PickerProperties.PlaceholderColor="Red" 
artina:PickerProperties.BorderCornerRadius="10"
~~~

**Comment by LeoHere** [comment]
@rellistheopportunity we updated the android renderers to support this properties too. See #272. Closing the issue now. If you need to open it again.
