### ISSUE TITLE
referencing Gorilla Player's dll, causes compile error.

### ISSUE THREAD

**Issue by omanuke** [UXDivers/Grial-UI-Kit-Support#21]
I'm trying to add Gorilla SDK to Grial sample, but if I add references to 4 Player dlls, compilation errors happen.
I referenced [here](http://docs.gorillaplayer.com/) and [here](https://github.com/UXDivers/Gorilla-Player-Support-And-Issues/wiki/Gorilla-SDK)

I wrote some of errors below.
This seems like [this](http://stackoverflow.com/questions/33219973/resource-contains-no-definition-for-animation).
Any idea?

and If you could ,please provide Grial next updated sample with Gorilla configuration except Gorilla dlls.
If you do so, I can copy Player's dlls and everything will work.

---errors ---
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\obj\Debug\res\drawable\walkthrough_bg_0.png : libpng warning : iCCP: Not recognizing known sRGB profile that has been edited
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\obj\Debug\res\drawable\walkthrough_bg_1.png : libpng warning : iCCP: Not recognizing known sRGB profile that has been edited
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\MainActivity.cs(49,7,49,63): warning CS0618: 'Resources.GetColor(int)' is obsolete: 'deprecated'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(29,117,29,126): error CS0117: 'Resource' does not contain a definition for 'Animation'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(30,118,30,127): error CS0117: 'Resource' does not contain a definition for 'Animation'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(31,134,31,143): error CS0117: 'Resource' does not contain a definition for 'Animation'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(32,121,32,130): error CS0117: 'Resource' does not contain a definition for 'Animation'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(33,120,33,129): error CS0117: 'Resource' does not contain a definition for 'Animation'
1>D:\MyDocuments\cvs\GrialUIKit\Source\grial-uikit-extended-1.1.0\samples\Grial\Droid\Resources\Resource.designer.cs(34,137,34,146): error CS0117: 'Resource' does not contain a definition for 'Animation'

**Comment by LeoHere** [comment]
Hi, can you tell me which version of gorilla and grial are you using?

I think that the problem might be that gorilla is using a version of XF superior to the one used by Grial.

**Comment by omanuke** [comment]
Grial 1.1
Gorilla 0.8.2
shiuld I use Grial 1.2.1?

**Comment by LeoHere** [comment]
Grial 1.1 used XF 1.4.4.6392, meanwhile Gorilla 0.8.2 use 2.0.1.6505.

You will need tu upgrade Grial. 

Moving to Grial 1.2.1 should be fine.

**Comment by omanuke** [comment]
I upgraded to Grial 1.2.1 and integrated Gorilla.

But there is some problems.
I can see pages below.
  BrandBlock.xaml
  WelcomePage.xaml

I can't see pages below.

![CustomRenderers.xaml](https://cloud.githubusercontent.com/assets/1901757/13351173/2f9f9fe6-dcc8-11e5-874c-50ed8fe5c103.png)
![MessageList.xaml](https://cloud.githubusercontent.com/assets/1901757/13351275/e1625a2a-dcc8-11e5-8105-a14b87cb8aab.png)

Some page causes crash.
This crash seems  to be caused by opening many pages or raising lots of error.
Not by specified page.
Some page caused crash ,but after started again, player shows error. didn't crash.
![crash then error](https://cloud.githubusercontent.com/assets/1901757/13351535/9789d3d6-dcca-11e5-8b66-b6f74657fa5a.png)

My environments are below.
VS2015 
Nexus4(Lollipop) on Xamarin Android Player.

**Comment by jpbrocca** [comment]
Hi @omanuke, 

I am closing this issue since it should be fixed by now through latest versions of Grial and Gorilla (through Gorilla SDK).

If you still face the same issue please reopen the issue and let me know.

Best regards,
JP
