### ISSUE TITLE
[QUESTION] Must I use a MasterDetailPage as root page of the app?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#213]
Hello, 

I try  to create a new app for my client from the **starter project**.

I would to like to know if I need to use a `MasterDetailPage` as the the **root page** of the app? For now, I use a `ContentPage` as root page, but the `NavigationBar` is not displayed...

Is it normal?

**Comment by LeoHere** [comment]
Using the `MasterDetailPage` is not required by Grial, it is up to you. 

You will need to wrap your `ContentPage` within a `NavigationPage` for the `NavigationBar` to show up. Please read [this link](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/hierarchical/) for additional information.

Something like:
~~~
MainPage = new NavigationPage(new MyContentPage());
~~~

Hope it helps.

**Comment by Goldstrike** [comment]
Thank you for your feedback!
