### ISSUE TITLE
[Question] Could I use Iconize with GrialKit

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#215]
Hello,

I would like to use font icons as icons for the ToolBarItem.

I've seen that [Iconize ](https://github.com/jsmarcus/Xamarin.Plugins/tree/master/Iconize) allows to do it easily. 

But I would like to know if the use of Iconize will not create a conflict with the other fonts of GrialKit?
In add, isn't there a way to do this without Iconize?

**Comment by LeoHere** [comment]
@Goldstrike you should not have conflicts using Iconize along with Grial. 

Currently we don't provide that feature in Grial, but we are working it, stay tuned.
