### ISSUE TITLE
Issue with Licenses

### ISSUE THREAD

**Issue by ImmenseIT** [UXDivers/Grial-UI-Kit-Support#217]
Hello, We are building and app we have pro version of Grial, and recently we changed the name of the app on Grial admin portal and downloaded new license. We applied the changes in our solution but we are still getting the error. please help. Attached are the screenshot.

**Comment by LeoHere** [comment]
@ImmenseIT please take a look at the [TroubleShooting License Guide](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-troubleshooting-license-issues)
