### ISSUE TITLE
Sample app crashing on Android

### ISSUE THREAD

**Issue by EdHubbell** [UXDivers/Grial-UI-Kit-Support#22]
Steps to recreate: 

Open app
Browse our samples
Navigation 
Root page
User Profile
(Back button)
App closes (which I find unexpected, but no biggie). 
On app re-launch, it goes back to the home screen. After about 5 seconds the app gives off the 'Unfortunately, Grial UIKit has stopped' Unfortunate, indeed. 

FWIW - I'm on a Nexus 5x  running Marshmallow.

My guess is that this has to do with some of the difficulties when demoing a root page.

**Comment by jpbrocca** [comment]
Hi @EdHubbel thanks for this.

You are right, this is part of the chalenges when demoing a root page. We will review your steps and try to fix this issue.

Thank you very much,
JP

**Comment by jpbrocca** [comment]
Hi @EdHubbell,

this is an old thread. I believe this is fixed on Grial 1.5 so I am closing this issue.
If you still face the same problem please let me know.

Thank you!
JP
