### ISSUE TITLE
[HOW TO] Build on Mobile Azure Center

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#221]
Hello,

I try to build my project on [Mobile Azure Center](https://mobile.azure.com/), but the build failed:

> Errors in packages.config projects
>
>     Unable to find version '2.0.60' of package 'UXDivers.Artina.Controls.Repeater'.
>       /Users/ci/.nuget/packages/: Package 'UXDivers.Artina.Controls.Repeater.2.0.60' is not found on source '/Users/ci/.nuget/packages/'.
>       https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Controls.Repeater.2.0.60' is not found on source 'https://api.nuget.org/v3/index.json'.
>     Unable to find version '2.0.60' of package 'UXDivers.Artina.Controls.Tab'.
>       /Users/ci/.nuget/packages/: Package 'UXDivers.Artina.Controls.Tab.2.0.60' is not found on source '/Users/ci/.nuget/packages/'.
>       https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Controls.Tab.2.0.60' is not found on source 'https://api.nuget.org/v3/index.json'.
>     Unable to find version '2.0.60' of package 'UXDivers.Artina.Shared'.
>       /Users/ci/.nuget/packages/: Package 'UXDivers.Artina.Shared.2.0.60' is not found on source '/Users/ci/.nuget/packages/'.
>       https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.2.0.60' is not found on source 'https://api.nuget.org/v3/index.json'.
>     Unable to find version '2.0.60' of package 'UXDivers.Artina.Shared.Base'.
>       /Users/ci/.nuget/packages/: Package 'UXDivers.Artina.Shared.Base.2.0.60' is not found on source '/Users/ci/.nuget/packages/'.
>       https://api.nuget.org/v3/index.json: Package 'UXDivers.Artina.Shared.Base.2.0.60' is not found on source 'https://api.nuget.org/v3/index.json'.

I can build without any problem on Mac or on Windows, as I added the Grial NuGet source.
But how could specify it to build on Mobile Azure Center?

**Comment by Goldstrike** [comment]
Finally, after having added "NuGet.config" file in the root directory (with the *.sln file), I can build on Mobile Azure Center.

This file looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />    
    <add key="GrialNuget" value="http://nuget.uxdivers.com/grial " />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSourceCredentials>
    <GrialNuget>
      <add key="Username" value="myLogin" />
      <add key="ClearTextPassword" value="myPassword" />
    </GrialNuget>
  </packageSourceCredentials>
</configuration>
```

**Comment by LeoHere** [comment]
@Goldstrike thanks for sharing. In case you don't know, under `My Account -> Nuget Access` you can configure Nuget Dedicated User, as shown in the image bellow.

![image](https://user-images.githubusercontent.com/16000584/29435329-fe047580-837c-11e7-8f41-89f4e50a8b12.png)

This user is useful for scenarios like this, so you don't have to include your personal credentials in the configuration file.

Hope it helps.
