### ISSUE TITLE
[Question] Grial and Azure Mobile Center - Android issue

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#222]
Hello,

I try to use [Azure Mobile Center ](https://mobile.azure.com/) to manage my app: analytics, continuous integration, deployment,..

The deployment works fine on iOS, but I meet a problem on Android.
When I deploy the app on an Android device from Visual Studio, or from a apk created from the Archive Manager there  is no problem: the app works well.
But when I use the apk created from the Azure Mobile Center there is a problem: the install works fine, but the app crashes after the splashscreen.

In a Xamarin.Forms project, we must place the `MobileCenter.Start() `in the `OnStart()` method in `App.xaml.cs`. So I can't see if the problem comes form the license activation in `MainActivity.cs`, as the `OnCreate()` method is called before the `OnStart()` in `App.xaml.cs`.

**_Have you already done tests with Azure Mobile Center?
Would you have any suggestion?_**

**Comment by den2107** [comment]
I'm facing the same problem, when I try to authenticate the whole app crashs

 MobileServiceClient.LoginAsync()

This method pops up a browser to log in on the B2c service.

Any ideia how to fix it?

**Comment by den2107** [comment]
@Goldstrike ,

Just find out that the issue is with the new versions of the Xamarin.Android.* packages that were upgraded.

Back them to the  23.30 version(all of them).

PS: I'm using the Microsoft.Azure.Mobile.Client 4.0.1 and NETStandard.Library 1.6.1
