### ISSUE TITLE
TabItem to use font icon

### ISSUE THREAD

**Issue by ShiroYacha** [UXDivers/Grial-UI-Kit-Support#225]
Hi,

It seems that the TabItem in tab control only supports file icons. Is it possible to support font icons in the future?

Thanks

**Comment by jpbrocca** [comment]
Hi @ShiroYacha,

Yes, it is on the roadmap.

Best,
JP

**Comment by dirivero** [comment]
This was included in Grial 2.6 as IconText and IconTextSelected properties in the TabItem.

Check here: https://github.com/UXDivers/Grial-UI-Kit-Support/blob/master/release-notes.md
