### ISSUE TITLE
[Question] CustomNavBar: how to implement it properly?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#226]
Hello, 

I try to use the CustomNavBar on the main page of my app:
```
<StackLayout Orientation="Vertical">
    <local:CustomNavBar />
    <ScrollView 
        ... 
     </ScrollView>
</StackLayout>
```

But ithis doesn't work as expected:
- the default height of the NavBar is not good (this problem is the same on Android and iOS):
[screenshot1](https://img4.hostingpics.net/pics/258679AndroidHeight.png)
- when I navigate to another page, I can see the CustomNavBar and the default NavBar of the new page during a short time (his problem only occurs on Android):
[screenshot2](https://img4.hostingpics.net/pics/553392Android2NavBars.png)

I think that the first issue could be easily fixed by setting a defaut height request for iOS and Android, but what about the second issue?

**Comment by jpbrocca** [comment]
Hi @Goldstrike, how are you?

Please check `CustomNavBarPage.xaml` for a reference on how to correctly use the `CustomNavBar`.

Basically, you will need a Grid as the main layout structure, not a StackLayout.
```
<!-- MAIN CONTAINER -->
	<Grid RowSpacing="0">
		<Grid.RowDefinitions>
			<RowDefinition Height="Auto" />
			<RowDefinition Height="*" />
		</Grid.RowDefinitions>

		<!-- CUSTOM NAVBAR -->
		<local:CustomNavBar 
			Grid.Row="0"/>

		<!-- SCROLL AREA -->
		<ScrollView 
			Grid.Row="1"
			Grid.RowSpan="1"
			Padding="{ DynamicdResource MainWrapperPadding }">
		       <!-- YOUR PAGE CONTENT HERE -->

		</ScrollView>
	</Grid>
```
The second issue you mention is caused by the way you are handling navigation.
@LeoHere can you provide more context about this?

Regards,
JP

**Comment by LeoHere** [comment]
@Goldstrike can you share how are you implementing the navigation?

**Comment by Goldstrike** [comment]
Thanks for your feedback.
@LeoHere  I have 2 ways of navigation:
- from a button on my main page:
`await Navigation.PushAsync(new AgendaEventListPage(new ObservableCollection<AgendaEvent>(_vm.AllAgendaEventList)), true);`
- from a template which is based on "DashboardCardItemTemplate":
```
var selectedAgendaEvent = (AgendaEvent)((VisualElement)sender).BindingContext;
var agendaEventView = new AgendaEventDetailsPage(selectedAgendaEvent);
await Navigation.PushAsync(agendaEventView);
```

In the both cases, I transmit a parameter to the destination page: I don't know if this could explain my problem...

**Comment by LeoHere** [comment]
@Goldstrike are you experiencing this issue in both cases (i.e. doing the push from the main page and from the item template)?

XF does not seems to be honoring the `NavigationPage.SetHasNavigationBar(this, false)` sometimes in Android.  Please take a look at the method `LaunchSampleInDetail` in `RootPage.xaml.cs`. It implements a workaround. Not a nice one, but it fixes the issue.

**Comment by LeoHere** [comment]
@Goldstrike forget about the workaround mentioned in my previous post. 

Try this one:

~~~
private async void NaviateTo(Page page)
{
    if (Device.RuntimePlatform == Device.Android)
    {
        NavigationPage.SetHasNavigationBar(page, false);

        await Navigation.PushAsync(page, animated: false);

        NavigationPage.SetHasNavigationBar(page, true);
    }
    else
    {
        await Navigation.PushAsync(page);
    }
}
~~~

Hope it helps.

**Comment by Goldstrike** [comment]
@LeoHere it's work better like that.

But there is something else that I did not see right away: when returning to the page containing the CustomNavBar, there is a "flash" that is not present with the classic NavBar.

I've attached a small video to illustrate this:
[video](http://dl.free.fr/eB75yR3Dg)

Is there a way to fix this? It only occurs on Android.

**Comment by LeoHere** [comment]
After some testing we end up with this workaround, not pretty, but seems to solve the issue. 

You will need to add the following code to the page containing the Custom Nav Bar.

~~~
private bool _isVisible;

protected override void OnDisappearing()
{
    base.OnDisappearing();

    NavigationPage.SetHasNavigationBar(this, true);
    CustomNavBar.IsVisible = false;

    _isVisible = false;
}

protected override void OnAppearing()
{
    base.OnAppearing();

    _isVisible = true;
    UpdateNavBar();
}

private void UpdateNavBar()
{
    if (_isVisible)
    {
        if (Navigation.NavigationStack[Navigation.NavigationStack.Count - 1] == this)
        {
            CustomNavBar.IsVisible = true;
            NavigationPage.SetHasNavigationBar(this, false);
        }
        else
        {
            Device.BeginInvokeOnMainThread(UpdateNavBar);
        }
    }
}
~~~

Hope it helps.

**Comment by Goldstrike** [comment]
Thank you, but there is still a problem. This time, it's on iOS that the 2 NavBars are displayed successively when the user returns to the page containing the CustomNavBar: I 've uploaded a [video ](http://dl.free.fr/ttRjAVaU1) to show this.

The quality of the video is not very good, but the 2 NavBars are visible in same time during a short time...

In addition, there is another "problem" that is present on iOS and Android: the size and/or the position of the "Hamburger" button is not the same for the 2 NavBars. This creates a "flash effect" on the "Hamburger" button, which is not really "user friendly".

Here are 2 screenshots on Android:
- with the "default" NavBar: [screenshot1](https://img4.hostingpics.net/pics/998841HamburgerButtonSizeDefaultNavBar.png)
- with the CustomNavBar: [screenshot2](https://img4.hostingpics.net/pics/547497HamburgerButtonSizeCustomNavBar.png)
You can see that the "Hamburger" button renders smaller on the CustomNavBar.

Here are 2 screenshots on iOS:
- with the "default" NavBar: [screenshot3](https://img4.hostingpics.net/pics/998841HamburgerButtonSizeDefaultNavBar.png)
- with the CustomNavBar: [screenshot4](https://img4.hostingpics.net/pics/596644HamburgerButtonSizeDefaultNavBariOS.png)
You can see that the "Hamburger" button renders smaller and is not aligned on the CustomNavBar.

So I think that it would be difficult to customize the CustomNavBar to my needs.
I wanted just to use it to replace the title of the NavBar with a logo on the homepage only: do you think it would be easier to do with a CustomRenderer?

**Comment by LeoHere** [comment]
@Goldstrike did you tried with `NavigationPage.SetTitleIcon(page, "logo.png");`? You should set it just in the homepage.

**Comment by Goldstrike** [comment]
@LeoHere this works fine on iOS, but not on Android.
On Android you must to add this to **Toolbar.axml**:

```
<ImageView
        android:src="@drawable/my_logo"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
/>
```

But in this case, the logo is visible on each page of the app: I only need to display on the main page...

Here are some links related to this:
[navigationpage-settitleicon-works-on-ios-but-not-android](https://forums.xamarin.com/discussion/88482/navigationpage-settitleicon-works-on-ios-but-not-android)
[navigationpage-settitleicon](https://forums.xamarin.com/discussion/52337/navigationpage-settitleicon)
[c-sharp-xamarin-forms-navigationpage-icon-not-showing](https://stackoverflow.com/questions/40057374/c-sharp-xamarin-forms-navigationpage-icon-not-showing/40098078#40098078)

**Comment by Goldstrike** [comment]
I finally managed to show and hide the **ImageView** of the **toolbar** through a **renderer**:

```
protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
{
    base.OnElementPropertyChanged(sender, e);

    if (e.PropertyName.Equals("CurrentPage"))
        // If we're on MainPage show the icon, otherwise hide it
        ChangeToolbarIconVisibility(Element.CurrentPage is MainPage); 
}

private void ChangeToolbarIconVisibility(bool visible) 
{
    var toolbarIcon = FindViewById<ImageView>(Resource.Id.toolbarIcon);        
    toolbarIcon.Visibility = visible ? Android.Views.ViewStates.Visible : Android.Views.ViewStates.Gone;            
}
```
And I added an **id** on the **ImageView**:

```
<ImageView android:src="@drawable/my_logo" 
           android:layout_width="wrap_content" 
           android:layout_height="wrap_content" 
           android:layout_gravity="center"
           android:id="@+id/toolbarIcon" />
```
