### ISSUE TITLE
Splash screen 

### ISSUE THREAD

**Issue by vidalkk** [UXDivers/Grial-UI-Kit-Support#228]
Guys,

Do you know how can I change the splash screen background color?

**Comment by jpbrocca** [comment]
Hi @vidalkk, how are you?

Yes, depending on the platform you can achieve that.

**Android**
The most straightforward is Android. You just change the `ComplementColor` value on your theme (i.e.: `GrialLightTheme.xaml`) and that will be used for splash background color.

If you need to point the background color to a different color resource you need to change the `splash_drawable.xml` directly:

```
Grial
    |_ Grial.Droid
        |_ resources
            |_ drawable
                |_ splash_drawable.xml
```
![image](https://user-images.githubusercontent.com/15996999/29730360-424429a4-89b6-11e7-8a82-54d19a590e25.png)

**iOS**
You will need to open`Splash.storyboard` file on Visual Studio:

```
Grial
    |_ Grial.iOS
        |_ Splash.storyboard
```

...then select the splash background and pick your color:

![image](https://user-images.githubusercontent.com/15996999/29730498-c85a50f4-89b6-11e7-855d-30d2160d09d7.png)

![image](https://user-images.githubusercontent.com/15996999/29730674-89cda466-89b7-11e7-928a-66501631d6f9.png)

Best,
JP

**Comment by vidalkk** [comment]
Hi JP,

I am fine and you?

The approach you mentioned for iOS worked fine, however the one for Android
didn't.

When I go to Colors.xml and update the @color/ComplementColor color it
doesn't reflect but below line works

<solid android:color="@android:color/black" />

Regards
Vidal Kitoko

2017-08-25 21:09 GMT+01:00 jpbrocca <notifications@github.com>:

**Comment by jpbrocca** [comment]
Hi @vidalkk, I am fine too, thanks :)

So, about the Android color, perhaps I was not clear.
What I meant is that you can simply change the color resource value (`ComplementColor`) on your theme (**XAML file!**) and then it will be used for the splash on Android.
You can also directly replace the value as you did on the `Colors.xml` file on your Android project.

Best,
JP

**Comment by jpbrocca** [comment]
Hi @vidalkk, how are you?

I am closing this bug to keep things tidy, but please feel free to reopen as needed.
Best,
JP

**Comment by IoTFier** [comment]
Hi JP, I am running into the same issue.

Your help with my questions below will be appreciated.

1. Why do we use the value of ComplementColor and not the SplashBackgroundColor when it sounds like meant for serving the purpose of changing background color of the splash screen?
2.  The Colors.xml has a comment that says any changes made outside in the theme xaml are synced into this file automatically (which is what I am experiencing) then why do you suggest to make change directly in the Colors.xml?
3. The ComplementColor resource is used at many other places. So, without using SplashBackgroundColor, how do we make sure the change made in ComplementColor is only reflected for splash background and not at other places where it is referred?
4. In iOS Splashscreen I could add labels. Do you have a sample XML to add a label in Android Splashscreen?

Thank you.

**Comment by jpbrocca** [comment]
Hi @IoTFier,

About your questions:

1) this is an old thread. Originally the color was the ComplementColor then we created an specific resource for the splash -SplashBackgroundColor- which has the same color value.

2) again, this was an old thread and I was explaining how to get the result you already have with grial 2.5+.

3) Like I said in 1) and 2) those are different and independent resources. Each color is for a different purpose since Grial 2.5+.

4) No

Best
JP
