### ISSUE TITLE
How to combine artina:OnOrientationDouble and OnPlatform?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#229]
Hello,

I would like to know is there is a way to combine `artina:OnOrientationDouble` and `OnPlatform` in the XAML code.

I use a same `ContentView`, but the render is must be different between iOS and Android.
I already use `OnPlatform` arguments like this to  manage `Margin`:
```
 <Grid		
    BackgroundColor="{ DynamicResource BasePageColor }"
    ColumnSpacing="0"
    RowSpacing="0"
    Style="{ StaticResource ListCardViewStyle }">
    <Grid.Margin>
        <OnPlatform x:TypeArguments="Thickness">
            <On Platform="Android">4,4,4,4</On>
            <On Platform="iOS">0,0,0,1</On>
        </OnPlatform>
    </Grid.Margin>
    ...
</Grid>
```

And I also use `artina:OnOrientationDouble` to manage other parameters:
```
<Grid.ColumnDefinitions>
    <ColumnDefinition Width="{ artina:OnOrientationDouble 
        Default=155,
        PortraitTablet=180,
        LandscapeTablet=180 }" />
    <ColumnDefinition Width="*" />
</Grid.ColumnDefinitions>
```

But for some parameters, I would like specify the **platform** (iOS/Android) and the **orientation** (Default, PortraitTablet, LandscapeTablet). 

**_I think that I could manage this through ViewModel, but is there a proper way to manage this through XAML or through the Code-Behind?_**

**Comment by Goldstrike** [comment]
I finally found the solution:

```
<Grid.ColumnDefinitions>
    <ColumnDefinition>
        <ColumnDefinition.Width>
            <artina:OnOrientationDouble>
                <artina:OnOrientationDouble.Default>
                    <OnPlatform x:TypeArguments="x:Double">
                        <On Platform="iOS">150</On>
                        <On Platform="Android">145</On>
                    </OnPlatform>
                </artina:OnOrientationDouble.Default>
                <artina:OnOrientationDouble.PortraitTablet>
                    180
                </artina:OnOrientationDouble.PortraitTablet>
                <artina:OnOrientationDouble.LandscapeTablet>
                    180
                </artina:OnOrientationDouble.LandscapeTablet>
            </artina:OnOrientationDouble>
        </ColumnDefinition.Width>
    </ColumnDefinition>
</Grid.ColumnDefinitions>

```

**Comment by Goldstrike** [comment]
Hi, I have a new request: is it possible to use `OnOrientationXxx` for managing **Padding**/**Margin**?
There are 4 parameters so I don't see how I could do...

**Comment by kriscoleman** [comment]
Yes. OnOrientationXxx is type safe, so just use the type that Padding/Margin expects, double. 

For a font size, which expects int, you would use OnOrientationInt. 

Whenever orientation changes, the function will update that view's property.
