### ISSUE TITLE
Meta-Issue - documentation of each template

### ISSUE THREAD

**Issue by RocketPop** [UXDivers/Grial-UI-Kit-Support#230]
Grial looks great and I'm getting it integrated to my new app pretty well. However getting up to speed with all the myriad pages is slow. I would like to request a "map" kind of document describing the structure of each template (and item templates!) you offer. I'm imagining a general wireframe of the template, with callouts for each item showing any names of bindables that also includes the type of each item (string, url, image, font icon etc). This goes as well for documenting which of the various item templates are used. It seems to me that most grial users will take some time with the demo app to locate the template closest to their needs, then tweak it. Documents of the structures would greatly reduce my time spent opening some xaml, looking around for "{Binding " to discover names, etc... :) A simple Visio/Omnigraffle style vector drawing would be just fine!

**Comment by jpbrocca** [comment]
Hi @RocketPop,
Thanks for your suggestion! 
We are working in making things easier in the same line of your suggestion.

Meanwhile, to mitigate this (even while not perfect) you could:
- go to grial website and check the different sections and the pages that belong to each one.
 - http://grialkit.com/screenshots/
- use [Gorilla player](www.gorillaplayer.com) to instantly preview each of the pages and templates on devices or simulators. That way  you can select specific files from visual studio and preview them.

Also, it would be great if you could reach us at hello@uxdivers.com so we can ask you more questions and keep you updated.

Regards and thanks
JP

**Comment by RocketPop** [comment]
Hi guys - thanks for the response - the screenshots page you link is going in the right direction! I'll follow up with an email shortly - I haven't yet installed Gorilla player but I definitely will!

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for more than a year.
