### ISSUE TITLE
GridOptionsView Item Clicked

### ISSUE THREAD

**Issue by ramonbrbs** [UXDivers/Grial-UI-Kit-Support#232]
Hi,
There is no example explanning how to find object clicked at GridOptionsView control.
The unique example found is at DashboardMultipleTilesPages but it only send the same message for each grid item clicked and not receives parameter about the item clicked.

Thanks in advance.

**Comment by jpbrocca** [comment]
Hi @ramonbrbs,
please, check this thread:

https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207

Best
JP

**Comment by LeoHere** [comment]
Closing this issue to keep things tidy. Please reopen if needed.
