### ISSUE TITLE
HowTo manage Padding and Margin with artina:OnOrientationXxx

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#233]
Hello,

I would like to know if there is a way use `artina:OnOrientationXxx` for managing **Padding**/**Margin**?
I've already tried with `artina:OnOrientationDouble` but it didn't work: it's maybe as there are 4 parameters...

**Comment by jpbrocca** [comment]
Check https://github.com/UXDivers/Grial-UI-Kit-Support/issues/293
