### ISSUE TITLE
How to open a link from an item of the menu?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#238]
Hello,

I would like to know which approach you recommand to open an URL from an item of the menu?

From your sample, you add items like this:

```
internal static Dictionary<string, SampleCategory> CreateSamples()
{
  var categories = new Dictionary<string, SampleCategory>();

  categories.Add(
    "SOCIAL",
      new SampleCategory
      {
        Name = "Social",
        BackgroundColor = Color.FromHex(_categoriesColors[0]),
        BackgroundImage = SampleData.DashboardImagesList[6],
        Icon = GrialShapesFont.Person,
        Badge = 2,
        SamplesList = new List<Sample> {
          new Sample("Document Timeline", typeof(DocumentTimelinePage), SampleData.DashboardImagesList[6], GrialShapesFont.QueryBuilder, false, true),
          new Sample("Timeline", typeof(TimelinePage), SampleData.DashboardImagesList[6], GrialShapesFont.QueryBuilder, false, true),
          new Sample("User Profile", typeof(ProfilePage), SampleData.DashboardImagesList[6], GrialShapesFont.AccountCircle),
	...
        }
      }
    );
     ...
}
```

But how could I do if I want that the item "User Profile" opens an URL? Must I navigate to a view that contains a WebView? Or is there another way?

I would like to open the URL in a [Browser ](https://github.com/jguertl/SharePlugin/blob/master/docs/OpenBrowser.md) with [Share Plugin](https://github.com/jguertl/SharePlugin) as I already use this plugin...

**Comment by jpbrocca** [comment]
Hi @Goldstrike,

the navigation in Grial is just an example. You can handle navigation as you find it more convenient for your app (for instance, some people use Prism for such purpose).

Being all that said, you could invoke the Share plugin from `OnItemSelected` method available on code behind of `MainMenuPage` (depending on the item).

Best,
JP
