### ISSUE TITLE
Same menu looks different on both platforms

### ISSUE THREAD

**Issue by mgiomi** [UXDivers/Grial-UI-Kit-Support#239]
Hi, 
To develop the menu use a list with a template. But when installing in adroid and ios, the menu does not look the same on both platforms. On iOS are visual defects. The problem is that you see in blue the options that group in the grid.

menu in android:
![whatsapp image 2017-09-11 at 10 17 46 am](https://user-images.githubusercontent.com/22667610/30276657-e82c25b0-96db-11e7-977a-c16f790f275e.jpeg)

nemu in iOS:
![whatsapp image 2017-09-11 at 10 18 00 am](https://user-images.githubusercontent.com/22667610/30276684-f94dc0f6-96db-11e7-9890-326028ade06d.jpeg)

Code for listview:
       <controls:CustomListView 
            BackgroundColor="Transparent"
            Grid.Row="1"
            x:Name="LvUserMenuOptions"
			SeparatorVisibility="None"
		    IsGroupingEnabled="true"
		    GroupDisplayBinding="{ Binding Title }"
		    GroupShortNameBinding="{ Binding ShortName }"
		    HasUnevenRows="false"
			Margin="0,5"
            		Style="{ DynamicResource MainMenuListViewStyle }"
			>
            <ListView.RowHeight>
                <OnIdiom x:TypeArguments="x:Int32"
					Phone="40"
					Tablet="60"/>
            </ListView.RowHeight>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <templates:UserMenuTmp  />
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </controls:CustomListView>

Code for the template:

        <AbsoluteLayout
		Padding="24,0,0,0" 
		VerticalOptions="CenterAndExpand"
		HorizontalOptions="FillAndExpand">
        
        
        <Label
			Text="{ Binding Icon }"
            FontSize="{ shared1:OnOrientationDouble  Default=14,PortraitTablet=20, LandscapeTablet=20 }"
            Style="{ StaticResource FontIcon  }" 
            TextColor="{ Binding TextColor }"
			HorizontalTextAlignment="Start"
			VerticalTextAlignment="Center" 
			AbsoluteLayout.LayoutBounds="0, 0.5, 20, 20"
			AbsoluteLayout.LayoutFlags="XProportional, YProportional, HeightProportional">
        </Label>

	    
        <Label
			AbsoluteLayout.LayoutBounds="24, 0, 1, 1"
			AbsoluteLayout.LayoutFlags="WidthProportional, HeightProportional"
			Text="{ Binding Name }" 
            FontSize="Default"
			Style="{ DynamicResource MainMenuLabelStyle }"
            TextColor="{ Binding TextColor }"
			VerticalTextAlignment="Center" 
			Margin="0,0,0,0"
		/>

    </AbsoluteLayout>

**Comment by jpbrocca** [comment]
Hi @mgiomi,

It is difficult without seeing your whole project but so far from your code I can tell you:

1. It seems you made the custom listview background color **transparent** and that could be the issue if you have a background color for the whole page.
2. I don't see your `GroupHeaderTemplate`, but the problem could be there and if you add your template for such item you could control how things render (i.e. BackgroundColor, font size, etc.).

I suggest you use MainMenuPage from Grial's sample and its templates (`MainMenuGroupHeaderTemplate`, `MainMenuItemTemplate`) as a starting guide.

Best,
JP
