### ISSUE TITLE
Walkthrouhpage crashing when clicked on Finish

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#241]
Hi,

I added Navigation & Walkthrough into the starter project. My App.xaml.cs looks like this

public static Page GetMainPage()
        {
         return new WalkthroughPage();
        }

Issue: When walk through reaches last screen and I click Finish, it crashes. I tried to debug but it doesn't show me any debug point. It shows me the error page i attached. 

![grial-error](https://user-images.githubusercontent.com/31895946/30335672-e6313976-97da-11e7-8f57-19ecb9c86a8d.png)

These are the files i added.

![grial-starter-files](https://user-images.githubusercontent.com/31895946/30335580-ad23952a-97da-11e7-815b-144a4955c0c4.png)

**Comment by LeoHere** [comment]
@qaliwebguru the `WalkthroughPage` assumes you are displaying it as a modal (i.e. on top of another page). Thus when the wizard ends a `PopModal` is performed. In your case you are setting it as the `MainPage`, thus the error.

You have two options:
- use another page as the `MainPage` and use `PushModal` to display the walkthrough.
- change the implementation of the Walkthrough to change the MainPage when it concludes.

Probably the first one will gives you a smother transition.

Hope it helps.

**Comment by qaliwebguru** [comment]
Thanks. You are right. I am going to try. 

Generally apps shows Splash/Walkthrough screens and at the end Login screen is presented. On Successful login, the dashboard page is presented. 

Looks like GrialKit needs good amount of change in implementation to achieve above because you put login in Navigation and RootPage is involving welcome and dashboard page directly.
