### ISSUE TITLE
Ios Debug not working.

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#243]
Hey, I am having trouble debugging the project on ios. My grial project package name includes an underscore., which is against apple's allowed characters for the bundle identifier.
![issue](https://user-images.githubusercontent.com/14857549/30510122-e05f5664-9adb-11e7-8fba-f67bf80dd66a.PNG)
 Any chance that i can change my package name.

**Comment by LeoHere** [comment]
@khadeeja-alif Yes, if you didn't switch your license to production mode, you can change your project information as many times as you need in the [Grial Admin](https://uxdivers.com/secure/grial/front/). After changing it, you will need to download the license again and replace the license file included in your iOS project. Please make sure the info you set in the Grial Admin match what you put in the solution. 

Read [this](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-license-verification) and [this](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-troubleshooting-license-issues) for more details about how the license mechanism works.

**Comment by khadeeja-alif** [comment]
But what if its in Production Mode. Is there any way i can change it?

**Comment by khadeeja-alif** [comment]
Is there a way i can switch the license mode to developer and make the necessary change and switch it back to production mode? What would i have to do for that?

**Comment by LeoHere** [comment]
@khadeeja-alif there is no way to switch back to development mode once in production mode, but we can help you to do the changes in your license. Please write me to l r o d r i g u e z at uxdivers.com and include your app's new bundle identifier and package name and the order number associated to your purchase.

I'm closing the issue now. Let's continue through mail.
