### ISSUE TITLE
Integrating Grail2.0 in project

### ISSUE THREAD

**Issue by SanjeevKarki** [UXDivers/Grial-UI-Kit-Support#244]
I am getting below error while integrating Grail2.0 in my project.

09-18 13:59:11.304 I/MonoDroid(19463): UXDivers.Artina.Shared.LicenseException: Error reading license. ---> System.ArgumentNullException: Value cannot be null.
09-18 13:59:11.305 I/MonoDroid(19463): Parameter name: stream
 at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean leaveOpen) [0x00016] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-18 18:30:11.394 I/MonoDroid(31528):   at System.IO.StreamReader..ctor (System.IO.Stream stream, System.Boolean detectEncodingFromByteOrderMarks) [0x0000d] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-18 18:30:11.394 I/MonoDroid(31528):   at System.IO.StreamReader..ctor (System.IO.Stream stream) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
09-18 18:30:11.394 I/MonoDroid(31528):   at (wrapper remoting-invoke-with-check) System.IO.StreamReader:.ctor (System.IO.Stream)
09-18 18:30:11.394 I/MonoDroid(31528):   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x0000a] in <c0a342b052ca4e07993dbf355dab77fa>:0 
09-18 18:30:11.394 I/MonoDroid(31528):    --- End of inner exception stack trace ---
09-18 18:30:11.395 I/MonoDroid(31528):   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x00044] in <c0a342b052ca4e07993dbf355dab77fa>:0 
09-18 18:30:11.395 I/MonoDroid(31528):   at UXDivers.Artina.Shared.GrialKit.Init (Android.App.Activity activity, System.String licenseResourceName) [0x00006] in <9e8b28bd3bec441ebbbc11ddd16a48b5>:0 
09-18 18:30:11.395 I/MonoDroid(31528):   at SchoolWayz.Smartphone.App.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00038] in C:\Users\Schoolwayz\Source\Repos\SchoolWayz\source\apps\Smartphone.App.Droid\MainActivity.cs:53 
09-18 18:30:11.395 I/MonoDroid(31528):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <7e083afc7c9045f59e01d9c14931060d>:0 
09-18 18:30:11.395 I/MonoDroid(31528):   at (wrapper dynamic-method) System.Object:956b1c0e-be27-4732-a5c5-a2cdf177acd8 (intptr,intptr,intptr)

**Comment by LeoHere** [comment]
@SanjeevKarki please double check that:
- Your license file is included in your Android Project
- It has Build Action Embedded resource
- You are passing the correct Resource id to the `GrialKit.Init` method (see [this](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#-grial-first-run-grial-license-setup))

Please let me know how it goes.

**Comment by SanjeevKarki** [comment]
Yes, I crosscheck the value,they are exactly same as it is mentioned.
I was using Grail1.2  which was working fine.I just need to upgrade the version to Grail2.0.

**Comment by LeoHere** [comment]
The error suggest that somehow the license file can't be found.

Can you please include your invocation to `GrialKit.Init`?

**Comment by SanjeevKarki** [comment]
protected override void OnCreate(Bundle bundle)
        {
            #region Register Device for Notifications
            #endregion
            instance = this;

            base.OnCreate(bundle);
            UXDivers.Artina.Shared.GrialKit.Init(this, "Smartphone.App.Droid.GrialLicense");
            LitePlatform.Initialize(new LitePlatformAndroid());
            global::Xamarin.Forms.Forms.Init(this, bundle);
            
            LoadApplication(new App.Application(IoC.Get<SimpleContainer>()));

            string dbPath = DatabaseHelper.GetLocalFilePath("schoolwayz.db");
            Xamarin.FormsMaps.Init(this, bundle);

            FormsAppCompatActivity.ToolbarResource = Resource.Layout.toolbar;
            FormsAppCompatActivity.TabLayoutResource = Resource.Layout.tabs;

            //RegisterDevice();
        }

**Comment by LeoHere** [comment]
What is the default namespace of your Android project?

Can you attach a screenshot of your Android project, including the license file.

**Comment by SanjeevKarki** [comment]
![droid](https://user-images.githubusercontent.com/19145050/30590337-bd42ff8c-9d5b-11e7-8363-4476952e4ad1.png)

[GrialLicense.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/1314043/GrialLicense.txt)

**Comment by LeoHere** [comment]
@SanjeevKarki  

- I updated your last post and removed your Grial license. Your license file is personal and must not be shared publicly. Please avoid doing this in the future. 
- As I mentioned before, the problem is that the license can not be found. The problem is not in the license itself. That is why I'm asking for all this info. Just to help you find out what is wrong.

In the last post you show the project name and location of te GrialLicense, but not the default namespace of `Smartphone.App.Droid`. Can you check check which is the namespace?

If possible, can you attach your `Smartphone.App.Droid.csproj`. I can check get all the required info from there.

**Comment by SanjeevKarki** [comment]
[Smartphone.App.Droid.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/1314119/Smartphone.App.Droid.txt)

**Comment by LeoHere** [comment]
Your default namespace is `SchoolWayz.Smartphone.App.Droid` that is why it is not finding the embedded license.

~~~
    <RootNamespace>SchoolWayz.Smartphone.App.Droid</RootNamespace>
~~~

You should call `Init` this way:

~~~
UXDivers.Artina.Shared.GrialKit.Init(this, "SchoolWayz.Smartphone.App.Droid.GrialLicense");
~~~

**Comment by SanjeevKarki** [comment]
thanks a lot..It is working fine now.
Now i can start adding Grail2.0 components.
Thanks again.

**Comment by LeoHere** [comment]
Glad to hear that.
