### ISSUE TITLE
artina Button Shadow and text

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#246]
How can i remove the button shadow and change text to not all caps in Android.?
By default there is shadow and caps for all artina buttons. How can i style its shadow and text for different platforms. Specifically need to know about removing shadows.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif,
The upper case text on buttons is coming from Android theme (Material Design themes use upper case for button texts).

If you want to overwrite that, you will need to change the android themes in your project to specifically not use upper case.

You will need to open `Style.xml` on your `Grial.Droid` project:

```
Grial.Droid
 |_ values-v21
   |_ Style.xml
```

Then:

1. Add the following as the las item on `AppTheme` style:
```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
         ...
         <item name="android:buttonStyle">@style/Button</item>
</style>
```	
2. Add the following style to make the text lower case and the shadows removed:
```
<style name="Button" parent="Widget.AppCompat.Button">
         <item name="android:textAllCaps">false</item>
         <item name="android:stateListAnimator">@null</item>
</style>
```
These changes will affect all your buttons (default buttons and Artina:Buttons):

![image](https://user-images.githubusercontent.com/15996999/30555859-457f9366-9c7f-11e7-9af2-af1cfe899733.png)

![image](https://user-images.githubusercontent.com/15996999/30555879-572602ee-9c7f-11e7-900c-3db38fe7253f.png)

Best,
JP

**Comment by khadeeja-alif** [comment]
Hi , 
Thanks. But i did try this method. But it doesnt seem to work.
This is my styles file. Ive added the item to the last of my apptheme style.
And also mentioned the style after it.
![apptheme](https://user-images.githubusercontent.com/14857549/30579632-1befbe46-9d37-11e7-899e-855905e6f1ab.PNG)
This is my button code.
![buttoncode - copy](https://user-images.githubusercontent.com/14857549/30579646-2a373bbe-9d37-11e7-8425-517be5ba73f4.PNG)
This is the style ive defined in app.xaml for the button.
![buttonstyle](https://user-images.githubusercontent.com/14857549/30579651-2ef26c32-9d37-11e7-8dab-fd0bab884fe4.PNG)
And this is the button i get. Stil in caps
![button](https://user-images.githubusercontent.com/14857549/30579652-324d7a5c-9d37-11e7-8bde-7c425b4d292c.jpg)

**Comment by khadeeja-alif** [comment]
I think the shown grey border is the shadow because , the border colour and the textcolor is supposed to be purple. No border colour is shown in android.  In ios it works.

**Comment by jpbrocca** [comment]
Hi,
As you can see from my screenshots it works. I added that on a copy of Grial sample project without touching anything else.

Could you please confirm:

1. You made your changes on the right file:

Grial.Droid
 |_ values-v21
   |_ Style.xml

2. You performed a cleans, re build then run the app to check the changes were effectively compiled?

Best,
JP
