### ISSUE TITLE
TabControl change title

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#248]
Hi

I am using TabControl and would like to change the ContentPage's Title based on the selected tab.

Is there clicked/tapped even we can handle in order to change the title?

Thanks,
Dennis

**Comment by LeoHere** [comment]
The `TabControl` has a `TabSelected` event that is fired each time the tab changes. As a parameter it receives the selected `TabItem`.

~~~
 <tab:TabControl
	...
       TabSelected="Handle_TabSelected">
...
~~~

code behind

~~~
void Handle_TabSelected(object sender, object tabItem)
{
    // Magic goes here...
}
~~~
