### ISSUE TITLE
GrialShapes not working

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#249]
Hey,
When i try to add a GrialShapes.Checkbox to my xaml. It doesn't seem to be working.
I have done all the necessary steps to implement GrialShapes.
1.Added grialshapes.ttf to Android Assets.
![shapes1](https://user-images.githubusercontent.com/14857549/30583554-ffb33c68-9d44-11e7-9db3-4e249c30ffa8.jpg)
2.Changed the grialshapes.ttf build action properties to 'AndroidAsset' 
![shapes4](https://user-images.githubusercontent.com/14857549/30583548-ff8b8420-9d44-11e7-97c7-ee9d9566813c.jpg)
3.Added the customfontlabelrendere class to renderers in android.
![shapes2](https://user-images.githubusercontent.com/14857549/30583547-ff7ff6d2-9d44-11e7-85cf-20d72ade33ac.jpg)
4. Added the grialshapes.ttf file to Ios project Resources. and changed its build action to 'Bundle Resource'
![shapesios](https://user-images.githubusercontent.com/14857549/30583552-ffa0f206-9d44-11e7-959a-8002e326ad38.jpg)
5. Added the necessary code to info.plist file as shown below.
![shapesios1](https://user-images.githubusercontent.com/14857549/30583551-ff91a2b0-9d44-11e7-9392-db6c7d56b94a.jpg)
6. And called the grialshapes.checkbox in my xaml file.
![shapes3](https://user-images.githubusercontent.com/14857549/30583549-ff8f0dca-9d44-11e7-92c3-a77fae092ca4.jpg)
7. But this is the output i get. No checkbox comes. Both in ios and android.
![checkbox](https://user-images.githubusercontent.com/14857549/30583550-ff8f463c-9d44-11e7-827d-f48d1e9a603f.jpg)

What can be done?

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif, how are you?

From image 6 you are missing to apply the font family to your labels and that is why you don't see the right outcome.

You can do that directly through the FontFamily property or using style on App.xaml (FontIconBase).

Best
JP

**Comment by khadeeja-alif** [comment]
Great! Thanks! It worked. :) 👍
