### ISSUE TITLE
Upgrade to Xamarin Forms 2.1.0.6529 causes crash on iOS

### ISSUE THREAD

**Issue by EdHubbell** [UXDivers/Grial-UI-Kit-Support#25]
App worked fine on 2.0.1.6505, but crashes on 2.1.0.6529 with an error of 'Animation operations must be invoked on the UI thread'. 

Difficult to convince customer that this is the solution we should be using.

**Comment by EdHubbell** [comment]
Apologies for lack of detail; This seems to occur when trying to move thru a walkthrough.

**Comment by EdHubbell** [comment]
Fixed locally. In the walkthru, change 

		protected async override void OnCurrentPageChanged()
		{
			base.OnCurrentPageChanged();
			var currentStep = (WalkthroughVariantStepItemTemplate)CurrentPage;

			await currentStep.AnimateIn();
		}


to 

		protected async override void OnCurrentPageChanged()
		{
			base.OnCurrentPageChanged();
			var currentStep = (WalkthroughVariantStepItemTemplate_SG)CurrentPage;

			Device.BeginInvokeOnMainThread(() => {
				currentStep.AnimateIn();
			});
				
		}

Only problem now is that the text size is way out of proportion. The zoom looks good, but it goes too large.

**Comment by diego5** [comment]
This problem on Xamarin.Forms 2.1 is reported here:
https://bugzilla.xamarin.com/show_bug.cgi?id=39821

The workaround requires updating the AnimateItem method on WalkthroughStepItemTemplate.xaml.cs file by queing the ContinueWith code for scaling back to normal size on the UI thread like this:

```
await Task.WhenAll (new Task[] {
	uiElement.ScaleTo(1.5, duration, Easing.CubicIn),
	uiElement.FadeTo(1, duration/2, Easing.CubicInOut).ContinueWith(
	_ => 
	{ 
		Device.BeginInvokeOnMainThread(() => {
			uiElement.ScaleTo(1, duration, Easing.CubicOut);
		});
	})
});
```

Hope this helps.
