### ISSUE TITLE
TabControl navigation

### ISSUE THREAD

**Issue by Altaf07Latheef** [UXDivers/Grial-UI-Kit-Support#252]
Hey i am using tabControls and i need to programmatically navigate through tabs on a button click. Will IsSelected do the trick ? When i used it just appears selected but not opened. Or is there any other property?

**Comment by denfung** [comment]
+1

**Comment by Altaf07Latheef** [comment]
@jpbrocca Is there any way to implement this?

**Comment by LeoHere** [comment]
@Altaf07Latheef 

You can use the `SelectedIndex` property of the `TabControl`. The following code illustrates it:

~~~
void Handle_Clicked(object sender, System.EventArgs e)
{
	var index = TestTabControl.SelectedIndex;
	index++;
	if (index >= TestTabControl.Tabs.Count){
		index = 0;
	}

	TestTabControl.SelectedIndex = index;
}
~~~

**Comment by Altaf07Latheef** [comment]
@LeoHere thnx a lot. It worked 👍
