### ISSUE TITLE
Only arm build failed in xamarin forms

### ISSUE THREAD

**Issue by dev-manishpandey** [UXDivers/Grial-UI-Kit-Support#255]
When i do arm + x86 build it works fine. But when i do only arm build, it fails stating some initialization in grial is missing. And also the apk size increases like any this after adding grial.

**Comment by jpbrocca** [comment]
Hi @manishp-rapidd,

can you provide more info about the message you get about the missing initialization in Grial?

Thanks,
JP

**Comment by dirivero** [comment]
I'm closing this issue as it's very old and we didn't receive further information.  Feel free to contact us.
