### ISSUE TITLE
Support Android OS 4.x+ as they account for around 60% of total market share

### ISSUE THREAD

**Issue by Korayem** [UXDivers/Grial-UI-Kit-Support#26]
### The OS Breakdown is as follows:
![Table](https://cloud.githubusercontent.com/assets/198332/14137318/9baf9ff2-f667-11e5-9d1d-162fb33ba717.png)

![Piechart](http://chart.googleapis.com/chart?chl=Froyo%7CGingerbread%7CIce%20Cream%20Sandwich%7CJelly%20Bean%7CKitKat%7CLollipop%7CMarshmallow&chco=c4df9b%2C6fad0c&chd=t%3A0.1%2C2.6%2C2.3%2C22.3%2C34.3%2C36.1%2C2.3&chf=bg%2Cs%2C00000000&chs=500x250&cht=p)

Reference: http://developer.android.com/about/dashboards/index.html

**Comment by jpbrocca** [comment]
Hi @Korayem, how are you ?

This is solved on Grial 1.5 through AppCompatV7.
I am closing this feature request now.

Best,
JP
