### ISSUE TITLE
iOS circle image bad drawing

### ISSUE THREAD

**Issue by RasAndresI** [UXDivers/Grial-UI-Kit-Support#263]
Hi guys!

I've a little issue using Circle image in iOS.

In android the image is drawn as expected but in iOS it draws the full image. (See attached screenshots)

Please help.

Thanks in advance,

AG

![android](https://user-images.githubusercontent.com/31995162/30988192-2a3a93e8-a45f-11e7-811b-b025bd76638c.png)

![ios](https://user-images.githubusercontent.com/31995162/30988193-2a3c912a-a45f-11e7-80a1-3a2d760a348f.png)

**Comment by jpbrocca** [comment]
Hi @RasAndresI,

That is weird!
What iOS version/device are you using when you get this?

Is this happening only with that image or basically with every other image in your project?

Regards and thanks,
JP

**Comment by RasAndresI** [comment]
Hi @jpbrocca 

Thanks for your help
Yeah that's so weird.

I've seen this behavior on  ---->    iPhone 7 Plus iOS 10.3 (Simulator).
Not tested on real device yet.

Actually I'm using Circle image in another view and it's rendered as expected. (Attached screenshot)

The only problem is in the view above.

Thanks in advance.
Regards,

AG

![simulator screen shot 02 10 2017 9 14 17 a m](https://user-images.githubusercontent.com/31995162/31081960-204a1d58-a753-11e7-900d-d6f5d7ce42b3.png)

**Comment by jpbrocca** [comment]
Hi @RasAndresI, how are you?

Hmmm...it seems you are using (for the second view) the images provided with Grial sample.
My guess is that the image you are using on the first view could be causing the issue (perhaps it is too big).
Is there any change that you could send me the image to:

![image](https://user-images.githubusercontent.com/15996999/31100642-aaf88f46-a7a0-11e7-91cf-84fa9c9113a4.png)

...so I can take a look?

Regards and thanks!
JP

**Comment by RasAndresI** [comment]
i @jpbrocca, I'm fine, thanks for ask
Hope you too!

Well... Yeah, actually I'm using the sample images for the second view.
Is there a specific image size for this widget?
Cause I've implemented a Camera function that takes a photo and replace profile image.
Now I've tested on real devices:
---> Moto G4: Android 7.0 - API 24
        *Take photo on Portrait and the image appears "croped"
        *Take photo on Landscape and it is shown Ok.

----> Ipad framework 9.3
         Image always appear "croped"

PD. I've sent you an Email with the image.

Thanks!
AG

**Comment by jpbrocca** [comment]
Hi @RasAndresl, I am Fine too thanks :)

OK, this seems to be an issue with our iOS renderer. The problem is the aspect property default value.

The workaround is easy though, simply set the aspect on your xaml template code to use `AspectFill` as in the following sample:

```
<artina:CircleImage 
	x:Name="avatar"
	Source="{ StaticResource ThemeAvatarSample0Image }"
	HeightRequest="100"

	Aspect="AspectFill"

	WidthRequest="100"
	/>
```

Let me know how it goes.

Best
JP
