### ISSUE TITLE
Unable to run app after making changes in Splash png

### ISSUE THREAD

**Issue by Bel0425** [UXDivers/Grial-UI-Kit-Support#264]
Hi There,

I have modified splash.png file and after that i am getting build error (but VS doesnt show any error in error list) and not able to run app.

Please help to resolve this issue on priority as i am have to submit prototype to client.

Regards,
Salil Belapurkar

**Comment by jpbrocca** [comment]
Hi @Bel0425,
Is difficult to diagnose what could be happening with so little details. Just changing splash.png shouldn't produce any error.

Could you please let me know:

1. Is this happening both on Android and iOS?
2. Did you only change the splash.png file? You basically changed the splash.png content? I mean, you modified the original image and just saved with the same name on the same location?
3. Can you add the build error to this thread?

Best
JP

**Comment by Bel0425** [comment]
it started working after re-opening VS and Emulator.
Thank you so much for your help.
