### ISSUE TITLE
Splash screen displaying for longer time

### ISSUE THREAD

**Issue by Bel0425** [UXDivers/Grial-UI-Kit-Support#268]
I realize that App keeps showing Splash screen for longer time almost a minute and after that my login page is getting landed.

Please let me know how to reduce splash time.

**Comment by jpbrocca** [comment]
Hi @Bel0425,

Is this happening with your app or with Grial sample?
Grial sample has a lot of things inside (after all, it is just an excuse to show all what you can do) that makes it big and heavy. 
If it is happening with your app you could try to make `App.xaml` to only contain the implicit styles and base styles, then you can move the specific styles used only for your pages as (page resources). 

Also make sure to use only the Nuget packages you need (e.g.: Lottie won't be probably something you will be using so there is no need for you to include it on your App). You could also try with AOT compilation.

You can take a look at the following guideline to help you:
https://blog.xamarin.com/5-ways-boost-xamarin-forms-app-startup-time

Best,
JP

**Comment by Bel0425** [comment]
It is happening with my App.
As per your suggestion, i have moved styles to specific pages but there is no improvement.
While debugging i found that it is taking time on LoadApplication(new App()); code. 

Below is OnCreate event code:
[Activity(
		Label = "R",
		Icon = "@drawable/icon",
		Theme = "@style/Theme.Splash",
	 	MainLauncher = true,
		LaunchMode = LaunchMode.SingleTask,
		ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize
		)
	]
public class MainActivity : FormsAppCompatActivity
	{
		protected override void OnCreate(Bundle bundle)
		{
			// Changing to App's theme since we are OnCreate and we are ready to 
			// "hide" the splash
			base.Window.RequestFeature(WindowFeatures.ActionBar);
			base.SetTheme(Resource.Style.AppTheme);


			FormsAppCompatActivity.ToolbarResource = Resource.Layout.Toolbar;
			FormsAppCompatActivity.TabLayoutResource = Resource.Layout.Tabs;

			base.OnCreate(bundle);

			//Initializing FFImageLoading
			CachedImageRenderer.Init();

			global::Xamarin.Forms.Forms.Init(this, bundle);
			UXDivers.Artina.Shared.GrialKit.Init(this, "R.Droid.GrialLicense");

			FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));

			LoadApplication(new App());
		}

		public override void OnConfigurationChanged(Android.Content.Res.Configuration newConfig)
		{
			base.OnConfigurationChanged(newConfig);

			DeviceOrientationLocator.NotifyOrientationChanged();
		}

	}

**Comment by dirivero** [comment]
Hi @Bel0425,

Have you tried running the Xamarin.Forms template app that comes with Visual Studio when creating a new solution? How much does it take to load?

Regards,
Diego

**Comment by LeoHere** [comment]
Closing the issue to keep things tight. Feel free to open it again if you need to.
