### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by adamlonsdale** [UXDivers/Grial-UI-Kit-Support#27]
I'm having a great deal of trouble getting started with Grial after purchasing it today. I initially got the below error but for "colorAccent" which I resolved by upping my API level to 21 (Although there are no Xamarin Android Player machines for this API level that are also a tablet). 

Now I am experiencing the following: 
Error APT0000: No resource found that matches the given name (at 'primary' with value '@color/AccentColor'). (APT0000)

This is in my Styles.xml file that lives in the 'values' table. How do I fix this and also get this to run on KitKat?

**Comment by jpbrocca** [comment]
Hi @adamlonsdale,

Did you take a look at the provided sample with Grial?
I assume you are starting from a new project.
If that is the case, then you will need to replicate the themes structure from the sample.

On App.xaml you will find the colors resources at the top.
The first one is the AccentColor which you should set to your own color. Then follow the procedure on the documentation to compile the Colors.tt file.

Regards,
JP

**Comment by adamlonsdale** [comment]
Hey, 

I am indeed setting it up for a new project, its one that we've already done most of the iOS / Forms work for, but want to start on the Android version - so I can't modify the sample project. 

I've added references, added the two styles.xml etc. But the documentation doesn't say about adding Colors.xml / Colors.tt or bools.xml - should I add those also? The documentation isn't clear on how I get the tools menu to appear - I assume I need to set a property of the file?

**Comment by jpbrocca** [comment]
Hi,

please check the provided sample with Grial.


You will need to add to your project the files:
~~~
Colors.tt
Colors.cs
~~~
on the **PCL** folder and also on the **Android** project under:
~~~
Resources > values
~~~

Just copy those from the sample:

![image](https://cloud.githubusercontent.com/assets/15996999/14226872/22ae7a5a-f8c5-11e5-9025-8c8f960d4cc0.png)

![image](https://cloud.githubusercontent.com/assets/15996999/14226874/3700e268-f8c5-11e5-8a27-2caae99628b4.png)

Then make sure you follow the steps here:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files

https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Getting-started-adding-Grial-to-an-existing-project

Also take a look at this to understand all the theme mechanics:
http://grialkit.com/gettingstarted/theme-and-branding/

What you mean by _"the tools menu to appear"_ ?

Regards,
JP
