### ISSUE TITLE
Not able to build.  Connected to private nuget

### ISSUE THREAD

**Issue by RecipeSavants** [UXDivers/Grial-UI-Kit-Support#270]
I have sorted out the private nuget issues and have restored packages but I have over *400* build errors.  What should I try next ?

![image](https://user-images.githubusercontent.com/32582201/31298576-61fb267e-aab0-11e7-91f7-03edb79ef569.png)

**Comment by LeoHere** [comment]
@RecipeSavants the errors suggest that there was an issue restoring packages, possible Xamarin Forms packages. 

My recommendation is:
- Close VS
- Remove the packages folder (next to where the solution resides)
- Open VS and open the solution again.
- Hit Restore packages

Hope it helps.

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again if you need to.
