### ISSUE TITLE
Button type not found in gorilla player

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#275]
I'm getting this on a new page

![image](https://user-images.githubusercontent.com/1398909/31449334-41583320-ae6c-11e7-9565-35270f8b57bd.png)

**Comment by LeoHere** [comment]
@attrib75 the player you get from the store in not capable of rendering Grial stuff, you need to run Gorilla SDK embedded within Grial as we were discussing in issue #273. Once you run Grial using Gorilla Configuration all this issues should be gone.
