### ISSUE TITLE
TabControl not loading - cannot be found.

### ISSUE THREAD

**Issue by adamlonsdale** [UXDivers/Grial-UI-Kit-Support#277]
Hi,

The below error occurs immediately after I upgraded to 2.5.2. I believe this could be some kind of linker issue but can't see any custom renderers that need to be registered. I assume nothing has changed locations because the assembly browser still shows it all as being in .Tab

Position 219:22. Type TabControl not found in xmlns clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared.Tab

**Comment by LeoHere** [comment]
@adamlonsdale yes, names are the same in 2.5.2. Are you sure all the packages has been updated to 2.5.2 in all the projects?

If yes is the answer, I would recommend to:
- clean your solution
- close VS, 
- remove the packages folder 
- open your solution again
- restore packages
- rebuild.

Hope it helps.
