### ISSUE TITLE
Can't preview with Xamarin.Forms Previewer

### ISSUE THREAD

**Issue by Fatihpk** [UXDivers/Grial-UI-Kit-Support#279]
Hi there, when i download your Full Development project i cant preview the XAML pages with the Xamarin.Forms Previewer. **WHY?**

![screenshot](https://user-images.githubusercontent.com/20399409/31603640-13101d5e-b261-11e7-9664-f62585a06a79.jpg)

**Comment by LeoHere** [comment]
@Fatihpk the Xamarin.Forms Previewer has still lot of issues. In this case seems like is is not able to handle the `FFImageLoading`. Anyways, I would recommend you to use Gorilla Player to preview. Read [this](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) for an explanation of how.
Closing the issue now. Please open a new one if you have any issue using Gorilla.

**Comment by Fatihpk** [comment]
I also try the Gorilla Player but the App on the Device crashes many times thats why i stop working with it.

**Comment by LeoHere** [comment]
@Fatihpk that is weird. Did you follow the steps [this](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player)? The player from the store will not allow to preview Grial, you need the SDK as described in the document.

If you have any issue, please let me know.

**Comment by Fatihpk** [comment]
Can you pleaseee help me 😞 I am working for days now for changing this thing on your template:


I want a CustomActivityIndicator on each page and then after loading the data from the 'BindingContext = new ProductViewModel(_ProductId);' the CustomActivityIndicator must be invisible. I am working on this for weeks now :(


Can you please help me?


________________________________
Van: Leonardo Rodríguez <notifications@github.com>
Verzonden: donderdag 19 oktober 2017 02:33
Aan: UXDivers/Grial-UI-Kit-Support
CC: Fatihpk; Mention
Onderwerp: Re: [UXDivers/Grial-UI-Kit-Support] Can't preview with Xamarin.Forms Previewer (#279)

If you have any issue, please let me know.
