### ISSUE TITLE
Can't get the theme/renderer provided by Grial Kit working

### ISSUE THREAD

**Issue by yingzhox** [UXDivers/Grial-UI-Kit-Support#28]
I've created a new PCL project, and followed every step here: https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files
and here:
https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files

But my entry still looks normal, not rendered by Grial. What should I do?

**Comment by jpbrocca** [comment]
Hi @yingzhox,
Did you make sure you added all the files as in the sample provided with Grial ?

Please take a look at this related issue and make sure you have all the required files in place:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/27

Then please let me know if you still have any problem.

Best,
JP

**Comment by yingzhox** [comment]
Hi @jpbrocca ,

I've added you to my private repo, I've setup a simple project there. My app can be ran without any error, but the renderer/style does not apply. Could you please help me take a look.

Thanks!

**Comment by yingzhox** [comment]
BTW, I'm testing it in my iOS simulator

**Comment by yingzhox** [comment]
Droid looks good,but iOS still not works!

**Comment by LeoHere** [comment]
Hi @yingzhox 
You need to invoke InitializeComponent() from the AppMain constructor, before setting the MainPage property. Without it the XAML in the AppMain.xaml is not taken into account. 

Let us know if you have any other question or issue.

**Comment by yingzhox** [comment]
Awesome, it's working now, thanks guys!
