### ISSUE TITLE
Searchbar in NavigationBar (PORTABLE)

### ISSUE THREAD

**Issue by BrunoRuiz** [UXDivers/Grial-UI-Kit-Support#280]
Hello good morning...

I recently bought GrialKit and am trying to create a customNavBar, since I need to create a SearchBar inside the NavigationBar but I can not do it, in android everything is ok, but in IOS of the encounter problems ...

would it be possible for you to help me with an example?

**Comment by jpbrocca** [comment]
Hi @BrunoRuiz,

Could you provide more info about what issue are you experiencing on iOS?
Is it an issue of layout/styles or logic?
A screenshot would be also very helpful.

Best
JP

**Comment by BrunoRuiz** [comment]
Hello...

I have a CustomNavBar

<?xml version="1.0" encoding="UTF-8"?>
<ContentView 
xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
x:Class="ParoquiaNet.CustomNavBar"
xmlns:local="clr-namespace:ParoquiaNet;assembly=ParoquiaNet" 
xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared">

    <Grid 
Style="{ StaticResource CustomNavBarStyle }"
Padding="0">

        

        <Label 
HorizontalOptions="Start"
VerticalOptions="Center"
Margin="20,0"
Text="{ x:Static local:GrialShapesFont.Menu }"
FontSize="22"
TextColor="{ DynamicResource CustomNavBarTextColor }" 
Style="{ StaticResource FontIcon }">
            <Label.TranslationY>
                <OnPlatform 
x:TypeArguments="x:Double" 
iOS="10" 
Android="0" />
            </Label.TranslationY>
            <Label.GestureRecognizers>
                <TapGestureRecognizer Tapped="OnHamburgerIconTapped" />
            </Label.GestureRecognizers>
        </Label>

        <SearchBar
            HorizontalOptions="Center"
            VerticalOptions="Center"
            x:Name="ControlSearchBar"
            Placeholder="Busque sua Paróquia"
            TextColor="{ DynamicResource CustomNavBarTextColor }">

            <SearchBar.TranslationY>
                <OnPlatform 
x:TypeArguments="x:Double" 
iOS="10" 
Android="0" />
            </SearchBar.TranslationY>
            
        </SearchBar>

        

        <Label 
HorizontalOptions="End"
TranslationY="0"
Margin="20,0"
VerticalOptions="Center"
Text="{ x:Static local:GrialShapesFont.Search } " 
FontSize="22"
TextColor="{ DynamicResource CustomNavBarTextColor }" 
Style="{ StaticResource FontIcon }">
            <Label.TranslationY>
                <OnPlatform 
x:TypeArguments="x:Double" 
iOS="10" 
Android="0" />
            </Label.TranslationY>
            <Label.GestureRecognizers>
                <TapGestureRecognizer Tapped="OnSearchIconTapped" />
            </Label.GestureRecognizers>
        </Label>
    </Grid >
</ContentView>



and a contentPage with this structure

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
x:Class="ParoquiaNet.SearchParoquia"
xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
xmlns:local="clr-namespace:ParoquiaNet;assembly=ParoquiaNet"
Title="Selecione sua Paróquia">

    <Grid RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        
        <local:CustomNavBar 
Grid.Row="0"/>

    </Grid>

</ContentPage>

in my Code-Behind I simply do this

NavigationPage.SetHasNavigationBar(this, false);

in android I have the following result ...
![android](https://user-images.githubusercontent.com/1844532/31620398-ecbcc426-b275-11e7-84ef-b5160e060953.JPG)


but I have an exception in IOS

**Comment by jpbrocca** [comment]
Can you paste the iOS exception so we can take a look?

**Comment by dirivero** [comment]
I'm closing this issue sin we didn't get further information and it's a 2 year old issue. Feel free to contact us if you need help.
