### ISSUE TITLE
Android splash

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#281]
Hello,

Trying to change the Android splash.  I've changed spash_drawable to point to a different image name like so
<?xml version="1.0" encoding="utf-8" ?>
	<layer-list
	 	xmlns:android="http://schemas.android.com/apk/res/android">
		<item>
			<shape android:shape="rectangle">
				<solid android:color="@color/ComplementColor" />
				<padding 
					android:left="0dip" 
					android:top="0dip"
					android:right="0dip" 
					android:bottom="0dip" />
				</shape>
		</item>
		<item>
			<bitmap android:src="@drawable/logo"
			android:gravity="center" />
		</item>
	</layer-list>

I've also changed  style to:
 `  <Color x:Key="SplashBackgroundColor">White</Color>`

I'm sure I'm doing something wrong, any ideas? thanks

**Comment by jpbrocca** [comment]
Hello @attrib75, how are you?

What issue are you experiencing?

If it is that the image is not being displayed check the image exists on the `drawable` folders with the right name and build action.

If it is about the color, you need to compile to get the color from your XAML theme synced with `Colors.xml` on your android project.
To make sure, just open the `Colors.xml` file and you should find there the line `<color name="SplashBackgroundColor">#FFFFFF</color>`. 
**Important:** Make sure to use hexadecimal notation for your color.

More info about splash here:
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-splash-screen

Let me know how it goes.

Best,
JP

**Comment by attrib75** [comment]
Thanks, turns out I didn't have the color as hex, nor did I update this line like this
`<solid android:color="@color/SplashBackgroundColor" />`
