### ISSUE TITLE
Circle Image Question

### ISSUE THREAD

**Issue by Nobuaki-Nishi** [UXDivers/Grial-UI-Kit-Support#282]
Hello, 

We try to use <artina:CircleImage> tag to show an image rounded (circle) though, but it is shown as square. 

<artina:CircleImage
BorderColor="Blue"
Source="{StaticResource BackButtonImage}" />

We have attached the screen shot. Please find it. 

Are there any settings to use <artina:CircleImage> tag? 

Thank you for your help.
Best Regards,
Nobuaki
<img width="370" alt="simulator screen shot - iphone 8 - 2017-10-17 at 12 55 08" src="https://user-images.githubusercontent.com/6005763/31688569-99bdcc12-b341-11e7-9a7f-3d2b3ccda6de.png">

**Comment by jpbrocca** [comment]
Hi @Nobuaki-Nishi, how are you?

I am not sure what you are trying to achieve.
I just have make a quick test by capturing the back button on your screenshot and used it as the source for the `<artina:CircleImage>`. 

Then, I changed `BorderColor` to `Blue` and here is the result:

![image](https://user-images.githubusercontent.com/15996999/31730615-d730115a-b408-11e7-9f79-2e1288f6eea1.png)

Just in case, I just used the following style for my fast test:

~~~
       <Style TargetType="artina:CircleImage">
		<Setter Property="WidthRequest" Value="100" />
		<Setter Property="HeightRequest" Value="100" />
		<Setter Property="BorderThickness" Value="3" />
		<Setter Property="BorderColor" Value="Blue" />
	</Style>
~~~

...and this is the `artina:Circle` code:

~~~
<artina:CircleImage
	Source="https://user-images.githubusercontent.com/15996999/31730325-fce525e4-b407-11e7-803d-2ecb6a0a2433.png" 
	HorizontalOptions="Center"
	Aspect="AspectFill" />
~~~

**Comment by ryouojima** [comment]
Mr. jpbrocca
Hello. Thank you for your answer.
It was solved by writing the following contents in xxxx.iOS / Properties / AssemblyInfo.cs.

`[assembly: ExportRenderer (typeof (UXDivers.Artina.Shared.CircleImage), typeof (UXDivers.Artina.Shared.ImageCircleRenderer))]`

Thank you very much.

**Comment by jpbrocca** [comment]
Hi @ryouojima, how are you?
You are welcome!

Perfect! I am closing this issue then.
Feel free to reopen if needed.

Best regards,
JP
