### ISSUE TITLE
Using .Net Standard 2.0 with latest GrialKit's ResX resources

### ISSUE THREAD

**Issue by rmoquin** [UXDivers/Grial-UI-Kit-Support#283]
Hi, I purchased a Grial License probably 2 weeks ago.  I decided to try to get the downloaded samples running, which was pretty easy.  I then migrated pieces of my application into it and started adding the NuGets packages to the project.  While trying to do it, I received errors that certain libraries I was trying to add weren't compatible with the profile that the PCL was targeting.  I had been using a Shared project previously because PCLs always seem to cause me a headache, so I spent a few hours making the changes so the pcl could be used as a shared project.  Of course the ResX files were no longer able to be located.  Apparently ResX files won't work in a shared project.  It seemed like my best option might be to switch the PCL to .Net Standard 2.0 which is implemented by .NET 4.6.  After a lot of screwing around and jumping through hoops with Visual Studio and Android Oreo compatibility, I was finally able to run my solution.  After the splash screen pops up, I get the error:

System.MissingMethodException: Default constructor not found for type MyApp.Resx.AppResources

It happens in the InitComponent() of the App class.  If I put:

System.Console.WriteLine("A resource string: " + MyApp.Resx.AppResources.StringWelcomeToGrial);

Before the InitComponent(); call, the I see the proper resource print out without issues.  I'm a little puzzled as to what's going on.  I'd really like to start getting back to working on my app.  Also, I downloaded a fresh copy of the project and I converted the PCL to a .Net Standard library and then ran it.  I received the same error.  I've done a ton of research around various parts of the app to see if it might be something library related, but I'm just completely lost at how to understand what exactly is going on.  Has anyone been able to get GrialKit to work with .Net Standard 2.0? 

Thanks!

**Comment by dirivero** [comment]
Hi @rmoquin,

We are currently working to support .net standard in Grial. The workaround for that problem is this:
a) Comment this line of code in App.xaml
	<resx:AppResources x:Key="DefaultStringResources" />

b) Add this line of code after the InitializeComponent call in the App.xaml.cs
	Resources["DefaultStringResources"] = new Resx.AppResources();
 
Hope this helps.

Diego

**Comment by rmoquin** [comment]
Thanks Giego, that allowed me to at least get past the splashscreen, but then I run into other problems and the app crashes.  I remembered I had gotten this same error when I convert ed the Grial download to use a shared project instead of the PCL to avoid the dependency problem.  I reverted back to that version and sure enough, I get that same error.  I applied the above fix which allowed the project to load, but none of the text loads.  If you click the button to continue past that initial screen, the UI is blank except for the master detail button, which if clicked, brings up a blank menu.  I think some of the dependency versions got updated, maybe if I revert those back, then I can get it to work with the shared project somehow (unless the resx stuff is doomed to never work with a shared project instead of a pcl.)

**Comment by rmoquin** [comment]
I'm so confused.  I tried to back out the library versions and still get the same constructor error.  I'm really confused.  I guess I'll see if I can approach customizing this in a slower fashion since even if I don't use the new packagereference and .netstandard library stuff, I still end up with the same error after converting the pcl library to a shared project.

**Comment by jpbrocca** [comment]
Hi @rmoquin, how are you?
Sorry for the late reply on this.

We are currently working on supporting .NET Standard 2.0 on Grial.
Can you let me know if you are working on Windows or Mac?

Regards and thanks,
JP

**Comment by jpbrocca** [comment]
Hi @rmoquin, how are you?

We have added support for .NET Standard to Grial.

You can check more details here:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/336

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it if you need so.
