### ISSUE TITLE
Label Wrapping incorrectly

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#284]
Working on Grial SignUpPage and IOS wrapping label incorrectly. Last two words going second line as can be seen in attached image... 

![image](https://user-images.githubusercontent.com/31895946/31719447-698a405a-b40b-11e7-96f3-e3e04eb2cd5f.png)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru,

This is how Xamarin Forms is handling the text.
Depending on what you want to achieve there are a few things you can do (**Note:** I am editing Grial's `SignUpPage.xaml`, just added a green `BackgroundColor` to help to see the text boundries) :

1. If you want to get everything on a single text line, the only way would be to make the font size smaller and also change the `LineBreakMode` to `NoWrap`:

    ![image](https://user-images.githubusercontent.com/15996999/31729705-26b84dda-b406-11e7-9903-9df61172c140.png)


2. If you want to make the text to go to the right margin then continue on next line, change `LineBreakMode` to `NoWrap`, then add the character `&#x0a;` to force a line break:
    
    ![image](https://user-images.githubusercontent.com/15996999/31730106-4796ba0e-b407-11e7-9a6f-8e7d0a6189ce.png)

Best,
JP

**Comment by qaliwebguru** [comment]
Thanks a lot for your solution. I already tried both but not working for me. Obviously first fix is not for us as it will clip some letters on some devices.

The second fix is good but it is not good for Tablets to force the linebreak.

**Comment by jpbrocca** [comment]
You cool use Grial responsive helpers to use one string or the other if you are on a phone | tablet or if you are on portrait | landscape orientation.

Check the responsive helpers sample in Grial.

Best
JP

**Comment by jpbrocca** [comment]
You could use Grial responsive helpers to use one string or the other if you are on a phone | tablet or if you are on portrait | landscape orientation.

Check the responsive helpers sample in Grial.

Best
JP
