### ISSUE TITLE
Gorilla Embedded player XHR poll error 

### ISSUE THREAD

**Issue by devp2017** [UXDivers/Grial-UI-Kit-Support#285]
When launching my application using the embedded gorilla player:

- if i choose a server (pc) to connect to. i get the following error : Could not establish the connection with the server (reason: xhr poll error)

If anyone can help me please

**Comment by LeoHere** [comment]
@devp2017 some questions:

- Are you running the player app in the simulator or device? iOS or Android? Please provide info about which simulator/device, OS Version, etc
- Do you have the chance to test in a different device? (just to see if it is device specific)
- Which version of Windows are you using? Which version of Gorilla?
- Please, send me the gorilla player log to l r o d r i g u e z at uxdivers.com.

**Comment by devp2017** [comment]
- I am using Android and I tried it on both Android 4.4 and Android 8.0

- I am already testing it on 2 different devices

- I am using Windows 10 and Gorilla 1.1.0.4 

- Email sent

**Comment by jpbrocca** [comment]
Closing this bug since it is not about Grial.
Please use  https://github.com/UXDivers/Gorilla-Player-Support
