### ISSUE TITLE
how to add new GrialShapesFont for my requirement 

### ISSUE THREAD

**Issue by azharuddinsayed** [UXDivers/Grial-UI-Kit-Support#286]
can you let me know how i can add new GrialShapesFont according to my custom requirement which is not available in the list given by you in the GrialShapesFont class.

**Comment by jpbrocca** [comment]
Hi @azharuddinsayed,

You should not add icons to that font, instead, you should create your own one with your icons and change the `FontIcon` style on `App.xaml` to use it. 

Please, have a look at the documents about this topic:
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-using-font-icons-adding-your-own-icon-font-to-you-app

Best,
JP
