### ISSUE TITLE
Error: [0:] SetValue: Can not convert Bold to type 'System.Enum'

### ISSUE THREAD

**Issue by rmoquin** [UXDivers/Grial-UI-Kit-Support#287]
I was able to get a .NET 4.7 library created, added all the dependencies that the shared PCL I downloaded had, and I copied over all the resources, so it's virtually the same.  I found another way to get the ResX file to cooperate, so now I'm at the point where the first screen loads up fine (after the splash screen).  The See our Walkthrough screens seem mostly ok, but when I hit "Browse our Samples", I get sent to a blank page.  The menu works for the master page and I see the items.  I can select some of them without the app crashes.  During the app start up and while selecting around it (to see if things in general seem to be working):

I keep seeing this error: [0:] SetValue: Can not convert Bold to type 'System.Enum'

This error also seems to eventually cause the app to crash...there is no stacktrace I can find so I'm not sure where it's happening.  Can anyone offer any clues on that one?  Maybe after that, I'll have a project that will support my dependencies so I can start customizing.

Thanks!

**Comment by LeoHere** [comment]
This issue is old. I guess you already found a solution for it or you switch to out Net Standard version of the libraries.

Anyways, closing the issue. Please feel free to reopen it if you need so.
