### ISSUE TITLE
TableView is not showing full screen

### ISSUE THREAD

**Issue by crakhi** [UXDivers/Grial-UI-Kit-Support#288]
Hi Team,
I just created a new page and added table view with some cells. When I load the page the tableView is covered only half of the screen and having scrollbar. I want it to be displayed in the full screen, what do I need to change, this doesn't seems to be the default xamarin style.

**Comment by jpbrocca** [comment]
Hi @crakhi, how are you?

Is there a chance you could share your code and some screenshots showing your current result and what you need to achieve?

Thanks!
JP

**Comment by crakhi** [comment]
Hi @jpbrocca I;m doing good!

Here is the code and screenshot attached. If you see the screen shot the screen is not filled and a scrollbar is shown. I want the content to scroll in the FULLSCREEN

> <ContentPage.Content>
>         <TableView Intent="Settings"  VerticalOptions="StartAndExpand" >
>             <TableRoot>
>                 <TableSection Title="Contact Details">
>                     <EntryCell Placeholder="First Name" Text="{Binding LoadingMessage, Mode=TwoWay}" Label="First Name "></EntryCell>
>                     <EntryCell Placeholder="Last Name" Text="{Binding Person.LastName, Mode=TwoWay}" Label="Last Name "></EntryCell>
>                     <EntryCell Placeholder="Mobile" Text="{Binding Person.Mobile, Mode=TwoWay}" Label="Mobile"  Keyboard="Numeric"  ></EntryCell>
> 
>                 </TableSection>
>                 <TableSection Title="Address Details">
>                     <EntryCell Placeholder="First Name" Text="{Binding Person.FirstName, Mode=TwoWay}"></EntryCell>
>                     <EntryCell Placeholder="Last Name" Text="{Binding Person.LastName, Mode=TwoWay}"></EntryCell>
>                     <EntryCell Placeholder="Mobile" Text="{Binding Person.Mobile, Mode=TwoWay}" Label="Mobile"  Keyboard="Telephone"  ></EntryCell>
>                    
>                 </TableSection>
>             </TableRoot>
>         </TableView>
>     </ContentPage.Content>
![tableview](https://user-images.githubusercontent.com/12002009/31838270-a7af278e-b5f9-11e7-86ff-9ed96b37d4f0.jpeg)

**Comment by jpbrocca** [comment]
Hi again @crakhi,
I had to edit your comment since the code was not being displayed.

I guess your problem is with `VerticalOptions="StartAndExpand"`...you should set it to `Fill` which is default behavior (so you can remove that if you want). 
That way you should see everything OK (No scroll and full screen).

Best,
JP

**Comment by crakhi** [comment]
Yeah! I dont know how I missed it! Thanks!

**Comment by jpbrocca** [comment]
No worries, that happens all the time :)

Best,
JP
