### ISSUE TITLE
upgrade build to .net standard library?

### ISSUE THREAD

**Issue by wiltwitt** [UXDivers/Grial-UI-Kit-Support#290]
Will you guys upgrade your Grial starter project builder tool to use .net standard library?

thanks

**Comment by jpbrocca** [comment]
Hi @wiltwitt, how are you?

We are currently working on it :)

Best,
JP

**Comment by wiltwitt** [comment]
Sweet, when do you think? months or weeks?

**Comment by jpbrocca** [comment]
Weeks ;)

**Comment by southrock70** [comment]
Great that this in the workings, any planned dates for .NET Standard support?

**Comment by ferastaleb** [comment]
Hi, Any planned dates for .NET Standard support ?

**Comment by jpbrocca** [comment]
Hi guys, just to let you know we have added support for .NET Standard.

More details here:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/336

Best,
JP

**Comment by southrock70** [comment]
Great will download and test. Nice work!!!
