### ISSUE TITLE
Error on localisation 

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#291]
I am trying following:
`<Label
                                x:Name="QuestionTwoLabel"
                                FontSize="Large"
                                HorizontalOptions="{artina:OnOrientationLayoutOptions PortraitPhone=StartAndExpand,
                                                                                      LandscapePhone=StartAndExpand,
                                                                                      PortraitTablet=CenterAndExpand,
                                                                                      LandscapeTablet=CenterAndExpand}"
                                LineBreakMode="NoWrap"
                                Text="{artina:OnOrientationString Portrait=How do you feel about your&#x0a;weight?,
                                                                  Landscape={artina:Translate Key=OnBoardingViewStringQ2}}"
                                TextColor="White" />
`

===================== Which gives me following error===============

Severity	Code	Description	Project	File	Line	Suppression State
Error		Position 292:33. No property, bindable property, or event found for 'Landscape', or mismatching type between value and property.	

============================== if I remove "{artina:Translate Key=OnBoardingViewStringQ2}" and replace with text, it works.

**Comment by jpbrocca** [comment]
Hi @qaliwebguru,
The conjunction of a responsive helper an `artina:Translate` is not supported, however, you can simply achieve what you need using two labels and making them visible through a responsive helper:

~~~
<!-- Portrait Visible Label -->
<Label 
	x:Name="QuestionTwoLabel0" 
	Style="{ StaticResource QuestionLabelStyle }"
	Text="How do you feel about your&#x0a;weight?"
	IsVisible="{
		artina:OnOrientationString 
			Portrait=True, 
			Landscape=False
		}" 
/>

<!-- Landscape Visible Label -->
<Label 
	x:Name="QuestionTwoLabel1" 
	Style="{ StaticResource QuestionLabelStyle }"
	Text="{ artina:Translate Key=OnBoardingViewStringQ2 }" 
	IsVisible="{
		artina:OnOrientationString 
			Portrait=False, 
			Landscape=True
		}" 
/>
~~~

To make code more legible/maintainable I just moved the other styling properties to a common `<Style>` which you can add to your Page's resources:

~~~
<Style x:Key="QuestionLabelStyle" TargetType="Label">
	<Setter 
		Property="HorizontalOptions" 
		Value="{
			artina:OnOrientationLayoutOptions 
				PortraitPhone=StartAndExpand, 
				LandscapePhone=StartAndExpand, 
				PortraitTablet=CenterAndExpand, 
				LandscapeTablet=CenterAndExpand
			}" />
	<Setter Property="FontSize" Value="Large" />
	<Setter Property="LineBreakMode" Value="NoWrap" />
		
</Style>
~~~

Best,
JP

**Comment by qaliwebguru** [comment]
Thanks a lot.

**Comment by jpbrocca** [comment]
You are welcome!

Please, remember to close the issues you have opened if the proposed solution worked for you.
We need help to keep things tidy :)

Thanks in advance!
JP
