### ISSUE TITLE
Title bar does not show Back-Button anymore

### ISSUE THREAD

**Issue by K232** [UXDivers/Grial-UI-Kit-Support#292]
Hi all,
I'm using Grial 1.5 and could not update in my project, so I hope I still get support for release 1.5.

I'm not sure whether it's related to iOS 11 but I haven't seen it before and on Android it's working fine so the problem probably exists since upgrade to iOS 11: The "Back"-Button in the Title bar is not shown in iOS anymore. The functionality itself does work, so I could click on the blank space and navigation goes back to previous page, but there is no BACK Indicator shown. So users might be confused.

Example in Grial Demo: From "Dashboard" click on any item, e.g. "Ecommerce". On "Ecommerce" there is no "Back" indicator, but you could click on the empty space and come back to the "Dashboard" Page.

Any idea how to get the "Back" back ;-) ? I've created a new sample project without Grial and there everything is working fine, "Back" is displayed as expected.

Many thanks!
![simulator screen shot - iphone 5s - 2017-10-25 at 16 35 42](https://user-images.githubusercontent.com/685016/32004724-bd0ac6d6-b9a2-11e7-934b-d36ea02faaf5.png)

**Comment by pboisso** [comment]
Got the same behaviour here on iOS11.  It looks like the icon is the same color than the header background.

**Comment by K232** [comment]
Any idea how to change the icon (color) ?

**Comment by pboisso** [comment]
Not found it yet, hoping for Grial to help as well.  Thanks for opening this issue.

**Comment by K232** [comment]
OK, so let's hope together :-) Don't know whether this does help for you (at least it did not help for me because I already had this key in my info.plist) [App icons missing after upgrading to iOS 11/Xamarin](https://blog.rthand.com/post/2017/10/17/app-icons-missing-after-upgrading-to-ios-11-xamarin.aspx)

**Comment by pboisso** [comment]
Sounds to me like there might be something missing in Appearance.cs

**Comment by jpbrocca** [comment]
Hello @K232 and @pboisso, how are you guys?
This issue is just a matter of colors so as @K232 correctly pointed you can still click and get back to the previous page.

Check the following link for a workaround:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/254

Let me know how it goes.

Best,
JP

**Comment by K232** [comment]
Brillant JP! Fixed it for me. Many thanks for fast support!

**Comment by jpbrocca** [comment]
You are welcome!
