### ISSUE TITLE
Margin & padding with responsive helper

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#293]
Is it possible to do something like this?

`<Grid Grid.Row="0" Grid.ColumnSpan="2"  Margin="{
		artina:OnOrientationDouble 
			PortraitPhone=16,0,0,10,
                                                                  LandscapePhone=18,0,0,10,
                                                                  PortraitTablet=20,0,0,10,
                                                                  LandscapeTablet=22,0,0,10
		}" >`

**Comment by jpbrocca** [comment]
Yes

**Comment by qaliwebguru** [comment]
Thanks but i don't think it works. There is definitely some issue with this. 

`<Grid Grid.Row="0" Grid.ColumnSpan="2"  Margin="{ artina:OnOrientationDouble PortraitPhone=0,10,0,0, LandscapePhone=0,10,0,0, PortraitTablet=0,50,0,0, LandscapeTablet=0,50,0,0 }" >`

The margin i am looking for on Tablet isn't showing. 

However, it is interesting to mentions that the first value (if given) probably is picked and applied to all around the grid. So for example in the following case, i can see 50 margin all around the grid on tablet.

`<Grid Grid.Row="0" Grid.ColumnSpan="2"  Margin="{ artina:OnOrientationDouble PortraitPhone=0,10,0,0, LandscapePhone=0,10,0,0, PortraitTablet=50,0,0,0, LandscapeTablet=50,0,0,0 }" >`

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?

You are absolutely right...my bad.
The problem is that the `Margin` type is `Thickness`. 
I assumed that providing each value like this should work, but it is not the case:
~~~
<Grid>
	<Grid.Margin>
		<Thickness 
			Left="{ 
				artina:OnOrientationDouble 
					PortraitPhone=20, 
					LandscapePhone=20, 
					PortraitTablet=20, 
					LandscapeTablet=20 
			}"
			Top="..."
			Right="..."
			Bottom="..."
		/>
	</Grid.Margin>
</Grid>
~~~

The good news is thanks to your issue we have added the `OnResponsiveThickness` responsive helper, however, it will take a few days to be added and released to `artina` dlls.

Meanwhile, what you can do is to handle this in your view model with a binding.
You can use the class `UXDivers.Artina.Shared.ResponsiveHelper` to detect when there is a change in orientation by listening to the `ResponsiveHelper.Orientation.OrientationChanged` event.

Let me know how it goes.

Best,
JP

**Comment by qaliwebguru** [comment]
Thanks a lot. Good to know that you will add new responsive helper. Great.

I wrote following code in my viewmodel and bind the margin but it doesn't have any impact. Not sure why?

<Grid Margin"{Binding SliderGridMargin}"></Grid>
I also tried 
<Grid Margin="{Binding SliderGridMargin, Mode=TwoWay}"></Grid>


`private void Orientation_OrientationChanged(object sender, EventArgs e)
        {
            if (Device.Idiom == TargetIdiom.Tablet && ResponsiveHelper.Orientation.IsLandscape)
            {
                SliderGridMargin = "0,50,0,0";
            }
            else if (Device.Idiom == TargetIdiom.Tablet && ResponsiveHelper.Orientation.IsPortrait)
                SliderGridMargin = "0,80,0,0";
            else
                SliderGridMargin = "0,10,0,10";            
        }`

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?
The update is ready, to use it you must allow your visual studio to see the pre release packages, then update to `2.5.14-RC2` version.

Then, in your xaml you will be able to use the new responsive helper like this:
~~~
<Grid 
     Margin="{ 
       artina:OnOrientationThickness 
         PortraitPhone='10,0,0,0', 
         LandscapePhone='10,0,0,0', 
         PortraitTablet='50,0,0,0', 
         LandscapeTablet='50,0,0,0' 
     }" 
>
~~~

Let me know how it goes.

Best,
JP

**Comment by qaliwebguru** [comment]
Brilliant. Thanks a lot.
