### ISSUE TITLE
Splash screen with Localised text ?

### ISSUE THREAD

**Issue by MichelMatthey** [UXDivers/Grial-UI-Kit-Support#294]
I need to be able to add some text to the splash screen and I need to use i18 to translate it before it gets there, fairly simple but I can't seem to see where and how it is done please ?

**Comment by jpbrocca** [comment]
Hi @MichelMatthey,

The splash screen provided with Grial only supports an image. So if you have the different localized images and you follow this guideline:

https://developer.xamarin.com/guides/xamarin-forms/advanced/localization/#Localizing_Platform-Specific_Elements

...you should be able to display the right splash image (with its localized texts inside).

Hope that helps.

Regards
JP

**Comment by MichelMatthey** [comment]
Hi,
No, this doesn't help as I am already using the translation from the PCL but here it is adding translated texts to the Splash screen which I need. The splash screen is an xml file in the Android and IOS implementations, and as such it doesn't seem to allow for anything else but images.
Can you please give me an example (code) on how I can:1) Add a fixed piece of text below my splash image2) How the translation works as this is not in the PCL where all my language resources are 
Please see the current Splash screen, the desired splash screen and the splash xml files attached...

Thanks
Michel
    On Thursday, 26 October 2017, 10:18:57 pm AEDT, jpbrocca <notifications@github.com> wrote:  
 
 
Hi @MichelMatthey,

The splash screen provided with Grial only supports an image. So if you have the different localized images and you follow this guideline:

https://developer.xamarin.com/guides/xamarin-forms/advanced/localization/#Localizing_Platform-Specific_Elements

...you should be able to display the right splash image (with its localized texts inside).

Hope that helps.

Regards
JP

**Comment by MichelMatthey** [comment]
<img width="137" alt="splash" src="https://user-images.githubusercontent.com/7455699/32052679-c4065b1e-baa4-11e7-814b-db779efe973d.png">


<img width="218" alt="currentsplashscreen" src="https://user-images.githubusercontent.com/7455699/32052611-92d9c03a-baa4-11e7-947e-a0b53f56df27.png">
<img width="218" alt="desiredsplashscreen" src="https://user-images.githubusercontent.com/7455699/32052612-93961690-baa4-11e7-8be4-384204b691a3.png">
