### ISSUE TITLE
Hambuger Menu

### ISSUE THREAD

**Issue by QamarAftab** [UXDivers/Grial-UI-Kit-Support#296]
![untitled](https://user-images.githubusercontent.com/32302413/32056071-2551cad4-ba7d-11e7-915e-c1faba2af697.png)
Hambuger Menu Icon Not Display in IOS .. I Also check your Full version . but nothing is display .

**Comment by jpbrocca** [comment]
Hi @QamarAftab, how are you?

Please check the following link for a workaround:
#254

I am closing this issue to keep things tidy, but in case you could have more issues related, please re-open.

Best,
JP

**Comment by QamarAftab** [comment]
Thanx its Working :)
