### ISSUE TITLE
Using AnyHUD and Acr.Dialog results in wide dialogs

### ISSUE THREAD

**Issue by logikonline** [UXDivers/Grial-UI-Kit-Support#297]
I use Acr.Dialog in many projects, the ShowLoading stretches instead of being normally formatted and it only seems to be an issue when I use the Grial library.  I cannot seem to find where it may be causing the issue.

UserDialogs.Instance.ShowLoading();

Can you assist in seeing what Style may be causing the stretch.

https://www.screencast.com/t/PxzTb5JSp

**Comment by jpbrocca** [comment]
Hi @logikonline, how are you?

Any chance you could send me by email your code or project details to:

![image](https://user-images.githubusercontent.com/15996999/32063926-d9be331a-ba4e-11e7-93bc-b0892f248528.png)

That way will be faster to find the cause and provide a fix.

Regards and thanks,
JP

**Comment by logikonline** [comment]
any update on this?

**Comment by jpbrocca** [comment]
Hi @logikonline, how are you?

Sorry for the delay on this.
I have sent you an email with the explanation about how to fix this issue, but I am going to leave it here in case someone else could have the same issue.

* Open the following file in your Android project:
   ~~~
   Grial.Droid
    |_ values-v21
      |_ Style.xml
   ~~~
* Find `AppTheme.Dialog` Style and change it to be:
   ~~~
    <style name="AppTheme.Dialog" parent="Theme.AppCompat.Light.Dialog">
   ~~~
   ...so it should be like the following:
   ![image](https://user-images.githubusercontent.com/15996999/32386646-adf3c742-c0a0-11e7-8e9f-cbf767551fd9.png)

* The final result should look like this (Here I just changed accent color to be blue just for testing purposes)
![image](https://user-images.githubusercontent.com/15996999/32386619-981cfc04-c0a0-11e7-9d23-b44a1bfecda3.png)

Best regards and thanks!
JP
