### ISSUE TITLE
Droid build problem when building on another PC: Resource.Drawble does not contain a definition for ...

### ISSUE THREAD

**Issue by yingzhox** [UXDivers/Grial-UI-Kit-Support#30]
Hi,

My project builds fine on one machine, but when I try to build the same solution on another machine, I got a lot of errors in Dorid project's Resource.Designer.cs, like:
````
Error	CS0117	'Resource.Drawable' does not contain a definition for 'ic_setting_dark'	DxuetangX.Droid
````
In line:
````
global::UXDivers.Artina.Shared.Resource.Drawable.ic_setting_dark = global::DxuetangX.Droid.Resource.Drawable.ic_setting_dark;
````

And a few others, is there anything wrong with my settings?

**Comment by yingzhox** [comment]
Here are a few other lines that has same error:
````

			global::UXDivers.Artina.Shared.Resource.Dimension.design_tab_min_width = global::DxuetangX.Droid.Resource.Dimension.design_tab_min_width;
			global::UXDivers.Artina.Shared.Resource.Dimension.dialog_fixed_height_major = global::DxuetangX.Droid.Resource.Dimension.dialog_fixed_height_major;
			global::UXDivers.Artina.Shared.Resource.Dimension.dialog_fixed_height_minor = global::DxuetangX.Droid.Resource.Dimension.dialog_fixed_height_minor;
			global::UXDivers.Artina.Shared.Resource.Dimension.dialog_fixed_width_major = global::DxuetangX.Droid.Resource.Dimension.dialog_fixed_width_major;
			global::UXDivers.Artina.Shared.Resource.Dimension.dialog_fixed_width_minor = global::DxuetangX.Droid.Resource.Dimension.dialog_fixed_width_minor;
````

**Comment by yingzhox** [comment]
Build settings:
Compile using Android version: Use Latest Platform (Android 6.0 (Marshmallow))
Minimum Android to target: Android 4.0.3 (API Level 15 - Ice Cream Sandwich))
Target Android Version: Use Compile using SDK version

**Comment by yingzhox** [comment]
I'm using Xamarin.Forms 2.2, it's not compatible with Grial currently and I have to downgrade it to 2.0. Any plan to support it?

**Comment by LeoHere** [comment]
Hi,

We have plans to move to 2.1 around Evolve timeframe. 2.2 is still on alpha, we will add support for it once it reaches RTM state.

Regarding the issue with resources. Are you still experiencing those issues? 

These resources issues are very annoying. They could happen from time to time on any Xamarin Android based project, usually after your update Xamarin Packages and those are not uniformly updated accross all dependencies.

Best,
Leo

**Comment by yingzhox** [comment]
Yes, it works fine with 2.0, thanks!
