### ISSUE TITLE
Two status bar 

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#302]
Hi,

I have added Grial rootPage for navigation in my project. It is showing two status bars. Any clue why its doing it?

![image](https://user-images.githubusercontent.com/31895946/32134230-96268344-bbe0-11e7-88a7-37f8fa562b12.png)

**Comment by logikonline** [comment]
You appear to be placing a navigation page inside of a navigation page.

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?

What @logikonline is pointing is correct, please make sure to use only one at a time.

Best,
JP
