### ISSUE TITLE
Grial App Icon positioning not working??

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#303]
Can you please have a look the following screenshot? The icons are dis positioned and badge circle is cut off from right and bottom.

The same issues is coming on Card View page.

I took screenshot from your App. I tested on S8+ & Nexus 4.

![screenshot_20171031-154634](https://user-images.githubusercontent.com/31895946/32234503-e89d021c-be54-11e7-8548-20d6a8c0b803.png)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?

Wow, that is really weird.

Is this happening only on that screen or did you find the same issue on others?

Thanks,
JP

**Comment by qaliwebguru** [comment]
Thanks for the reply. It is not happening all the time on all the devices. I see it working as well but some times we come across broken "Icon Category" & "Dashboard Page" as above in my attached screenshot. Its hard to tell you exact scenario but you can try like going off the screen and then opening again... But we definitely see this in your app installed from the play store and it is giving us exact same problem in the gorilla-starter project.

**Comment by qaliwebguru** [comment]
Just to update you.

1- Badge issue is definitely is there if you check on S8+.
2- If you navigate to Icons Category page and then press home button and go to some other app and then press app stack button and select Grial app to open. The icon category page will show you that all the icons are moves up.

**Comment by qaliwebguru** [comment]
and just to let you know some times it breaks the badge as well. You can see in second row. 14 is broken. 


![screenshot_2017-11-03-10-48-38](https://user-images.githubusercontent.com/31895946/32371541-2d75c654-c089-11e7-831a-393edffc98d8.png)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, 
thanks for the details.

I am trying to reproduce the issues you mentioned.
Can you let me know which flavor of Grial are you using? (i.e.: Grial Pro + RTL, Grial Standard, etc).
There are different combinations I need to test to make sure.

Also, can you let me know your:
- Xamarin Forms version
- Grial Version

Best regards and thanks,
JP

**Comment by qaliwebguru** [comment]
Thanks for your reply. 

1- Grial Pro + RTL
2- Latest version of Grial
3- xamarin forms version 2.4.0.282

**Comment by foswha** [comment]
Hello, it happens with the Samsung S8 +, this image is from the downloaded application from google play

![23261837_1712205145491136_2020546327_o](https://user-images.githubusercontent.com/31733735/32408381-d03dcd56-c164-11e7-8fcc-5c6efa247568.png)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?

We couldn't reproduce the bug exactly as you described in your steps, but at some point we get things with bad alignment too.

It seems this is caused by Xamarin Forms:
https://bugzilla.xamarin.com/show_bug.cgi?id=49311

The workaround is to change `VerticalTextAlignment` and `HorizontalTextAlignment` -on the problematic `<Label>`- to its counterpart using `VerticalOptions` and `HorizontalOptions`.

Can you send me an email to:
![image](https://user-images.githubusercontent.com/15996999/32743110-452cc262-c88a-11e7-8646-037174ecbc13.png)


...so I can send you the modified templates with the fix?

Regards and thanks,
JP
