### ISSUE TITLE
Gorilla Build Config Not Appearing

### ISSUE THREAD

**Issue by webmasterdevlin** [UXDivers/Grial-UI-Kit-Support#304]
Hi guys. The full demo can be built in Gorilla SDK, while the starter kit would not even though I aldready installed the Gorilla SDK Nuget in both in Android and iOS. I even copied the GorillaSdkHelper and Gorilla.json from the full demo., but still doesn't work.

Here are the screenshots of full demo that has Gorilla build config and the starter that doesn't have.
![capture1](https://user-images.githubusercontent.com/22025912/32358990-3e223bbc-c085-11e7-9390-8f5c62c05118.PNG)

![capture](https://user-images.githubusercontent.com/22025912/32358995-488136e4-c085-11e7-88bb-9f2349c101f1.PNG)

**Comment by webmasterdevlin** [comment]
The Starter or bare-minimum project doesn't have the Gorilla build config. How can I fix it?

**Comment by jpbrocca** [comment]
Hi @webmasterdevlin, how are you?

If you take a look at the docs:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player

...you will find info about how to download your Grial project with Gorilla SDK pre configured (even with the starter project).

Just check the download dropdown and you will find there is an option: **Grial Starter - Gorilla Ready** .
![](http://52.10.147.219/system/uploads/images/download-options.png)

Best,
JP

**Comment by webmasterdevlin** [comment]
Thanks. But unfortunately, I don't have an access to that page. Only my boss. In addition, I already spent a lot of time in my current project. 

Is there a way for me to include it in my existing project?

**Comment by webmasterdevlin** [comment]
@jpbrocca , I appreciate your help. I hope it is possible. This will save me a lot of time.  Thank you.

**Comment by jpbrocca** [comment]
Did you check the Gorilla SDK docs?
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK

Probably you missed a step while copying from full sample?

Hope that helps!
JP

**Comment by webmasterdevlin** [comment]
Copied this. 
           FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));


			_locale = Resources.Configuration.Locale;

            //			LoadApplication(new App());

            LoadApplication(UXDivers.Gorilla.Droid.Player.CreateApplication(
                this,
                new UXDivers.Gorilla.Config("Good Gorilla")
                    // Register Grial Shared assembly
                    .RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>()
                    // Register UXDivers Effects assembly
                    .RegisterAssembly(typeof(UXDivers.Effects.Effects).Assembly)
                    // FFImageLoading.Transformations
                    .RegisterAssemblyFromType<FFImageLoading.Transformations.BlurredTransformation>()
                    // FFImageLoading.Forms
                    .RegisterAssemblyFromType<FFImageLoading.Forms.CachedImage>()
            ));

**Comment by webmasterdevlin** [comment]
It says Additional SDK configuration needed on my screen.

**Comment by webmasterdevlin** [comment]
Here's my AssemblyInfo.
[assembly: AssemblyTitle (AssemblyGlobal.ProductLine + " - " + "Grial Xamarin.Forms UIKit")]
[assembly: AssemblyConfiguration (AssemblyGlobal.Configuration)]
[assembly: AssemblyCompany (AssemblyGlobal.Company)]
[assembly: AssemblyProduct (AssemblyGlobal.ProductLine + " - " + "Grial Xamarin.Forms UIKit")]
[assembly: AssemblyCopyright (AssemblyGlobal.Copyright)]
[assembly: XamlCompilation (XamlCompilationOptions.Compile)]
[assembly: UXDivers.Artina.Shared.GrialVersion("2.5.0.0")]

**Comment by webmasterdevlin** [comment]
If I did it correctly, then perhaps my phone is the one that has a problem.

**Comment by jpbrocca** [comment]
@LeoHere, can you help @webmasterdevlin?
Regards and thanks
JP

**Comment by jpbrocca** [comment]
@webmasterdevlin but do you see the 'Gorilla' option on the Visual Studio dropdown then?

Are you running Grial with Gorilla SDK on your phone and you can't preview? If that is the case then this could be a connectivity issue and I can point you to the docs about troubleshooting that:
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Troubleshooting-Connectivity

If not, then you have two options:

1. Ask your boss to download for you the starter with Gorilla.
2. Wait for @LeoHere's guidance.

Sorry for not being of much help. Probably I could be more helpful about XAML issues 😀

Best regards
JP

**Comment by webmasterdevlin** [comment]
Are you running Grial with Gorilla SDK on your phone and you can't preview?  Yes.

I'm seeing immediate changes on the text when I edit it. Is that the expected outcome?

However, I could not navigate while on the preview.

I can't also preview the Master Page. Only the Detail Page? Is there a special requirement in Master Page? Thanks for your help.

**Comment by webmasterdevlin** [comment]
I copied this from the Full and pasted it to Starter not Gorilla ready.

public class MainActivity : FormsAppCompatActivity
    {
		private Locale _locale;

        protected override void OnCreate(Bundle bundle)
        {
			// Changing to App's theme since we are OnCreate and we are ready to 
			// "hide" the splash
			base.Window.RequestFeature(WindowFeatures.ActionBar);
			base.SetTheme(Resource.Style.AppTheme);

			FormsAppCompatActivity.ToolbarResource = Resource.Layout.Toolbar;
            FormsAppCompatActivity.TabLayoutResource = Resource.Layout.Tabs;

			base.OnCreate(bundle);

			// Initializing FFImageLoading
			CachedImageRenderer.Init();

			global::Xamarin.Forms.Forms.Init(this, bundle);
			UXDivers.Artina.Shared.GrialKit.Init(this, "Genixs.Droid.GrialLicense");
			
            FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));

			_locale = Resources.Configuration.Locale;

#if GORILLA
			LoadApplication(
				UXDivers.Gorilla.Droid.Player.CreateApplication(
					this,
					new UXDivers.Gorilla.Config("Good Gorilla")
						// Shared.Base
						.RegisterAssemblyFromType<UXDivers.Artina.Shared.NegateBooleanConverter>()
						// Shared
						.RegisterAssemblyFromType<UXDivers.Artina.Shared.CircleImage>()
						// Tab Control
						.RegisterAssembly(GorillaSdkHelper.TabControlType.Assembly)
						// Repeater Control
						.RegisterAssembly(GorillaSdkHelper.RepeaterControlType.Assembly)

						// Effects
						.RegisterAssembly(typeof(UXDivers.Effects.Effects).Assembly)

						// // FFImageLoading.Transformations
						.RegisterAssemblyFromType<FFImageLoading.Transformations.BlurredTransformation>()
						// FFImageLoading.Forms
						.RegisterAssemblyFromType<FFImageLoading.Forms.CachedImage>()

						// Grial Application PCL
						.RegisterAssembly(typeof(Genixs.App).Assembly)
					));
#else
			LoadApplication(new App());
#endif
        }

        public override void OnConfigurationChanged(Android.Content.Res.Configuration newConfig)
        {
			base.OnConfigurationChanged(newConfig);

			GrialKit.NotifyConfigurationChanged(newConfig);

			if ((int)Build.VERSION.SdkInt <= 19 &&
			    !_locale.Equals(newConfig.Locale))
			{
				// Need to recreate the activity when locale has changed for APIs 18 and 19 
				// as changes in ConfigChanges.Locale brake images used in the app
				Recreate();
			}
        }

#if GORILLA
		public override bool OnKeyUp (Android.Views.Keycode keyCode, Android.Views.KeyEvent e)  
		{  
			if ((keyCode == Android.Views.Keycode.F1 || keyCode == Android.Views.Keycode.Menu || keyCode == Android.Views.Keycode.VolumeUp || keyCode == Android.Views.Keycode.VolumeDown || keyCode == Android.Views.Keycode.VolumeMute) && UXDivers.Gorilla.Coordinator.Instance != null) {  
				UXDivers.Gorilla.ActionManager.ShowMenu();
				return true; 
			} 

			return base.OnKeyUp (keyCode, e); 
		}

		private readonly static GestureDetector LongPressDetector = new GestureDetector (new UXDivers.Gorilla.Droid.LongPressGestureListener());

		public override bool DispatchTouchEvent(MotionEvent ev)
		{
			LongPressDetector.OnTouchEvent(ev);
			                 
			return base.DispatchTouchEvent(ev);
		}
#endif
	}
}

**Comment by jpbrocca** [comment]
I am little bit confused now.

I guess you successfully made the proper changes to preview on your Grial Starter, right?
Gorilla SDK will allow you to preview your changes on your XAML pages and custom templates.

There is no navigation on Gorilla SDK, you just preview the XAML file you opened on Visual Studio.

**Comment by webmasterdevlin** [comment]
Yeah. I think it is working now. Although I added some block of codes from the Full and hoping it will run better.

**Comment by webmasterdevlin** [comment]
It stopped working when I added the directives. I guess what I saw earlier was the expected outcome. Thanks. I'll return back to the link you've sent me.

**Comment by webmasterdevlin** [comment]
It's now working. Thanks.

**Comment by LeoHere** [comment]
Ok, cool. Closing the issue now. Open a new one if you need to.
