### ISSUE TITLE
Swipe to Delete on Android ListView 

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#305]
Hi,

Looking at the Swipe and Delete function for ListView, I notice that it is not working for Android platform.

I am checking on Messages sample view from Grial.

Any idea?

Dennis

**Comment by jpbrocca** [comment]
Hi @define, how are you?
Check the xamarin forms docs about ListView and context actions:
https://developer.xamarin.com/guides/xamarin-forms/user-interface/listview/interactivity/#Context_Actions

Only iOS supports swipe gesture. 
On Android it works by performing a long press on your item.

Best,
JP
