### ISSUE TITLE
Urgent - Looking for help quickly if possible?

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#307]
## **Search bar is not coming on S7, S7 edge & S8+.** 

"It is working on Moto 2, Google Pixel & IPhone and IPad"

I took following screenshot from your GrialKit App which i downloaded today. 

![screenshot_20171107-085822](https://user-images.githubusercontent.com/31895946/32485498-8e17da3c-c39b-11e7-9631-65abea029049.png)

![screenshot_20171107-0901431](https://user-images.githubusercontent.com/31895946/32485463-69b9342e-c39b-11e7-85aa-b8bbf7985df1.png)

![screenshot_20171107-090143](https://user-images.githubusercontent.com/31895946/32485471-6f1a0a6a-c39b-11e7-95c7-730f3cbcdd07.png)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru, how are you?

Are you testing on emulators (if so, which one you are using?)...or are you using real devices?

Best
JP

**Comment by qaliwebguru** [comment]
Thanks for your quick response JP. I am testing on real devices.

**Comment by jpbrocca** [comment]
Apparently this is a bug from android 7.
Take a look at the proposed fix:
https://bugzilla.xamarin.com/show_bug.cgi?id=43975

Try setting Search Bar with `HeightRequest="42"`.

Please let me know if it works with your phones (and also answer my previous question about your devices).

Thanks
JP

**Comment by jpbrocca** [comment]
OK, it seems you replied while I was typing.
Thanks.
Let me know if setting the proposed workaround worked.

Best
JP

**Comment by qaliwebguru** [comment]
yes works perfectly. Fantastic. 

Actually i was using the "Native control" page as reference to do some stuff. 

Great stuff.

Thanks a lot.

**Comment by jpbrocca** [comment]
Great!

Best regards
JP
