### ISSUE TITLE
Keyboard is covering the UI in iOS?

### ISSUE THREAD

**Issue by webmasterdevlin** [UXDivers/Grial-UI-Kit-Support#308]
Hi. Is there a way in Grial to keep the keyboard from covering the UI in iOS?

**Comment by jpbrocca** [comment]
Hi @webmasterdevlin, how are you?

Please check for a workaround:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/173

Best
JP

**Comment by webmasterdevlin** [comment]
Thanks!

**Comment by jpbrocca** [comment]
You are welcome!

Closing the issue now.
Feel free to reopen as needed.

Best
JP
