### ISSUE TITLE
Circle Button when expands loses circularity

### ISSUE THREAD

**Issue by mahmoudk-metwally** [UXDivers/Grial-UI-Kit-Support#310]
hi, i tried to create a circle button in a grid with a Label in the underneath row, but it changes from circle to rounded rectangle when the content of the next row expands, is the circle button guarantees circularity regardless of the resizing of its parent view? or there should be a workaround to achieve this?

**Comment by jpbrocca** [comment]
Hi @mahmoudk-metwally , how are you?

It's difficult to diagnose your issue without seeing the code.
Probably if you add `VerticalOptions="Start"` it should work as expected.
If not, then please add your code to this issue.

Best
JP

**Comment by foswha** [comment]
Could you provide an example in a lisview using a circular button? would be very helpful thanks

**Comment by mahmoudk-metwally** [comment]
Thanx @jpbrocca , it's fixed now by separating the button and label in two stack layouts and by setting the VerticalOptions="Start" to the one that contains the circular button.
