### ISSUE TITLE
Can't preview XAML page because of Grial license check

### ISSUE THREAD

**Issue by ceir** [UXDivers/Grial-UI-Kit-Support#313]
I am using the latest version of the Grial developing in Visual Studio 2017 CE on Mac, trying to use the built-in preview available for XAML.   

Running the solution with emulators works fine, no licensing issues. 

Trying to preview any page, I get the missing Init() message.  Added a dependency in the IOS solution that inits the license.  Now the error message becomes the: "... . The application display name does not match ... "  (see screenshot)

![image](https://user-images.githubusercontent.com/6359596/32829104-02265ffe-c9e9-11e7-9eff-d7553c8aa4c9.png)

I have not changed the Bundle Name or Display name since the download. 

I have also tried this with the demo application downloaded, with the same results.

**Comment by jpbrocca** [comment]
Hi @ceir, how are you?

 Xamarin.Forms Previewer has some limitations about previewing. 
I would suggest you to use Gorilla Player to preview instead. It is a free product we develop and maintain.

Check [Grial docs about previewing with Gorilla Player](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) for an explanation of how to.

Best
JP

**Comment by stavrianos** [comment]
Hi, Are you gonna fix that issue? I don't accept as a solution to use Gorilla Player.

**Comment by LeoHere** [comment]
@ceir @stavrianos please see #446
