### ISSUE TITLE
Is there a reason why initialization is done in FinishedLaunching instead of WillFinishLaunching?

### ISSUE THREAD

**Issue by afbase** [UXDivers/Grial-UI-Kit-Support#316]
Hello,  

Is there a reason why in the sample and full project code bases that you have the following code into `FinishedLaunching` instead of `WillFinishLaunching` method of iOS project's AppDelegate class?

    CachedImageRenderer.Init(); // Initializing FFImageLoading
    AnimationViewRenderer.Init(); // Initializing Lottie
    UXDivers.Artina.Shared.GrialKit.Init(param1, param2)
    FormsHelper.ForceLoadingAssemblyContainingType(typeof(UXDivers.Effects.Effects));
    FormsHelper.ForceLoadingAssemblyContainingType<UXDivers.Effects.iOS.CircleEffect>();

1. Is there an advantage or disadvantage of placing this in `WillFinishLaunching`?  I have it working in my starter codebase with no problems.

**Comment by LeoHere** [comment]
No, AFAIK it should not affect moving those the the `WillFinishLaunching`. Those methods usually should be invoked after using `FFImageLoading`, `Lottie` and `Grial` stuff. All of that occurs after the `LoadApplication` so you should be good.

**Comment by LeoHere** [comment]
Closing the issue. Please reopen it if needed.
