### ISSUE TITLE
TFS build error

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#317]
I am trying to create build definition. It works all get upto the point where it needs Acr package. It exit with following error.

DialogService.cs(1,7): Error CS0246: The type or namespace name 'Acr' could not be found (are you missing a using directive or an assembly reference?)

Is there an clue why it is happening?

**Comment by LeoHere** [comment]
@qaliwebguru this issue does not seems to be related to Grial. Closing the issue. Feel free to open a new one if you need to.
