### ISSUE TITLE
Margin for Button using OnIdiom and OnPlatform

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#320]
I was trying to use the combination of OnIdiom and OnPlatform with Grial with it's corresponding counterpart which I think is OnOrientationDouble.PortraitPhone (OnIdiom) and OnPlatform (OnPlatform). When I put <On Platform="Android">30</On> it is working but when I specify <On Platform="Android">30,70,30,0</On> the margin for left,top,right,bottom it is not working. Is there other way to implement such scenario ?

                  <loginButton:LoginButton 
                                EnabledBackgroundColor="#0076FF"
                                DisabledBackgroundColor="#0046AD"
                                EnabledTextColor="#FFFFFF"
                                DisabledTextColor="#638BC6"
                                FontFamily="Calibri Regular"
                                FontSize="16"
                                BorderRadius="20"
                                Text="{Binding LoginText}"
                                Command="{Binding btnLoginCommand}">

                    <loginButton:LoginButton.Margin>
                        <artina:OnOrientationDouble>
                            <artina:OnOrientationDouble.PortraitPhone>
                                <OnPlatform x:TypeArguments="x:Double">
                                    <On Platform="iOS">30,110,30,0</On>
                                    <On Platform="Android">30,70,30,0</On>
                                </OnPlatform>
                            </artina:OnOrientationDouble.PortraitPhone>
                        </artina:OnOrientationDouble>
                    </loginButton:LoginButton.Margin>
                </loginButton:LoginButton>

thanks

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay, how are you?
You were close, but the problem is you need `Thickness` type in order to make it work.

Please have a look at #293 for more details.

Best
JP

**Comment by KirkPatrickJunsay** [comment]
doing great, my first time diving in with Grial :)

Thanks @jpbrocca  for your response, I checked #293 and I was wondering on how to add the Platform type in the code snippet that you have provided below:

<Grid 
     Margin="{ 
       artina:OnOrientationThickness 
         PortraitPhone='10,0,0,0', 
         LandscapePhone='10,0,0,0', 
         PortraitTablet='50,0,0,0', 
         LandscapeTablet='50,0,0,0' 
     }" 
>

thanks

**Comment by jpbrocca** [comment]
Hi again @KirkPatrickJunsay,

Very nice to know you are 'diving' in with Grial, as we are UXDivers we certainly like that! :)

Now, about your question, you should use it this way:

~~~
<Button 
    BackgroundColor="Blue"
    Text="Hello">

    <Button.Margin>
        <artina:OnOrientationThickness>
            <artina:OnOrientationThickness.PortraitPhone>
                <OnPlatform x:TypeArguments="Thickness">
                    <On Platform="iOS">30,110,30,0</On>
                    <On Platform="Android">30,70,30,0</On>
                </OnPlatform>
            </artina:OnOrientationThickness.PortraitPhone>
            
            <artina:OnOrientationThickness.LandscapePhone>
                <OnPlatform x:TypeArguments="Thickness">
                    <On Platform="iOS">20,0,110,70</On>
                    <On Platform="Android">0,30,70,0</On>
                </OnPlatform>
            </artina:OnOrientationThickness.LandscapePhone>
        </artina:OnOrientationThickness>
    </Button.Margin>
</Button>
~~~

You can use any of the available orientations from our responsive helpers:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-helpers-responsive-helpers

Let me know how it goes.

Best,
JP

**Comment by KirkPatrickJunsay** [comment]
Hi @jpbrocca  thanks for the prompt support, I tried your code above and its giving me an error:

![image](https://user-images.githubusercontent.com/12691869/33429380-9929c4a2-d607-11e7-8cbc-651d22136b55.png)

It cannot find the OnOrientationThickness and I already added the namespace in the XAML.
Is there a specific version of Grial Packages that is only applicable for OnOrientationThickness ?
By the way my current Grial Packages installed are version 2.5.2

Thank you very much,
kirk

**Comment by jpbrocca** [comment]
Hi Kirk, how are you?

Yes, you need version `2.5.14-RC2`.
This is a pre release and will be soon added to stable version.

Best regards,
JP
