### ISSUE TITLE
Visual Studio Mobile Center can't find the Grial Packages.

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#321]
Hi @jpbrocca as I was trying to build IOS package for Mobile Center, unfortunately it cannot find the package for Grial. I attached the screenshot below as your reference:

![image](https://user-images.githubusercontent.com/12691869/33465930-a1f6fd56-d685-11e7-809e-236804bd9831.png)

Is there any special configurations that I need to perform when building in Mobile Center with respect to Grial Packages ?

As always thanks in advance for you help :)

**Comment by LeoHere** [comment]
@KirkPatrickJunsay please see #221.

**Comment by KirkPatrickJunsay** [comment]
Hi @LeoHere, thanks for the help, it works perfectly with App center 👍
