### ISSUE TITLE
how to get list of products from Magento2 in UXDivers?

### ISSUE THREAD

**Issue by ukomiljon** [UXDivers/Grial-UI-Kit-Support#322]

**Comment by jpbrocca** [comment]
Hi @ukomiljon,

can you clarify what you are asking?

Please provide as much context as possible.

Thanks,
JP

**Comment by ukomiljon** [comment]
we are going to build Magento2  cross platform mobile app with xamarin.
to make faster develop we choose UXDivers.
which rest api is better to use with UXDivers to get, post, delete and update from/to Magento2?

**Comment by jpbrocca** [comment]
Hi @ukomiljon,

The rest API is totally independent of Grial, you can choose the best that suits your needs.

Best,
JP

**Comment by ukomiljon** [comment]
thanks
