### ISSUE TITLE
GrialShapesFont - Unlock Icon?

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#323]
Is there an Unlock Icon available in GrialShapesFont?
I was able to find a lock icon, but can't see no unlock icons.

**Comment by jpbrocca** [comment]
Hi @khadeeja-alif, how are you?

No, it is not currently provided.
You can switch to Fontawesome to get that icon:

http://fontawesome.io/icon/unlock-alt/

Best,
JP
