### ISSUE TITLE
Grial UI Kit Gradient background on viewcell

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#324]
Hi @jpbrocca  are there any gradient techniques for Grial controls like for example in View Cell could we implement gradient background ?

thank you very much,
kirk

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay,

No, currently not gradient support.
It's on the backlog though so probably next version will provide it.

In the meantime, you can use an image (png, jpg) as your background.
Alternatively, you could try with FFImageLoading SVG to consume an SVG file.

Best,
JP

**Comment by KirkPatrickJunsay** [comment]
Thanks as always @jpbrocca  for your support.
