### ISSUE TITLE
TabControl - using separate page for its children - Also tab control shows blank page

### ISSUE THREAD

**Issue by sky018** [UXDivers/Grial-UI-Kit-Support#325]
Hi,

@jpbrocca 

Would it be possible to use a different xaml page when implementing child of a tab control? If yes, how would I be able to do it? Thanks.

Plus, the tab control I made doesn't work, it only shows a blank white page:
Here's the xaml content:
```
<ContentPage.Content>
        <ScrollView Orientation="Both" HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            <tabGrial:TabControl TabStripPlacement="Top">
                <tabGrial:TabItem Text="test">
                    <Label Text="Test"/>
                </tabGrial:TabItem>
                <tabGrial:TabItem Text="test">
                    <Label Text="Test"/>
                </tabGrial:TabItem>
                <tabGrial:TabItem Text="test">
                    <Label Text="Test"/>
                </tabGrial:TabItem>
            </tabGrial:TabControl>
        </ScrollView>
    </ContentPage.Content>
```

**Comment by jpbrocca** [comment]
Hi @sky018, how are you?

The `TabControl` is used to display content within the current page. If you want to use pages as content you will need to use a `TabbedPage`.

It seems you are missing the `StyleClass` to make it work...in this case I am using the one from Grial Sample, but you can use the other ones available (or create your own based on any of them):

- Android look and feel -> `TabControlStyle`
- iOS -> `iOSTabControlStyle`

~~~
<tabGrial:TabControl TabStripPlacement="Top" StyleClass="GrialTabControlStyle" >
~~~

Best,
JP

**Comment by sky018** [comment]
Hi @jpbrocca ,

I see - so using tab control only displays the current page, so tab page if I want to separate each of them. (Thanks for this)

I have tried this, I even tried to copy pasted the tab control snippet on the project sample grial provided, unfortunately, it didn't worked.

**Comment by jpbrocca** [comment]
Hi @sky018,

I just used your code, pasted over Grial Tab Control sample page and it just works if you add the `StyleClass` attribute as I mentioned.
(I only had to rename your namespace `tabGrial` to use the same used on that sample page).

You need to make sure you have the StyleClass, DataTemplate, etc. on your page as ResourceDictionary items.

About the effects question:
It seems you misspelled `UXDivers.Effects`...You have `UXDrivers.Effects` (remove the 'r') 😀.

Best,
JP

**Comment by sky018** [comment]
@jpbrocca 

Hi, yes, I think I just mistyped it here, here's the complete assembly name:  ` xmlns:effects="clr-namespace:UXDivers.Effects;assembly=UXDivers.Effects" `

Alright, idk what happened, I just did copy pasted it and it worked, weird thing, I just tried to recreate it. But the assembly `Effects`  is nowhere to be found.
