### ISSUE TITLE
TabControl - no highlight/underscore when selecting the tab

### ISSUE THREAD

**Issue by sky018** [UXDivers/Grial-UI-Kit-Support#326]
![tabcontrol](https://user-images.githubusercontent.com/21186089/33754067-9a1420be-dc25-11e7-9c3b-c1f3c4587c2b.jpg)

Hi @jpbrocca ,

I have a problem regarding the highlight / underscore when selecting a tab, it's not showing -- using a tab control, is there a way to fix this? It seems like the `Text="{ artina:Translate TabItemTextDrama }"` is the one representing the highlight / underscore in Grial's sample, or is it another issue? Thanks!

**Comment by jpbrocca** [comment]
Hi @sky018, how are you?

Is this happening on the full sample provided with Grial or in your own project?
If it is the later then make sure to check with the full sample `TabControlSamplePage.xaml` file...maybe you missed some resources.

If this is happening with the full sample then please provide more info such as:

- Grial version you are using
- Grial flavor (RTL, Standard or PRO?)
- Xamarin Forms version
- Is this happening on both platforms, iOS and/or Android?
- Which device are you testing with?

Regards,
JP

**Comment by sky018** [comment]
Hi, @jpbrocca still alive and breathing.

Sorry for my late response since I did not have my machine last weekend to test it. It works on grial sample, however, I just copy pasted the code without doing any revisions. 

Grial Version: 2.5.2
Grial Flavor: RTL PRO
Xamarin Forms Version: 2.4.0.282
Platforms: Both iOS and Android.
Device: Simulator 

Best Regards

**Comment by sky018** [comment]
Hi @jpbrocca seems like it is because of the dynamic resource, changed it into static resource and manually inserted styles on it. Issue is now fixed, thanks!
