### ISSUE TITLE
Grial UI Kit Text Color of Tab Item

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#327]
Hi @jpbrocca, I was trying to change the text color of the Tab Items but cannot find the property
textcolor. Are there any work around for the text color of Tab Items ?

thank you very much,
kirk

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay, how are you?

If you take a look at `TabControlSamplePage.xaml` you see at the top the different resources used on that sample.

Basically, the tab items are built based on the 3 different `DataTemplate` provided with the sample (Android, iOS and Grial look and feel). That will give you total flexibility about how tabs are displayed.
So depending on which of the tree tabs look and feel you are using you will need to change one of the following colors with your color:

~~~
<!-- GRIAL COLORS -->
<Color x:Key="GrialTabItemActiveStateTextColor">YOUR_COLOR_HERE</Color>

<!-- ANDROID COLORS -->
<Color x:Key="TabItemActiveStateTextColor">YOUR_COLOR_HERE</Color>

<!-- IOS COLORS -->
<Color x:Key="iOSTabItemActiveStateTextColor">YOUR_COLOR_HERE</Color>
~~~

Best,
JP

**Comment by KirkPatrickJunsay** [comment]
Hi @jpbrocca thanks for the help, It works well.
