### ISSUE TITLE
Is it OK to use Xamarin.Forms 2.5.0.91635 with UXDivers 2.5.14-RC3 ?

### ISSUE THREAD

**Issue by MichelMatthey** [UXDivers/Grial-UI-Kit-Support#328]
Is it OK to use Xamarin.Forms 2.5.0.91635 with UXDivers 2.5.14-RC3 ?

Getting some Object Disposed Exceptions since I upgraded UXDivers to 2.5.14-RC3 and XF to 2.5.0.91635 ? I upgraded as it was solving another issue I had...
System.ObjectDisposedException: Cannot access a disposed object.

See in this XF ticket, I am stuck at the moment, please help: https://github.com/xamarin/Xamarin.Forms/issues/1338

**Comment by LeoHere** [comment]
@MichelMatthey we tested Grial with XF 2.5.0.91635 and we didn't find any issue so far. 

We tested running Grial for ~50mins in the emulator to see if something like what you described happen but we were not able to reproduce the problem. 

Without a solution or further details about how to reproduce the issue it would be very difficult to find out what is going on. Can you provide any additional detail or a solution to reproduce it?

**Comment by MichelMatthey** [comment]
Did you get lots of Warnings when you built, I get some 153 related to conflicts with packages ?

Is there any way Grial could provide a version that uses the latest XF version so I can upgrade please ?

**Comment by LeoHere** [comment]
@MichelMatthey we are working on an update that should make those warnings goes away. You will need to update UXDivers packages and probably a bunch of other packages in order to remove the warnings. 

The updated should be ready early next week. I will keep you posted.

**Comment by MichelMatthey** [comment]
Thank you, please let us know what packages we need to update when it is ready, including the more common packages like NewtonSoft which seems to be causing issues as the rest of the packages seem to need NewtonSoft 10+ and the rest NewtonSoft 9+...

**Comment by MichelMatthey** [comment]
You mentioned next week mid last week, can you please let us know when it is going to be ready on the Grial nuget ?

**Comment by LeoHere** [comment]
@MichelMatthey we are very close. Hold on please. We will let you know as soon as those bits are live.

**Comment by MichelMatthey** [comment]
Great thanks! Looking forward to being able to upgrade and get rid of all these warnings that get in the way o other proper warnings...

**Comment by MichelMatthey** [comment]
Any progress on that one please ?

**Comment by LeoHere** [comment]
@MichelMatthey we have just published version `UXDivers.Artina.Shared*` `2.6.0.4` of the nuget packages which are compatible with .NET Standard. You will need to upgrade those.

In addition to this and in order to get rid of those warnings you might need to upgrade other packages in your project. I'm not sure what packages your current solution have, but if you project was based on the Grial Starter project you will need to upgrade at least:
- `UXDivers.Effects`
- `FFImageLoading` 
- `Lottie`

**Comment by MichelMatthey** [comment]
Thanks for that, here are a couple of questions please:
1) had to change the call to CachedImageRenderer.Init(true); as Init is no longer a parameter less method... It crashes so maybe I need to pass false, please explain which one we need to pass ?

2) Also, Which versions of Xamarin Forms and Xamarin Android Support does it depends on please ?  
- UXDivers.Artina.Shared.* V2.6.4 ?
- UXDivers.Effects V.0.6.3 ?
- Xamarin Android Support V26.1.0.1 ?
- Xamarin Forms V2.5.0.121934 ?
- Xamarin.FFImageLoading.* V2.3.2 ?
- Com.Airbnb.Android.Lottie V2.2.5.0 ?
- Com.Airbnb.Xamarin.Forms.Lottie V2.4.0 ?
- Newtonsoft.Json V10.0.3 ?
- System.Runtime.* V4.3.0 ?

Other packages we have:
- Xam.Plugin.Connectivity V3.0.3 ?
- Xam.Plugins.Notifier V2.1.0 ?
- Xam.Plugins.Settings V3.1.1 ?
- HtmlAgilityPack V1.6.10 ?

- NETStandard.Library V1.6.1 ?

**Comment by jpbrocca** [comment]
Hello @MichelMatthey, how are you?

I can give you some orientation about your questions so you can save some time while you wait for @LeoHere's answer.

1. For Android, [FFImageLoading latest version](https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API)  requires this:
~~~
// Initializing FFImageLoading
CachedImageRenderer.Init(enableFastRenderer: [true]/[false]);
~~~
2. About Xamarin Forms version and Android Support, check Xamarin official docs here:
https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.5/2.5.0-stable/

Here are the details about the different packages versions for this release:
## Modified Artina packages in this version

- `UXDivers.Artina.Shared.Base` upgraded to version **2.6.4**
- `UXDivers.Artina.Shared` upgraded to version **2.6.4**
- `UXDivers.Artina.Controls.Tab` upgraded to version **2.6.4**
- `UXDivers.Artina.Controls.Repeater` upgraded to version **2.6.4**

## Upgraded packages in this version

### Xamarin Forms
- `Xamarin.Forms` upgraded to version **2.5.0.121934**

### FFImageLoading
- `Xamarin.FFImageLoading` upgraded to version **2.3.1**
- `Xamarin.FFImageLoading.Forms` upgraded to version **2.3.1**
- `Xamarin.FFImageLoading.Transformations` upgraded to version **2.3.1**

### Lottie
- `Com.Airbnb.Xamarin.Forms.Lottie` upgraded to version **2.4.0**
- `Com.Airbnb.Android.Lottie` upgraded to version **2.2.5**
- `Com.Airbnb.iOS.Lottie` upgraded to version **2.1.5**

Best,
JP

**Comment by MichelMatthey** [comment]
Hi Thanks very much, couple of questions:
1) Which bool should I pass, true or false in the Init method ?
2) Is it Ok to use FFImageLoading 2.3.2 instead of 2.3.1, why didn't you use 2.3.2 as it is the latest ?

Much appreciated ...

**Comment by jpbrocca** [comment]
1. That will depend on your app if you want to use fast renderers or not. By default if you take a look at Grial Full or Starter projects you download from Grial Admin you will see it is set to:

~~~
// Initializing FFImageLoading
CachedImageRenderer.Init(enableFastRenderer: false);
~~~

2. That is a question for @LeoHere :)

Hope that helps!

Best,
JP

**Comment by MichelMatthey** [comment]
I am getting the following warnings:
- 1st Warning:
Warning		Skipping CrowdBlendingMe.Droid.Resource.Animation.design_fab_in. Please check that your Nuget Package versions are compatible.	CrowdBlendingMe.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1344	

- 2nd Warning:
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Skipping CrowdBlendingMe.Droid.Resource.Style.TextAppearance_StatusBar_EventContent. Please check that your Nuget Package versions are compatible.	CrowdBlendingMe.Droid	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1344	

and 12 more similar ones in the Driod project when building ?

**Comment by jpbrocca** [comment]
Take this with a grain of salt since I am just trying to guide you, but that is probably related to your other libraries and the Android version being used. 
Probably @LeoHere can provide more guidance here.

A couple of comments:

1. Can you successfully build and run the project or do you get any errors that are blocking you?
2. Could you add here the details about what Android version are you targeting in your app?

Thanks,
JP

**Comment by MichelMatthey** [comment]
No they are just warnings, it builds and runs OK, but it would be nice to have them resolved anyway!

Can you make sure@LeoHere has a look at why he didn't use the latest version of FFImageLoading (2.3.2 instead of 2.3.1) ?

And if h can answer my other questions... Thanks!

**Comment by LeoHere** [comment]
@MichelMatthey regarding the `FFImageLoading` version, `2.3.2` has been released just a couple of days ago, too close to the release to update it.  

Regarding your questions for `NETStandard.Library` we are using `2.0.0`.  For the other packages I can't say because I'm not familiar with them.

If you want you can download the Grial .Net Standard based app from the [Grial Admin](http://uxdivers.com/secure/grial/front/) and compare your packages agains them. [Here](http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html#release-notes-grial-2600-rc) are the release notes where you will find a detailed explanation of what to do to get it.
