### ISSUE TITLE
Grial Project not running on device

### ISSUE THREAD

**Issue by msl2000** [UXDivers/Grial-UI-Kit-Support#329]
Hi

I recently purchased Grial and have been attempting to debug it on an android device. Problem is the app won't get past the splash screen. Tried with 2 different device, where one is running on API 23, it crashes shortly after the app gets to the splash screen. As for the other running on API 25.

I am currently running on VS for windows.

I have tried running on a emulator and it works there no problem.

**Comment by jpbrocca** [comment]
Hi @msl2000,

Can you provide more details about your issue, like:

- Grial version you are using
- Grial flavor (RTL, Standard or PRO?)
- Xamarin Forms version
- Which device are you testing with?

Is there any chance you could get the exception and paste add it here?

Regards and thanks,
JP

**Comment by msl2000** [comment]
Hi @jpbrocca 

Grial version is 2.5.0.0

Grial Flavor is PRO

Xamarin Forms Version 2.4.0.282

Device is a LG G4 and a Samsung S8

No Exception has been published which is quite a hassle.

Thank you!

**Comment by msl2000** [comment]
Xamarin Forms version 2.4.0.282 for the solution and Xamarin 4.8.0.753 on VS

**Comment by jpbrocca** [comment]
Hi @msl2000, how are you?

Can you take a look at the Application Output panel on Visual Studio and check if you get more info when the crash occurs?

Regards and thanks,
JP

**Comment by msl2000** [comment]
Hi JP

Seems a clean install of visual studio did the trick for some oddball reason. Sorry for the late response.
