### ISSUE TITLE
How to work with font awesome in Grial?

### ISSUE THREAD

**Issue by kirti-zare** [UXDivers/Grial-UI-Kit-Support#330]
Hello

I have purchase grial kit since 5 day ago.

It is working properly, but I want to use fontawesome instead of grialshapes font.

when I write code in app.xaml <OnPlatform x:Key="IconsFontFamily" x:TypeArguments="x:String" Android="grialshapes.ttf#grialshapes" iOS="grialshapes" /> app is working.

But when I write code <OnPlatform x:Key="IconsFontFamily" x:TypeArguments="x:String"
Android="FontAwesome.ttf#FontAwesome"
iOS="FontAwesome"
/> app is not working.

I also try <OnPlatform
x:Key="IconsFontFamily" x:TypeArguments="x:String"
Android="Ionicons.ttf#Ionicons"
OS="Ionicons"
/> but not work

I refer to this link "https://github.com/UXDivers/Grial-UI-Kit-Support/blob/master/all.md" but it is not helping me.

I set build action to android asset of file "fontawesome-webfont.ttf" and "ionicons.ttf" but still it is not working.

Please tell me how can I use FontAwesome or custom icon step by step.

**Comment by jpbrocca** [comment]
Hi @kirti-zare,

Please refer to Grial documentation about working with icons:
https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons 

If you set the build action for font awesome then that would be enough in terms of the file.
You will still need to change the current templates to point to the right font helper and icon.

Best,
JP

**Comment by kirti-zare** [comment]
Hello,


I already mention you that I go through that document.


Please explain me with example


Thanks and Regards,

Kirti Zare

Krtya Softwares

________________________________

**Comment by jpbrocca** [comment]
Hi @kirti-zare,
Please notice the link I sent you:

https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons

... is different than the one you put here.

Mine has the specific link to the detailed explanation on how to use font icons in Grial.

Alternatively, you can also check this one, which it seems you already did:
https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-helpers-font-helpers

You need to do 3 main things to change the font icons for your app (explained in the above doc):

1. Set the proper font family on you `App.xaml`. Make sure you use the right syntax for Android as in the document is shown (perhaps this is your real issue).
2. Set the proper build action for the new font on each platform.
3. Set your templates items to use to the right icon. This is easier to do by using the font helpers (check the second link above). In your case, you will need to use `FontAwesomeFont.cs`.

Best
JP

**Comment by txk103** [comment]
Hi,

I'm also experiencing difficulties in getting FontAwesome running. I believe we have version 2.0

What I have done:

- [ ]  App.xaml commented out `<x:String x:Key="IconsFontFamily">grialshapes</x:String>` and uncommented `<x:String x:Key="IconsFontFamily">FontAwesome</x:String>` 
- [ ]  In the Droid project, set `fontawesome-webfont.ttf` file to `AndroidAsset`

I don't have anything that remotely resembles 
```
<OnPlatform 
        x:Key="GrialShapesFontFamily" x:TypeArguments="x:String"
        Android="grialshapes.ttf#grialshapes"
        iOS="grialshapes"
    />

    <!-- PUT YOUR OWN ICONS FONT FAMILY BELOW -->
    <OnPlatform 
        x:Key="IconsFontFamily" x:TypeArguments="x:String"
        Android="grialshapes.ttf#grialshapes"
        iOS="grialshapes"
    />
``` 

In any xml or xaml file, the only place I seem to have font files specified is the one below (I uncommented the font-awesome-webfont.tff parts)
```
public class CustomFontLabelRenderer : ArtinaCustomFontLabelRenderer
{
        private static readonly string[] CustomFontFamily = new[] { "grialshapes", "FontAwesome" };
        private static readonly Tuple<FontAttributes, string>[][] CustomFontFamilyData = new [] { 
			new [] {
				new Tuple<FontAttributes, string>(FontAttributes.None, "grialshapes.ttf"),
				new Tuple<FontAttributes, string>(FontAttributes.Bold, "grialshapes.ttf"),
				new Tuple<FontAttributes, string>(FontAttributes.Italic, "grialshapes.ttf")
			},            
			
			new [] {
				new Tuple<FontAttributes, string>(FontAttributes.None, "fontawesome-webfont.ttf"),
				new Tuple<FontAttributes, string>(FontAttributes.Bold, "fontawesome-webfont.ttf"),
				new Tuple<FontAttributes, string>(FontAttributes.Italic, "fontawesome-webfont.ttf")
			},
```

I then have a simple page:
```
<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage
	x:Class="Namespace.Test"
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
	xmlns:local="clr-namespace:Namespace;assembly=Namespace"
	xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
	Title="Prism test page"
	prism:ViewModelLocator.AutowireViewModel="True"
	BackgroundColor="{DynamicResource BasePageColor}">

	<Label Style="{DynamicResource FontIcon}" Text="{x:Static local:FontAwesomeFont.DesktopWindows}" BackgroundColor="Cornsilk" />

</ContentPage>
```

I displays the label as a small box (ie the char is not found). 

I have verified that `protected override bool CheckIfCustomFont (string fontFamily, FontAttributes attributes, out string fontFileName)` is not event hit. However, if I revert the `IconsFontFamily` and change the label text to a Grial font helper value it all works fine.

Suggestions for next step?

Tamas

**Comment by jpbrocca** [comment]
Hi @txk103, how are you?

A couple of questions:

1) It seems you are trying to add Grial to an existing project, right?
2) What version of Grial are you using? It seems to be an old version. The `CustomFontLabelRenderer` is deprecated. The right way of getting the right font applied on Android is through something like this:

~~~
<OnPlatform 
        x:Key="IconsFontFamily" x:TypeArguments="x:String"
        Android="grialshapes.ttf#grialshapes"
        iOS="grialshapes"
/>
~~~

For Android is not enough to set the file name. If you don't point to the font family name by adding the "#" it won't work (grialshapes.ttf#**grialshapes**).
https://developer.xamarin.com/guides/xamarin-forms/user-interface/text/fonts/#Android

Also from your comment, it seems you are not getting the `<OnPlatform>` block which seems to confirm you are using an old version of Grial.

Last but not least, it seems you are using `{x:Static local:FontAwesomeFont.DesktopWindows}` for your page. That icon (char) is not present on `FontAwesomeFont.cs` helper so that could be also the reason why you are not seeing this icon. Don't know if you added it to that file, but keep in mind the version of Fontawesome you are using. 

Hope that helps,
JP

**Comment by IoTFier** [comment]
Hi JP,
I am interested in using some new icons from latest fontawesomefont (5.1.1)
How to update latest fontawesomefont ttf file? I have downloaded the latest zip file from their site but it doesn't contain .ttf file.

Thanks,

**Comment by jpbrocca** [comment]
Hi @IoTFier,

I have downloaded latest from FontAwesome site, and they certainly provide ttf files.

Download by clicking the web version button.

Best,
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca , thank you for your response. 
I am trying not to add on icons fontawesome to grialshapes and not replace them. **_In that case are your instruction stated in your responses above still valid?_**

So far, with my steps below, I am still getting "?" for the icon fonts that I am trying to use from the net version of fontawesomeweb. **Your quick help will be truly appreciated.**

![image](https://user-images.githubusercontent.com/26844611/43038332-0fe890a0-8cdd-11e8-9d69-dfc60c85ec18.png)

* I downloaded latest 5.1.1 version of the fontawesome for web (free version).  
* Extracted the fa-solid-900.ttf (included in the free version) and renamed it to FontAwesomeWebFree-fas900-511.ttf
* In App.xam made following inserts / updates -
            
			<OnPlatform
				x:Key="IconsFontFamily"
				x:TypeArguments="x:String"
				Android="grialshapes.ttf#grialshapes"
				iOS="grialshapes" />

            <OnPlatform 
				x:Key="FontAwesomeWebIconsFontFamily" 
                x:TypeArguments="x:String"
				Android="FontAwesomeWebFree-fas900-511.ttf#FontAwesomeWebFree-fas900-511"
				iOS="FontAwesomeWebFree-fas900-511"
			/>
 
Added a base style in App.xaml
			
			<Style
				x:Key="FontIcon"
				TargetType="Label">
				<Setter
					Property="FontFamily"
					Value="{ StaticResource IconsFontFamily }" />
			</Style>

			<Style
				x:Key="FontIconBase"
				TargetType="Label">
				<Setter
					Property="FontFamily"
					Value="{ StaticResource GrialShapesFontFamily }" />
			</Style>

            <Style
                x:Key="FontAwesomeWeb511"
                TargetType="Label">
                <Setter
                    Property="FontFamily"
                    Value="{StaticResource FontAwesomeWebIconsFontFamily}"/>
            </Style>

In LoginPage.xaml updated logo label tag to 

						<Label
						TextColor="{ DynamicResource OverImageTextColor }"
						FontSize="42"
						Text="{x:Static helpers:FontAwesomeWeb511Font.Plus}"
						Style="{StaticResource FontAwesomeWeb511}"
						HorizontalTextAlignment="Center"
						VerticalTextAlignment="Center" />

Created a new font helper class - 

using System;
using System.Collections.Generic;
using System.Text;

    class FontAwesomeWeb511Font
    {
        public const string Plus= "\uf067";
    }

* copied FontAwesomeWebFree-fas900-511.ttf file for -
   * Android under Assets folder
![image](https://user-images.githubusercontent.com/26844611/43038370-669e8788-8cdd-11e8-84f3-66bc0c1518e7.png)
    * iOS under Resources folder 

![image](https://user-images.githubusercontent.com/26844611/43038375-890f843e-8cdd-11e8-904b-4f96d3f41565.png)
      updated Info.plist to include new ttf file as shown below 
	<key>UIAppFonts</key>
	<array>
		<string>grialshapes.ttf</string>
		<string>FontAwesomeWebFree-fas900-511.ttf</string>
	</array>

* Set the build action for the new font awesome ttf file in both Android and iOS appropriately

**Comment by jpbrocca** [comment]
Hi @IoTFier,

I am not sure what you mean with 'I am trying not to add on icons fontawesome to grialshapes and not replace them'...you want to add fontawesome icons besides grialshapes?
If that is the case check the docs where it is explained.

From your comments I think you used the file name as the font family. The font family will remain the same even if you rename the file. You need to make sure the font family is the right one, otherwise you will get those question marks instead of your icons.

Best
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca , my typo above. Yes. I am trying to add fontawesome icon in addition (besides) grialshapes.

Not clear on your input from 2nd para. Do you mean to suggest keep the value in the setter tag as name of the ttf file that was downloaded? Like the one shown below?

            <Style
                x:Key="FontAwesomeWeb511"
                TargetType="Label">
                <Setter
                    Property="FontFamily"
                    Value="{StaticResource fa-solid-900}"/>
            </Style>

With all due respect, there is good documentation provided by Grial, but many times it is not clear to interpret and understand quickly. I am definitely nowhere expert on this tech stack as you all, but I have spent more than a day and half in getting this addressed. I felt that's is a bit of a stretch.

Thank you for your help.

**Comment by jpbrocca** [comment]
Hi @IoTFier,

OK. So what you need to be sure is about the font family.

In your previous message you mentioned you added this:

~~~
<OnPlatform 
  		x:Key="FontAwesomeWebIconsFontFamily" 
          x:TypeArguments="x:String"
  		Android="FontAwesomeWebFree-fas900-511.ttf#FontAwesomeWebFree-fas900-511"
  		iOS="FontAwesomeWebFree-fas900-511"
  	/>
~~~

This will be the font family you will use as a resouce. You set it this way in order to point it in the right way for android and iOS plaforms respectively.

For Android you need to point to the file name + the font family (filename.ttf#fontfamily). For iOS just the font family.

Now, you seem to be using the **file name** as the **font family** (FontAwesomeWebFree-fas900-511.ttf#FontAwesomeWebFree-fas900-511). I am sure the font family should be something 'Fontawesome' or similar. You need to intall the font and check the right font family name (or search for an online tool opentype.js which will allow you to inspect the font and check the font family name).

Find the right font family name and let me know how it goes.

Best
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca,

Thank you for your guidance again.
Here is the information obtained from opentype.js
The **font family** is "Font Awesome 5 Free" . Is that what should be using with spaces between the words?

![image](https://user-images.githubusercontent.com/26844611/43041143-e3255f04-8d1c-11e8-88b1-d8584728248a.png)

Q: At this point I am using the free version which allows me to use only the solid font. But when I upgrade it to Pro license, I will be using other two ttf as well. How does this configuration change in that scenario within Grial settings?

………………………………………………………...
**P.S.** - I do want to take a moment to thank you for putting this UI Kit together. Truly awesome work! It is definitely giving me a sweeping broad help and assistant. My other comments are truly as a well wisher with hopes and wishes for Grial's faster progress with features and capabilities to make us more productivity. Thank you.

**Comment by IoTFier** [comment]
Whoooo hooooo . Hi @jpbrocca , yes it did work.
These are my final changes - 
            
             <OnPlatform 
				x:Key="FontAwesomeWebIconsFontFamily" 
                x:TypeArguments="x:String"
				Android="FontAwesomeWebFree-fas900-511.ttf#Font Awesome 5 Free"
				iOS="Font Awesome 5 Free"
			/>

            <Style
                x:Key="FontAwesomeWeb511"
                TargetType="Label">
                <Setter
                    Property="FontFamily"
                    Value="{StaticResource FontAwesomeWebIconsFontFamily}"/>
            </Style>

Please help me with this question also - 
Q: At this point I am using the free version which allows me to use only the solid font. But when I upgrade it to Pro license, I will be using other two ttf as well. How does this configuration change in that scenario within Grial settings?

Thanks a lot!

**Comment by jpbrocca** [comment]
You are welcome!
Yes, you should use exactly the font family as in the screen capture you attached.

If you add more fonts, then you will need to repeat the process if adding the font files in rhe right place, right build action set, etc., then you will need to create a style pointing to the font family resource and use it where you need it.

Thanks for your kind words.
We are working hard to make things even better.

Best
JP

**Comment by jpbrocca** [comment]
Great! 😀

**Comment by IoTFier** [comment]
Hi @jpbrocca, how are you?
Any recommendations on any opensource utility to -
1. create enum class from fontawesome.ttf (any font file)?
2. create font file from a set of svgs and/or pngs files? 

I would appreciate your guidance on that.

Thank you.

**Comment by IoTFier** [comment]
Just Created a enum file for fontawesome using https://github.com/smourier/FontAwesomeEnum.
It is a commandline utility which requires the .zip file to parse thru. 

Your help on Q.2 above will be appreciated.

**Comment by excellapay** [comment]
I am using the latest copy of GrailKit UI, but cannot seem to get FontAwesome icons to load.  I have commented out the line in App.xaml. Here is my  label code. It is just generating the [?] instead of the icons. Does anyone have a github example of complete code?



 <Label
                            Grid.Column="0"
                            Grid.Row="3"
                            FontSize="24"
                            Text="{ x:Static local:FontAwesomeFont.Cog }"
                            Style="{StaticResource FontIcon}"
                            FontFamily="{ StaticResource IconsFontFamily }"
                            HorizontalTextAlignment="Center"
                            TextColor="White"
                            VerticalOptions="Center"
                            HorizontalOptions="Center" />

**Comment by jpbrocca** [comment]
Hi @excellapay,

Most probably you are missing the step where you make the font file available for your app.
You need to make sure the font file is present in your platform projects and with the build options properly set.
Check this document for more details:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-working-with-projects-adding-font-icons-to-your-project

Let me know how it goes.

Regards,
JP
