### ISSUE TITLE
Need to change app name

### ISSUE THREAD

**Issue by IWantMyApp** [UXDivers/Grial-UI-Kit-Support#331]
Hi, I didn't realize switching to production mode was a onetime thing.  I see the warnings now, but don't remember them at the time, although admit to doing crazing things to get a clean build sometimes ;)  

I need to change the app name.  Please let me know how I can get this done.  Thanks!

**Comment by LeoHere** [comment]
@IWantMyApp I think this issue was already addressed by email. Closing the issue. Feel free to reopen it if you need to.

**Comment by sandrea** [comment]
Hi, it would a very good help if you put the solution here, please. I have the same problem. Thank you very much.

**Comment by LeoHere** [comment]
@sandrea please write me to l r o d r i g u e z at uxdivers.com explaining your case. Thanks
