### ISSUE TITLE
Is it compatible with Prism?

### ISSUE THREAD

**Issue by stesvis** [UXDivers/Grial-UI-Kit-Support#335]
All my MVVM apps use Prism, will Grial work with it?

PS: I wish you had a contact form on your website.

**Comment by jpbrocca** [comment]
Hi @stesvis,
Grial is MVVM framework agnostic.
It is built over MVVM pattern but it doesn't use Prism or any other framework.
You can however use Grial with Prism, many of our customers use it that way.

Here is a link that shows how you can do it:
https://devlinduldulao.pro/how-to-use-grial-ui-kit-with-prism-and-infragistics-appmap/

About our website, if you go to grialkit.com you will find a chat (on every page) where our team answers all that kind of questions.

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it if you need so.
