### ISSUE TITLE
Added support for .NET Standard 2.0 to Grial 2.6.0.0 RC

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Grial-UI-Kit-Support#336]
Dear customers, we have great news to share! 
We have added support for **.NET Standard 2.0** to **Grial 2.6 RC**.

Starting in this version Grial UI Kit Sample project is a **.NET Standard 2.0 Project**, *not a PCL project anymore*. The packages target **.NET Standard 1.0** to maximize compatibility.

## Extra stuff!
Additionally, **Grial 2.6 RC** includes some enhancements for the license verification and some improvements for the `Tab Control`.

## Very Important!

`UXDivers.Artina.Shared*` nuget packages are released as fully flagged **RTM**, meanwhile, the Grial app will be released as **RC**.

We chose to label it as **Release Candidate** due a few bugs in `Xamarin Forms` latest stable version that breaks `XAMLC` in the context of **.NET Standard** projects. 

As a result `XAMLC` **must be disabled** which degrades performance, especially in Android. Once those bugs hit the Xamarin stable channel we will release Grial app as RTM.

### What does this means to you?

`UXDivers.Artina.Shared*` are **RTM** packages, so it is perfectly safe to upgrade to those
You can base your app on **Grial 2.6.0.0 RC** sample app and it will work like a charm. You must only be aware that `XAMLC` has been disabled. If that is not an issue for you, just go with it.

## How to base your app on **Grial 2.6 RC**
In order to base your app on **Grial 2.6 RC**, you must configure that on Grial Admin through the following steps:

- Opening your app details page on [Grial Admin](https://uxdivers.com/secure/grial/front/#/myapps)
- Choose **Grial Settings tab**
- Uncheck the **"Stick to latest stable version"** checkbox
- Select version **2.6.0.0** Release Candidate
- Press **"Save Changes"** button

![grial_admin_2_6_rc](https://user-images.githubusercontent.com/15996999/34397775-c6d2f2d8-eb57-11e7-99c8-88226f118423.png)

Then, simply download your Grial Full or Starter customized projects:

![grialadmin_download_dropdown](https://user-images.githubusercontent.com/15996999/34399039-8d286e5e-eb62-11e7-808e-49ef6a52036c.png)

For more details, please refer to [Grial Release notes page](https://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html).

Best,
JP

**Comment by vhugogarcia** [comment]
One question:

The .NET Standard 2.0 version when is planned to be released officially?

**Comment by jpbrocca** [comment]
As soon as Xamarin.Forms latest stable version includes a fix for the XAMLC issue.
After that, Grial 2.6 will be promoted to RTM.

More details here:
https://grialkit.com/2017/12/grial-ui-kit-net-standard-2-0-support/

**Comment by vhugogarcia** [comment]
Thanks @jpbrocca one last question, Is GrialKit's supporting latest version of Xamarin.forms 2.5?

**Comment by jpbrocca** [comment]
Yes, latest stable version is supported.

**Comment by vhugogarcia** [comment]
Thanks @jpbrocca Sorry for bother you, but I do have one last question, Do you know if Grial's is compatible with iPhone X screen resolution or are you working still on adapt it for that size?

**Comment by jpbrocca** [comment]
Grial design should adapt by itself, however our current version is not optimized for the iphone X notch, but doing something like the following should do the trick to display content in the safe area:
~~~
xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
ios:Page.UseSafeArea="true"
~~~
If you need to go further you can take a look here:
https://xamarinhelp.com/safeareainsets-xamarin-forms-ios/

**Comment by vhugogarcia** [comment]
Are you planning to fully integrate the Grial's UI.Kit with iPhone X soon? just curiosity

**Comment by jpbrocca** [comment]
Next version.

**Comment by vhugogarcia** [comment]
Awesome @jpbrocca . Is there a possibility to know when are you planning to release the next version so we can plan a timeline for our client on a mobile project? please

thanks in advance

**Comment by muhaym** [comment]
@jpbrocca Could you please share the Link to the Xamarin Forms Xaml C issue? 
Is it #https://github.com/xamarin/Xamarin.Forms/issues/1316

Because I tried to upgrade our Project to .NET Standard, Even with latest Xamarin.Forms, for code like OnPlatform, Xaml C Build is failing. Is it because I have Grial in the project?

**Comment by jpbrocca** [comment]
Hi @muhaym,
Yes, that was the issue.
Also, this one is related:
https://bugzilla.xamarin.com/show_bug.cgi?id=60452

If you upgrade to latest Xamarin Forms (2.5.0.280555) it should work but, they introduced another bug affecting how android buttons are rendered. We are working on a fix for this issue, then, probably next week we will release our update as RTM.

Best,
JP

**Comment by muhaym** [comment]
Hi @jpbrocca, I did update to Xamarin Forms 2.5.280555, but not to Grial 2.6.0.0, I am facing the build issue? Is it because of Grial or the above bug mentioned?

**Comment by jpbrocca** [comment]
OK, I assumed you had Grial 2.6.0.0 RC on your project.

Grial shouldn't be causing this. 
You can try deleting the "obj" and "bin" folders of every project, closing Visual Studio, reopen and try to compile again.

If this still happening then please, send your project attached to:
![image](https://user-images.githubusercontent.com/15996999/36550665-90fe603a-17d4-11e8-9b4c-b8fe6db29e10.png)

...so we can take a look.

Best,
JP

**Comment by voicebooth** [comment]
Any ideas when 2.6.0.0 will go to RTM?

**Comment by LeoHere** [comment]
@voicebooth it is planned for early next week.

**Comment by faceoffers28** [comment]
@jpbrocca @LeoHere Can we get some upgrade procedures for moving to Grial 2.6.9.0? I looked all over the documentation and this support site. I could not find any upgrade procedures. Thanks!

**Comment by LeoHere** [comment]
@faceoffers28 If you need to upgrade from the 2.6 RC to the 2.6.9, just upgrade the nuget packages.

**Comment by faceoffers28** [comment]
@LeoHere Which packages are you referring to? Can you be more specific? Here is what I think you are referring to. 

UXDivers.Artina.Shared 2.5.2
UXDivers.Artina.Shared.Base 2.5.2
UXDivers.Effects 0.6.0

As you can see here, there is nothing under Version and Options, so I can't upgrade. I'm running Visual Studio Enterprise 2015 Update 3.

![image](https://user-images.githubusercontent.com/10619627/37976605-779ca24a-31a7-11e8-8d7d-e730006f1a11.png)

As you can see here, it looks like I can update the UXDivers.Effects package.

![image](https://user-images.githubusercontent.com/10619627/37976878-15a7c460-31a8-11e8-94d9-1aa5f92418e6.png)

**Comment by LeoHere** [comment]
@faceoffers28 you should update the following packages (in the 3 projects):

- `UXDivers.Artina.Shared` to `2.6.9`
- `UXDivers.Artina.Shared.Base` to `2.6.9`
- `UXDivers.Artina.Controls.Repeater` to `2.6.9` (if you have a PRO)
- `UXDivers.Artina.Controls.Tab` to `2.6.9` (if you have a PRO)
- `Xamarin.Forms` to `2.5.0.280555`

This is to migrate from `2.6-RC` to `2.6.9`. Are you using `2.6-RC`?

**Comment by faceoffers28** [comment]
@LeoHere [assembly: UXDivers.Artina.Shared.GrialVersion("2.5.0.0")] Same update procedure??? Thanks!

**Comment by LeoHere** [comment]
@faceoffers28 by upgrading those packages you will be using the same version of the Shared packages and Xamarin Forms that 2.6.9 uses. 

Grial 2.6 is .NET Standard based no PCL based as 2.5 is.

**Comment by faceoffers28** [comment]
@LeoHere Interesting! I guess I will stay with 2.5, then. I will also need to learn more about the difference between .Net Standard and PCL. Both of my Xamarin apps are currently supported by a PCL-based SDK that interfaces with my API.
