### ISSUE TITLE
TabControl - OnTapped?

### ISSUE THREAD

**Issue by ianvink** [UXDivers/Grial-UI-Kit-Support#337]
Our UI needs to display something outside the tabs when a certain tab is clicked, but there don't seem to be any Selected events?

**Comment by ianvink** [comment]
Fantastic tool by the way, nice job guys.

**Comment by jpbrocca** [comment]
Hi @ianvink, how are you?
Thanks a lot for the positive feedback!! :)

Please take a look at #248 where it is explained how to handle events with `TabControl`.

Best regards,
JP
