### ISSUE TITLE
ListView Click and Drag Order of Items

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#339]
Hi @jpbrocca , 

Happy new year :)

I would like to ask if Grial has a built in reordering functionality of items ?

thanks

**Comment by markmark028** [comment]
I hope we have this in Grial.

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay, happy new year for you too!

No, Grial just uses ListViews provided by
 Xamarin Forms.

Best
JP

**Comment by KirkPatrickJunsay** [comment]
Ok, thanks for the info 👍
