### ISSUE TITLE
Private email - Xamarin Component Store error

### ISSUE THREAD

**Issue by PolywickStudio** [UXDivers/Grial-UI-Kit-Support#34]
Do you have a private email address?

I have a Xamarin Component Store error trying to buy your component.

**Comment by pablogermano** [comment]
Hi there. Thank you for reporting this issue, we will try to contact Xamarin Component Store support.
If it's not a problem for you, please purchase it directly on our site [](http://www.grialkit.com/download)

Thanks in advance

**Comment by PolywickStudio** [comment]
Purchased. Thank you.
