### ISSUE TITLE
How to print in console

### ISSUE THREAD

**Issue by msl2000** [UXDivers/Grial-UI-Kit-Support#340]
Hi 

Apologies if this seems like a really low level question but I can't seem to find a way to be able to log to the console.

Doing some testing and would really appreciate knowing how to print our.

System.Console and System.Debug aren't available in the starter package.

**Comment by jpbrocca** [comment]
Hi @msl2000,

I am not sure what you are asking, or why you mention the starter, but if you just need to log something you normally use Console.WriteLine("Text here");

You can take a look here for more details:
https://developer.xamarin.com/api/member/System.Console.WriteLine()/

...and here:
https://developer.xamarin.com/recipes/cross-platform/ide/debugging/output_information_to_log_window/

Best
JP
