### ISSUE TITLE
Responsive Helpers

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#341]
Hi @jpbrocca,

I have a question with Responsive Helpers, In iOS the artina:OnOrientationBool is working while in Android it is not working. I attached the sample code snippet for your reference.

![responsivehelper](https://user-images.githubusercontent.com/12691869/34599095-9d42bf18-f22b-11e7-8343-49adafc8d75c.PNG)

thanks

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay, how are you?

Can you let me know:

- Are you testing on real devices or emulators?
- Which Android version are you targeting?
- Xamarin forms version?

Thanks,
JP

**Comment by KirkPatrickJunsay** [comment]
Hi @jpbrocca 

I'm doing fine,
I'm testing in real device Android O.S. Version **7.0** and Xamarin Version is **2.4.0.282**

thanks,
kirk

**Comment by jpbrocca** [comment]
Hi @KirkPatrickJunsay, how are you?

I did a fast test and could not reproduce your issue.

I tried with this code:

~~~
<StackLayout 
    Padding="40"
    IsVisible="{ 
        artina:OnOrientationBool
            Default=False,
            Landscape=True
        }">
    <Button Text="Btn0" BackgroundColor="Red" TextColor="White" />
    <Button Text="Btn1" BackgroundColor="Blue" TextColor="White" />
    <Button Text="Btn2" BackgroundColor="Orange" TextColor="White" />
</StackLayout>
~~~

...and it seems to be working properly.

**Comment by jpbrocca** [comment]
Hi again @KirkPatrickJunsay :)

Just something to make sure you have all the necessary stuff to make the responsive helpers run on Android...did you make sure you added in your `MainActivity.cs`?:

~~~
...
ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.Locale | ConfigChanges.LayoutDirection
...

public override void OnConfigurationChanged(Android.Content.Res.Configuration newConfig)
        {
			base.OnConfigurationChanged(newConfig);

			GrialKit.NotifyConfigurationChanged(newConfig);

			if ((int)Build.VERSION.SdkInt <= 19 &&
			    !_locale.Equals(newConfig.Locale))
			{
				// Need to recreate the activity when locale has changed for APIs 18 and 19 
				// as changes in ConfigChanges.Locale brake images used in the app
				Recreate();
			}
        }
...
~~~

**Comment by KirkPatrickJunsay** [comment]
Hi @jpbrocca 

I tried the code snippet inside **OnConfigurationChanged** and it works wonderfully.
thanks again for the support 👍 

thanks,
kirk
