### ISSUE TITLE
IOS Application loader - Missing ICON error

### ISSUE THREAD

**Issue by qaliwebguru** [UXDivers/Grial-UI-Kit-Support#343]
Hi

Can you please help me? Why IOS Application loader giving the error of missing icons? In grial project i have only replace the images with exactly same sizes. 

Is there any update which i need to get or this is some other issue?
![20180108_151112](https://user-images.githubusercontent.com/31895946/34677080-e1be6004-f486-11e7-95d0-d6753ac62501.jpg)

**Comment by jpbrocca** [comment]
Hi @qaliwebguru,

It seems this is something Apple changed recently.

Check here:
https://forums.developer.apple.com/thread/86290

...and here for possible solutions:
https://stackoverflow.com/questions/46109835/app-icons-not-included-in-build-from-xcode-9

Looks some folks are pointing this to an issue on `info.plist` or the color profile on the icons used for their app. Check if any of those could be your case.

Best,
JP

**Comment by qaliwebguru** [comment]
Its very weird. No luck.

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it if you need so.
