### ISSUE TITLE
AppMap Issues

### ISSUE THREAD

**Issue by mdredmond** [UXDivers/Grial-UI-Kit-Support#344]
This isn't strictly Grial's issue, but since November, Infragistic's AppMap only supports .NET Standard 2.0 PCLs.  The PCL supplied in the Grial starter solution doesn't target .NET Standard so AppMap can't be added to it.  That leaves the tedious process of adding Grial to to the skeleton application that AppMap produces... 

I'm not good enough with Xamarin Forms to weed through these issues...  It all seems so fragile.

**Comment by jpbrocca** [comment]
Hi @mdredmond, how are you?

We have recently released an update to support .NET Standard in Grial.
Please take a look a this:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/336

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again is you need to.
