### ISSUE TITLE
artina:GridOptionsView Click Event

### ISSUE THREAD

**Issue by msl2000** [UXDivers/Grial-UI-Kit-Support#346]
Hi there

For artina:GridOptionsView, is there a way to toggle a click event after pressing an image? The ItemClickCommand is not responding

Coded as so:

xaml:
<artina:GridOptionsView Padding="10,20" ColumnSpacing="10" RowSpacing="10" VerticalOptions="Fill" HeightRequest="120" ColumnCount="3" RowCount="1" ItemClickCommand="Video_Clicked" ItemsSource="{Binding videos}">

code behind:
private async System.Threading.Tasks.Task Video_Clicked(object sender, SelectedItemChangedEventArgs e)
        {
            Dribl.Models.Video videos = (Dribl.Models.Video)e.SelectedItem;
            await this.Navigation.PushAsync(new VideoView(videos));
        }

**Comment by LeoHere** [comment]
@msl2000 `ItemCliclCommand` expects a command not an event handler. Please check #207 for an example of how to use it.

**Comment by msl2000** [comment]
Thank you for that, Problem has been solved and just added an event handler to the template!
