### ISSUE TITLE
Input text disappear when sending message

### ISSUE THREAD

**Issue by jsucupira** [UXDivers/Grial-UI-Kit-Support#347]
On the Chat Messages List Screen when you click on the input text to enter a message the input is hidden by the keyboard.
![no-focus](https://user-images.githubusercontent.com/1004621/35003463-f2037686-faba-11e7-828c-fff161d73b4b.png)
![with-focus](https://user-images.githubusercontent.com/1004621/35003475-f6bf1e5a-faba-11e7-9fa9-cd8f5ac774de.png)

**Comment by jpbrocca** [comment]
Hi @jsucupira, how are you?

Please check this related issue:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/173

Best,
JP
