### ISSUE TITLE
Problem about showing GrialShapesFont.LogoGrial

### ISSUE THREAD

**Issue by gurhangulmez** [UXDivers/Grial-UI-Kit-Support#349]
Hi,

I am coding in a bank for a big Xamarin project and trying to use Grial Front End stylings and xamls.

I opened your Full Grial project and my Xamarin project side by side and I am copying your xaml and styles to my Xamarin Project. This is my way of coding.

This picture demonstrates my problem, I can’t see any Preview because of IconsFontFamily problem at the below. What is the problem? I can’t understand the working method of IconsFontFamily.

grialshapes.ttf exists in …IOS/Resources and BuildAction is BundleResources,

The Code is:          <OnPlatform x:Key="IconsFontFamily" x:TypeArguments="x:String" Android="grialshapes.ttf#grialshapes" iOS="grialshapes" />

What is the incomplete thing here?

![a](https://user-images.githubusercontent.com/13269673/35149610-d956d7e4-fd27-11e7-857e-fd930269f1b9.jpg)

**Comment by jpbrocca** [comment]
Hi @gurhangulmez, 
As I mentioned in your previous reported issue, the Xamarin Previewer is limited.
Just to make sure, try to run your app and check. Most probably it will work but it won't be correctly previewed. If cannot compile and get errors check what it says, this will provide more clues about what could be wrong/missing.

Also, please have a look at the docs about working with font icons and Grial:

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-working-with-projects-adding-font-icons-to-your-project

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again is you need to.
