### ISSUE TITLE
Enviar Parámetros a ContentPage contenido en CarouselPage

### ISSUE THREAD

**Issue by HectorOCH** [UXDivers/Grial-UI-Kit-Support#350]
Estimados, tengo un **CarouselPage** con distintos **ContentPage** contenidos, mi pregunta es: ¿Como entregarles _parámetros_ a los **ContentPage** desde el **CarouselPage**?

```javascript
<CarouselPage  ...>
         <local:Sitio1Page ...  />
         <local:Sitio2Page  ...  />
         <local:Sitio3Page  ...  />
</CarouselPage>
```

Necesito que **Sitio1Page**, por ejemplo reciba un parametro
```javascript
public Sitio1Page(string Variable = "")
{
      DoSomethingsNumero();
}
```

Estoy utilizando el Template **WalkThroughPage.xaml**

**Comment by dirivero** [comment]
Hector, hay varias opciones. 

Puedes instanciar las páginas desde el code-behind del CarouselPage agregándolas a la colección de Children. De esta forma le puedes pasar parámetros como a cualquier otro objeto creado dede C#. Aquí hay algún ejemplo:

https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/navigation/carousel-page/

Alternativamente puedes definir propiedades en las ContentPages, en lugar de parámetros en el constructor, a las que le puede asignar valores desde Xaml. Si vas a utilizar Bindings como valores para esas propiedades, éstas deben ser BindableProperties:

https://developer.xamarin.com/guides/xamarin-forms/xaml/bindable-properties/

**Comment by HectorOCH** [comment]
@dirivero , definí propiedades **BindableProperties** en las **ContentPage**, asi resolví mi problema.

Muchas Gracias.
