### ISSUE TITLE
GrialShapesFont.Close  icon problem

### ISSUE THREAD

**Issue by gurhangulmez** [UXDivers/Grial-UI-Kit-Support#351]
Hi,

I can't see GrialShapesFont.Close icons on screens,
But I am already using Grial Full Solution and I haven't changed a code about it,
Could you please help me to find the solution?

Screen Codes : 
			
			<Label Style="{StaticResource IconCloseLabelStyle}" HorizontalOptions="End" VerticalOptions="Start" TranslationX="-20" TranslationY="35" Grid.Row="0">
				<Label.GestureRecognizers>
					<TapGestureRecognizer Tapped="OnCloseButtonClicked" />
				</Label.GestureRecognizers>
			</Label>

App.xml Codes :
			
			<Style x:Key="IconCloseLabelStyle" TargetType="Label" BasedOn="{StaticResource FontIcon}">
				<Setter Property="FontSize" Value="20" />
				<Setter Property="VerticalOptions" Value="FillAndExpand" />
				<Setter Property="Text" Value="{ x:Static local:GrialShapesFont.Close }" />
				<Setter Property="HorizontalTextAlignment" Value="End" />
				<Setter Property="VerticalTextAlignment" Value="Center" />
				<Setter Property="TextColor" Value="{ DynamicResource OverImageTextColor }" />
				<Setter Property="HeightRequest" Value="30" />
				<Setter Property="WidthRequest" Value="30" />
			</Style>

![untitled](https://user-images.githubusercontent.com/13269673/35331162-5ecd80ec-0117-11e8-9068-7a86d1fd88c7.png)

**Comment by jpbrocca** [comment]
Hi @gurhangulmez, how are you?

Actually, it seems you can't see Grial logo (on this page it is also made through Grialshapes).

I am not sure I understood...is this happening on your downloaded Grial Full sample?...or is this just happening in your own project where you are adding stuff from Grial Full sample?

If it is the later, then, make sure in your App.xaml you have set the font like this:

~~~
<!-- PUT YOUR OWN ICONS FONT FAMILY BELOW -->
	<OnPlatform 
		x:Key="IconsFontFamily" x:TypeArguments="x:String"
		Android="grialshapes.ttf#grialshapes"
		iOS="grialshapes"
	/>
~~~

Also, is this happening on iOS or Android?
If it is iOS you will need to make sure to add the font to your `info.plist` file.

More info here:

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-working-with-projects-adding-font-icons-to-your-project

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons-adding-your-own-icon-font-to-you-app

Best,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again is you need to.
