### ISSUE TITLE
Concatenacion de String en Button con un Icono

### ISSUE THREAD

**Issue by HectorOCH** [UXDivers/Grial-UI-Kit-Support#352]
Estimados, me gustaría saber como concatenar  un String en un Button con un icono, no concibo la forma de hacerlo.

```javascript
<artina:Button  Style="{ StaticResource FontIcon2 }"   TextColor="White" x:Name="refresh"
 Text="{ x:Static local:GrialShapesFont.Loop + TEXTO }"
 BackgroundColor="#000000" Clicked="function_Clicked" />
```

Héctor.

**Comment by jpbrocca** [comment]
Hola @HectorOCH, qué tal?
Los botones  `artina:Button` están basados en la clase `Button` de xamarin forms, por lo que no permiten utilizar simultáneamente un icono y un texto dado que en ambos casos es un único elemento el que muestra el string, por lo tanto la fuente desplegada será sólo la del icono o la del texto del botón.

Saludos,
JP

Lo que puedes hacer es usar una imagen (bitmap):
https://developer.xamarin.com/api/property/Xamarin.Forms.Button.Image/

Para controlar la disposición de la imagen en el botón puedes emplear la propiedad `ContentLayout`:
https://developer.xamarin.com/api/property/Xamarin.Forms.Button.ContentLayout/

**Comment by LeoHere** [comment]
Closing the issue. Feel free to open it again is you need to.
