### ISSUE TITLE
Android squashed

### ISSUE THREAD

**Issue by JamesPetras** [UXDivers/Grial-UI-Kit-Support#354]
Hi,

I've just downloaded a full sample (version 2.5.0.0) restored all NuGet packages run using Visual Studio for Mac and default Android emulator Android_Accelerated_Nugat (emulator version 26.1.4-4266726) and all forms are squashed. Please see few screenshots.

<img width="494" alt="spalsh" src="https://user-images.githubusercontent.com/16455026/35484042-cad258f8-0441-11e8-953c-9e8e10f804dd.png">

<img width="493" alt="article" src="https://user-images.githubusercontent.com/16455026/35483806-436a9f18-043e-11e8-9649-c5065a3bca17.png">
<img width="506" alt="register" src="https://user-images.githubusercontent.com/16455026/35483808-467fcade-043e-11e8-8d32-10e4fa87d244.png">

On iOS works perfectly but I would expect to work perfectly on Android as well. Is this due emulator or?

**Comment by jpbrocca** [comment]
Hi @JamesPetras, how are you?

Yes, most probably this is caused by the emulator.
Can you try with a real device or a different emulator (genymotion for instance), just to make sure?

Best,
JP
