### ISSUE TITLE
Fill circle image

### ISSUE THREAD

**Issue by msl2000** [UXDivers/Grial-UI-Kit-Support#355]
Hi

I just wanted to ask how to make an image expand to fill a CircleImage. In the social page, uploading an image that is rectangular vertically leads to some space at the left and right end of the image circle which looks a bit odd.

Best regards
Marvis

**Comment by jpbrocca** [comment]
Hi Marvis, how are you?
did you already try adding `Aspect="AspectFill"` to your CircleImage?

Best,
JP

**Comment by jpbrocca** [comment]
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/263
JP

**Comment by msl2000** [comment]
Hi jp

Thanks a lot, AspectFill made things a bit weird but AspectFit did the trick!
