### ISSUE TITLE
Tab Height

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#356]
Hi,

Looking at the latest release of Grial UI Kit (2.6.0.0 RC) that supports the Font Icon on Tab,  GrialTabControl.

Notice the tab is taking more space than the previous version. How can I change the tab height?

Thanks,
Dennis

![simulator screen shot - iphone 7 - 2018-01-30 at 11 14 21](https://user-images.githubusercontent.com/23342040/35546397-fe03cc48-05ae-11e8-95e8-e10f9d838df5.png)

**Comment by jpbrocca** [comment]
Hello @denfung, how are you?

Yes, you can customize almost everything about the `TabControl` through the XAML resources and templates.

You will need to locate the `TabControlCustomResources.xaml` file in your project:

~~~
 |_ Views
   |_ Theme
     |_ Resources
        |_ TabControlCustomResources.xaml
~~~

Then you can change the value of the resource `CustomTabStripIconAndTextHeightRequest`.

Here I have set it to `20` to show how the height changes and the icons will resize to fit:

`<x:Double x:Key="CustomTabStripIconAndTextHeightRequest">20</x:Double>`

![image](https://user-images.githubusercontent.com/15996999/35575799-188db224-05bc-11e8-976b-411ed3d5e00a.png)

Best,
JP
