### ISSUE TITLE
Extending Renderers overwrites base styling

### ISSUE THREAD

**Issue by nd-srogers** [UXDivers/Grial-UI-Kit-Support#359]
I am trying to put a gradient as the background of one of my buttons using a method similar to the first answer here: https://stackoverflow.com/questions/37946140/set-gradient-as-button-color-renderer

I still want to use the extra features afforded to me by the ArtinaButton component, so I extended the ArtinaButton and ArtinaButtonRenderer with my custom component and renderer with extra fields to set gradient details and set the background to a `GradientBackground`. (focusing on droid only)

However, when I run the app, depending on the order of when I call the base methods in my renderer, either my code completely overwrites the Artina code (losing the rounded sides etc), or the Artina code overwrites mine (losing the gradient).

Is there anyway to properly extend the Artina component and renderer to add additional features like this, while keeping the base functionality intact?

GradientButton.cs:
    
    public class GradientButton : UXDivers.Artina.Shared.Button
    {
        public static readonly BindableProperty DirectionProperty = BindableProperty.Create(
            propertyName: "Direction",
            returnType: typeof(GradientDirection),
            declaringType: typeof(GradientButton),
            defaultValue: GradientDirection.LeftRight);

        public GradientDirection Direction
        {
            get { return (GradientDirection)GetValue(DirectionProperty); }
            set { SetValue(DirectionProperty, value); }
        }

        public static readonly BindableProperty StartColorProperty = BindableProperty.Create(
            propertyName: "StartColor",
            returnType: typeof(Color),
            declaringType: typeof(GradientButton),
            defaultValue: Color.Black);

        public Color StartColor
        {
            get { return (Color)GetValue(StartColorProperty); }
            set { SetValue(StartColorProperty, value); }
        }

        public static readonly BindableProperty EndColorProperty = BindableProperty.Create(
            propertyName: "EndColor",
            returnType: typeof(Color),
            declaringType: typeof(GradientButton),
            defaultValue: Color.Black);

        public Color EndColor
        {
            get { return (Color)GetValue(EndColorProperty); }
            set { SetValue(EndColorProperty, value); }
        }
    }

    public enum GradientDirection
    {
        BottomLeftTopRight,
        BottomTop,
        BottomRightTopLeft,
        LeftRight,
        RightLeft,
        TopLeftBottomRight,
        TopBottom,
        TopRightBottomLeft,
    }

GradientButtonRenderer.cs
    
    public class GradientButtonRenderer : UXDivers.Artina.Shared.ArtinaButtonRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.Button> e)
        {
            UpdateGradient();
            base.OnElementChanged(e); // if this is before UpdateGradient, Artina style is overwritten
        }
        
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == GradientButton.StartColorProperty.PropertyName ||
                e.PropertyName == GradientButton.EndColorProperty.PropertyName ||
                e.PropertyName == GradientButton.DirectionProperty.PropertyName)
            {
                UpdateGradient();
            }
            base.OnElementPropertyChanged(sender, e); // if this is before UpdateGradient, Artina style is overwritten
        }

        protected override void UpdateBackgroundColor()
        {
            UpdateGradient();
            base.UpdateBackgroundColor(); // if this is before UpdateGradient, Artina style is overwritten
        }

        private void UpdateGradient()
        {
            var button = this.Element as GradientButton;
            if (button != null && this.Control != null)
            {
                int[] colors = { button.StartColor.ToAndroid(), button.EndColor.ToAndroid() };
                var gradientDrawable = new GradientDrawable(GetOrientation(button.Direction), colors);
                gradientDrawable.SetGradientType(GradientType.LinearGradient);
                this.Control.Background = gradientDrawable;
            }
        }

        private GradientDrawable.Orientation GetOrientation(GradientDirection direction)
        {
            switch (direction)
            {
                case (GradientDirection.BottomLeftTopRight):
                    return GradientDrawable.Orientation.BlTr;
                case GradientDirection.BottomTop:
                    return GradientDrawable.Orientation.BottomTop;
                case GradientDirection.BottomRightTopLeft:
                    return GradientDrawable.Orientation.BrTl;
                case GradientDirection.LeftRight:
                    return GradientDrawable.Orientation.LeftRight;
                case GradientDirection.RightLeft:
                    return GradientDrawable.Orientation.RightLeft;
                case GradientDirection.TopLeftBottomRight:
                    return GradientDrawable.Orientation.TlBr;
                case GradientDirection.TopBottom:
                    return GradientDrawable.Orientation.TopBottom;
                case GradientDirection.TopRightBottomLeft:
                    return GradientDrawable.Orientation.TrBl;
            }

            return GradientDrawable.Orientation.TopBottom;
        }
    }

**Comment by dirivero** [comment]
Hi,

The current version of ArtinaButtonRenderer does not do anything, it only derives from Xamarin.Forms.Platform.Android.ButtonRenderer. In older versions it added the border properties but that's not needed anymore.

You can find more info here: https://bugzilla.xamarin.com/show_bug.cgi?id=36031

This means that you can extend directly from the Xamarin ButtonRenderer (make sure not to use the appcompat version) and go from there. 

You can verify this editing the AssemblyInfo.cs of your Android project and replacing this line:

[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.Button), typeof(UXDivers.Artina.Shared.ArtinaButtonRenderer))]

with this one:

[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.Button), typeof(Xamarin.Forms.Platform.Android.ButtonRenderer))]

Regards
Diego

**Comment by nd-srogers** [comment]
@dirivero Changing the renderer does demonstrate that, however something else must be going on.

I tried the following:

    <components:GradientButton Text="Get Started" Style="{StaticResource RoundedButtonStyle}" 
                                           VerticalOptions="EndAndExpand"
                                           HorizontalOptions="{ artina:OnOrientationLayoutOptions PortraitPhone=Fill, LandscapePhone=Fill, PortraitTablet=Fill, LandscapeTablet=Center }" 
                                           WidthRequest="{ artina:OnOrientationDouble LandscapeTablet=600 }"
                                           StartColor="{StaticResource GradientPinkColor}"
                                           EndColor="{StaticResource GradientPurpleColor}"
                                           Direction="BottomLeftTopRight"/>
    
    <artina:Button Text="Get Started" Style="{StaticResource RoundedButtonStyle}" VerticalOptions="EndAndExpand"/>
    
    <Button Text="Get Started" Style="{StaticResource RoundedButtonStyle}" VerticalOptions="EndAndExpand"/>

Results in the following:

![image](https://user-images.githubusercontent.com/33408863/35891076-280fa4fe-0bee-11e8-99eb-12cf06e670ef.png)

Note the slight corner radius on the top button, I attempted to use `SetCornerRadius`, but it doesn't give the same pill shape as the Artina button. Also note the bottom button which is a stock Xamarin button has no corner radius at all even though it uses `RoundedButtonStyle`.

Is there something else I'm missing?

**Comment by dirivero** [comment]
The last one is rendered through the appcompat ButtonRenderer because that's the default one, that's why the corner has the default minimum radius in that case.

Going back to your renderer, it seems you are overriding the background generated by the Xamarin renderer. Please take a look at this helper class used by the Xamarin renderer to draw the background and outline (border + radius):

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ButtonDrawable.cs

By using a code similar to that you should be able to render the gradient and the outline manually within your renderer.

Hope this helps.

**Comment by nd-srogers** [comment]
That got me on the right track. Basically because `GradientDrawable` implements `Drawable` I had to implement my own `GradientButtonDrawable` that takes codes from both `ButtonDrawable` and `GradientDrawable` to get the correct result.

I'll close this issue since it isn't related to Grial. Thanks for your help.
