### ISSUE TITLE
Request recompilation of 

### ISSUE THREAD

**Issue by PolywickStudio** [UXDivers/Grial-UI-Kit-Support#36]
2>e.Styleable' does not contain a definition for 'Theme_editTextColor'
2>Droid\Resources\Resource.designer.cs(3061,114,3061,133): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_editTextStyle'
2>Droid\Resources\Resource.designer.cs(3062,118,3062,141): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_homeAsUpIndicator'
2>Droid\Resources\Resource.designer.cs(3063,130,3063,165): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listChoiceBackgroundIndicator'
2>Droid\Resources\Resource.designer.cs(3064,123,3064,151): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listDividerAlertDialog'
2>Droid\Resources\Resource.designer.cs(3065,121,3065,147): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPopupWindowStyle'
2>Droid\Resources\Resource.designer.cs(3066,124,3066,153): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPreferredItemHeight'
2>Droid\Resources\Resource.designer.cs(3067,129,3067,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPreferredItemHeightLarge'
2>Droid\Resources\Resource.designer.cs(3068,129,3068,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPreferredItemHeightSmall'
2>Droid\Resources\Resource.designer.cs(3069,129,3069,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPreferredItemPaddingLeft'
2>Droid\Resources\Resource.designer.cs(3070,130,3070,165): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_listPreferredItemPaddingRight'
2>Droid\Resources\Resource.designer.cs(3071,116,3071,137): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_panelBackground'
2>Droid\Resources\Resource.designer.cs(3072,119,3072,143): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_panelMenuListTheme'
2>Droid\Resources\Resource.designer.cs(3073,119,3073,143): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_panelMenuListWidth'
2>Droid\Resources\Resource.designer.cs(3074,115,3074,135): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_popupMenuStyle'
2>Droid\Resources\Resource.designer.cs(3075,117,3075,139): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_popupWindowStyle'
2>Droid\Resources\Resource.designer.cs(3076,117,3076,139): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_radioButtonStyle'
2>Droid\Resources\Resource.designer.cs(3077,115,3077,135): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_ratingBarStyle'
2>Droid\Resources\Resource.designer.cs(3078,116,3078,137): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_searchViewStyle'
2>Droid\Resources\Resource.designer.cs(3079,125,3079,155): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_selectableItemBackground'
2>Droid\Resources\Resource.designer.cs(3080,135,3080,175): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_selectableItemBackgroundBorderless'
2>Droid\Resources\Resource.designer.cs(3081,125,3081,155): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_spinnerDropDownItemStyle'
2>Droid\Resources\Resource.designer.cs(3082,113,3082,131): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_spinnerStyle'
2>Droid\Resources\Resource.designer.cs(3083,112,3083,129): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_switchStyle'
2>Droid\Resources\Resource.designer.cs(3084,129,3084,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceLargePopupMenu'
2>Droid\Resources\Resource.designer.cs(3085,123,3085,151): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceListItem'
2>Droid\Resources\Resource.designer.cs(3086,128,3086,161): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceListItemSmall'
2>Droid\Resources\Resource.designer.cs(3087,135,3087,175): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceSearchResultSubtitle'
2>Droid\Resources\Resource.designer.cs(3088,132,3088,169): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceSearchResultTitle'
2>Droid\Resources\Resource.designer.cs(3089,129,3089,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textAppearanceSmallPopupMenu'
2>Droid\Resources\Resource.designer.cs(3090,129,3090,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textColorAlertDialogListItem'
2>Droid\Resources\Resource.designer.cs(3091,119,3091,143): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_textColorSearchUrl'
2>Droid\Resources\Resource.designer.cs(3092,129,3092,163): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_toolbarNavigationButtonStyle'
2>Droid\Resources\Resource.designer.cs(3093,113,3093,131): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_toolbarStyle'
2>Droid\Resources\Resource.designer.cs(3094,116,3094,137): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowActionBar'
2>Droid\Resources\Resource.designer.cs(3095,123,3095,151): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowActionBarOverlay'
2>Droid\Resources\Resource.designer.cs(3096,124,3096,153): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowActionModeOverlay'
2>Droid\Resources\Resource.designer.cs(3097,123,3097,151): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowFixedHeightMajor'
2>Droid\Resources\Resource.designer.cs(3098,123,3098,151): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowFixedHeightMinor'
2>Droid\Resources\Resource.designer.cs(3099,122,3099,149): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowFixedWidthMajor'
2>Droid\Resources\Resource.designer.cs(3100,122,3100,149): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowFixedWidthMinor'
2>Droid\Resources\Resource.designer.cs(3101,120,3101,145): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowMinWidthMajor'
2>Droid\Resources\Resource.designer.cs(3102,120,3102,145): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowMinWidthMinor'
2>Droid\Resources\Resource.designer.cs(3103,114,3103,133): error CS0117: 'Resourc
2>e.Styleable' does not contain a definition for 'Theme_windowNoTitle'

**Comment by giammin** [comment]
this is the same of https://github.com/UXDivers/Grial-UI-Kit-Support/issues/37

**Comment by PolywickStudio** [comment]
This is fixed with Grail 1.5
