### ISSUE TITLE
Xamarin Preview Resx error

### ISSUE THREAD

**Issue by ufuf** [UXDivers/Grial-UI-Kit-Support#363]
After migrating my project to Grial I started to get an error on preview which prevents views to be loaded.

You can find the error screenshot attached.
![screen shot 2018-02-07 at 18 32 16](https://user-images.githubusercontent.com/4348233/35924942-7b0f7f5c-0c35-11e8-99e9-80dd97c1f94d.png)

**Comment by jpbrocca** [comment]
Hi @ufuf,
Please check this related issue:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/348

Best,
JP
