### ISSUE TITLE
RTL nav bar does not appear

### ISSUE THREAD

**Issue by musab-alrmmah** [UXDivers/Grial-UI-Kit-Support#364]
When the nav bar appears, the Language Switch button does not appear

![28033265_1701016506625724_1613191969_o](https://user-images.githubusercontent.com/17981288/36090455-79c1cc1c-0ff1-11e8-95b3-b14d21fab2f8.png)

**Comment by jpbrocca** [comment]
Hi @musab-alrmmah, how are you?

Can you provide more details about your issue?

1. What are you running? Is that a Grial PRO + RTL Full sample?
2. Is it your own project with pages you are copying from Grial full sample? If so...did you follow steps from documentation to enable and properly use RTL?
http://uxdivers.github.io/Grial-UI-Kit-Support/rtl-page.html

Best,
JP

**Comment by szaid07** [comment]
i want to change the text of rtl button in navigation bar where i can find it

**Comment by jpbrocca** [comment]
Hi @szaid07,

This button uses an image which you can locate here:

~~~
Grial
    |_ Grial.iOS
        |_ Resources
            |_ RTL_icon.png
~~~

Best,
JP
