### ISSUE TITLE
Purchased Pro License, I downloaded the 2.6.0.0 RC Full Sample Gorilla Ready

### ISSUE THREAD

**Issue by eglibecerra** [UXDivers/Grial-UI-Kit-Support#366]
Hi, 
Purchased Pro License, I downloaded the 2.6.0.0 RC Full Sample Gorilla Ready, been trying to get this working for 2 days I've given up trying. (we have so many potential pro license purchases lined up, so if you can help it will be win win for us)

Just trying to be able to view the virigin un modified solution in Gorilla Player, I have my vs2017 extension installed, and my devices connected to them just fine, like I said 2.6.0.0 RC Full Sample Gorilla Ready, I need RC as I need to use .NET Standard for the shared library.

Every time i try to see any page i keep getting the "Sad Gorilla, Issues found on f.e (happens on all the pages) Views\Navigation\WelcomePage.xaml I get 33 warnings, but the main thing is the "Gorilla SDK needed" for File: Views\Navigation\WelcomePage.xaml basically saying the following Bindings need data:
- Lottie.Forms
- UXDivers.Artina.Shared
- UXDivers.Artina.Shared.Base
- UXDivers.Effects
- FFImageLoading.Forms

Wish it just ran like from that sample you guys had in a video.

It would be great if you guys could lend a helping hand

**Comment by jpbrocca** [comment]
Hi @eglibecerra, how are you?

I tried to reproduce your issue but I couldn't. 
Here are the steps I followed:

1. I configured my app to use 2.6 RC
![image](https://user-images.githubusercontent.com/15996999/36155481-3eb71920-10b3-11e8-9c5a-872cc0bf653e.png)
2. I downloaded Grial Full sample with Gorilla SDK pre-configured
![image](https://user-images.githubusercontent.com/15996999/36155509-51aad62a-10b3-11e8-940d-9219034c784f.png)
3. I started Gorilla Player server on my MAC
![image](https://user-images.githubusercontent.com/15996999/36155572-78c31a06-10b3-11e8-975c-ca7854ab3072.png)
4. I opened the solution in Visual Studio, then changed the configuration to run with Gorilla
![image](https://user-images.githubusercontent.com/15996999/36155645-aecff01a-10b3-11e8-9021-74d8981a9337.png)
5. I run the app with that configuration and made sure Gorilla is connected on my VS
![image](https://user-images.githubusercontent.com/15996999/36155695-cd11f14a-10b3-11e8-906f-03ede29c3e6c.png)
6. Opened a few pages and everything seems to be working OK
![image](https://user-images.githubusercontent.com/15996999/36155781-0bba2638-10b4-11e8-81ca-bfa4c220759e.png)

A couple of questions to check if maybe some step was missing:
a) Do you have latest Gorilla version (1.2.0.0)? this is the version that supports .NET Standard.
b) Did you make sure to download a Grial full sample with Gorilla pre-configured?
c) Did you make sure you see Gorilla SDK UI (dark orange as in the picture below)? A common mistake is people use just Gorilla Player out of the box (without SDK) which has a light orange UI:
![image](https://user-images.githubusercontent.com/15996999/36156059-c8216de0-10b4-11e8-81a1-b6bee3b90aea.png)

If you did all the above, then please try to clean, rebuild and run with Gorilla config again and try to preview any page. 

Let me know how it goes.

Best,
JP

**Comment by eglibecerra** [comment]
So i figured this out by browsing through several git issues, I realized that it needed to run the app through gorilla mode to open de gorilla sdk (its very obscure in documentation not as explicit) thanks for providing a very detail documentation. So one thing i needed to do was restart vs2017 (im on a pc not a mac btw) turn off my firewall for private network, I added an exclussion for the gorilla.exe but that didnt work...  

One thing to note my gorilla desktop is 1.2.0.0 like you mentioned, and when i run the Gorilla SDK is 1.2.0.0 but my IOS device (real device) has gorilla player 1.1.0.4 (is this the latest? for the actual app you download from the appstore?)

**Questions:** 
**1)** Once you run the gorilla mode and the gorilla sdk app loads up i have to manually put in the host address as it never finds the machine automatically like the external app does. So the question is which is the program you add for an exception rule in the firewall? i put the android sdk one i was running. (didnt seem to work) either way i managed to connect by manually entering the host address like I said.

**2)** Once you build and run through gorilla mode and the Gorilla SDK loads up, are you meant to leave it running? or turn it off? just wondering how that workflow goes...

**3)** I managed to void the previous errors i mentioned. But got the Lottie.Forms Bindings missing as
(And a heads up) the Android Project (for this 2.6.0.0 Full Grial Gorilla Ready ) doesn't register the Lottie.Froms in the MainActivity.cs like it does for the IO's AppDelegate.cs so you guys might want to update this. After registering that assembly I got the following errors:

**4**) my Gorilla.json is the default one provided by the download sample of it:

`{
  "localization": {
    "markupExtension": {
      "name": "Translate",
      "namespace": "UXDivers.Artina.Shared",
      "keyPropertyName": "Key"
    },
    "resources": {
      "resourceId": "CrossPlatform.CSR.Achieve.Resx.AppResources",
      "assembly": "CrossPlatform.CSR.Achieve",
      "defaultCulture": "en"
    }
  },
  "navigationPage": {
    "all": [
      true
    ],
    "exclude": [
      "WalkthroughFlatStepItemTemplate.xaml",
      "WalkthroughStepItemTemplate.xaml",
      "WalkthroughVariantStepItemTemplate.xaml",
      "WalkthroughFlatPage.xaml",
      "WalkthroughPage.xaml",
      "WalkthroughVariantPage.xaml",
      "LoginPage.xaml",
      "PasswordRecoveryPage.xaml",
      "SignUpPage.xaml",
      "SimpleLoginPage.xaml",
      "SimpleSignUpPage.xaml",
      "CustomNavBarPage.xaml",
      "WelcomePage.xaml",
      "MainMenuPage.xaml",
      "ProfilePage.xaml",
      "ArticleClassicViewItemTemplate.xaml",
      "ArticleFeedItemTemplate.xaml",
      "ArticleItemTemplate.xaml",
      "ArticleVariantItemTemplate.xaml",
      "CommentItemTemplate.xaml",
      "FrontPageHeaderItemTemplate.xaml",
      "FrontPageNewsItemTemplate.xaml",
      "Badge.xaml",
      "BrandBlock.xaml",
      "CircleIcon.xaml",
      "CustomActivityIndicator.xaml",
      "CustomNavBar.xaml",
      "Rating.xaml",
      "RoundedLabel.xaml",
      "DashboardAppNotificationItemTemplate.xaml",
      "DashboardCardItemTemplate.xaml",
      "DashboardItemTemplate.xaml",
      "DashboardMultipleScrollItemTemplate.xaml",
      "DashboardMultipleScrollMainItemTemplate.xaml",
      "DashboardMultipleScrollSectionTemplate.xaml",
      "DashboardVariantItemTemplate.xaml",
      "ProductGridItemTemplate.xaml",
      "ProductsCatalogItemTemplate.xaml",
      "ProductImageFullScreenPage.xaml",
      "ChatLeftMessageItemTemplate.xaml",
      "ChatRightMessageItemTemplate.xaml",
      "ChatTimelineIncomingItemTemplate.xaml",
      "ChatTimelineOutgoingItemTemplate.xaml",
      "MessageItemTemplate.xaml",
      "RecentChatItemTemplate.xaml",
      "CardsListItemTemplate.xaml",
      "CategoriesListItemTemplate.xaml",
      "CategoriesListWithIconsItemTemplate.xaml",
      "CategoriesListWithImagesItemTemplate.xaml",
      "MainMenuGroupHeaderTemplate.xaml",
      "MainMenuItemTemplate.xaml",
      "NotificationsListItemTemplate.xaml",
      "SamplesListFromCategoryItemTemplate.xaml",
      "DocumentTimelineLeftItemTemplate.xaml",
      "DocumentTimelineRightItemTemplate.xaml",
      "FriendItemTemplate.xaml",
      "SocialGalleryImage.xaml",
      "SocialHeaderTemplate.xaml",
      "SocialGalleryImagePreviewPage.xaml",
      "TimelineItemTemplate.xaml",
      "WalkthroughFlatStepItemTemplate.xaml",
      "WalkthroughStepItemTemplate.xaml",
      "WalkthroughVariantStepItemTemplate.xaml"
    ]
  },
  "clients": [
    {
      "kind": "GrialLive",
      "mappings": [
        {
          "from": {
            "className": "FontAwesomeFont",
            "namespace": "UXDivers.Artina.Grial"
          },
          "to": {
            "namespace": "CrossPlatform.CSR.Achieve"
          }
        }
      ]
    }
  ]
}`

but i do notice that some github issues you guys ask to add the "knownAssemblies" node in there? is this required if so why doesnt the one provided by the download provide it?

**Anyways....
The Errors (and note that all the sdk dependencies seemed to load fine now)**

Sad Gorilla, issues found on:
Views\Navigation\WelcomePage.xaml

Errors(2)
XAML: Position 21:116. MarkupExtension not found for artina:OnOrientationDouble
XAML: Position 147:5. Type Rating not found in xmlns clsr-namespace.<<the name of my netstandard lib>(provided by the download after configuring the name of it)

Warnings(10)
Unable to infer property type (Phone)
.
.
.(does the same for Tablet, iOS, Android

Can you help me with the errors and answer my questions.

**Kudos to all the UXDivers team for Gorilla and the Grail UI Toolkit its amazing (once it works like you guys promote) definately better then Xamarin Live Player.**

_If you could really help me with this id appreciate it and help put my case forward in my company in to using this ToolKit/Workflow going forward for our future enterprise apps..._

**Comment by LeoHere** [comment]
Hi,

1) You need to put `gorilla.exe` as a firewall exception. Both for TCP/UDP. UDP is used for auto discovery. UDP usually is not routed across access points/routers. So it is important both you desktop machine and you preview device to be connected to the same wireless network/router.
2) When you run Grial using Gorilla configuration, what you are doing is lunching Gorilla Player preview app preconfigured with the stuff used in Grial. This is the app you will use as a previewer. So yes you need it open since it is the one that will show you the preview. The Gorilla Player app available in the stores does not know anything about Grial, so don't use it to preview. If you need to preview Grial in your real device, just deploy Grial using **Gorilla** configuration into your real device and use that app. Please check the animated gif shown [here](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) to get an idea of how it works.
3) Ok, we will check this. Thanks.
4) The `knownAssemblies` section of the `Gorilla.json` is not required any more. Now the known assemblies is inferred from your project. You can still use the `knownAssemblies` if you need to enumerate the assemblies for some reason, but it is not needed in Grial.


The errors you are still getting should go away as soon as you start previewing using the app you deployed from running Grial in Gorilla mode.

**Comment by eglibecerra** [comment]
Hola Leo,

Thanks for explaining it point 2 made it all really clear, so then the question is whats the purpose of the Gorilla App in the AppStore? i guess this is what confuses everyone, but now that you mentioned it, it makes perfect sense. So in order to have the gorilla player functionality you have to deploy the gorilla from your IDE to your device, once there providing you didnt alter code and the dll's remain the same one should be able to run it and have it reflect the changes done in the Xaml view/page in the IDE....

Perfect Thanks for clarifying this

**Comment by LeoHere** [comment]
Hola!

The Gorilla app in the App Store allow you to preview XAML that makes uses of basic XF components + some popular libraries (like Prism, FFImageLoading, etc). Usually it's used to start with Gorilla or for educational proposes.
