### ISSUE TITLE
UWP Support issue

### ISSUE THREAD

**Issue by omaarmostafa** [UXDivers/Grial-UI-Kit-Support#370]
Hello,
 i got Grial kit pro license
and added UWP project to the solution and added all references to it
but when i'm run it gives me exception "Grial UI Kit license not initialized,please call 'UXDivers.Artina.Shared.GrialKit.Init(<License>)'
the problem now i can't write this line of code 
because **GrialKIT** is not loaded and i can't call it.

**Comment by chrisgate** [comment]
same issues here

**Comment by LeoHere** [comment]
@omaarmostafa please take a look at issue #367.
