### ISSUE TITLE
CircleImage

### ISSUE THREAD

**Issue by musab-alrmmah** [UXDivers/Grial-UI-Kit-Support#371]
How to set Source in CircleImage by type Image in XML

  <artina:CircleImage Source="{Binding image}"  // image is type image (convert from base64) from message class 
			Style="{ StaticResource Avatar }"
			Aspect="AspectFill"
			HorizontalOptions="Center"
			VerticalOptions="Start" 
			TranslationX="{ DynamicResource MessageItemTemplateAvatarTranslationX }" 
			TranslationY="14"/>

**Comment by jpbrocca** [comment]
Hi @musab-alrmmah,

`<artina:CircleImage>` derives from `<Image>`, so the correct type for the `Source` attribute should be `ImageSource`:

https://developer.xamarin.com/api/type/Xamarin.Forms.Image/
https://developer.xamarin.com/api/type/Xamarin.Forms.ImageSource/

Best,
JP
