### ISSUE TITLE
It's surprising to know a premium product like GRIAL UI have almost zero support

### ISSUE THREAD

**Issue by chrisgate** [UXDivers/Grial-UI-Kit-Support#372]
When they decided to reply u it's a week or more with no support at All.... since I bought it I just left  it somewhere. It supposed to make my development easier but now with zero support it's otherwise.

**Comment by dirivero** [comment]
I know this is old, but I'm sorry if you had a bad experience with support. 
I saw you had some interactions with our support & technical team after this thread. 
You can ping me directly to drivero at uxdivers.com if you need help.
