### ISSUE TITLE
use MaterialIcons

### ISSUE THREAD

**Issue by musab-alrmmah** [UXDivers/Grial-UI-Kit-Support#373]
how to use MaterialIcons inside project ?

**Comment by jpbrocca** [comment]
Hi @musab-alrmmah,

Normally as when you work with any icon font you will need to download the font containing the icons, then add it to your platform projects.
And you will need to reference each icon by its char to use them.

I did a fast search on Google and it seems Material Icons use ligatures:
http://google.github.io/material-design-icons/#icon-font-for-the-web
http://alistapart.com/article/the-era-of-symbol-fonts

...so I am not sure this will work in Xamarin Forms. 
If that is the case you will need to download all their SVG icons from their repo -or just the ones you are going to use-, then create your own font (you can use [iconmoon.com](https://icomoon.io/)) and finally add it to your project.
Check Grial docs about adding icons to your project for more details:

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-working-with-projects-adding-font-icons-to-your-project

Best,
JP

**Comment by musab-alrmmah** [comment]
i preview this link 
https://github.com/jsmarcus/Xamarin.Plugins/tree/master/MaterialIcons
but This error appears	(Failed to resolve assembly: 'MaterialIcons.FormsPlugin.Abstractions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

**Comment by dirivero** [comment]
Material icons are available as part of Grial 3:
http://docs.grialkit.com/features.html#features-more-than-5k-icons-included
