### ISSUE TITLE
TabControl with ContentPage

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#374]
Hi,

Looking at the Grial UIKit's TabControl. It is possible to use ContentPage instead of ContentView? Below is my sample code.

                         <tab:TabItem 
                                BadgeText="{Binding NotificationNumber}"
                                Text="Notification"
                                IconText="{ x:Static local:GrialShapesFont.Notifications }">
                                <views5:NotificationCatalogView/>
                            </tab:TabItem>

The " <views5:NotificationCataloView>" contains a ListView which is preloaded with 600+ items with the image.

Notice that when I select this tab, it takes sometimes to appear. So, I decided to do post loading of ListView data. However, due to this is a ContentView, there isn't "onAppearing" method that I can override to set the ListView data.

With above limitation, I am looking to do this with ContentPage. I tested with default Xamarin Forms' TabbedPage, it works well.

Please advice anyway we can do the same for Grial UIKit's TabControl.

Thanks,
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung, how are you?
No, the TabControl was made with the goal of allowing to have tabs within a page.

Best,
JP
