### ISSUE TITLE
UXDivers nuget fail to load. 401 (Unauthorized) – tried everything

### ISSUE THREAD

**Issue by havardo** [UXDivers/Grial-UI-Kit-Support#376]
I am having no luck loading nuget from uxdivers.com after changing the password on the Nuget server. The identical setup works fine on other machines. The pc with issues connected to the uxdivers nuget server first with other credentials. I have since removed these credentials, without this helping anything. 

Have tried all the tips that I have found. This include using nuget.exe, the VS nuget console, removing and manually adding windows credentials, nuget.config with explicit password, removing and replacing package sources, etc. Yes, and I have checked the spelling. 

Any new tips or a fresh approach would be very welcome.

**Comment by LeoHere** [comment]
@havardo are you able to authenticate agains [http://nuget.uxdivers.com/grial](http://nuget.uxdivers.com/grial) if you visit the url from your browser?

**Comment by havardo** [comment]
Yes, I tried that and it works like a breeze (forgot to mention this). Even tried with a few different browsers. Just tested the whole thing again after a full reboot. The 401 message came first, but subsequent attemtps to restore packages will just give me this one:
Error occurred while restoring NuGet packages: Failed to retrieve information about 'UXDivers.Artina.Controls.Repeater' from remote source 'http://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.Artina.Controls.Repeater''.

**Comment by LeoHere** [comment]
@havardo that is really weird. Is it possible that you still have your old credentials in a `Nuget.config` file in the file system?

**Comment by havardo** [comment]
Thanks for looking into this @LeoHere. There are no Nuget.config files on the system. I will try to configure a new project and see if that behaves the same (unless you or any body else have any other ideas). After that, I will see if wiping the folders and reload from source control makes any difference.

**Comment by havardo** [comment]
Thanks @faceoffers28. I finally got this to work setting up the <packageSourceCredentials> AppData\Roaming\NuGet\NuGet.Config File using the admin account (NOT the nuget access account). Please note - the admin account is without domain prefix. Just email address. 

It appears that the dedicated nuget access account is failing on this PC after the password was changed. I tried to remove all traces of the old account details without apparent success.

**Comment by canperk** [comment]
What about with Mac?
