### ISSUE TITLE
buttons style doesnt appear to be as in sample

### ISSUE THREAD

**Issue by kberawala** [UXDivers/Grial-UI-Kit-Support#377]
![image](https://user-images.githubusercontent.com/13636878/36884176-d5df2f48-1e2a-11e8-88e6-536719b9857d.png)

please let me know how to fix the button styling.

**Comment by jpbrocca** [comment]
Hi @kberawala,

This is caused by latest xamarin forms version:
https://github.com/xamarin/Xamarin.Forms/issues/1909

We are working on a fix.
 
Best,
JP

**Comment by kberawala** [comment]
do you have an ETA for fix for this ?

**Comment by jpbrocca** [comment]
Hi @kberawala, how are you?

If you use `<artina:Button>` and Grial latest packages, you should see them better.
Please check our release notes for more details:
http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html

Xamarin recently released Xamarin Forms 3.0 pre2 which fixes the linked issue.

Best,
JP
