### ISSUE TITLE
Dashed bolder

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#378]
Hi,

I am trying to create a ContentPage which allow user to add Photo from camera.

I need to create a placeholder with the dashed/dotted border line and “+” sign at the middle.

Does Grial UIKit allows to create dashed/dotted line border for frame or box control?

Please advice.

Thanks,
Dennis

**Comment by jpbrocca** [comment]
Hi @denfung, no Grial does not allow to add such borders.
The easiest way for you would be creating an image with those borders and the "+" icon.

Best,
JP
