### ISSUE TITLE
Change background color of list item?

### ISSUE THREAD

**Issue by yingzhox** [UXDivers/Grial-UI-Kit-Support#38]
Hi,

It seems that Grial forces the background of a selected(tapped) item of ListView to be AccentColor.
I can't find a way to override that other than changing AccentColor. Is there any method to resolve this to some other color or not change it at all?

**Comment by yingzhox** [comment]
Hi @jpbrocca I saw you have some solution in another thread, will that solve my problem? My email is yingzhong.xu@live.com

**Comment by jpbrocca** [comment]
Hi @yingzhox,
sorry for the late reply on this.

Somehow I missed this issue.
You can tweak the lists to use whatever color you need for the selected(tapped) item.
Are you still looking for the solution or did you find the solution on the other thread you mention ?

Best,
JP
