### ISSUE TITLE
Can't get iOS Splash Page to pick up my images

### ISSUE THREAD

**Issue by faceoffers28** [UXDivers/Grial-UI-Kit-Support#381]
I added splash.png, splash@2x.png and splash3x.png to the Resource folder. I then added the files to the  iOS project as a BundleResource. I did a clean and a rebuild, but I can't get my images to display.

I then tried editing the Storyboard. I'm getting this error when trying to edit Splash.storyboard. I am using Visual Studio on Windows 10 and XCode 8.2.1 on my Mac.

This file has been edited in a version of Xcode which is unsupported by the designer. Documents saved in Xcode 8.2.1 format, or older, are supported.

Contents of C:\Users\USERNAME\AppData\Local\Xamarin\Logs\14.0\iOSDesigner-11336.2018-03-07__21-13-03.log:
MDAddinsHash: 60422829d78f5ab031e36c4eabeac715e0b6ef0c

[2018-03-07 21:26:51.3] INFO: Starting full reload...

Any ideas on how to get my images to work? Thanks!

**Comment by jpbrocca** [comment]
Hi @faceoffers28,

please take a look at this related issues:

https://github.com/UXDivers/Grial-UI-Kit-Support/issues/228

https://github.com/UXDivers/Grial-UI-Kit-Support/issues/314

I did a fast search and it seems he storyboard issue seems to be related to these bugs:

https://bugzilla.xamarin.com/show_bug.cgi?id=44330
https://forums.xamarin.com/discussion/106112/storyboard-does-not-load-anymore-after-upgrading-xcode-to-version-9-1-9b55

Hope that helps,
JP

**Comment by faceoffers28** [comment]
All of a sudden, it started working. :)
