### ISSUE TITLE
Merge between Font Attribute and Font Family in same Label 

### ISSUE THREAD

**Issue by musab-alrmmah** [UXDivers/Grial-UI-Kit-Support#383]
How to  Make TextLabel is Bold and custom FontFamily  in same Label  in MessageListPage

Read/UnRead

**Comment by jpbrocca** [comment]
Hi @musab-alrmmah,

Not sure what you are asking...you can change directly the styles on the template being used by that page:

`MessageItemTemplate.xaml`

...so you can set bold attribute and font family as needed.

Best,
JP
