### ISSUE TITLE
Please provide a proper documentation.

### ISSUE THREAD

**Issue by szaid07** [UXDivers/Grial-UI-Kit-Support#387]
Proper documentation for where i can find the components which are added in the project which will be easy.
just like i want to edit the rtl button on navigation bar but i cant find that button.
and now i want to use the article list with full image but i cant find it.

**Comment by jpbrocca** [comment]
Hi @szaid07,

You can find Grial documentation here:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html

Here you can have more details about Grial's custom renderers:
http://uxdivers.github.io/Grial-UI-Kit-Support/renderers.html

About the RTL button, I already have answered your previous post about that topic here:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/364

About your last comment:

> article list with full image but i cant find it

...the easiest way of finding each page and its templates is just to use [Grial with Gorilla SDK embedded](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) to allow you previewing your opened pages in Visual Studio.

Best,
JP
