### ISSUE TITLE
how to use FillAndExpand in button

### ISSUE THREAD

**Issue by nsy738** [UXDivers/Grial-UI-Kit-Support#388]
![2018-03-19_18-35-01](https://user-images.githubusercontent.com/31877682/37590786-5556e258-2ba4-11e8-9943-139f5c525149.png)

I tried to let the button fill the whole space automatic. 
but I can't make it. any suggestion on this
have any documentation can search for those setting?

`<artina:Button
							Style="{StaticResource SquareActionButtonStyle}"
					        Text="{Binding Name}" 
                            WidthRequest="200" 
							VerticalOptions="{ artina:OnOrientationLayoutOptions
								PortraitPhone=FillAndExpand,
								LandscapePhone=FillAndExpand,
								PortraitTablet=FillAndExpand,
								LandscapeTablet=FillAndExpand }"  
							HorizontalOptions="{ artina:OnOrientationLayoutOptions
								PortraitPhone=FillAndExpand,
								LandscapePhone=FillAndExpand,
								PortraitTablet=FillAndExpand,
								LandscapeTablet=FillAndExpand }" />`

SquareActionButtonStyle i am copy from RoundActionButtonStyle

**Comment by jpbrocca** [comment]
Hi @nsy738,

I could not reproduce your issue.

Just a couple of comments:

- You don't need to set the responsive helper for each orientation case and device type if you want to achieve the same behavior. Just set the `VerticalOptions` or `HorizontalOptions` to `FillAndExpand` and that would be all.
- I tried with your code, and just replaced the `SquareActionButtonStyle` with `PrimaryActionButtonStyle` and also set the `BorderRadius="0"` just in case and set the `Text` property to a string. Even if I use the responsive helpers as in your code or if I directly use the `VerticalOptions` or `HorizontalOptions` set `FillAndExpand` I get the button as expected:

<img src="https://user-images.githubusercontent.com/15996999/37613854-db81e660-2b87-11e8-852a-0be6c14fd2ea.png" width="480" >

<img src="https://user-images.githubusercontent.com/15996999/37613950-207edb92-2b88-11e8-83a1-6590f1af61d3.png" width="480" >

Best,
JP

**Comment by nsy738** [comment]
Hi.
Problem solved. 
it is my problem.
