### ISSUE TITLE
There was a conflict between mscorlib 4.0.0.0 and 2.0.5.0

### ISSUE THREAD

**Issue by MarcusSpecht** [UXDivers/Grial-UI-Kit-Support#389]
Using `Grial Starter - Gorilla Ready` with `Grial 2.6.9.0`.

If I build Droid project with VS 2017 15.6.2 i get the following warning but build is successful.

```
There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
```

Using visual studio appcenter CI with Mono Version 5.4.1 does not build with error:

```
CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: '/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll' and '/Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/4.5/mscorlib.dll'. Remove one of the duplicate references. [/Users/vsts/agent/2.129.1/work/1/s/liberry.Droid/liberry.Droid.csproj]
```

I tried updating all nuget packages hoping this resolves the issue but for the android project I always get `collection is readonly` error. For now I gave up because nothing seemed to work updating nuget packages.

**Comment by LeoHere** [comment]
@MarcusSpecht does this warning happens in the `Grial Starter - Gorilla Ready` without modifications? Or did you updated the packages / installed new packages?

I was not able to reproduce the issue.

When are you getting this `collection is readonly` error? As soon as you hit update in any package? Is this error reported by nuget? VS?

**Comment by MarcusSpecht** [comment]
@LeoHere yes i tested this without modifications. The update nuget problem seems to be a nuget bug. But  the mscorlib problem has most probably something to do with nuget dependencies and target support I guess? My local VS just uses mscorlib 4.0.0.0 and everything works fine but appcenter seems to be more strict here and exits build with an error.

**Comment by MarcusSpecht** [comment]
I found this answer to the problem

> This happens because Xamarin.Android is using the mono version of mscorlib, and the .NET Standard Library uses the .NET version of mscorlib. I believe at the current state, this is a harmless warning which will eventually be resolved when the MonoAndroid assembly references the latest mscorlib. Right now it selects the latest version (4.0). You should be able to "unreference" your mscorlib included in your Android project as it's already added by Mono.Android.dll

here: https://developercommunity.visualstudio.com/content/problem/121536/mscorlib-version-conflict-android.html

**Comment by MarcusSpecht** [comment]
There is also a Xamarin bug report regarding the "outdated" mscorlib dependency:
https://bugzilla.xamarin.com/show_bug.cgi?id=60351

**Comment by MarcusSpecht** [comment]
Seems like this is also related to Xaml Compilation 
https://github.com/xamarin/Xamarin.Forms/issues/1958

**Comment by MarcusSpecht** [comment]
If I disable xamlc in the .netstandard 2.0 project VS does not report the error.
```
// Comment the line bewlow to disable XAMLC
//[assembly: XamlCompilation (XamlCompilationOptions.Compile)]
```
Sadly appcenter build still does exit with an error. I checked the Mono.Android.dll that is referenced in 8.1 myself and it does have mscorlib 2.0.0.0 dependency.

**Comment by MarcusSpecht** [comment]
So this should be fixed with xamarin forms 3.0.
https://github.com/xamarin/Xamarin.Forms/pull/1899

Xamarin Forms released 3.0.0 Pre Release 2 yesterday and it lists
```
"[XamlC] no longer use any reflection-base ImportReference (#1899)" (#1899)
```
I'll try it out when the nuget package arrives and report back if this solves the issue.

**Comment by MarcusSpecht** [comment]
I managed to update to xamarin.forms 3.0.0 Pre Release 2. Local build with VS now works without error and XamlCompilation enabled. Sadly appcenter build still throws the same error.  I guess there needs to be a fix within MonoAndroid and appcenter needs to update to such a future MonoAndroid or something similar.

**Comment by MarcusSpecht** [comment]
Good news. Appcenter just updated their build VMs including the latest Mono.Android 8.2 and now the android app builds perfectly. I am still using xamarin.forms 3.0.0 Pre Release 2 meaning i did not test if it would also work with latest stable Xamarin.Forms 2.5.0.280555. 

Do you test grial kit releases with appcenter build pipelines? If not you should because it is aweseome :D Should I try it with 2.5.x so you know if their is a problem?

**Comment by LeoHere** [comment]
@MarcusSpecht, excellent! Thanks for shearing. We do not use appcenter to test Grial Kit. It has been on our mental backlog for a while but we never actually do it. Looks it is time to reconsider this :)

**Comment by klaasel** [comment]
We had this problem on a Xamarin Native Droid project on the VSTS build server (Macincloud). Checking the "do not reference mscorlib.dll" in the Droid Project>General settings did the trick.
