### ISSUE TITLE
Starting a new project

### ISSUE THREAD

**Issue by izefler** [UXDivers/Grial-UI-Kit-Support#39]
I'm starting a new project, and I wonder what is the best way to do this. That is:

1) Should I create the new project and copy only the views and relaciondas viewmodels the sample project?

2) Should I create the new project and copy all the sample project files?

3) Or another?

Thank you.

**Comment by jpbrocca** [comment]
Hi,
That will depend on your needs.

The fastest and easier way is to build on top of the sample provided with your purchase.

Then, other option could be 1) from your list.

Best,
JP

**Comment by izefler** [comment]
Very good! Thank you.
