### ISSUE TITLE
Apostrophe in app name is not accepted in admin portal

### ISSUE THREAD

**Issue by samnaseri** [UXDivers/Grial-UI-Kit-Support#391]
Our app name contains apostrophe(') in it. But when I try to set my app name in app portal it does not allow it. For the time being I just removed apostrophe from the name. But when we publish it to app store we need to name it correctly. Am I doing something wrong or is this an issue within admin portal?

**Comment by LeoHere** [comment]
@samnaseri yes there is a limitation in the Grial Admin. We will fix that and let you know.

**Comment by LeoHere** [comment]
@samnaseri this should be fixed now. Please try again.

**Comment by samnaseri** [comment]
Thank you. It is fixed now!
