### ISSUE TITLE
visual studio is crashing when running the grial solution.

### ISSUE THREAD

**Issue by szaid07** [UXDivers/Grial-UI-Kit-Support#392]
Visual studio crashing with fatal error only when running grial solution.

**Comment by jpbrocca** [comment]
Hi @szaid07,

can you please provide more info?

- Which Grial flavor are you using (standard, Pro, or Pro + RTL)?
- Which Grial version number are you using?
- Are you trying to run Grial Full sample or Grial Starter solutions?
- Which is your VS version number? Are you running it on a MAC or a Windows PC?

Your visual studio just closes when you attempt to run Grial?...or just Grial suddenly crashes and your Visual Studio is still alive?

Thanks,
JP

**Comment by szaid07** [comment]
I am using : 
1-Grial Pro + RTL
2-version 2.6.0
3-Full Sample
4-Visual studio community on MAC

Visual studio is crashing when attempting to run grial.

Please help me here.
Thanks,
Zaid

**Comment by jpbrocca** [comment]
Hi @szaid07,

- Which is your VS version number? 
- If you update Grial to latest version (2.6.9.0), do you get the same result?
- can you share your Visual Studio log?

Best
JP

**Comment by dirivero** [comment]
I'm closing this issue since we didn't get more information and it's very old. Feel free to contact back if you need help.
