### ISSUE TITLE
Translucent/Transparent NavigationBar on a specific page

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#394]
Hello,

I would like to know if there is a way to implement a **translucent or transparent NavigationBar** on a specific page?

For exemple, if we based on your **Article** view, the actual display would be like this with a the default **"back" icon** and an additional **"Share" icon**:
[screenshot1](https://ibb.co/gjuicx)

I would like to get something like this, where the icons are displayed on the image:
[screenshot2](https://ibb.co/gdoyAH)

It should also be interesting to manage the display of the NavigationBar when the user scrolls on the page. A solution could be this way:
[screenshot3](https://ibb.co/nyC3cx)

**_Can we achieve this with your custom NavigationBar?
Is there another way?_**

Regards,

**Comment by jpbrocca** [comment]
Hi @Goldstrike, how have you been?

Grial doesn't provide that behavior out of the box.
You could get a similar outcome by using custom renderers but that will be a little bit hard for this particular case.

We provide the CustomNavBar for cases like this one.
 It will make things much easier and if you want you could also try to animate it similarly as in the `ArticleViewPage`.

Best,
JP

**Comment by Goldstrike** [comment]
Hi @jpbrocca 
Thanks for your feedback.
Do you have planned to update the Grial UI samples for the next version of Xamarin.Forms?

**Comment by jpbrocca** [comment]
Hi @Goldstrike,
you are welcome!

You mean if we will update Grial to be compatible with Xamarin Forms 3.0?

Best,
JP

**Comment by Goldstrike** [comment]
@jpbrocca 
Yes it's that!
And I also would like to know if there will be new "screens" that taken into account the new abilities given by Xamarin.Forms 3.0, as the Bottom TabbedPage on Android.

**Comment by jpbrocca** [comment]
Hi @Goldstrike,

Yes, we will update Grial to be compatible with Xamarin Forms 3.0.

About the new screens, that will depend on how stable are things on their release :)
Normally we don't add new screens when we do this kind of updates, but we need to see how things go, and if that makes sense I see no reason why not doing so.

Best,
JP
