### ISSUE TITLE
Use TabControl instead of MasterDetail page

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#395]
Hello,

I've seen that the latest version of your **TabControl** ("TabControlCustomSamplePage") looks fine.
However the content of each tab is directly assigned from the main page.

**_Is there a way to "split" the container (the TabControl page) and the content's pages?_**
This should permit to get a View/ViewModel per Tab, and to customize the NavigationBar for each View.

Regards,

**Comment by dirivero** [comment]
Hi,

It's not possible to include a page directly into the tabtiem content. You can use content views to have individual Xaml files for each tab content.
For a global navigation you can try with Xamarin's TabbedPage:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page

Regards,
Diego

**Comment by Goldstrike** [comment]
Hi @dirivero 
Finally I've used this approach:
- `TabbedPage`, with a CustomRenderer on Adroid to use it as `BottomNavigationView`
- `TabControl `embedded in a page of the TabbedPage when necessary, in "Top" mode
