### ISSUE TITLE
How to change the color of the Action Bar

### ISSUE THREAD

**Issue by toverux** [UXDivers/Grial-UI-Kit-Support#396]
Hello,

I want to change the color of the Android action bar, which inherits the primary color by default, which is itself the accent color.

Multiple parameters in `Resources` seem to refer to the bar color. I tried various variations without success, and found things over the Net that didn't worked too.

Here are my `Resources/layout` and `Resources/values` files. They are coming from Grial Kit Starter, with very few changes.

Thanks for your help.

**Comment by toverux** [comment]
> Please don't attach Grial code here.

Oh sh*t, I'm really sorry. It's the GitHub effect.

> Changing the look and feel of your app made with Grial is normally made through XAML directly.

Ah this is closely related to the native component, I think it's more efficient to style it using the native styling methods. I'll try in XAML though. If it's ok, why not.

> Could you paste a screenshot of your current result and some picture showing what you would like to get as the final result?

Expected (mockup):

<img width="270" alt="mockup" src="https://user-images.githubusercontent.com/1343250/37890946-bdfbaa04-30d2-11e8-97f1-141c2562d202.png">

Current :

<img width="199" alt="android" src="https://user-images.githubusercontent.com/1343250/37890951-c25d8cde-30d2-11e8-84e2-cf5a14fa5cb3.png">

I want to keep the red color as the primary/accent color, but just change the color of the action bar.

NB: The application will also run under iOS. That's a good point for doing this in XAML. But still, I don't feel comfortable with that.

**Comment by toverux** [comment]
Tried the XAML approach. I didn't even see before that an implicit NavigationPage style was applied by Grial...

I can effectively control the color from there:

<img width="208" alt="xaml" src="https://user-images.githubusercontent.com/1343250/37891724-9c0eb334-30d5-11e8-9edc-b399a041b3d3.png">

But the Android back button is still white. Do you know how I can make it take the text color or better, make it red like in the mockups? I'd like to keep Android's animation and styling.

**Comment by jpbrocca** [comment]
Hi @toverux, how are you?

Grial is based on Xamarin Forms, so the main purpose is to allow you easily change styling through XAML. Normally, with what we provide you should have like 95% covered, but, there are exceptions where you need to go directly to the platform. 
The `NavigationPage` implicit style is the way to go.

Unless I am missing something here, all you will need is to provide the icons for the `ToolBarItems` with the right color in order to get the desired outcome.

Best,
JP

**Comment by toverux** [comment]
Thanks for your answer.

> Unless I am missing something here, all you will need is to provide the icons for the ToolBarItems with the right color in order to get the desired outcome.

Unfortunately, no. The thing is, I don't always have an icon and for now I'm only using `ToolbarItem.Text`. Just one will be replaced with an actual icon (the search toolbar item, the one you see in the mockup, maybe that's why you didn't understood me) but all the other ones will stay text-only.

Same with the back button. It is provided by Android here. It has an animation and gets the platform look and feel. I'd loose that with a static icon. And I'd prefer to keep the wrong color more than loosing cool platform features and consume unplanned time.

**Comment by jpbrocca** [comment]
To change the color of the Drawer arrow, you need to follow the following steps:

Open the Style file on your Android project:

~~~
Droid/Resources/values-v21/Style.xml
~~~

Find the `AppTheme.DrawerArrowStyle` style and change color so it points to an specific color resource:

~~~
<style name="AppTheme.DrawerArrowStyle" parent="Widget.AppCompat.DrawerArrowToggle">
	...
	<item name="color">@color/DrawerArrowColor</item>
</style>
~~~

Add the color to your `Colors.xml` file also on Android project (in this case, I used a yellow color):
~~~
<color name="DrawerArrowColor">#FFFFFF00</color>
~~~

<img src="https://user-images.githubusercontent.com/15996999/37935228-1acbf000-3127-11e8-8990-b9703554f090.png" width="320"/>

NOTE: If you add this color on your Grial theme .xaml file (`GrialLightTheme.xaml` or `MyAppTheme.xaml` depending on what are you using), the color will be automatically updated on your `Colors.xml`.

Best,
JP

**Comment by toverux** [comment]
Thanks a lot.

For the posterity, I've also been able to change the action bar items with this:

```xml
<item name="actionMenuTextColor">@drawable/StatesAccentColor</item>
```

`StatesAccentColor.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
  <!-- order is important -->
  <item android:state_enabled="false" android:color="#BABABA"/>
  <item android:state_pressed="true" android:color="#CC847F"/>
  <item android:color="@color/AccentColor"/>
</selector>
```

I've lost the ripple effect on them though. I lack time to polish it but if I find a way to get it back I'll edit the post later.

<img width="403" alt="actionbar" src="https://user-images.githubusercontent.com/1343250/37961106-ae826d02-31b7-11e8-92fe-de1d93b347e5.png">
