### ISSUE TITLE
How to change the background image and color of master detail page

### ISSUE THREAD

**Issue by szaid07** [UXDivers/Grial-UI-Kit-Support#397]
there is no view named with master detail page in the project 
how to change the background image of it.
and the top logo also.

**Comment by jpbrocca** [comment]
Hi @szaid07,

There is a `RootPage.xaml` on Grial Full project which is a `MasterDetail` page.
I suggest to take a look a at Xamarin Forms docs about it:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page

It is not a stylable page itself, but more a page that manages two pages (which can be individually styled).

If you want to style the background image of the menu (`Master`) you need to work on `MainMenuPage.xaml`. This page uses the `BrandBlock` which is a common view you can find in Grial. If you make changes there those will be propagated to other pages too.
More info here:
http://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-brand-image

Best,
JP
