### ISSUE TITLE
Determine version of GrialKit in use???

### ISSUE THREAD

**Issue by faceoffers28** [UXDivers/Grial-UI-Kit-Support#398]
I looked in the cs.proj files and I can not find any version information. I also looked in the online documentation and I don't see any information on this. Thanks!

**Comment by LeoHere** [comment]
@faceoffers28 look for a attribute `UXDivers.Artina.Shared.GrialVersion` in the `AssemblyInfo.cs` file of the PCL/NET Standard project.

**Comment by faceoffers28** [comment]
Found it. Thanks!
