### ISSUE TITLE
artina:OnOrientation Issue

### ISSUE THREAD

**Issue by khadeeja-alif** [UXDivers/Grial-UI-Kit-Support#399]
I tried using artina:OnOrientation property for a ContentView in a page. When i am redirecting to other pages and coming back to the Page, The text in the contentview seems to be either missing or text orientation changes to vertical. 
![image uploaded from ios 2](https://user-images.githubusercontent.com/14857549/37948821-8bf00ffe-31af-11e8-81ee-9a4c1c1738e1.jpg)
![image uploaded from ios 3](https://user-images.githubusercontent.com/14857549/37948828-8f8c2ecc-31af-11e8-953e-def2b70514dc.jpg)

![image uploaded from ios 4](https://user-images.githubusercontent.com/14857549/37962450-c41c61ce-31d8-11e8-830d-0f25a2adb003.jpg)
Or At times it becomes like this. Every label gets cut out.

This is my code
<img width="1054" alt="screen shot 2018-03-27 at 4 07 52 pm" src="https://user-images.githubusercontent.com/14857549/37962547-142d96ba-31d9-11e8-922b-98ca53271c2a.png">
This is my code inside contentview for the top label
<img width="960" alt="screen shot 2018-03-27 at 4 22 48 pm" src="https://user-images.githubusercontent.com/14857549/37963205-34069836-31db-11e8-8b06-506eb1bbe869.png">

**Comment by dirivero** [comment]
I'm closing this issue as it's very old and we didn't get further information. Feel free to reopen if you need help.
