### ISSUE TITLE
Make Grial fully compatible with Xamarin Forms 2.0

### ISSUE THREAD

**Issue by Laumania** [UXDivers/Grial-UI-Kit-Support#4]
This especially include performance improvements on lists (reuse of cells).

**Comment by homerokzam** [comment]
It has a time estimate to support Xamarin Forms 2.0?

Thanks,
Homero

**Comment by Laumania** [comment]
I'm listening here too :)

**Comment by jpbrocca** [comment]
@homerokzam @Laumania we started working on it this week :)
I would say about 2 weeks. We already made Grial work on XF 2.0 but we also want to improve some other related things.

**Comment by Laumania** [comment]
Awesome!
Please look into the new ListView property and how to support it, so we can get better performance in lists :)

```CSharp
public enum ListViewCachingStrategy
{
    RetainElement = 0,
    RecycleElement,
}
```

https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.0/2.0.0/

**Comment by jpbrocca** [comment]
By the way @homerokzam I added you as a collaborator to this project so can have full access :)

**Comment by Laumania** [comment]
@jpbrocca Will there be an "Upgrade guide" for us who is already using the 1.5 XF version of Grial?
Just a bullet list of things to change would be nice I guess.

**Comment by jpbrocca** [comment]
Yes @Laumania, our friend @pablogermano will be adding info about it. It's pretty simple, just replace a few deprecated attributes.

That will be more than enough to make Grial work on XF2.

Our next release will be a little bit more ambitious though ;)

**Comment by homerokzam** [comment]
Great news. Thanks Pablo for the information and opportunity to collaborate.

**Comment by jpbrocca** [comment]
Thank you Homero! :)

**Comment by Laumania** [comment]
@homerokzam Remember also to join the Gitter chat, you'll find the link on the Readme on the fromt page of this repo :)

**Comment by pablogermano** [comment]
@homerokzam @Laumania hey guys, 
in order to make Grial work on XF2. 

You will have to find and replace: 

**XAlign** for **HorizontalTextAlignment** 

and 

**YAlign** for **VerticalTextAlignment**.
 
And that will be all :)

**Comment by Laumania** [comment]
That's awesome. I'll update tonight then :)

Den 9. dec. 2015 kl. 17.03 skrev Pablo Germano <notifications@github.com>:

@homerokzam <https://github.com/homerokzam> @Laumania
<https://github.com/Laumania> hey guys,
in order to make Grial work on XF2.

You will have to find and replace:

*XAlign* for *HorizontalTextAlignment*

and

*YAlign* for *VerticalTextAlignment*.

And that will be all :)

—
Reply to this email directly or view it on GitHub
<https://github.com/UXDivers/Grial-UI-Kit-Bugs-1.1.0/issues/4#issuecomment-163305410>
.

**Comment by jpbrocca** [comment]
We will also need to add Compiled XAML on Grial:
https://blog.xamarin.com/optimizing-xamarin-forms-apps-for-maximum-performance/

**Comment by Laumania** [comment]
Yes I did that in my project and for some reason images defined in App.xaml
don't work then. So I marked XAML as compiled on assembly level, and then
added a "skip" attribute to the App class.

Then it works and I get compile error on xaml now it seems so I guess it
works.

I don't feel any performance gain though...

Den 12. dec. 2015 kl. 10.45 skrev jpbrocca <notifications@github.com>:

We will also need to add Compiled XAML on Grial:
https://blog.xamarin.com/optimizing-xamarin-forms-apps-for-maximum-performance/

—
Reply to this email directly or view it on GitHub
<https://github.com/UXDivers/Grial-UI-Kit-Bugs-1.1.0/issues/4#issuecomment-164134628>
.

**Comment by jpbrocca** [comment]
Yes, I think it makes sense to add it on assembly level.

I didn't understand if it finally worked or not...you said you get compile error but it worked ?
Maybe that's related to the performance comment -perhaps it is not working?-.

Anyways, the idea is to get the most of xamarin forms 2.0 on next version of Grial.
Xamarin team said this XAMLC should have a positive impact on performance, so I hope we can benefit from it.

**Comment by Laumania** [comment]
Sorry for being unclear :)

I made it work, by "skipping" the App class, but else have the XAML.Compile set on the rest of the assembly.

WHEN I make a XAML syntax error, I get a compile error - not all the time :)

So it is working, I just don't feel any difference....but I have it kind of the same with this new ListView CacheMode or what it is called, can't remember right now. I have tried enable/disable it and don't feel any difference - but that's another topic :)

**Comment by jpbrocca** [comment]
No worries ;)

Well, interesting feedback about this XF2.0 improvements :)
We'll see if it can really work as expected and it really makes a difference on performance.

**Comment by Laumania** [comment]
Yeah I'm looking forward to see/try your sample app after XF 2.0, because it might be me who is missing something :)
