### ISSUE TITLE
Intercept the Navigation Back button

### ISSUE THREAD

**Issue by josesimas** [UXDivers/Grial-UI-Kit-Support#400]
Hi,

I need to validate a page before letting the user leave it by pressing Back. The problem is that if the user presses the Nav Bar arrow at the top I am not notified of this action. I tried the solution from this site:

https://theconfuzedsourcecode.wordpress.com/2017/03/12/lets-override-navigation-bar-back-button-click-in-xamarin-forms/

And it works fine on a simple project but it does not work in my main project that uses the Grial UI Kit. I am wondering if you are doing anything special with the  Android toolbar or if you have any suggestion on how to solve the problem.

Thanks

**Comment by josesimas** [comment]
Hi,

I wonder if the answer to this issue would be using your CustomTab example? Unfortunately I am using a TabbedPage and I cannot figure out how to make it work. Can anyone help?

**Comment by jpbrocca** [comment]
Hi @josesimas,

We are reviewing this issue. So far we didn't find anything that could be causing this in Grial.

From your last comment it seems you are using our TabControl...is that correct?
You think this could be the issue?
Please provide as much info as possible so we could work faster.

Regards and thanks,
JP

**Comment by dirivero** [comment]
HI @josesimas,
Can you send us the sample project where you have that working?

**Comment by jpbrocca** [comment]
@josesimas,

could you send your project to:
![image](https://user-images.githubusercontent.com/15996999/37982168-2ced6d6e-31c6-11e8-9d3c-c3a84ea0f060.png)

Thanks! 
JP

**Comment by josesimas** [comment]
Hello both,

I am afraid I don't have enough free time to do a full repro at the moment. I implemented the back interception as described in the link above, both in a basic Xamarin Forms project (no Grial Kit) and on the project I am working on which is using the Grial Kit. It only works in the basic project, in our main project the OnOptionsItemSelected override in the main activity is never called both in a TabbedPage and on a ContentPage (I am sorry but I cannot send the project).

Due to the timescales we are considering using your CustomNavBar plus your TabControl to work around the issue (with some redesign involved). If that does not pan out I will try to get time to create a full repro.

Thanks!

**Comment by dirivero** [comment]
Do you have the basic project where the back is being intercepted according to the article? If you have it please send it to us so we can review what may be the difference.
Thanks

**Comment by dirivero** [comment]
I'm closing this one as it's been inactive for more than a year and we didn't get more information. Feel free to contact us if you need help.
