### ISSUE TITLE
TabControl's TabItem loaded event

### ISSUE THREAD

**Issue by josesimas** [UXDivers/Grial-UI-Kit-Support#401]
Hello,

I have a TabControl with a number of TabItems and one of them hosts a Mapsui control. The mapping control can only navigate after it knows its size. The TabSelected event and the SelectedIndex property are both raised before the tab item is drawn (at least that is what it looks like). I wonder if there is a way to be notified after the TabItem has been loaded and drawn?

Thanks,
Jose

**Comment by dirivero** [comment]
Hi,

You can try subscribing to the PropertyChanged of the TabItem content (the single child of the TabItem). For instance, Render, Width, Height, Opacity properties should be called and you can hook to them.

Hope it helps.
Regards,
Diego

**Comment by josesimas** [comment]
Hi Diego,

Thanks. I like the TabControl in that it lazy loads the tabs. I will have a go at your suggestions. Please consider adding some kind of TabLoaded event (or eager loading per tab) in the future.

Thanks,
Jose
