### ISSUE TITLE
Error: java.lang.IllegalArgumentException: already added 

### ISSUE THREAD

**Issue by velikocakk** [UXDivers/Grial-UI-Kit-Support#403]
When I try to deploy my application on Android Simulator I am getting this error message. Same Application is working on iPhone simulator but It is not running on iPhone.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Lcom/airbnb/lottie/BuildConfig; (StonebaseApp.Droid)

**Comment by ianvink** [comment]
Clean the solution, then rebuild and deploy. Works for me
