### ISSUE TITLE
Entry IOS custom renderer BorderStyle BottomLine not working

### ISSUE THREAD

**Issue by giammin** [UXDivers/Grial-UI-Kit-Support#41]
With latest Xamarin.Forms (2.2.0.31)

`<Setter Property="artina:EntryProperties.BorderStyle" Value="BottomLine"/>`

in IOS doesn't display any border

**Comment by LeoHere** [comment]
Hi, I can't reproduce the issue. Can you attach/send small solution where we can reproduce it? 

Is artina:EntryProperties.BorderColor set to a color other than Colors.Default?

**Comment by giammin** [comment]
there you can download the project: https://drive.google.com/file/d/0B9v-_MrAfNMIa28xdk53Z1A2SzA/view?usp=sharing

**Comment by giammin** [comment]
any news on this? can you confirm the bug?

**Comment by giammin** [comment]
Is there anybody in there?

**Comment by LeoHere** [comment]
Hi @giammin, 
Sorry for the delay. Yes, you are right, you hit a bug. Please write us to hello@grialkit.com with your purchase order number and we will provide you a fix for this.

**Comment by jpbrocca** [comment]
Hi @giammin I already had your info so I sent you an email with this fix.

If everything is OK after applying the fix please close this issue.

Thanks!
JP

**Comment by giammin** [comment]
I'll check it on Monday morning asap

**Comment by giammin** [comment]
It works great! thanks!

**Comment by jpbrocca** [comment]
Awesome! Thanks @giammin !
For other folks running on the same issue please send an email to hello@uxdivers.com

Cheers,
JP
