### ISSUE TITLE
Licence BundleIdentifier error

### ISSUE THREAD

**Issue by augustohug** [UXDivers/Grial-UI-Kit-Support#410]
I need to make the Exchange Builder Identifier of my application, and when I change (since I changed my account in the Apple Store), the above error occurs. How can I change the same in my licensing? That licensing issue does not seem very correct, since such things can happen.

**Comment by LeoHere** [comment]
@augustohug if you need to change the license you can do it through the [Grial Admin](https://uxdivers.com/secure/grial/front). Do the changes you need and download the license again.
