### ISSUE TITLE
HTTP client refuse connection on Grial Kit

### ISSUE THREAD

**Issue by mmakdessii** [UXDivers/Grial-UI-Kit-Support#412]
I'm running the following code on Grial template but it's not working. On the other hand, it's working on an empty project. These are all the relevant data with the API running.

//DATA SERVICE
    public class DataService
    {

        private string Url = "http://mystroapi.azurewebsites.net/api/Company/validatecompany";

        public async Task<CompanyModel> ValidateCompany(CompanyModel model)
        {
            try
            {
            var httpClient = new HttpClient();
            var json = JsonConvert.SerializeObject(model);

            StringContent content = new StringContent(json);
            content.Headers.ContentType = new MediaTypeHeaderValue("applicantion/json");

            var response = await httpClient.PostAsync(Url, content);
            var result = await response.Content.ReadAsStringAsync();
            var company = JsonConvert.DeserializeObject<CompanyModel>(result);

            return company;
            }  catch (Exception){
                return new CompanyModel();
            }
        }
}

//MODEL
    public class CompanyModel
    {
        public int CompanyId { get; set; }
        public string CompanyIdentification { get; set; }
        public string CompanyName { get; set; }
        public string CompanyApi { get; set; }
        public bool? IsActive { get; set; }
	}
}

//CALLING METHOD
        public  Page GetMainPage()
        {            
            if(!string.IsNullOrWhiteSpace(CompanyIdentification))
            {
                CompanyModel companyModel = new CompanyModel();
                companyModel.CompanyIdentification = CompanyIdentification;

                var company = dt.ValidateCompany(companyModel);
                if(company.Id!=0)
                {
                    CompanyApi = company.Result.CompanyApi;
                    Settings.CompanyApi = CompanyApi;

                    if (!IsLogin)
                        return new NavigationPage(new EmployeeLoginPage());
                    else
                        return new RootPage();
                }

            }

           return new NavigationPage(new CompanyLoginPage());
        }

**Comment by LeoHere** [comment]
@mmakdessii not sure how this is related with Grial. Also not sure what you mean by it does not work. Please clarify.

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for a year.
Thanks
