### ISSUE TITLE
App Name and Grial License

### ISSUE THREAD

**Issue by ImmenseIT** [UXDivers/Grial-UI-Kit-Support#415]
A lot of app developers optimize their app names by using a combination of branded and common search terms to enhance discoverability. For example: If you create a photo editing app, it might be a good idea to use the words “photo editor” in the app name along with a branded name. Here are examples of a few apps that do this:

![image](https://user-images.githubusercontent.com/30938367/39015958-cacbd8ee-43ec-11e8-9fc4-9db8fe7d970c.png)

Here is another example: https://itunes.apple.com/us/app/muslim-pro-azan-quran-qibla/id388389451?mt=8

If we do this with App developed using Grial Kit, will the licensing cause any issues ?
If so we can not use this technique to improve SEO. please advise.

**Comment by LeoHere** [comment]
@ImmenseIT as you know once you move to production, we don't allow to change the app name any more. However, if for some reason you need to do some changes and you are in production mode, you can write us an email saying what change(s) you need to do and the reasons for it and we can help you.
