### ISSUE TITLE
GrialUI Fonts and styles does not show up on Gorilla Player. 

### ISSUE THREAD

**Issue by uurcm16** [UXDivers/Grial-UI-Kit-Support#419]
Hi there. 
I bought GrialUI Kit a few days ago and I've downloaded the Gorilla Ready samples. 
On Gorilla Player, selected pages are shown but styles and icons are **not**. Even in Gorilla Configuration or Debug Configuration.

**LoginPage.xaml, SimpleLoginPage.xaml and CustomSettingsPage.xaml** screenshots added.

Is there anything that I miss?

**I'm using Visual Studio 2017 running on Windows 10 machine and the project is under Gorilla Configuration by the way**

![img_0558](https://user-images.githubusercontent.com/38659860/39129099-3c294d6e-4712-11e8-9c97-9f1853548fd6.PNG)
![img_0559](https://user-images.githubusercontent.com/38659860/39129100-3c4a9654-4712-11e8-8639-59da5d092b74.PNG)
![img_0560](https://user-images.githubusercontent.com/38659860/39129101-3c67a956-4712-11e8-88e2-6d643dadf3a4.PNG)

**Comment by jpbrocca** [comment]
Hi @uurcm16,

Can you please answer the following questions?

- are you using Gorilla SDK embedded in Grial, right?
- which is your gorilla player version?
- which is your xamarin forms version?
- which device are you testing with and which OS version it has?

Thanks
JP

**Comment by uurcm16** [comment]
Hi again.

1- Yes, I've downloaded Gorilla Ready solution. (I've tried Full and Starter solutions and the result is the same)
2- Gorilla Versions: Application: 1.2.0.6, Server: 1.2.0.6
3- If you are asking the Xamarin.Forms reference dll version, it is v2.5.0.280555
6- I'm testing on iPhone 6s 16Gb, Turkish Language, iOS 11.3

Best regards.

**Comment by jpbrocca** [comment]
Hi @uurcm16, thanks for the info.

That is weird. Specially if you get same results when you debug.

A couple more questions:

- is this a real device or an emulator?..can you try with another device and check if you get same results?
- can you try downloading from Grial Admin again? and also please check with the starter solution and let me know.

Regards and thanks
JP

**Comment by uurcm16** [comment]
@jpbrocca , 

1- It is a real device. I'll try with an Android device and let you know about the result.
2- I've downloaded 5 or 6 times each project (Starter and Full, Gorilla ready versions).

NuGet Package manager says that there are updates for some dlls. Should I update'em and try again?

**Comment by jpbrocca** [comment]
@uurcm16 if those updates are grial related (artina*) then yes.

**Comment by uurcm16** [comment]
@jpbrocca  nope, all the updates are related with Xamarin and Json. :( I'm sick of trying to make it work. I'll let you know when the Android test is done.

**Comment by uurcm16** [comment]
@jpbrocca I've done the test with Android. Gorilla Player keeps crashing https://vimeo.com/266536047

**Comment by LeoHere** [comment]
@uurcm16 you can't preview Grial with the standard Gorilla Player downloaded from the App Store or the Player solution installed along with Gorilla. 

To preview Grial you need to deploy Gorilla using the solution configuration named **Gorilla**. Please take a look a [this](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player) section of the documentation where this is explained.

**Comment by uurcm16** [comment]
@LeoHere Hi there.  
I think it is working now. I've deployed under Gorilla config and it is working now.
