### ISSUE TITLE
Error Test in Device iPhone 9.2 iOS

### ISSUE THREAD

**Issue by izefler** [UXDivers/Grial-UI-Kit-Support#42]
Hello, follows the provisioning procedure for testing on iOS devices, but to compile (build), the following error occurs:

Error MT2002: Failed to resolve "System.Object Xamarin.Forms.ElementTemplate::CreateContent()" reference from "Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002) (Grial.iOS)

Can you help me?

**Comment by jpbrocca** [comment]
Hi @izefler, how are you?

Can you provide more context about this issue?

Are you working on a new project where you tried to add Grial?
Can you compile the sample provided with Grial?
Does it works on Android ?

Thanks,
JP

**Comment by izefler** [comment]
All great JP! And you all right?

I'm using the sample project, I chose not to create a new project and incorporate the theme files.

I'm using iOS, the problem occurs when I try to compile the application using a device iPhone 5 version of OS 9.2.

With android I have other problems, but will open a new issue.

Thank you,
Izefler

**Comment by izefler** [comment]
Problem was solved by updating the xamarin.forms to the most current version - 2.2.0.31.

Thank you.
