### ISSUE TITLE
DashboardWithImages badge number disappeared after nuget update

### ISSUE THREAD

**Issue by mgcmartin2** [UXDivers/Grial-UI-Kit-Support#422]
I am using DashBoardWithImages and i updated xamarin to version: 2.5.1.444934 from 2.4.0.282 and i have updated grial/uxdivers packages too but that dosent change anything. But when i see my DashBoard it only shows the green color and border from my badges and the number inside the badge is gone.

**Comment by LeoHere** [comment]
@mgcmartin2 If you are still experiencing this issue please consider downloading the latest version of Grial, get from it the `Badge.xaml`/ `Badge.xaml.cs` and replace those in your solution.
