### ISSUE TITLE
Type 'UXDivers.Artina.Shared.LicenseException' in Assembly 'UXDivers.Artina.Shared.Base, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

### ISSUE THREAD

**Issue by KirkPatrickJunsay** [UXDivers/Grial-UI-Kit-Support#424]
Hi I would like to ask support on the above encountered Crash report by App Center. The app is already deployed in the production environment. It's weird that other devices doesn't encounter this kind of crashes while some encounter.

Here are some additional info based on app center:

System.Runtime.Serialization.Formatters.Binary
WriteObjectInfo.InitSerialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder)
1
System.Runtime.Serialization.Formatters.Binary
WriteObjectInfo.Serialize (System.Object obj, System.Runtime.Serialization.ISurrogateSelector surrogateSelector, System.Runtime.Serialization.StreamingContext context, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit serObjectInfoInit, System.Runtime.Serialization.IFormatterConverter converter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter objectWriter, System.Runtime.Serialization.SerializationBinder binder)
2
System.Runtime.Serialization.Formatters.Binary
ObjectWriter.Serialize (System.Object graph, System.Runtime.Remoting.Messaging.Header[] inHeaders, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter serWriter, System.Boolean fCheck)
3
System.Runtime.Serialization.Formatters.Binary
BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers, System.Boolean fCheck)
4
System.Runtime.Serialization.Formatters.Binary
BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers)
5
System.Runtime.Serialization.Formatters.Binary
BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph)

thanks

**Comment by LeoHere** [comment]
@KirkPatrickJunsay the only reason I can think of for this to happen is that you have some devices running different versions of your app. One that has linking issues meanwhile other not. Did you fixed the issue?

**Comment by dirivero** [comment]
I'm closing this as we didn't get more information and it's very old. Feel free to reopen or create a new issue if you need help.
