### ISSUE TITLE
The Label breaking with character - in Redmi Note 4 device

### ISSUE THREAD

**Issue by judsonabraham301** [UXDivers/Grial-UI-Kit-Support#426]
I'm trying to display a label in my Redmi not Device.I'm doing it in xamarin forms. But the word is breaking with - at the end. I want the whole word to be displayed in next line instead of breaking the word. For example

> Welcome to Lighthouse, the PSAV online customer followup prog-
> 
> ram designed to ensure a one-on-one approach to individual guest contact and interaction. Lo-
> 
> gin using your PSAV credentials to begin entering your guests' Touch Points now.

It should be:

> Welcome to Lighthouse, the PSAV online customer followup
> 
> program designed to ensure a one-on-one approach to individual guest contact and interaction.
> 
> Login using your PSAV credentials to begin entering your guests' Touch Points now.

But this is not shown in any other device rather than Redmi Note 4. I have tried all LineBreakMode properties but nothing helps. This is my code

` <Label  Grid.Row="0" Grid.Column="0" Style="{StaticResource LabelStyle}" Margin="10" x:Name="lblLogin" TextColor="Black" Text="{Binding lblLoginText , Mode=TwoWay}" > </Label>`

I know i can use `&#x0a;` with the word which breaks and it will take that word to next line. But that is like hard coding a break line.I want it to be done dynamically.

Please help me with this.Ur help will be appreciated.If this is not possible in Xamarin Forms please provide me a proof for that please.

**Comment by LeoHere** [comment]
@judsonabraham301 this question does not seems to be related to Grial UI kit. I would recommend that you post it in the Xamarin Forms forum directly. Closing the issue. If I misunderstood, please clarify and feel free to open it again.
