### ISSUE TITLE
Compatibility with Plugin.FirebasePushNotification

### ISSUE THREAD

**Issue by nmadrane** [UXDivers/Grial-UI-Kit-Support#430]
Hi,
When I try to install Plugin.FirebasePushNotification via Nuget Package on my project, I get a build error: this plugin needs Xamarin.Android.Support.v4 (>= 26.0.2). But it seems it is not compatible with grial because grial is using Xamarin.Android.Support.v4 25.4.0.2.

**Comment by szaid07** [comment]
Hi, 
Just change your Android settings and install Oreo 8.1 it will work.
