### ISSUE TITLE
Using Custom Style causing error: *An unhandled exception occured.*

### ISSUE THREAD

**Issue by smhasan11** [UXDivers/Grial-UI-Kit-Support#432]
I'm trying to implement Grial-UI into my existing project. But getting error.
I didn't made any change in `App.xml` for custom style (kept exactly as it is). `App.xml` declaration looks as follows:
```
<?xml version="1.0" encoding="utf-8" ?>
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="NswHealth.App"
             xmlns:local="using:NswHealth"
             xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
             xmlns:converter="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared.Base"
             xmlns:resx="clr-namespace:NswHealth.Resx;assembly=NswHealth"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations">
```
 
I've used that style in below:
```
<?xml version="1.0" encoding="utf-8" ?>
<local:DashboardItemTemplateBase xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
    xmlns:converter="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared.Base"
    xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
    xmlns:fftransformations="clr-namespace:FFImageLoading.Transformations;assembly=FFImageLoading.Transformations"
    xmlns:local="clr-namespace:NswHealth"
  x:Class="NswHealth.DashboardItemTemplate"
  x:Name="Root">

            <StackLayout
              VerticalOptions="Center"
              HorizontalOptions="Center"
              Orientation="Vertical"
              Spacing="10">

                <Grid>

                    <Label
                      Style="{StaticResource DashboardItemTemplateShape}"
                      Text="BISMILLAH" />

                </Grid>
            </StackLayout> 
```
If I remove that `Style={StaticResource DashboardItemTemplateShape}` from the `Label`, it works fine; but using that style throws an exception:

>  An unhandled exception occured.

Any clue what's going wrong?

**Comment by jpbrocca** [comment]
Hi @smhasan11,
Most probably you are missing some of the dependencies for that style: 
`DashboardItemTemplateShape` uses `grialshapes.ttf` font to draw the icons.
~~~
...
<Setter Property="Text" Value="{ x:Static local:GrialShapesFont.Circle }" />
...
~~~
Each icon in Grial can be referenced by using `GrialShapesFont.cs` helper, so you need to make also sure you had included the font file but also that helper in your project.

I suggest you follow the steps here:
http://uxdivers.github.io/Grial-UI-Kit-Support/setup-grial-on-an-existing-project.html

Best,
JP

**Comment by smhasan11** [comment]
Hi @jpbrocca, 
Thanks a lot for your reply. Those required folders (Helpers, Rex, Themes) were in place. But I was missing some steps in mentioned in that doc you've suggested. The error message which I was getting is quite vague. It could've more explicit message. 
However, you've pointed me in right direction; may Almighty Allah rewards you and show you the right path too.
