### ISSUE TITLE
Error Reading License 

### ISSUE THREAD

**Issue by SanjeevKarki** [UXDivers/Grial-UI-Kit-Support#433]
![img_12052018_202539_0](https://user-images.githubusercontent.com/19145050/39958604-dab934d4-5622-11e8-9c90-7dd58d2dec99.png)

Renewed and Downloaded a new license but there is an Error in Deployment of android app. Says Error Reading License.

**Comment by LeoHere** [comment]
Please refer to the [license troubleshooting](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-troubleshooting-license-issues) section in the documentation which explains how to fix this issue.
