### ISSUE TITLE
How to combine Tab Control Android and Tab Control IOS in one content page?

### ISSUE THREAD

**Issue by imzuhdi** [UXDivers/Grial-UI-Kit-Support#438]
How to combine Tab Control Android and Tab Control IOS in one content page using TabControlAndroidResources and TabControlIOSResources ?

**Comment by LeoHere** [comment]
@imzuhdi you might use the `OnPlatform` with `StaticResource` to set the style depending on the platform. I did't test it but it should work.

Alternatively you can have the iOS and Android styles in separate `ResourceDictionaries` and include one or the other at runtime depending on the platform you are.

Hope it helps.
