### ISSUE TITLE
Grailkit with Xamarin.Android.Support.v7.AppCompat version 23.3.0

### ISSUE THREAD

**Issue by bprochniak** [UXDivers/Grial-UI-Kit-Support#44]
Hi,

I have an existing project with utilizes Xamarin.Android.Support.v7.AppCompat version 23.3.0. When I add reference to your library (UXDivers.Artina.Shared.dll and UXDivers.Artina.Shared.Droid.dll) from Android project I get plenty of errors eg:

'Resource.Styleable' does not contain a definition for 'Theme_windowNoTitle'
 'Resource.Styleable' does not contain a definition for 'Theme_windowMinWidthMinor'

When I start a new project with Xamarin.Android.Support.v7.AppCompat version 23.0.1.3 it is working fine. I don't want to downgrade others packages in my existing project. Is there any way to make grailkit work with version 23.3.0?

Thanks

**Comment by EdHubbell** [comment]
+1 - Same problem here. Had to roll back to Xamarin.Forms 2.1.0, which moves AppCompat version back to 23.0.1.3.

**Comment by jpbrocca** [comment]
Hello guys,
could you guys please send me an email with your purchase order number so I can send you the link to this update ?

thanks!
JP

**Comment by EdHubbell** [comment]
Thanks for the update, JP. I did a beyond compare on my project vs the new sample so I could get a guess at what files to update. I updated the files and then re-updated my Xamarin.Forms to 2.2.0.31 and AppCompat to 23.3.0.

Just for the record, here are (approx) the files that I imported from the newer project version that you shared.

Modified:
  modified:   Droid/Assets/fontawesome-webfont.ttf
  modified:   Droid/Properties/AssemblyInfo.cs
  modified:   Droid/Resources/Resource.designer.cs
  modified:   Droid/Resources/values/Colors.tt
  modified:   AppName/App.xaml
  modified:   AppName/App.xaml.cs
  modified:   SupportFiles/UXDivers.Artina.Shared.Droid.dll
  modified:   SupportFiles/UXDivers.Artina.Shared.dll
  modified:   SupportFiles/UXDivers.Artina.Shared.iOS.dll
  deleted:    iOS/Resources/Tab-bar-icon.png
  deleted:    iOS/Resources/toolbar-icon.png

Added:
  iOS/Resources/tabs0_icon.png
  iOS/Resources/tabs0_icon@2x.png
  iOS/Resources/tabs0_icon@3x.png

I'm up and running with the latest version, so I'm good to go. Thanks for the help.
~Ed

**Comment by jpbrocca** [comment]
Hi @EdHubbell,
glad to hear that :)

Let me know if you need anything else.

Best,
JP

**Comment by bprochniak** [comment]
Thanks JP,
Where can I find my purchase order number?
Is this my purchase order number: C991613000800792
Because this is what I have found on my bank account listing. 
It also says XAMARIN COMPONENTS SAN FRANCISC  00000001 000445134165999 

I placed this order on 09-May-2016.
Regards
Blazej
Date: Mon, 16 May 2016 10:42:06 -0700

**Comment by jpbrocca** [comment]
Hi @bprochniak,
You should have received an email with the requested update.

Best regards,
JP

**Comment by bprochniak** [comment]
Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin Account?
The point is that in the past Xamarin was not free and the trail period of Xamarin last for a month, so every month I have registered with another email. But it was a fake email - Xamarin do not require to confirm the email address. I bought your prodact with an email zxc@wp.pl but I have no access to it. Can you send me the update on blazej.prochniak@hotmail.com, please?
Regards
Blazej

Date: Wed, 18 May 2016 07:33:05 -0700

**Comment by bprochniak** [comment]
Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin Account?
The point is a have no access to the email.
Regards
Blazej

Date: Wed, 18 May 2016 07:33:05 -0700

**Comment by bprochniak** [comment]
Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin Account?
The point is that in the past Xamarin was not free and the trail period of Xamarin last for a month, so every month I have registered with another email. But it was a fake email - Xamarin do not require to confirm the email address. I bought your prodact with an email zxc@wp.pl but I have no access to it. Can you send me the update on blazej.prochniak@hotmail.com, please?
Regards
Blazej

Date: Mon, 16 May 2016 10:42:06 -0700

**Comment by bprochniak** [comment]
Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin Account?
The point is I have no access to the email.
Regards
Blazej

Date: Wed, 18 May 2016 07:33:05 -0700

**Comment by bprochniak** [comment]
Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin Account?
The point is I have no acces to the email.
Regards
Blazej

**Comment by jpbrocca** [comment]
Hi,

Yes I sent it to the email account used when you purchased Grial.
I am going to send it again to this email.

Best,
JP


On jue, may 19, 2016 at 2:53 a. m., bprochniak <notifications@github.com>
wrote:

Hi,
I have not received the update.
Have you sent the update on the email I have registered with Xamarin
Account?
The point is that in the past Xamarin was not free and the trail period of
Xamarin last for a month, so every month I have registered with another
email. But it was a fake email - Xamarin do not require to confirm the
email address. I bought your prodact with an email zxc@wp.pl
<javascript:_e(%7B%7D,'cvml','zxc@wp.pl');> but I have no access to it. Can
you send me the update on blazej.prochniak@hotmail.com
<javascript:_e(%7B%7D,'cvml','blazej.prochniak@hotmail.com');>, please?
Regards
Blazej

Date: Wed, 18 May 2016 07:33:05 -0700

**Comment by bprochniak** [comment]
Thanks jp,
Can you provide me with my purchase order number so I can use it in future and can you change my email in your client database, please?

Aslo I have a question regarding support Windows Phone. When can we expect it?
Regards
Blazej

Date: Thu, 19 May 2016 07:40:37 -0700

**Comment by tilutza** [comment]
Hi,


I've send twice an email (3 weeks ago) from the contact from in the grail ui kit but no one seems to respond to that.

Like I said, I would like to use Xamarin Forms 2.3 in my project and the Grail UI KIT is build with 1.5. I need the source code for Artina PCL, Android and iOS. Can you please send it to me to tilutza at g.mail COM

**Comment by SWHandyMan** [comment]
I'm also in need of the latest version so that I can use my XF 2.2 project. I just purchased Grial. What email do I send my request to? The hello at uxdivers email sent an automatic response that the inbox was full.

Thanks, 

Brent

**Comment by pablogermano** [comment]
Hi SWHandyMan, the update was launched today. 
Please check your inbox (the address used on the purchase).

Best,
Pablo

**Comment by arunr14** [comment]
Hello

We purchased Grail version 1.2.1 and we still have this problem when using appcompact 23.3.0 and xamarin forms 2.2.0. We have not received any update on the purchase email. Could you please instruct where to get the latest version, this is impacting our deployments and would appreciate an immediate response.
 
Thanks
Arun

**Comment by jpbrocca** [comment]
Hi @arunr14,

Could you send me an email with your order number so I can send you the update?

Regards and thanks,
JP

**Comment by jpbrocca** [comment]
Hi,

OK, glad to hear that :)
Please let me know if you need anything else.

Best,
JP

**Comment by bprochniak** [comment]
Hi,

A few years ago I purchased your product. How I can login into admin page?

https://admin.grialkit.com/secure/grial/front/login.html
Grial Admin | User Login<https://admin.grialkit.com/secure/grial/front/login.html>
Grial Admin
admin.grialkit.com



Regards

Błażej

________________________________
From: Blazej Prochniak <blazej.prochniak@hotmail.com>
Sent: Friday, May 20, 2016 7:02 AM
To: UXDiversGrial-UI-Kit-Support
Subject: RE: [UXDivers/Grial-UI-Kit-Support] Grailkit with Xamarin.Android.Support.v7.AppCompat version 23.3.0 (#44)

Thanks jp,

Can you provide me with my purchase order number so I can use it in future and can you change my email in your client database, please?

Aslo I have a question regarding support Windows Phone. When can we expect it?

Regards

Blazej

________________________________
Date: Thu, 19 May 2016 07:40:37 -0700

**Comment by jpbrocca** [comment]
Hi,

Grial Web Admin is available for Grial 2 and Grial 3. Your license is Grial
1.5 so if you try to get access it won't work.

Best regards
JP

**Comment by bprochniak** [comment]
Hi JP,

Thanks for your message. How can I upgrade to Grial 3 and what is the price?

Regards

Błażej
________________________________

**Comment by jpbrocca** [comment]
Hi Blazej,

Grial 3 is not backward compatible with Grial 1, so you need to purchase a
new license.

You can check the pricing here:
https://grialkit.com/download/

During this month (today is the last day! ) we are offering Grial customers
a 30% discount to purchase Grial 3 Pro.

Best regards
JP

**Comment by bprochniak** [comment]
Hi JP,

Do you still offer a 30% discount to purchase Grial 3 Pro?

Best regards

Blazej
________________________________
