### ISSUE TITLE
How do you use a CustomNavBar.xaml in the TabControlCustomSamplePage.xaml?

### ISSUE THREAD

**Issue by mikeatmarvel** [UXDivers/Grial-UI-Kit-Support#442]
I want to have a custom navigation bar for use on the multiple platform TabControlCustomSamplePage.  I am having a difficult time trying to implement this in the xaml code.  Where do I best drop in the custom nav code to do this?  Is it possible?

thank you
-premium subscriber

**Comment by jpbrocca** [comment]
Hi @mikeatmarvel,

Simply wrap your `TabControl` into a `Grid` or a `StackLayout` so you could have the CustomNavBar at the top and the `TabControl` at the bottom.

Best,
JP
