### ISSUE TITLE
Upgrade to Xamarin Forms - Version 3

### ISSUE THREAD

**Issue by jwtownsend** [UXDivers/Grial-UI-Kit-Support#443]
Are there any problems reported with Grial Kit when updating to Xamarin Forms 3?  Thanks.

**Comment by kevinvella** [comment]
@jwtownsend I've started a project and updated to Xamarin Forms 3. Till now no errors or exceptions popped up from this update

**Comment by jwtownsend** [comment]
Thank for your response! I'll try it.

**Comment by jpbrocca** [comment]
Hi @jwtownsend and @kevinvella,

Today we have released Grial 2.7.0.0 with support for Xamarin Forms 3.1.

Best,
JP
