### ISSUE TITLE
Lazy loading App.xaml resources

### ISSUE THREAD

**Issue by kevinvella** [UXDivers/Grial-UI-Kit-Support#444]
Hi,

I've been doing some research on improving the app start up on android. I've come across this article [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance#reduce-the-application-resource-dictionary-size](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance#reduce-the-application-resource-dictionary-size).

How could we lazy load the current App.xaml?

**Comment by jpbrocca** [comment]
Hi @kevinvella,

We have tested with the past versions of Xamarin Forms and we didn't find any improvement on startup time. We have repeated the same tests with latest Xamarin Forms version (3.0.0.561731).

Our tests in Android were as it follows:

Test 1)
- We duplicated `App.xaml` and renamed the file as `Test.xaml`.
- We removed all resources from `App.xaml`.
- Then we modified `WelcomePage.xaml` to contain only a `<Button>`. We added code to merge the `Test.xaml` resource dictionary when the button was clicked.

*Result*: We measured the statup time and it took **5 seconds** to load, and **1 additional second** when the button was clicked.

Test 2)
- Same as Test 1 but merging `Test.xaml` right after the `WelcomePage.xaml` was loaded in the visual tree.

*Result*: We measured the statup time and it took **6 seconds** to load.

Test 3)
- Just tested a non-modified copy of Grial.

*Result*: We measured the statup time and it took **6 seconds** to load.

We didn't notice any improvement so we left everything it as it was.
If you find another way then please let us know.

Best,
JP

**Comment by kevinvella** [comment]
@jpbrocca Thanks for the explanation. Closing issue :)
