### ISSUE TITLE
Xamarin update - breaks Gorilla player?

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#447]
Updated to the latest version of Visual Studio, which includes a Xamarin upgrade.  When running Gorilla player in either an Android or iOS emulator, the main screen displays the running server.  You select the server to connect.  Then it acts like its going to connect and returns to the same screen.  I cleaned and rebuilt, tried restarting VS, restarted my computer.

**Comment by attrib75** [comment]
This also occurs on a real Android phone.  Running latest version of Gorilla Player

**Comment by LeoHere** [comment]
@attrib75 is this on VS for Mac or Windows?

**Comment by LeoHere** [comment]
@attrib75 we tested with latest VS on Windows (15.7.4) and VS on Mac (7.5.3) and all seems to be working as expected. We used Gorilla 1.2.2.0. What versions/platform are you testing?

**Comment by attrib75** [comment]
This is for Windows.   Are there any logs I can look at or troubleshooting steps I can perform? Thanks

**Comment by LeoHere** [comment]
@attrib75 yes, you can set the log's verbosity and access to the log location from the task bar icon.

![image](https://user-images.githubusercontent.com/16000584/42315121-08d2ff66-801d-11e8-9cb6-a22b91fc8dc1.png)

Do as follow:
- Close VS
- Open the Gorilla logs location
- Move the current log files to a safe location, just in case you need them later. (This step is just remove any previous log entry to make it easier to focus on the problem you are currently analyzing)
- Restart Gorilla Desktop
- Set log Level to `Debug`
- Open VS

Try reproduce the issue and check the logs.

**Comment by IoTFier** [comment]
I am also experiencing build failure error while compiling as-is downloaded code for the full version of Grial with Gorilla Enabled Android version of my App.

I have opened a new issue https://github.com/UXDivers/Gorilla-Player-Support/issues/295.
May be we are facing the same root cause.
 
Thanks,

**Comment by attrib75** [comment]
This seemed to work itself out after restarting computer again, uninstalling the particular app on the simulator and redeploying it to the simulator.  Thanks for the help!
