### ISSUE TITLE
Adding Grial UI Kit in existing project

### ISSUE THREAD

**Issue by srivastava1july** [UXDivers/Grial-UI-Kit-Support#45]
I am adding grial UI kit in an existing project, I am trying to create the dasboard page with my viewmodel but I the DashboardItemTemplate is not binding with the viewmodel. I am not getting any error but the blank dashboard page without any data.

**Comment by jpbrocca** [comment]
Hi @srivastava1july,
Did you make sure you copied everything from the sample provided with Grial?

And yes, if the data is not getting to the view you won't get any error and nothing will be rendered.

Regards,
JP

**Comment by srivastava1july** [comment]
I have added UXDivers.Artina.Shared dll in Forms project and UxDivers.Atina.Shared.IOS in IOS project.  I have added Appearance.cs in Ios and made changes in AppDelegate, also I have added required style in App.xaml and added colours.cs and colours.tt in forms project. I need only dashboard page right now so copied only DashboardPage and DashboardItemTemplate.
What else is required?

**Comment by jpbrocca** [comment]
Try to copy the data from the model on our sample.
Maybe what you did is missing some of the data structure or your data is not getting properly to the view.

**Comment by srivastava1july** [comment]
I tried that also but the same issue. Anyway whatever model I am binding I have made the changes to binding so it should work with my viewmodel also.

**Comment by jpbrocca** [comment]
hmmm....is difficult to tell you what could be wrong from here.
Only thing that comes to my mind is an issue with the model/viewmodel.
