### ISSUE TITLE
Support for Xamarin Live Reload during debug mode

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#452]
**Is your feature request related to a problem? Please describe.**

The deployment of the app in Gorilla enabled mode takes a lot of time. After that delay, almost everytime, on Android platform, I have to uninstall the app, remove the mono files, Xamarin.android runtime and then run deployment. It takes away lot of time

**Describe the solution you'd like**
Faster deployment and support for Xamarin Live Reload in debug mode.

**Describe alternatives you've considered**
I tried evaluating Xamarin Live Reload which is in the preview now. But it doesn't work with Grial based app. Has anyone on Grial team evaluated this new feature?

**Additional context**
Please validate on your end if with Xamarin Live Reload works with your app in the debug mode.

**Comment by dirivero** [comment]
I'm closing this as Xamarin Live Reload was deprecated a long time ago. It has been replaced by XAML Hot Reload that is way better and more stable. We have collaborated with MS in their preview by providing Xaml templates for testing :) please check here: https://devblogs.microsoft.com/xamarin/xaml-hot-reload/
