### ISSUE TITLE
Showing borders around grid rows and columns

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#453]
How to enable borders around rows, columns and controls within the styles and themes provided by Grial ?
### Description

For customizing my own changes and for quick learning of the xaml controls on as-is views and templates, I am trying to enable borders. But couldn't find any easy approach.
I don't want to keep introducing boxviews and frames to do that (which is by the way messes up the code and is very time consuming process).

I would appreciate your thoughts and any guidance to achieve this.

The as-is documentation is appreciated but it will be helpful if there was documentation and diagrams  showing per page control structure in some kind of wireframes as well as relation among views and view templates. 

If the goal of Grial is to have customer use their framework and be productive for the shortest time to market, then, please help us reduce our learning curve. 

Your help is really appreciated.

**Comment by IoTFier** [comment]
Any input from anyone?

**Comment by jpbrocca** [comment]
Hi @IoTFier,

Unfortunately, there is no such property provided by Xamarin Forms.

As a workaround you can check how this is achieved for `<Grid/>` on `DashboardPage.xaml`.
Basically you set a `BackgroundColor` for the `Grid` then add `ColumnSpacing` and `RowSpacing`=1 and finally you set the cells content also with a `BackgroundColor` (i.e.: "`White`").
That way you will get "borders".

You should check Xamarin Forms documentation about which controls provide borders.

You can check Grial's custom renderers to see which styling properties we provide:
http://uxdivers.github.io/Grial-UI-Kit-Support/renderers.html.

Best,
JP
