### ISSUE TITLE
Xamarin Forms 3.1 Tab Page support

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#455]
Hi Grial Team,

Xamarin Forms 3.1 now supports bottom tabbed-page for both iOS and Android.

Will Grail Ui kit Pro update to support this features instead of current “view” approach? With “page” we can capture more events as the page is shown and hidden.

Hope to hear from you soon.

Thanks,
Dennis

**Comment by IoTFier** [comment]
Hi @denfung, Grial Kit 2.7 Xamarin Forms 3.1.0.583944. 
I am also new to Grial UI Kit. I haven't tried that bottom tab feature yet. Check if it is in the version 3.1.0.583944 or in the Forms 3.1.0637273?

**Comment by denfung** [comment]
Hi @IoTFier,

It is in verison 3.1.0.583944.

Regards,
Dennis

**Comment by denfung** [comment]
Hi Grial Team,

Any plan to incorporate bottom page navigation in Grial UI Kit Pro?

Hope to hear from you soon.
Dennis
