### ISSUE TITLE
Android app "Could not resolve reference to 'Mono.Security.Interface.MonoTlsProviderFactoryDelegate' (defined in assembly 'Xamarin.iOS)"

### ISSUE THREAD

**Issue by faceoffers28** [UXDivers/Grial-UI-Kit-Support#456]
When trying to Release a GrialKit Android app with Linking as SDK Assemblies Only, I get the following error.

everity Code Description Project File Line Suppression State
Error The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Mono.Security.Interface.MonoTlsProviderFactoryDelegate' (defined in assembly 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065') with scope 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Mono.Security.Interface.MonoTlsProviderFactoryDelegate

### Description
I built my app on top of the Full sample that comes with the initial Grial download. Since the Android Project seems to be somehow referencing Xamarin.iOS, I decided to create a support ticket. 

### Steps to Reproduce
1. Create a Xamarin.Forms app using the Full sample code base
2. Build a Release app using Android SDK 8.1

### Expected Behavior
Linking should work and the Release package should be  smaller in size.

### Actual Behavior
I get the error message. For now, I can build the Release app by setting the Linking to none.

### Basic Information
Version with issue: Artina.Shared = 2.5.2.0, Artina,Shared.Base = 2.5.2.0
Last known good version: This is my first Grial app.
IDE: Visual Studio Enterprise 2017
Platform Target Frameworks: Xamarin.Android = 8.2.0.16
Android: 8.1
Android Support Library Version: 26.0.2
Nuget Packages: Xamarin.Forms = 2.5.1.444, FFImageLoading.Forms = 2.2.25, FFImageLoading.Transformations = 2.2.9
Affected Devices: None. This is a Release issue.

**Comment by LeoHere** [comment]
@faceoffers28 Are you experiencing this issue in the solution downloaded from the Grial admin, without any modifications?

I don't see any reference to iOS from Android.

I did a quick search and this [Xamarin Forum post](https://forums.xamarin.com/discussion/69073/problem-linkassemblies) might help you.
