### ISSUE TITLE
Custom Nav Bar - How to show back arrow on Android

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#457]
Hi,
Not an issue, just a question.  I'm implementing the custom nav bar successfully.  Only thing is that it shows the hamburger menu when I would like it to show the back arrow.  Is there a way to do that? 
thanks

**Comment by jpbrocca** [comment]
Hi @attrib75,

You just need to change the Icon as you would do with any of other icons in Grial (this is just a `<Label />` showing a font icon.

Best,
JP

**Comment by attrib75** [comment]
Gotcha, thanks.  I thought there was a way to somehow tap into the navigation stack and make it dynamic.  I could probably build that in to my logic.
