### ISSUE TITLE
error after update projetct

### ISSUE THREAD

**Issue by ClaudineiMonteiro** [UXDivers/Grial-UI-Kit-Support#459]
started to generate this error, how do I solve it
![capturar](https://user-images.githubusercontent.com/16354515/43399266-d6e9c782-93e0-11e8-9a79-34294f80f132.PNG)

**Comment by jpbrocca** [comment]
Hi @ClaudineiMinteiro,

Did you check you have access to our nugget server?
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-setting-up-uxdivers-nuget-source

You can try with your browser to check if you get access here:

http://nuget.uxdivers.com/grial

Regards
JP

**Comment by LeoHere** [comment]
Closing the issue since it is duplicated in #460.
