### ISSUE TITLE
Problem using Grail

### ISSUE THREAD

**Issue by darkl0ad** [UXDivers/Grial-UI-Kit-Support#461]
I purchased Grail to improve the UI for my company's product. Thus far, I'm having a very difficult time integrating it into our platform.  I've been using the Sample app that was automatically created for me as well as the full demo.  The full demo is probably great for someone with expertise in the subject. I've been developing in Forms since its release and have mostly implemented the UI through code.  I'd like to move the project to the xaml model. I bought Grail to learn from. 

Question: Are there example projects which demonstrate one or a few features? I'm finding it difficult to unwind the demo for the views I need.

Is there a user support site?

Thanks!

**Comment by jpbrocca** [comment]
Hi @darkl0ad,

Can you please describe what part you need help with?

Here are a few resources which could be helpful in the meantime: 

- All Grial UI Kit screens previewed and categorized as in Grial Full sample
  - https://grialkit.com/screenshots/
- I think the most important part for you to start with is to have a better understanding of how the product is structured:
  - http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-ui-templates
  - https://www.youtube.com/watch?v=4uasuF67Dew
- How to work with Grial theme:
  - http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#theme-and-branding-of-your-app
  - https://www.youtube.com/watch?v=uMGwnAgJu_w
- How to set up Grial on an existing project
  - http://uxdivers.github.io/Grial-UI-Kit-Support/setup-grial-on-an-existing-project.html

Best regards,
JP

**Comment by darkl0ad** [comment]
I read all the docs. I decided to start over so I downloaded my full Grail package from your site.  I updated all the Nuget packages. When I compile for Android, I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'MainActivity.OnConfigurationChanged(Content.Res.Configuration)': no suitable method found to override	Reflex.Android	D:\Dev\Grial\Reflex.Android\MainActivity.cs	113	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Content' does not exist in the namespace 'Reflex.Android' (are you missing an assembly reference?)	Reflex.Android	D:\Dev\Grial\Reflex.Android\MainActivity.cs	113	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)	Reflex.Android	D:\Dev\Grial\Reflex.Android\MainActivity.cs	109	Active

# I am runny the latest VS. 

Thanks!

**Comment by jpbrocca** [comment]
Hi @darkl0ad, how are you?

Try the following steps:

1. Close Visual Studio.
2. Delete Bin & Obj folders in .NET Standard & Android projects.
3. Open Visual studio again.
4. Clean the Solution.
5. Rebuild the solution.

In case the above didn't work, here are just a couple of questions to help us to find the cause:
- Are you experiencing this issue in the solution downloaded from the Grial admin, without any modifications?...if you changed something related to Android Build setup (linker) check this thread:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/456
- Could you provide more details about your OS, and Android device you are using?
- Check your Android SDK tools are set properly.

Let me know how it goes.

Best,
JP

**Comment by darkl0ad** [comment]
I changed my namespace to just Reflex.  I am getting this error from the full app

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	Reflex	D:\Dev\GrailTest\Full\Reflex\Views\Navigation\CategoriesListFlatPage.xaml.cs	10	Active

**Comment by LeoHere** [comment]
@darkl0ad this error usually means that the namespace in the XAML file (i.e. `CategoriesListFlatPage.xaml`) does not match the namespace in the code behind (i.e. `CategoriesListFlatPage.xaml.cs`). Could it be what is happening here?
