### ISSUE TITLE
Grial UI Kit example for Responsive and Adaptive UI

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#462]
Hi Grial team and Community,

**Any recommendation on using any of the  Grial UI Kit Views to implement an Responsive and Adaptive UI?**
I started with ProductCatalogPage.xaml and its template but there is not much out there to build on for my needs. In fact, I didn't find anything delivered by Grial UI Kit that provides any Adaptive UI templates across orientations, and different type of devices.

I am looking for an example (may be using Relative and/or Absolute layout) where in couple of rows of my DataTemplate - 
1. some views towards the beginning and end of the row are position bound (locked) regardless of the device
2. Label view in of the rows is expandable to two rows (which I have achieved using a Grid in the containing column and using LineBreakMode. But, I would like the container row to expand its height to match the height of the expanded label, and also pushing down its sibling rows below the expanded length.

I am also referring to the following links -
[]
((https://github.com/dannycabrera/Get-iOS-Model))

(https://github.com/dannycabrera/GetDroidModel)

(https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions)

Thanks,

**Comment by jpbrocca** [comment]
Hi Nilesh,

All of our templates are optimized for phones and tablets. That is achieved through the responsive helpers provided by Grial. These will add more control over how things are displayed in different scenarios. You can add them to extend our templates to suit your needs.

Check the `ResponsiveHelpersPage.xaml` which show you specific properties in actions, and also check the docs about responsive helpers:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-helpers-responsive-helpers

Best,
JP

**Comment by jpbrocca** [comment]
Hi @IoTFier,
you are welcome.

Please check:
- http://uxdivers.github.io/Grial-UI-Kit-Support/renderers.html
- All pages under `Theme` category of Grial full sample.

I am closing this issue now to keep things tidy.

Best,
JP

**Comment by IoTFier** [comment]
Thanks @jpbrocca.

**Comment by IoTFier** [comment]
Hi @jpbrocca,

I reviewed ResponsiveHelpersPage.xaml closely and it doesn't have foundational baseline for my responsive layout for my needs. Also, within ResponsiveHelpersPage.xaml the text on the comparison table labels on the 3rd row doesn't get resized or broken down when the phone's screen resolution is low. I am trying to support my UI for iPhone SE as well as on the 1080x1920 resolution on Android.
See the screenshot attached below.
![responsivehelperspage-render-comparison](https://user-images.githubusercontent.com/26844611/44033854-4513d93c-9ed1-11e8-86b6-bc32dd697002.JPG)

I have laid out one of the examples from my responsive needs in the document attached below - 
Can you help me identifying a view from Grial UI Kit that I can build upon for my needs?
I am trying to avoid using absolute and relative layouts. With Stacklayout I don't know how to restrict width to position last two views with relative position locked to the width of the screen.
Note - specified pixels is just an unit for example; it need not be that absolute / specific.

![responsivedesignlayoutrequirement1](https://user-images.githubusercontent.com/26844611/44034218-2df24a9e-9ed2-11e8-9fec-16eccf41bc02.jpg)

Looking forward to your input and help.

Thanks

**Comment by jpbrocca** [comment]
Hi Nilesh,

The responsive helpers will certainly help you to target specific scenarios to control how things flow in tables/phones and when specific device orientation is met.

What you want to achieve can be done in several ways. 
I suggest to take a look to `CategoriesListWithIconsItemTemplate.xaml` and also templates under `Articles/Templates` and `Messages/Templates` folders.

I highly suggest that you review [Xamarin Forms's docs about Grid Layouts](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid). This will give you foundational knowledge to understand how to dissect your layout.
Also you need to get familiar with [`LayoutOptions`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options) to understand how elements will behave in your UI in order to get the desired outcome.

Best,
JP

**Comment by IoTFier** [comment]
Hi JP,
Thank you and I appreciate your guidance. 

I will continue my reading on the topics you pointed out. I had started on building out my requirement mentioned above using the template ProductCatalogueItemTemplate which has two rows. It will be used in a template which has 4-5 rows with varying pieces of information in each one of them. I had taken bunch of steps but wasn't able to achieve using that template.

Luckily your suggestion matched my pick that I had started working on from last night. I have made a much better progress using the template "CategoriesListWithIconsItemTemplate.xaml"
So, thank you very much your guidance there.

Grial is adding a great value to my learning curve by giving a much broader exposure to Xamarin Form Stack. This is a much better way for someone in my shoes to accomplish the startup goals than just learning theory and trying HelloWorld like example in each topic. With Grial UI Kit, I am doing a lot more progress in putting together my App's UI layer.

Again as a well-wisher and looking at this UI Kit from the other side of the table - I highly request you all to structure the documentation of the Grial App from the point of App Architecture, wiring into Mock API services (next version for the DesignTimeData.json) running in Azure, option to plug-in for Content Management Services for structuring digital assets and a wiring template in the new Xamarin Essential API. **It will be a supercharged jump startup for any type and size of organization.**

I was reading some other Git issues and there are users who have been working with Xamarin in Native but new to Xamarin Forms are struggling in picking up Xaml. This UI Kit is an awesome catalyst for learning, building and delivering … then why not make it simple for us to absorb, keep up with the changes and build the mastery in it? 

As much as we understand this avenue to address only Grial related issues - please recognize the need from the grassroot level. I request to have an open Wiki and a Forums for Grial Customers to collaborate for needs beyond Grial and Xamarin Forum. Gitter channel could be active but no one uses that.

Again, thank you for your help and for all the hard work put together by Grial Team members.

Thanks,
-Nilesh
