### ISSUE TITLE
DashboardMultipleTileItem page "OnTileTapped" code behind for different tiles

### ISSUE THREAD

**Issue by upskydownshoes** [UXDivers/Grial-UI-Kit-Support#463]
I am trying to use the DashboardMultipleTilePage with the tiles set out as DashboardMultipleTileItem in the DashboardMutipleTilesViewModel. I would like each tile to have it's own action bound to it when I tap it. I have found that any tap is processed in the DashboardVariantItemTemplate with this code:

```
<ContentView.GestureRecognizers>
		<TapGestureRecognizer
			Tapped="OnTileTapped" />
	</ContentView.GestureRecognizers>
```

I have tried various iterations of adding new methods, such as adding the following in DashboardVariantItemTemplate.xaml.cs: 

```
public async void OnTileTapped(object sender, EventArgs args)
		{
			await Application.Current.MainPage.DisplayAlert("Tile Tapped!", "You have tapped a VariantItem \r\n DashboardItemTemplateBase", "OK");
		}

        public async void OnTileTapped2(object sender, EventArgs args)
        {
            await Application.Current.MainPage.DisplayAlert("Tile Tapped!", "You have tapped a second VariantItem \r\n DashboardItemTemplateBase", "OK");
        }
```

And then adding the following to the DashboardMutipleTilesViewModel.cs file:

```
new DashboardMultipleTileItem
				{
					Title = DataResources.DashboardMultipleTileItem2Title,
					Body = "",
					Avatar = "",
					BackgroundColor = "transparent",
					ShowBackgroundColor = false,
					IsNotification = false,
					BackgroundImage = "Tiles/VDarkGreenTile.jpg",
					Icon = FontAwesomeWeb511Font.Atlas,
					Badge = 2,
                    Tapped="OnTileTapped2"
                },
```

But I am still only getting one popup with the same message.

Is there a file somewhere I am missing to make each tile route to a different page when tapped???

Many thanks.

**Comment by dirivero** [comment]
I don't know exactly what kind of actions you want to execute, but, in general, the best way to achieve that is through a bound Command. Here is an article about Commands: 
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm#commanding-with-viewmodels

You would want to define the command action in the class that acts as BindingContext for the dashboard items. In Grial's sample that class is `DashboardMultipleTileItem`. Try adding these lines of code to it:

```
private Xamarin.Forms.Command _tapCommand;
public Xamarin.Forms.Command TapCommand
{
    get
    {
        if (_tapCommand == null)
        {
            _tapCommand = new Xamarin.Forms.Command(() =>
                    Xamarin.Forms.Application.Current.MainPage.DisplayAlert(Title, "", "Ok"));
        }

        return _tapCommand;
    }
}
```

Finally, from the Xaml you have to use the Command property instead of Tapped.

```
<ContentView.GestureRecognizers>
  <TapGestureRecognizer Command="{Binding TapCommand}" />
</ContentView.GestureRecognizers>
```

If you run this you will notice that the alert title will match the data of the tapped item. That means that you can decide to do different things depending on the data in that `this`. Another option is to have multiple classes with the `TapCommand` property each doing something different.

Hope this helps.

**Comment by upskydownshoes** [comment]
That's Fantastic Diego, thank you!

For anyone else out there, I had real trouble using the title variable to invoke the new page method upon tapping a tile, so this is what I ended up with in the DashboardVariantItemTemplate.xaml.cs:

```
private Xamarin.Forms.Command _tapCommand;
        public Xamarin.Forms.Command TapCommand
        {
            get
            {
                if (_tapCommand == null)
                {
                    switch (this.Title) {

                        case "Find Bottle By Name":
                            _tapCommand = new Xamarin.Forms.Command(() =>
                            Xamarin.Forms.Application.Current.MainPage.Navigation.PushAsync(new FindBottlesNames()));
                            break;
                        case "Find Bottle By Type":
                            _tapCommand = new Xamarin.Forms.Command(() =>
                            Xamarin.Forms.Application.Current.MainPage.Navigation.PushAsync(new BottleSearch()));
                            break;
                        case "Lay Bottles Down":
                            _tapCommand = new Xamarin.Forms.Command(() =>
                            Xamarin.Forms.Application.Current.MainPage.Navigation.PushAsync(new LayBottlesDown()));
                            break;
                    }
```
Again, many thanks Diego, was stuck on that 2 days.

**Comment by upskydownshoes** [comment]
Diego,

I don’t know if you saw my comments on github, but I just wanted to say thanks again for this. I
am just getting started on Xamarin and c# in general and although I code in other languages, I got properly stuck. Cheers... good man!

**Comment by dirivero** [comment]
I'm glad it helped! Happy coding :)
