### ISSUE TITLE
Fill up the tab control content with tab item content

### ISSUE THREAD

**Issue by sky018** [UXDivers/Grial-UI-Kit-Support#466]
### Description
The tab items content are in center how do I fill up the tabControl content with the tab items

### Expected Behavior
Image shown below should be the expected behaviour:
![expected_grial](https://user-images.githubusercontent.com/21186089/44011132-5b0153ec-9ee9-11e8-83c7-a40d64d8d47e.jpg)

### Actual Behavior
Image shown below is the actual behaviour:
![result_grial](https://user-images.githubusercontent.com/21186089/44011338-95fbecea-9eea-11e8-8872-e0847d68575e.PNG)

### Basic Information
Code snippet for Data Template:

`<DataTemplate x:Key="CustomDefaultTabItemTemplate">`
<Grid Style="{ Binding IsSelected, Converter={ StaticResource CustomTabItemIndicatorStateStyleConverter }, Mode=OneWay }"
              VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">

            <Grid Padding="0,0"
		      ColumnSpacing="0"
		      HorizontalOptions="Center">

                <StackLayout Orientation="Vertical" Spacing="0">

                    

                    <Label IsVisible="{ Binding Icon, Converter={ StaticResource IsNotNullConverter } }"
                        HorizontalTextAlignment="Center"
			    Text="{ Binding Icon }"
			    Style="{ Binding IsSelected, Converter={ StaticResource CustomTabItemIconTextStateStyleConverter }, Mode=OneWay }" />

                    

                    <Label IsVisible="{ Binding Text, Converter={ StaticResource IsNotStringEmptyConverter} }"
                           HorizontalTextAlignment="Center"
			       Style="{ Binding IsSelected, Converter={ StaticResource CustomTabItemTextStateStyleConverter }, Mode=OneWay }"
		               Text="{ Binding Text }" />

                </StackLayout>
            </Grid>

        </Grid> </DataTemplate>`

- Version with issue: 2.5.2
- Last known good version: 2.5.2
- IDE: VS2017 Pro
- Platform Target Frameworks: 
  - Android: 6.0
- Nuget Packages: Xamarin Forms 2.4.0.282
- Affected Devices: Android

**Comment by sky018** [comment]
Fixed. Used a different template and not the customtabitemtemplate

**Comment by IoTFier** [comment]
Hi @sky018, are you using Grial's TabbedPage?
