### ISSUE TITLE
Artina:Translate TabbedPage heading for Android

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#467]
Hi @jpbrocca,

I am using Grial TabbedPage. 
In Android version it shows the tab headers in upper case. I would like the casing to be same as one on iOS. How do I accomplish that ? Also how to change the font size on Android using Artina:Translate markup extension?

Thanks

**Comment by jpbrocca** [comment]
Hi @IoTFier,
The Upper Case is by design on Material Design language. This is not exposed by Xamarin Forms so there is no direct way for you to change that.
You need to search for Android styles so you can accomplish that natively.

Best,
JP

**Comment by jpbrocca** [comment]
I forgot to mention that `artina:Translate` purpose is just display strings from RESX files in the UI...it is only about translation/localization.

You also need to search for Android styles to change font size.

**Comment by IoTFier** [comment]
Thank you JP. I will do that.

**Comment by IoTFier** [comment]
Hi JP, Happy Saturday!

While reading https://montemagno.com/xamarin-forms-android-selected-and-unselected-tab-colors/ 
I learned from one of the comment that using XF 3.1+ for Android one doesn't need Custom Renderer to add Icons on Tabs, which I don't see reflected on my Android phone directly. 
Is that suppose to work with Grial + XF 3.1?

I was also wondering does XF 3.1 also support styles changes Android Tab directly?

Thanks,

**Comment by jpbrocca** [comment]
Hi @IoTFier,

Grial TabbedPage sample y just a sample showing Xamarin form's Tabbed Page.
Basically, all their features should work.

Best,
JP

**Comment by IoTFier** [comment]
Thanks JP. I am going to validate XF 3.2 for the TitleView feature to host CustomNavBar. Will let you know later tonight.
