### ISSUE TITLE
Controlling Grial Badge Circle Size

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#468]
Hi @jpbrocca and Grial Team.

Few questions on Grial's badge 

1. How do we control the size of the circle in Grial's Badge?

2. How do I display Grial's badge when the my counter value is 0? I would like the badge to showup with a specific color that I want to control based on the data.

3. In Android I saw in some instances showing "-2" inside the badge was not rendering the circle completely while circle was displayed in full. The same thing on other rows, of the same Grid, at exactly same displacements was showing full circle and -2. 
How do fix that?

Your help will be appreciated.

Thanks,

**Comment by jpbrocca** [comment]
Hi @IoTFier,

About your questions:

1. You need to edit the `Badge.xaml` file and change the font size directly for both the circle and the text.
2. You need to use logic to manage that. Check the `Badge.xaml.cs` file.
3. I am not aware of that issue...could you provide more details?
 - Is this happening in the Grial Full sample or Starter?

Best,
JP
