### ISSUE TITLE
Adding CustomNavBar to the TabbedPage

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#470]
Hello @jpbrocca , Grial Team and friends,

I am trying to place the custom nav bar (from Grial) in the Tabbed page (Grial); but haven't been successful. Is there any Grial template that's using TabbedPage and hosting the CustomNavBar on top of that page? Any recommendations ? 

I tried defining ControlTemplate (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/creating) in App.xaml, wrapped the local:customNavBar inside the ControlTemplate. But TabbedPage doesn't support it.
    <Application.Resources>
        <ResourceDictionary>
            <ControlTemplate x:Key="myCustomNavBar">

Any thoughts / recommendations on the xaml approach in Xamarin Form 3.1 ?

Xamarin Form 3.2, which is in preview, has a new feature - "TitleView"
https://github.com/xamarin/Xamarin.Forms/pull/2586

Can anyone from Grial who is validating next build of Grial UI Kit against Xamarin Form 3.2 provide some input too?

Thank you.

**Comment by jpbrocca** [comment]
Hi @IoTFier,

The [`TabbedPage`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page) is a container for multiple pages so there is no way of adding other content.

Alternatively you could add inside each `ContentPage` the `CustomNavBar` but you will need to set the tabs to be positioned on the bottom in Android to make sense:
https://montemagno.com/xamarin-forms-official-bottom-navigation-bottom-tabs-on-android/

Best,
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca,

Thank you for your suggestion above. In the mean time, in the Grial TabbedPage, I assigned Grial CustomNavBar (customized for my app) to the TitleView property of the NavigationPage in the XF 3.2 pre2. It renders fine, except it adds margin of (I guess) 10-15 points on both left and right side on iOS, and of around 10-15 points on Android as shown below 
FYI - https://github.com/xamarin/Xamarin.Forms/issues/3644

I also observed that adding any new ContentView xaml file in the project shows a default navigation bar added at the top of the page like one shown below 

I am got this behavior when I simply duplicated existing Customer Navigation Bar and just change the name of the file (in .xaml, .cs and class names etc).
![xf3 2-titleview-defaultnavbar](https://user-images.githubusercontent.com/26844611/44548109-c9027000-a6e2-11e8-821a-a6168d5ed452.JPG)

Original CustomNavBar where the top page has gradient portion of the image with no navigation bar at all. I tried to reproduce this in XF 3.1 as well, and apparently it did appear in all top 3 versions of XF 3.1.
I am not sure if this is an issue around XF alone or in combination of XF 3.x and Gorilla. Weird thing is I don't see that navigation bar for the template codes that came in the app code. 
_**I need your help to get to address this.**_

![xf3 2-titleview-nodefaultnavbar-withcodewritteninxf3 1](https://user-images.githubusercontent.com/26844611/44548124-d1f34180-a6e2-11e8-9236-d33e4322b3f8.JPG)

**Comment by IoTFier** [comment]
Hi @jpbrocca , any thoughts on my note above?

Thanks

**Comment by jpbrocca** [comment]
1. Yes, wait for Xamarin team answer.
2. You need to read the documentation about how to hide navigation bar in Gorilla:
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Previewing-within-a-Navigation-Page

**Comment by IoTFier** [comment]
Hi @jpbrocca,

On # 1 above - Xamarin Forms team has acknowledge the issue and they are working on the fix
On # 2 above - Thank you for your guidance. I truly appreciate that.

Thank you,
