### ISSUE TITLE
ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java: Error: no suitable constructor found for TypefaceSpan(Typeface)

### ISSUE THREAD

**Issue by softsan** [UXDivers/Grial-UI-Kit-Support#473]
### Description

After updating to VS for mac 7.6 and Mono 5.12 it throws compile time error for our android project.
```
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error :  error: no suitable constructor found for TypefaceSpan(Typeface)
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error : 		super (p0);
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error :     constructor TypefaceSpan.TypefaceSpan(String) is not applicable
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error :       (argument mismatch; Typeface cannot be converted to String)
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error :     constructor TypefaceSpan.TypefaceSpan(Parcel) is not applicable
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error :       (argument mismatch; Typeface cannot be converted to Parcel)
obj/Debug/android/src/md523ddbe2709b662017ca089741e4ab680/ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(22,3): error : 
```
Grail UIKIT
 version:1.3
   
UXDivers.Artina.Shared.Droid v1.5.0.12799
UXDivers.Artina.Shared 1.5.0.12366

Even tried downloading latest application from admin site which has all the latest package, but it too has the same error.
### Steps to Reproduce

N/A 

### Expected Behavior

It should build correctly.

### Actual Behavior

It doesn't build and throw compile time error
### Basic Information

- Version with issue:
- Last known good version: VS for Mac 7.4 and Mono 5.10 
- IDE:VS for Mac 7.6
- Platform Target Frameworks: 
  - iOS:   iOS runs fine
  - Android:   android 8.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @softsan,

Version 1.3 is not supported.

When you said:

> "Even tried downloading latest application from admin site which has all the latest package, but it too has the same error."

- That render is not present in Grial 2+ since it is not necesary. You can remove it and directly reference the font family for Android in your styles.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#android

Best,
JP
