### ISSUE TITLE
Can not build project after Visual Studio for mac updated

### ISSUE THREAD

**Issue by eddycn3** [UXDivers/Grial-UI-Kit-Support#474]
error:
.../ArtinaCustomFontLabelRenderer_CustomTypefaceSpan.java(3,3): Error:  error: no suitable constructor found for TypefaceSpan(Typeface)
		super (p0);
    constructor TypefaceSpan.TypefaceSpan(String) is not applicable
      (argument mismatch; Typeface cannot be converted to String)
    constructor TypefaceSpan.TypefaceSpan(Parcel) is not applicable
      (argument mismatch; Typeface cannot be converted to Parcel)
 (ObaADM.Droid)

**Comment by dirivero** [comment]
There's no need for that custom renderer. It was removed from Grial about a year ago. You can check our code downloading version 2.5 or higher.

To fix it just remove it and reference the font family for Android directly in your styles with an OnPlatform:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#android
