### ISSUE TITLE
Problems for add Grial to an existing project

### ISSUE THREAD

**Issue by netoviskyy** [UXDivers/Grial-UI-Kit-Support#477]
Error at droid (iOS I not test yet) build:

"Type does not contain a definition for 'Assembly' ..."
"The "Resolvelibraryprojectimports" task failed unexpectedly..."
As the attached screenshot

What I've tried to do:
Important: I followed step by step from Grial documentation for add the (Grial) to an existing project
1. Clean Solution and Rebuild
2. I moved the solution for other drive
3. Deleted bin of all project and recompiled
4. Deleted and pasted again the files with problem
5. Restart the IDE

![sem titulo](https://user-images.githubusercontent.com/36972630/44790864-aeaf1300-ab76-11e8-8b41-624b8dfb4c45.png)

- IDE: VS2017
- Platform Target Frameworks: Xamarin Forms

**Comment by LeoHere** [comment]
@netoviskyy is your project targeting .net standard 2.0? 

**Side comment**: it is much more easy to start from the starter project than following the path of integrating Grial to your project. If it is an option for you I will strongly recommend you to follow that path.

**Comment by netoviskyy** [comment]
Unfortunately it is not an option. The problems reported above I solved. But I'm having different issues on the themes like in the image below

![sem titulo 222](https://user-images.githubusercontent.com/36972630/44809485-33188a80-aba5-11e8-8962-6ebb0091aca1.png)

**Comment by LeoHere** [comment]
@netoviskyy are you using Xamarin Forms 3.1 in your project?

**Comment by netoviskyy** [comment]
No, this is the version of my xamarin forms

Xamarin.Forms
3.2.0.729530-pre2

**Comment by LeoHere** [comment]
This property was added in XF 3.1 (see [this](https://github.com/xamarin/Xamarin.Forms/issues/1662)). May be this property is not in the pre release you are using...i would recommend moving to the last stable version.

**Comment by netoviskyy** [comment]
Okay, I will try !

**Comment by netoviskyy** [comment]
Good and bad news rsrsrs. The good new is wich the color problem solved, and the bad news is wich my project not works yet. I am have a new erro now, look:

![3](https://user-images.githubusercontent.com/36972630/44849788-964ffe80-ac31-11e8-97cf-98d3da9b36c5.png)

**Comment by LeoHere** [comment]
Looks like a Xamarin Android package issue....check [this](https://forums.xamarin.com/discussion/67000/error-inflating-class-android-support-v7-widget-toolbar-after-updaring-to-v7-appcompat-version-23-3) for example. If you google it you will finde several similar entries...

Hope it helps.

**Comment by netoviskyy** [comment]
I had read all the posts in the xamarin forum, stackoverflow etc rsrsrs. But no   solution worked for me. But now I found the cause of error, was my "style" wich missing theme reference!

Thank you very much @LeoHere , now its worked!
