### ISSUE TITLE
Load an icon in a tile, not a label, in Grial?

### ISSUE THREAD

**Issue by upskydownshoes** [UXDivers/Grial-UI-Kit-Support#479]
I have added a new icon set from Pixeden. I have added the Fontawesomefont with success before but I can only render an icon in a label, not at the center of a tile (such as on the DashboardMultipleTilesPage). On the tiles, I only get the question mark.

This is the font reference sheet:

![pixeden reference sheet](https://user-images.githubusercontent.com/37253528/45081918-225d9c80-b0f0-11e8-8295-8b30309e4bfb.PNG)

I downloaded the ttf file from:

[(http://www.4sale.at/templates/classic-theme/fonts/)]

I followed your instructions as I did when successfully adding Fontawesome:

1) Added the ttf file "pe-icon-set-food.ttf" to the iOS "Resources" folder. Changed the build action to "Bundle Resource".

2) Added the following to app.axml:

```
<OnPlatform` 
   x:Key="PixedenFontFamily" 
   x:TypeArguments="x:String"
   Android="pe-icon-set-food.ttf#pe-icon-set-food"
   iOS="pe-icon-set-food" />
```
3) Added the following to the app.xaml base styles section:

```
<Style
   x:Key="Pixeden"
   TargetType="Label">
    <Setter
	Property="FontFamily"
	Value="{ StaticResource PixedenFontFamily }" />
</Style>
```
3. Added cs file "Pixeden.cs" to the Helpers folder and added one icon in the code for testing:

```
namespace mynamespace
{
    class Pixeden
    {
        public const string donut = "\ue97f";      
    }
}
```
I added the iconfont file to the Info.plist file:

```
<key>UIAppFonts</key>
	<array>
		<string>grialshapes.ttf</string>
    <string>special-elite-v8-latin-regular.ttf</string>
    <string>fontawesome-webfont.ttf</string>
    <string>FontAwesomeWebFree-fas900-511.ttf</string>
    **<string>pe-icon-set-food.ttf</string>**
	</array>
```

The problem:

I can render the sample donut icon in a label like this:

```
<Label
	VerticalTextAlignment="Center"
	HorizontalTextAlignment="Center"
	**Text="{ x:Static local:Pixeden.donut }"
	FontFamily="{ StaticResource PixedenFontFamily }">**
	<Label.FontSize>
        <OnIdiom
	x:TypeArguments="x:Double"
	Phone="15"
	Tablet="20" />
	</Label.FontSize> 
</Label>
```
But I cannot load the icon within a tile:

```
private void LoadData()
		{
			DashboardPairMultipleTilesList = new List<DashboardPairMultipleTileItem> 
			{
				
				new DashboardPairMultipleTileItem
				{
					Title = DataResources.DashboardPairMultipleTileItem2Title,
					Body = "",
					Avatar = "",
					BackgroundColor = "transparent",
					ShowBackgroundColor = false,
					IsNotification = false,
					BackgroundImage = "Tiles/DarkBlackTile.jpg",
                                        **Icon = Pixeden.donut,**
					Badge = 2 }
                         }
              }
```

Any idea what I am doing wrong?

Many thanks,

Mark

**Comment by upskydownshoes** [comment]
Hi JP all's well thanks, great summer in the UK for once! Actually got hot!

Thanks again for the help.

The problem is that I am using two icon fonts in the dashboard, so if I add another to the XAML template, it'll throw a duplicate FontFamily error. I tried adding a new variable called FontFamily to the cs code behind file of DashboardPairMultipleTileItemViewModel like so:

```
 public class DashboardPairMultipleTileItem
    {
        public string Title { get; set; }
        public string Body { get; set; }
        public string Avatar { get; set; }
        public string BackgroundColor { get; set; }
        public string BackgroundImage { get; set; }
        public bool ShowBackgroundColor { get; set; }
        public bool IsNotification { get; set; }
        public string Icon { get; set; }
        public int Badge { get; set; }
        **public string FontFamily { get; set; }**
        public string NavigPage { get; set; }
```

And then reference the FontFamily in the Tile I wanted to display the icon in, like so:

```
new DashboardPairMultipleTileItem
				{
					Title = DataResources.DashboardPairMultipleTileItem2Title,
					Body = "",
					Avatar = "",
					BackgroundColor = "transparent",
					ShowBackgroundColor = false,
					IsNotification = false,
					BackgroundImage = "Tiles/DarkBlackTile.jpg",
                                       **FontFamily = "{StaticResource PixedenFontFamily}",
                                       Icon = Pixeden.donut,**
					Badge = 2,
                    NavigPage= "LayBottlesDown"
                    
                },
```

But no joy....

Have I misunderstood maybe?

Cheers,

Mark

**Comment by dirivero** [comment]
Hi! The problem with that solution is that StaticResource is interpreted as a string so it's not resolved against the proper resource.

Instad, you can include a boolean property **UsePixedenFont** to theview model and convert its value to the resource from the xaml with a converter like this:

First include this namespace in the file:

```
xmlns:converters="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared.Base"
```

Then define this converter in the resources:

```
<converters:BooleanToObjectConverter 
    x:Key="FontConverter"
    x:TypeArguments="x:String"
    FalseValue="{StaticResource IconFontFamily}"
    TrueValue="{StaticResource PixedenFontFamily}" />
```

And finally bind the FontFamily in the Xaml like this:

```
FontFamily="{Binding UsePixedenFont, Converter={StaticResource FontConverter}}"	
```

Hope this helps.
Diego

**Comment by upskydownshoes** [comment]
That's great Diego, thanks very much!
