### ISSUE TITLE
When incorporated into existing projects, modify MyAppTheme.Xaml document AccentColor, build when no update to Colors.xml.why?

### ISSUE THREAD

**Issue by 15937823** [UXDivers/Grial-UI-Kit-Support#480]
When incorporated into existing projects, modify MyAppTheme.Xaml document AccentColor, build when no update to Colors.xml.why?

**Comment by jpbrocca** [comment]
Hi @15937823,

Most probably you need to configure the theme synchronization in your project:

http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-theme-and-branding-of-your-app-advanced-theme-synchronization-configuration

Regards,
JP

**Comment by 15937823** [comment]
I compared the two projects and found that my project was colors.xml, but the file name should be Colors.xml
thank's!@JP
