### ISSUE TITLE
back button does not appear in IOS 11.00

### ISSUE THREAD

**Issue by arthurmoreiraSD** [UXDivers/Grial-UI-Kit-Support#481]
Hello
The return button was working correctly after an IOS upgrade to version 11.00. He stopped appearing, do you know how to solve this problem?

**Comment by jpbrocca** [comment]
Hi @arthurmoreiraSD,

Which version of Grial are you using?
If you are not using latest please check this thread:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/254

Best,
JP

**Comment by arthurmoreiraSD** [comment]
Hello,

Solved problem.
Thank you.

**Comment by arthurmoreiraSD** [comment]
Hello,

Solved problem.
Thank you.
