### ISSUE TITLE
CWE-327: Use of a Broken or Risky Cryptographic Algorithm on Dlls

### ISSUE THREAD

**Issue by sadranyi** [UXDivers/Grial-UI-Kit-Support#486]
We have developed an insurance app with your kit, and per requirement we needed to perform security scans on the application. after scanning with Veracode, we have the above findings in uxdivers.artina.shared.droid.dll/uxdivers.artina.shared.base.droid.dll. Immediate help in mitigating this issue would be helpful

**Comment by dirivero** [comment]
Hi,
I've sent an email a week ago regarding this issue to Kwame Essieh, who is the only contact we had. Can you write us at hello at uxdivers.com?

**Comment by sadranyi** [comment]
Kwame, has not received any email. I am the technical lead on the project so please send all technical stuff to me instead.

**Comment by dirivero** [comment]
I only have Kwame's email. Can you email me to hello [at] uxdivers.com?

**Comment by sadranyi** [comment]
sure

**Comment by sadranyi** [comment]
sent, samuel.adranyi@eaiinfosys.com

**Comment by dirivero** [comment]
I've just fw the original email to you.
