### ISSUE TITLE
DatePicker in IOS and Android show selected date in wrong format

### ISSUE THREAD

**Issue by mostafasany** [UXDivers/Grial-UI-Kit-Support#488]
### Description
When you open the IOS or Android Datepicker in RTL, Selected date showed in Hijri format but if you open the picker you will see values in Gerogian format

### Steps to Reproduce

1. Switch your device to arabic form Device settings
2.Open Grial UI Kit
3. Go to Native controls section
4.Go to Date pikcer

### Expected Behavior
Both Selected value and values should shown in Gerorgian but with arabic translation

### Actual Behavior
Selected Value showed in Hijri but when you open the picker you will see values in Gerogian

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![issue 2](https://user-images.githubusercontent.com/2448942/45539336-b4108c80-b809-11e8-918c-54eab6df048c.jpg)

**Comment by dirivero** [comment]
Hi,
Form pickers do not support that as far as I know. What you can do is include a simple renderer for each platform and format the displayed text for the selected date manually. I'm sharing the basic code for those renderers:

**iOS**
```
public class ExtendedDatePickerRenderer : UXDivers.Artina.Shared.ArtinaDatePickerRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
    {
        base.OnElementChanged(e);

        UpdateText();
    }

    protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        base.OnElementPropertyChanged(sender, e);

        if (e.PropertyName == DatePicker.DateProperty.PropertyName || e.PropertyName == DatePicker.FormatProperty.PropertyName)
        {
            UpdateText();
        }
    }

    private void UpdateText()
    {
        // Use specific code to format Element.Date:
        Control.Text = Element.Date.ToString(Element.Format);
    }
}
```

**Android**
```
public class ExtendedDatePickerRenderer : UXDivers.Artina.Shared.ArtinaDatePickerRenderer
{
    public ExtendedDatePickerRenderer(Android.Content.Context context)
        : base(context)
    {
    }

    protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
    {
        base.OnElementChanged(e);

        UpdateText();
    }

    protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        base.OnElementPropertyChanged(sender, e);

        if (e.PropertyName == DatePicker.DateProperty.PropertyName || e.PropertyName == DatePicker.FormatProperty.PropertyName)
        {
            UpdateText();
        }
    }

    private void UpdateText()
    {
        // Use specific code to format Element.Date:
        Control.Text = Element.Date.ToString(Element.Format);
    }
}
```
