### ISSUE TITLE
Ecommerce(checkout summary screen)

### ISSUE THREAD

**Issue by bharadwajnanenuganti** [UXDivers/Grial-UI-Kit-Support#489]
I am currently working on Ecommerce in after adding product to cart i dont see any screen for order summary.they have product order screen.Can you please provide the order summary screen.

**Comment by bharadwajnanenuganti** [comment]
![whatsapp image 2018-09-13 at 9 32 33 am](https://user-images.githubusercontent.com/43280772/45571648-e7b4dc00-b834-11e8-923e-806ebb63a8f5.jpeg)

**Comment by bharadwajnanenuganti** [comment]
Please see below screen what i am referring to
<img width="356" alt="screen shot 2018-09-14 at 3 44 01 pm" src="https://user-images.githubusercontent.com/43280772/45571704-1d59c500-b835-11e8-8219-5e1904a2cd31.png">

**Comment by jpbrocca** [comment]
Hi @bharadwajnanenuganti,

This screen is not included in Grial.
Here is a page showing all the screens and templates included in the kit:
https://grialkit.com/screenshots/

In case you need something to extend and/or customize Grial you can hire our custom services team.

Regards,
JP

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
