### ISSUE TITLE
Updating to Grial 1.5

### ISSUE THREAD

**Issue by babernethy** [UXDivers/Grial-UI-Kit-Support#49]
Is there anyone/info that can help with getting the 1.5 update? Have the e-mail. Having difficulty with the code/download.

**Comment by jpbrocca** [comment]
HI @babernethy,

can you send me an email to jpbrocca@uxdivers.com with your order number and explaining what problem you have ?

Thanks,
JP

**Comment by jpbrocca** [comment]
Hi @babernethy I have received your email and you soon will receive the link with the update.
Please close this issue after you get it.

Best,
JP

**Comment by babernethy** [comment]
Thanks for the quick response, and great product - looking forward to 2.0 ...
