### ISSUE TITLE
RoundedLabel in Repeater doesn't Bind Text

### ISSUE THREAD

**Issue by ianvink** [UXDivers/Grial-UI-Kit-Support#490]
When I use a RoundedLabel in a Repeat it fails to render the text, or anything.

When I replace RoundedLabel with a simple Label it works

			<artina:Repeater
				ScrollPadding="10,0"
				ItemsSource="{Binding Customer.ListOfSimpleStrings}"
				Spacing="10">
				<artina:Repeater.ItemTemplate>
					<DataTemplate>
                                         DOES NOTHING
						<max:RoundedLabel RoundedLabelText="{Binding .}" ></max:RoundedLabel>
						<max:RoundedLabel RoundedLabelText="Hi Mom" ></max:RoundedLabel>
                                        WORKS FINE
                                        <Label Text="{Binding .}"></Label>
					</DataTemplate>
				</artina:Repeater.ItemTemplate>
			</artina:Repeater>

**Comment by dirivero** [comment]
Can you share the exact code that doesn't work?

For instance, this code works:
```
<ctlRep:Repeater 
    HeightRequest="100"
    VerticalOptions="Center"
    ItemSize="100"
    ItemsSource="{ Binding Items }">
    <ctlRep:Repeater.ItemTemplate>
        <DataTemplate>
            <Grid Padding="15">
                <local:RoundedLabel RoundedLabelText="{ Binding . }" ></local:RoundedLabel>
            </Grid>
        </DataTemplate>
    </ctlRep:Repeater.ItemTemplate>
</ctlRep:Repeater>
```

It shows this:
<img width="308" alt="screen shot 2018-09-14 at 6 29 49 pm" src="https://user-images.githubusercontent.com/7670773/45576101-37eb6880-b84c-11e8-87fc-e5f8a835fa14.png">

**Comment by ianvink** [comment]
Notice the ItemsSource, a compound binding

		<artina:Repeater
			ScrollPadding="10,0"
			ItemsSource="{Binding Customer.ListOfSimpleStrings}"
			Spacing="10">
			<artina:Repeater.ItemTemplate>
				<DataTemplate>
                                     DOES NOTHING
					<max:RoundedLabel RoundedLabelText="{Binding .}" ></max:RoundedLabel>
				</DataTemplate>
			</artina:Repeater.ItemTemplate>
		</artina:Repeater>

**Comment by dirivero** [comment]
The compound binding should not be a problem. I imagine that `ListOfSimpleStrings` is just a string array/collection property, right?

Does the rounded label render something if you replace the binidng by a fixed text?

**Comment by ianvink** [comment]
When I replace the Rounded Label with a Label the label renders. I tried setting the background color of the Rounded Label so I could see if the control renders and it's not visible.

     <Label Text="{Binding .}"></Label>

But it's not a binding issue I think it is the Repeater. When I place the Rounded Label outside the Repeater it renders fine.

The problem seems to be a Rounded Label inside a Repeater.

Label in a Repeater works
RoundedLabel outside a Repeater works.

The Repeaters is in a View Cell of a ListView. I am showing a list of "Tags"

**Comment by dirivero** [comment]
Can you try setting `ItemSize="100"`to the repeater and `RoundedLabelBackgroundColor="Red"` to the rounded label?

**Comment by ianvink** [comment]
<?xml version="1.0" encoding="UTF-8"?>
    <ViewCell xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared.Repeater"
             xmlns:effects="clr-namespace:UXDivers.Effects;assembly=UXDivers.Effects"
             xmlns:max="clr-namespace:Max;assembly=Max"
             x:Class="Max.Views.Common.ListViewCells.TextListViewCell">
      <ViewCell.View>
		<StackLayout  Orientation="Vertical" Padding="10">
			<Label Text="{Binding Title}" Style="{StaticResource LabelNoteStyle}"></Label>
 
			<artina:Repeater
				ScrollPadding="10,0"
				ItemSize="100"
				ItemsSource="{Binding Value.TextList}"
				Spacing="10">
				<artina:Repeater.ItemTemplate>
					<DataTemplate>
						<max:RoundedLabel RoundedLabelText="{Binding .}" BackgroundColor="Red"></max:RoundedLabel>
					</DataTemplate>
				</artina:Repeater.ItemTemplate>
			</artina:Repeater>
		</StackLayout>
      </ViewCell.View>
    </ViewCell>

**Comment by ianvink** [comment]
Blank result. Just the Header Label with Title appears

**Comment by dirivero** [comment]
Ohh, I see the problem now. The repeater doesn't have a Height and it's inside a vertical stack layout so it doesn't grow. Try adding `HeightRequest="100"` to it and it should display something.

Note that the `ItemSize` property defines the dimension of the elements in the repeater's orientation, in this case it's horizontal (by default) so it defines the element's width.

**Comment by ianvink** [comment]
BINGO! Thanks for your awesome help.
