### ISSUE TITLE
how to add ZGorilla SDk?

### ISSUE THREAD

**Issue by Sam0555** [UXDivers/Grial-UI-Kit-Support#491]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LeoHere** [comment]
@Sam0555 You just need to download Gorilla Ready version of Grial. The SDK is included and configured in the downloaded solution.

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
