### ISSUE TITLE
Licence expired issue

### ISSUE THREAD

**Issue by flippinloud** [UXDivers/Grial-UI-Kit-Support#492]
Hello.
We face the problem: if licence is expired, all applications become crashed, no matter when it was built or installed. So is it correct, that for now to make application work we should update application at least one time per month? Or can we solve it another way?

With best regards.

**Comment by LeoHere** [comment]
Hi @flippinloud, please review [this section](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-license-modes) of the documentation where the two available license modes are explained.

Please let us know if you have any further question.

**Comment by flippinloud** [comment]
Could you please explain which restrictions production mode license has? We won't be able to change solution settings for license? Or some more restrictions are included?

**Comment by LeoHere** [comment]
@flippinloud after you move to production you can't change app settings in the Grial Admin any more. Therefore your license gets permanently tied to the AppName/Bundle Identifier you have once you move to production mode. And it never expires. That's it.

If for some reason you have an issue after moving to production, e.g. you discover that the name of your app has trademark issues and you need to change it, you can contact us and we will help you changing it. 

Let me know if you have any other question.

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
