### ISSUE TITLE
License verification fails on android only 

### ISSUE THREAD

**Issue by jgtaveras** [UXDivers/Grial-UI-Kit-Support#493]
### Description

The default starter example provided to my app it's failing on android due to license verification. I double check that the package name and application name matches what i have no the admin portal, and as the title suggest this is only on android, ios is working fine

```
[AndroidRuntime] android.runtime.JavaProxyThrowable: UXDivers.Artina.Shared.LicenseException: License verification failed because: The PackageName does not match the license's. 
[AndroidRuntime]   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x0007e] in <8b212ba4031a48888b2aad27bb893fee>:0 
[AndroidRuntime]   at UXDivers.Artina.Shared.GrialKit.Init (Android.App.Activity activity, System.String licenseResourceName) [0x0000b] in <dc92a29277ef4d98bd8ae97a30a82316>:0 
[AndroidRuntime]   at Nyoobe.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00045] in <b734af6afa5a46648da3ee5c07f33a04>:0 
[AndroidRuntime]   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
[AndroidRuntime]   at (wrapper dynamic-method) System.Object.7(intptr,intptr,intptr)
[AndroidRuntime] 	at md5915aac193eab89b5b54b28c47972933c.MainActivity.n_onCreate(Native Method)
[AndroidRuntime] 	at md5915aac193eab89b5b54b28c47972933c.MainActivity.onCreate(MainActivity.java:30)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:6999)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:6990)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
[AndroidRuntime] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
[AndroidRuntime] 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Steps to Reproduce
1. Mark the app as Production
2.  Download starter kit 
3. Run the android version on a physical device

### Expected Behavior
App should go pass the splash screen

### Actual Behavior
App crash due to a license verification error.

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android: Target SDK -> Automatic -> API 28
- Android Support Library Version: 25.4.0.2

**Comment by LeoHere** [comment]
Hi @jgtaveras

What is your current package name?

Does the package name have a dot (".") somewhere? If it doesn't, please see #276.

**Comment by jgtaveras** [comment]
it does and a hyphen dunno if that's the error here(package name: com.my-xxxx.nyyyy)

**Comment by LeoHere** [comment]
The problem seems to be that the package name can't have an hyphen. If you set the package name to `com.my-xxxx.nyyyy` in the `AndroidManifest.xaml` (as it is now), then at runtime if you query it you get `com.my_xxxx.nyyyy`. That is why you are getting an error. 

My recommendation would be to change the package name to `com.my_xxxx.nyyyy`.

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.

**Comment by jgtaveras** [comment]
sorry for not replying over here, that did the trick thanks
