### ISSUE TITLE
Access to Gorilla disappears on Visual Studio Update 15.8.5

### ISSUE THREAD

**Issue by upskydownshoes** [UXDivers/Grial-UI-Kit-Support#494]
Hi guys, hope all's well!  

Updated to Visual Studio 15.8.5 yesterday, Gorilla Player has disappeared from Tools > Gorilla > (follow me, stick to this XML etc).

Tried reinstalling Gorilla Player 1.2.2.0.

Tried unloading and reloading Gorilla package using Nuget, nothing happened.

I can still run project in Debug > IphoneSimulator, it appears on remote Mac fine.

I can still run project on simulator with Gorilla > iPhoneSimulator, it appears on remote Mac, but can't follow any of the XAML files as Gorilla not present in tools.

The following is from Nuget in dependencies: 

> Package 'UXDivers.GorillaPlayer.Common 0.9.1.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Cheers,

Mark

**Comment by LeoHere** [comment]
@upskydownshoes please write me to l r o d r i g u e z at uxdivers.com. I will share with you the development version which fixes this.

**Comment by upskydownshoes** [comment]
Fixing problem was embarrassingly simple…

I went into VS -> Tools -> Extensions and updates -> Tools and enabled the Gorilla Player Visual Studio Addin.

Updating VS obviously disabled that addin.

My apologies.
