### ISSUE TITLE
Getting xaml parse exception

### ISSUE THREAD

**Issue by ricavir11** [UXDivers/Grial-UI-Kit-Support#496]
I'm trying to add grial to an existing project.
I've followed your documentation for this.
I'm getting an error on InitializeComponent of App.xaml.cs : 

Xamarin.Forms.Xaml.XamlParseException: Position 87:11. Can't resolve OnColorProperty on Switch

I've removed all views from existing project and added only grial view WelcomeStarterPage.

Any idea how to fix that ?

**Comment by jpbrocca** [comment]
Hi @ricavir11,
which version of Xamarin Forms are you using?
XF support for OnColor on Switch control started on version 3.1.

Regards,
JP

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
