### ISSUE TITLE
Nuget lottie package

### ISSUE THREAD

**Issue by AntoT84** [UXDivers/Grial-UI-Kit-Support#498]
Hi,
I'm new with GrailUiKit and I've got an issue with the Com.Airbnb.Xamarin.Forms.Lottie package.

This alert is displayed on the package console:

Package 'Com.Airbnb.Xamarin.Forms.Lottie 2.4.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

This could couse same problems?

Thanks.

**Comment by jpbrocca** [comment]
Hi @AntoT84,

Go ahead with the package. It should not cause issues.

Best,
JP

P.S: I am closing this issue to keep things tidy. Feel free to reopen if needed.
