### ISSUE TITLE
Add Windows Phone support

### ISSUE THREAD

**Issue by Laumania** [UXDivers/Grial-UI-Kit-Support#5]
We are many people who want Windows Phone support, it is after all the smartphone platform of tomorrow ;)

**Comment by Laumania** [comment]
@nodoid I was told you had interest in Windows Phone too?
Have you made Grial run on Windows Phone, with the current release that doesn't support Windows Phone officially?

**Comment by nodoid** [comment]
I have a lot of interest on getting this to run on Windows Phone and am working with the guys on making this a reality. Currently, you can get it to "kind of" run, but it is messy and I'd not advise it

**Comment by Laumania** [comment]
Ok, fair enough. My guess would be that I could do my own renderers - but I would like not too - as I guess the Grial team is doing exactly the same too :P
But it could still be a solution, if it is possible, depending on how many of the "Grial" controls I'm using...I don't know that right now as I haven't looked into it.

Really I was just fishing for some tricks about how to make it work if you had any, but guess the best advice is to wait - currently.

**Comment by dirivero** [comment]
Closing this old issue as Windows Phone was discontinued.
