### ISSUE TITLE
Adding Grial to a new project

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#50]
Greetings,
The tutorial [here ](https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Creating-a-new-project-using-Grial) makes mention of UXdivers.Artina.Grial.Droid.dll.  However, when I purchased the license, the download does not contain this file anywhere.  There is a dll named UXdivers.Artina.Shared.Droid.  The dlls with 'shared' in the name are used in the sample project.  Should these be used instead?

Also, when I add the required Android files to a new project as shown  [here](https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files#android) the project has errors in the resource.designer file 

How do you go about adding a view?

**Comment by jpbrocca** [comment]
Hi @attrib75,

We are updating our documentation so probably this could be something that should be updated.
@LeoHere can you confirm ?

We recently released an update of the product (Grial 1.5 with support for AppCompatV7)...are you using this version on your project ?

We are also working on making the setup of a new project much easier if you write me an email to jpbrocca@uxdivers.com I can send you a starter project which will provide a basic setup showing all what you need to start.

Best regards,
JP

**Comment by LeoHere** [comment]
Hi,
The references to `UXDivers.Artina.Grial*.dll` done in the "Basic project setup" were wrong. They all should refer to `UXDivers.Artina.Shared*.dll` (I have just fixed that)

In the section "Addin pages and templates to your project" you will see that `UXDivers.Artina.Grial` is mentioned too. That one is right. `UXDivers.Artina.Grial` is the output assembly of the Grial project (the one under samples). When you move views to your own project, since the project assembly name would change you need to do as explained there.

Hope it helps.

**Comment by attrib75** [comment]
Ok gotcha.  Thanks for responding.  Yeah the set up is impossible.  The first time I downloaded the sample I got it working. Then I screwed it up and downloaded it again.  (should have copied it first I know).  Now the sample doesn't even build.  There's like 1700 errors.  Good times.  I've been pulling my hair out.

**Comment by attrib75** [comment]
Let me amend that.  I deleted the folders in c:\users\<user>\appdata\local\low\xamarin and the sample works.  I'll still email you for the starter project, as I need to get this going for a client.  Thanks!

**Comment by jpbrocca** [comment]
Hi @attrib75 let me know if I can close this issue since I already sent you the starter project.

Best,
JP

**Comment by attrib75** [comment]
Sure thing, thanks!
