### ISSUE TITLE
XAMarin.Forms v3.3.0.9521 issues with iOS License File

### ISSUE THREAD

**Issue by RecipeSavants** [UXDivers/Grial-UI-Kit-Support#500]
I have just started getting license issues in my iOS project - I am getting the following exception - GrialKit.Init(new ThemeColors(), "RecipeSavants.Mobile.iOS.GrialLicense");

I have downloaded the new license, clean and rebuilt - the bundle name looks right to me -- here it is in my solution and in the grial portal - anything I might have mucked up?

This is blocking my development please let me know what I can do to resolve it
<img width="655" alt="screen shot 2018-10-26 at 8 37 30 am" src="https://user-images.githubusercontent.com/32582201/47569943-82a3da00-d8fa-11e8-8793-fe523a8cd9a0.png">
<img width="923" alt="screen shot 2018-10-26 at 8 37 56 am" src="https://user-images.githubusercontent.com/32582201/47569944-82a3da00-d8fa-11e8-98e2-949c71ac34e2.png">

**Comment by RecipeSavants** [comment]
here is the code in the app.delegeate  
<img width="923" alt="screen shot 2018-10-26 at 10 05 55 am" src="https://user-images.githubusercontent.com/32582201/47575045-c13f9180-d906-11e8-9772-0e784b4121d6.png">

**Comment by RecipeSavants** [comment]
I have rolled back Xamarin forms as well -- but it is still causing this issue - but the same exact license file works in the android version

**Comment by jpbrocca** [comment]
Hi @RecipeSavants, how are you?

Did you check the license troubleshooting section on Grial docs?
http://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-grial-first-run-troubleshooting-license-issues

If your issue is not there, then, could you paste the full exception you are getting so we can get an idea about what it could be?

Regards,
JP

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
