### ISSUE TITLE
WalkthroughStepItemTemplate Header is not fully bindable

### ISSUE THREAD

**Issue by RocketPop** [UXDivers/Grial-UI-Kit-Support#502]
### Description

The WalkthroughStepItemTemplate.xaml.cs implementation has a property for the header, but it never sets the property into the xaml controls. This is confusing, since the sample WalkthroughPage.xaml does bind a string to the Header, but it never displays on the view. The "Flat" and "Variant" versions do not have this bug.

### Steps to Reproduce

1.  Open up the Walkthrough sample
2. Notice every header says "Learn"
3. Attempt to change the header text in the walkthrough xaml file and it will not update

### Expected Behavior

The values set in the WalkthroughPage.xaml should be respected

### Actual Behavior

The default value hard-coded in the template .xaml is used instead 

### Basic Information

- Version with issue: 2.7
- Last known good version: unknown
- IDE: Visual Studio 2017 Enterprise
- Platform Target Frameworks:  n/a
- Affected Devices: all

### Workaround/Fix
Within WalkthroughStepItemTemplate.xaml.cs, simply  update the Header Bindable property and ensure it has a propertyChanged() action as per the TextProperty above it does. Also, provide a name in the template .xaml such as x:name="HeaderLabel" or some-such. This will now allow the walkthrough items to bind to the header.

**Comment by RocketPop** [comment]
Also (related) on line 75 of  ...\Views\Walkthroughs\Templates\WalkthroughStepItemTemplate.xaml the opacity is "0,7" which is invalid - should be "0.7"

**Comment by jpbrocca** [comment]
Hi @RocketPop, thanks for taking the time to this bug in detail :)

I confirm this is a bug on our end (actually 2 as you pointed).
What you proposed as the workaround is the right way.

Thanks a lot!
JP

**Comment by dirivero** [comment]
Both things were fixed in latest Grial versions. We did this through XAML directly:

```Text="{ Binding Source={x:Reference Root}, Path=Header }"```

being "Root" the the x:Name of the root element.

Thanks again.
