### ISSUE TITLE
Hide status bar only in splash screen

### ISSUE THREAD

**Issue by ignacioinnovo** [UXDivers/Grial-UI-Kit-Support#505]
Dear Grial UI Kit Team,

I was trying to hide the status bar only in splash screen (Android and iOS). I saw that we need a Dependency Service as shown here: https://stackoverflow.com/questions/36449480/hide-statusbar-for-specific-contentpage/36451267#36451267

Is there any "Grial way" to achieve the same?

Thank you in advanced!

**Comment by jpbrocca** [comment]
Hi @ignacioinnovo, how are you?

No, we don't have any "Grial way" to achieve that :)
The page renderer solution mentioned on the link seems to be a good option.

Regards,
JP

**Comment by LeoHere** [comment]
Closing the issue to keep things tidy. Please reopen it again if you need to.
