### ISSUE TITLE
TabControlCustom showing strange Badges without numbers only in Android

### ISSUE THREAD

**Issue by Fatihpk** [UXDivers/Grial-UI-Kit-Support#506]
Want to work with the TabControlCustom and everything works fine but when i run it on a iOS all works fine but in Android this shows as init:

![screenshot](https://user-images.githubusercontent.com/20399409/49655371-caaa3680-fa3a-11e8-9050-806db907af9a.jpg)

Very strange:

Using: 

- Visual Studio's 2017
- UXDivers.Artina 2.7.5
- Xamarin.Forms 3.4.0.1008975

**Comment by jpbrocca** [comment]
Hi @Fatihpk,
Can you provide more details about your devices such as:

- is it an Android device or emulator?
- Android API?
- Do you get the same result if you try the Grial demo app from Google Play?

Thanks,
JP

**Comment by Fatihpk** [comment]
Your Grial Demo works fine on the Android device. It does the same on the normal device as in the emulator. I copy the TabControlCustom from the new version the my old version and get this The strange part is that it works fine in iOS.

**Comment by jpbrocca** [comment]
Hmmm...just a checklist to see if maybe something is missing:
- Did you make sure you have the right package version on your Android project?
- Did you make sure you copied all the resources?
- Just in case try: 
  - uninstalling the app on your device
  - close VS
  - remove all obj/bin folders from your solution
  - open solution on VS
  - run again

If all the above fails I am not sure what could you be missing but most probably is the packages version or some missing resources.

Regards,
JP

**Comment by Fatihpk** [comment]
Hi @jpbrocca thanx for response. 

How do I copy the package versions from the latest version the old version (100%).

**Comment by Fatihpk** [comment]
Did this:

Just in case try:

    uninstalling the app on your device
    close VS
    remove all obj/bin folders from your solution
    open solution on VS
    run again

But did not work! 

How do i copy ALL the resources save from the new version to my old version!

@jpbrocca

**Comment by jpbrocca** [comment]
You can download 2 projects from Grial Admin:

1. A Grial Full sample with your old version
2. A Grial Full sample with new version

Then, you should compare both with a diff tool such as [diffmerge](https://sourcegear.com/diffmerge/) which allows performing a folder diff. That way you will see the differences between both.

https://sourcegear.com/images/screenshots/diffmerge/img_folder_window_1.png

Best,
JP

**Comment by Fatihpk** [comment]
Hi @jpbrocca are there other resources that we need to copy and replace the new ones. I already downloaded the latest version with the nuget packages.

**Comment by Fatihpk** [comment]
Still not working. Try everything! Where do you find all resource files for the template @jpbrocca ?

**Comment by Fatihpk** [comment]
Change files copy resource files and suddenly my iOS also does the same :@

@jpbrocca does the Tabbpage refer to some style in files?


![screenshot](https://user-images.githubusercontent.com/20399409/49926375-b42d3080-febb-11e8-9ee7-e9c2ad1ebc7b.jpg)

**Comment by jpbrocca** [comment]
Hi @Fatihpk,
if you follow the procedure from my previous message you will get a list with all the files you need to make sure to add to your latest project.

The sample uses the `TabControlCustomResources.xaml` file

(/Views/Theme/Resources/**TabControlCustomResources.xaml**)

You need to make sure to use the latest version of it and its dependencies (i.e: `Badge`). 
Most probably you need to update the `Badge.xaml.cs` and `Badge.xaml.cs` files.

**Comment by Fatihpk** [comment]
Hi @jpbrocca Changing the Badge.xaml.cs file did the trick. Everything looks fine now in Android and iOS. And i am very happy :)
