### ISSUE TITLE
Icon not working on button

### ISSUE THREAD

**Issue by gihanfonseka** [UXDivers/Grial-UI-Kit-Support#508]
![image](https://user-images.githubusercontent.com/1900722/49954726-17748e00-fecf-11e8-9fb4-59a5994ee1b3.png)

Have tried to apply an icon to a button.  if you look at the image, the icon in label works but the one in the button is not.  Code is in the screenshot.

**Comment by LeoHere** [comment]
@gihanfonseka I can't reproduce the issue.

I just get the Grial Sample app and replicate your code in the `CustomRenderersPage.xaml` as follows:

~~~
<artina:Button 
    WidthRequest="48" 
    HeightRequest="48"
    BorderRadius="24"
    FontSize="26"
    BorderWidth="1"
    Text="{ x:Static local:IonicIconsFont.Calendar }" 
    FontFamily="{ StaticResource IconsFontFamily }"
>
    <artina:Button.BorderColor>
        <OnPlatform x:TypeArguments="Color" Android="Black" iOS="#0076FF" /> 
    </artina:Button.BorderColor>
</artina:Button>

<Label 
    Text="{ x:Static local:IonicIconsFont.Calendar }" 
    FontFamily="{ StaticResource IconsFontFamily }"
/>
~~~

Additionally I needed to:
- declare the font in the info.plist
- set it as BundleResource
- change the IconFontFamily to use Ionic

![image](https://user-images.githubusercontent.com/16000584/50114880-83832900-0224-11e9-8254-5088765af780.png)

Are you testing this over your own solution or the solution downloaded from the Grial Admin?
Can you try with the code above?

**Comment by gihanfonseka** [comment]
We're testing this on Android.  Will try your code and get back.

**Comment by gihanfonseka** [comment]
Yea we tested android its not working there but it's working on iOS

**Comment by schnabs** [comment]
We updated our App.xaml to get this working

From (which I think is from an older Grial sample solution):

<x:String x:Key="IconsFontFamily">Ionicons</x:String>

To This (which is from the current Griald sample solution):

<OnPlatform
    x:Key="IconsFontFamily" x:TypeArguments="x:String"
    Android="ionicons.ttf#Ionicons"
    iOS="Ionicons"
/>

First works on Android Labels, and second works on Android Labels & Buttons. 
This can be closed. Thanks!
