### ISSUE TITLE
GridOptionsView Badge

### ISSUE THREAD

**Issue by JDOUKIS** [UXDivers/Grial-UI-Kit-Support#510]
Any suggestions (or feature add-in) on how to refresh the Badge value (the little numeric label that appears over a Dashboard Category?).

I need to be able to change it's value on the fly, when a background running process completes.

Thanks in advance for any help.

**Comment by LeoHere** [comment]
@JDOUKIS If the badge is bound to a view model you just need to update the badge number in the view model as soon as the process completes.
