### ISSUE TITLE
License verification failed because: The application display name does not match the license's. 

### ISSUE THREAD

**Issue by mostafasany** [UXDivers/Grial-UI-Kit-Support#513]
Adding new generated licenses key on IOS throw this exception 
License verification failed because: The application display name does not match the license's. 

### Steps to Reproduce
I have checked the followings:
1. Bundle Identifier in the Grial App Matches the bundle identifier in InfoPlist
2-CFBundleDisplayName in infoplist.strings in all resoureces matches name of app name in Grial App

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LeoHere** [comment]
@mostafasany 

1. Did you tried removing the app from the device/simulator + clean and then redeploy the app again? Sometimes Xamarin build process missed changes done to embedded resources and don't deploy them again.
2. Are you sure you are using the correct Grial License file? It might worth double checking the name in the Admin and the app match + downloading the license file again and replace it in your solution. After doing so please do 1, to be sure it gets updated.

**Comment by mostafasany** [comment]
@LeoHere 
I check all of these, is the solution and project name should match the one in Grial Apps?

**Comment by LeoHere** [comment]
@mostafasany no project name and solution name can defer. [This](https://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-grial-first-run-license-verification) section of the doc explains what license verification check.

**Comment by mostafasany** [comment]
Yes i check this document but still have the same problem , is there anyway to send a sample project has the issue ?

**Comment by LeoHere** [comment]
@mostafasany sure. Send it to me l r o d r i g u e z at uxdivers.com

**Comment by mostafasany** [comment]
@LeoHere  i found that CFBundleDisplayName wasn't changed as it doesn't appear in the info.plist in Visual studio  i had to open it with Xcode, 
Thanks for your help :)
