### ISSUE TITLE
How to handle event CardsListItem taped

### ISSUE THREAD

**Issue by anhtuan0030** [UXDivers/Grial-UI-Kit-Support#514]
### How to know exactly with card to taped, in demo app it only shows a alert like code bellow

_public async void OnCardTapped(object sender, EventArgs args)
 {
            await Application.Current.MainPage.DisplayAlert("Card Tapped!", "You have tapped a Card", "OK");
 }_

Please help me. Tks!

**Comment by LeoHere** [comment]
@anhtuan0030 the `DashboardCardsPage` uses the `GridOptionsView` control. You can use the `ItemClickCommand` of the `DashboardCardsPage` to achieve what you want. Please check #207 for an example of how to use it.
