### ISSUE TITLE
i need page in pro design 

### ISSUE THREAD

**Issue by musab-alrmmah** [UXDivers/Grial-UI-Kit-Support#521]
![img_8705](https://user-images.githubusercontent.com/17981288/52302040-188cdd80-299d-11e9-9248-314865f0f16e.jpg)

i need design this page i doesn't found this

**Comment by musab-alrmmah** [comment]
How do we create a bigger center UITabBar Item

![o7tka](https://user-images.githubusercontent.com/17981288/52306956-58a68d00-29aa-11e9-9da6-928f853141d2.png)

**Comment by dirivero** [comment]
I would adjust the styles from `CustomTabResources.xaml` resource dictionary (the styles from the first image). 
You can play with the `IconTextFontSize` property on the `TabItem` to differentiate the central tab from the others.
