### ISSUE TITLE
Error when trying to build for actual iphone "Can't resolve reference"

### ISSUE THREAD

**Issue by Glomby** [UXDivers/Grial-UI-Kit-Support#522]
Building and running the App on an simulated iPhone works for but when I try to deploy it on an actual iPhone I get the following error:

> `Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

	
`All the nuget packages are up to date. I'm kind of thinking I might actually have to downgrade something.

**Comment by Glomby** [comment]
My initial thought turned out to be correct. I started downgrading my Xamarin.Forms Version until it ended up working properly. The Version I ended up with is 3.1.69

**Comment by kberawala** [comment]
I dont have an option to downgrade, any other resolution ?

**Comment by Glomby** [comment]
You can deinstall the packages (especially Xamarin.Forms) and then install Version 3.1.69 manually. Thats how Id did it.

**Comment by emipasat** [comment]
This issue should stay open, for us is not an option to downgrade.

**Comment by jpbrocca** [comment]
Hi @emipasat,

Could you please send an email to hello@uxdivers.com with your order number and the email address registered when you purchased Grial? That way we can check your version and try to reproduce your issue.

Regards and thanks,
JP

**Comment by emipasat** [comment]
Email sent. There is no version to check anyway, just try to build for iOS device, with latest prerelease of xamarin.forms.

**Comment by dirivero** [comment]
@Glomby, your exception should not happen anymore after the Xamarin.Forms team fixes this issue labeled as regression/blocker/critical (I guess it will be soon):
https://github.com/xamarin/Xamarin.Forms/issues/5278
