### ISSUE TITLE
TabControl / TabItem label alignment bug

### ISSUE THREAD

**Issue by ahmedmehanna-greenfinch** [UXDivers/Grial-UI-Kit-Support#523]
There is a bug with the TabControl / TabItem, when you navigate away and come back, the label is aligned to the left instead of the middle, I attached a gif:

### Expected Behavior
the label should be aligned to the center

### Actual Behavior
the label should be aligned to the left

### Basic Information

- Grial version: 2.7.5
- Xamarin Forms version: 3.2.0.871581

This issue happens on below devices

- Android Emulator
- OnePlus 6t
- Xiaomi Mi A2 Lite

### Screenshots
![tabcontrol issue](https://user-images.githubusercontent.com/38100336/52426659-45083d00-2af6-11e9-9c5b-bf0fc3521eb8.gif)

**Comment by ahmedmehanna-greenfinch** [comment]
I had chatting with one of the Grial's team support and we fixed this issue by
replace 
```
<Setter Property="HorizontalTextAlignment" Value="Center" />
<Setter Property="VerticalTextAlignment" Value="Center" />
```
with 
```
<Setter Property="HorizontalOptions" Value="Center" />
```

**Comment by jpbrocca** [comment]
Just to clarify: those were the styles used by the texts in the TabControlItemTemplate.
This is a safe workaround but it happens due to a bug in Xamarin Forms.
