### ISSUE TITLE
CardsList's shadow doesn't look same on Android and iOS

### ISSUE THREAD

**Issue by ahmedmehanna-greenfinch** [UXDivers/Grial-UI-Kit-Support#525]
I implemented the CardsList design for xamarin, but after testing i found that shadow for card is working only on Android not for iOS
### Steps to Reproduce
1. Use the same code for CardsList
2. Run app on iOS , the shadow doesn't appear.
3. Run app on Android , the shadow appears.

```
<!-- CARDS -->
            <OnPlatform x:TypeArguments="x:Double" 
                        x:Key="CardViewCornerRadius"
                        Android="4"
                        iOS="4" />
```
```
<Style x:Key="CardViewStyle" TargetType="VisualElement">
                <Setter Property="effects:Effects.CornerRadius" Value="{ StaticResource CardViewCornerRadius }" />
                <Setter Property="effects:Effects.Shadow" Value="True" />
                <Setter Property="effects:Effects.ShadowSize" Value="5" />
                <Setter Property="effects:Effects.ShadowIOSColor" Value="#77000000" />
            </Style>
```
```
<Grid Style="{ StaticResource CardViewStyle }"
	  BackgroundColor="{ DynamicResource BasePageColor }"
          ColumnSpacing="10"
          RowSpacing="1"
          Margin="10,5,10,5"
          HeightRequest="65">
        
    </Grid>
```
### iOS
![ios](https://user-images.githubusercontent.com/38100336/52788145-f6a7f080-3057-11e9-8c1c-46b3d926a6fc.PNG)

### Android
![android](https://user-images.githubusercontent.com/38100336/52788285-57cfc400-3058-11e9-8cd6-51df10f4a0db.jpg)

**Comment by jpbrocca** [comment]
Hi @ahmedmehanna-greenfinch, how are you?

There are some minor differences in the way Android and iOS platforms render the shadows, but you should see at least something in iOS.

A couple of questions:
- Which version of Xamarin Forms are you using?
- Do you get the same results if you run Grial Full sample on your iOS device? (CardsListPage.xaml).

Regards, 
JP

**Comment by ahmedmehanna-greenfinch** [comment]
Hi @jpbrocca 

Grial version: 2.7.5
Xamarin Forms version: 3.2.0.871581

I tried to run Grial Full sample on iOS device? I couldn't see the shadow also

**Comment by dirivero** [comment]
The problem is that the CornerRadius effect in iOS clips the iOS shadow. To fix it, you can include a new Grid wrapping everything and apply the shadow to it, while keeping the CornerRadius in the original Grid.

It would be like this:
a) In the App.xaml remove the CornerRadius effect from the `CardViewStyle`, this line:
 ```
<Setter Property="effects:Effects.CornerRadius" Value="{ StaticResource CardViewCornerRadius }" />
```
b) In the item template add a new Grid outside everything, as the root of the ContentView:
```
<Grid>
    <Grid.Style>
        <OnPlatform x:TypeArguments="Style" iOS="{ StaticResource CardViewStyle }" />
    </Grid.Style>
        
    <Grid
        effects:Effects.CornerRadius="{ StaticResource CardViewCornerRadius }"
        BackgroundColor="{ DynamicResource BasePageColor }"
        ColumnSpacing="10"
        RowSpacing="1"
        Margin="10,5,10,5"
        HeightRequest="65">
        <Grid.Style>
            <OnPlatform x:TypeArguments="Style" Android="{ StaticResource CardViewStyle }" />
        </Grid.Style>

            ...
```
In Android, as you can see, the Style is kept in the original Grid through an OnPlatform. This is because we don't want the shadow to include a dead area around in Android due to `Margin="10,5,10,5"`. In iOS this is not a problem because the shadow only applies to non transparent pixels.

**Comment by ahmedmehanna-greenfinch** [comment]
@dirivero 
Thank you so much, this solution is working so good.

Just little bit issue.
In below comparison Image between iOS and Android, I found that iOS has more shadow around the Grid.
Is there any solution for this behaviour?

![untitled](https://user-images.githubusercontent.com/38100336/52818212-05b19180-309e-11e9-97f1-e689ce564da4.png)

**Comment by jpbrocca** [comment]
Hi @ahmedmehanna-greenfinch,

Yes, you could use `OnPlatform` to specify your shadow only in iOS through the property `effects:Effects.ShadowSize`.

Additionally, you could adjust the value of `effects:Effects.ShadowIOSColor` to make it look lighter/darker to suit your needs.

Let me know if you need more help.

Regards,
JP

**Comment by ahmedmehanna-greenfinch** [comment]
@jpbrocca Thank you so much. Thank you for all your team.
