### ISSUE TITLE
XF 3.5.0 crashes when TabControl Used

### ISSUE THREAD

**Issue by ianvink** [UXDivers/Grial-UI-Kit-Support#527]
Upgrading projects to XF 3.5.0 crashes when the TabControl is used
Crash Log attached

### Description

Add a TabControl to a page and it crashes when rendered. Remove the Tab Control, or revert to XF 3.4.0 and it works
### Steps to Reproduce

```
	<ContentPage.Content>
        <Grid CompressedLayout.IsHeadless="True">
			<StackLayout Orientation="Vertical" Padding="0" Spacing="0" >
				<templates:HeaderView></templates:HeaderView>

				<tab:TabControl
				VerticalOptions="FillAndExpand"
				TabStripPlacement="Top"
				StyleClass="CustomTabControlStyle"
				SingleDescriptionTabs="True"
				SelectedIndex="0">
```

### Expected Behavior

Not crash
### Actual Behavior

Crash
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017
-iOS or Android

[Crash Log.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/2891639/Crash.Log.txt)

**Comment by dirivero** [comment]
Can you try with pre-release version 2.7.6-RC of UXDivers.Artina.* packages?

**Comment by ianvink** [comment]
That worked

**Comment by dirivero** [comment]
Final packages were published. Version 2.7.7. Will close this issue.
