### ISSUE TITLE
Cannot release an archive for release mode

### ISSUE THREAD

**Issue by kevinvella** [UXDivers/Grial-UI-Kit-Support#528]
When trying to create an archive for release mode the following error occurs:
`MTOUCH : error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.`
  

### Steps to Reproduce

1. Set to Release iPhone
2. Archive for Publishing

### Expected Behavior
Compile an archive successfully

### Actual Behavior
Does not compile. Results in the following error:
`MTOUCH : error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void UXDivers.Artina.Shared.ArtinaPhoneMasterDetailRtlAwareRenderer::ViewDidLoad()' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.`
  

### Basic Information

- Version with issue: 2.7.6-RC
- Last known good version: 2.7.5
- IDE: Visual Studio Community Edition
- Platform Target Frameworks: 
  - iOS:  9.0
- Nuget Packages:
UxDivers 2.7.6-RC
Xamarin Forms - 3.5.0.169047

**Comment by dirivero** [comment]
Please take a look here: https://github.com/UXDivers/Grial-UI-Kit-Support/issues/526

**Comment by kevinvella** [comment]
Will downgrade to 3.4 until this issue is fixed. Thanks

**Comment by kevinvella** [comment]
Hi,

Xamarin Forms v3.6.0.220655 resolves this issue. Closing down issue
