### ISSUE TITLE
Grial Artina controls not working in IOS

### ISSUE THREAD

**Issue by Reitensen** [UXDivers/Grial-UI-Kit-Support#529]
I'm using latest Grial with Xamarin Forms 3.1.0.583944 on my PC, and Xamarin iOS 12.1 installed in the mac. The android app is working flawlessly, but the ios version running in iOS simulator, none of the Grial controls are working. Artina buttons for example is not triggering the clicked event, similar to how they behave in Gorilla. It's already running on Debug, not Gorilla mode.

The other non-grial controls are working fine. I'm stumped. Please help.

**Comment by dirivero** [comment]
Do the buttons animate when tapped or they behave as if they were disabled?
What other Grial controls behave like that?
Do you have Grial custom renderers defined in the iOS project? Similar to the last comment here https://github.com/UXDivers/Grial-UI-Kit-Support/issues/82
