### ISSUE TITLE
artina:button expose button.triggers

### ISSUE THREAD

**Issue by clarkjason** [UXDivers/Grial-UI-Kit-Support#53]
Hi,

Could you expose artina:button to allow Button.Triggers so I can do form validation on a button click?
e.g.

<Entry x:Name="entry"
       Text=""
       Placeholder="required field" />

artina:button
    <Button.Triggers>
        <DataTrigger TargetType="Label"
                     Binding="{Binding Source={x:Reference entry},
                                       Path=Text.Length}"
                     Value="0">
            <Setter Property="IsEnabled" Value="False" />
        </DataTrigger>
    </Button.Triggers>
/artina:button

https://developer.xamarin.com/guides/xamarin-forms/working-with/triggers/

Or is there another way I should be doing this ( Ignoring a code behind if statement ).

Thanks,
Jason

**Comment by jpbrocca** [comment]
Hi @clarkjason,
take a look at the "SignUpPage.xaml" for a reference on how to make validations.

Best,
JP

**Comment by tellamon** [comment]
@clarkjason, Have you solved the problem??

Same problem here, I can't see a rounded button even if I use <artina:Button>.
But I see the rounded button on Gorilla Player(Compiled with Gorilla Player SDK on Grial sample project)
