### ISSUE TITLE
Entry.Properties not working

### ISSUE THREAD

**Issue by jbtamaresgit** [UXDivers/Grial-UI-Kit-Support#533]
Hi,

I am having an issue regarding artina:EntryProperties.BorderStyle as my entry unable to apply the said style. 

1st implementation:
`<Entry artina:EntryProperties.BorderStyle=”None” Placeholder=”Username/> `

2nd implementation:
```
<ResourceDictionary>
            <Style x:Key="ArtinaNoBorderEntryStyle" TargetType="Entry">
                <Setter Property="artina:EntryProperties.BorderStyle"
					    Value="None" />
                <Setter Property="artina:EntryProperties.BorderWidth"
					    Value="0" />
            </Style>
</ResourceDictionary>
```

`<Entry Style="{StaticResource ArtinaNoBorderEntryStyle}" Placeholder=”Username/>`

yet it still shows the border for both android and iOS

### Expected Behavior
Should not show border

### Actual Behavior
Border being shown

### Basic Information

- Version with issue: 2.7.5
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  12.2.1.15
  - Android: 9.1.7.0
- Nuget Packages: Xamarin.Forms 3.4.0.1029
- Affected Devices: Android, iOS

### Screenshots
![screenshot_20190305-144142](https://user-images.githubusercontent.com/44351076/53786019-3fffa780-3f55-11e9-8ac1-6019398413a4.jpeg)

**Comment by BradleyDHobbs** [comment]
I am seeing the same thing

**Comment by troyanas** [comment]
Same issue here

**Comment by dirivero** [comment]
Please check if you have Grial Entry render declared in both Droid and iOS projects:
```
[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Grial.EntryRenderer))]
```

**Comment by troyanas** [comment]
Yes, at least that was the case for me, so I linked the issue here. Not sure if the same issue was for @jbtamaresgit
