### ISSUE TITLE
UXDivers.Artina.Shared.LicenseException :Error reading license

### ISSUE THREAD

**Issue by kwabenaowusujnr** [UXDivers/Grial-UI-Kit-Support#536]
Hi,
Im using Grial-UI-Kit for xamarin forms app development. I`m receiving this error **Unhandled managed exception: Error reading license. (UXDivers.Artina.Shared.LicenseException)** on iOS project when ever i run the project.  
Android project runs with no errors.

Using VS 17, Xamarin Forms 3.6.0.220655,
UXDivers.Artina.Controls.Repeater - 2.7.5
UXDivers.Artina.Controls.Tab - 2.7.5
UXDivers.Artina.Shared  - 2.7.5
UXDivers.Artina.Shared.Base - 2.7.5

I need help urgently.

Thanks.

**Comment by jpbrocca** [comment]
Hi @kwabenaowusujnr,

please check the documentation about troubleshooting license issues:

http://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-grial-first-run-troubleshooting-license-issues

Regards,
JP

**Comment by kwabenaowusujnr** [comment]
Hello JP,

![image](https://user-images.githubusercontent.com/17472090/54240161-31952b00-4515-11e9-876d-f01f0e2a4336.png)

I have gone through that documentation the entire day.

Still having same issue.

**Comment by jpbrocca** [comment]
Please check https://github.com/UXDivers/Grial-UI-Kit-Support/issues/244

**Comment by kwabenaowusujnr** [comment]
Thanks **JP**, the RootNamespace from #244 did the trick.
Issue fixed.

**Comment by jpbrocca** [comment]
Great!

Closing issue now.
Feel free to re-open as needed.

Best,
JP
