### ISSUE TITLE
Adding a line of text at the bottom of a dashboard page

### ISSUE THREAD

**Issue by olaeld** [UXDivers/Grial-UI-Kit-Support#537]
[question] I just took over a Xamarin forms project that is using a Grial template, and I am trying to add a text label at the bottom of a dashboard page. There is a DashboardMenuContentPage, with a GridOptionsView. I would like to add a simple line of text at the bottom, but when I add a Label object, it does not show up on the screen.

**Comment by jpbrocca** [comment]
Hi @olaeld,

I am not sure what do you have inside the `DashboardMenuContentPage` -it is not part of Grial demo sample app-. Probably your `GridOptionsView` is filling all the vertical space.

The `GridOptionsView` is based on a `Grid` so you can handle it in a similar way.

If you need to add a line of text at the bottom, then, most probably you will need to wrap your `GridOptionsView` inside any `Layout` of your choice (`StackLayout`, `Grid`, etc.) and make sure you have enough room for the label to be rendered inside your page.

Regards,
JP

**Comment by olaeld** [comment]
Thanks, putting the GridOptionsView and Label in a StackLayout did the trick!
