### ISSUE TITLE
Finding button event trigger

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Grial-UI-Kit-Support#538]
i am the file DashboardPage.xaml i was wondering where I can find the events triggered for the buttons?

**Comment by jpbrocca** [comment]
Hi @Onslot,

The `DashboardPage.xaml` uses a `GridOptionsView`.
Check the following link which explains how you can use `ItemClickedCommand`.

Regards,
JP

**Comment by Onslot** [comment]
Hi Jp,

Thanks!! I am new to this and bought the template and is helping me learn a bit faster. There is no link in your post for me to follow?

Thanks,
Mark

**Comment by jpbrocca** [comment]
Sorry @Onslot,

Here is the link:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207#issuecomment-319760712

**Comment by Onslot** [comment]
thank you
