### ISSUE TITLE
Grial TabControl letters color

### ISSUE THREAD

**Issue by Sacai01** [UXDivers/Grial-UI-Kit-Support#539]
How can we change the color of the letters in Grial TabControl
![Captura](https://user-images.githubusercontent.com/48775664/54725133-294b7a00-4b2b-11e9-92f1-d0874aca954c.JPG)

**Comment by dirivero** [comment]
If using Grial 2, check the file TabControlCustomResources.xaml. Almost at the beginning you will find 2 colors values to control this: CustomTabItemDefaultStateTextColor and CustomTabItemActiveStateTextColor.

**Comment by dirivero** [comment]
I’m closing this issue after a few days of inactivity.
Please reopen if you have further questions.
Thanks
