### ISSUE TITLE
Running on Android Emulator does not format the view correctly?

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Grial-UI-Kit-Support#541]
When i run the out of the box and viewing the multiple tile it does not fit the and emulator, any ideas why this is? here is a link to the screenshot of the emulator [https://ibb.co/mN0QRms](url)

i have it set as Android_Accelerated_x86_Oreo 8.1 API 27

**Comment by jpbrocca** [comment]
Hi @Onslot,
the link seems to be broken, could you paste the correct one?

Best,
JP

**Comment by jpbrocca** [comment]
Ok, now I was able to browse the link, thanks.

I guess this could be something on the emulator...so far we didn't get reports of this bug.
Try rotating the device to landscape and back to portrait.

Also, please keep in mind that when you add a new issue you follow all the steps in the text, and provide as much info as possible (i.e.: xamarin forms version, grial version, etc.). 

Thanks,
JP

**Comment by Onslot** [comment]
ok thanks jp. i will report back.

**Comment by Onslot** [comment]
Hi JP,

I tried to turn the emulator landscape and to portrait and it did not make any difference. This is the emulator from visual studio i have taken a screenshot [https://ibb.co/7X4F1R3](https://ibb.co/7X4F1R3)

**Comment by jpbrocca** [comment]
Hi @Onslot,
Sometimes emulators could do strange things, so I suggest -if you have the chance- to test with a real device. 

So far we didn't hear from customers about this issue.
Also, I am not being able to reproduce your issue (different emulator here).

Please add as much info as possible (i.e.: xamarin forms version, grial version, etc.) as it is explained in the new issue template text.

Regards,
JP

**Comment by Onslot** [comment]
Hi JP,

I will update you once I get more information for ya. I am going to sub to genymotion as soon as my boss allows me to buy it and give you a feedback.

Thanks,
Mark

**Comment by Onslot** [comment]
using genymotion works best for this issue. The visual studio emulator is not.
