### ISSUE TITLE
DashboardMultipleTiesPage Move Text align Top Left

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Grial-UI-Kit-Support#542]
How would i be able to adjust the Text to start from Top Left of the grid in the scroll view?

**Comment by jpbrocca** [comment]
Hi @Onslot,

Sorry...I am not sure what you are asking :(
You mean how to change text alignment of the tiles?
If that is your questions, you simply modify the tile template to suit your needs.

Regards,
JP

**Comment by jpbrocca** [comment]
Hi @Onslot,
You simply need to modify the XAML template for the tiles to suit your needs...or you could potentially create a new one if you want to keep the original ones (it seems from your screenshot that you won't need to alternate templates so this could be a handy option).

In any case, it should not be difficult if you duplicate `DashboardAppNotificationItemTemplate.xaml`, rename it, reference it from the page.
To make the changes you must remove some unnecessary stuff on the template and just leave 2 `Label`, each one for each text, then, make sure you put in the right row of the `Grid`.

You can comment the `TapGestureRecognizer` to avoid the tap detection on each tile.

**Comment by Onslot** [comment]
Thanks JP,

I will try today from your suggestion and see if I can understand what you suggested =) I will report back.

Thanks,
Mark

**Comment by jpbrocca** [comment]
Check the following docs that would help you to understand my comments:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector

**Comment by Onslot** [comment]
Thanks JP!

**Comment by jpbrocca** [comment]
Cheers!

**Comment by Onslot** [comment]
JP before you go, can you link me where i can find a listing of the available icon fonts that i can use with grialfonts ?

**Comment by jpbrocca** [comment]
Yes, check the docs about working with icons:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-using-font-icons

You can find the list of available glyphs in each font helper here:

~~~
Grial
    |_ Helpers
       |_ FontawesomeFont.cs
       |_ GrialShapesFont.cs
       |_ IoniciconsFont.cs
~~~

**Comment by Onslot** [comment]
ok i will take a look thanks JP

**Comment by Onslot** [comment]
how can i tell in the dashboardmultipletilepage.xaml which template it uses? I do not see any template that says or would tie with DashboardMultipleTilesPages.xaml it only indicates ItemTemplate="{StaticResource Selector}" and I am not sure where Grial sets ther static resource, can you point me to the right file?

**Comment by Onslot** [comment]
Can you tell me what file i can find ItemTemplate="{StaticResource Selector}" i have been trying to find the StaticResourse and thought it would be in the App.xaml but i do not see Selector

**Comment by Onslot** [comment]
what file can i find where this is calling the template? ItemTemplate="{StaticResource Selector}"

**Comment by Onslot** [comment]
When i modify the template DashboardAppNotificationItemTemplate.xaml i want to add a label before the Grid but i get an error when building 

Can not Add() elements to ASTMemberApp.DashboardAppNotificationItemTemplate.Content	ASTMemberApp	D:\_VSTesting\Grial\ASTMemberApp\Views\Dashboards\Templates\DashboardAppNotificationItemTemplate.xaml

how do i add a label in the template above the gird? I want to add a **Welcome Onslot** line of text above the tiles.

**Comment by jpbrocca** [comment]
Hi @Onslot,
it seems you are trying to add additional content inside the template (`ContentView`).
The content must be a single element:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts#contentview

I suggest to take a few minutes to read about `Layout` in Xamarin Forms, that will make things easier for you:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts

Regards,
JP

**Comment by Onslot** [comment]
Thanks! From reading the code and reading the example you shared,
the DashboardAppNotificationItemTemplate.xaml is called to be a template
for the list that is called from DashboardMultipleTilesPage.xaml and the
list is created from DashboardMutipleTilesViewModel.cs but i am not sure
how DashboardAppNotificationItemTemplate.xaml is being called/set, all i
see is ItemTemplate="{StaticResource Selector}" in scrollview >
artina:GridOptionsView can you tell me how that is tied in? i was able to
add what I needed but not quite there yet. I guess where is StaticResource
Selector set?

**Comment by Onslot** [comment]
Thanks! From reading the code and reading the example you shared, the DashboardAppNotificationItemTemplate.xaml is called to be a template for the list that is called from DashboardMultipleTilesPage.xaml and the list is created from DashboardMutipleTilesViewModel.cs but i am not sure how DashboardAppNotificationItemTemplate.xaml is being called/set, all i see is ItemTemplate="{StaticResource Selector}" in scrollview > artina:GridOptionsView can you tell me how that is tied in? i was able to add what I needed but not quite there yet. I guess where is StaticResource Selector set?

**Comment by Onslot** [comment]
also when i try to test different ways to possibly modify and viewing it with genymotion with gorilla player it is not rendering the change i have made to the list data. here is a picture [https://ibb.co/Kxw1hKW](https://ibb.co/Kxw1hKW)

**Comment by jpbrocca** [comment]
> Thanks! From reading the code and reading the example you shared, the DashboardAppNotificationItemTemplate.xaml is called to be a template for the list that is called from DashboardMultipleTilesPage.xaml and the list is created from DashboardMutipleTilesViewModel.cs but i am not sure how DashboardAppNotificationItemTemplate.xaml is being called/set, all i see is ItemTemplate="{StaticResource Selector}" in scrollview > artina:GridOptionsView can you tell me how that is tied in? i was able to add what I needed but not quite there yet. I guess where is StaticResource Selector set?

Hi @Onslot,
the `DashboardAppNotificationItemTemplate` is being selected when the property `IsNotification` is `true`. That is done through the `<artina:BoolMemberTemplateSelector>` which acts as the template selector.
When the `IsNotification` value is `false` then, then `DashboardVariantItemTemplate` is used.

**Comment by jpbrocca** [comment]
> DashboardMultipleTilesPage



> i tried adding another row to the template with colspan 2 but it did not add it to the main view and finally uderstood what it is doing. So i tried to adding another content item `DashboardMultipleTilesPage.xaml` a stacklayout with label inside it but it does not show on top of the grid. Also in that page `DashboardMultipleTilesPage.xaml` it has a section:
> 
> `<ContentPage.Content> <StackLayout Spacing="10" x:Name="layout"> <Label Text="This is underlined text." /> </StackLayout> </ContentPage.Content>`
> 
> which is part of the out of box code but the `DashboardMultipleTilesPage.xaml` does not render that and only shows the header and the tile template box view grid layout. I do not understand why I am not able render the stacklayout content above the grid. This would be line 37 on `DashboardMultipleTilesPage.xaml`

> i apologize for these questions in advance and appreciate your help.

Again, I suggest you to get familiar with `Layout` in Xamarin Forms.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts

The `ContentPage` **must have**  __a single content node__ (that is any `Layout` **but** only one, that means you will need to nest `Layouts` if you want things to overlap each other properly or just use something like a `StackLayout` to "stack" elements).

**Comment by jpbrocca** [comment]
> also when i try to test different ways to possibly modify and viewing it with genymotion with gorilla player it is not rendering the change i have made to the list data. here is a picture https://ibb.co/Kxw1hKW

I am not sure if your code is valid, but you have 2 content nodes there...I suspect you are just overwriting the first one with the `StackLayout` with `ScrollView` block. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=windows#setting-page-content

![image](https://user-images.githubusercontent.com/15996999/55104721-b487bb00-50a9-11e9-9904-cb094ccd8483.png)

Try commenting the `ScrollView` block (red one in my screenshot).

**Comment by Onslot** [comment]
Thanks JP i just created my own page seems to be easier than trying to understand the Grial one. Thanks. I will look into it more once i finished this project.
