### ISSUE TITLE
grial UI KIT 3.0 Full Download no found file

### ISSUE THREAD

**Issue by alexnavarronarvaez** [UXDivers/Grial-UI-Kit-Support#548]
grial UI KIT 3.0 Full Download no found file

![Captura](https://user-images.githubusercontent.com/3916943/55574204-799d0d00-56d1-11e9-9c38-1b9bded4d126.PNG)

**Comment by jpbrocca** [comment]
Hello @alexnavarronarvaez,

from your screenshot, it seems that there is probably an issue with our migration of your previous license to the new one (Grial 3 Standard).

We are reviewing it and will get back to you ASAP.

Best regards,
JP

**Comment by LeoHere** [comment]
@alexnavarronarvaez the problem has been fixed. Just download the Full version again.

Please close the issue once you verified it is working.

**Comment by alexnavarronarvaez** [comment]
@LeoHere  

![image](https://user-images.githubusercontent.com/3916943/55653433-218b0700-57b4-11e9-81fa-e49778372e72.png)

**Comment by LeoHere** [comment]
@alexnavarronarvaez please try doing clean + rebuild. Does the problem persist?

Did you successfully downloaded and executed the Starter project?

**Comment by alexnavarronarvaez** [comment]
Thanks. 👍

**Comment by jpbrocca** [comment]
Hi @alexnavarronarvaez,
It seems your issue was solved, so I am closing this to get things tidy. 

Feel free to reopen or add new ones as needed. 

Best, 
JP
