### ISSUE TITLE
Drawer Menu pages open slowly. Please help!!!

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#549]
I have just bought and deployed the Grial UI kit on my android phone. When i run and open the navigation drawer to switch page... it gets too slow... Please help how can i sort this out. I tried on two phones but its still same...

**Comment by jpbrocca** [comment]
Hello @ZiaStansall,
Could you please provide more details about your issue?:

- Which android phones are you testing with?
- Which is their Android API?
- Are those real devices or emulators?
- What happens if you download Grial Demo app from Google Play on those devices...do you get similar results?

Regards,
JP

**Comment by ZiaStansall** [comment]
Hi.. Details are given below:
1. Phones (Real Devices):
    - **Huawei** was‑lx2. (Slow Navigation) - Android Version 8.0.0
    - **Redmin** 6A (Slow Navigation) - Android Version 8.1.0
    - **I Phone** 7 (Working Fine) 
The demo app is also slow on Huawei & Redmin phones but working fine on i phone 7.

**Comment by eljotape** [comment]
Hi @ZiaStansall, 

What happens if you download Grial Demo app from Google Play on those devices...do you get similar results?

**Comment by ZiaStansall** [comment]
I clearly mentioned that "The demo app is also slow on Huawei & Redmin phones but working fine on i phone 7."

**Comment by dirivero** [comment]
Sadly, I don't have those any of those phones to reproduce this. I've tried with a Huawei Y9 and works fine as well as with lots of emulators. 

Does the slow opening happens no matter what page is opened behind? For instance, does it happen if the "what's new" page is the currently opened page? that one is very simple. 

I'll try to get an older Huawei to try to reproduce this behavior.

If you have more info feel free to contact me directly at drivero at uxdivers.com

Thanks
Diego

**Comment by jpbrocca** [comment]
Hi @ZiaStansall,

I have tested with an old Huawei device and I see the drawer opens normally. 

Any chance you can get in touch with @dirivero at drivero at uxdivers.com so we could investigate further if is there any issue with your Visual Studio solution? 

Thanks, 
JP

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for more than 10 days and we could not reproduce it either with old or new Huawei devices.
Please reopen if you still encounter this problem or has more information about it.
Thanks
