### ISSUE TITLE
Error Build Project

### ISSUE THREAD

**Issue by angelSwp** [UXDivers/Grial-UI-Kit-Support#55]
I'm trying to build the project with Link All Assemblies, but I am getting the following error:

`Xamarin.Forms.Xaml.XamlParseException: Position 195:35. Type FontAwesome not found in xmlns clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared
  at at (wrapper dynamic-method) System.Object:39281cee-6b90-4711-924d-fef960250d48 (intptr,intptr,intptr)
  at at (wrapper native-to-managed) System.Object:39281cee-6b90-4711-924d-fef960250d48 (intptr,intptr,intptr)`

**Comment by homerokzam** [comment]
Have you seen this?

https://github.com/UXDivers/Grial-UI-Kit-Support/issues/10

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for 3 years.
Please reopen if you still encounter this issue with the latest Grial version.
