### ISSUE TITLE
Upgrade to v3?

### ISSUE THREAD

**Issue by ajardolino3** [UXDivers/Grial-UI-Kit-Support#552]
Hello,

I tried emailing hello@grialkit.com but waited over a week with no response.  I just purchased v2 less than a month ago and then version 3 was released.  Can I be upgraded to v3?

**Comment by eljotape** [comment]
Hello,

Please send an email to grialkit@uxdivers.com with your purchase number and registered email address.

Thanks, 
JP

**Comment by jpbrocca** [comment]
Hi @ajardolino3,
I am closing this issue since we already processed your request by email.

Feel free to re-open if needed.

Best regards,
JP
