### ISSUE TITLE
Gorilla live xaml view is not working on real ios device. 

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#553]
### Description
i have connected my real Ios device to my MAC to preview the live xaml  with GORILLA and then my phone just only shows *Connected via GORILLA* but no xaml page preview at all on phone screen.

### Expected Behavior
No xaml page live preview on my phone (Iphone 7)

### Actual Behavior
It shows live preview on my android device. and working fine (y)

### Basic Information
- Version with issue: I phone 7
- Affected Devices: I phone 7

### Screenshots

![abbacbc5-0ae3-4332-b6f6-3d53ef3ae8f3](https://user-images.githubusercontent.com/49310231/55719186-3378de00-5a30-11e9-8655-01a26574fef9.jpg)

**Comment by jpbrocca** [comment]
Hi @ZiaStansall,
please add your issue here:
https://github.com/UXDivers/Gorilla-Player-Support

This is just for [Grial UI Kit](//grialkit.com) related issues only.

Thanks,
JP

**Comment by ZiaStansall** [comment]
Ok.. Thanks!
