### ISSUE TITLE
License not readable after upgrade to v3

### ISSUE THREAD

**Issue by lowleetak** [UXDivers/Grial-UI-Kit-Support#554]
After upgrading to v3, my existing app license is not working anymore.

I have converted from v2 license to v3 license last week. My account is having 1 existing app that is using v2. Today, I change the package name and name of the app. Then I regenerate the license. However, the app is now throwing exception when initializing the license.

**Comment by lowleetak** [comment]
Console log:
UNHANDLED EXCEPTION:
04-09 17:05:19.361 I/MonoDroid( 7945): UXDivers.Artina.Shared.LicenseException: Internal license validation error. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000db] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00054] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <d32db49e5e3440729da31845c03ddc3a>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at UXDivers.Artina.Shared.Licensing.LicenseManager.ValidateLicence (System.String license, UXDivers.Artina.Shared.Licensing.License& licenseObject, System.String& cause) [0x00139] in <682f0a3186b1418db4c441d9192f460e>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at UXDivers.Artina.Shared.Licensing.LicenseManager.Init (Android.App.Activity activity, System.String license, System.String& cause) [0x0001c] in <682f0a3186b1418db4c441d9192f460e>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x0005a] in <682f0a3186b1418db4c441d9192f460e>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):    --- End of inner exception stack trace ---
04-09 17:05:19.361 I/MonoDroid( 7945):   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x00074] in <682f0a3186b1418db4c441d9192f460e>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at UXDivers.Artina.Shared.GrialKit.Init (Android.App.Activity activity, System.String licenseResourceName) [0x0000b] in <2fc42d44c5f1409586b3bb4707a468c9>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at IndoShare.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00085] in D:\Projects\dms2\Mobile\IndoShare.Droid\MainActivity.cs:74 
04-09 17:05:19.361 I/MonoDroid( 7945):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <a10f61e70eeb434e952fef884856c199>:0 
04-09 17:05:19.361 I/MonoDroid( 7945):   at (wrapper dynamic-method) System.Object.7(intptr,intptr,intptr)

**Comment by LeoHere** [comment]
@lowleetak Grial 3 licenses are only valid for Grial 3 projects. If you try to use it in a Grial 2 project it will fail.

**Comment by lowleetak** [comment]
I was not told about this information and now my existing app is developed with v2 and going to release today then only you told me about this. Can help to generate a temporary one month license for my new package name and app name? So that I can release first and upgrade to v3 later?

**Comment by LeoHere** [comment]
@lowleetak what is the app you need to migrate? the one starting with "F" or "i". Please confirm so we can proceed.

**Comment by LeoHere** [comment]
@lowleetak we migrate your app back to Grial 2 (the one you mentioned in the website's chat). The other 4 licenses will be Grial 3 licenses. 

Closing the issue now. Please follow it on the Website chat if you have further questions.
