### ISSUE TITLE
Dashboard With Carousel (DashboardCarouselViewModel) is pointing to the wrong .json file

### ISSUE THREAD

**Issue by ismaelf** [UXDivers/Grial-UI-Kit-Support#557]
### Description
With a freshly downloaded project, the Dashboard with Carousel doesn't show any data. I noticed that the view model for that page, DashboardCarouselViewModel.cs is calling the wrong json file. I changed it and it worked. 

### Steps to Reproduce

1. Go to the Grial Kit Admin
2. Download a copy of the solution project (I downloaded a partial project, not the full version)
3. The View Model is pointing to the wrong json file.

### Expected Behavior
Line 30, JsonHelper.Instance.LoadViewModel(this, source: "Navigation.json"); should be:
JsonHelper.Instance.LoadViewModel(this, source: "NavigationDashboards.json");

### Basic Information

- Version with issue: Grial UI Kit 3.0
- IDE: Any

### Screenshots
<img width="1123" alt="Screen Shot 2019-04-10 at 9 10 13 PM" src="https://user-images.githubusercontent.com/700770/55924053-4a593500-5bd6-11e9-87b2-272bf35d17a2.png">

**Comment by dirivero** [comment]
Hi @ismaelf!

You are very right, the JSON file name is wrong as you indicate. It will be fixed in the next update of Grial.

Thanks for reporting this.

Regards,
Diego

**Comment by dirivero** [comment]
Closing this one as it was released with Grial 3.0.46.
