### ISSUE TITLE
Grial-UI-Kit v. 3, how to add more Pages after first setup

### ISSUE THREAD

**Issue by mrutter** [UXDivers/Grial-UI-Kit-Support#558]
Hello.
This is not a FR nor a BUG, but a simple enquiry.

Say I created and download the solution for the first time. I chose some Pages. Later I would like to add more Pages to my existing project.

Which is the best way to achive with this? Is it preferrable to create the solution with all the Pages and exlude/include them by the project?

Thank you.
-m

**Comment by dirivero** [comment]
Hi,

One alternative is to download the full project besides the starter project. You work on the starter and when you need a new screen or other file you simply copy it from the full solution folder into the starter solution folder. You don't need to add those new files from visual studio since the .net standard project (the multi-platform one) will recognize the new files automatically. Namespaces and other settings will be the ones you've defined so you won't need to change anything.
 
You can also have the full solution running with Gorilla Player so you can analyze in deep the screens before copying them.

Hope this helps.

Regards,
Diego

**Comment by mrutter** [comment]
Hi Diego,
thank you for your answer.

That's a good tip. BTW, from your message I understand that it is possible to download the full project (I mean the Grial UI Kit demo app available on the AAPL/GOOG stores), is it correct?

Thanks.
-m

**Comment by dirivero** [comment]
When you download the full project from the Grial Web Admin you get a curated version of the demo app. The idea is that, if you decide to base your project on that full version, you won't need to remove stuff specific of Grial's demo app that won't make sense for a different app. All the screens are included of course.

**Comment by dirivero** [comment]
I will close this issue. Feel free to reopen if you have more questions.
Thanks!

**Comment by mrutter** [comment]
Hi @dirivero, after working on the solution I downloaded from the Grial Web Admin site (both Full and Starter), everything is more clear but I still have one question. The Grial Official Demo App contains screens and features that I cannot find in the Full/Starter project. I mean, just to mention some pages, the theme selector page (Pick your theme), the About Grial Page and the All icons page.

I think it would be very helpful to have access to the Grial Demo App source code as it was for v. 2. Is there a way to get it?

Thank you.
-m

**Comment by dirivero** [comment]
Hi again :)

The `RichAboutPage` is almost a copy of the one in the demo app but with generic data. 
Regarding the icons page it's a very good idea, we will include it in future service releases of Grial.
We will also include code for changing themes.

All good ideas, thank you.

Diego

**Comment by mrutter** [comment]
Hi Diego.
Thank you for following up with my message.

About RichAboutPage, I just want to point out that I like very much the animation that happens when you swipe down the page and the title 'About Grial UI Kit' fades from the page to the navigatio's bar title. That's a very interesting example.

Thank you.
-m

**Comment by dirivero** [comment]
Good point. I will include that one in the rich about page for future versions and let you know :)
