### ISSUE TITLE
Error to compile Colors.tt

### ISSUE THREAD

**Issue by homerokzam** [UXDivers/Grial-UI-Kit-Support#56]
When I try to compile the Colors.tt file gives the following error (own example of UIKit Grial):

Running generator 'TextTemplatingFileGenerator' on file '/Users/HomeroKzam/Projects/ParkCode/ParkCode/Colors.tt'...
error CS1703: An assembly `System.Xml' with the same identity has already been imported. Consider removing one of the references
error CS1703: An assembly`System.Core' with the same identity has already been imported. Consider removing one of the references

Errors in file generation.

Thanks,
Homero.

**Comment by jpbrocca** [comment]
Hi @homerokzam, how are you ?

How are you compiling the Colors.tt file ?
Are you using Visual Studio ?

**Comment by homerokzam** [comment]
It's all right. And with you?
I'm using Xamarin Studio on Mac. I tried in VS 2015 and worked perfectly.

Thanks.
Homero

**Comment by jpbrocca** [comment]
Hi @homerokzam, I am doing great, thanks for asking :)

Which version of Xamarin Studio, Xamarin Forms and Grial are you using?

Regards
JP

**Comment by homerokzam** [comment]
I'm using Xamarin Studio 6.0.2, Xamarin.Forms 2.3.0.107 and GrialUIKit 1.5.0.12366.

Thanks.
Homero

**Comment by jpbrocca** [comment]
Hi @homerokzam,

I am using same setup as yours except for Xamarin Forms, which in my case is 6.0.1.

I will switch to your same version and let you know if I get the same error as you.

Regards and thanks,
JP
