### ISSUE TITLE
Can not bind click event for grial:GridView.ItemTemplate

### ISSUE THREAD

**Issue by pingpong2020** [UXDivers/Grial-UI-Kit-Support#560]
Can not add click event for gridview

### Description

I used grial:GridView + DataTemplate
I create an template (DataTemplate), but i can not bind click event when click element of gridview

### Steps to Reproduce

1. Create grial:GridView
2. Create grial:GridView.ItemTemplate
3. Binding command when click element
![Screen Shot 2019-04-14 at 9 28 07 PM](https://user-images.githubusercontent.com/49345429/56094274-c87e4a00-5efc-11e9-8756-10696fb8a533.png)
![Screen Shot 2019-04-14 at 9 28 29 PM](https://user-images.githubusercontent.com/49345429/56094277-d7fd9300-5efc-11e9-95b2-540d774412d6.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio on MacOS
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @pingpong2020,

Please check the following thread:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207#issuecomment-319760712

Regards, 
JP

**Comment by pingpong2020** [comment]
PersonalHomePage.xaml(38,38): Error: 'artina' is an undeclared prefix. Line 166, position 38. I also try to do with "grial" namespace, but ItemClickCommand does not work.

**Comment by pingpong2020** [comment]
I confuse that what is the difference between these packages below 
![Screen Shot 2019-04-15 at 8 40 21 AM](https://user-images.githubusercontent.com/49345429/56102940-52a8cb80-5f5a-11e9-87c1-308e641eeeb4.png)

**Comment by pingpong2020** [comment]
My license is PRO. But I got this error message

![Screen Shot 2019-04-15 at 9 03 26 AM](https://user-images.githubusercontent.com/49345429/56103499-686bc000-5f5d-11e9-9d27-70b1e71155ab.png)

**Comment by dirivero** [comment]
When using Grial 3 the only package needed is UXDivers.Grial.

The license validation error is because the package is old, as Artina* packages belong to older Grial versions. Please use UXDivers.Grial only.

**Comment by pingpong2020** [comment]
Thank you. I fixed this issue in DashboardCarouselPage. There is overlapping between GRID element.
