### ISSUE TITLE
Repearter's setting for calculating ItemSize to automatically

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#562]
Hi, I am using Grial 2.7.7 Kit.
From the Grial's documentation at "https://docs.grialkit.com/v2/#grial-uikit-overview" I read the Repeater in 2.7 calculates Item Size Automatically.

I have a list of items to be displayed vertically but the item information text varies in size.

Can you please help me with an example or point me to the template where Repeater's ItemSize is calculated automatically ? Which properties are used for setting spacing between Items ?

Thanks

**Comment by dirivero** [comment]
Hi,

The repeater is optimized for item virtualization and that's why it does not support items of different size. 

What the release notes of 2.7 tried to say was simply that you don't need to specify the ItemSize at the Repeater level anymore because it will measure the first item internally to calculate the size of every cell.

I'm sorry if it was confusing.

Regards,
Diego

**Comment by IoTFier** [comment]
Hi Diego, how are you ?
Your quick response is truly appreciated.

I chose Repeater to work with as I don't how to disable scrolling in the (readonly) listview and set the height of the ListView just enough to include all loaded Items by the DataTemplate.  

Any pointer on that end ? Is there Grial template that has such example ?

Thanks

**Comment by dirivero** [comment]
Hi! I'm fine, thanks. You?

If you want to completely avoid the scroll as there are not so many items you may try using the lightweight GridOptionView; 1-column with different item heights would be something like this:

```
<artina:GridOptionView
    ItemsSource="{ Binding Items }"
    ColumnCount="1"
    ItemHeightAuto="true"
>
    <artina:GridOptionsView.ItemTemplate>
        ITEM  TEMPLATE
    </artina:GridOptionsView.ItemTemplate>
</artina:GridOptionView>
```

**Comment by IoTFier** [comment]
I am doing good Diego. Thank you.

Is this control in Grial 2.7.7 ?

**Comment by dirivero** [comment]
Great. Yes, it's part of Grial 2+.

**Comment by IoTFier** [comment]
I don't see it .

Here is my assembly.info from iOS

[assembly: UXDivers.Artina.Shared.GrialVersion("2.7.0.0")]

// Custom renderer definition

[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.CircleImage), typeof(UXDivers.Artina.Shared.ImageCircleRenderer))]
[assembly: ExportRenderer(typeof(EntryCell), typeof(UXDivers.Artina.Shared.ArtinaEntryCellRenderer))]
[assembly: ExportRenderer(typeof(ImageCell), typeof(UXDivers.Artina.Shared.ArtinaImageCellRenderer))]
[assembly: ExportRenderer(typeof(SwitchCell), typeof(UXDivers.Artina.Shared.ArtinaSwitchCellRenderer))]
[assembly: ExportRenderer(typeof(TableView), typeof(UXDivers.Artina.Shared.ArtinaTableRenderer))]
[assembly: ExportRenderer(typeof(TextCell), typeof(UXDivers.Artina.Shared.ArtinaTextCellRenderer))]
[assembly: ExportRenderer(typeof(ViewCell), typeof(UXDivers.Artina.Shared.ArtinaViewCellRenderer))]

[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Artina.Shared.ArtinaEntryRenderer))]
[assembly: ExportRenderer(typeof(Editor), typeof(UXDivers.Artina.Shared.ArtinaEditorRenderer))]
[assembly: ExportRenderer(typeof(SearchBar), typeof(UXDivers.Artina.Shared.ArtinaSearchBarRenderer))]
[assembly: ExportRenderer(typeof(Picker), typeof(UXDivers.Artina.Shared.ArtinaPickerRenderer))]
[assembly: ExportRenderer(typeof(DatePicker), typeof(UXDivers.Artina.Shared.ArtinaDatePickerRenderer))]
[assembly: ExportRenderer(typeof(TimePicker), typeof(UXDivers.Artina.Shared.ArtinaTimePickerRenderer))]
[assembly: ExportRenderer(typeof(Page), typeof(UXDivers.Artina.Shared.ArtinaPageRenderer))]
[assembly: ExportRenderer(typeof(CarouselPage), typeof(com.IoTFier.MedGPS.iOS.CarouselPageVerticalScrollFixRenderer))]

**Comment by IoTFier** [comment]
I don't see it
Here is my assembly info
[assembly: UXDivers.Artina.Shared.GrialVersion("2.7.0.0")]

// Custom renderer definition

[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.CircleImage), typeof(UXDivers.Artina.Shared.ImageCircleRenderer))]
[assembly: ExportRenderer(typeof(EntryCell), typeof(UXDivers.Artina.Shared.ArtinaEntryCellRenderer))]
[assembly: ExportRenderer(typeof(ImageCell), typeof(UXDivers.Artina.Shared.ArtinaImageCellRenderer))]
[assembly: ExportRenderer(typeof(SwitchCell), typeof(UXDivers.Artina.Shared.ArtinaSwitchCellRenderer))]
[assembly: ExportRenderer(typeof(TableView), typeof(UXDivers.Artina.Shared.ArtinaTableRenderer))]
[assembly: ExportRenderer(typeof(TextCell), typeof(UXDivers.Artina.Shared.ArtinaTextCellRenderer))]
[assembly: ExportRenderer(typeof(ViewCell), typeof(UXDivers.Artina.Shared.ArtinaViewCellRenderer))]

[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Artina.Shared.ArtinaEntryRenderer))]
[assembly: ExportRenderer(typeof(Editor), typeof(UXDivers.Artina.Shared.ArtinaEditorRenderer))]
[assembly: ExportRenderer(typeof(SearchBar), typeof(UXDivers.Artina.Shared.ArtinaSearchBarRenderer))]
[assembly: ExportRenderer(typeof(Picker), typeof(UXDivers.Artina.Shared.ArtinaPickerRenderer))]
[assembly: ExportRenderer(typeof(DatePicker), typeof(UXDivers.Artina.Shared.ArtinaDatePickerRenderer))]
[assembly: ExportRenderer(typeof(TimePicker), typeof(UXDivers.Artina.Shared.ArtinaTimePickerRenderer))]
[assembly: ExportRenderer(typeof(Page), typeof(UXDivers.Artina.Shared.ArtinaPageRenderer))]
[assembly: ExportRenderer(typeof(CarouselPage), typeof(*****.******.iOS.CarouselPageVerticalScrollFixRenderer))]

**Comment by IoTFier** [comment]
Found it .. But the artina:GridOptionsView.ItemTemplate doesn't support Grid as the child

**Comment by dirivero** [comment]
It's a data template, to have a Grid as root the Xaml would be:

```
<DataTemplate>
   <Grid>
      ....
   </Grid>
</DataTemplate>
```

**Comment by IoTFier** [comment]
Lovely! Diego … you made my day today. 
Please note the link https://docs.grialkit.com/v2/#grial-uikit-overview-working-with-projects-setting-up-artina-custom-renderers-in-your-project  doesn't have any info on this renderer..
Or am I missing any other doc ?
Thanks

Please don't close this ticket till I get to validate all test cases..

**Comment by dirivero** [comment]
Glad to hear that :)
It doesn't require a renderer as it's a "pure" Xamarin.Froms control, that's why it's not mentioned in that section.
I'll leave the ticket open until you finish.
Regards

**Comment by IoTFier** [comment]
Hello @dirivero , how are you?

I am not able to scroll thru all items listed by the ItemTemplate once the GridViewOption is rendered.
It is enclosed in a stacklayout. Is that a problem?

I am expecting 12-24 listitems rendered by the GridViewOptions. For now, even for 7 items it stops showing beyond 5 in iOS and 4 n Android.

Thoughts?

Thanks,

**Comment by IoTFier** [comment]
Hi @dirivero - any thoughts ? Especially on why the data disappearing for GridViewOption which is referred in each listview item (from itemtemplate) ?

Thanks

**Comment by IoTFier** [comment]
@dirivero , @leohere - can you please help me with the issue of data disappearing in the GridViewOption when used in a datatemplate attached to a listview?

Please ref to above 2 of my notes.

Thanks

**Comment by dirivero** [comment]
Hi @IoTFier. 

I'm not sure why that may happen. Does the ListView has HasUnevenRows == false?
Can you send me by email the Xaml code so I can try to reproduce it?

**Comment by IoTFier** [comment]
Hi @dirivero, thank you.

Xaml should be in your inbox. The ListView has HasUnevenRows=true

**Comment by IoTFier** [comment]
@dirivero - any finding from the Xaml I emailed you ?

**Comment by dirivero** [comment]
Could not reproduce it yet. I've just answered explaining what I've tried, a video, and a couple of questions.

**Comment by IoTFier** [comment]
@dirivero , @jpbrocca - thank you for helping me at Xamarin Dev Summit.
I really appreciate your help.

The solution was to change the caching strategy on the ListView to RetainElement
CachingStrategy="RetainElement"

Closing this issue now.
Thank you.
