### ISSUE TITLE
'Resource.Layout' does not contain a definition for 'Tabbar'

### ISSUE THREAD

**Issue by binhara** [UXDivers/Grial-UI-Kit-Support#564]
Donwload a zip file of grials 3 and dont work 

### Description
Severity	Code	Description	Project	File	Line	Suppression State Error	CS0117	'Resource.Layout' does not contain a definition for 'Tabbar'	Ubi.Droid	D:\Starter-Ubi\Grial\Ubi.Droid\MainActivity.cs	46	N/A

### Steps to Reproduce
1. Create a app on grial site
2. open on vs 2017 
3. try build , dont work 

### Expected Behavior
build a solution 

### Basic Information

![grialserros](https://user-images.githubusercontent.com/121224/56437357-6aaf8080-62b5-11e9-9103-e16f78d83e3b.PNG)

**Comment by jpbrocca** [comment]
Hello @binhara, how are you?

Could you take a look at this related issue and see if any of the proposed solutions work for you? 

https://github.com/UXDivers/Grial-UI-Kit-Support/issues/551

Let me know how it goes. 

Best, 
JP
