### ISSUE TITLE
Grial Radio button binding not working

### ISSUE THREAD

**Issue by deepakyogi1995** [UXDivers/Grial-UI-Kit-Support#566]
Hello @LeoHere,

I am using grial check box for multiple button in list 
```
<grial:Checkbox IsChecked="False" InputTransparent="True" >
                                                <Label Text="{ Binding . }" Margin="8,0" />
                                            </grial:Checkbox>
```
i have two issue in this radio button

1. If i set IsChecked="False" then first radio button by default true means checked.
2. If i set IsChecked="{Binding checkPropery}"  then first radio button by default true means checked and working as ckeck box not radio button means i tap radio button and working as check box, i am able to select `multiple.` 

**What want**

1. not select by default true.
2. not able to select multiple radio button

**Comment by jpbrocca** [comment]
Hello @deepakyogi1995,
What are you using to repeat the radios? 
From your comments it seems you are using a `ListView`.
If that is the case, try with the sample from here:

http://docs.grialkit.com/checkbox-radio.html#working-with-checkboxes-and-radios-about-radios

Best, 
JP

**Comment by deepakyogi1995** [comment]
Hello @jpbrocca 

yes i am using this

```
<grial:Repeater.ItemTemplate>
        <DataTemplate>
            <StackLayout Orientation="Horizontal">
                <grial:Checkbox IsChecked="{Binding IsChecked}">
                    <Label Text="{ Binding . }" Margin="8,0" />
                </grial:Checkbox>
                <Label Text="{Binding value}" HorizontalOptions="StartAndExpand" VerticalOptions="CenterAndExpand"/>
            </StackLayout>
        </DataTemplate>
    </grial:Repeater.ItemTemplate>
    <grial:Repeater.SelectedItemTemplate>
        <DataTemplate>
            <StackLayout Orientation="Horizontal">
                <grial:Checkbox IsChecked="{Binding IsChecked}" InputTransparent="{Binding IsInputTra}">
                    <Label Text="{ Binding . }" Margin="8,0" />
                </grial:Checkbox>
                <Label Text="{Binding value}" HorizontalOptions="StartAndExpand" VerticalOptions="CenterAndExpand"/>
            </StackLayout>
        </DataTemplate>
    </grial:Repeater.SelectedItemTemplate>
```
but it's not working such as radio button, it's working such as check box

**Comment by jpbrocca** [comment]
Hi @deepakyogi1995,

OK. You should not bind the Is Checked of the checkbox, that will be true if it is the selected item template. 
You need to bind the selected item of the Repeater to know which one is active.

**Comment by deepakyogi1995** [comment]
Ya i now which item is active or not,

but how can bind template from code behind

**Comment by dirivero** [comment]
Hi @deepakyogi1995,
What exactly is that you want to achieve from code behind?
To prevent it from working as a checkbox please remove the bindings from the IsChecked properties and use true and false values.

**Comment by deepakyogi1995** [comment]
Hello @dirivero 

In my case IsChecked properties binding necessary.
First time load radio button list with Ischecked false then  then check radio button and save in server after second time load radio button list with binding value.

This Is my code

  ```
<ContentPage.Content>
        <ListView SelectionMode="None" x:Name="listView" HasUnevenRows="True"
              IsPullToRefreshEnabled="False" ItemTemplate="{StaticResource QuestionTemplateSelector}"/>
    </ContentPage.Content>


    <ContentPage.Resources>
        <ResourceDictionary Source="/Styles/TabControl/AndroidTabResources.xaml">
            <template:QuestionTemplateSelector x:Key="QuestionTemplateSelector" RadioTemplate="{StaticResource templateRadio}"/>


            <DataTemplate x:Key="templateRadio">
                <ViewCell IsEnabled="True" >
                    <StackLayout>
                        <StackLayout Orientation="Vertical" VerticalOptions="Center" HorizontalOptions="FillAndExpand" >
                            <Label Text="{Binding Question_Desc}">
                                <Label.FontSize>
                                    <OnIdiom x:TypeArguments="x:Double" Phone="{StaticResource PhoneFontSize}" Tablet="{StaticResource TabletFontSize}" />
                                </Label.FontSize>
                            </Label>
                        </StackLayout>

                        <Grid Padding="20,0"  VerticalOptions="Center" grial:Effects.ApplyIOSSafeAreaAsPadding="Left,Right">

                            <grial:Repeater  x:Name="RadiouGroup" SelectionMode="Single" InitialSelection="First"
                                                   ItemSize="45" ItemsSource="{Binding RadioList}" 
                                                   HorizontalOptions="Start" Orientation="Vertical">

                                <grial:Repeater.ItemTemplate>
                                    <DataTemplate>
                                        <StackLayout Orientation="Horizontal">
                                            <grial:Checkbox IsChecked="{Binding IsCheck}">
                                                <Label Text="{ Binding . }" Margin="8,0" />
                                            </grial:Checkbox>
                                            <Label Text="{Binding value}" />
                                        </StackLayout>
                                    </DataTemplate>
                                </grial:Repeater.ItemTemplate>
                                <grial:Repeater.SelectedItemTemplate>
                                    <DataTemplate>
                                        <StackLayout Orientation="Horizontal" >
                                            <grial:Checkbox IsChecked="{Binding IsCheck}" InputTransparent="True">
                                                <Label Text="{ Binding . }" Margin="8,0" />
                                            </grial:Checkbox>
                                            <Label Text="{Binding value}" />

                                        </StackLayout>
                                    </DataTemplate>
                                </grial:Repeater.SelectedItemTemplate>
                            </grial:Repeater>


                        </Grid>


                    </StackLayout>

                </ViewCell>
            </DataTemplate>
        </ResourceDictionary>
    </ContentPage.Resources>
```

I attach link of screen shot of my radio button list

[https://drive.google.com/file/d/1VL7rRI9dXfExHtDfDu2oNG4BlYax4Pbo/view?usp=sharing](url)

**Comment by dirivero** [comment]
> In my case IsChecked properties binding necessary.

Not exactly... what you need is a `TwoWay` binding on the `SelectedItem` property of the repeater. That's where the unique selected item (correspondent to the checked radio) is going to be. Since those are radios it can be at most one checked or none, if the property is null.

```
<grial:Repeater 
   ItemsSource="{Binding RadioList}" 
   SelectedItem="{Binding SelectedRadio, Mode=TwoWay}}" ...
```
> First time load radio button list with Ischecked false then then check radio button and save in server after second time load radio button list with binding value.

The first time, the bound value is going to be null (nothing checked, you should remove the `InitialSelection` property too). Then the user taps in some radio button and the repeater will change its `SelectedItem` value to the radio tapped by the user. As you have a `TwoWay` binding you will now know what the checked value is in the view model (in my code it would be in `SelectedRadio`). Note that it will always be one of the items of your `RadioList`.

Next time, you initialize `SelectedRadio` and the initial state of the screen will reflect whatever value you have in your view model.

The important thing here is that the checkboxes in the templates are just a visual representation of something checked/unchecked and can't be interactive (they could be just 2 labels "checked" and "unchecked" but it wouldn't look pretty  :)), the interaction needs to be handled by the repeater. This is why the checkboxes in the templates have to have `IsChecked="true"` and `IsChecked="false"` always, as mentioned before.
