### ISSUE TITLE
Theme Setup not as in the video

### ISSUE THREAD

**Issue by MarcelMbom** [UXDivers/Grial-UI-Kit-Support#567]
Hi,

I'm configuring a new app with Grial 3.0 and I noticed that the Theme Setup step is not the same as showed in the docs page. It's not possible to change the following attributes: BasePageColor, BaseTextColor, ComplementColor, MainWrapperBackgroundColor, ...
Is it an issue? Or you choose to no longer provide feature?

Thanks

**Comment by jpbrocca** [comment]
Hi @MarcelMbom,
We chose not to provide the feature to make things easier for our customers. 
That is why we added the necessary logic to calculate the additional colors based on `AccentColor`.

We could allow further customization in the feature, similar to what you saw on the video but easier. 

Regards 
JP

**Comment by jpbrocca** [comment]
I am closing this issue to keep things tidy, but feel free to reopen if needed.

Best
JP

**Comment by 4bs-zer0** [comment]
Hi,

I just want to add a vote to bring this feature back. Perhaps you could allow an "easy" and "advanced" mode?

Cheers
