### ISSUE TITLE
License is giving me Exception

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Grial-UI-Kit-Support#568]
License is giving me Exception here is a screenshot [https://ibb.co/3v2BYpx](https://ibb.co/3v2BYpx) 
It keeps bringing up an exception even when i have re-downloaded the production license and replaced them in the android and IOs folder.

### Steps to Reproduce

1. Just ran debug for Iphone simulator 
2. Deleted license and download to renew the files.

### Screenshots

[https://ibb.co/3v2BYpx](https://ibb.co/3v2BYpx)

**Comment by Onslot** [comment]
This ran fine as Android but when i try to run the iphone simulator the license is an issue. Please let me know if i need to submit the license as well?

**Comment by Onslot** [comment]
i am still having this issue and went through troubleshootings section of the doc of grial kit. I also went back to grial admin and downloaded the whole sample kit with gorilla and deleted the license from current project and replaced them with the ones i just downloaded and i am still having the same exception. "Error reading license".

**Comment by jpbrocca** [comment]
Hi @Onslot, how are you?
Could you please send your `.csproj` file from the iOS project so we can take a deeper look?

Please send it to:
grialkit@uxdivers.com

Regards and thanks,
JP

**Comment by Onslot** [comment]
hi @jpbrocca 

i found the solution and made it embded. i have another issue but i am not sure how to fix it. i will submit another ticket.

Thanks!

**Comment by jpbrocca** [comment]
Great!
And thanks for helping us to get things tidy :)

Regards,
JP
