### ISSUE TITLE
Date Picker Customization

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#570]
Hi..
The Grial Date Picker is showing the current date by default. I need to add a placeholder text in the date-picker. How do i do that? also how do i change the date format from 5/2/19 to 2/5/19? Please help. Thanks in advance

**Comment by jpbrocca** [comment]
Hi @ZiaStansall,
Grial `DatePicker` is based on Xamarin Forms `DatePicker`.

There is no placeholder property provided.
You can use for instance a `<Label>` to display the placeholder text and depending on your needs you could make it visible or not after the user selects a date.

To change the format just use the available `Format` property.

Check the Xamarin Forms pages about `DatePicker` for more details:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datepicker
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.datepicker?view=xamarin-forms

Regards,
JP

**Comment by ZiaStansall** [comment]
Ok.. understood. Thanks!

**Comment by jpbrocca** [comment]
Closing this issue to keep thing tidy.
Feel free to reopen if needed.
