### ISSUE TITLE
Crop image

### ISSUE THREAD

**Issue by deepakyogi1995** [UXDivers/Grial-UI-Kit-Support#571]
Hello @stormlion227,

I Used ImageCropper.Forms pluging for crop the image but in my case this happening in the content view not content page so any solution for that because show method parameter pass content page and i have content view.
`  new ImageCropper()
                {
                    //                PageTitle = "Test Title",
                    //                AspectRatioX = 1,
                    //                AspectRatioY = 1,
                    Success = (imageFile) =>
                    {
                        Device.BeginInvokeOnMainThread(() =>
                        {
                            byte[] bytes = System.IO.File.ReadAllBytes(imageFile);
                            Stream Newstream = new MemoryStream(bytes);
                            Img.Source = ImageSource.FromStream(() =>
                            {
                                return Newstream;
                            });
                        });
                    }
                }Show(this);`

**Comment by jpbrocca** [comment]
Hi @deepakyogi1995,

It seems you added this issue to the wrong place :)
I am closing it to keep things tidy, but feel free to reopen if needed.

Best,
JP
