### ISSUE TITLE
How-to: programmatically get a translated string

### ISSUE THREAD

**Issue by mrutter** [UXDivers/Grial-UI-Kit-Support#572]
**Referring Grial documentantion**
https://github.com/UXDivers/Grial-UI-Kit-Support/blob/master/i18n-page.md

**Question**
Is there a way to get the value of a string using Grial Translate converter?

On XAML I can do something like this:

`Text="{ grial:Translate StringLogin }"`

On my code, I need something like this:

`var myString = UXDivers.Grial.Translate.Get("StringLogin")`

**Comment by mrutter** [comment]
Please, forgive me for the trivial question, completely forgot that the resources are available directly thru Resx.AppResources ... Sorry!

**Comment by jpbrocca** [comment]
No problem! :)
