### ISSUE TITLE
Missing screen in the solution

### ISSUE THREAD

**Issue by vidalkk** [UXDivers/Grial-UI-Kit-Support#573]
Can somebody tell me where in the solution I find below screen?  

![F6D2906E-4F4D-4743-839C-BEC5DB6FD466](https://user-images.githubusercontent.com/16191124/57698766-be02bd80-762c-11e9-995d-b8eb8f5b77d0.png)

**Comment by mrutter** [comment]
Hi @vidalkk: not sure but I think that it's one of the missing screens, I mean screens that you can see on the demo app but not on your full solution. BTW, I would like to have that screen too (if possible).

**Comment by vidalkk** [comment]
@mrutter That’s correct, I look for it all over the solution and could not find it. @jpbrocca is there any chance to have an update to add these missing screens?

**Comment by jpbrocca** [comment]
Hello @vidalkk and @mrutter, how are you guys?

Please look for the file called `DashboardCarouselPage` in the following location in your solution:

~~~
YourGrialSolution
    |_ Views
        |_ Navigation
           |_ Dashboards
              |_ DashboardCarouselPage.xaml
~~~

Please notice there is a bug in the name of the referenced data.
In `DashboardCarouselViewModel.cs` says:
~~~
JsonHelper.Instance.LoadViewModel(this, source: "Navigation.json"); 
~~~

...but the correct file name is `NavigationDashboards.json`.

This will be fixed on the next service release.

More details here:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/557

Regards,
JP

**Comment by mrutter** [comment]
Thank you very much @jpbrocca.

**Comment by vidalkk** [comment]
FOUND IT.

thank you so much.

Em qua, 15 de mai de 2019 às 18:19, Marcello Rutter <
notifications@github.com> escreveu:

**Comment by jpbrocca** [comment]
Hello @vidalkk and @mrutter, how are you guys?

I am glad you found it :)

I am closing this issue now but feel free to reopen if needed.

Best,
JP
