### ISSUE TITLE
Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by RGPDev** [UXDivers/Grial-UI-Kit-Support#575]
I just purchased Grail and I'm using the starter solution provided. 

When I add the Nuget for Xamarin.Forms.Maps, it installs normally like any other Nuget I've used. However, when I try access it in a page\class "using Xamarin.Forms.Maps" doesn't find 
.Maps. 

I have cleared bin\obj\cleaned\rebuilt\rebooted and started clean. I cannot figure out why I can't access Maps.

Any suggestions? 

Visual Studio For Mac 2019

Here are a few screenshots:

<img width="401" alt="Maps" src="https://user-images.githubusercontent.com/24420022/57818227-acaed380-7748-11e9-9c34-4487ac6d72a8.png">

<img width="1437" alt="Maps2" src="https://user-images.githubusercontent.com/24420022/57818269-c94b0b80-7748-11e9-9459-e9ed39f2992b.png">

**Comment by LeoHere** [comment]
@RGPDev the screenshot shows you add the nuget package to your iOS project. Did you add it to the .NET Standard project too?

**Comment by dirivero** [comment]
Did you make this work?

**Comment by dirivero** [comment]
I'm going to close this issue as we didn't get more information. Feel free to contact us again if you need to.
