### ISSUE TITLE
Close button is not showing in the app

### ISSUE THREAD

**Issue by danialbakhsheshi** [UXDivers/Grial-UI-Kit-Support#58]
close Icon is not showing in anywhere,
any idea why?

**Comment by danialbakhsheshi** [comment]
Any help?!!

**Comment by jpbrocca** [comment]
Hi @danialbakhsheshi,

What close button you are not being able to see ?
Please be more specific so we could help you.

Thanks,
JP

**Comment by jpbrocca** [comment]
Hi @danialbakhsheshi,
Could you close this issue or provide more info ?

Thanks,
JP
