### ISSUE TITLE
Navigation Bar Height

### ISSUE THREAD

**Issue by denfung** [UXDivers/Grial-UI-Kit-Support#581]
Hi,

Is there any reusable control (Grid with height same as NavigationBar) with Grial 3 Pro to provide a padding at top of the screen. I would like to use fullscreen to display background image at the top and ListView to stop at the navigation bar area.

I am trying to use the iOS SafeArea Effect with "grial:GrialNavigationPage.IsTransparent=true" but this doe not provide consistence (safe) layout across  different screensize such iPhone 7, iPhone Xs, and Android phone.

Can I do something like this with Grial 3 Pro?

Thanks,
Dennis

**Comment by dirivero** [comment]
Hello,

You can achieve that with the code bellow. The `GrialNavigationBar` is used to save the space normally used by the navigation bar. This assumes the NavigationPage has both:
 a) grial:GrialNavigationPage.IsBarTransparent="true"
 b) grial:GrialNavigationPage.BarBackgroundHeight="-1"  (this is the default value)

```
<Grid>
    <Image 
        Aspect="Fill"
        Source="https://images.unsplash.com/photo-1559518875-4ce738e04b3a" 
    />
    
    <Grid RowSpacing="0">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        
        <grial:GrialNavigationBar 
            Grid.Row="0"
            BackgroundColor="Transparent"
        />
        
        <Grid
            Grid.Row="1"
            Opacity="0.5"
            BackgroundColor="Red"
        >
            <Label 
                Text="PAGE CONTENT HERE" 
                VerticalOptions="Center"
                HorizontalOptions="Center"
                FontSize="40"
            />
        </Grid>
    </Grid>
</Grid>
```

Check the results in the attached screenshots.
# PORTRAIT
![portrait](https://user-images.githubusercontent.com/7670773/58904030-1d5c6680-86dd-11e9-9e13-5277c8ac26cd.png)
# LANDSCAPE
![landscape](https://user-images.githubusercontent.com/7670773/58904031-1d5c6680-86dd-11e9-9e7b-52091f95a528.png)
