### ISSUE TITLE
ViewModels Sample Data & Localized Json files

### ISSUE THREAD

**Issue by mistersam91** [UXDivers/Grial-UI-Kit-Support#582]
Hi,

I've downloaded the full pro solution with **French language** added.
I can't understand how sample Json data works in the solution....and can't find any documentation about it in your official documents.

With french language activated the solution has no sample data, i can't see any french ressource file for the Data. 

And i've opened the **JsonHelper.cs** and saw that theses lines are responsible for localization of sample data : 

`                    if (culture.TwoLetterISOLanguageName != "en")
                    {
                        try
                        {
                            var satelliteAssembly = assembly.GetSatelliteAssembly(culture);
                            if (satelliteAssembly != null)
                            {
                                assembly = satelliteAssembly;
                            }
                        }
                        catch
                        {
                            // No satellite assembly, keep en strings
                        }
                    }`

When i comment this mecanism, the data are here (but in english).

What did i miss ?

Thanks for your help.

**Comment by dirivero** [comment]
You are right, there's a problem in that code. We will include the fix in the next service release of Grial 3 but in the meantime, if you can ping me at drivero at uxdivers.com I will send you the patch.

Thanks

**Comment by mistersam91** [comment]
Do you have an estimated release date for the next Grial Version ?

Do you have a documentation for updating Grial UI Kit ? 

Thanks

**Comment by dirivero** [comment]
I'm closing the issue as a fix for this was released as part of Grial version `3.0.49`.
