### ISSUE TITLE
NavigationCardsList and Navigation.PushAsync(xxxxx)

### ISSUE THREAD

**Issue by mistersam91** [UXDivers/Grial-UI-Kit-Support#583]
Hi,

I would like to use a NavigationCardsList page to naviage to a new page on click on an item.

**What is the best way to do it ?**

Should i pass navigation from ContentPage to ViewModel (cf : https://forums.xamarin.com/discussion/21822/call-navigation-pushasync-from-viewmodel)

And add a ContentPage property to NavigationItemData in order to do 

```
public NavigationItemData SelectedItem
        {
            get { return _selectedItem; }
            set
            {
                if (SetProperty(ref _selectedItem, value) && value != null)
                {
                    _navigation?.PushAsync(value.ContentPage).Wait();
                    SetProperty(ref _selectedItem, null);
                }
            }
        }
```

Thanks for your help, i can't find any documentation about it.

**Comment by dirivero** [comment]
That looks good.

MVVM frameworks such as Prism or MvvmCross have specific services to do navigations from ViewModels but, if you decide not to use any of those your approach is good and very clean.

**Comment by mistersam91** [comment]
Thanks, i will look at Prism.

Do you plan to integrate it in Grial UI Kit ? For V3.1 ?

**Comment by mrutter** [comment]
Hi @mistersam91,
please forgive me but it'snt a good practice to navigate within a property setter.

A property setter in a ViewModel should be limited to change the property's value. To navigate to a new page, you should implement an ICommand associated to the ItemTapped event or also "react" to the changed property (for example by "observing" the property itself).

Regardas.
-m
