### ISSUE TITLE
Grial bundle identifier change  

### ISSUE THREAD

**Issue by deepakyogi1995** [UXDivers/Grial-UI-Kit-Support#584]
Hello @jpbrocca ,

   I want to change my grial app bundle identifier because i am updating my app on App Store and my old app bundle identifier is different to grial project if i changed identifier then it throw a error.

**License verification failed because: The BundleIdentifier does not match the license's.**

**Comment by LeoHere** [comment]
@deepakyogi1995 please email at grialkit at uxdivers.com requesting the change. In that email, please explain why the old bundle identifier is not valid any more.

Thanks.

Closing the issue. Feel free to reopen it if you need to.
