### ISSUE TITLE
Changed view name but no data loaded . 

### ISSUE THREAD

**Issue by Pirate911** [UXDivers/Grial-UI-Kit-Support#588]
Hi , 
I bought Grial 3.0 pro + RTL . I have weird issue : 

I changed DashboardMultipleTilesPage.xaml and it's associated viewmodel to the following 
MainViewPage.xaml and MainPageViewModel.cs . Then I changed the name of the view to the new name in NavigationDashboards.json and NavigationDashboards.ar.json . Finally I moved MainViewPage.xaml to root of Views folder . 

The project compiles with no issue but it doesn't load any content from json file . 

Is there any hidden place I should change view name or something to fix this issue ? 

Thanks

**Comment by mrutter** [comment]
Hi @Pirate911,
not sure but I think there is a kind of naming violation while renaming the objects.

Grial UI Kit uses a default naming convention to get the name of the page having the model:

If your ViewModel is named MainPageViewModel.cs then the page must be name MainPagePage.cs (please note that Page is repeated twice).

You can manually specify the name of the page in the call to LoadViewModel or you can follow the naming criteria used by Grial.

For example, if your page is named MainViewPage.xaml, then the ViewModel must be named MainViewViewModel.xaml

Hope this helps!

Regards.
-m

**Comment by Pirate911** [comment]
Thanks @mrutter for the reply. I did try what you said but it didn't load(deleted app in simulator,cleaned proj,deleted obj&bin). 

Any other thoughts ?

**Comment by mrutter** [comment]
Can you post the source of your new ViewModel class?
This would help to troubleshooting your case.

**Comment by Pirate911** [comment]
Ok , viewmodel name : 

`public class MainViewViewModel : ObservableObject
    {
        private readonly INavigation _navigation;

        public MainViewViewModel(INavigation navigation) : base(listenCultureChanges: true)
        {
            _navigation = navigation;
            LoadData();
            _itemCommand = new Command<DashboardMultipleTileItemData>(OnItemCommand);
        }

        public ObservableCollection<DashboardMultipleTileItemData> Items { get; } = new ObservableCollection<DashboardMultipleTileItemData>();

        protected override void OnCultureChanged(CultureInfo culture)
        {
            LoadData();
        }

        private void LoadData()
        {
            Items.Clear();
            JsonHelper.Instance.LoadViewModel(this, source: "NavigationDashboards.json");
        }....//no changes done for the view model before and after changing the name `

as for json file : NavigationDashboards.json , below is sample of the content :
`{
    "MainViewPage.xaml": {
        "Items": [
            {
                "$id": "dashboard-tile-13",
                "Title": "Linkedin",
                "Body": "Xamarin Forms IS Grial",
                "Avatar": "https://s3-us-west-2.amazonaws.com/grial-images/v3.0/friend_07.png",
                "BackgroundColor": "#0077b5",
                "BackgroundImage": "https://s3-us-west-2.amazonaws.com/grial-images/v3.0/category_08.jpg",
                "ShowBackgroundColor": false,
                "IsNotification": true,
                "Icon": "",
                "Badge": 0
            },`

**Comment by mrutter** [comment]
Hi @Pirate911.
Just to be sure: can you confirm you're debugging/running your app in English UI culture?
If you're running your app in a different culture, I think you're incurring into this #582.

Let me know.
-m

**Comment by mrutter** [comment]
Hi @Pirate911.
I deleted my previous message because in the meantime, I tried to make the same changes as you.

I was not able to reproduce your issue, I mean that I copied/pasted the original files, I renamed them and I adjusted the .json exactly as in your case. The app works fine.

Following is my code:

**DemoTilesPage.xaml.cs**

`    public partial class DemoTilesPage : ContentPage
    {
        public DemoTilesPage()
        {
            InitializeComponent();

            BindingContext = new DemoTilesViewModel();
        }
    }
`


**DemoTilesPage.xaml**

`<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:MyNamespace" xmlns:grial="clr-namespace:UXDivers.Grial;assembly=UXDivers.Grial"
	x:Class="MyNamespace.DemoTilesPage"
	BackgroundColor="{ DynamicResource BasePageColor }"
	Title="{ grial:Translate PageTitleDashboardMultipleTiles }">
`
**DemoTilesViewModel.cs**

`    public class DemoTilesViewModel : ObservableObject
    {
        public DemoTilesViewModel()
            : base(listenCultureChanges: true)
        {
            LoadData();
        }

        public ObservableCollection<DashboardMultipleTileItemData> Items { get; } = new ObservableCollection<DashboardMultipleTileItemData>();

        protected override void OnCultureChanged(CultureInfo culture)
        {
            LoadData();
        }

        private void LoadData()
        {
            Items.Clear();

            JsonHelper.Instance.LoadViewModel(this, source: "NavigationDashboards.json");
        }
    }
`


**NavigationDashboards.json**

`  "DemoTilesPage.xaml": {
    "Items": [
      {
        "$id": "dashboard-tile-1",
        "Title": "Social",
        "Body": "",
        "Avatar": "",
        "BackgroundColor": "#774C4C4C",
        "BackgroundImage": "https://s3-us-west-2.amazonaws.com/grial-images/v3.0/profile_image.jpg",
        "ShowBackgroundColor": false,
        "IsNotification": false,
        "Icon": "",
        "Badge": 0
      },
`

Let me know if I can help in any way.

By.
-m

PS: I'm not a Grial's employee, I'm just a developer as you, willing to help whenever I can.

**Comment by Pirate911** [comment]
Thank u @mrutter and I really appreciate your kind help . 
I know there is nothing special about the changes I made and it should work smoothly exactly like what you did. I will revert changes down to where I began and see .  Thanks again man

**Comment by Pirate911** [comment]
I added the deleted page and viewmodel again then i ran the app , it works again . Then i deleted the page and viewmodel again and changed the json file and it works .I absolutely have no idea what happened . It could be VS messed up things . Thanks @mrutter for your time .
