### ISSUE TITLE
Default app to arabic language only 

### ISSUE THREAD

**Issue by Pirate911** [UXDivers/Grial-UI-Kit-Support#590]
Hi , 
I've RTL pro edition . My app support both ar and en . Now I need the application to only support arabic language and no more english . 

When the app start it always take english locale even after changing this line in app.cs : 
`CultureSettings.Initialize("ar");`

2nd Question : 
How can I hide LTR button at the navigationbar ?

**Comment by dirivero** [comment]
For the first question you should call this right after the Initialize:

```
CultureSettings.SetCulture("ar");
```

And for the second question you have to **remove** this line from the `App.xaml.cs`

```
RtlSwapHelper.Initialize(MainPage);
```

Hope this helps.

**Comment by Pirate911** [comment]
Thank you
