### ISSUE TITLE
Gorilla does not preview custom Json file data 

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#591]
Hi.. Gorilla live data preview is working with existing json data (DesignTimeJason.json etc etc). So when i create my own navigation view model, new page, new template and new json file then gorilla does not preview the live data but when i debug it on my phone it works. Why is it happening ?

**Comment by dirivero** [comment]
Hi,

Gorilla previews data from the `DesignTimeData.json` file, if you add data on a different json file Gorilla won't be able to see it. 

This means that:
* when you run in preview mode with Gorilla then data always come from `DesignTimeData.json`
* when you run in debug mode your actual view models are used so any data you load in them should be displayed

**Comment by ZiaStansall** [comment]
Ok Understood. Thank you!
