### ISSUE TITLE
Font icons in toolbar items

### ISSUE THREAD

**Issue by vinco83** [UXDivers/Grial-UI-Kit-Support#592]
I saw in a previous topic that the ability to use font icons in toolbaritems was being worked on. Is this possible now, without using Iconize?

**Comment by Pirate911** [comment]
hi , did you find the answer to your questions ? Can you post the answer plz if you know . 

thanks

**Comment by vinco83** [comment]
I did manage to figure it out. You have to use a <FontImageSource ... /> in your ToolbarItem

 ```
<ContentPage.ToolbarItems>
        <ToolbarItem>
            <ToolbarItem.IconImageSource>
                <FontImageSource Glyph="{ x:Static root:GrialIconsFont.Settings }"
                                 Size="20"
                                 FontFamily="{StaticResource GrialIconsFill}" />
            </ToolbarItem.IconImageSource>
        </ToolbarItem>
    </ContentPage.ToolbarItems>
```

**Comment by Pirate911** [comment]
Thank you so much @vinco83 for your reply but I got this error : 
`Views/Theme/RichAboutPage.xaml(17,17): Error: Position 34:17. No property, bindable property, or event found for 'IconImageSource', or mismatching type between value and property. `

**Comment by Pirate911** [comment]
God bless man ...I got it to work after upgrading xamarin.forms to latest ver...You're the best 👍

**Comment by jpbrocca** [comment]
Hi guys, 
keep in mind there is a related bug to `FontImageSource` icons in Xamarin Forms for Android which will cause the icons to be broken when you navigate:

https://github.com/xamarin/Xamarin.Forms/issues/6317

Regards,
JP

**Comment by vinco83** [comment]
Thanks for the info! I was having this exact problem when navigating to another page. All of my GrialIconsFill weren't displaying, and was driving me nuts. I had a mixture of Line + Fill icons in my pages. Gonna try the work around posted in that link...hopefully it works!

**Comment by jpbrocca** [comment]
You are welcome @vinco83!
This is the main reason why we didn't add a sample in our latest update (Grial 3.0.46).
