### ISSUE TITLE
Upgrade from Standard to Pro

### ISSUE THREAD

**Issue by nm-a** [UXDivers/Grial-UI-Kit-Support#594]
Dear team,
Can you guide me to Upgrade from Standard to Pro.

thank you

**Comment by LeoHere** [comment]
Hi @nm-a,

Please write to grialkit at uxdivers.com asking for an upgrade and providing the information of you current license. Please include the name of the grial admin user you use. They will provide further instructions on how to proceed.

Closing the issue now. Feel free to open it again if you need to.
