### ISSUE TITLE
NavigationCardsDescriptionListPage highlight problem

### ISSUE THREAD

**Issue by henriquedrumond** [UXDivers/Grial-UI-Kit-Support#595]
I am opening a bug here, because the support is not able to help me. I downloaded the portal starter project and placed the NavigationCardsDescriptionListPage page. My surprise was that in this project, this page changes the background color when clicked and a visual problem appears in the page transition. I decided to do a test downloading the full project to verify. In this project the background color when an item is selected does not change and the annotated screen transition error does not occur. Support guided me to put the line: SelectionMode = "None" claiming that the app posted on the Apple Store has this line. However, when I do, the page does not detect the SelectItem event, even though it is in the ViewModel.
<img width="390" alt="foto2" src="https://user-images.githubusercontent.com/20068417/60967082-2f3eb400-a2f0-11e9-9b62-44a354d9d35f.png"> - Without Problem Screen from Full project

<img width="404" alt="foto1" src="https://user-images.githubusercontent.com/20068417/60967131-4c738280-a2f0-11e9-9008-4f479e414e51.png"> - Problem Screen from Startet project

Can anybody help me. Tks a lot.

**Comment by dirivero** [comment]
If you set `SelectionMode="None"` the selected item won't work as the selection is disabled as you indicate.

In this case you will have to use the `ItemTapped` event. The fastest (and ugly) way to dispatch this to the view model would be a code behind handler and calling a method in the view model directly.

To keep the code clean and without breaking the Model-View-ViewModel pattern you can dispatch that event straight to a command in the view model by using this event-to-command behavior from Microsoft:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior

Prism has its own nice implementation for this too:
https://prismlibrary.github.io/docs/xamarin-forms/EventToCommandBehavior.html

Here's their code if you want to take a look:
https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Behaviors/EventToCommandBehavior.cs

Hope this helps.

**Comment by henriquedrumond** [comment]
This explain is not directed to my problem. My problem is anything visual. When I tap in my NavigationCardsDescriptionListPage, the highlight is not equal the Grial Demo example. The background color is diferent. You can seen the imagens in attachment in de issue. My impression is that the case is not functional in Grial... You support can't solve my question or give me a position on.

**Comment by dirivero** [comment]
Please take a look at the page `SamplesListPage.xaml` under `Views/DemoApp` folder. You will see that it the `ListView` has both:
* `SelectionMode="None"`
* `ItemTapped="OnItemTapped"`

If you open the code behind file `SamplesListPage.xaml.cs` you will see the method `OnItemTapped` that follows the 1st approach I mentioned in my previous answer. 

You need to do 3 things in the `NavigationCardsDescriptionListPage` to obtain the same results:
* set selection none
* set an ItemTapped handler
* write a handler method in the code behind:

```
private void OnItemTapped(object sender, ItemTappedEventArgs e)
{
    ((NavigationViewModel)BindingContext).SelectedItem = (NavigationItemData)e.Item;
}
```
