### ISSUE TITLE
GridView loads very slowly when there is more data in ItemsSource

### ISSUE THREAD

**Issue by xiaoyu4649** [UXDivers/Grial-UI-Kit-Support#596]
GridView Loads very slowly when there is more data in ItemsSource, and the app is stuck for a long time.
Problem mobile phone screen video compression zip see attachment

[video.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3380466/video.zip)

**Comment by dirivero** [comment]
The GridView does not have virtualization as the Repeater or a regular ListView provide. You shouldn't use it to load too many elements as they will be added to the visual tree altogether and that won't scale.

If that's the scenario you can use a vertical repeater with an item template that has 2 items per row.

Hope this helps.
