### ISSUE TITLE
What about Grial-UI-Kit 3 and Xamarin.Forms 4.x?

### ISSUE THREAD

**Issue by mrutter** [UXDivers/Grial-UI-Kit-Support#597]
First of all, congrats guys! I recognized Grial-UI-Kit by reading this post where you are also mentioned: https://devblogs.microsoft.com/xamarin/xaml-hot-reload/

As you already know, Xamarin.Forms 4.1 is here. I would like to know if Grial-UI-Kit 3 works fine with XF 4.x and, if not, when you will release a compatible version.

We have some minor issues with XF 3.6 (non concerning Grial) that are solved on XF 4.x. Thus we need to upgrade our apps to XF 4.x ... soon.

Thank you.
-m

**Comment by jpbrocca** [comment]
Hi @mrutter, how have you been?
Sorry for the late reply on this.

You should upgrade to Xamarin forms 4.1 without issues, but please let me know if you find any.

Best regards,
HP

**Comment by mrutter** [comment]
Hi @jpbrocca, I'm fine, thank you.
I hope you're doing well too.

I didn't trust upgrading to XF 4.1 but if you write to me that there should be no problem, then I'll try as soon as possible and I'll let you know.

Thank you.
-marcello
