### ISSUE TITLE
DashboardFlatPage is broken

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#60]
The links done work on the dashboardflatpage. If you set the ShowBackgroundColor="false", it starts working. Please advice how we can fix this.

**Comment by jpbrocca** [comment]
Hi @scorpio2000,
Please, add the following to the "DashboardItemTemplate.xaml" file, on the BoxView:

`InputTransparent="true"`

![image](https://cloud.githubusercontent.com/assets/15996999/17112847/2e1ec8c8-527e-11e6-940d-35e6d610951b.png)

Please close this bug after you apply this fix.

Thanks!
JP

**Comment by scorpio2000** [comment]
Thank you for the quick reply. It worked like a charm.
