### ISSUE TITLE
Gorilla Player doesn't work on our recently Grial UIKit project

### ISSUE THREAD

**Issue by victorhgol0713** [UXDivers/Grial-UI-Kit-Support#600]
Hi.! Before the issue, i want to congrats all UXDivers team for the amazing work on Grial UIKit. It's a really time saver and allow us to concentrate our effort on another important aspects of our startup.

I'm writing coz our dev team has some problems with Gorilla Player configuration. After we downloaded our app fro web admin, we proceeded steb by step to setup project and gorilla player on Visual Studio. But, we couldn't see live preview yet (our solution works well, but gorilla player shows and error or gorilla app close unespectedly).

We'll happy if someone from the Grial team give us a hand on this issue asap, so we can use all Grial UIKit as we expected before purshasing it.

Thanks.!

Victor
FitGure Team

**Comment by jpbrocca** [comment]
Hello @victorhgol0713,
thanks for the positive feedback! :)

Could you please add more details about what error/s you get?

A few additional questions:

- Did you download your Grial Solution from Grial Web Admin with Gorilla SDK configured?...you can check more about it here:
http://docs.grialkit.com/grial-web-admin.html#grial-web-admin-downloading-for-the-first-time-add-gorilla-sdk-preconfigured
- You could also check on Microsoft blog the following blog post that will help you to understand how to work with Gorilla and Grial:
https://devblogs.microsoft.com/xamarin/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/

Best regards,
JP
