### ISSUE TITLE
v3 license

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#602]
Hi JP,

Waiting for your help to provision v3 license for my App.

Can you please help?

Thank you

**Comment by jpbrocca** [comment]
Hi @IoTFier, how are you?

You should have received an email from @LeoHere with the details for you to get the v3 license. 

Please confirm.

Regards 
JP

**Comment by IoTFier** [comment]
Hi JP, good morning !

I received an email from @LeoHere, and replying to that one /cc you.

Thank you,

**Comment by jpbrocca** [comment]
Good morning @IoTFier :)

Ok, thanks for your confirmation. 
Will check it soon. 

Regards 
JP

**Comment by IoTFier** [comment]
Hi JP, good afternoon!

Today, I have registered my app for v3.
Waiting on the guidance for RTL Flow.

Thanks
