### ISSUE TITLE
Issue building the Grial Project on Android

### ISSUE THREAD

**Issue by EricJones1975** [UXDivers/Grial-UI-Kit-Support#605]
I have recently purchased the application and I am trying to build the application source code, however I am getting a number of errors (please see screenshot below).

I have cleaned / removed obj and bin folders but all no effect.  Can someone please assist and help?

![image](https://user-images.githubusercontent.com/27342099/61943455-543f5200-af93-11e9-8ada-84efa2a13dff.png)

**Comment by dirivero** [comment]
I suppose you were able to fix this problem, but in anycase, did you try/use a manual nuget package restore? Was it a problem with Xamarin installation?
