### ISSUE TITLE
VideoPlayer and YouTube

### ISSUE THREAD

**Issue by Nanouz** [UXDivers/Grial-UI-Kit-Support#606]
Hi

Is it possible to add a youtube video in de grial videoplayer? I can't seem to get it working.

```
                    <grial:VideoPlayer
                        Grid.Row="1"
                        Source="https://www.youtube.com/watch?v=tHvEd55oAtM"/>
```

Thx for help!

**Comment by LeoHere** [comment]
@Nanouz yes it is possible. I tested with the provided link and seems to be working fine.

![image](https://user-images.githubusercontent.com/16000584/62156079-a3152080-b2e0-11e9-9591-0091e3150fde.png)

This is a screenshot of the video within Gorilla Player Preview.

Did you get an error or something?

**Comment by Nanouz** [comment]
With this code I get a black screen with the text "HTTP is not supported"

**Comment by LeoHere** [comment]
What version of Xamarin Forms are you using?

**Comment by Nanouz** [comment]
My verison is : 4.1.0.581479

**Comment by LeoHere** [comment]
Ok. I found the issue. The video player is doing an HTTP request to get some info about the video and HTTP is not allowed anymore. HTTPs must be used.

The issue will be fixed in the next nuget release. 

In the meantime, you might try `NSExceptionAllowsInsecureHTTPLoads` in iOS and `android:usesCleartextTraffic="true"` as a workaround.

**Comment by Nanouz** [comment]
@LeoHere  How do I exactly set these values in Visual Studio? Can't get it working. I am quite new to Xamarin Forms sry.

**Comment by LeoHere** [comment]
@Nanouz on Friday we did an update (package 3.0.46) that fixes this issue.

**Comment by jpbrocca** [comment]
Hello @Nanouz,

I am closing this issue since it was fixed on our latest stable release (Grial 3.0.46).
Feel free to re-open this issue as needed.

Regards,
JP

**Comment by Nanouz** [comment]
@jpbrocca I updated the grial package but still the video does not load. (Android, can't test iOS yet)

This is the code I use:

```
                        <grial:VideoPlayer                     
                            Source="https://www.youtube.com/watch?v=tHvEd55oAtM">
                        </grial:VideoPlayer>
```
I just see a blackbox where the video should be.

![Video](https://user-images.githubusercontent.com/26550349/65883291-07169c80-e397-11e9-874d-596d782257d7.jpg)

How can I fix this? Thx!

**Comment by jpbrocca** [comment]
Hi @Nanouz,

That is weird.
Do you still get the same error as before?...or now you only get a black surface instead of the whole video player?
Can you check your console and verify if you get any error/information that could help us to understand what could be your issue?

Regards and thanks,
JP

**Comment by Nanouz** [comment]
@jpbrocca  Hmm yes I think this is message from the console is related to the video.

10-03 09:47:10.097 V/MediaHTTPService( 2061): MediaHTTPService(android.media.MediaHTTPService@1e826bc): Cookies: null
10-03 09:47:10.144 V/MediaHTTPService( 2061): makeHTTPConnection: CookieManager created: java.net.CookieManager@d0df645
10-03 09:47:10.144 V/MediaHTTPService( 2061): makeHTTPConnection(android.media.MediaHTTPService@1e826bc): cookieHandler: java.net.CookieManager@d0df645 Cookies: null
10-03 09:47:10.268 D/NetworkSecurityConfig( 2061): No Network Security Config specified, using platform default
10-03 09:47:13.054 W/MediaPlayer( 2061): Couldn't open https://r2---sn-uxaxoxu-cg0k.googlevideo.com/videoplayback?expire=1570117629&ei=ncOVXYDaEZis1wLq16aABg&ip=178.118.116.181&id=o-AAuWCQzi2GNg6euNjp1bt81cOaR9uwy8V0MVHfPgMeEI&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-uxaxoxu-cg0k%2Csn-5hnekn7z&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=15&initcwndbps=1483750&mime=video%2Fmp4&ratebypass=yes&dur=291.689&lmt=1562491616286684&mt=1570095933&fvip=2&fexp=23842630&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgYsFpxh4RJPfUrtf0PrtL2mDUl8Lo6VKev7OtnMEec0UCIQD9Arboh9XPIltvWq70DXjDdX5eARN0ETrvakjp_AZnCA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgL95qklPFzI8BiXWbH9wTopaDgxkmF6vdzkDGZizuxwoCIEYKJG1Ub86i__kgM3ZSDP8bYkjreoLm0SFB1YszM8W-: java.io.FileNotFoundException: No content provider: https://r2---sn-uxaxoxu-cg0k.googlevideo.com/videoplayback?expire=1570117629&ei=ncOVXYDaEZis1wLq16aABg&ip=178.118.116.181&id=o-AAuWCQzi2GNg6euNjp1bt81cOaR9uwy8V0MVHfPgMeEI&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-uxaxoxu-cg0k%2Csn-5hnekn7z&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=15&initcwndbps=1483750&mime=video%2Fmp4&ratebypass=yes&dur=291.689&lmt=1562491616286684&mt=1570095933&fvip=2&fexp=23842630&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIgYsFpxh4RJPfUrtf0PrtL2mDUl8Lo6VKev7OtnMEec0UCIQD9Arboh9XPIltvWq70DXjDdX5eARN0ETrvakjp_AZnCA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgL95qklPFzI8BiXWbH9wTopaDgxkmF6vdzkDGZizuxwoCIEYKJG1Ub86i__kgM3ZSDP8bYkjreoLm0SFB1YszM8W-
10-03 09:47:13.054 V/MediaHTTPService( 2061): MediaHTTPService(android.media.MediaHTTPService@7c58f77): Cookies: null
10-03 09:47:13.382 V/MediaHTTPService( 2061): makeHTTPConnection: CookieHandler (java.net.CookieManager@d0df645) exists.
10-03 09:47:13.382 V/MediaHTTPService( 2061): makeHTTPConnection(android.media.MediaHTTPService@7c58f77): cookieHandler: java.net.CookieManager@d0df645 Cookies: null

Is there a grial example page with a video I can test maybe?

**Comment by Nanouz** [comment]
Could you help me with this please? 

12-03 16:11:36.765 W/MediaPlayer(20068): Couldn't open https://www.youtube.com/embed/tHvEd55oAtM: java.io.FileNotFoundException: No content provider: https://www.youtube.com/embed/tHvEd55oAtM
![Video error](https://user-images.githubusercontent.com/26550349/70068451-4f994300-15f0-11ea-81f0-6dbf81cc28a0.jpg)

**Comment by dirivero** [comment]
Did you try with the regular url? https://www.youtube.com/watch?v=tHvEd55oAtM

**Comment by mijngistel** [comment]
The same problem. This is the error I see in the output:

12-06 15:53:36.627 W/MediaPlayer(31940): Couldn't open https://r2---sn-uxaxoxu-cg0k.googlevideo.com/videoplayback?expire=1575669172&ei=VHnqXaGfOpPY1wKl1bmoAQ&ip=178.118.116.181&id=o-ANpsgheeaMYfWFeUWNXruatgecWljLJuVxYmYyS7b60o&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-uxaxoxu-cg0k%2Csn-5hnekn7z&ms=au%2Crdu&mv=m&mvi=1&pl=15&initcwndbps=1810000&mime=video%2Fmp4&ratebypass=yes&dur=291.689&lmt=1562491616286684&mt=1575647414&fvip=2&fexp=23842630%2C23860862&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAJuTYD9xT_dkjb7uoVL1V2hAJSkxKbZRokSoQOcfsfTzAiEAlYfhqpQApICeMRtR7soVbl3EKci1ZaLtVe-tKOmjiJw%3D: java.io.FileNotFoundException: No content provider: https://r2---sn-uxaxoxu-cg0k.googlevideo.com/videoplayback?expire=1575669172&ei=VHnqXaGfOpPY1wKl1bmoAQ&ip=178.118.116.181&id=o-ANpsgheeaMYfWFeUWNXruatgecWljLJuVxYmYyS7b60o&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-uxaxoxu-cg0k%2Csn-5hnekn7z&ms=au%2Crdu&mv=m&mvi=1&pl=15&initcwndbps=1810000&mime=video%2Fmp4&ratebypass=yes&dur=291.689&lmt=1562491616286684&mt=1575647414&fvip=2&fexp=23842630%2C23860862&c=WEB&txp=2216222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAJuTYD9xT_dkjb7uoVL1V2hAJSkxKbZRokSoQOcfsfTzAiEAlYfhqpQApICeMRtR7soVbl3EKci1ZaLtVe-tKOmjiJw%3D
12-06 15:53:36.637 V/MediaHTTPService(31940): MediaHTTPService(android.media.MediaHTTPService@55474f2): Cookies: null
12-06 15:53:37.933 V/MediaHTTPService(31940): makeHTTPConnection: CookieHandler (java.net.CookieManager@b74735e) exists.
12-06 15:53:37.933 V/MediaHTTPService(31940): makeHTTPConnection(android.media.MediaHTTPService@55474f2): cookieHandler: java.net.CookieManager@b74735e Cookies: null

**Comment by dirivero** [comment]
Can you try updating `UXDivers.Grial` package to 3.0.56-RC version and try again? Make sure you check for pre-released nugets to see it.

**Comment by Nanouz** [comment]
Hi Diego

I finally had time to check it out but now I get this :
[image: afbeelding.png]

What could be the problem? Thx!


Op do 12 dec. 2019 om 21:53 schreef Diego Rivero <notifications@github.com>:

**Comment by jpbrocca** [comment]
Hi @Nanouz,
This bug is fixed in our latest version (3.0.60).

You can read more about this version here:
https://docs.grialkit.com/release-notes.html#release-notes-grial-3060

Regards,
JP

**Comment by Nanouz** [comment]
@jpbrocca Thanks! This seems to be working now.

**Comment by mgernand** [comment]
Hi @jpbrocca,

I encounter the same issue @mijngistel reported in Dec. 2019. I am using UXDivers.Grial 3.1.76.

02-07 17:34:00.132 V/MediaHTTPService( 4106): MediaHTTPService(android.media.MediaHTTPService@512597a): Cookies: null
02-07 17:34:00.133 V/MediaHTTPService( 4106): makeHTTPConnection: CookieManager created: java.net.CookieManager@e6f752b
02-07 17:34:00.133 V/MediaHTTPService( 4106): makeHTTPConnection(android.media.MediaHTTPService@512597a): cookieHandler: java.net.CookieManager@e6f752b Cookies: null
02-07 17:34:00.136 D/NetworkSecurityConfig( 4106): No Network Security Config specified, using platform default
02-07 17:34:00.531 W/MediaPlayer( 4106): Couldn't open https://r2---sn-5hnekn7s.googlevideo.com/videoplayback?expire=1612737238&ei=dhYgYP7KFsjK1gLd3bvQAw&ip=95.90.224.51&id=o-AFs7Nm0ez06qS36JIhHl0784zsKiw6-mDTtfFoNBxssO&itag=18&source=youtube&requiressl=yes&mh=Tu&mm=31%2C29&mn=sn-5hnekn7s%2Csn-5hne6nsz&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=1902500&vprv=1&mime=video%2Fmp4&ns=xWwEnvD2t-JY-KVv2Tuwd5gF&gir=yes&clen=19134596&ratebypass=yes&dur=277.594&lmt=1611589205985886&mt=1612715340&fvip=2&c=WEB&txp=5430434&n=2DzLiYeLaIv-VYn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgLfrJyITs5yFWAmYB163UZTH4L8kCuX77Tj1zou1DMWwCIQCmz_IzHHzRDodGHDtt5nOn-c7x2LrVKY5bUIZnmvdgOQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALrbzSlCAjR09S6DOz4EV8OO27YNPFvVDDhJm5QRw4OvAiEAiOuaCGbjjCTT6hNw-rcqLqZZ-RH7XWioqSAr13ob8ng%3D: java.io.FileNotFoundException: No content provider: https://r2---sn-5hnekn7s.googlevideo.com/videoplayback?expire=1612737238&ei=dhYgYP7KFsjK1gLd3bvQAw&ip=95.90.224.51&id=o-AFs7Nm0ez06qS36JIhHl0784zsKiw6-mDTtfFoNBxssO&itag=18&source=youtube&requiressl=yes&mh=Tu&mm=31%2C29&mn=sn-5hnekn7s%2Csn-5hne6nsz&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=1902500&vprv=1&mime=video%2Fmp4&ns=xWwEnvD2t-JY-KVv2Tuwd5gF&gir=yes&clen=19134596&ratebypass=yes&dur=277.594&lmt=1611589205985886&mt=1612715340&fvip=2&c=WEB&txp=5430434&n=2DzLiYeLaIv-VYn&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgLfrJyITs5yFWAmYB163UZTH4L8kCuX77Tj1zou1DMWwCIQCmz_IzHHzRDodGHDtt5nOn-c7x2LrVKY5bUIZnmvdgOQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALrbzSlCAjR09S6DOz4EV8OO27YNPFvVDDhJm5QRw4OvAiEAiOuaCGbjjCTT6hNw-rcqLqZZ-RH7XWioqSAr13ob8ng%3D
02-07 17:34:00.531 V/MediaHTTPService( 4106): MediaHTTPService(android.media.MediaHTTPService@7d386e2): Cookies: null
02-07 17:34:00.544 V/MediaHTTPService( 4106): makeHTTPConnection: CookieHandler (java.net.CookieManager@e6f752b) exists.
02-07 17:34:00.545 V/MediaHTTPService( 4106): makeHTTPConnection(android.media.MediaHTTPService@7d386e2): cookieHandler: java.net.CookieManager@e6f752b Cookies: null
02-07 17:34:00.564 I/Choreographer( 4106): Skipped 42 frames!  The application may be doing too much work on its main thread.
02-07 17:34:00.591 I/OpenGLRenderer( 4106): Davey! duration=742ms; Flags=0, IntendedVsync=62230998403432, Vsync=62231698403404, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=62231714002900, AnimationStart=62231714045900, PerformTraversalsStart=62231714062900, DrawStart=62231718436900, SyncQueued=62231727137700, SyncStart=62231727169100, IssueDrawCommandsStart=62231727319000, SwapBuffers=62231739828200, FrameCompleted=62231741080000, DequeueBufferDuration=34000, QueueBufferDuration=335000, 
02-07 17:34:01.144 D/MediaPlayerNative( 4106): getMetadata

Did Google change the metadata format again?

**Comment by dirivero** [comment]
@mgernand, the next version we are about to publish will support more videos. Can you send me yours so I can double-check? Feel free to send it at drivero at uxdivers.com if you want. Thanks
