### ISSUE TITLE
[V3] Navigation to another Root page

### ISSUE THREAD

**Issue by Fatihpk** [UXDivers/Grial-UI-Kit-Support#609]
If I load my project and the first Page (DashboardPage) is loaded and I want to load another Page as Root page FROM the DashboardPage:

`Application.Current.MainPage = new MyPage();`

Does it but without the Header Navigation Page. 

How do i load the second Page in a Root page ... (do I call the MainMenuViewModel function?)

**Comment by dirivero** [comment]
If you want to replace the entire navigation stack you can assign the `MainPage` property as you but wrapping the target page with a `NavigationPage` to keep the nav bar:

```
Application.Current.MainPage = new NavigationPage(new MyPage());
```

Another option is to do a await for a `PushAsync(...)` and then remove the previous page:

```
await Navigation.PushAsync(new MyPage());
Navigation.RemovePage(Navigation.NavigationStack[0]);
```

You can read more [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical).
