### ISSUE TITLE
My grial account

### ISSUE THREAD

**Issue by adminVendx** [UXDivers/Grial-UI-Kit-Support#611]
I have already sent four emails to the support team to modify my company login email, but got no response. I'm opening this topic just to try to reach the team through another communication channel as my emails have been ignored for over 1 month.

I work in a startup and would like to change the email used to log in to the Grial Admin site, the email server has had all accounts canceled except the one used for this login, as I can't talk to anyone from Grial. Are you generating costs, please help me ...

**Comment by LeoHere** [comment]
@adminVendx first of all sorry for the inconvenience. 

Recently we had issues with the account hello at grialkit.com. We ended up changing the account to grialkit at uxdivers.com. By this point in time, we should have updated the contact email address everywhere. If you still see it somewhere please let me know.

What email did you write to? If it was the former please email us to grialkit at uxdivers.com. To make it fast, please email us directly from the email address you are using in the Grial admin and let us know the new address. 

If you have any issue please let me know here.

**Comment by adminVendx** [comment]
Hmmm, I did not know. Please email this email informing you of this issue, email this Email Requesting email to hello@uxdivers.com. Thank you!

**Comment by LeoHere** [comment]
@adminVendx if everything is working for you now please close the issue. Tks
