### ISSUE TITLE
Xamarin Forms: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation when using SegmentedTabResources.xaml

### ISSUE THREAD

**Issue by EdwardLamote** [UXDivers/Grial-UI-Kit-Support#613]
Whenever I try to load the **ShippingDetailsPage** a **TargetInvocationException** is thrown.

This is caused by this piece of code in ShippingDetailsPage.xaml:

`Style="{ StaticResource SegmentedTabStyle }"`

Which references to:

```
    <ContentPage.Resources>
        <ResourceDictionary
			Source="/Styles/TabControl/SegmentedTabResources.xaml" />
```

1.  I don't see any other errors/underlines
2.  StaticResource SegmentedTabStyle is able to find SegmentedTabResources.xaml
3.  When I remove "Style="{ StaticResource SegmentedTabStyle }"", the view is able to load but 
     with a strange touch to  the SegmentedTabStyle

### Screenshots
![resourcelink](https://user-images.githubusercontent.com/32507751/63462852-23e8b780-c45c-11e9-9aec-9c611450e586.PNG)
![segmentedtabstyle](https://user-images.githubusercontent.com/32507751/63462853-23e8b780-c45c-11e9-8945-eacb470c5cae.PNG)
![69614034_351556175783163_1788986696352661504_n](https://user-images.githubusercontent.com/32507751/63463346-40d1ba80-c45d-11e9-9029-6e0c5a69755e.jpg)

**Comment by jpbrocca** [comment]
Hi @EdwardLamote,
a couple of questions to help us find the root of the issue:

- Which Xamarin Forms version are you using?
- Are you testing a Grial Full or a Grial Starter downloaded solution?
- Do you get similar issues with other pages or just with this one?

Regards and thanks,
JP

**Comment by EdwardLamote** [comment]
Hi @jpbrocca 

* I'm using version 4.1.0.618606
* I started on a Grial Standard project. Then also bought the Grial Full version. (So I have 2 Grial 
  projects). I was so far in the Grial Standard project that I decided to keep working in that project and just started to copying the code from the Full Version.
* Everything else works really good.

Thanks for answering,

Ed

**Comment by jpbrocca** [comment]
Hi @EdwardLamote,

What happens if you download the Grial Full solution and run it? 
Do you get tje same exception?

Regards 
JP

**Comment by EdwardLamote** [comment]
Hi @jpbrocca 

It runs fine in the Grial Full solution.

I'm like 99% sure I added all references & added all templates to get it to run.
-> no errors anywhere, just when I run it, the TargetInvocation exception pops up.

Kind regards, Ed

**Comment by EdwardLamote** [comment]
Hi @jpbrocca 

Just got some more info about the error by pressing continue...
-> StaticResource not found for key SegmentedTabStyle.

The problem was that I made a new xaml file which didn't had a xaml.cs file underneath.

Image for illustration.

![SegmentedExplained](https://user-images.githubusercontent.com/32507751/63653680-463a4800-c770-11e9-99c2-c55923ba1d78.PNG)
