### ISSUE TITLE
DataGrid not scrolling

### ISSUE THREAD

**Issue by Morhpeuss** [UXDivers/Grial-UI-Kit-Support#615]
### Description
We are using your ShippingDetailPage.xaml in our app, but we have got a problem with vertical scrolling, as you can see in the video below. 

### Basic Information

- Version with issue: 3.0.46
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
    - Android: API 28 

### Screenshots
https://www.screencast.com/t/sf8wkMUIWb

**Comment by dirivero** [comment]
I wasn't able to reproduce this. Here are a couple of questions:
* What version of Xamarin.Forms are you using?
* Does this also happen in real devices?
