### ISSUE TITLE
NavigationPage.HasNavigationBar=True crop footer part .

### ISSUE THREAD

**Issue by Pirate911** [UXDivers/Grial-UI-Kit-Support#618]
Hi , 
@jpbrocca 
I'm having weird behavior . If I use below properties , I get the page with no color at the bottom only . 

` NavigationPage.HasNavigationBar="True"
     BackgroundColor="Transparent"`

I'm using the same code exactly as in the sample provided in the pro edition of grial 3.0.

### Steps to Reproduce
1. Use the xaml page named : PasswordRecoveryPage.xaml
2. add the two lines above at the page header . 
3. run and see the result as in the attached image . 
4.Now remove the two lines you just added and see how the difference.

### Basic Information

- Version with issue: Latest Grial UI Kit 3.0 pro RTL 
- Last known good version:
- IDE:VS on mac .
- Platform Target Frameworks: 
  - iOS:  10 
  - Android: not tested.
- Affected Devices:simulator only
![Simulator Screen Shot - iPhone 8 - 2019-09-13 at 23 57 21](https://user-images.githubusercontent.com/8066281/64894556-be66a000-d682-11e9-91fa-cb85d017e9a9.png)

**Comment by dirivero** [comment]
Hi @Pirate911,

I'm very sorry for the delay. I've been trying to reproduce the behavior today but I couldn't. Can you send me the page to drivero at uxdivers.com?

Thanks!

**Comment by dirivero** [comment]
Were you able to fix this?

**Comment by dirivero** [comment]
I will close this issue as we couldn't repro and didn't get more info. Feel free to reopen or create a new one if needed.
