### ISSUE TITLE
How I can replace my custom logo icon with existing as in example

### ISSUE THREAD

**Issue by SufyanAhmad** [UXDivers/Grial-UI-Kit-Support#620]
Is it possible to replace my custom logo icon with existing as in example 
             
                                          <Label
							Grid.Row="0"
							Grid.RowSpan="2"
							Margin="20,0"
							TextColor="{ DynamicResource InverseTextColor }"
							FontSize="74"
							Text="{ x:Static local:GrialIconsFont.LogoGrialSquare }"
							Style="{StaticResource FontIcon}"
							HorizontalOptions="Start"
							VerticalTextAlignment="Center" />

what steps required that i able to pick my custom icon comes on ui instead of GrialIconsFont.LogoGrialSquare as in example.

**Comment by jpbrocca** [comment]
Hi @SufyanAhmad,

You can do that, but it would be easier to just replace the Label with an Image and user either a bitmap or SVG file.
You can read more about what would be required for you to create your custom font with your logo here:
http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-creating-your-custom-made-icon-font

Regards,
JP
