### ISSUE TITLE
MasterDetailPage HorizontalOptions

### ISSUE THREAD

**Issue by acspacca** [UXDivers/Grial-UI-Kit-Support#621]
I am trying to expand the menu drawer to fill the screen, (today it expands a third of the way with a translucent background probably to allow the drawer to be closed). But I need it to fil the screen without a custom MasterDetailPage. If I try to add FillAndExpand to HorizontalOptionsValue below, I get a visual studio error that says **Can't resolve HorizontalOptions on VisualElement**.

Is there something I can do to achieve this?

<MasterDetailPage MasterBehavior="Default">

<Style x:Key="MainMenuStyle" TargetType="ContentPage">
    <Setter Property="BackgroundColor" Value="#E0E0E0" />
</Style>
          
<Style x:Key="MainMenuOrModalBackgroundStyle" TargetType="VisualElement">
    <Setter Property="grial:Effects.BackgroundGradient" Value="{DynamicResource MainMenuGradient}" />
</Style>

**Comment by jpbrocca** [comment]
Hi @acspacca,
As far as I know, there is no way to make the Master fill the whole screen width unless you create your own.

Regards,
JP
