### ISSUE TITLE
How to add a Toolbar?

### ISSUE THREAD

**Issue by ohgabbey** [UXDivers/Grial-UI-Kit-Support#622]
I've been looking for ways to adding a toolbar but I cannot seem to make it work using Grial. Thank you.

**Comment by jpbrocca** [comment]
Hi @ohgabbey,
I am not sure what you are asking, but here are two possible answers:

1. If you are trying to add a ```NavigationBar``` then you should wrap your ```ContentPage``` in a ```NavigationPage``` in your ```App.xaml.cs```.

2. If you are trying to add ```ToolBarItems``` to your page check this link:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/toolbaritem

Keep in mind this is "not Grial", it is just common Xamarin Forms stuff.

Regards,
JP
