### ISSUE TITLE
Default constructor not found for type __XamlGeneratedCode

### ISSUE THREAD

**Issue by hharng** [UXDivers/Grial-UI-Kit-Support#624]
I created and downloaded a new application using the latest Grial UI Kit.
My iOS app required that I link all assemblies, so I did that.
I got errors, searched for solutions, and here's what I have so far:
1. iOS app "Linker behavior": "Link All".
2. mtouch arguments: --linkskip=UXDivers.Grial --linkskip=UXDivers.Grial.iOS --linkskip=UXDivers.Effects --linkskip=UXDivers.Effects.iOS
3. A custom class is created:
public class PreserveAttribute : System.Attribute
    {
        public bool AllMembers;
        public bool Conditional;
    }
4. A bunched of classes are decorated with this attribute, such as:
[Preserve(AllMembers = true)]
    public partial class MyAppTheme
	{
		public MyAppTheme()
		{
			InitializeComponent();
		}
	}
5. The initial error where the troubleshooting started, related to Grial license, is gone.
6. Now, getting this error on startup, in the FinishedLaunching method: 
System.MissingMethodException has been thrown
Default constructor not found for type __XamlGeneratedCode[...]

### Steps to Reproduce
1. Start a new project with a new license. Add all pages. Download to a Mac.
2. Open in Visual Studio for Mac. Restore all packages. Build.
3. in iOS project, open Options --> iOS Build --> set "Linker behavior"to "Link All". In Ädditional mtouch arguments", add "--linkskip=UXDivers.Grial --linkskip=UXDivers.Grial.iOS"
4. Run. Observe the runtime error described above.

### Expected Behavior
There should be no runtime error.

- Version with issue:
- Last known good version: N/A (a new project).
- IDE: Visual Studio for Mac, Version 8.2.6
- Platform Target Frameworks: 
  - iOS:  10.0
- Nuget Packages: all that came with this downloaded project.
- Affected Devices: all iOS.

Am I missing something, or doing something wrong? Please advise. Thank you!

**Comment by dirivero** [comment]
You should be able to fix this problem by setting the Preserve attribute at assembly level:

 ```[assembly:Preserve(AllMembers = true)]```

There's a specific problem with resource dictionaries included through the `Source` property:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#merged-resource-dictionaries

Grial uses that approach to include the `AppFontFamilies.xaml` dictionary in the `App.xaml`. This won't work unless you set `Preserve` at the assembly level. 

You can bypass this problem by either:
 * copying the font families content into the `App.xaml` directly, or 
 * include it as a merged dictionary referencing as we do with themes dictionaries but, to do that, you will need to define a class for it with `x:Class` and a partial class in a cs file that calls the `InitializeComponent()` in its default constructor.

Hope this helps.

**Comment by hharng** [comment]
Thank you very much!
