### ISSUE TITLE
"Grial UIKit" is seen in popup as if it's the application name instead of real Application name 

### ISSUE THREAD

**Issue by CoderFan1** [UXDivers/Grial-UI-Kit-Support#626]
Good day , I implemented google auth in my current application that's downloaded by grial web portal . The issue is that "Grial UIKit" takes over the application name when signing in to google.com. Please see attached picture on the simulator. The real application name is not "Grial UIKit"
<img width="268" alt="pic" src="https://user-images.githubusercontent.com/55708299/65544549-1f606480-df1c-11e9-89d6-4210a9b7679e.png">

Why is this happening ?

**Comment by jpbrocca** [comment]
Hi @CoderFan1,

It seems there is a bug when the custom solution is generated in Grial Web Admin.

Can you please check you have something like this in your downloaded solution?:
`<YOUR_SOLUTION>.iOS/Resources/en.lproj/InfoPlist.strings`

In my case, I added a culture in Grial Web Admin and in that file, I get `Grial UIKit` as the `CFBundleName`:
![image](https://user-images.githubusercontent.com/15996999/65552503-eb287c00-defa-11e9-99a1-5f33de295b77.png)

Please try replacing the `CFBundleName` with the right one, run again and let me know how it goes.

Best regards,
JP

**Comment by CoderFan1** [comment]
Thanks so much.That fixed it.
I appreciate the help brother.
