### ISSUE TITLE
IOS 13 Fail Access to UITextField's _placeholderLabel ivar is prohibited

### ISSUE THREAD

**Issue by christianharohh** [UXDivers/Grial-UI-Kit-Support#628]
There is an issue while using  Entry PlaceHolder for IOS 13 .

The Placeholder property can't be used in the same way you mention in the examples:

                   
                        <Entry
							Grid.Column="1"
							Grid.Row="0"
							VerticalOptions="Center"
							HorizontalOptions="FillAndExpand"
						Placeholder="{ grial:Translate StringEmail }"/>

The Placeholder attribute will break at run time with 
**Foundation.MonoTouchException:** 'Objective-C exception thrown.  Name: NSGenericException Reason: Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug
Native stack trace:
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98a1c +[NSException raise:format:] + 188
	3   UIKitCore                           0x00007fff47455030 -[UITextField valueForKey:] + 84
	4   Foundation                          0x00007fff256153f0 -[NSObject(NSKeyValueCoding) setValue:forKeyPath:] + 251
	5   UnitedHardwareMobile.iOS            0x0000000102a4b9e9 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x000000011269aae3 0x0 + 4603882211

If you have a solution or new templates please let us Know

**Comment by jpbrocca** [comment]
Hi @christianharohh,
can you please check here?:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/625
