### ISSUE TITLE
Unhandled Exception:  UXDivers.Grial.LicenseException: Internal license validation error. occurred

### ISSUE THREAD

**Issue by fdelcarmen** [UXDivers/Grial-UI-Kit-Support#631]
![LicenseError](https://user-images.githubusercontent.com/30697075/66340100-81549d00-e912-11e9-8fcd-5035ef291768.png)

**Comment by dirivero** [comment]
It may be the same problem reported here https://github.com/UXDivers/Grial-UI-Kit-Support/issues/617

What's the exception stack trace?

**Comment by fdelcarmen** [comment]
Ok.. we are trying this. Thaks !
    El lunes, 7 de octubre de 2019 03:13:17 p. m. AST, Diego Rivero <notifications@github.com> escribió:  
 
 
It may be the same problem reported here #617

What's the exception stack trace?

**Comment by dirivero** [comment]
Did it work?

**Comment by fdelcarmen** [comment]
Yes, it worked. Thanks.

    El martes, 8 de octubre de 2019 02:15:24 p. m. AST, Diego Rivero <notifications@github.com> escribió:  
 
 
Did it work?

**Comment by dirivero** [comment]
Great. I will close the issue then.
