### ISSUE TITLE
CardView Issue Android 4.4

### ISSUE THREAD

**Issue by SDKexplorer** [UXDivers/Grial-UI-Kit-Support#633]
CardView is not being displayed correctly on older version of Android system.
Missing border and drop shadow.

![CardView_BadSample_galaxy_nexus_kit_kat_4_4_api_19](https://user-images.githubusercontent.com/24542530/66553228-6755cd00-eb53-11e9-8aac-e8980f3a26f4.png)
![CardView_GoodSample_nexus_5_oreo_8_1_api_27](https://user-images.githubusercontent.com/24542530/66553229-6755cd00-eb53-11e9-93af-cdd29b90890e.png)

[galaxy_nexus_kit_kat_4_4_api_19 hardware.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3711378/galaxy_nexus_kit_kat_4_4_api_19.hardware.txt)
[nexus_5_oreo_8_1_api_27 _hardware.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3711379/nexus_5_oreo_8_1_api_27._hardware.txt)

**Comment by dirivero** [comment]
The shadow in Android is implemented through the elevation that was included in API 21. 
Grial 3 runs in API 19 but we don't officially support that version, missing elevation is one of the reasons:
http://docs.grialkit.com/overview.html#grial-3-overview-supported-platforms

Market share for Android 4.4 should be pretty small right now but if it's not an option to set min version to Android 5 you can try to simulate the shadow with a png.
