### ISSUE TITLE
TabView styling - text color of tabs not working anymore

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#634]
I'm using Grial Kit, upgraded to 2.7.0 in my project.  I also upgraded Xamarin and VS, changed nothing else.  All of a sudden, the text in my tab controls has changed to white.  No code has changed.  I am wondering, is there something that has changed in Grial?  

### Steps to Reproduce
1.  Use Grial 2.7.0, latest Xamarin and VS, and tab control

### Expected Behavior
You can set the text color of the tab using BarTextColor.  Viewing the tab control through Gorilla Player shows the bar text color as Gray, as expected.  At runtime, however, the text is white. 

### Actual Behavior
The text is white 

### Basic Information
Grial 2.7.0 
VS 16.3.2
Xamarin 16.3.0

### Screenshots
![tabwhitetext](https://user-images.githubusercontent.com/1398909/66702954-df96cc80-ecd2-11e9-87e0-db5b861693e8.png)

**Comment by dirivero** [comment]
Is this a TabbedPage? Android or iOS?

**Comment by attrib75** [comment]
Yes, this is for a tabbed page. The text color appears white on both Android and iOS.  thanks

**Comment by attrib75** [comment]
I don't know which is causing the issue, Grial or Xamarin.  In case, I filed a bug with Xamarin as well.  Feel free to close this if you feel the issue is not with Grial
[https://github.com/xamarin/Xamarin.Forms/issues/8069](url)

**Comment by attrib75** [comment]
HI, just wondering what is the status of this?  What can I provide?

**Comment by dirivero** [comment]
I've tried your sample project and it shows the text, and the selected text with a lighter gray: 
![image](https://user-images.githubusercontent.com/7670773/68310941-99dde180-008f-11ea-901e-0743895fd64f.png)

Is this what you see?

**Comment by attrib75** [comment]
Wow, I don't know what the difference is.  On mine you cannot see the text of the tabs other than the selected tab

**Comment by dirivero** [comment]
Did you find the difference?

**Comment by attrib75** [comment]
nope

**Comment by attrib75** [comment]
I have a generated 'full' Grial solution.  I've changed it only as follows:  Add tabbed page as main page.  The tab text color is not visible for selected or unselected tabs.  The text color is white.  Is there something fundamental I need to change this behavior?  I'm willing to copy our real solution files into the default generated one to start over if we can just get the tab text color to work

**Comment by dirivero** [comment]
I was finally able to reproduce the issue. Please try setting the BarTextColor in the OnAppearing method:

```
    protected override void OnAppearing()
    {
        base.OnAppearing();

        BarTextColor = Color.Red;
    }
```
