### ISSUE TITLE
TabControl Set TabsWidth

### ISSUE THREAD

**Issue by Nanouz** [UXDivers/Grial-UI-Kit-Support#635]
Hi

I am making a profile page and I'm using TabControl with Direct-mode but I don't need all the tabs all the time.

I thought I could do this by hiding the tabs based on data I get from my API but the width is always calculated if all tabs were visible.

Is there a way I can change the width based on how many tabs I need?

I tried binding TabsWith to a property and calculating the value but the width does not change. All my data is loaded async.

How would I make this work?

**Comment by dirivero** [comment]
Good catch @Nanouz.
This is fixed internally and will be released soon.

**Comment by dirivero** [comment]
Try updating `UXDivers.Grial` package to latest version `3.0.54` and it should work fine.
Let me know how it goes.

**Comment by Nanouz** [comment]
Hi @dirivero 

This seems to be working now! Thank you.
