### ISSUE TITLE
Any way to add a custom icon (our own) to the actual Icon-Font package?

### ISSUE THREAD

**Issue by clundstedt** [UXDivers/Grial-UI-Kit-Support#636]
As the title implies we would like to know if there's any way to add a new custom icon to our grialkit solution or more precisely to the pseudo-icon/font-package that you guys hand over with your solution.

We are looking for this particular solution since using this method is way easier to adapt the size/color of the icons across all our functional screens of the solution itself since we are lacking 5 specific ones to implement on it

Or is the only way to work with this by working our particular icons as an image???

Kind Regards and thanks for your help

_PS: Sorry if this is not the right place to ask this but the support chat wouldn't let me write to you guys._

**Comment by dirivero** [comment]
As you indicate, it's better to have the icons in a font so they scale. We provide almost 6k icons out of the box hoping that you will find the ones you need, check here:
http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-find-and-select-available-icons-easily

If you don't find the ones you need, you can always include new icon fonts in the project:
http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-adding-font-icons-to-your-project

Finally, if no icon font available out there suits your needs you can create your own, here are some tips:
http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-creating-your-custom-made-icon-font

Hope this helps.

**Comment by clundstedt** [comment]
> As you indicate, it's better to have the icons in a font so they scale. We provide almost 6k icons out of the box hoping that you will find the ones you need, check here:
> http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-find-and-select-available-icons-easily
> 
> If you don't find the ones you need, you can always include new icon fonts in the project:
> http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-adding-font-icons-to-your-project
> 
> Finally, if no icon font available out there suits your needs you can create your own, here are some tips:
> http://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-creating-your-custom-made-icon-font
> 
> Hope this helps.

Thanks for your quick reply we will look into the provided links :)!
