### ISSUE TITLE
Unable to find package UXDivers.Analyzers - "api.nuget.org/v3-flatcontainer/uxdivers.analyzers/index.json"

### ISSUE THREAD

**Issue by celsosz** [UXDivers/Grial-UI-Kit-Support#637]
Hi. Someone here having the same issue?

Error: "NotFound https://api.nuget.org/v3-flatcontainer/uxdivers.analyzers/index.json"

____________________________________
Restoring packages for MonoAndroid,Version=v9.0...
  GET http://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.Analyzers'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/uxdivers.analyzers/index.json
  OK http://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.Analyzers'&semVerLevel=2.0.0 980ms
  NotFound https://api.nuget.org/v3-flatcontainer/uxdivers.analyzers/index.json 632ms
____________________________________

I am using Visual Studio for Mac.

Thanks.

**Comment by dirivero** [comment]
Hi. We are looking into fixing that. Thanks for reporting.

You can fix it yourself by removing the following line from your .net standard `csproj` project file:

```
<PackageReference Include="UXDivers.Analyzers" Version="1.0.5" />
```

Or from Visual Studio, just right click this nuget package and choose Remove:

![image](https://user-images.githubusercontent.com/7670773/67161608-8eba5000-f332-11e9-89dd-3b3df80c3855.png)

**Comment by celsosz** [comment]
It worked. Thank you very much for responding very quickly.

Just for curiosity. What is the impact of removing that package?

Best regards,
Celso.

**Comment by LeoHere** [comment]
Hi. There was a bug in the program that generates your custom version of Grial. It was not removing 'UXDivers.Analyzers' from your solution. The problem was fixed.

Please let us know if you have any questions.

**Comment by celsosz** [comment]
Thanks.
