### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null. Parameter name: assemblyFile'

### ISSUE THREAD

**Issue by aicukltd** [UXDivers/Grial-UI-Kit-Support#638]
I have just purchased a license to the Pro version, configured my app in the Admin area, downloaded the .SLN and the Xamarin files, open app in VS2019, build, run and then I get an exception thrown:

**System.ArgumentNullException: 'Value cannot be null. Parameter name: assemblyFile'**

### Description
It seems something is attempting to be loaded in memory and is failing.

### Steps to Reproduce
1. Setup Project in Admin
2. Configure with screens
3. Set theme to dark
4. Download SLN
5. Build, Run
6. Exception on Splash Screen

### Expected Behavior
The application should launch with the screens.

### Actual Behavior
Exception is thrown.

### Basic Information

- Version with issue: Latest AS AT this post date.
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages: Unmodified from generated solution.
- Affected Devices:

### Screenshots
![Error](https://user-images.githubusercontent.com/10234035/67163553-52a1e200-f368-11e9-9a1a-1b70c0fc964b.png)

**Comment by dirivero** [comment]
Hi @aicukltd, what is exception stack trace?

**Comment by aicukltd** [comment]
I unfortunately cannot see any stack trace of the exception at all. Very odd.

**Comment by dirivero** [comment]
I don't remember seeing this... what happens if you let it continue?
Do you have latests Xamarin versions?
Same if you target Android?

**Comment by aicukltd** [comment]
I have all of the latest versions on the MAC and on VS19.

If I click continue it freezes VS19 forcing a restart.

In the call stack it just shows up as [External Code].

**Comment by aicukltd** [comment]
![Error-1](https://user-images.githubusercontent.com/10234035/67215778-0020fe00-f41a-11e9-9b1d-b60b7d35cd4c.png)

**Comment by dirivero** [comment]
Have you tried closing VS, removing bin & obj folders from the 3 projects and then reopen / rebuild?

**Comment by aicukltd** [comment]
Yes I have.


Kind Regards,
Oliver Christie
AIC UK Ltd
Full Spectrum Solutions
Manchester, UK
W: https://www.aicuk.ltd
P: +44 (0) 20 7160 6320
This email is intended for the recipient only. Access to this message by any other person is not permitted. If you are not the intended recipient you must not use, disclose, distribute, copy, print or rely on this email. If an addressing or transmission error has misdirected this email, please notify the author by replying to this email. Recipients should note that all email traffic on MoD/GSi/Commercial systems are subject to monitoring and auditing.
P Save a tree...please don't print this e-mail unless you really need to!
________________________________

**Comment by dirivero** [comment]
Can you send me your order id to: d r i v e r o at uxdivers.com? so I can check your your app configuration.

**Comment by dirivero** [comment]
I'm closing this issue as I haven't received further information. Feel free to reopen if the problem persists.

**Comment by aicukltd** [comment]
In that case I request a full refund.


Kind Regards,
Oliver Christie
AIC UK Ltd
Full Spectrum Solutions
Manchester, UK
W: https://www.aicuk.ltd
P: +44 (0) 20 7160 6320
This email is intended for the recipient only. Access to this message by any other person is not permitted. If you are not the intended recipient you must not use, disclose, distribute, copy, print or rely on this email. If an addressing or transmission error has misdirected this email, please notify the author by replying to this email. Recipients should note that all email traffic on MoD/GSi/Commercial systems are subject to monitoring and auditing.
P Save a tree...please don't print this e-mail unless you really need to!
________________________________

**Comment by dirivero** [comment]
Can you contact me at d r i v e r o at uxdivers.com? Thanks
