### ISSUE TITLE
iOS13 - text not visible in the Entry control in dark mode

### ISSUE THREAD

**Issue by bprochniak** [UXDivers/Grial-UI-Kit-Support#639]
Hi Grial-UI-Kit-Support,

I'm using Xamarin.Forms 4.3.0.851321 and UXDrivers.Grial 3.0.54. The text of the Entry control is not visible when IsEnabled = 0. This happens only in dark mode (iOS 13).

Thanks in advance.

**Comment by LeoHere** [comment]
@bprochniak did you tried opting-out dark mode? See [this](https://montemagno.com/opt-out-of-dark-mode-on-ios-android-uwp-and-macos/).
