### ISSUE TITLE
How to use AutoCompleteTextView in Grial ?

### ISSUE THREAD

**Issue by DilipNikam** [UXDivers/Grial-UI-Kit-Support#64]
Can you please let me know how we can implement AutoCompleteTextView with Grial theme.  we can not use platform specific View's on Xamarin Forms (PCL) ContentPage. So what is the way and how we can implement this.

Really appreciate if provide any sample.

**Comment by jpbrocca** [comment]
Hi @DilipNikam,

You can combine a SearchBar and a ListView, try with this control:
https://github.com/XLabs/Xamarin-Forms-Labs/wiki/AutoCompleteView

Best,
JP

**Comment by DilipNikam** [comment]
Thanks @jpbrocca,

Sure...I will try this example as well. 

In my project I have form where I will first need to displayed the location search autocomplete and below this need show google MAP. Currently I have tried one search box and List control this will work. But when List-items populated its goes behind of MAP. I wanted to render list-items above the map. So How can I bring this searched list items above the map ?

For example Please have look of the below image.

**Comment by jpbrocca** [comment]
Hi @DilipNikam,

Probably this is related to how you created the layout to contain the SearchBar + ListView + Map.
If you want things to overlap you will need to go with a Grid and use same row number to make elements to render one on top of the other.

I suggest you try with another XAML file and make everything visible with static data (gorillaplayer.com will help you with that), then once you are sure your layout works move this code to your real page.

Hope that helps.

Best,
JP
