### ISSUE TITLE
HTTP Error 503. The service is unavailable - http://nuget.uxdivers.com/grial

### ISSUE THREAD

**Issue by JigarM** [UXDivers/Grial-UI-Kit-Support#640]
Hello Devs,

I can’t able to integrate Grial with my project.
When I added Grial Kit in the VS 2019 Nuget Sources section, It says “http://nuget.uxdivers.com/grial” Unreachable.

So, I tried to hit the URL and found that the URL throws an error **“Service Unavailable”.
HTTP Error 503. The service is unavailable.**
![ServiceUnavailable](https://user-images.githubusercontent.com/2315291/67603611-0d7e1580-f797-11e9-8f88-8ab592a7206c.png)

PLEASE DO THE FIX ASAP.
Let me know if I am missing something here.

**Comment by LeoHere** [comment]
@JigarM the problem has been fixed. Sorry for the inconvenience.

Please confirm it is working for you.

**Comment by JigarM** [comment]
Great @LeoHere.
Let me have a look at it

**Comment by JigarM** [comment]
@LeoHere It's working. 
Thanks for the help.
