### ISSUE TITLE
ExtendedCarouselViewControl does not show anything with SDK 13.1 iOS

### ISSUE THREAD

**Issue by heromcp** [UXDivers/Grial-UI-Kit-Support#641]
### Description
I'm working with GriakKit UXDivers.Grial 3.0.54 and Xamarin.Forms 4.1.0.555618. Everything was fine until the iOS SDK was updated to the latest version 13.1. Since then the screen that makes use of ExtendedCarouselViewControl shows nothing,

In android everything is ok

### Steps to Reproduce

1. Upgrade SKD from iOS to 13.1

**Comment by dirivero** [comment]
I haven't seen this before. We've been using 13.1 extensively without problems with the carousel view. The current version of our demo app in the app store was compiled with that SDK. 

Does this happen with a new solution downloaded from the web admin too?

**Comment by dirivero** [comment]
I'm going to close this issue as we didn't get more information. Feel free to contact us again if the problem persist.
