### ISSUE TITLE
TabControlCustomSamplePage as MainNavigation system

### ISSUE THREAD

**Issue by mistersam91** [UXDivers/Grial-UI-Kit-Support#642]
Hi,

I would like to use your TabControlCustomSamplePage as my main navigation system in my application.

How can i achieve this ? 

In App.xaml should i do this : 

`public static Page GetMainPage()
        {
            return new NavigationPage(new TabControlCustomSamplePage());
        }`

How can i handle the system to navigage to a detail page (for example in chat) ?
How can i handle back button on each page ?

Thanks for your help

**Comment by dirivero** [comment]
Hi @mistersam91,

The tab control doesn't support any Xaml content (and even DataTemplates) but not ContentPages. That means that if you navigate with a PushAsync to a detail page from one of the tab items, the tab control that is part of the first page will be pushed too. 

Going back to your chat example... what you can achieve with the tab control is the same navigation that WhatsApp uses for the chat list -> chat detail. In the chat detail you don't have the tab options visible.
