### ISSUE TITLE
Background VideoPlayer on Android doesn't AspectFill

### ISSUE THREAD

**Issue by kcrandall** [UXDivers/Grial-UI-Kit-Support#643]
On iOS the background video player will properly adhere to the aspect fill settings but on Android it just uses letterboxing.
### Description

The video player doesn't fill the screen with AspectFill
### Steps to Reproduce

```
 <Grid>
            <grial:VideoPlayer
                Aspect="AspectFill"
                VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand"
                Source="{ Binding BackgroundVideo }"
                Style="{ StaticResource BackgroundVideoPlayerStyle }"
                Margin="{ grial:OnOrientationThickness Landscape='-200,0', Portrait=0 }" />
</Grid>
```
### Expected Behavior

Video player should fill the screen
### Actual Behavior

video player is letterboxed on android
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android:28 
- Android Support Library Version: 
- Nuget Packages: 3.0.54
- Affected Devices: pixel 3 emulator

### Screenshots

<img width="461" alt="Screen Shot 2019-11-06 at 2 58 52 PM" src="https://user-images.githubusercontent.com/6306086/68333117-f51ace80-00a5-11ea-9736-bf2bcc5f107f.png">

**Comment by dirivero** [comment]
Do you see the same behavior in the VideoCarouselHighlightsPage from Grial's demo app? 

I've tried your snippet in empty page with a generic simulator and in a Samsung device and the player fills the screen properly.

**Comment by dirivero** [comment]
I will close this issue as we couldn't repro and didn't get more info. Feel free to reopen or create a new one if needed.
