### ISSUE TITLE
Grial Licence Issue

### ISSUE THREAD

**Issue by ZiaStansall** [UXDivers/Grial-UI-Kit-Support#647]
Hi 

we have been developing our app using Grial Kit and renewing the licence in every month since its in "Development Mode". Now our first phase development is complete and we want to change the License Mode to "Production Mode". So Now the question is, will we have the option to change it back to "Development Mode" for our 2nd phase app development in future ? 

Thanks!

**Comment by LeoHere** [comment]
@ZiaStansall once you move your app to Production mode you can't change it back to Development mode. Being in production mode means that your app name and bundle identifier are fixed. You can't change them anymore from the Grial Web Admin. That is the only restriction. You can keep working on your app, as usual, implementing features and fixing bugs, etc. 

Does that answer your question?

**Comment by ZiaStansall** [comment]
Yes exactly that's what we wanted to know. Thanks for the fast reply!
