### ISSUE TITLE
Splash screen duration

### ISSUE THREAD

**Issue by MehmetCANKAYA** [UXDivers/Grial-UI-Kit-Support#648]
Hi, Can we reduce manualy spalsh screen duration in opening?

**Comment by santiagoBaro** [comment]
The splash screen will be as long as the app takes to start, it is a place holder while the app loads.
if the problem is happening in android, check out this link
https://devblogs.microsoft.com/xamarin/faster-startup-times-with-startup-tracing-on-android/

**Comment by MehmetCANKAYA** [comment]
> The splash screen will be as long as the app takes to start, it is a place holder while the app loads.
> if the problem is happening in android, check out this link
> https://devblogs.microsoft.com/xamarin/faster-startup-times-with-startup-tracing-on-android/

Thanks for your feedback.
