### ISSUE TITLE
Add a Menu Item to Custom Navigation Bar

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#65]
Hello,

 We have a page where we use the toolbaritems.secondary property to create a fly out menu as mentioned here: http://forums.xamarin.com/discussion/comment/72080/#Comment_72080

We want to replace the navigation bar with the custom Navigation Bar from Grial. Is it possible to create a fly out menu button from the custom navigation bar?

thanks,
Pawan

**Comment by jpbrocca** [comment]
Hi @scorpio2000,
This is not a feature provided by Grial's CustomNavBar but you can implementation your own using a Grid layout as main container then the items can be similares through a ListView.
You will need to code the toggle visibility behavior.

Best,
JP

**Comment by scorpio2000** [comment]
Thanks Juan.

**Comment by jpbrocca** [comment]
You are welcome!
