### ISSUE TITLE
Make the top bar colors dynamically  with the same color of the page in Android and IOS 

### ISSUE THREAD

**Issue by wpanduka** [UXDivers/Grial-UI-Kit-Support#650]
we wanted the top bar of each page to have the same color of the page in android and ios pages , we have used the BackgroundColor="colour name" properties and BackgroundImage="" properties but no use , when we use those it always totally different from the top bar color and the page colors . even we tried with the Mainactivity theme , since theme only carries single color we cant change the page top bar colors dynamically with respective to pages colors ( this applies to the top-bar text color as well , because we are unable to change the top-bar text color dynamically with respect to the page colors)

Some of the screenshots of the out put what we are expecting as below 
<img width="290" alt="screencapture-app-zeplin-io-project-5d9ab433d39ef01ec17f5372-screen-5d9ab9dead37321f11aefbf5-2019-11-26-11_47_59" src="https://user-images.githubusercontent.com/19517563/69604259-e8edb580-1042-11ea-9c5d-5b912bad29e5.png">
<img width="292" alt="screencapture-app-zeplin-io-project-5d9ab433d39ef01ec17f5372-screen-5d9c67c2488adf20cd5ecdff-2019-11-26-11_47_40" src="https://user-images.githubusercontent.com/19517563/69604263-e9864c00-1042-11ea-899f-bcb47034c339.png">
<img width="291" alt="screencapture-app-zeplin-io-project-5d9ab433d39ef01ec17f5372-screen-5da53f803466c32f9c0b54f5-2019-11-26-11_47_11" src="https://user-images.githubusercontent.com/19517563/69604265-e9864c00-1042-11ea-8560-32bd5436e258.png">

as you can see the red square area i have highlighted to see where we are expecting the top bars and the text should be dynamically change , please let me know what should i do to achieve the above result, your help highly appreciated .

**Comment by dirivero** [comment]
To have the color vary based on the page you should use set the Grial's `IsBarTransparent` property on the *NavigationPage*:

http://docs.grialkit.com/navbar.html

```grial:GrialNavigationPage.IsBarTransparent="True"```

By doing that, you Content Pages will start rendering right at the top of the screen behind the actual NavBar content (back button, title, etc). This means that the navbar background will be totally defined by your Content Page.
