### ISSUE TITLE
HTML Label Styling

### ISSUE THREAD

**Issue by Nanouz** [UXDivers/Grial-UI-Kit-Support#651]
Hi

I am using a Label with TextType HTML and I noticed the <blockqoute> element has a purple color. How can I change this in my own theme color? (See screenshot)

Thx!

![blockquote](https://user-images.githubusercontent.com/26550349/69627553-235b5080-104b-11ea-908c-fcff7a341536.jpg)

**Comment by dirivero** [comment]
What do you want to achieve exactly? Making the purple part of your app theme or turning the purple into another color that matches your theme?

If it's the second option, you will need to modify the HTML code you are getting so it renders another color. The HTML is self-contained, Grial themes can't affect that directly.

Just look for the color you want to change in the HTML string and replace it by something better dynamically before setting it as the Label's text.

**Comment by Nanouz** [comment]
I see thx! Would you have any code example for outputting HTML that is styled?

**Comment by dirivero** [comment]
That's a hard question to answer as it would completely depend in the kind of format you want to achieve. 

If it's just replacing a color with a different one you can try string.Replace(). 

You can always copy the HTML text into a plain html page, open it in a browser and freely play with it.

**Comment by Nanouz** [comment]
Thank you!
