### ISSUE TITLE
Icon and text on a button 

### ISSUE THREAD

**Issue by Nodessa** [UXDivers/Grial-UI-Kit-Support#652]
Hi, 

i was just wondering, how do i an icon on a button and text as well?

**Comment by jpbrocca** [comment]
Hi @Nodessa,

Check this link:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/button#using-bitmaps-with-buttons

You can specify how the `Text` and `ImageSource` properties are arranged on the `Button` using the [ContentLayout](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.button.contentlayout#Xamarin_Forms_Button_ContentLayout) property of `Button`.

Somehting like this:

```
<Button Text="Left icon" ContentLayout="Left,10" ImageSource="image filename" />
<Button Text="Top icon" ContentLayout="Top,0" ImageSource="image filename" />
<Button Text="Right icon" ContentLayout="Right,0" ImageSource="image filename" />
<Button Text="Bottom " ContentLayout="Bottom,0" ImageSource="image filename" />
```

Cheers,
JP

**Comment by Nodessa** [comment]
Hi JP @jpbrocca thank you for quick answer. I have tried that, but if I want to use the GrialIconFont it doesnt display any icon  if i use ImageSource. Should I just save the icon then? 
Sorry, I am a begginer.

**Comment by jpbrocca** [comment]
You should use [FontImageSource](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.fontimagesource?view=xamarin-forms) as your image source.

Something like this:

```
<Button Text="Left icon" ContentLayout="Left,10">
     <Button.IconImageSource>
               <FontImageSource 
                         Glyph="{ x:Static root:GrialIconsFont.Settings }"
                         Size="20"
                         FontFamily="{ StaticResource GrialIconsFill }" 
               />
     </Button.IconImageSource>
</Button>
```

**Comment by Nodessa** [comment]
Thank you so much

**Comment by jpbrocca** [comment]
Hi @Nodessa,

You are welcome :)

I am closing this issue to keep things tidy, but feel free to reopen as needed.

Regards,
JP
