### ISSUE TITLE
.  Name: NSGenericException Reason: Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug

### ISSUE THREAD

**Issue by SufyanAhmad** [UXDivers/Grial-UI-Kit-Support#653]
I am getting following exception when running app on IOs.
 Name: NSGenericException Reason: Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug

**Comment by jpbrocca** [comment]
Hi @SufyanAhmad,

which Grial version are you using?

**Comment by SufyanAhmad** [comment]
By updating version issue resolved. Thank you @jpbrocca
