### ISSUE TITLE
using DashboardCarouselPage as main page in project

### ISSUE THREAD

**Issue by MehmetCANKAYA** [UXDivers/Grial-UI-Kit-Support#655]
How can I use DashboardCarouselPage as landing page like grial demo app on Google play? Can you advise me or send an example?

**Comment by dirivero** [comment]
Open the `App.xaml.cs` file and return that page in the main page method:

```return new NavigationPage(new DashboardCarouselPage());```

Wrapping it into a NavigationPage will allow you to push new pages using the standard Xamarin navigation mechanism.

Hope this helps.
