### ISSUE TITLE
Use grial:translate

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#656]
Hi,

I use the dashboardCarouselPage. it works great. It uses a template DashboardCarouselPage and use a json file to fill data.

I would like to use json file as you provide for my static texts. And have a translation of the strings in the json at run time through the grial:translate.

However when I go in the code and try to use grial:translate with the binding of the json it's not working.

How can I fix this?

Text="{grial:Translate {Binding Name} }"

Thanks,

**Comment by MehmetCANKAYA** [comment]
I have the same question. Please respond if possible. Thank you.

**Comment by dirivero** [comment]
Hello, for the static texts I recommend you to use the regular resource files approach from .net. Actually, the `grial:Translate` extension works with those .resx files.

You can read more here: 
http://docs.grialkit.com/i18n-page.html

**Comment by dalton5** [comment]
Not clear to me. Let's see.

I have a json which lists values for two pages in the onboarding.

How can I achieve this by using the translation of the values in the json? Even if I want to use resources.

**Comment by dirivero** [comment]
Let's say your json looks like this:
```
{
  "OnboardingText1" : "...",
  "OnboardingText2" : "..."
}
```

If you move those strings to the `AppResources.resx` file:

```
<data name="OnboardingText1" xml:space="preserve">
    <value>...</value>
</data>
<data name="OnboardingText2" xml:space="preserve">
    <value>...</value>
</data>
```

You can consume them from the XAML like this:

```
<Label Text="{ grial:Translate OnboardingText1 } />
<Label Text="{ grial:Translate OnboardingText2 } />
```

**Comment by dalton5** [comment]
Ok thanks.

And when I have:

In my dashboard page:

` <cv:CarouselViewControl.ItemTemplate>
                    <DataTemplate>
                        <local:DashboardCarouselHeaderItemTemplate />
                    </DataTemplate>
                </cv:CarouselViewControl.ItemTemplate>`

And in my local:DashboardCarouselHeaderItemTemplate I have 

 <Label
						Text="{ Binding Name }"
						FontFamily="{ DynamicResource FancyFontFamily }"
						TextColor="{ DynamicResource InverseTextColor }"
						FontSize="32"
						VerticalOptions="Center"
						VerticalTextAlignment="Center" />

How can I have the grial trnaslate on the text property?

Thanks

**Comment by dirivero** [comment]
In that case the string is dynamic so you'd have to provide its value in the View Model of the page. 

Following your example, you can have the `Name` property of the items returning a value from the AppResoruces like this:

```
public class Item
{
  private string _nameKey;

  public Item(string nameKey)
  {
    // Stores the resource key of this item's name
    _nameKey = nameKey;
  }

  public string Name => AppResources.ResourceManager.GetString(_nameKey);

  ...
```

**Comment by MehmetCANKAYA** [comment]
I did not understand that.
 in local:DashboardCarouselHeaderItemTemplate has the following codes

					Text="{ Binding Name }"
					FontFamily="{ DynamicResource FancyFontFamily }"
					TextColor="{ DynamicResource InverseTextColor }"
					FontSize="32"
					VerticalOptions="Center"
					VerticalTextAlignment="Center" />

	Text="{ Binding Name }" value   is coming from  NavigationDashboards.json  file as the following.

 {
        "$id": "dashboard-item-3",
        "Name": "Settings",
        "BackgroundColor": "#FFCD195E",
        "BackgroundImage": "https://s3-us-west-2.amazonaws.com/grial-images/v3.0/category_07.jpg",
        "Icon": "",
        "ItemCount": 15,
        "Description": "",
        "Badge": 9
      },
      {
        "$id": "dashboard-item-4",
        "Name": "Messages",
        "BackgroundColor": "#FF56329A",
        "BackgroundImage": "https://s3-us-west-2.amazonaws.com/grial-images/v3.0/category_03.jpg",
        "Icon": "",
        "ItemCount": 10,
        "Description": "",
        "Badge": 0
      },

****And how can we translate these static values (like Settings,  Messages etc.) that are in the json file to another languages.****

Thanks.

**Comment by LeoHere** [comment]
@MehmetCANKAYA 

In a XAML page, you usually have Static content and Dynamic content. 
* Static content usually is translated using the `Translate` extension. In that case, strings resides in the resx files. 
* Dynamic content is usually bound to the view model. The JSON files provided provides sample data, and mimic design-time view models. If you need to translate your dynamic content you usually should handle that in your view models.

I hope it helps.
