### ISSUE TITLE
Can't seem to use a Font other than Grial for Icons

### ISSUE THREAD

**Issue by webcognoscere** [UXDivers/Grial-UI-Kit-Support#658]
Hi,

I've recently purchased Grial Kit and think it's fantastic, well done!

I'm having an issue trying to use some icons from the other fonts, such as Material, Fontawesome etc. It simply doesn't work, no icon is shown if I use any icon outside of the GrialIconsFont.

### Description
Example: If I have the following label:
`<Label
								TextColor="{ DynamicResource BaseTextColor }"
								Text="{ x:Static local:GrialIconsFont.Calendar }"
								Style="{ StaticResource FontIcon }" />`

and I change the icon to:
` <Label
								TextColor="{ DynamicResource BaseTextColor }"
								Text="{ x:Static local:MaterialCommunityIconsFont.ClockStart }"
								Style="{ StaticResource FontIcon }" />`

No icon appears.

Any other font, other than GrialIconsFont doesn't show up.

I've downloaded the starter and full version and have added Grial to an existing project, but even if I try changing an icon in both the starter and the full project, the same behavior occurs.

Your help would be greatly appreciated.
Thanks

**Comment by jpbrocca** [comment]
Hi @webcognoscere, thanks a lot for the positive feedback :)
We put a lot of love on Grial!

About your issue:
Please make sure you followed all steps here:
https://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-changing-default-icons-font

...and you will also need to make sure the font you want to add has the right build action as well as it is present in `info.plist` in iOS:
https://docs.grialkit.com/working-locally.html#working-locally-using-font-icons-adding-font-icons-to-your-project

Let me know how it goes.

Regards,
JP

**Comment by webcognoscere** [comment]
Hi JP,

So I don't want to change the font icons, I just want to be able to use different icons for different labels.

Does this mean that I can't mix and match icons basically, that if I want to use Material icons I'd need to set the whole app to use the Matrial Font?

Thanks again

**Comment by jpbrocca** [comment]
Hi @webcognoscere,

Yes, you can use different font icons in your app.
You just need to create an additional style for those (`FontIcon` is meant to be used globally across your app, so you will need to create a specific style for each font icon font family). Another option is just to set the specific `FontFamily` directly on the `Label` as in the example below:

```
<StackLayout 
    VerticalOptions="Center"
    HorizontalOptions="Center"
    Orientation="Horizontal"
>
    <Label 
        Style="{ StaticResource FontIcon }"
        FontSize="54"
        Text="{ x:Static local:GrialIconsFont.Calendar }"
        TextColor="{ DynamicResource OverImageTextColor }"
        VerticalOptions="Center"
    />

    <Label 
        FontFamily="{ DynamicResource GrialIconsFill }"
        FontSize="54"
        Text="{ x:Static local:GrialIconsFont.Calendar }"
        TextColor="{ DynamicResource OverImageTextColor }"
        VerticalOptions="Center"
    />
    
    <Label 
        FontFamily="{ DynamicResource Ionicons }"
        FontSize="54"
        Text="{ x:Static local:IoniconsFont.PersonStalker }"
        TextColor="{ DynamicResource OverImageTextColor }"
        VerticalOptions="Center"
    />

    <Label 
        FontFamily="{ DynamicResource MaterialCommunityIcons }"
        FontSize="54"
        Text="{ x:Static local:MaterialCommunityIconsFont.ClockStart }"
        TextColor="{ DynamicResource OverImageTextColor }"
        VerticalOptions="Center"
    />
</StackLayout>
```

![image](https://user-images.githubusercontent.com/15996999/70650332-a70d6380-1c2d-11ea-8024-93fd29ca5faf.png)

Regards,
JP

**Comment by webcognoscere** [comment]
Hi JP,

Awesome, this is the line I was missing:
'FontFamily="{ DynamicResource MaterialCommunityIcons }""'

Thank you very much!
-Miguel
