### ISSUE TITLE
VideoPlayer Ended event not fired

### ISSUE THREAD

**Issue by martinlasalle** [UXDivers/Grial-UI-Kit-Support#659]
### Description
The Ended event is never fired within the VideoPlayer control

### Steps to Reproduce
<grial:VideoPlayerContainer  Grid.Row="2" Grid.Column="0" Grid.ColumnSpan="3">
                    <grial:VideoPlayer x:Name="VideoPlayer" AutoPlay="True" Ended="VideoPlayer_OnEnded" Error="VideoPlayer_OnError"
                                       SkinTemplate="{StaticResource VideoPlayerSkin}" />
                </grial:VideoPlayerContainer> 

private void VideoPlayer_OnEnded(object sender, EventArgs e)
        {
            this.StackLayoutQuiz.IsVisible = true;
            this.btnSubmit.IsVisible = true;
        }

### Expected Behavior
VideoPlayer_OnEnded should be called at the end of the video

### Actual Behavior
never fired

### Basic Information

- Version with issue: Grial 3 Pro
- Last known good version:
- IDE: Visual Studio 2019 Windows
- Platform Target Frameworks: 
  - iOS:  13.1.3
  - Android: 9

**Comment by dirivero** [comment]
Can you try updating `UXDivers.Grial` package to 3.0.56-RC version and try again? Make sure you check for pre-released nugets to see it.

**Comment by martinlasalle** [comment]
the 3.0.26-RC release fixed the problem! Thank you!
