### ISSUE TITLE
Just purchased and can't make it work! I have updated the nugets pakages, lot of errors...

### ISSUE THREAD

**Issue by marchanddesable** [UXDivers/Grial-UI-Kit-Support#66]
I can't compile the solution:

I have visual studio 2015
I updated the nugets pakages
Now the version of xamarin forms is v2.3.1.114
Xamarin.Android.Support.v7.AppCompat v23.4.0.1

I have a lot of error with the files Style.xml and values.xml

here are some of them:

Error retrieving parent for item: No resource found that matches the given name '@style/TextAppearance.AppCompat.Title'.
Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.Dialog'.
Error retrieving parent for item: No resource found that matches the given name '@style/Widget.AppCompat.Button.Borderless'.

Error retrieving parent for item: No resource found that matches the given name 'Animation.AppCompat.Dialog'

Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.AppCompat.Button'.

**Comment by jpbrocca** [comment]
Hi @marchanddesable,

Are you trying to compile the sample provided with Grial or your own project ?

This is happening only with Android or you have similar issues with iOS ?

Thanks,
JP

**Comment by marchanddesable** [comment]
It was the "Grial" solution, provided.

I think I have fixed the issues, here is what I did:

Step 1:

In the folder:
\AppData\Local\Android\android-sdk\extras\android\support\v7\appcompat

there is a file named "project.properties"
In this file I replaced the:

Project target.target=android-19android.library=true
by
Project target.target=android-21android.library=true

Almost all the errors were fixed after doing that but I two other errors, something like:

Please install package: 'Xamarin.Android.Support.v7.AppCompat' available in SDK installer
Android resource directory AppData\Local\Xamarin\Xamarin.Android.Support.v7.AppCompat\23.3.0.0\embedded\./ doesn't exist.	Grial.Droid			

To fix that you need to remove the "23.3.0.0" folder, clean the project in visual studio and compile it.

Note: I have also deleted the one in the folder "Xamarin.Android.Support.v4".

The missing folder will be detected and automaticaly downloaded with the right files in it.

Now the compilation works.

Thanks.

**Comment by jpbrocca** [comment]
Ok, thanks for the details.

We will investigate more because it seems something could have changed on XF v2.3.1.114 and we could need to update some files to make it run out of the box for that version -at least for Android-. 

Regard and thanks,
JP

**Comment by LeoHere** [comment]
Closing the issue. Feel free to reopen it if you need so.
