### ISSUE TITLE
iOS Layout bug?

### ISSUE THREAD

**Issue by Nanouz** [UXDivers/Grial-UI-Kit-Support#660]
Hi

The layout on iOS is showing weird lines. On top of the page and around my picker. The dark green lines. How can I remove these?

![iOS Layout Bugs](https://user-images.githubusercontent.com/26550349/70727220-975e4f80-1cff-11ea-8c93-fd8d7d5a6d15.jpg)

**Comment by dirivero** [comment]
It's hard to tell without looking at the code. Can you send me the XAML of the page to: drivero at uxdivers.com?

**Comment by Nanouz** [comment]
> 
> 
> It's hard to tell without looking at the code. Can you send me the XAML of the page to: drivero at uxdivers.com?

You are right. I have it on multiple pages but will send the XAML of this page. Thx for looking at it!

**Comment by jpbrocca** [comment]
Hi @Nanouz,
This bug is fixed in our latest version (3.0.60) so I am closing this bug. 
Feel free to re-open as needed.

You can read more about this version here:
https://docs.grialkit.com/release-notes.html#release-notes-grial-3060

Regards,
JP
