### ISSUE TITLE
Cannot convert from 'ThemeColors' to 'UXDivers.Artina.Shared.ThemeColorsBase'

### ISSUE THREAD

**Issue by BrunoRuiz** [UXDivers/Grial-UI-Kit-Support#662]
* - THIS PROBLEM ONLY HAPPENS IN .iOS - *

Every time I try to Deploy to my device I get Cannot convert from 'ThemeColors' to 'UXDivers.Artina.Shared.ThemeColorsBase' error the system recompiles this file and I have nothing to do!

### Description
* - THIS PROBLEM ONLY HAPPENS IN .iOS - *
Cannot convert from 'ThemeColors' to 'UXDivers.Artina.Shared.ThemeColorsBase'

### Steps to Reproduce
1. I simply have Build

### Expected Behavior
Should build and deploy to my device / emulator

### Actual Behavior
Don't deploy and give me the error: Cannot convert from 'ThemeColors' to 'UXDivers.Artina.Shared.ThemeColorsBase'

### Basic Information

- Version with issue:
 - UXDivers.Grial - 3.0.54
 - UXDivers.Artina.Shared.Base - 2.7.7
 - UXDivers.Artina.Shared - 2.7.7
 - UXDivers.Artina.Controls.Tab - 2.7.7
 - UXDivers.Artina.Controls.Repeater - 2.7.7

- Last known good version:
 - I can not say which last version valid, the project was at a standstill.

- IDE:
 - Microsoft Visual Studio Community 2019 - 16.4.2
- Platform Target Frameworks: 
  - iOS: 13.2
     - Xamarin.iOS and Xamarin.Mac SDK - 13.8.3.0(0d8fe21)

- Affected Devices:
 - Iphone 6S and any other

### Screenshots
![Capturar1](https://user-images.githubusercontent.com/1844532/71112332-fc0b2580-21a9-11ea-99af-f18877a29d89.JPG)

![Capturar2](https://user-images.githubusercontent.com/1844532/71121648-a2145b00-21bd-11ea-8e8e-4b0aa887566f.JPG)

![Capturar3](https://user-images.githubusercontent.com/1844532/71121732-c53f0a80-21bd-11ea-9f72-f3d204e4d51a.JPG)

**Comment by LeoHere** [comment]
@BrunoRuiz from your description it seems that you are referencing both Grial 2 and Grial 3 packages. That is not supported. 
* If your app is a Grial 2 solution you should reference just Grial 2 packages (i.e. those named UXDivers.Artina.*)
* If your app is a Grial 3 solution you should reference just UXDivers.Grial nuget package.

I hope it helps.
