### ISSUE TITLE
EmailValidatorBehavior

### ISSUE THREAD

**Issue by carlhoogstoel** [UXDivers/Grial-UI-Kit-Support#663]
I would like to add some padding to the behavior. 
Can you let me know how this can be achieved?

![image](https://user-images.githubusercontent.com/19626310/71154345-9b2c2d80-223b-11ea-8757-6c0f79633d3f.png)

**Comment by LeoHere** [comment]
@carlhoogstoel the error message usually is a `Label` with a `DataTigger` that watch for changes in the `IsValid` property of the `EmailValidatorBehavior`. Just look for the `DataTrigger` that refers to the element named `emailValidator`. Add the required spacing to that label.

I hope it helps.
