### ISSUE TITLE
Behaviors

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#667]
Hi,

Where can I find the source code of behaviors for email validator?

I would like to create other behaviors for other specific validations.

Thanks,

**Comment by LeoHere** [comment]
@dalton5 the source code for the behavior is not available. It is within the NuGet packages. [Here](https://devblogs.microsoft.com/xamarin/behaviors-in-xamarin-forms/) you have a similar behavior that you can base on.

I hope it helps.

**Comment by dalton5** [comment]
Perfect. Thanks a lot @LeoHere.
