### ISSUE TITLE
Navigate from DashboardCarouselPage to other page with the back navigation bar.

### ISSUE THREAD

**Issue by GirishHolla** [UXDivers/Grial-UI-Kit-Support#669]
Hi Team,
How do I navigate from DashboardCarouselPage to other page with back navigation option?
Is there a sample code for the demo app?

**Comment by LeoHere** [comment]
@GirishHolla you need to wrap the `DashboardCarouselPage` within a `NavigationPage`.  [This](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical) section of the Xamarin Forms documentation explains how it works.

I hope it helps.
