### ISSUE TITLE
How can I modify the main Navigation bar 

### ISSUE THREAD

**Issue by danialbakhsheshi** [UXDivers/Grial-UI-Kit-Support#67]
I want to add the shopping cart Icon or add some other Icons to the main navigation bar, how can I do that, I know we have a page which is custom navigation but I need the main nav to be modified, any Idea how?

**Comment by jpbrocca** [comment]
Hi @danialbakhsheshi,

You simply add ToolbarItems to your page:

```
<ContentPage.ToolbarItems>
		<ToolbarItem Icon="icon.png" Clicked="OnClicked" Order="Primary" Priority="0" />
		<ToolbarItem Name="Second" Clicked="OnClicked" Order="Primary" Priority="0" />
		<ToolbarItem Name="Third" Icon="icon.png"  Clicked="OnClicked"  Order="Secondary" Priority="1" />
		<ToolbarItem Name="Last" Clicked="OnClicked"  Order="Secondary" Priority="2" />
	</ContentPage.ToolbarItems>
```

As you can see, you can add icons and also display items grouped on Android as in the previous code:

![image](https://cloud.githubusercontent.com/assets/15996999/17686025/5a6fd134-633f-11e6-87fa-1b422729aeb0.png)

![image](https://cloud.githubusercontent.com/assets/15996999/17686033/6b4a6352-633f-11e6-9242-0d7c586328ea.png)


More info here:
https://developer.xamarin.com/api/type/Xamarin.Forms.ToolbarItem/

Best,
JP

**Comment by danialbakhsheshi** [comment]
Thank you so much, but then If I add them like that how can I add badge on the Icon?

**Comment by jpbrocca** [comment]
You will need to go through the platform/s to get that if for some reason don't want to use the custom nave bar.
This is not provided our if the box by xamain forms.

One alternative though could be that you create some icons including the badge with the number then you change the icon through bindings to reflect the right image.
Not the most elegant solution but could help you in case you cannot implement the behaviour.
