### ISSUE TITLE
Urgent!!! TabControl  setting SelectedIndex not navigating to appropriate tab

### ISSUE THREAD

**Issue by GirishHolla** [UXDivers/Grial-UI-Kit-Support#670]
Dear folks,
I am using the tab control. And setting the Tab selected index in the ViewModel an d below is the .xaml settings 
 `<grial:TabControl
			Style="{ StaticResource CustomTabStyle }"
			TabStripBackgroundColor="{ DynamicResource ArticleHeaderBackgroundColor }"
            TabSelectedCommand ="{Binding Shopping.TabSelectedCommand}"
            SelectedIndex="{Binding Shopping.SelectedTabIndex}">`

SelectedIndex="{Binding Shopping.SelectedTabIndex}" is not setting the desired Tab.

Pls help me out.

**Comment by dirivero** [comment]
Hi,
Please make it a 2-way binding so it goes both ways (because the tab control also changes the selected index):

```
SelectedIndex="{Binding Shopping.SelectedTabIndex, Mode=TwoWay}"
```

**Comment by GirishHolla** [comment]
Thanks it worked.
