### ISSUE TITLE
grial:Effects.Shadow doesn't work for buttons

### ISSUE THREAD

**Issue by visionary78** [UXDivers/Grial-UI-Kit-Support#672]
I was looking ChatMainPage.Xaml and you have defined some shadow properties for the  add button. But no shadow is visible around the button. Is there any solution for this issue?
```
  <Style
			x:Key="FloatingActionButtonStyle"
			TargetType="Button"
			BasedOn="{ StaticResource CircleActionButtonFlatStyle }">
            <Setter
				Property="grial:Effects.Shadow"
				Value="True" />
            <Setter
				Property="grial:Effects.ShadowSize"
				Value="2" />
            <Setter
				Property="grial:Effects.ShadowIOSColor"
				Value="#66000000" />
            <Setter
				Property="HorizontalOptions"
				Value="End" />
            <Setter
				Property="VerticalOptions"
				Value="End" />
            <Setter
				Property="FontFamily"
				Value="{ StaticResource IconsFontFamily }" />
            <Setter
				Property="Margin"
				Value="20" />
        </Style>

```
**Screenshot from the Grial app:**
![Screenshot_20200115-092855](https://user-images.githubusercontent.com/5931572/72422192-e1f93e80-3779-11ea-9f79-67c382a52057.png)

**Comment by jpbrocca** [comment]
Hi @visionary78,
This bug is fixed on our latest version (3.0.60) so I am closing this bug. Feel free to re-open as needed.

You can read more about this version here:
https://docs.grialkit.com/release-notes.html#release-notes-grial-3060

Regards,
JP
