### ISSUE TITLE
Transition Animation bottom to top

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#674]
Hi,

I try to create animations between pages with transitions.

I would like for example create a transition from bottom to top when I navigate and show a new content page or content view.

I searched in the source code but found nothing. Just parallax one.

Can you help?

**Comment by dalton5** [comment]
Any clues, examples or ideas?

**Comment by jpbrocca** [comment]
Hi @dalton5,

Grial doesn't provide page transitions.
You could try with something like this:
https://github.com/jsuarezruiz/xamarin-forms-page-transitions

Hope that helps!

JP
