### ISSUE TITLE
Error on video player 

### ISSUE THREAD

**Issue by luisnovaisdev** [UXDivers/Grial-UI-Kit-Support#678]
Video from youtube don't work

### Description
When try to open youtube video give error message 
the given key 'url_encoded_fmt_stream_map' was not present in the dictionary xamarin forms

This happens in your test app.

**Comment by jpbrocca** [comment]
Hi @luisnovaisdev,

Can you please specify your device and OS version? Also, can you share the video URL?

Thanks a lot
JP

**Comment by luisnovaisdev** [comment]
Hi @jpbrocca ,
this happens in all devices, android and IOS, in all versions.
And happens with all youtube videos, one link is that : https://www.youtube.com/watch?v=JpV-FGsMUig

**Comment by jpbrocca** [comment]
Hi @luisnovaisdev,

Thanks a lot for the details.
I confirm I can reproduce the error.
We will be taking a look at it and keep you updated.

Regards and thanks,
JP

**Comment by luisnovaisdev** [comment]
Thanks @jpbrocca ,
We have an app in production and we really need that feature working

**Comment by jpbrocca** [comment]
Hi @luisnovaisdev,
I asked our team and it seems the issue is already solved on our latest grial packages (3.6.0). 
The app on the stores has not been published with thay version. 

Could you please try with latest and let me know? 

Regards and thanks 

JP

**Comment by luisnovaisdev** [comment]
Hi. @jpbrocca 
The videos are working now.
On IOS no problem but in android the video show the content below him, don't have background
Can you see that ? I attach the image with that 
![Screenshot_2020-02-12-14-13-56-431_com primariu europe4youth](https://user-images.githubusercontent.com/58727647/74343163-81721700-4da2-11ea-8c30-c20103aea9c1.jpg)

**Comment by jpbrocca** [comment]
Hi @luisnovaisdev,

I have tested on a real device (Google Pixel 3) with Android 10 using your video and the Grial page used to display videos and everything seems to be OK.

![Screenshot_20200212-153020](https://user-images.githubusercontent.com/15996999/74365819-93a58280-4dad-11ea-8a7e-f3c80558e480.png)
![Screenshot_20200212-152954](https://user-images.githubusercontent.com/15996999/74365821-943e1900-4dad-11ea-9343-5186b83ad238.png)

It seems you are using a custom page right?

If problem persists, please send your page to hello@grialkit.com and mention bug #678 in the subject.

Regards,
JP

**Comment by Escudero183** [comment]
I have the same problem, I am testing with various youtube urls and I am getting this error:

the given key 'url_encoded_fmt_stream_map' was not present in the dictionary

**Comment by jpbrocca** [comment]
Hi @Escudero183,

can you please tell me which Xamarin Forms and Grial packages version are you testing with?

Regards,
JP
