### ISSUE TITLE
CarouselViewRenderer throws NullReferenceException

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#679]
### Description
When running GrialKit App (only splash screen and about page) in Android, I get a NullReferenceException in CarouselViewRenderer page. KeyboardService happens to be null.

### Steps to Reproduce

1.  Download Grial (Demo) App for V3 with only splash screen and RichAboutPage.xaml
2. Upgrade the Grial SDK to 3.0.60
3. Upgrade Xamarin Forms to the latest stabel 4.4.0.991640
4. Run the app against pixel Android 8.1 google emulator 

### Expected Behavior
App to show Splash screen. This works smoothly on iOS

### Actual Behavior
Gets a NPE

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 8.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![CarouselViewRenderer_Exception](https://user-images.githubusercontent.com/26844611/74190961-c9fdc900-4c18-11ea-86d5-b42a288cc42f.JPG)

**Comment by jpbrocca** [comment]
Hi @IoTFier, how have you been?

I have attempted to reproduce your issue, but I couldn't.
I followed your description step by step and I cannot get any exception.

![image](https://user-images.githubusercontent.com/15996999/74194737-a5194e00-4c38-11ea-8730-834e69dab500.png)


![image](https://user-images.githubusercontent.com/15996999/74194720-9a5eb900-4c38-11ea-9b67-865b627cb018.png)



Could it be possible that you are seeing actually a cached version of your app deployed in your device?

To make sure, please make sure your device is connected to your Pc, then go to `Tools` menu in visual studio:

![image](https://user-images.githubusercontent.com/15996999/74194458-0ab90a80-4c38-11ea-9a71-70a8e1a1c098.png)

Then run:
`adb uninstall <YOUR_PACKAGE_NAME>`

![image](https://user-images.githubusercontent.com/15996999/74194515-29b79c80-4c38-11ea-825f-61e1a2d6b6d7.png)

That should completely remove your app from your device, then, try running again from Visual Studio and let me know how it goes.

Regards,
JP

**Comment by IoTFier** [comment]
Hi JP, I am doing good. How are you and everyone else doing ? 
My apologies for the delayed response. I followed your step on my Win 10 Pro environment (VS 16.4.5 as of today and got the same result). 

I am emailing you my soln zip to your email address.
Let me know if that helps you to repro. 

More than happy to fire up a web session if needed.

Thank you

**Comment by IoTFier** [comment]
Hi JP, could you reproduce the issue using my soln zip?

**Comment by jpbrocca** [comment]
Hi @IoTFier, how are you?
Unfortunately today it was impossible, but tomorrow I will be reviewing it and will send my comments. 

Regards 
JP

**Comment by IoTFier** [comment]
Hi JP, it is working with the new version of the renderer file. Closing this issue. 
Thanks a lot.
