### ISSUE TITLE
Colors.tt in Android causes build error

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#68]
I'm trying to set up a new project from scratch.  I've copied everything like the sample project, I think.  I'm getting the following error from colors.tt:

Severity    Code    Description Project File    Line    Suppression State
Error       Running transformation: System.IO.FileNotFoundException: Unable to locate file
File name: 'C:(path to my project)\Resources\values../../../../Grial/App.xaml'

Server stack trace: 
   at Microsoft.VisualStudio.TextTemplating.VSHost.TextTemplatingService.ResolvePath(String path)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost.ResolvePath(String path)
   at Microsoft.VisualStudio.TextTemplating35F087C37193E79CD28CF5BF36F73395B8D77B8C3A680676AB0FC0CFB6E5DE42310CB74453FAE8896884648B7B26D0B8C6B6ABFF773D3B356D70B294E7D5DB52.GeneratedTextTransformation.TransformText() myproject.Droid (path)\myproject.Droid\Resources\values\Colors.tt   1   

I'm also getting the error:
Severity    Code    Description Project File    Line    Suppression State
Error       No resource found that matches the given name (at 'android:windowBackground' with value '@drawable/splash').    myproject.Droid C:(path to my project)\myproject.Droid\Resources\values\Style.xml  2

**Comment by jpbrocca** [comment]
Hi @attrib75,
Do you get the same error if you try to compile the sample project's colores.tt?

If not probably you need to update some of the references inside your project's colores.tt.

Best
JP

**Comment by LeoHere** [comment]
Hi @attrib75, 
You probably will need to adjust the line that says:
```
string path = Host.ResolvePath("../../../Grial/App.xaml");
```
since the new project will have a different name. That is a relative path from the Colors.tt to the App.xaml file.

**Comment by attrib75** [comment]
There's something wrong with the path.  The error specifically says: 

Unable to locate file
File name: 'C:\example_folder\another_example_folder\MyProject.Droid\Resources\values\../../../../MyProject/App.xaml'

This doesn't happen in the sample.  The sample compiles fine.

**Comment by jpbrocca** [comment]
Hi @attrib75,
did you try with @LeoHere's suggestion?

Are you on Mac/Windows Xamarin Studio/Visual Studio ?

If this is blocking you, one way to overcome this -until we figure out your issue- is that you manually replace the exported colors on the "Colors.xml" file (the process T4 template just look for the exported colors on the App.xaml file and extract them to the "Colors.xml" file in the Android project).

Best,
JP

**Comment by attrib75** [comment]
Thanks, I'm using Visual Studio. I changed the path and now there is a different error.  I'm not sure where to find the colors.xml file

**Comment by attrib75** [comment]
Ok I have it working now.  I just coped 
     <?xml version="1.0" encoding="utf-8" ?>
<resources>
  
  <color name="AccentColor">#FFDA125F</color>
  <color name="InverseTextColor">#FFFFFFFF</color>
</resources>

from the sample colors.xml.  Thanks for your help everyone

**Comment by jpbrocca** [comment]
Great!

Thank you.
It would help if you keep adding more details about the errors you get so that way we could find the reason and fix this issue.
Whenever you had a minute please add more info. I will leave this issue open.

Best regards,
JP
