### ISSUE TITLE
Grial 2 Pro License - Couple of Issues with existing apps

### ISSUE THREAD

**Issue by eglibecerra** [UXDivers/Grial-UI-Kit-Support#680]
### Description
 Hi Grial team
 
Hope all is good

**Context:** I was asked by the business owners to move our app built with Grial UI to the app store (before we were hosting internally through enterprise ) no code changes were involved

So nothing has changed in terms of code since 2019 when we published the app all screens back then all looked fine but with latest iOS and latest Android OS the following things happened

- The apps are no longer visible in iPad.
- The apps don’t stretch height wise in both iOS and Android (I only have portrait mode enabled) 
in iOS it looks like after the splash screen disappears it remains behind the main layout so you can see it at the top like its beneath the main layout. In Android theres a massive gap at the bottom of the screen.

The current Grial Version I have is version 2.7 Under the Pro License
![GrialVersionUsed](https://user-images.githubusercontent.com/2393193/74293201-32ba8200-4d8e-11ea-9a68-7be99d0bb3f3.JPG)
![GrialProLicensed](https://user-images.githubusercontent.com/2393193/74293203-33ebaf00-4d8e-11ea-86fb-e77ecb2c3e0f.JPG)

Also when uploading the app to appstoreconnect I get a warning from apple saying I'm using deprecated Libraries and they will no longer accept these in the app store. I have checked my app not really using that (dont know if behind the scenes grial is or what not)
![DeprecatedStuff](https://user-images.githubusercontent.com/2393193/74293403-d9068780-4d8e-11ea-9727-fe0200e5eee8.JPG)

Can you please let me know what are my upgrade options as I payed a fair bit for the pro license for it to no longer work /have issues with the apps we have. 

 Cheers

### Steps to Reproduce
(Grial version 2.7)
1.  Running my app with in iPad in iOS 13.3
2.  Running my app in Android 10
3.  Running my app in iPad in iOS 13.3

### Expected Behavior
Both should render like they did before full screen stretch.

### Actual Behavior
 iPad does not render at all.
On Phones iOS/Android the layout does not stretch to 100% of height of container
### Basic Information

- Version with issue: 2.7
- Last known good version: 2.7 Back with Xamarin 3.1
- IDE: Visual Studio 2019 (but the issue is once app is published)
- Platform Target Frameworks: 
  - iOS:  9.0
  - Android:  
- Android Support Library Version: 
- Nuget Packages: 

![Dependencies](https://user-images.githubusercontent.com/2393193/74293555-50d4b200-4d8f-11ea-999e-8e14b32e6c54.JPG)

- Affected Devices: iPhone, iPad, (v 13 )Android Phones (version 10)

### Screenshots
iOS 13.3 (iPhone 8)
![IPhone8_iOS13](https://user-images.githubusercontent.com/2393193/74293042-b2941c80-4d8d-11ea-82d7-fd07a4c6f176.JPG)
Android 10 (Pixel 4XL)
![Android10](https://user-images.githubusercontent.com/2393193/74293081-d7888f80-4d8d-11ea-92a9-35b9f899ffef.jpg)

**Comment by jpbrocca** [comment]
Hi @eglibecerra, how are you?

The issues seem to come from Xamarin Forms version.
I have tested with `Xamarin Forms 3.1.0.697729` and I can reproduce the ipad issues as well iphone issues you mentioned, however could't reproduce Android issues.
I am also using the latest Grial 2 stable (`2.7.7`).

Can you update your Xamarin Forms packages to latest stable `4.4.0.991640`?

The Xamarin Forms team removed the `UIWebView` from their source in 4.5 version (still a pre-release), so you need to update to that version to avoid the apple store warning: 
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

Regards,
JP

**Comment by eglibecerra** [comment]
Hi JP Sorry for the late reply its been hectic, I recently had to go back to Enterprise Apple Developer account as the app in question got rejected in the app store (hijacking my bundle id, I since requested an updated bundle id from Grial which they have provided) So now I'm gonna put the app back in our local host instead of app store... Will look at updating the version of Xamarin to the latest stable 4.4.0.991640

Thanks for letting me know about the UIWebView also read that info through Xamarin...

Going back to my issue my Grial version is 2.7.1, do you recommend me just upgrade Xamarin forms? I reckon there will be a lot of work involved for me if I have to update the version of Grial to latest stable (as you mention) 2.7.7, You guys have your own nuget repo right? 

The version

**Comment by dirivero** [comment]
Yes, we have a private nuget feed. Setup information is [here](http://docs.grialkit.com/v2/#grial-uikit-overview-grial-first-run-setting-up-uxdivers-nuget-source).

Apple will receive apps using that API until April. You can try updating the packages to latest XF. If you do so, please have in mind this [issue](https://github.com/xamarin/Xamarin.Forms/issues/9212) as you may need to reformat some binding expressions in the XAML to remove white spaces after single quotes.

**Comment by eglibecerra** [comment]
thanks for the links @dirivero I will have a look at these and start working on the upgrade to fix these issues as per @jpbrocca 's instructions I will let you know how it goes. Hopefully i can get these working back on iPads

**Comment by eglibecerra** [comment]
Hi guys sorry to reach out again, back in 2020 i couldn't make those updates as I was on other projects, but now I have sometime to work on this... as you know currently the latest version of X.F is 5. 

Our app build with Grial 2.7.1 is being used internally through enterprise and for the purpose it was build for there's no need for us to upgrade to the latest Grial version. (nor we have the budget to do so)

**My question**
Our mobile application is still published internally but is no longer working in IOS (still works in android) and I need to fix it ASAP (I'm guessing it's because of the UIWebView which jpbrocca mentioned above) which is still referencing X.F3. 

So my question is can I upgrade my version of X.F 5 and still use Grial 2.7.1 or is there any known compatibility issues with those 2 versions? and if there is whats the highest version of X.F compatible with Grial 2.7.1.

Also are there any upgrade guides i can follow if any?

Cheers

**Comment by jpbrocca** [comment]
Hi @eglibecerra, how are you?
You can upgrade to Xamarin Forms 5 but you will need to make sure to replace the `MaterDetailPage` for `FlyoutPage` since the first is obsolete in Xamarin Forms 5.

Check the details below:

**RootPage.xaml.cs**
```
public partial class RootPage : FlyoutPage
	{
	     public RootPage (bool sayWelcome)
		{
			...
			// Empty pages are initially set to get optimal launch experience
			Flyout = new ContentPage { Title = "Grial" }; 
			...
		}

	...
	    private void InitializeMasterDetail()
		{
			Flyout = new MainMenuPage (new NavigationService(Navigation, LaunchSampleInDetail));
                         ...
		}
       	}
```

**RootPage.xaml**
```
<?xml version="1.0" encoding="utf-8"?>
<FlyoutPage
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	x:Class="YOUR_NAMESPACE.RootPage"
	xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
	IsPresented="false"
	Title="{ artina:Translate StringTitleWelcomeToGrial }"
>
</FlyoutPage>
```

Regards,
JP

**Comment by eglibecerra** [comment]
Cool I'll start making those changes will let you know if I run into any unforeseen issues
