### ISSUE TITLE
Where can i change Starting Page ?

### ISSUE THREAD

**Issue by turgaygncr** [UXDivers/Grial-UI-Kit-Support#682]
I want to change first loading page before main page.
Where is it in the project ?

Thanks.

![image](https://user-images.githubusercontent.com/5506941/74613504-0f8e2a80-5120-11ea-932b-d9ceb1f8a878.jpeg)

**Comment by jpbrocca** [comment]
Hi @turgaygncr,

Please check the docs about splash screen:

http://docs.grialkit.com/working-locally.html#working-locally-splash-screen

Cheers 
JP
