### ISSUE TITLE
Android Error CS0234 The type or namespace name 'Content' does not exist in the namespace

### ISSUE THREAD

**Issue by VarakornK** [UXDivers/Grial-UI-Kit-Support#683]
I buy Grial UI version Pro.

I've downloaded full package of Grail Solution and I've got a problem while compiling on Visual Studio for MAC OS, it said "Error CS0234: The type or namespace name 'Content' does not exist in the namespace 'VLPos.Android' (are you missing an assembly reference?) (CS0234) (VLPos.Android)". I've attached a screenhot to you.

<img width="1369" alt="Screen Shot 2563-02-17 at 10 25 22" src="https://user-images.githubusercontent.com/43699328/74624536-6bd26800-517b-11ea-8885-dc3ef949f9fd.png">

Please help!

**Comment by jpbrocca** [comment]
Hi @VarakornK,
Some questions here to try to find the cause of your issue:

- Are you using Visual Studio 2017 or 2019? Which version?
- which android sdk version do you have?

Regards 
JP

**Comment by VarakornK** [comment]
Are you using Visual Studio 2017 or 2019? Which version?
- Visual Studio 2019
which android sdk version do you have?
- Android 9.0 (Pie)

Thanks!

**Comment by jpbrocca** [comment]
Hi @VarakornK,

Can you please try the following:

- clean solution
- close Visual Studio
- delete bin and obj folders in all your projects folders
- open again your solution in Visual Studio and rebuild.
- try running again in Android

Regards,
JP

**Comment by VarakornK** [comment]
Hi Sir,

I try already but have error this.

<img width="1403" alt="Screen Shot 2563-02-17 at 22 18 41" src="https://user-images.githubusercontent.com/43699328/74666365-ef1fa800-51d3-11ea-99b0-1a8c2c77b97a.png">

Thanks!

**Comment by VarakornK** [comment]
I try to compile on a different MAC Machine, same message is still coming up. Could you please check that error from my project that I attached link right here???

[https://we.tl/t-TMXZAKuCbK](url)

<img width="1233" alt="Screen Shot 2563-02-18 at 10 30 35" src="https://user-images.githubusercontent.com/43699328/74701738-52dcbc00-523a-11ea-80a8-9cf40fd16737.png">

Many thanks.

**Comment by dirivero** [comment]
Hi,

The problem is that the Android part of the `VLPos.Android` namespace is clashing with the `Android.Content.Res.Configuration` full name.

You can fix the issue by including this using on top:
```
using Android.Content.Res;
```

And removing the fully qualification of `Configuration` in the method:

```
public override void OnConfigurationChanged(Configuration newConfig)
```

Or by using `VLPos.Droid` as your Android namespace to avoid further conflicts.

Hope this helps.

**Comment by VarakornK** [comment]
Hi,

I change project android to VLPos.Droid.
I can compile android project with out error.

Many Thanks.
