### ISSUE TITLE
VideoPlayer access to properties

### ISSUE THREAD

**Issue by rsposato06** [UXDivers/Grial-UI-Kit-Support#685]
Is there a way to access the properties: IsPlaying and IsFullscreen from the VideoPlayer object on a content page?

**Comment by dirivero** [comment]
`IsFullScreen` is a readonly property on the player. `IsPlaying` is not exposed. 

What do you want to achieve?

**Comment by rsposato06** [comment]
IsFullScreen is not coming up as a property when I access the VideoPlayer object in my content page.  
We are trying to put the VideoPlayer in FullScreen Mode when the user turns their device into landscape orientation.  Kind of like the YouTube functionality in their Apps.  We wanted to further that by only doing it if the video was currently playing.  
We have most of that functionality working, but without knowing if the screen is already in FullScreen mode, it could lead to actually taking the user out of it when calling ToogleFullScreen.

**Comment by dirivero** [comment]
Make sure you are using version 3.0.60 of `UXDivers.Grial` nuget package. The `IsFullScreen` readonly property was added in that version recently.

**Comment by rsposato06** [comment]
I am not seeing 3.0.60 UXDivers.Grial in http://nuget.uxdivers.com/grial
Even with Include Prerelease checked.

![image](https://user-images.githubusercontent.com/31314001/75257215-a1e29e00-57b2-11ea-8119-da7b7ff399d2.png)

**Comment by dirivero** [comment]
That's strange, I can see later versions from Visual Studio and by running `nuget list` from the command line. Can you try re-adding the nuget feed to Visual Studio?

http://docs.grialkit.com/working-locally.html

**Comment by rsposato06** [comment]
Re-adding the nuget feed brought up 3.0.60.  Thanks.  Any suggestions on how to determine if the video is playing?

**Comment by dirivero** [comment]
There's no way to know that. We will add something, thanks for the idea.

The youtube app seems to do make the video full screen on landscape regardless of the state of the video.
