### ISSUE TITLE
Xaml errors: Empty Value String in markup expression

### ISSUE THREAD

**Issue by Henryegal** [UXDivers/Grial-UI-Kit-Support#686]
Hello there,
We just purchased the latest Grial UI 3.0.
I downloaded my starter and runs fine.
As I start adding in other nugets and update the Xamarin.Forms to latest version I get the subject error throughout the grial xaml files.
I have attached the nugets that are updated to trigger my errors as well as the errors.
Thanks for any direction!!

.
![1  xamarin updates](https://user-images.githubusercontent.com/61336437/75475137-422cf400-5966-11ea-85d6-61f8d6901649.PNG)
![2  Error List](https://user-images.githubusercontent.com/61336437/75475146-448f4e00-5966-11ea-9d68-6729a05baa71.PNG)
![3  Line](https://user-images.githubusercontent.com/61336437/75475161-4ce78900-5966-11ea-9dfd-dbc67989bf50.PNG)

**Comment by Henryegal** [comment]
I resoled this by downgrading to the previous release of Xamarin.Forms.
The latest version was causing these errors above.

**Comment by dirivero** [comment]
This is cause by this [issue](https://github.com/xamarin/Xamarin.Forms/issues/9212). 

For now using latest 4.4 seems to be the best option for a case like that where the thickness value is not a single number hence it requires single quotes.

**Comment by Henryegal** [comment]
Hello there,
I just spet $600 on this UI-Kit and I am regretting it.  I was looking for a quick way to make my Xamarin app look sharp, but have spent days on a bug and trying to figure out how things are working with partial examples.

The control FlatDashboard is using the viewmodel:  NavigationViewModel And the ObservableColletion Items to load the grid on the dashboard.
There is a property in this viewmodel:  SelectedItem
Which never gets set.
I can get, but is always null.

I was looking at augmenting the OnTap in the template.

I am sure I could fix it, but what is the proper way I should be getting the dashboard selected item?


Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.
https://support.horizon-is.com/scripts/texcel/customerwise/clogin.dll

**Comment by dirivero** [comment]
Hi @Henryegal,

The best way to execute code when the the user taps/clicks an item would be to use a command. You can achieve this by adding this property to the `GridView` in the Xaml code:

```
<grial:GridView
    ItemClickCommand="{ Binding ItemClickCommand }"
    ...
```

And adding this `Command` in the view model:

```
public ICommand ItemClickCommand => new Command(OnItemClicked);

private void OnItemClicked(object item)
{
    // Code that executes when an item is clicked
    // "item" parameter is the data bound to the clicked item view (its BinidngContext)
}
```

Hope this helps.

PS: Selection implies the UI has the notion of a "selected item" which is not the case of the `GridView`. This view model has that property because it's reused in other navigation screens that use lists and lists can have a selected item as part of their state.

**Comment by Henryegal** [comment]
Hi there,
This is greatly appreciated.   Thanks for taking the time!

Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.
https://support.horizon-is.com/scripts/texcel/customerwise/clogin.dll

**Comment by Henryegal** [comment]
Hi there,
I found a link on your site discussing the subject.
I do not see details on the actual steps to take..... where to copy license file, etc.

Can someone direct me?
Thanks
Henry
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dirivero** [comment]
Hi @Henryegal, 

If you change the license parameters (app name or ids) or the license mode, you just need to re-download the license file `GrialLicense` and replace it in both Android and iOS projects. 

The app name and ids need to be updated accordingly from Visual Studio in your local solution also.

Is this what you were asking?

**Comment by dirivero** [comment]
Hi @Henryegal,
The latest XF version 4.5.0.495 includes a fix for this. You can upgrade now.
Thanks!

**Comment by Henryegal** [comment]
Great thanks!

Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.
https://support.horizon-is.com/scripts/texcel/customerwise/clogin.dll

**Comment by Henryegal** [comment]
Hi there,

We have the Grial package for one of your apps.
It is under my email, name, and company.    Henry@Horizon-is.com<mailto:Henry@Horizon-is.com>,  Henry Egal, Horizon Information Systems, Inc.

I am not sure where to go to support for this.

I am using the NavigationFlatListPage.

I am calling my List with:
Navigation.PushAsync(new NavigationFlatListPage("Consumer"));

The view I am calling from is a NavigationPage.

I cannot seem to popAsync it back after a row is clicked on.  Nothing happens and no Error.
await Navigation.PopAsync(true);  //I have tried variations of this.

I can do this:
await App.Current.MainPage.Navigation.PushModalAsync(new RootMasterDetailPage());   // This is not the behavior I want.


The Back button at the top works to navigate back.

Is there something special I need to do?

Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.

**Comment by dirivero** [comment]
HI,

What is the MainPage on the App? For navigation to work as you expect it should be a NavigationPage wrapping an actual content page, for instance in the App.xaml.cs:

```
MainPage = new NavigationPage(new RootPage());
```

Then, within that RootPage.xaml.cs (not within the navigation page) you can use your code:

```
Navigation.PushAsync(new NavigationFlatListPage("Consumer"));
```

Note that the navigation page is a single instance wrapping the main page.

The PopAsync should work under this structure.

Hope that helps.

**Comment by Henryegal** [comment]
Hello there,

  1.  In my App.xaml.cs my MainPage is set to a LoginPage


        public static Page GetMainPage()
        {
            return new NavigationPage(new SimpleLoginPage());

        }



  1.  After a successful login, in the viewmodel for the SimpleLoginPage, I am navigating to the RootMasterDetailPage


await App.Current.MainPage.Navigation.PushModalAsync(new RootMasterDetailPage());


  1.  The RootMasterDetail has views where in the first view I want to perform this navigation.



Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.

**Comment by Henryegal** [comment]
Hello there,
The navigation is starting in the “MainMenuViewModel” that was part of the downloads I had when selecting views.
public MenuEntry MainMenuSelectedItem

Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.


From: Henry Egal
Sent: July 22, 2020 11:54 AM
To: UXDivers/Grial-UI-Kit-Support <reply@reply.github.com>; UXDivers/Grial-UI-Kit-Support <Grial-UI-Kit-Support@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [UXDivers/Grial-UI-Kit-Support] Xaml errors: Empty Value String in markup expression (#686)

Hello there,

  1.  In my App.xaml.cs my MainPage is set to a LoginPage


        public static Page GetMainPage()
        {

            return new NavigationPage(new SimpleLoginPage());

        }



  1.  After a successful login, in the viewmodel for the SimpleLoginPage, I am navigating to the RootMasterDetailPage


await App.Current.MainPage.Navigation.PushModalAsync(new RootMasterDetailPage());



  1.  The RootMasterDetail has views where in the first view I want to perform this navigation.



Henry Egal | Horizon Information Systems | Software Developer
435 Napoleon Place | Johnstown, PA 15901 | •: 814.535.7810 | •: Henry@horizon-is.com<mailto:Henry@horizon-is.com>

Important Horizon Websites
A place to log and track Help Desk incidents and view our knowledgebase.
