### ISSUE TITLE
GrialNavigationPage Title multiple colors

### ISSUE THREAD

**Issue by astralmaster** [UXDivers/Grial-UI-Kit-Support#687]
Hello,  this is not actually a feature request.  

Is it possible to have two colors for the GrialNavigationPage's title text?  So for example if the title is "GitHub", for "Git" part to have one color and for the "Hub" part to have another?

**Comment by jpbrocca** [comment]
Hi @astralmaster,

You can use Xamarin Form's `TitleView` for that case:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical#displaying-views-in-the-navigation-bar

You can also take a look at Grial's `RichAboutPage` to see how the `TitleView` can be used.

Regards,
JP
