### ISSUE TITLE
Blur effect

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#688]
Hi,

I have seen you provide shaddow and corner radius effect which is wonderful.

Do you provide blur effect?

It should be awesome.

If not how can I do this?

Thanks,

**Comment by jpbrocca** [comment]
Hello @dalton5,
Depending on your needs this can be done with Grial.

Check for instance the `MovieDetailPage` in Grial:
https://grialkit.com/portfolio-items/movie-detail-page/

If you are looking to blur a whole view, then you can take a look at the iOS VisualElement Blur:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/visualelement-blur

Hope that helps!

Regards,
JP

**Comment by dalton5** [comment]
Thanks. It's exactly what I looked for!
