### ISSUE TITLE
Grial TabControl's TabStrip item's border color and background color on Selected

### ISSUE THREAD

**Issue by astralmaster** [UXDivers/Grial-UI-Kit-Support#689]
Hello, is it possible to specify a BackgroundColor and Border/outline color for the selected item of grial:TabControl's TabStrip's TabItem? If not, is it possible to place the TabStrip's items in a container of sorts and specify background color for this container and add Padding="1" to create a visibility of border?

**Comment by dirivero** [comment]
Hi @astralmaster,

You can achieve something like that. Take a look at `AndroidTabResources.xaml` file. Those styles have a highlighting line in the selected tab. That line is a short height box view that has its visibility associated to the `IsSelected` tab item property in the template. You can play with that box view to make it a background element and achieve something similar to what you expect.

Hope that helps.

**Comment by astralmaster** [comment]
Hi @dirivero , Thank you for the info, I will pursue the mentioned route.
