### ISSUE TITLE
CustomNavBar - History instead of Hamburger

### ISSUE THREAD

**Issue by babernethy** [UXDivers/Grial-UI-Kit-Support#69]
Got the CustomNavBar working with the sample/hamburger - is there any sample code from the Grial regular page implementation that could help towards getting the "back" navigation into the upper-left instead of the main menu?

No is acceptable :-) but if anyone has done this, a tip would be appreciated before spending a lot of time on it ... hints even?

**Comment by jpbrocca** [comment]
Hi @babernethy,
Not sure if I understood your requiremente but just in case here are my two cents :)

If you want to change the hamburguer icon from the CustomNavBar to another icon you can easily do that using any of the icons from fontawesome (font included with Grial):
http://fontawesome.io/icons/

You could even use a bitmap instead if you change the CustomNavBar template.

The sample we provide uses a MasterDetailPage so you can navigate on the Detail from the menu, but if you want you can navigate through common pages too.

**Comment by babernethy** [comment]
Figured this out with the Navigation object and PopAsync ...
