### ISSUE TITLE
ExtendedCarouselViewControl automatic height based on children's height

### ISSUE THREAD

**Issue by astralmaster** [UXDivers/Grial-UI-Kit-Support#690]
Does the ExtendedCarouselViewControl provide solution to the following issue of the CarouselViewControl? https://github.com/alexrainman/CarouselView/issues/363
The implementations of ExtendedCarouselViewControl that I have seen in Grial's code all have static height specified either to itself or parent's container but my requirement is to have  fluid height equal to the height of CarouselViewControl.ItemTemplate's contents' height.

One particular example in Grial's samples affected by this issue is in ArticlesBrowserPage.xaml where there is an ExtendedCarouselViewControl that contains articles with images. When you change the screen orientation from vertical to horizontal, you can see how the height of the image in this control is cut and the image is clipped. This is due to ExtendedCarouselViewControl having a static HeightRequest of 300 and not having its height automatically adjusted based on child's contents's height.

If right now I remove the HeightRequest from ExtendedCarouselViewControl  and set this control's parent's width to Auto, then it will take all the height of the parent and other siblings will disappear.

**Comment by dirivero** [comment]
Hi. 

The carousel control is a regular view which takes its height from the space provided by the parent layout or by a defined height request.  Keep in mind that the carousel should not change its height based on the currently selected item, so you would probably need to define a fixed height request for its items anyways.

Something you can do to adjust that page layout to your specific content based on the device orientation is to use a [responsive helper](http://docs.grialkit.com/responsive-helpers.html) like this:
```
HeightRequest="{ grial:OnOrientationDouble Portrait=300, Landscape=200 }"
```
