### ISSUE TITLE
Charts does not work on ios 13.3.1

### ISSUE THREAD

**Issue by j-kosasih** [UXDivers/Grial-UI-Kit-Support#691]
All the charts does not work on ios 13.3.1.

It worked on 13.3, but not on 13.3.1

it worked on the emulator, but not on the actual device with ios 13.3.1

**Comment by j-kosasih** [comment]
it worked on the emulator, but on on the actual device with ios 13.3.1

**Comment by dirivero** [comment]
Hello. 
I've just tried in a device with 13.3.1 with both XF 4.4 and XF 4.6 latest and it worked. What version are you using?
