### ISSUE TITLE
NavigationBar settings and rtl icon

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#693]
Hi,

I am sorry for this question but I really struggle to find where the navigation bar which shows settings and rtl button is located in the source code.

Can you help me please?

Thanks,

**Comment by dirivero** [comment]
Hi,
The menu item for the RTL button is located in the class `RtlSwapHelper` which injects the toolbar item from code.

**Comment by dalton5** [comment]
Sorry but I can't find any RtlSwapHelper in the source code. Where is it setup? In which file?

![image](https://user-images.githubusercontent.com/8339768/76946503-6ac06200-6904-11ea-889e-fbfefa00257f.png)

**Comment by dalton5** [comment]
Ca you help please?

**Comment by dirivero** [comment]
The file is called `RtlSwapHelper.cs`. 
What version of Grial are you using?

**Comment by dalton5** [comment]
I can't find the file...

![image](https://user-images.githubusercontent.com/8339768/77076455-2613f400-69f4-11ea-87df-ddc77ddaf74d.png)

**Comment by dirivero** [comment]
Do you have RTL enabled version? Can you send me your order number?

**Comment by dalton5** [comment]
Ok I think I understand. It's because I do not have the RTL version. My order number is 3182.

Anyway it was just to understand how I can add icons or buttons in the navigation bar like in the screenshots here:

![image](https://user-images.githubusercontent.com/8339768/77092542-346d0a80-6a0a-11ea-94c4-f66a557d9d99.png)

**Comment by dirivero** [comment]
Oh, ok! You can find information on the docs here:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/toolbaritem

You can add one or more to a specific `ContentPage`:

```
    <ContentPage.ToolbarItems>
        <ToolbarItem 
            Icon="some_icon1.png" 
            Command="{ Binding ToolbarItem1Command }"
        />
        <ToolbarItem 
            Icon="some_icon2.png" 
            Command="{ Binding ToolbarItem2Command }"
        />
    </ContentPage.ToolbarItems>
```

And you can also define them at the `NavigationPage` level. If you follow this approach, the toolbar item will be displayed on every page that is navigated (pushed) within that navigation page.

**Comment by dalton5** [comment]
Oh cool. Thanks for the input.

Last question, is it possible to add a label with font icon instead of image in toolbaritem?

**Comment by dirivero** [comment]
Yes, it's possible. Check this [answer](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/592#issuecomment-521432064).

**Comment by dalton5** [comment]
Thanks! very appreciated!
