### ISSUE TITLE
Grial Full Sample with RTL doesn't show menu when changed to LTR

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#695]
### Description

When clicked on LTR in the Grial Full Sample App project (with RTR functionality), the menu goes blank.

I am trying to learn the Grial 3 Styles to apply in my App for handling LTR and RTR UX.
For some of XAML it is working seamlessly (with or without Grial styles). But for some XAML it is not.
Is there a guide or documentation that you can point me to for understanding how to use these styles for making UI RTR compliant ? 
In one scenario when the text changes to RTR but the TranslationX=10 is not factored in while changing the direction. How to address that ?

Also, in my custom nav bar the hamburger and right side icon is not getting swapped even when they are part of a grid. Can you please guide me in these situations as well?
Your help will be truly appreciated.

Thank you

### Steps to Reproduce

1. download a copy of Grial Sample full project - with RTL - without Gorilla.
2. Keep all Nuget packages as is - no upgrade of even XF, Xamarin Essentials, keep Grial at 3.0.60
3. Watch the behavior by clicking hamburger menu in RTR and LTR functionality by clicking the RTR/LTR button in the taskbar

### Expected Behavior

Menu should appear when clicked on LTR

### Actual Behavior

In RTR mode the App Menu becomes blank.

### Basic Information

Affected Devices:
- Version with issue: 3.0.60
- Last known good version:
- IDE: VS 16.5
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: 8.1, 9, 10
- Android Support Library Version: 
- Nuget Packages: All the packages that comes with the downloading of the code
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/26844611/76918625-bc310880-6894-11ea-8693-3810c3a44421.png)

**Comment by jpbrocca** [comment]
Hi @IoTFier,

It seems that the RTL mechanism is working since you actually get the menu moved to right when in RTL. 

From what I can see from your screenshots it seems that the data is missing for the menu when in RTL? 

Can you try removing the binding on the main menu item template label so you can check if this is actually related to data? Just replace the binding with some hard coded text. 

If you need to make some property to have an specific value in RTL different than in LTR you can add it as a resource in the RTL and LTR XAML theme files. So for example you could have a TranslationX="10" in LTR and a TranslationX="-10" in RTL. 

Hope that helps! 

Best regards 
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca, per your suggestion I hard coded values in the MainMenuItemTemplate.xaml, and the results are still same. In fact after LTR -> RTR -> LTR the menu (master) page is also becomes blank.
Please see the screenshots below. I would really like the Grial Sample App to work fully between LTR and RTR mode, so I can debug and understand how and which Grial styles are applied for making the XAMLs RTR compliant.

![image](https://user-images.githubusercontent.com/26844611/77134510-66479680-6a35-11ea-9a46-cc7c635d6197.png)

I will work on adding a resource in RTL and LTL xaml themes to address TranslationX as mentioned.

But,
1. In my custom nav bar the hamburger and right side icon is not getting swapped even when they are part of a grid. Can you please guide me in these situations as well?
2. Is there a guide or documentation on Grial site that you can point me to - for understanding how to use these styles for making UI RTR compliant ?

Thank you,

**Comment by IoTFier** [comment]
Hi @jpbrocca, I would appreciate your input.

Waiting.

Thank you

**Comment by IoTFier** [comment]
Hi Grial team ! 

Hope you all are doing ok with the given crazy Covid situation around the world.
 
Can someone please help me to resolve this github issue ? 
I would appreciate it.

Thank you,

**Comment by dirivero** [comment]
Please replace the `LoadData` method on the `MainMenuViewModel` with this:

```
        private void LoadData()
        {
            var entries = new List<MenuEntry>();

            foreach (var cat in SamplesCatalog.SamplesCategoryList)
            {
                entries.Add(new MenuEntry
                {
                    Name = cat.Name,
                    Icon = cat.Icon,
                    CreatePage = () => new SamplesListPage(cat.Id)
                });
            }

            MainMenuEntries = entries;
        }
```

That should fix the empty menu problem.

**Comment by IoTFier** [comment]
Hi @dirivero , there is no MainMenuViewModel in the code I had downloaded 2 months ago.

I see SamplesViewModel set as the bindingcontext in mainmenupage.cs.

The existing code for LoadData() is as follows -
`		private void LoadData_old()
		{
			SamplesCategories = SamplesDefinition.SamplesCategoryList;
			AllSamples = SamplesDefinition.AllSamples;
			SamplesGroupedByCategory = SamplesDefinition.SamplesGroupedByCategory;
		}
`
Are there any new updates in the SampleApp code that I should download again ?

Thank you
