### ISSUE TITLE
Entry padding issue with pre-release version

### ISSUE THREAD

**Issue by HasithaJay** [UXDivers/Grial-UI-Kit-Support#697]
### Description

with the pre-release version the entry's space for text gets reduced.

### Code
`<?xml version="1.0" encoding="UTF-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        x:Class="View.OTPPage"
        xmlns:grial="clr-namespace:UXDivers.Grial;assembly=UXDivers.Grial"
        BackgroundColor="WhiteSmoke" NavigationPage.HasNavigationBar="false"
        FlowDirection="LeftToRight">
    <ContentPage.Content>
        <Entry  TextColor="Black"
            VerticalOptions="Center"
            HorizontalOptions="Center" 
            BackgroundColor="Red" 
            HeightRequest="52"
            WidthRequest="75"
            FontSize="Large"
            grial:EntryProperties.BorderColor="#1058d1"
            grial:EntryProperties.BorderCornerRadius="0"
            grial:EntryProperties.BorderStyle="BottomLine"
            Keyboard="Numeric"/>
    </ContentPage.Content>
</ContentPage>`

### Expected Behavior

This can  be achieved by the latest stable version but not with the pre-release version.
![Screenshot_20200320-231547](https://user-images.githubusercontent.com/38936886/77199939-aaa76500-6b0f-11ea-87d1-5fc91a6ae4d9.jpg)

### Actual Behavior

This is the same code with version changes. In here the text gets cropped.
![Screenshot_20200320-210521](https://user-images.githubusercontent.com/38936886/77200161-07a31b00-6b10-11ea-9546-b4afe22fe3d3.jpg)

### Basic Information

- Version with issue: 3.0.61-RC pre-release
- Last known good version: 3.0.60 stable
- IDE: visual studio
- Platform Target Frameworks: 
  - Android: 9
- Affected Devices: J6, A10

**Comment by dirivero** [comment]
Hi @HasithaJay,

You are wright. We've changed the padding because it was not taking into account the pixel density on Android devices. 

Please go ahead and remove this part of your theme's file XAML code:

```
<OnPlatform x:Key="EntryAndEditorsHorizontalPadding" x:TypeArguments="x:Single">
    <On Platform="iOS" Value="12" />
    <On Platform="Android" Value="30" />
</OnPlatform>
```

Replacing it with this line that is not platform dependent: 

```
<x:Single x:Key="EntryAndEditorsHorizontalPadding">12</x:Single>
```
