### ISSUE TITLE
Images not loading in Gridview in Social Pages

### ISSUE THREAD

**Issue by davynys** [UXDivers/Grial-UI-Kit-Support#698]
![Simulator Screen Shot - iPhone 11 - 2020-03-27 at 08 30 30](https://user-images.githubusercontent.com/58054021/77732613-7c40f280-7005-11ea-94bf-e9424a8ff2ee.png)
The GridView doesn't show the images. If you click in the white space the image preview screen loads so the images are there.

Tried this on a freshly downloaded project. It's on all the social pages. the Gridview works in the Dashboard / Navigation pages.

**Comment by jpbrocca** [comment]
Hi @davynys,
Could you please add more details about this issue? 

- which xamarin forms version are you using? 
- which Grial version? 
- is this happening only in Android or iOS or both?

Thanks 
JP

**Comment by davynys** [comment]
Xamarin Forms: 4.4.0.991265
Grial: 3.0.60

Just checked and apparently only in iOS.

**Comment by dirivero** [comment]
Hi @davynys,

I've tried with that XF version and with latest (4.5.0.530) and the images did load in both the emulator and the device. Maybe there was a problem with the server returning them as they are loaded remotely. You can check the URLs in the file `Social.json` under `Related.Images`.

Is this still happening to you?

**Comment by davynys** [comment]
Well right now I cannot test anything as the menu stopped working this
morning. Any ideas on that one?

Best,
Davy


On 2 April 2020 at 15:19:47, Diego Rivero (notifications@github.com) wrote:

Hi @davynys <https://github.com/davynys>,

I've tried with that XF version and with latest (4.5.0.530) and the images
did load in both the emulator and the device. Maybe there was a problem
with the server returning them as they are loaded remotely. You can check
the URLs in the file Social.json under Related.Images.

Is this still happening to you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/UXDivers/Grial-UI-Kit-Support/issues/698#issuecomment-607842259>,
or unsubscribe

**Comment by dirivero** [comment]
I'm checking that one. Will answer there.
