### ISSUE TITLE
Problems setting cursor color

### ISSUE THREAD

**Issue by EdHubbell** [UXDivers/Grial-UI-Kit-Support#70]
The cursor color in my entries is set to exactly what the background of my page is. I've tried changing the AccentColor and the BrandColor in App.xaml, but that doesn't seem to get it. 

There may not be a way to set this property via artina grialkit, but figured I'd ask. 

For now, I'm changing the background of the entry to be a bit lighter. Looks OK, but would rather have a white cursor explicitly assignable.

**Comment by jpbrocca** [comment]
Hi @EdHubbell, how are you ?
This is currently not supported on Grial.

Are you targeting an Android only project ?
If that is the case I think you could achieve this modifying the Android theme directly.

**Comment by EdHubbell** [comment]
Bummer. I'll stick with my background change for the time being. The problem is on both iOS and Android, so I'd rather address it in a consistent way.
