### ISSUE TITLE
Menu doesn't work (anymore) in iOS

### ISSUE THREAD

**Issue by davynys** [UXDivers/Grial-UI-Kit-Support#700]
The main menu loads fine but doesn't respond to select events. Even not on a clean, unchanged downloaded project. On Android it works.

The Set property modifier of MainMenuSelectedItem is never executed. The ViewModel is there, the BindingContext is set.

Xamarin.Forms 4.5.0.530

**Comment by dirivero** [comment]
Hi Davy,

I'm not being able to reproduce the issue with the menu with a brand new downloaded solution and XF 4.5.

I assume you didn't do modifications to the code, but in any case, can you verify the `MainMenuPage` XAML has this line?

```
SelectedItem="{ Binding MainMenuSelectedItem, Mode=TwoWay }"
```

**Comment by francois-junker** [comment]
I have the same problem but with the Xamarin.Forms 4.4 and **iOS 13.4**.
With iOS 13.3, the same code works fine

**Comment by dirivero** [comment]
Yes, iOS 13.4 is the problem. The XF team is working on it already, check this [issue](https://github.com/xamarin/Xamarin.Forms/issues/10162).

**Comment by dirivero** [comment]
If you are in a hurry you can install the Xamarin iOS version with the fix, check here:

https://github.com/xamarin/Xamarin.Forms/issues/10162#issuecomment-607585466

**Comment by francois-junker** [comment]
The xamarin team (from the issue) : 
⚠️ Please update to latest stable in Visual Studio for Mac (v8.5.2) and Windows (v16.5.3), we have released the update that includes the fix. Thanks again for your patience.
