### ISSUE TITLE
NavigationBar Gradient not working in iOS 13.4

### ISSUE THREAD

**Issue by dknezevic1** [UXDivers/Grial-UI-Kit-Support#702]
The issue with the navbar gradient seems to be back in iOS 13.4. 

![Grial gradient 12_0](https://user-images.githubusercontent.com/20426072/78688470-4cc29d80-78c3-11ea-8f37-f5b8596d2f06.png)

![Grial gradient 13_4](https://user-images.githubusercontent.com/20426072/78688493-53511500-78c3-11ea-8898-566fd3c8db6d.png)

**Comment by dirivero** [comment]
Please try using the latest pre-release version of UXDivers.Grial nuget package (3.0.62-RC).

**Comment by dknezevic1** [comment]
Thank you, that fixes it.
