### ISSUE TITLE
Grial VideoPlayer force orientation on fixed portrait mode

### ISSUE THREAD

**Issue by astralmaster** [UXDivers/Grial-UI-Kit-Support#704]
I have a Xamarin Forms app that is fixed to only showing in portrait mode on both Android and iOS platforms. Is it possible to force the Grial's VideoPlayer to always go to landscape mode when the VideoPlayer's maximize button is pressed?  Right now it stays in portrait mode and wont switch to landscape on orientation change. But I require it to always maximize to landscape mode regardless of the orientation.
For example, BBC's official app does this on iOS - it's article pages are fixed to portrait mode, but when an article contains a video, and you press the maximize video button, the video maximizes to landscape mode.

**Comment by dirivero** [comment]
You can check how to dynamically force landscape orientation in Android and iOS here:
https://heartbeat.fritz.ai/force-an-orientation-on-a-single-page-in-xamarin-forms-b9c0c5295367

To detect the video full screen change you can bind the `IsFullScreen` readonly property with `OneWayToSource`:

```
<grial:VideoPlayerContainer>
    <grial:VideoPlayer
        Source="{ Binding TrailerVideo }"
        IsFullScreen="{ Binding IsVideoFullScreen, Mode=OneWayToSource }"
    />
</grial:VideoPlayerContainer>
```

In the setter of the `IsVideoFullScreen` property of your view model you will know when the video toggles between full screen and inline modes.

You can wrap the code in that article into a service that you can consume directly from the shared code (from the view model). If you need help with that you can write me to: drivero at uxdivers.com

**Comment by astralmaster** [comment]
Yep that is what I ended up doing, except I used the ToggleFullscreen function of the VideoPlayer but binding it to an event is of course better. Thank you.
