### ISSUE TITLE
Grial 3.0.60 - Xamarin.Forms 4.5.0.617

### ISSUE THREAD

**Issue by BrunoRuiz** [UXDivers/Grial-UI-Kit-Support#705]
### Description

Today when I submitted my app to the Apple Store I got the following answer:

"We discovered one or more bugs in your app when reviewed on iPad running iOS 13.4.1 on Wi-Fi.

Specifically, no action occurred when we tapped on the any of the buttons in the landing page after login."

I noticed that this only occurs on the most current version of iOS 13.4.1.

### Steps to Reproduce

1. I downloaded the full Grial solution from https://admin.grialkit.com/
    I updated all the components available for updating.

2. Xamarin.Forms atualizado 4.5.0.617

2. Grial Kit 3.0.60

3. Build and Deploy in device.

### Expected Behavior

all visual controls should work.

### Actual Behavior

All menu options, and dashboards don't work tapped

### Basic Information

- Version with issue: Grial 3.0.60 - Xamarin.Forms 4.5.0.617
- Last known good version: Grial 3.0.60 - Xamarin.Forms 4.5.0.617
- IDE: Visual Studio 16.5.2
- Platform Target Frameworks: 
  - iOS:  iOS 13.4.1
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All iOS version 13.4.1
![attachment-14540358695033365936Screenshot-0416-053715](https://user-images.githubusercontent.com/1844532/79500903-961d9600-8003-11ea-9560-2c98ab8f8e55.png)
![attachment-3763461489375253508Screenshot-0414-050731](https://user-images.githubusercontent.com/1844532/79500924-9d44a400-8003-11ea-9c9c-0a5d65f5d705.png)
![WhatsApp Image 2020-04-16 at 17 03 30](https://user-images.githubusercontent.com/1844532/79501452-7470de80-8004-11ea-8430-aab60fe46519.jpeg)
![WhatsApp Image 2020-04-16 at 17 03 49](https://user-images.githubusercontent.com/1844532/79501458-75097500-8004-11ea-9b77-7cff7f59b43f.jpeg)

**Comment by jpbrocca** [comment]
Hi, 
Please check:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/700

Regards 
JP
