### ISSUE TITLE
Grail 3 throwing error on AndroidX 

### ISSUE THREAD

**Issue by Codespliceltd** [UXDivers/Grial-UI-Kit-Support#706]
<img width="1580" alt="VS error" src="https://user-images.githubusercontent.com/54868235/79514118-596e9080-803d-11ea-87dc-78bc6a8ede86.png">
Hi Team,

We have migrated our project over to AndroidX but when we try build it with Target Framework "Android 10", we receive below error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error XA2002: Can not resolve reference: `Xamarin.Android.Support.Design`, referenced by `UXDivers.Grial.Droid`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Design`, or remove the reference to `UXDivers.Grial.Droid`. (XA2002) (FMVerify.Droid)

I know that the Xamarin.Android.Support.Design is not supported on Android 10 but as we followed all the steps to migrate the product to "AndroidX" and also added Xamarin.AndroidX.Migration but it still fails with above error.

**Comment by Codespliceltd** [comment]
Hi There,
We get the same error even when we change the Target to Android 10 without Android X. We did download the SDK etc.

**Comment by Codespliceltd** [comment]
Hi Team,

Just to add to above, the project builds well when we use Android 9 as target framework but fails with above error with Android 10 as target Framework.

**Comment by dirivero** [comment]
You can use version 3.1.73-RC version of `UXDevers.Grial` package to make it work. 

Sorry for the late reply on this.

**Comment by dirivero** [comment]
I'm closing this issue as AndroidX support is part of final release 3.1.76.
