### ISSUE TITLE
UXDivers.Grial.LicenseException: 'License verification failed ERROR

### ISSUE THREAD

**Issue by wpanduka** [UXDivers/Grial-UI-Kit-Support#708]
For the new license we download having this weird error,"**UXDivers.Grial.LicenseException: 'License verification failed because: The application name does not match the license's. Activity title does not match the license's application name.**" this didn’t happen on the first licensee, can you please guide us if we are doing anything wrong . we have re-check the package name and the activity title and everything more than 20 times, also tried with different machines as well, this is a big issue and we have to urgently develop this app and we are all in trouble. please help to install this .(Please see the images ) 
![image](https://user-images.githubusercontent.com/19517563/79689506-f6fed580-8272-11ea-9991-4825c5db145e.jpg)
![unnamed](https://user-images.githubusercontent.com/19517563/79689525-0ed65980-8273-11ea-97f5-5e80c686ea9b.png)
Need your help regarding solving the issue, it seems a bug with the system or version, waiting for your urgent reply. thank you in advance for the support 
Panduka

**Comment by dirivero** [comment]
Hi Panduka,

I've just tried with your app configuration and it worked fine in Android. Are you still seeing that issue?

**Comment by derekvantonder** [comment]
For anyone else that struck this issue, it is indeed very weird. I was able to fix by setting 'this.Title' to the name of my app in MainActivity.cs. Here is more info:

https://stackoverflow.com/questions/42397873/how-to-dynamically-set-title-on-a-xamarin-android-dialog-activity

**Comment by jakubjenis** [comment]
Had the same issue, fix by @derekvantonder worked and saved me a lot of hair pulling.
