### ISSUE TITLE
Font Icon not changing color in Button

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#709]
Hi

I am trying to change font color of icon on the Button , but it remains grey.

Any idea what is wrong ?
![image](https://user-images.githubusercontent.com/25946929/79874467-13288100-83f1-11ea-8b35-fb79f6f2908b.png)

Following is the xaml code.
<Button 
              x:Name="previousButton" 
              Grid.Row="3" 
              Grid.Column="0" 
                FontSize="Large"
              TextColor="White"
              Text="{ x:Static local:GrialIconsFont.ArrowCircleLeft }"
              Style="{ StaticResource FontBackgroundIconFill }"
              Clicked="OnPreviousClicked" />
          
          <Label
              x:Name="pageNumberLabel"
              Grid.Row="3"
              Grid.Column="1"
                FontSize="Large"
              HorizontalTextAlignment="Center"
              VerticalTextAlignment="Center"/>

            <Button 
              x:Name="nextButton" 
              Grid.Row="3" 
              Grid.Column="2" 
                FontSize="Large"
              TextColor="White"
                 Text="{ x:Static local:GrialIconsFont.ArrowCircleRight }"
              Style="{ StaticResource FontBackgroundIconFill }"
              Clicked="OnNextClicked" />

**Style Xaml**
   <Style
				x:Key="FontBackgroundIconFill"
				TargetType="Button">
            <Setter
                      Property="FontFamily"
                      Value="{ StaticResource GrialIconsFill }" />
            <Setter
                      Property="BackgroundColor"
                      Value="{ DynamicResource PrimaryActionButtonStartColor }" />
            <Setter
                      Property="BorderColor"
                      Value="{ DynamicResource PrimaryActionButtonStartColor }" />
            <Setter
                      Property="TextColor"
                      Value="{ DynamicResource OverImageTextColor }" />
            <Setter
                      Property="grial:Effects.BackgroundGradient"
                      Value="{DynamicResource PrimaryButtonGradient}" />

          </Style>
          
**Color**
<Color
		x:Key="OverImageTextColor">#FFFFFF</Color>

Thanking in advance

**Comment by jpbrocca** [comment]
Hi @ShamineDsouza,

Which version of Xamarin.Forms are you using?... Is this happening in Android only orbin both platforms?

Thanks 
JP

**Comment by ShamineDsouza** [comment]
Xamarin forms 4.4

**Comment by ShamineDsouza** [comment]
I havent checked in IOS yet , but it is happening in android.

**Comment by ShamineDsouza** [comment]
Not an issue . was disabled due to single page
