### ISSUE TITLE
iOS Could not load file or assembly 'UXDivers.Artina.Shared' or one of its dependencies

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#71]
Sorry about this, but can I send you the project so you can get it to build?  I'm running out of time to spend on this.  thanks

**Comment by jpbrocca** [comment]
Send it to jpbrocca@uxdivers.com

**Comment by attrib75** [comment]
I sent you a download link.  Thank you for your help!

**Comment by attrib75** [comment]
is there any status on this?  I added reference to artina dlls, the path is accessible.  Still getting this error

**Comment by LeoHere** [comment]
Assembly loading can be tricky when you are working with XAML in iOS. Xamarin expects all required assemblies to be loaded when a given XAML is loaded, and only loads an assembly when it is referenced in code. If you only reference the assembly from the XAML (which is your case here) Xamarin will throw an exception stating it could not found it or one of its dependencies.

Workaround add this before the LoadApplication in the AppDelegate.cs to force loading the assembly into memory.

~~~
var workaround = typeof(UXDivers.Artina.Shared.CircleImage);
~~~

**Comment by attrib75** [comment]
This worked, thank you, you are a life saver!

**Comment by jpbrocca** [comment]
Send it to jpbrocca@uxdivers.com
