### ISSUE TITLE
SwitchCell label text not showing up on Android

### ISSUE THREAD

**Issue by madmapper** [UXDivers/Grial-UI-Kit-Support#715]
Using SwitchCell on android device the label text color is the same as the background color, leaving the label invisible.

### Steps to Reproduce

1. This issue is present on the GrialKit demo app under the Settings view
2. Use a SwitchCell in any form
3. 

### Expected Behavior

Should be able to see SwitchCell label test
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @madmapper, how are you?

This bug is caused by line number 65 in `Style.xml` file in your android project:

`<item name="android:textColorSecondary">@color/NavigationBarTextColor</item>`

If you just remove it you should see everything OK.

Please try it and let me know how it goes.

Best,
JP

**Comment by madmapper** [comment]
Things are great, closing in on release on our first GrialKit app!

This fixed the issue.
