### ISSUE TITLE
NavigationBar color

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#717]
Hi,

How I can set the color of a navigation bar as transparent and extend with an image. I use a content page

Please see below:

![image](https://user-images.githubusercontent.com/8339768/82564822-b6e48880-9b79-11ea-9cee-e0c20db50818.png)

Thanks,

**Comment by jpbrocca** [comment]
Hi @dalton5,

Please check the docs for reference:
http://docs.grialkit.com/navbar.html

Basically, you can take a look at the `MoviesMainPage` implementation.
You will need to create a `NavigationPage` where you will be setting the `GrialNavigationPage` settings and specifically the `IsBarTransparent`...something like this:

**MyNavigationPage.xaml**
~~~
<?xml version="1.0" encoding="UTF-8"?>
<NavigationPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:grial="clr-namespace:UXDivers.Grial;assembly=UXDivers.Grial" 
    x:Class="YOUR_CLASS_HERE" 
    
    grial:GrialNavigationPage.IsBarTransparent="True"
    grial:GrialNavigationPage.BarBackgroundHeight="-1"
>
    ...
</NavigationPage>
~~~

**MyNavigationPage.xaml.cs**

~~~
using System;

using Xamarin.Forms;

namespace ...
{
    public partial class MyNavigationPage
    {
        public MyNavigationPage()
        {
        }

        public MyNavigationPage(Page root)
            : base(root)
        {
            InitializeComponent();
        }

        private void OnClose(object sender, EventArgs e)
        {
            Navigation.PopModalAsync();
        }
    }
}
~~~


**MyContentPage.xaml**
~~~
...
<ContentPage.Content>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <grial:GrialNavigationBar 
            Grid.Row="0"
            UseNavigationPageBarBackgroundColor="true" 
            UseNavigationPageBarBackgroundGradient="true" 
        />

        ...
        <!-- Put your image and other content on top here-->
        ...
    </Grid>
</ContentPage.Content>
...
~~~

In the page that will open your `MyContentPage`
~~~
...
var page = new MyNavigationPage(new MyContentPage());
GrialNavigationPage.SetIsBarTransparent(page, true);
await Navigation.PushModalAsync(page);
...
~~~

Regards,
JP

**Comment by dalton5** [comment]
Nice trick but how can I show the back button with the UI?

**Comment by dalton5** [comment]
Sorry I am completely lost between the GrialNavigationBar and the navigationbar.

If I use the GrialNavigationBar I hide the default navigationbar?

I would like to have a trnasparent NavBar and another with the background color of my page.

And I really can't sort it out.

This is the code I use:

In my page I want to navigate to the profile edit view:

         `private async void Button_Clicked1(object sender, EventArgs e)
         {
            
            var nav = DependencyResolver.Resolve<INavigationService>();

            await nav.SetMainPage<ProfileEditView>("data", isTransparent:false);
        }`

And in my method I have:

               ` public async Task SetMainPage<TView>(object parameter = null, bool isTransparent = true) where TView : IXView
               {
                           var page = await _pageService.CreatePage(typeof(TView),parameter);

                   if(isTransparent)
                   {
                       /**/ WHat to write here?**
                   }
                    else // **I want the same background color of my page** I tried a lot of solutions with GrialNavigationPage but nothing works
            }

Could you help?

I really strugggle on this

**Comment by dirivero** [comment]
Hi @dalton5,

By setting the `IsBarTransparent="True"` in the NavigationPage you won't need to use a `GrialNavigationBar`. The `GrialNavigationBar` is useful when you want to have a taller than usual navigation bar since it extends the area of the native navigation bar.

```
var page = await _pageService.CreatePage(typeof(TView),parameter);
var navPage = new NavigationPage(page);
GrialNavigationPage.SetIsBarTransparent(navPage, isTransparent);
```

Have in mind that the nav bar is either transparent or not at the `NavigationPage` level, not at the page level. You can't change that in the middle of a navigation path but you can set it if you are replacing the main page as it seems to be the intention in your code.
