### ISSUE TITLE
Spelling Mistake on Nuget Package Description

### ISSUE THREAD

**Issue by raymond-dillon** [UXDivers/Grial-UI-Kit-Support#718]
### Description
"Superb is spelt incorrectly in NuGet package description"

### Steps to Reproduce

1. Look for UXDivers.Artina.Shared, UXDivers.Artina.Shared,Base, UXDivers.Artina.Shared, UXDivers.Grail in NuGet Package Manager

### Expected Behavior

Superb is should be spelt superb

### Actual Behaviour
Superb is spelt suberb. 

### Basic Information

N/A - Documentation Issue 

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @raymond-dillon, how are you?

Nice catch! :)
Thanks a lot!

Regards,
JP

**Comment by raymond-dillon** [comment]
Hi @jpbrocca - All good with me. Still loving Xamarin & Grial! Happy enough for me to close this issue?

**Comment by dirivero** [comment]
We've updated the nuget descriptions. The future versions of the packages won't the typo anymore. Thanks!
