### ISSUE TITLE
iPadOS: Invoking camera on iPad second time freezes the GrialKit app

### ISSUE THREAD

**Issue by timmi4sa** [UXDivers/Grial-UI-Kit-Support#719]
### Description
A second attempt to invoke camera on an iPad in a newly-generated app (downloaded from Grial Admin website) makes the app freeze indefinitely. (The very first attempt to invoke the camera on the iPad succeeds well and the app is fully responsive.) Visual Studio for Mac doesn't report any exceptions when the app freezes so we don't know how to troubleshoot this. The iPad is our target device.

What else we tried:
- Invoking camera on the iPad from within a blank Xamarin.Forms Shell application doesn't freeze the iPad no matter how many times we invoke it,
- Invoking camera on the iPad from within a blank Xamarin.Forms application (non-Shell) doesn't freeze iPad.

The issue **doesn't affect** iPhones (those with Home button as iPhone 8 Plus as well as those without, such as iPhone XR). So we are scratching our heads big time.
### Steps to Reproduce

1. Go to Grial Admin page,  select several pages to be included, mainly: "Product Detail", and "Order Confirmation" (we don't have custom logos yet),
2. Go and click on the "Download a Starter Solution". 
3. Unzip the starter solution and open in Visual Studio for Mac (8.6 build 4520)
4. Once the solution has been loaded go to Project -> Manage NuGet Packages.. window,
5. Click the "Browse" header and type in "Xam.Plugin.Media" (by James Montemagno) in the Search textbox and install version 4.0.1.5 (since the latest stable version 5.0.1 requires Xamarin.Forms v4.5, but the Grial starter solution comes with Xamarin.Forms v4.4),
6. Go to iOS project of the starter solution to open "Info.plist",
7. Add a new entry to the Info.plist file titled: "Privacy - Camera Usage Description", 
8. Go to the main project in order to open the "OrderConfirmationPage.xaml.cs" file,
9. Add the code below to the empty OnClicked event handler,
10. Build the application,
11. Connect an iPad (in our case iPad Air 2, OS: 13.4.x, 13.5) to your Mac,
12. Select iOS project as a Startup Project,
13. Select your iPad from the list of connected devices and "Run without Debugging",
14. From the app menu (at left) select Order Confirmation page and click the "Proceed to checkout" button: the app will request permissions and then will display Camera window. Take a picture and click "Use Photo",
15. You will return to the Order Confirmation page and the name of an image file will be displayed in a message box. Dismiss the message box.
16. Click the "Proceed to checkout" button again (this is the second time).

Code to add:
`
await CrossMedia.Current.Initialize();
if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
{
    await DisplayAlert("No Camera", ":( No camera available.", "OK");
    return;
}

var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
{
    Directory = "Sample",
    Name = "test.jpg"
});

if (file == null) return;

await DisplayAlert("File Location", file.Path, "OK");
`

### Expected Behavior
A camera window should open allowing the user to take a picture.

### Actual Behavior
The app gets frozen until the iPad shuts down the app and it disappears (which takes several minutes to occur).

Furthermore (in case it would be helpful): While the app is frozen and we attempt to turn the iPad 90 degrees (to the Landscape mode) a black margin appears and now the "whole" device gets frozen for several seconds so it won't respond to the Home key presses.

### Basic Information

- Version with issue: latest stable Grial version (and latest pre-release)
- Last known good version: None
- IDE: Visual Studio for Mac (8.6 build 4520), Xcode installed version 11.5
- Platform Target Frameworks: Xamarin.Forms 4.4 thru 4.6.x (latest stable)
  - iOS: iPadOS both 13.4.1 and 13.5
- Nuget Packages:
- Affected Devices: iPad Air 2

**Comment by timmi4sa** [comment]
This is an absolute show-stopper, taking Photos isn't Hi-Tech task it's expected in many Apps that would utilize Grial UI kit! We either need a refund (and find another controls vendor) or Grial Kit team should comment on this bug. We have provided a lot of information to help reproduce it.

**Comment by jpbrocca** [comment]
Hi @timmi4sa,
Please check
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/333

Regards 
JP

**Comment by timmi4sa** [comment]
@jpbrocca Hi JP, this workaround has fixed the Starter solution. Nonetheless I am not sure why the #333 has been closed without any meaningful changes to GrialKit initialization. The idea of GrialKit in my opinion is in us paying money so that custom theme would take our Ugly UI pain away, we drop this in and voila! When a sudden and unexpected discrepancy in behavior rears its head on a single device type it shocks the developer and compels him/her research the issue (it cost our two developers a whole day of billable time! and me 30 minutes of putting together the issue; I am not sure why the GitHub search didn't bring up prior resolutions). So here is what I propose to keep your clients pain-free: could you consider adding a new method alongside the GrialKit.Init(..), perhaps: ApplyThemeColor(themeColorBase, [Flags]ExcludeFromTheme? excludedElements), where the enumeration with flags is something like:

`[Flags] enum ExcludeFromTheme {
  UISliderAppearanceMinimumTrackTintColor = 1,
  UISliderAppearanceMaximumTrackTintColor = 2,
  UISwitchAppearanceOnTintColor = 4,
  //etc. 
}`

So that in the iOS project of the Starter solution the initialization would be like so:
`GrialKit.Init(**null**, "...iOS.GrialLicense");
  // Dear developer due to an ongoing Apple bug related to lock up when taking photos on iPad the following items are not stylized as a precaution
  GrialKit.**ApplyThemeColor**(new ThemeColor(), ExcludeFromTheme. UISliderAppearanceMinimumTrackTintColor | UISliderAppearanceMaximumTrackTintColor);`

Otherwise we need to reverse engineer your Init() code after every GrialKit update, while you continue to service these one off requests.

**Comment by jpbrocca** [comment]
Hi @timmi4sa, how are you?

Thanks a lot for your suggestions!
Our team is carefully reviewing them in-depth and will soon provide more details.

Thanks again,
JP

**Comment by dirivero** [comment]
After reviewing this issue we removed those lines from Grial configuration since the colors affected by them can be updated from XF code. 

We've published this change in UXDivers.Grial package version 3.0.68-RC so it won't happen again. 

Many thanks for the detailed report.

**Comment by timmi4sa** [comment]
@dirivero Thank you so much we will pick up the version 3.0.68-RC+ and will remove the manual configuration steps. Again, thank you and we really appreciate your commitment!!
