### ISSUE TITLE
Xamarin Project with grial , dos it coz permission issue when internal sharing on Play store ?

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#721]
Hi ,

I have implemented grial in my project and have almost completed development .
However , we need to do internal testing before proceeding . However I have been getting permission issue when trying the internal sharing uploading of google play store

### Description
I am trying to load the .apk in the internal sharing link provided by google play store for organizational testing .

### Basic Information

Xamarin

### Screenshots

![image](https://user-images.githubusercontent.com/25946929/83345514-b2a83000-a31c-11ea-8632-3eecf0fbf9b9.png)

**Comment by jpbrocca** [comment]
Hi @ShamineDsouza, how are you?

Sorry, I don't think I fully understand. 
It seems to be something not related to Grial. 

Regards 
JP

**Comment by ShamineDsouza** [comment]
Can I do internal sharing on google playstore with grial in development mode ?
