### ISSUE TITLE
Android: White space while page is loading when adding navigatiobar titleview

### ISSUE THREAD

**Issue by askinadze** [UXDivers/Grial-UI-Kit-Support#722]
While a Contentpage is loading a white space is shown if a navigationbar.titleview is added to the page

### Steps to Reproduce
It is easy to reproduce the problem. I downloaded the sample projekt and added following xaml to the SamplesListPage.xaml

```
    <NavigationPage.TitleView>
        <StackLayout Orientation="Horizontal">
            <Label Text="test" FontSize="Caption" TextColor="White"></Label>

        </StackLayout>
    </NavigationPage.TitleView>
```

### Actual Behavior
Between splash screen and finishing page loading the following background is visible for some seconds (**you can see the white space at the bottom**):

![Screenshot_20200603-104740](https://user-images.githubusercontent.com/16515948/83617438-5b5ac780-a589-11ea-984a-024040a5cc46.png)

After that the page is shown correctly:

![Screenshot_20200603-104747](https://user-images.githubusercontent.com/16515948/83617564-8cd39300-a589-11ea-9371-1e2ec57ad1c1.png)

### Basic Information

- Version with issue: 3.0.60

- Platform Target Frameworks: 
  - Android:  10.0
- Android Support Library Version: 28.0.0.3

**Comment by fcastro07** [comment]
Hi @askinadze 
There is no problem with raising the value to 2000 but we do some research about why is displayed that betewen the splash and the page and we think is a normal behavior. Anyway if we find something to improve this behavior it will be included in next versions.
