### ISSUE TITLE
Build Errors -> ThemeColors.cs not found in project.

### ISSUE THREAD

**Issue by sdonoghue76** [UXDivers/Grial-UI-Kit-Support#723]
We are getting build errors that state ThemeColors.cs not found. However I manually checked that the file exists in project

### Description
[Grial] Error occurred 'Fatal error 'iOS theme colors definition file (ThemeColors.cs) not found in project '/Users/runner/runners/2.169.1/work/1/s/Platforms/Caren.iOS/Caren.iOS.csproj'.'. See inner exception for details.' StackTrace: at UXDivers.Daas.Engine.EngineExecutor.Execute (UXDivers.Daas.ExecutionSession session, System.Collections.Generic.Dictionary`2[TKey,TValue] sideEnvironment, System.Boolean ignoreSessionEnv, System.String[] variablesToKeep) [0x00213] in <bacf301cfed84d46aac3e98ad6f1f99d>:0

### Steps to Reproduce
1. Project is app shell project. Pull grialkit elements into project.
2. Runs correctly in simulator and sideload to iphone device. 
3. Produces this error on release build. 

### Basic Information

- Version with issue: We are using Grial 3 Pro
- Last known good version:
- IDE: Visual Studio on Mac
- Platform Target Frameworks: 
  - iOS:  currently 13.3
  - Android: 7.0 ~
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by fcastro07** [comment]
Hi @sdonoghue76 ,
We couldn't reproduce your issue. Can you give me more information about it?

**Comment by sdonoghue76** [comment]
Yes. We have a xamarin shell project built from scratch, and we then pull in the grial kit elements. 
We encountered an issue whereby the bundleId was changing for each build type. Once we standardized this so that GrialKit License matched the bundleId, this error corrected itself.
Thank you.
