### ISSUE TITLE
Google Internal Sharing with Grial in development mode?

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#725]
Hi ,

I have implemented grial in my project and have almost completed development .
However , we need to do internal testing before proceeding . However I have been getting permission issue when trying the internal sharing uploading of google play store

Description
I am trying to load the .apk in the internal sharing link provided by google play store for organizational testing .

Can I do internal sharing on google playstore with grial in development mode ?

Basic Information
Xamarin

Screenshots
image
![image](https://user-images.githubusercontent.com/25946929/84640679-ae763800-af02-11ea-84ff-a689ff3b6878.png)

**Comment by dirivero** [comment]
You can do that but of course have in mind that the app won't work after the license expires. 
If it's just for internal testing and you control who installs the app and even you can force them to reinstall new versions that shouldn't be a problem.

The permissions problem doesn't seem to be related to Grial.
