### ISSUE TITLE
App with Grial crashes switching to WKWebView

### ISSUE THREAD

**Issue by truekxmexico** [UXDivers/Grial-UI-Kit-Support#728]
UIWebView Deprecation and App Store Rejection (ITMS-90809)
Starting in April 2020, Apple will reject apps that still use the deprecated UIWebView API. While Xamarin.Forms has switched to WKWebView as the default, there is still a reference to the older SDK in the Xamarin.Forms binaries. Current iOS linker behavior does not remove this, and as a result the deprecated UIWebView API will still appear to be referenced from your app when you submit to the App Store.
A preview version of the linker is available to fix this issue. To enable the preview, you will need to supply an additional argument --optimize=experimental-xforms-product-type to the linker.

For switch to WKWebView you have to

1.-Linker Behavior to: "Link All"
2.-Adding Additional mtouch arguments add this flag: --optimize=experimental-xforms-product-type
source: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=macos

3.-Setting the linker to Link all assemblies will start producing the mentioned error. In order to fix it you need to exclude UXDivers.Grial assemblies from the linking. To achieve that, add the following to the “Additional mtouch arguments”:  --linkskip=UXDivers.Grial --linkskip=UXDivers.Grial.iOS
source: https://docs.grialkit.com/troubleshooting.html#troubleshooting-license-issues-error-reading-license-error-message

Additional mtouch arguments looks like this: --optimize=experimental-xforms-product-type --linkskip=UXDivers.Grial --linkskip=UXDivers.Grial.iOS

But the app crashes, I don't Know why. I need your help for publishing an update of my app

**Comment by fcastro07** [comment]
Hi @truekxmexico 
In addition to what you did, did you add PreserveAttribute in the LightTheme and GrialIconsFont classes?
The app crashes without any error when you running it?

**Comment by fcastro07** [comment]
Hi @truekxmexico ,
I'm closing this issue due to no response to keep things tidy.
Feel free to re-open if needed.
