### ISSUE TITLE
Repeater control rendering items as blank after 6/7th child element on GrialKit 3.0.70

### ISSUE THREAD

**Issue by djad442** [UXDivers/Grial-UI-Kit-Support#730]
### Description
After upgrading to GrialKit 3.0.70 the repeater control showing child items as blank space after the 6/7th element. Happening for both iOS and Android.

### Steps to Reproduce
1. Create a project with GrialKit 3.0.60. Use a repeater control.
2. Make sure it's working as per normal.
3. Upgrade GrialKit to 3.0.70
4. The same project now will now show repeater items not rendering correctly.

### Expected Behavior
All child items of repeater rendered correctly.

### Actual Behavior
After the 6th or 7th child element, the space is blank and can see the scrollbar with the white area.

### Basic Information

- Version with issue: 3.0.70
- Last known good version: 3.0.60
- IDE: VS2019 16.6.3
- Platform Target Frameworks: 
  - iOS:  13
  - Android: 28

### Screenshots
<a href="https://ibb.co/G3ww01H"><img src="https://i.ibb.co/G3ww01H/Inked-IMG-6834-LI.jpg" alt="Inked-IMG-6834-LI" border="0"></a>

**Comment by fcastro07** [comment]
Hi @djad442 
The bug is fixed and will be available in the next version of Grial.Core, as soon as it's available I'll let you know

**Comment by fcastro07** [comment]
@djad442 
Sorry for the late reply.
You can use 3.1.73-RC version of `UXDivers.Grial` package to make it work.
I'm going to close but feel free to reopen in case of find other issues!
