### ISSUE TITLE
I cannot update nuget using Visual Studio for Mac

### ISSUE THREAD

**Issue by siwenhuang** [UXDivers/Grial-UI-Kit-Support#731]
### Description

 I cannot update nuget using Visual Studio for Mac

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio for MAC
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

https://imgur.com/rWcwcit

**Comment by bolenton** [comment]
I have the same issue. I am getting a not found for http://nuget.uxdivers.com/grial

**Comment by jpbrocca** [comment]
Hi @siwenhuang and @bolenton,
Did you setup the nuget access in the Grial Web Admin?
http://docs.grialkit.com/grial-web-admin.html#grial-web-admin-nuget-access-setup

The grial nuget server requires authentication. 
You need to enter the same credentials you configured in the Grial Web Admin.

You can test your credentials by visiting on your browser:
http://nuget.uxdivers.com/grial

If that all fail, please check:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/376

Let me know how it goes.

Regards
JP

**Comment by fcastro07** [comment]
Hi @siwenhuang ,
I'm closing this issue due to no response and keep things tidy.
Feel free to re-open if needed.
