### ISSUE TITLE
How I can fire an event on grial repeater scroll is on last item to load more items in grial repeater on run time ?

### ISSUE THREAD

**Issue by SufyanAhmad** [UXDivers/Grial-UI-Kit-Support#735]
I am using grial repeater to load list of items and I want to load more items in list on run time when user is on last item by scroll.

**Comment by fcastro07** [comment]
Hi @SufyanAhmad 
Sorry for the late response.

In the next version of Grial.Core will expose the repeater's "Scrolled" event.
With this event and the Width/Height of the items you can add/remove items when you reach the position you want.

As soon as it's available I'll let you know!

**Comment by dirivero** [comment]
The new event is included in version 3.1.74-RC of the UXDivers.Grial package.

**Comment by dirivero** [comment]
I'm closing this issue as this is part of final release 3.1.76.
