### ISSUE TITLE
Can we extend gradient in Android status bar?

### ISSUE THREAD

**Issue by theescapers** [UXDivers/Grial-UI-Kit-Support#737]
Neither the Grial demo app on Google Play, or the app I downloaded for my project extends the gradient into the Android status bar.

It extends into the status bar on iPhone just fine,

iPhone Simulator:

![image](https://user-images.githubusercontent.com/632289/90101794-b0356e00-dd82-11ea-892e-0672e6ce8fc6.png)

Real Android phone : (Nokia 7.1).

![image](https://user-images.githubusercontent.com/632289/90101947-f12d8280-dd82-11ea-93eb-711c2e5e0ad6.png)

I get I can colour the button bar and status bar, but that would be a solid colour not a matching gradient. Can Grial put the gradient into the status bar on Android same as it does on iOS?

Thanks

Garry

**Comment by jpbrocca** [comment]
Hi @theescapers,

the Grial gradients go from top to bottom in any case, but on Android, you need to make the status bar translucid to be able to see through.

![image](https://user-images.githubusercontent.com/15996999/90185512-3c4c9300-dd8d-11ea-94b6-56051edca084.png)

You need to add the following to `styles.xml` file located here:

~~~
AndroidProject
    |_ Resources
        |_ values
            |_ styles.xml
~~~

...on the `AppTheme` style add the following:

~~~
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    ...
    <item name="android:windowTranslucentStatus">true</item>
</style>
~~~

Regards,
JP

**Comment by theescapers** [comment]
That did it, thanks!
