### ISSUE TITLE
Pickers look wrong on Android

### ISSUE THREAD

**Issue by theescapers** [UXDivers/Grial-UI-Kit-Support#739]
![image](https://user-images.githubusercontent.com/632289/90307515-228c8680-df1a-11ea-9208-7ec2779a47e7.png)

Note how the text isn't centred vertically. I've attached a screenshot of the example Grial app, and this exhibits the problem, not just my own app. This is on a Nokia 7.1, Android 10.

**Comment by fcastro07** [comment]
Hi @theescapers 
The bug is fixed and will be available in the next version of Grial.Core, as soon as it's available I'll let you know.

**Comment by fcastro07** [comment]
Hi @theescapers
The bug is fixed and will be available in the next version of UXDivers.Grial, as soon as it's available I'll let you know.

**Comment by theescapers** [comment]
That's fantastic, thank you.

**Comment by dirivero** [comment]
The fix for this is included in version 3.1.74-RC of the UXDivers.Grial package.

**Comment by dirivero** [comment]
I'm closing this issue as this fix is part of final release 3.1.76.
