### ISSUE TITLE
Grial UI Kit license not initialized, please call 'UXDivers.Grial.GrialKit.Init(<license>)' before performing the LoadApplication. (UXDivers.Grial.LicenseException)

### ISSUE THREAD

**Issue by rafaelchei** [UXDivers/Grial-UI-Kit-Support#740]
### Description

Hi!
for some reason when I publish my app in release mode on a real device it crashes, investigating the device logs I found the message "Grial UI Kit license not initialized, please call 'UXDivers.Grial.GrialKit.Init(<license>)' before performing the LoadApplication. (UXDivers.Grial.LicenseException)". I know I called the Init method before the Load Application because the application was working on the last version and because looking at the device logs there is a message "[Grial Kit] Production mode license." before the error message. So anyone have any idea of what could be the cause of the license exception?
Thank you!

### Steps to Reproduce

1. Add the license key in the project as a Embedded resource
2. Initialize the license by calling the Init method
3. Publish the app in release mode to the test flight
4. Open the device logs and see the error message

### Expected Behavior

It should not crash the app once the license is initialized already

### Actual Behavior

It crashes after launch my app

### Basic Information

- Version with issue: 3.0.60
- Last known good version: 
![device_log_LI](https://user-images.githubusercontent.com/2171388/91322861-380d7600-e78e-11ea-9858-b168e23cb238.jpg)

- IDE: Visual Studio for mac
- Platform Target Frameworks: 
  - iOS:  10.0 
  - Android:  
- Android Support Library Version: 
- Nuget Packages: UXDivers.Grial 3.0.6.0
- Affected Devices: Any iOS Device

**Comment by jpbrocca** [comment]
Hi @rafaelchei,

Can you please confirm you are properly calling `Init`, and that there is not any Grial component being used before invoking it?.

If the problem persists, then try by closing VS, deleting all OBJ and BIN folders, open again your solution in VS then try publishing again.

Let me know if it succeeded or not.

Regards and thanks
JP

**Comment by rafaelchei** [comment]
Hi @jpbrocca , sorry for the delay response on this.

I can confirm I'm calling the Init method (it was working already), and I'm not using any Grial component before the Init call.
As a test I've downloaded again the entire solution from the Grial admin website and copied all my files from the old project to this new one, it works fine in all simulators using the debug mode.
I published to the test flight and tried to open in two devices (iPhone 11 Pro and iPhone X), the iPhone 11 is working now but in the iPhone X it crashes at the launch. I'll attach the iPhone X logs so you can see the error again and I'll attach my Appdelegate to help in the investigation.

Thank you for your help.

[AppDelegate.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/5210921/AppDelegate.txt)
![Screen Shot 2020-09-11 at 2 26 43 PM](https://user-images.githubusercontent.com/2171388/92960179-2937ec00-f43b-11ea-9306-40653bc03ab9.png)

**Comment by dirivero** [comment]
Have you tried running the app in Release mode in the simulator or a device?

**Comment by rafaelchei** [comment]
Yes, I just ran in release mode in the simulator (iPhone 11 iOS 13.6) and it worked as expected.

**Comment by dirivero** [comment]
Have you found the problem? Does the iPhone X and iPhone 11 have same versions of iOS?
