### ISSUE TITLE
Billing Issue

### ISSUE THREAD

**Issue by dueguard** [UXDivers/Grial-UI-Kit-Support#744]
### Description
I need to upgrade my subscription I just purchased today but I don't see how I can do this.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @dueguard,
I am closing this issue since I already answered by email.

Regards,
JP
