### ISSUE TITLE
CarouselView Forms plugin

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#746]
Hello, 

When will / is there any plan for Grial UI Kit to move away from https://github.com/alexrainman/CarouselView to another plugin or use Xamarin Native Carousel view to align with AndroidX packages ?
This plugin is still dependent on Xamarin.Android.Support.v7.AppCompat - v25.4.0.2, and haven't been upgraded in a while.

I can't upgrade the dependency on Xamarin.Android.Support.v7.AppCompat to the latest version v28.0.0.3

I am using 
 XF v4.8.0.1364; 
 Grial 3.x (lastest RC);
 Android targeted min v7.1 max v11

Would appreciate your help.

Thank you

**Comment by IoTFier** [comment]
Hi @dirivero , any thoughts on this ?

**Comment by IoTFier** [comment]
Hi @dirivero, @jpbrocca , any thoughts on this please ? Thank you.

**Comment by dirivero** [comment]
Hi @IoTFier,
We are working on this. I'll let you know when ready.

**Comment by dirivero** [comment]
The carousel was replaced as part of release 3.1.76 along with full AndroidX support.

**Comment by IoTFier** [comment]
> The carousel was replaced as part of release 3.1.76 along with full AndroidX support.

Thanks @dirivero .
Any example / steps on how to replace existing code that uses the https://github.com/alexrainman/CarouselView ?

**Comment by dirivero** [comment]
You just need to replace the `ExtendedCarouselViewControl` by `ExtendedCarouselView`.

The source code for the new control is available in version 3.1.76 of Grial, there are just 2 files you need to include: `ExtendedCarouselView.cs` and an Android renderer `ExtendedCarouselViewRenderer.cs`.

The API is exactly the same with the only exception of the properties `NextItem` and `CurrentItem` that are now named `NextAnimatedItem` and `CurrentAnimatedItem`.
