### ISSUE TITLE
When calling ToggleFullScreen in Landscape switches to Portrait iOS14

### ISSUE THREAD

**Issue by rsposato06** [UXDivers/Grial-UI-Kit-Support#749]
### Description
This bug just started occurring with the release of iOS14.  It was working prior to that.  When in landscape on the device and call 
`VideoPlayer.ToggleFullScreen()` from the .Xaml.cs file the video player opens the fullscreen in portrait.  This does not occur when you press the full screen button on the video player.  Only when calling togglefullscreen from the code.  

### Steps to Reproduce
1.  Put device in landscape mode
2.  Call VideoPlayer.ToggleFullScreen()
3.  Video starts playing in Full Screen Portrait. Even thought he device is in landscape.
3.  If press X it goes back to landscape correctly.

### Expected Behavior
Open fullscreen in landscape

### Actual Behavior
Opens fullscreen in portrait

### Basic Information

- Version with issue: 3.0.70 (on iOS14)
- Last known good version: 3.0.27 (anything other than iOS14)
  - iOS:  14
- Nuget Packages:
- Affected Devices: iOS14

### Screenshots
![image](https://user-images.githubusercontent.com/31314001/93927724-485e3580-fce7-11ea-9db2-7d56df76a4f1.png)
![image](https://user-images.githubusercontent.com/31314001/93927768-5c099c00-fce7-11ea-999c-12589f507c59.png)

**Comment by jpbrocca** [comment]
Hi @rsposato06,

Did you make sure to include the following code previous calling `VideoPlayer.ToggleFullScreen()` ?

~~~
DependencyService.Get<IOrientationLockService>().LockOrientation(OrientationLock.Landscape);
~~~

I have tested it and it seems it works correctly if you add the above line before going fullscreen.

Please give it a try and let me know how it goes.

Regards,
JP
