### ISSUE TITLE
Dialog Result Showing Title Twice in Messages

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#75]
Hello, 

We are implementing the messages module from the Grial kit into our application. We have implemented the functionality to allow the user to click on a message to get more information. The dialog box shows the title twice. This is happening in the grial application too. I have attached a screenshot for the same. Please advice how we can resolve this. 
We are using Xamarin Forms 2.2.0.31

![grialerror](https://cloud.githubusercontent.com/assets/20643972/18037222/64be4986-6d44-11e6-80e2-4f4d2e429735.PNG)

**Comment by jpbrocca** [comment]
Hi @scorpio2000, how are you?

Good catch! :)
Please locate your **Styles.xml** file on this folder:

`Droid/Resources/values-v21/Style.xml`

![image](https://cloud.githubusercontent.com/assets/15996999/18039100/e513026c-6d75-11e6-8511-519d5e067336.png)

add the following line to that **Styles.xml** file:

`<item name="android:windowNoTitle">true</item>`

Here is the diff for your convenience:

![image](https://cloud.githubusercontent.com/assets/15996999/18039053/788fdc00-6d75-11e6-8422-bc449637c8d7.png)

Best regards,
JP

**Comment by scorpio2000** [comment]
Thanks Juan. Worked like a charm.

**Comment by jpbrocca** [comment]
Great to hear that! :)

Best,
JP
