### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'AlDiwan.Droid.RtlLabelRenderer'

### ISSUE THREAD

**Issue by shijo-kg** [UXDivers/Grial-UI-Kit-Support#751]
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'AlDiwan.Droid.RtlLabelRenderer'

### Description
Sometimes this error is happing in Android device

### Steps to Reproduce

1. Phone Keep in sleep mode 5 to 10 minute
2. Change RTL direction
3. Crashing phone

### Expected Behavior
Should not crash app

### Actual Behavior
Should not crash app

### Basic Information

- Version with issue:
  - Android: 10

**Comment by jpbrocca** [comment]
Hello @shijo-kg,

Could you please provide the following details?
- Xamarin Forms packages version
- Grial packages version
- Are you testing with a real device or with an emulator?...Please specify which device (brand/model) are you using.

Regards,
JP

**Comment by dirivero** [comment]
Hi @shijo-kg,

If you are using latest Xamarin Forms you can safely remove the `RtlLabelRenderer` from the android project. The original issue has been fixed already.

https://github.com/xamarin/Xamarin.Forms/issues/3077

**Comment by shijo-kg** [comment]
Updated with the latest Xamarin version working.
