### ISSUE TITLE
Text Alignment in IOS

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#752]
I have observed another issue that the text alignment is not proper . I have two languages Arabic and English . in android it aligns them properly to right and left accordingly .
However in IOS there seems to be a problem, If I set flow direction , even English moves towards the right.

**Comment by jpbrocca** [comment]
Hi @ShamineDsouza,
If you set flow direction to RightToLeft, then text should align from right in any case.

I have tested within Grial and with a blank Xamarin Forms project.
If I try the following code:

~~~
<StackLayout
    Margin="20"
>
	<Label
		Text="Hello world"            
		FlowDirection="RightToLeft"
	/>

	<Label
		Text="مرحبا بالعالم"
		FlowDirection="LeftToRight"
	/>
</StackLayout>
~~~

...what I get in any case is a different result in iOS and Android, however, if I add the instructions from MS docs:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left#android

~~~
<?xml version="1.0" encoding="utf-8"?>
<manifest ... >
    <uses-sdk android:minSdkVersion="17" ... />
    <application 
         ... 
         android:supportsRtl="true"
         ... 
    >
    </application>
</manifest>
~~~
...then everything works consistently.

![image](https://user-images.githubusercontent.com/15996999/94447535-3ca7be80-0180-11eb-8f54-c15f5c8f6dfd.png)

![image](https://user-images.githubusercontent.com/15996999/94448102-eab36880-0180-11eb-9d1c-3dbaf33a0ffa.png)


Hope that helps,
JP
