### ISSUE TITLE
Crash on iOS when taking two pictures one after the other (styling issue)

### ISSUE THREAD

**Issue by josesimas** [UXDivers/Grial-UI-Kit-Support#754]
On iPad, an app crashes the second time a picture is taken.

### Description
Our app uses Grialkit and also uses James Montemagno Media plugin (https://github.com/jamesmontemagno/MediaPlugin). I have an issue specific to the iPad/IPad Pro where it crashes if I take two pictures one after the other. I know this may not seem anything to do with you but, apparently, it is related to the styling of the the app. This was the conclusion reached when this bug was submitted to the Media Plugin:

https://github.com/jamesmontemagno/MediaPlugin/issues/450

Here is the conclusion:
"This issue can be closed. It was determined that the UI framework used was styling the slider bar that appears on iPad when the camera is invoked. Removing the styling worked"

With a link to this bug report:
UIImagePickerController freeze when setting UISlider appearance proxy: http://www.openradar.me/30396879

I wonder if this is caused by the styling applied by the Grialkit and I would ask you came across this before

### Steps to Reproduce
1. Create an app styled with Grialkit that invokes the camera and takes a picture
2. Within the same session take two pictures

### Expected Behavior
It should just go on taking pictures without crashing.

### Actual Behavior
The app freezes and eventually crashes without providing any useful log or exception.

### Basic Information

- Version with issue: 2.7.5
- IDE: VS for MAC
- Platform Target Frameworks: 
  - iOS:  13.x
- Nuget Packages:
- Affected Devices: IPad, IPad Pro

**Comment by dirivero** [comment]
Hi @josesimas,
Can you try using latest UXDivers.Artina.* packages version 2.7.13. We've just published that version and it should fix the problem you are having.

**Comment by josesimas** [comment]
Hi @dirivero, many thanks, I upgraded to 2.7.13 and it is fixed on the iPad Pro (I don't have an iPad handy at the moment but the symptoms were the same so I expect the fix to work there too)! Great kudos to you guys for the quick solution.
