### ISSUE TITLE
Editor Text Direction is not changing after RTL change

### ISSUE THREAD

**Issue by shijo-kg** [UXDivers/Grial-UI-Kit-Support#756]
Editor Text Direction is not changing after RTL change

### Description
Editor Text Direction is not changing after RTL change

### Steps to Reproduce

1.  Change the RTL
2.  All Fields direction changed but editor not
3. 

### Expected Behavior
The editor text direction should change based on the RTL direction

### Actual Behavior
Editor text direction not changing

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  All
  - Android: All
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="387" alt="Screen Shot 2020-10-04 at 4 18 59 PM" src="https://user-images.githubusercontent.com/71206266/95015369-7e8fa380-065d-11eb-9646-e46672d3056a.png">
<img width="371" alt="Screen Shot 2020-10-04 at 4 19 07 PM" src="https://user-images.githubusercontent.com/71206266/95015371-818a9400-065d-11eb-94a7-f584e3a6977d.png">

**Comment by shijo-kg** [comment]
Using
Xamarin Form 4.8.0.1269
Grial 3.0.70

**Comment by dirivero** [comment]
Please add the `Setter` below to the Editor style in your App.xaml file:

```
<Style TargetType="Editor" ApplyToDerivedTypes="true">
    <Setter Property="grial:EditorProperties.HorizontalTextAlignment" Value="{ DynamicResource LayoutDirectionHorizontalTextAlignment }" />
    ...
```

We've added the `grial:EditorProperties.HorizontalTextAlignment` property in version 3.0.70.

**Comment by shijo-kg** [comment]
After setting the above it is working fine.
