### ISSUE TITLE
Nuget package error for grial

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#759]
When trying tro add the nuget package in my MAC laptop to build my solution , I  am getting the following error.
Please help.

[Grial Nuget] Unable to load the service index for source http://nuget.uxdrivers.com/grial
The network connection was lost .

ErrorDomain = NSURLErrorDomain Code = 1005

**Comment by jpbrocca** [comment]
Hi @ShamineDsouza,
You have a typo in the URL. 
Please try with:

http://nuget.uxdivers.com/grial

Regards
JP
