### ISSUE TITLE
Icons as a part of button 

### ISSUE THREAD

**Issue by JamesPetras** [UXDivers/Grial-UI-Kit-Support#76]
Hi Guys,

I'm struggling to make Font awesome icons to work as a part of a label. 

I have a button

`<artina:Button Command="{Binding GoPremium}" Style="{DynamicResource SecondaryActionButtonStyle}" Text="{Binding GoPremiumLabel}"  />`

where the GoPremiumLabel is defined

```
public string GoPremiumLabel
		{
			get { return "  " + '\uf073' + "  Go Premium   "; }
		}
```

As the result of this code I get a square with question mark and Go Premium text

Also tried to set value directly in Xaml

`Text=" f073;  Go Premium"  />`

but it shows actual f073 instead of the icon

thanks

**Comment by JamesPetras** [comment]
Ok I think I know why it isn't working: I'm trying to use font awesome in a button instead of a label.

But I came across something else 

you Profile.xaml has this line
```

<Label Grid.Column="1" VerticalTextAlignment="Center" HorizontalTextAlignment="Center">
									<Label.FormattedText>
										<FormattedString>
											<FormattedString.Spans>
												<Span Text="&#xf075; " ForegroundColor="{StaticResource AccentColor}" FontFamily="{x:Static artina:FontAwesome.FontName}" />
												<Span Text="2963" ForegroundColor="White" />
											</FormattedString.Spans>
										</FormattedString>
									</Label.FormattedText>
								</Label>
```

but when I copy the code into my project and save the Xaml file I get

```
<Label Grid.Column="1" VerticalTextAlignment="Center" HorizontalTextAlignment="Center">
			<Label.FormattedText>
				<FormattedString>
					<FormattedString.Spans>
						<Span Text=" " ForegroundColor="{StaticResource AccentColor}" FontFamily="{x:Static artina:FontAwesome.FontName}" />
						<Span Text="2963" ForegroundColor="White" />
					</FormattedString.Spans>
				</FormattedString>
			</Label.FormattedText>
		</Label>
```

(notice Span text from &#xf075 become )

**Comment by JamesPetras** [comment]
Final update I made it to work,

in Xaml ( for me) the only way to show an Icon was using

`"&#xUNICODE; "`

Example on your site (http://grialkit.com/gettingstarted/using-icons/)

`“” + UNICODE + “;”`

Didn't work

**Comment by jpbrocca** [comment]
Hi James,

thanks for the feedback.
Your fix is the right way to add a font awesome icon on Grial.
We will fix the documentation on our website since it is wrong.

Regards and again thanks,
JP

**Comment by brnpatel** [comment]
Hello,

I'm unable to use the Ionicons provided in the kit. I commented out the IconFontFamily set to grialshapes and uncommented the Ionicons. This isn't working per your documentation. I event tried setting the <On platform> specific to the file name for iOS and Android.

Still not working. Please advise.

**Comment by jpbrocca** [comment]
Hi @brnpatel,
Just to make sure, did you remember to:

* ..add the right build action on the font file?
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-working-with-projects-adding-font-icons-to-your-project
* ...reference the icon through the font helper after you specified the IonicIcons font?
https://uxdivers.github.io/Grial-UI-Kit-Support/#grial-uikit-overview-helpers-font-helpers

Regards,
JP

**Comment by brnpatel** [comment]
JP...after two days of frying my brain, I feel extremely stupid forgetting the simplest of steps of adding the files. I figured the font files were already added to info.plist and set to BundleResource. But they weren't. Now it WORKS!!!

You Rock!! Thanks for the quick reply and solution.

**Comment by jpbrocca** [comment]
Hi @brnpatel, you are welcome!
No worries!...It happens to me all the time :)

If you want to suggest any improvement (even on the docs) to make this task easier, then please let me know.

Best regards,
JP
