### ISSUE TITLE
Grial Tabcontrol is having issue in Android but working fine with iOS

### ISSUE THREAD

**Issue by flutterdev-vinit** [UXDivers/Grial-UI-Kit-Support#762]
I am using grial kit tabcontrol in my xamarin forms based app. version is 3.0.70 . 

### Description
I am using tabitem with refresh view . its working fine with iOS but not displaying in android .

### Steps to Reproduce

1. Used <grial:TabControl> in my xaml
2. not displaying in android if i remove grial that it display in android 

### Expected Behavior
This should work in both iOS and Android platform

### Actual Behavior
only iOS is working not android

### Basic Information

- Version with issue:
- Last known good version:3.0.70
- IDE:Visual studio Mac 8.7.8
- Platform Target Frameworks: 
  - iOS:  iOS 14
  - Android: 11 
- Android Support Library Version: 
- Nuget Packages:3.0.70
- Affected Devices:

**Comment by jpbrocca** [comment]
Hi @flutterdev-vinit,

Can you please tell me which Xamarin Forms are you using?

Regards,
JP

**Comment by flutterdev-vinit** [comment]
its 4.8.0.1560

**Comment by jpbrocca** [comment]
Hi @flutterdev-vinit,

Could you please send me a working sample to this email address?
![image](https://user-images.githubusercontent.com/15996999/97487561-cbecf100-193b-11eb-9af1-e440e96f799c.png)

Regards and thanks,
JP

**Comment by dirivero** [comment]
Is this still happening? In case it is, can you send me the example to drivero at uxdivers.com?
