### ISSUE TITLE
Failed to retrieve information about 'UXDivers.Grial' from remote source

### ISSUE THREAD

**Issue by gittieatlas** [UXDivers/Grial-UI-Kit-Support#763]
When I try upgrading the package from nuget source, it fails. 

`Failed to retrieve information about 'UXDivers.Grial' from remote source 'http://nuget.uxdivers.com/grial /FindPackagesById()?id='UXDivers.Grial'&semVerLevel=2.0.0'`

When I try to authenticate at http://nuget.uxdivers.com/grial/, I get the following response: 
```xml
<service xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app" xmlns="http://www.w3.org/2007/app" xml:base="http://nuget.uxdivers.com/grial/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>
```

**Comment by jpbrocca** [comment]
Hi @gittieatlas,
please check: 
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/318

Regards,
JP

**Comment by gittieatlas** [comment]
I fixed the issue by updating other nuget packages this one relies on.
