### ISSUE TITLE
How to make text below then icon on tabitem when using grial Tabcontrol. 

### ISSUE THREAD

**Issue by SufyanAhmad** [UXDivers/Grial-UI-Kit-Support#765]
I am using TabControl for tab menu where icon text is coming on side of icon but we want text should come below the icon. How we can adjust this thing? Here is code:
 `<grial:TabItem Tapped="TabTappedHome" Text="Play" WidthRequest="33"
                    IconText="{ x:Static local:GrialIconsFont.AudioPlay }">`

**Comment by jpbrocca** [comment]
Hi @SufyanAhmad,
you can do that just by modifying the XAML template of the `TabItem`.

You can read more here:
http://docs.grialkit.com/tab-control.html#working-with-the-tabcontrol-look-and-feel

Regards,
JP

**Comment by SufyanAhmad** [comment]
![Screenshot_20201102_185506](https://user-images.githubusercontent.com/14059289/97877681-58821f80-1d3f-11eb-8dfb-aaa9d197c526.jpg)
 Please can you explain a lit bit which modification needed in xml Play should come below the play icon ?

**Comment by jpbrocca** [comment]
@SufyanAhmad Which [tabs resources file](http://docs.grialkit.com/tab-control.html#working-with-the-tabcontrol-look-and-feel) are you using?

**Comment by SufyanAhmad** [comment]
@jpbrocca  here are the files.
 `<ResourceDictionary 	Source="/Styles/TabControl/CustomTabResources.xaml" />
        <ResourceDictionary Source="/Styles/TabControl/DotTabResources.xaml" />`

**Comment by jpbrocca** [comment]
@SufyanAhmad, OK, so you need to locate and edit the  tab item template inside that file:

```
<ControlTemplate x:Key="TabItemTemplate">
</ControlTemplate>
```

...then simply modify the XAML to suit your needs.

I am closing this issue to keep things tidy, but feel free to re-open if needed.

Best,
JP
