### ISSUE TITLE
Grial Development License is failing: License verification failed because: The PackageName does not match the license's

### ISSUE THREAD

**Issue by NicolasKlaas** [UXDivers/Grial-UI-Kit-Support#769]
Today I was trying to launch my development APP build with Grial, though because I did not use it for over a month I had to renew my development license. I did this in the grial admin and put the new Grial license in the root of my android (and iOS) folder.

I already renewed it before and it always worked but now it suddenly does not work. 

I read the license instructions closely and I can't figure out why it is failing, it is highly frustrating. 

**Steps taken:**
1. I downloaded the new license:
![image](https://user-images.githubusercontent.com/34881984/100989712-6c44bf80-3551-11eb-9198-c7d5085160dd.png)

2. I put the new license into the root (Android taken as example):
![image](https://user-images.githubusercontent.com/34881984/100989850-90080580-3551-11eb-9714-cc1099267b37.png)

3. Rebuild the app and relaunch Visual Studio.
4. I am still getting the license error (while the first time i renewed the license it did work).

Extra info:

- Grial init code: `GrialKit.Init(this, "PCS2.APP.Droid.GrialLicense");`

- (Android) namespace: `namespace PCS2.APP.Droid`

- Activity code in `MainActivity.cs`:
```
namespace PCS2.APP.Droid
{
    //https://developer.android.com/guide/topics/manifest/activity-element.html
    [Activity(
        Label = "PCS",
        Icon = "@drawable/icon",
        Theme = "@style/Theme.Splash",
        MainLauncher = true,
        LaunchMode = LaunchMode.SingleTask,
        ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.Locale | ConfigChanges.LayoutDirection
        )
    ]

    //https://docs.grialkit.com/grial-web-admin.html#grial-web-admin-grial-license-setup-license-verification
    public class MainActivity : FormsAppCompatActivity
    {
        private Locale _locale;

        protected override void OnCreate(Bundle savedInstanceState)
        {
            // Changing to App's theme since we are OnCreate and we are ready to 
            // "hide" the splash
            base.Window.RequestFeature(WindowFeatures.ActionBar);
            base.SetTheme(Resource.Style.AppTheme);

            FormsAppCompatActivity.ToolbarResource = Resource.Layout.Toolbar;
            FormsAppCompatActivity.TabLayoutResource = Resource.Layout.Tabbar;

            base.OnCreate(savedInstanceState);

            // Initializing FFImageLoading
            FFImageLoading.Forms.Platform.CachedImageRenderer.Init(enableFastRenderer: false);

            Forms.SetFlags("FastRenderers_Experimental");

            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

            // Initializing Xamarin.Essentials
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);

            // Initializing Popups
            Rg.Plugins.Popup.Popup.Init(this, savedInstanceState);

            GrialKit.Init(this, "PCS2.APP.Droid.GrialLicense");
```

- Made sure that the manifest app name and Activity label match:
![image](https://user-images.githubusercontent.com/34881984/100990821-9f3b8300-3552-11eb-8d94-a2cd3c2c1ba1.png)

- My webadmin project info (with 1 localization set):
![image](https://user-images.githubusercontent.com/34881984/100990989-cc883100-3552-11eb-816a-ba0bfa3c85bf.png)

Any clues what I am missing ..? 

My NuGet libraries used in the Android project (not all):
- Xamarin.Forms 4.8.0.1687
- Xamarin Essentials 1.5.3.2
- UXDrivers.Grial 3.1.76
- Rg.Plugins.Popup 2.0.0.7

**Comment by NicolasKlaas** [comment]
In the end solved it myself by re-downloading the Grial example project and comparing different settings.
For some reason in my Android manifest the package name in my old project was different then the package name in my newly downloaded example project, so I changed that. Furthermore the downloaded example project used as application name `@string/app_name` and in my old project I used `PCS`, I converted the application name back to `@string/app_name` in my old project. The `MainActivity label` of the example project also points to the `string.xml` file which I did not have in my old project so I modified that as well.

After these changes the old project works again. But I do find it weird that the package name has changed and that the string.xml files were missing in my old project, since this old project is also build on a example project.. did anything changed recently?

**Comment by dirivero** [comment]
Hi @NicolasKlaas

First of all, I'm sorry for the inconvenience. 

Is it possible that the app you you downloaded initially didn't have cultures configured? If that was the case the app name is set in the `Activity` attribute of the MainActivity class. When you have multiple cultures defined we moved the app name to the `strings.xml` so it can be localized.
