### ISSUE TITLE
Proper way of adding Artina.Shared.dll

### ISSUE THREAD

**Issue by JamesPetras** [UXDivers/Grial-UI-Kit-Support#77]
Hi Guys,

I have one more issue/question. 

When I was adding your dlls, in my main project folder I created a  subfolder called external ddls and copied all your dlls to it. Afterwards, In Xamarin studio I referenced the dlls in the following way 

Reference right click->Edit References-> .net Assembly -> browse to appropriate dll (ios, andriod and pcl).

And on my local machine, everything works perfectly. 

I have my project hooked to a BitBacked repository and from there to www.bitrise.io. After a few days of coding, I've checked in all the changes to BitBacked, bitrise picked up changes and start building the project. 

After a few minutes, the build failed with the following message:

```
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.Common.targets : warning: Reference 'UXDivers.Artina.Shared' not resolved
/Users/vagrant/git/TXFNewsApp/obj/Release/TXFNewsApp.Views.Account.ForgottenPasswordPage.xaml.g.cs(26,41) : error CS0234: The type or namespace name `Shared' does not exist in the namespace `UXDivers.Artina'. Are you missing an assembly reference?
/Users/vagrant/git/TXFNewsApp/obj/Release/TXFNewsApp.Views.Account.RegisterMePage.xaml.g.cs(56,41) : error CS0234: The type or namespace name `Shared' does not exist in the namespace `UXDivers.Artina'. Are you missing an assembly reference?
```
I double checked my repository on Bitbacked and realised that your dlls are not there. My question is how to fix this problem? When I was adding any other external DLL I did this either via nuget or directly trogh Xamarin store end every single time bitrise was able to restore the package

thanks

**Comment by LeoHere** [comment]
You should use relative paths from the project to the dependency folder to reference assemblies. That should fix the issue.

**Comment by JamesPetras** [comment]
thank you Leo.

Just as a reference for others facing the same problem. Copy Grial folder with dlls to the packages folder and reference all dlls from there

cheers
