### ISSUE TITLE
BrandImage not updating on all views

### ISSUE THREAD

**Issue by ADonelson** [UXDivers/Grial-UI-Kit-Support#770]
I have updated the loading_placeholder.png and logo.png files, in all Drawable resolutions. 
The Slide-out main menu shows the correct BrandImage (logo.png) for the device resolution.
However, all Views are still showing the Grail Boxed default logo. Yet, I cannot find it anywhere in the project. 

### Description
See the attached files

### Steps to Reproduce

1. Update the logo.png file for each android resolution
2. Clean Solutions
3. Build/Deploy

### Expected Behavior
I should see the updated logo.png

### Actual Behavior
I see the default Grail UI Logo (logo.png)

### Basic Information

- Version with issue: 3.1.76
- Last known good version: none
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  NA
  - Android: 5.1 - 10
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android

### Screenshots

![image](https://user-images.githubusercontent.com/52006742/101280015-2de71480-378c-11eb-98e6-6b3ae23f00e7.png)
![image](https://user-images.githubusercontent.com/52006742/101280027-40614e00-378c-11eb-9fe6-e04ba45d4d10.png)
![image](https://user-images.githubusercontent.com/52006742/101280517-3725b080-378f-11eb-8a3e-1cd0e6b9828b.png)
![image](https://user-images.githubusercontent.com/52006742/101280542-5b818d00-378f-11eb-93fa-ca82384ea39b.png)

**Comment by jpbrocca** [comment]
Hi @ADonelson,
I have tested both Android and iOS and when I replace the original images with new ones I do see them.

I think that probably you are expecting that some pages that don´t use the Grial `BrandBlock` should be also updated.
Take a look at the `CustomActivityIndicatorPage.xaml` for instance.

That page is using just one icon included in the grial icons font, but if you want you can just replace the whole `Label` with the `BrandBlock` or just an image:

![image](https://user-images.githubusercontent.com/15996999/101485037-53655100-3939-11eb-8a52-1079e51012c3.png)

![image](https://user-images.githubusercontent.com/15996999/101485188-90c9de80-3939-11eb-8312-0e59a74449f9.png)


Here I just replaced the icon with the `BrandBlock` (you can see the ugly updated ` grial_logo.png` image being properly displayed):


![image](https://user-images.githubusercontent.com/15996999/101485814-7e03d980-393a-11eb-970f-7aa10f9ac824.png)


![image](https://user-images.githubusercontent.com/15996999/101485544-1188da80-393a-11eb-8070-19772313c760.png)

You could search for `{ x:Static local:GrialIconsFont.LogoGrial }` or similar to get where the Grial icon is being used so you can replace it with your own stuff.

Regards,
JP

**Comment by jpbrocca** [comment]
I am just closing this issue to keep whings tidy, but feel free to re-open as needed.

**Comment by ADonelson** [comment]
I ended up seeing that hours later. You are using your own font. Any reason why that icon is not an SVG or something so we can change out for our own logo without creating a font?

**Comment by jpbrocca** [comment]
Yes, the reason is that we deliver all our vector icons as a font since that is much easier to manage (everything is in one file, we also provide the font glyphs helpers so it is easy to reference them, etc).

But, you can always change your XAML to fit your needs (that is why Grial is so flexible!), which means you can replace the `Label` in my example for your SVG.
