### ISSUE TITLE
Merge licenses in one file

### ISSUE THREAD

**Issue by e120guru** [UXDivers/Grial-UI-Kit-Support#771]
Hi,

We have an app that we currently have a license for Grial. We will now build a second variant of this app with a different theme and a different name (for our sister brand). These apps are obviously build from the same code base, but we will have different names and bundle names for the apps.

If we order a second license for this second app - can we merge these two licenses into the same grial license file? Or do we need to let our build system copy one or the other into the right place before building?

/Michael

**Comment by jpbrocca** [comment]
Hi @e120guru,

The merging is not currently supported, so you will need to make sure your build system copies one or the other license file into the right place before building.

Regards,
JP

**Comment by dirivero** [comment]
@e120guru can you contact me directly: drivero [at] uxdivers.com?
