### ISSUE TITLE
Grials License Error

### ISSUE THREAD

**Issue by grTomT** [UXDivers/Grial-UI-Kit-Support#772]
I have downloaded the license file numerous times in Development mode and can't get it to work.
Any help would be greatly appreciated.

![Screen Shot 2020-12-14 at 9 16 26 PM](https://user-images.githubusercontent.com/76029013/102174163-a6676880-3e51-11eb-8c1e-104d0389c804.png)

![Screen Shot 2020-12-14 at 9 14 18 PM](https://user-images.githubusercontent.com/76029013/102174047-58526500-3e51-11eb-9dc5-6642188c0443.png)
![Screen Shot 2020-12-14 at 9 17 13 PM](https://user-images.githubusercontent.com/76029013/102174214-c008b000-3e51-11eb-86c9-37414cc8687e.png)
<img width="634" alt="Screen Shot 2020-12-14 at 9 14 54 PM" src="https://user-images.githubusercontent.com/76029013/102174086-715b1600-3e51-11eb-87b1-efe83dd902c5.png">

**Comment by jpbrocca** [comment]
Hi @grTomT,
what happens if you download a whole new solution from Grial Web Admin and run it...do you get the same result?

Regards,
JP

**Comment by grTomT** [comment]
If I download a simple solution, it works fine.

There is something I am not matching up correctly.


[cid:gigRoninLogo-Final_d4c3c86d-b2e7-4c46-8e24-038845e2510b.png]               Thomas Tupper
Chief Technology Officer
gigRonin
PH 4082427667

**Comment by dirivero** [comment]
For what I can see you have a Grial 3 license but you are using our Grial 2 nuget packages `UXDivers.Artina.*`
Please remove those and use instead `UXDivers.Grial` latest version (3.1.76)

**Comment by grTomT** [comment]
Is it a straight up replacement for the packages?  I have references to 
xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
all over the app.  { artina:Translate LabelWelcomeToGrialStarter }

**Comment by dirivero** [comment]
Most Grial 2 things were kept, for instance, `Translate` will work after the namespace change). Some did suffer name changes like `GridOptionsView` being called `GridView` in Grial 3. Everything is in a single nuget package under a single namespace. 

If you have trouble migrating write me directly at drivero at uxdivers.com
