### ISSUE TITLE
Android App is Crashing when device orientation change

### ISSUE THREAD

**Issue by shijo-kg** [UXDivers/Grial-UI-Kit-Support#773]
### Description
When I am changing divide orientation, getting an exception in GrialKit.NotifyConfigurationChanged method.

### Steps to Reproduce

1. Open Application
2. Rotate the screen
3. Crash

### Expected Behavior
Should not crash

### Actual Behavior
App Crashing

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Galaxy Tab S 10.5
- Platform Target Frameworks: 
  - Android:  6.0.1 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="900" alt="Screen Shot 2020-12-17 at 8 20 04 AM" src="https://user-images.githubusercontent.com/71206266/102444136-dc6b3f00-4041-11eb-8bff-b742f75fbd91.png">

**Comment by jpbrocca** [comment]
Hi @shijo-kg,
could you please let me know the following info?

- Xamarin Forms packages version
- Grial packages version

Regards and thanks,
JP

**Comment by dirivero** [comment]
Is this still happening? If so, can you include the full exception stack trace? Thanks

**Comment by dirivero** [comment]
Closing this issue as we don't have more info. Feel free to reopen if it's still happening.
