### ISSUE TITLE
Arabic UI - Right to Left - Navigation Back button not showing in IOS

### ISSUE THREAD

**Issue by sajirkhan** [UXDivers/Grial-UI-Kit-Support#774]
in Right to Left Arabic UI, Navigation bar back button not showing,
In english view (Left to Right) , it is showing
In arabic view (Right to Left) - Bug

![IMG_6632](https://user-images.githubusercontent.com/8619090/103515521-4ed47f80-4e88-11eb-9e30-22504c05f3fb.PNG)
![IMG_6633](https://user-images.githubusercontent.com/8619090/103515542-5431ca00-4e88-11eb-8121-8b4f36bb2be9.PNG)

**Comment by jpbrocca** [comment]
Hello Sajir, how have you been?

I sent you an email with a proposed solution.
Please give it a try and let me know how it goes.

Best regards,
JP

**Comment by sajirkhan** [comment]
Could you tell me which email you sent the solution ? I didnt find any of them

 

 
Thanks and Regards




 

    On Tuesday, 5 January, 2021, 05:34:08 pm GMT+4, jpbrocca <notifications@github.com> wrote:  
 
 


Hello Sajir, how have you been?

I sent you an email with a proposed solution.
Please give it a try and let me know how it goes.

Best regards,
JP

**Comment by sajirkhan** [comment]
Thanks brocca, it is working after implementating prposed solution

**Comment by dirivero** [comment]
Hi @sajirkhan 
This was fixe in the latest Grial release (3.2.82). Feel free to reopen this issue if you find any trouble.

**Comment by sajirkhan** [comment]
still the issue is not solved in android , version 3.2.82,
