### ISSUE TITLE
How to disable/remove preloader where it shows UXDIVERS?

### ISSUE THREAD

**Issue by weiliu423** [UXDivers/Grial-UI-Kit-Support#776]

**Comment by jpbrocca** [comment]
Hi @weiliu423,

I am not sure what you mean, but in case you want to modify the splash screen you can take a look at this page:

http://docs.grialkit.com/working-locally.html#working-locally-splash-screen

Regards,
JP

**Comment by weiliu423** [comment]
Perfect, just what im looking for. thank you
