### ISSUE TITLE
Grial:CardView BackgroundImageSource

### ISSUE THREAD

**Issue by syahman** [UXDivers/Grial-UI-Kit-Support#777]
how i can add background image to grial:cardview ?

**Comment by jpbrocca** [comment]
Hi @syahman,

As you can read in the docs, the `<Grial:CardView>` derives from Grid:
http://docs.grialkit.com/card-view.html

...so basically you can just add an `<Image>` as the first child of your `Grial:CardView`, then you can overlap content adding as many additional children as you could need.

You can check the `DashboardCardItemTemplate.xaml` for a reference.

Hope that helps!
Regards,
JP
