### ISSUE TITLE
NuGet service unavailable

### ISSUE THREAD

**Issue by juanmalm** [UXDivers/Grial-UI-Kit-Support#778]
### Description

ServiceUnavailable http://nuget.uxdivers.com/grial/FindPackagesById()?id='Microsoft.AppCenter'&semVerLevel=2.0.0 328ms
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.uxdivers.com/grial/FindPackagesById()?id='Microsoft.AppCenter'&semVerLevel=2.0.0'.
Response status code does not indicate success: 503 (Service Unavailable).

[error]The nuget command failed with exit code(1) and error(Failed to retrieve information about 'UXDivers.Artina.Controls.Repeater' from remote source 'http://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.Artina.Controls.Repeater'&semVerLevel=2.0.0'.

### Steps to Reproduce
1. Just do a NuGet restore

**Comment by ArtemKiyashko** [comment]
Confirming the same

**Comment by dirivero** [comment]
We had a small issue with the server but is already fixed. Please try again and sorry about the inconvenience.
