### ISSUE TITLE
Cannot change ObservableCollection during a CollectionChanged event

### ISSUE THREAD

**Issue by dalton5** [UXDivers/Grial-UI-Kit-Support#779]
Hi,

When I nest a grial repeater in another I have an error:

Cannot change ObservableCollection during a CollectionChanged event

I followed the same as ecommerce main page.

My code is as below:

` <grial:Repeater Orientation="Vertical" ScrollBarVisibility="Always"  BackgroundColor="Transparent" ItemsSource="{Binding CatObsColl}" Spacing="10">
                
                <grial:Repeater.ItemTemplate>
                        <DataTemplate x:DataType="local:CatObs">
                        <Grid>
                            <StackLayout Spacing="10" Grid.Row="0" Orientation="Horizontal">
                                <forms:CachedImage WidthRequest="40" HeightRequest="40" Source="{Binding Image, Converter={StaticResource uic}}"/>
                                <Label VerticalOptions="Center" Text="{Binding Name, Converter={StaticResource tc}}" Style="{StaticResource LabelSubSubTitleStyle}" TextColor="{StaticResource RedColor}"/>
                            </StackLayout>

                                <grial:Repeater Orientation="Horizontal" ScrollBarVisibility="Always"  BackgroundColor="Transparent" ItemsSource="{Binding SpecialitiesColl}">

                                <grial:Repeater.ItemTemplate>
                                    <DataTemplate x:DataType="dtos:SpecialityDto">
                                        <StackLayout Orientation="Horizontal">
                                            <forms:CachedImage Source="{Binding Image, Converter={StaticResource uic}}"/>
                                            <Label Text="{Binding Name, Converter={StaticResource tc}}" Style="{StaticResource LabelFormTitle}"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </grial:Repeater.ItemTemplate>
                            </grial:Repeater>
`

CatObsColl and SpecialitiesColl are collectionview. I have also tried with List.

Same issue.

What is wrong?

**Comment by dirivero** [comment]
Hi, what do you mean by collectionview here?
> CatObsColl and SpecialitiesColl are collectionview.

Can you share the viewmodel code? You can send it to drivero at uxdivers.com if you prefer.
