### ISSUE TITLE
Grial TabControl doesn't work after Xamarin Forms update

### ISSUE THREAD

**Issue by muhaym** [UXDivers/Grial-UI-Kit-Support#780]
After updating Xamarin.Forms from 4.3.0.947036 to 5.0.0.2012, UXDivers TabControl doesn't work in Android (it works in iOS). The page shows an empty layout with Tab Items in the middle. 
Grial Version is 2.7.7

Updating to Grial Version 2.7.13 (which is the latest in Nuget), two of my custom renderers are throwing internal error

- There is no argument given that corresponds to the required formal parameter 'context' of 'ArtinaCustomFontLabelRenderer.ArtinaCustomFontLabelRenderer(Context)'
- There is no argument given that corresponds to the required formal parameter 'context' of 'ArtinaButtonRenderer.ArtinaButtonRenderer(Context)'

### Screenshots

![image](https://user-images.githubusercontent.com/10905479/111128545-07125880-859b-11eb-9e77-346cb131df24.png)

**Comment by muhaym** [comment]
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/743 This issue states that it's updated in the 3.x version. Is 3.x free upgrade for 2.x license holders?

**Comment by muhaym** [comment]
The issue is still in the latest 2.x version. Please advise a solution

**Comment by dirivero** [comment]
We've published version 2.7.14 with a fix for this so you can publish a new version with a fix for the iOS pickers quickly.
Also discussed with your coworker Abdul about a strategy for migrating to Grial 3. Grial 2 latest version was published more than 2 years ago so its support has ended already.
