### ISSUE TITLE
Onboarding Video Carousel Highlights

### ISSUE THREAD

**Issue by M-Abdulfatah** [UXDivers/Grial-UI-Kit-Support#782]
Hi there,
I'm using Grial 3 and noticed 2 bugs on the Onboarding Video Carousel Highlights Page when testing on my real devices

### Description
For Android the background video never starts (I'm testing on Android 10)
For IOS The CarouselView is scrolling slowly and laggy sometimes.

I'm running the project you provided without any modifications yet!
I also noticed that your sample application downloaded from the online stores works fine without issues (On IOS and Android) so I'm wondering if you made any specific changes to this screen and didn't implement in the version we have.

### Steps to Reproduce
1. Run the provided project on a real device iOS / Android
2. Navigate to Onboarding
3. Select Video Carousel Highlights

### Expected Behavior
Working exactly as the Grial App from App Store and Play Store

### Actual Behavior
Background video is not working on Android and the CarouselView scrolling is slow and laggy sometimes

### Basic Information

- Version with issue: Grail 3
- Last known good version:
- IDE: Visual Studio Mac
- Platform Target Frameworks: IOS, Android
  - iOS: 11
  - Android: 10 API level 29
- Nuget Packages: 3.2.82 

### Screenshots

![image](https://user-images.githubusercontent.com/38479833/112020599-25e39280-8b39-11eb-96e6-66dd0defc572.png)

**Comment by jpbrocca** [comment]
Hi @M-Abdulfatah,
which version of xamarin forms are you using?

Regards,
JP

**Comment by M-Abdulfatah** [comment]
Hi @jpbrocca,
Thanks for your quick replay, I'm using version 5.0.0.2012

**Comment by jpbrocca** [comment]
Hi @M-Abdulfatah,
I tested both Android and iOS with the Xamarin Forms version untouched from what I downloaded from Grial Web Admin and everything works properly.

Then I updated to Xamarin Forms version `5.0.0.2012` and I could reproduce your issues.
I suggest you don't update Xamarin Forms so you can continue working normally.

Meanwhile, we will investigate and keep you updated.

Regards,
JP

**Comment by M-Abdulfatah** [comment]
@jpbrocca Thank you very much, I hope these issues will be fixed soon during your busy schedules. 

I also noticed one more issue with the linear gradient effect when you use a gradient color with opacity.
The gradient colors rendered fine but it doesn't apply the Opacity values so please check that either.

Thanks very much.

**Comment by jpbrocca** [comment]
Hi @M-Abdulfatah,
could you please show me a sample code of the gradient issue and also could you tell me if this is happening in android, iOS, or on both platforms?

Regards and thanks
JP

**Comment by dirivero** [comment]
@M-Abdulfatah could your problem be related to this? 
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/786#issuecomment-819526003
