### ISSUE TITLE
Arabic Menu drawer not working from Right to Left in Android (3.2.82 - version)

### ISSUE THREAD

**Issue by sajirkhan** [UXDivers/Grial-UI-Kit-Support#783]
In Right to Left Layout (RTL), Drawer open from Left to Right
### Description

In Right to Left Layout (RTL), Drawer open from Left to Right
### Steps to Reproduce

1. App with latest version update Grial 3.2.82 with xamarin 5.0.0.2012
2. Change to RTL 
3. Drawer layout still open from LTR

### Expected Behavior
1.  If Change to RTL ,  Drawer layout should open as RTL layout

### Basic Information
Issue in Android version

### Screenshots
![WhatsApp Image 2021-03-23 at 3 52 50 PM](https://user-images.githubusercontent.com/8619090/112143473-5ab32080-8bf1-11eb-895c-7866661d95c6.jpeg)

**Comment by jpbrocca** [comment]
Hi @sajirkhan,
I have download a new app from Grial Web Admin with the specified packages versions and I swe everything working as expected in RTL. I am testing on a physical device.

![image](https://user-images.githubusercontent.com/15996999/112158149-aa302700-8bc6-11eb-878e-b19f6b7b252a.png)

Can you please let me know more details about the phone you are using to test your app?

Regards and thanks,
JP
