### ISSUE TITLE
Any (easy) way to add an expander to the grial:Datagrid control?

### ISSUE THREAD

**Issue by nicolasHul** [UXDivers/Grial-UI-Kit-Support#784]
I have set up the following Datagrid which works great:

`<grial:DataGrid
	grial:Effects.ApplyIOSSafeAreaAsPadding="Left,Right"
	HorizontalOptions="FillAndExpand"
	ItemSelectedCommand="{Binding ClientSelectedCommand}"
	ItemsSource="{Binding ClientsGridData.ClientsData}"
	RowHeight="80"
	SelectionMode="Row"
	VerticalOptions="FillAndExpand">
	<grial:DataGrid.ColumnDefinitions>
		<grial:DataGridColumn Style="{StaticResource ClientColumn}" />
		<grial:DataGridColumn Style="{StaticResource FinishedRoomsColumn}" />
		<grial:DataGridColumn Style="{StaticResource PercentageAfgerondColumn}" />
	</grial:DataGrid.ColumnDefinitions>
</grial:DataGrid>`

This was based on an example in the Grial UI. 
Though, I would like to extend the rows of the Datagrid with an expander. Usually I would use the Expander from the Xamarin Community Toolkit for this ([link](https://docs.microsoft.com/en-us/xamarin/community-toolkit/views/expander)) in combination with a CollectionView. 

Though the above Datagrid setup is a per-column based setup and not for an entire row. Can I easily add the Expander to the Datagrid component or would I end up with a CollectionView or ListView anyway? 

Any examples would be great.

**Comment by jpbrocca** [comment]
Hi @nicolasHul,
The DataGrid is meant for displaying tabular data, so this scenario is not currently supported.

I am closing this issue to keep things tidy, but feel free to re-open if needed.

Regards,
JP
