### ISSUE TITLE
Using Grial 2.7.1 with latest Xamarin Forms 5

### ISSUE THREAD

**Issue by eglibecerra** [UXDivers/Grial-UI-Kit-Support#785]
Hi guys sorry to reach out again, back in 2020 i couldn't make those updates as I was on other projects, but now I have sometime to work on this... as you know currently the latest version of X.F is 5. (https://github.com/UXDivers/Grial-UI-Kit-Support/issues/680)

Our app build with Grial 2.7.1 is being used internally through enterprise and for the purpose it was build for there's no need for us to upgrade to the latest Grial version. (nor we have the budget to do so)

My question
Our mobile application is still published internally but is no longer working in IOS (still works in android) and I need to fix it ASAP (I'm guessing it's because of the UIWebView which jpbrocca mentioned above) which is still referencing X.F3.

So my question is can I upgrade my version of X.F 5 and still use Grial 2.7.1 or is there any known compatibility issues with those 2 versions? and if there is whats the highest version of X.F compatible with Grial 2.7.1.

Also are there any upgrade guides i can follow if any?

Cheers

**Comment by jpbrocca** [comment]
Hi @eglibecerra,

Please refer to this post:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/680#issuecomment-813637396

Let me know if you have questions.

Regards,
JP
