### ISSUE TITLE
Updating to latest Xamarin.Forms causes iOS app to become unresponsive

### ISSUE THREAD

**Issue by UsherNet** [UXDivers/Grial-UI-Kit-Support#786]
I have just created a new app, downloaded the source and compiled.  

I run under Android - everything works as expected.

Run under iOS (simulator) iOS 14.4, and everything works.  

Update Xamarin.Forms libs as per Visual Studio message. 

I run under Android - everything works as expected.

Run under iOS (simulator) iOS 14.4, attempt to show the Full Background Login - app becomes unresponsive. 

- Version with issue: 3.2.82
- Last known good version: n/a
- IDE: Visual Studio 2019 Mac & Visual Studio 2019 Windows
- Platform Target Frameworks: 
- iOS:  14.4

**Comment by jpbrocca** [comment]
Hi @UsherNet,
I downloaded a customized solution from Grial Web Admin that includes the Full Background Login, then opened it in Visual Studio.

I was notified by Visual Studio about the need to update Xamarin Forms to `5.0.0.2012` to make the previewer work properly.
Then I updated.

Run the app, and when I try to navigate to the Full Background Login page the app starts to behave slowly but after some time I finally navigate to the page. Tried again several times and this behavior is somehow erratic, meaning that sometimes it works as expected but most of the time, the page finally works but takes different amounts of time each time.

Then, I stopped debugging, then I opened directly the app in the device and each time I opened it worked properly (not experiencing any delay). So I guess this could be an issue related to the Previewer in Visual Studio.

I am testing with:
Visual Studio Enterprise 2019 for Mac
Version 8.9.5 (build 4)

Could you try opening the app (not debugging) and let me know how it behaves?

Regards and thanks,
JP

**Comment by UsherNet** [comment]
I am testing with:
Visual Studio Enterprise 2019 for Mac
Version 8.9.5 (build 4)

If I run the app directly on the device (simulator) then it runs correctly.

Further tests have caused Visual Studio Mac to freeze requiring a "force quit".

I also noticed in the Visual Source Tree, the counter increasing rapidly.

![image](https://user-images.githubusercontent.com/566827/114447939-4d98b880-9c16-11eb-88cc-b96aa117650c.png)

**Comment by jpbrocca** [comment]
Hi @UsherNet, thanks for the details.

It seems this is something more related to Visual Studio than to Grial, so I will close the issue now but feel free to re-open it if you find anything else that could point to Grial.

Regards and thanks,
JP

**Comment by dirivero** [comment]
@UsherNet, please take a look at this issue: https://github.com/xamarin/Xamarin.Forms/issues/14010

The Hot Reload is having problems with ListViews having CachingStrategy="RecycleElement". It keeps instantiating visuals until it crash. Until it's fixed, you can change its behavior "Full Page":

![image](https://user-images.githubusercontent.com/7670773/114719366-62a44300-9d0d-11eb-9600-9db72bca1ac2.png)

**Comment by UsherNet** [comment]
Awesome. Thank you.
