### ISSUE TITLE
Supporting multiple app versions/environments side-by-side

### ISSUE THREAD

**Issue by miroslavpopovic** [UXDivers/Grial-UI-Kit-Support#788]
Hello,

We are using a production Grial UI Kit license, for quite some time. As we have multiple environments, we have the request from the management to allow installing multiple app versions side-by-side (Dev/Test, Alpha/Staging, Beta/Production). They would be differentiated by an icon and/or name (with env suffix). However, in order to achieve this, we would need to have a different package name (bundle identifier), but the Grial license is connected to the package name/id.

Is it possible to have this using our existing license, or we need to purchase additional license(s)? If we need to purchase more, are there some discounts for those, as they will be used only for dev/testing purposes?

**Comment by dirivero** [comment]
Hi @miroslavpopovic,
Please send me an email to drivero at uxdivers.com
