### ISSUE TITLE
Application Restarts when connecting or disconnecting a bluetooth device

### ISSUE THREAD

**Issue by tillits** [UXDivers/Grial-UI-Kit-Support#789]
Whenever I connect or disconnect a bluetooth barcode scanner with my device the app restarts.

I have also tested this on the Demo app that is available on the Playstore and it reacts the same way.
I've read that it should be related to configuration changes, but it doesn't raise the OnConfigurationChanged event, I have also tried changing the android:configChanges values using this solution: https://stackoverflow.com/questions/25735227/bluetooth-keyboard-will-cause-activity-destroy-and-recreate?noredirect=1&lq=1 without any luck yet.

**Comment by tillits** [comment]
Additional Info: https://stackoverflow.com/questions/31032042/android-get-restarted-once-it-is-connected-or-disconnected-to-bluetooth-device

**Comment by dirivero** [comment]
Have you tried adding the proper config changes to the Android's main activity so they are handled through the OnConfigurationEvent?

**Comment by tillits** [comment]
It doesn't raise the OnConfigurationChanged Event

public override void OnConfigurationChanged(Android.Content.Res.Configuration newConfig)
{
    base.OnConfigurationChanged(newConfig);

    GrialKit.NotifyConfigurationChanged(newConfig);
}

**Comment by tillits** [comment]
It looks like it changes the HardKeyboard Configuration, however, it doesn't raise the event we previously mentioned

**Comment by tillits** [comment]
Solution Found:

`//https://developer.android.com/guide/topics/manifest/activity-element.html
    [Activity(
        Label = "*****************",
        Icon = "@drawable/icon",
        Theme = "@style/Theme.Splash",
        MainLauncher = true,
        LaunchMode = LaunchMode.SingleTask,
        ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.ScreenSize | ConfigChanges.Locale | ConfigChanges.LayoutDirection | ConfigChanges.Keyboard | ConfigChanges.KeyboardHidden
        )`

Had to add ConfigChanges.Keyboard and ConfigChanges.KeyboardHidden here
