### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by kepbem** [UXDivers/Grial-UI-Kit-Support#79]
HI I was wondering if you could help me with this?
I have just added to my Nuget packages Xamarin.Forms.Maps and I think It has updated my version of xamarin Forms also, could this be what is causing the error?

Any help would be really appreciated, I am only learning this lark!! 
Thanks in advance,

![image](https://cloud.githubusercontent.com/assets/22010574/18255991/58cc3534-73a7-11e6-81c4-f4731f545b46.png)

**Comment by jpbrocca** [comment]
Hi, I don't think updating xamarin forms could cause this issue (I am using latest on the development branch of Grial 2.0 with no issues).

Try manualy deleting packages files and try adding just xamarin forms and maps packages again. 

Hope that helps!
Best,
JP
Looks more

**Comment by kepbem** [comment]
HI,

Thanks for getting back to me. I don't have the 2.0 version though, I bought the UI kit a few days ago version 1.5.0 do I need to buy an upgrade?

I don't think the xamarin forms maps is the issue, it keeps making me install other google packages with it, I'll try to remove them see what happens.

Cheers,

Paul.

**Comment by kepbem** [comment]
Hey Man,

I tried removing the packages like you said, even removed the Xamarin.Forms.Maps one but then the whole solution shit itself and errors started to show up! I have tried to manually added back NuGet packages that it seems to be missing from the the sample project but they don't add?
![image](https://cloud.githubusercontent.com/assets/22010574/18258924/191fbff8-73d6-11e6-9dbe-e9eb0651c785.png)

**Comment by jpbrocca** [comment]
Hi,
What I meant is that I am using latest xamarin forms on Grial 2.0 which is under development, latest public version is 1.5 which is the same you have.


Packages could be hard to handle sometimes.
There are some that depends on other so you need to even remove/add them in specific order.

Check this:
https://developer.xamarin.com/guides/xamarin-forms/troubleshooting

Regards, 
JP

**Comment by kepbem** [comment]
HI,
Sorry to bother you again, could you please give me some advise. All i am trying to do is install the Xamarin.Forms.Maps. I rolled it back to the same version as Xamarin but then gives this error _'No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version'). ' I have then tried variations of removing shared packages and doing a clean then rebuilding but I always get this error in the attached screen grab. Any advice or help please would be great, or at least can you tell me what working versions of xamarin.forms, xamarin.fomms.maps, and its dependencies work with the ui kit 1.5 that i purchased?
Any help would be greatly appreciated.
Thanks,
Paul
![image](https://cloud.githubusercontent.com/assets/22010574/18406491/7a48898c-76f5-11e6-923b-b7c2af1eb783.png)

**Comment by kepbem** [comment]
Its ok, i think I have it fixed by uping the heap size. Sorry to bother you.
Think its a great framework to kick-start educational projects, have you any guides on maps and xaml or recommend anywhere that can help?

**Comment by jpbrocca** [comment]
Hi @kepbem,

We didn't include maps on Grial because by the time we were working in Grial 1.0 that was a very problematic control.

You should check the blog of our very good friend Tawfik:
http://www.isosoft.org/taoffi/post/2016/05/07/Xamarin-forms-maps-lets-talk-renderers-2-Droid

He is the man with more experience on maps I know.

Best regards,
JP

**Comment by kepbem** [comment]
HI @jpbrocca 
I am so sorry to keep asking you questions, but I am having real difficulties with this. Do you know or are aware of any other users that have a Maps working with the UI Kit and what version they are using?

Cheers,

Paul

**Comment by jpbrocca** [comment]
Hi @kepbem,

No, I don't know  about other guy than Tawfik.
Did you try to ask him con his blog? 

I am sure he would give you advice as well as some invaluable tipos (he is a very friendly guy).

Did you research on xamarin forum about issues with maps?

Best,
JP
