### ISSUE TITLE
Youtube videos show 404 error

### ISSUE THREAD

**Issue by luisnovaisdev** [UXDivers/Grial-UI-Kit-Support#790]
When try to play video in VideoPlayer gives 404 error, this worked in one month ago, can you check that please ?

**Comment by dirivero** [comment]
Can you try with latest version of UXDivers.Grial nuget package? v3.2.83

**Comment by Fatihpk** [comment]
Hi @dirivero the Youtube video's worked fine after updating to v3.2.83 untill yesterday! Now no youtube video will work anymore. 

Any idea??

**Comment by dirivero** [comment]
It seems to be working fine on my side, can you send me a video URL that doesn't work?

**Comment by Fatihpk** [comment]
Hi @dirivero . not working on iOS and Android : 

Dit try both url : 

https://youtu.be/S985xPL9Xn0
https://www.youtube.com/watch?v=S985xPL9Xn0

**Comment by Fatihpk** [comment]
Any update @dirivero ?

**Comment by dirivero** [comment]
I've just tried downloading a Grial solution from the Grial Web Admin with the MovieDetailPage in it, changed the video URL to the one you sent and it load correctly. Both URLs work fine. Can you try that?

**Comment by Fatihpk** [comment]
I just downloaded in the Grial Web Admin same project name with only the MobieDetailPage and changed the Video URL but I stil see the 'Error loading video' error.

**Comment by Fatihpk** [comment]
Hi @dirivero I just made a simple empty page with the next line :

`        <grial:VideoPlayerContainer>
        
            <grial:VideoPlayer
                Source="https://www.youtube.com/watch?v=S985xPL9Xn0"/>

        </grial:VideoPlayerContainer>`

And still the same : 

![screenshot](https://user-images.githubusercontent.com/20399409/123512288-ed4adc00-d686-11eb-9ea9-5b00b768c46d.jpg)

:(

**Comment by dirivero** [comment]
That's weird. Is that page running inside your app or inside a brand new Grial app downloaded from the Web Admin? I'm wondering if there's something specific in your app that might be blocking the video player...

**Comment by Fatihpk** [comment]
It is a clear NEW project from the Web Admin with only the MovieDetailPage thats it. Just like i said before. The youtube video's worked fine untill a couple days ago suddenly dit not work (without changing anything with the player). :( 

Can I sent you the simple project with a DM?

**Comment by Fatihpk** [comment]
Hi @dirivero this is last thing in our project :(  Can we solve this please!

**Comment by Fatihpk** [comment]
OK! I just find out that this has nothing to do on our side. I have restored a old backup (where it simple work'd) and still not working. I think that something has changed on Youtube side! Please investigate!

**Comment by dirivero** [comment]
Contact me directly to drivero at uxdivers.com.

**Comment by Fatihpk** [comment]
> 
> 
> Contact me directly to drivero at uxdivers.com.

I just sent you the project email!

**Comment by Insire** [comment]
Any update on this? Am using 
```xml
<PackageReference Include="UXDivers.Grial" Version="3.2.83" />
```

I can reproduce this with the full grial solution app using the movies flow. Playback for youtube videos, including [this](https://www.youtube.com/watch?v=8_rTIAOohas) one seems to be broken.

**Comment by dirivero** [comment]
Can you try upgrading the nuget to latest version 3.2.85?

**Comment by Insire** [comment]
Will do on monday and report back.

**Comment by Insire** [comment]
'''xml
   <PackageReference Include="UXDivers.Grial" Version="3.2.85" />
'''
works as expected. 

Thx!
