### ISSUE TITLE
Shell sample

### ISSUE THREAD

**Issue by quintonv** [UXDivers/Grial-UI-Kit-Support#791]
Hi, could you please provide a sample that contains the fly out and the custom tab control. Preferably in the new Shell layout. I've been trying to combine the tab and menu at the same time but not getting it right with the custom controls.

**Comment by jpbrocca** [comment]
Hi @quintonv, how are you?

Unless I am missing something you already have a sample of what you are asking in the Grial Demo app -except for the Shell-:

![image](https://user-images.githubusercontent.com/15996999/121021760-178c3680-c778-11eb-9d4a-fb31e52cbf0f.png)

![image](https://user-images.githubusercontent.com/15996999/121021784-1d821780-c778-11eb-88ec-056c6f13ddaf.png)

Regards,
JP

**Comment by quintonv** [comment]
@jpbrocca I did see that, but that's not using the shell like I asked. It's using a flyout navigation with tab control on that, so not sure how to rather extend the Shell to use the custom tab from Grial into the Shell if that makes sense.

**Comment by NarenDBB** [comment]
**grial:GrialNavigationBar** not working in Shell based naviagtion
is there any possible way to make this work in Shell based naviagtion??

Also is there any shell based template sample for grial UI - which we can use it now

**Comment by quintonv** [comment]
> 

It would help a lot. Sadly they don't seem to be addressing this. I actually removed Grial from my application, even after paying so much money for it in the first place...

**Comment by marketdevsoft** [comment]
Hi, is there somethings news about integration of shell-integration in grial ui kit? We need it... is very important !

**Comment by dirivero** [comment]
Here you can read about integrating Shell in Grial for .NET MAUI:
https://docs.grialkit.com/working_locally/shell_maui
