### ISSUE TITLE
Check icon from GrialIconsFont not loading in IOS 

### ISSUE THREAD

**Issue by SufyanAhmad** [UXDivers/Grial-UI-Kit-Support#792]
I am using grial icons every thing fine but check icon not loading on ios.
### Steps to Reproduce

1.       <Label
				                                                            Text="{ x:Static local:GrialIconsFont.Check}"
				                                                            FontSize="22"
				                                                            TextColor="#ffd280"
                                                                              FontAttributes="Bold"
                                                                            Grid.Row="0"
                                                                                Margin="25,10,0,0"
                                                                             IsVisible="{Binding CommentState}"
				                                                            Style="{ StaticResource FontIconFill }"
                                                                            VerticalOptions="Start" 
                                                                            HorizontalOptions="End"/>
2. 
3. 

### Expected Behavior

Check mark should on author image  in ios, Fine on android
### Actual Behavior

Question mark is coming on author image on ios but okay on android 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/14059289/120959315-e6f5ce00-c772-11eb-9f55-a989cc3d5281.png)
![image](https://user-images.githubusercontent.com/14059289/120959606-99c62c00-c773-11eb-8c6e-75f7061485c6.png)

**Comment by jpbrocca** [comment]
Hi @SufyanAhmad, how are you?

Can you please tell me which Xamarin Forms and Grial packages version are you using?
Also, which is your iOS version?

Regards and thanks
JP

**Comment by jpbrocca** [comment]
Hi again @SufyanAhmad,

I made a quick test and I found the reason:

![image](https://user-images.githubusercontent.com/15996999/121020466-c3cd1d80-c776-11eb-8a8b-59c9c5ad8fc1.png)

...so you should remove the `FontAttributes="Bold"` to get the icon properly displayed.

I am closing this issue but feel free to reopen it if needed.

Regards,
JP
