### ISSUE TITLE
ExportRendererAttribute build error Xamarin forms project update to X.F 5.0.0.X using UXDivers 2.7.14

### ISSUE THREAD

**Issue by eobecerra** [UXDivers/Grial-UI-Kit-Support#794]
Hi tream I recently updated to Xamarin forms X.F 5.0.0.X (tried with all 5 versions) using UXDivers 2.7.14

### Description
And now I'm getting this weird build error "The type 'ExportRendererAttribute' exists in both 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' <In the Android project>\Properties\AssemblyInfo.cs

### Steps to Reproduce
Update the UXDivers (2.7.14) Xamarin forms project to use latest version of X.F 5 

### Expected Behavior

Should build without errors
The build errors happen

### Actual Behavior
Severity	Code	Description	Project	File	Line	Category	Suppression State
Error	CS0433	The type 'ExportRendererAttribute' exists in both 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'	CrossPlatform.CSR.Achieve.Droid	C:\XXX.Droid\Properties\AssemblyInfo.cs	15	Compiler	Active

![image](https://user-images.githubusercontent.com/77310819/122666397-48e11980-d1f0-11eb-9e17-405ca651e638.png)

### Basic Information
- Version with issue: UXDivers 2.7.14 with Xamarin forms 5.0.0.X
- Last known good version:  Xamarin forms 3.X
- IDE: Visual Studio 2019 
![image](https://user-images.githubusercontent.com/77310819/122666477-c6a52500-d1f0-11eb-91c5-aa8d94c8b9b5.png)

- Platform Target Frameworks: 
  - iOS:  14
  - Android: 11.0 (API Level 30)
- Nuget Packages:

"Com.Airbnb.Xamarin.Forms.Lottie" Version="2.4.0" 
"Plugin.Fingerprint" Version="1.4.7"
"Prism.Core" Version="7.0.0.396"
"Prism.Forms" Version="7.0.0.396"
"Prism.Unity.Forms" Version="7.0.0.396"
"Refractored.XamForms.PullToRefresh" Version="2.2.2"
"RestSharp" Version="106.3.1"
"UXDivers.Effects" Version="0.6.3"
"Xam.Plugin.Connectivity" Version="3.2.0"
"Xam.Plugins.Vibrate" Version="4.0.0.5"
"Xamarin.FFImageLoading" Version="2.4.3.840"
"Xamarin.FFImageLoading.Forms" Version="2.4.3.840"
"Xamarin.FFImageLoading.Transformations" Version="2.4.3.840"
"Newtonsoft.Json" Version="11.0.2"
"Xamarin.Forms" Version="5.0.0.1931"
"UXDivers.Artina.Shared.Base" Version="2.7.14"
"UXDivers.Artina.Shared" Version="2.7.14"
"UXDivers.Artina.Controls.Tab" Version="2.7.14"
"UXDivers.Artina.Controls.Repeater" Version="2.7.14"

- Affected Devices:
 Just the Android project has this build error.

**Comment by jpbrocca** [comment]
Hi @eobecerra, how are you?

I tried to reproduce your issue but I wasn't able to.

Here is what I did:

- I downloaded a Grial Full solution from Grial Web Admin.
- I updated packages to the latest version of Xamarin Forms (`5.0.0.2012`) and Artina packages to `2.7.14`.
- Then I tried to run but had some issues on Android. 
Visual Studio complained saying I needed to target a higher version of Android, and I did so:

<img src="https://user-images.githubusercontent.com/15996999/122807095-86ea4600-d2a1-11eb-9253-7b1b7e4d7365.png" width="370"/>

- Tried again and I got this:

<img src="https://user-images.githubusercontent.com/15996999/122807195-a5e8d800-d2a1-11eb-9168-810937744434.png" width="370"/>

- So I took a look at the android project packages and found this:
<img src="https://user-images.githubusercontent.com/15996999/122807696-4939ed00-d2a2-11eb-9563-5b7ab51e6240.png" width="370"/>

- I manually retargeted each of those packages:
<img src="https://user-images.githubusercontent.com/15996999/122807351-dc265780-d2a1-11eb-9981-702276953398.png" width="370"/>

Tried again and I was notified I needed to make sure to add this package and versions:
```
<PackageReference Include="Xamarin.AndroidX.ExifInterface" Version="1.3.1" />
<PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.2.0" />
<PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0.5" />
```

- Then I did the typical clean, rebuild, etc., closed and reopened the solution, tried to run again and it worked (I am testing with a real device):
<img src="https://user-images.githubusercontent.com/15996999/122807578-23144d00-d2a2-11eb-8582-04506c127e81.png" width="370"/>

Hope that helps!
Regards,
JP

**Comment by eobecerra** [comment]
Hi @jpbrocca, thanks for getting back to me so quickly, yes I have replicated your steps the updates to those packages

<PackageReference Include="Xamarin.AndroidX.ExifInterface" Version="1.3.1" />
<PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.2.0" />
<PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0.5" />

Seem to have been the culprits, also what i noticed is that when you upgrade XF for some reasons the old version dll wasnt removed after a clear/rebuild so now i know to delete that manually if i ever upgrade thanks :)

**Comment by jpbrocca** [comment]
Hi @eobecerra , how are you?

Ok, it seems you succeeded so I am closing this issue to keep things tidy, but feel free to reopen if needed.

Regards,
JP
