### ISSUE TITLE
iOS License read error

### ISSUE THREAD

**Issue by arashkatchooi** [UXDivers/Grial-UI-Kit-Support#795]
I keep getting the same error as below: 
Shared.LicenseException: Error reading license. ---> System.ArgumentNullException: Value cannot be null
i followed this link to troubleshoot but it seems the issue is still there:
https://docs.grialkit.com/troubleshooting.html

the license file is not marked as Embedded Resource ... the file is embeded resource
…or it is not in the root of the platform specific project.... file is in the root of iOS project
…or the embedded resource is not correctly named following the convention:
<Default Namespace of the Container Project>.<Name of the File> above explained. 
file name is GrialLicense but i initialize it as namespace.GrialLicense 

as your info i did the same way on android and it worked but it doesn't work on iOS on browaserstack platform and i am not sure where to check to resolve this issue

**Comment by dirivero** [comment]
I'm not familiar with browserstack ios simulators/devices, but I can tell you that that error happens if the app can't read the following Stream:

```
Stream stream = assembly.GetManifestResourceStream("namespace.GrialLicense")
```

That `assembly` is to the AppDelegate's assembly.

Please verify that this manifest resource is available at runtime.
