### ISSUE TITLE
SwitchCell Text Color iOS

### ISSUE THREAD

**Issue by raymond-dillon** [UXDivers/Grial-UI-Kit-Support#796]
Switch Cell Text Color is White on iOS

### Description
When using the settings page with switch cells, the text is white. This occurred on Android as well but a fix was documented at https://github.com/UXDivers/Grial-UI-Kit-Support/issues/715.

I suspected there's some property under the iOS project I can change?
 

### Steps to Reproduce

1. Use the Settings Template XAML as is.
2. Load page on iOS

### Expected Behavior
Switch Color takes accent color.

### Basic Information

- IDE: VS2019 Community
- Affected Devices: any iOS Device

### Screenshots

![MediaItem_0](https://user-images.githubusercontent.com/28100585/123789750-6a6b9080-d8d5-11eb-8d21-1998f541ca4b.JPEG)

**Comment by jpbrocca** [comment]
Hi @raymond-dillon, how are you?

I made this fast test:

- I downloaded a new solution from Grial Web Admin and included the SettingsPage.
- Then, I run it and checked on a iOS 8 phone (simulator):

![image](https://user-images.githubusercontent.com/15996999/123810651-f62af000-d8c8-11eb-82c2-d6df915ff84c.png)

I can see the text in black color.
Please check the package's version from my screenshot...maybe you need to update some of them.

Regards,
JP

**Comment by raymond-dillon** [comment]
I'm good - thank you for the quick response by the way! All XF and UXDivers packages are up to date. Labels etc render with the correct colour, but just not labels in switch cells. 

Is it possible I've changed a grail colour in the iOS project inadvertently which is causing the issue?

**Comment by jpbrocca** [comment]
Hi @raymond-dillon, you are welcome.

I am not sure.
The `SwitchCells` are sometimes not respecting colors.
If you need a workaround just replace the page with the `CustomSettingsPage`
![image](https://user-images.githubusercontent.com/15996999/124053404-8ca8ff80-d9f6-11eb-8de8-9a940662ed2d.png)



Best regards,
JP

**Comment by raymond-dillon** [comment]
Hi @jpbrocca - thanks for the response. I'll have to find al alternative workaround. Just realised that page isn't included in our license.

**Comment by raymond-dillon** [comment]
@jpbrocca - Solved it using a View Cell with a Label and Switch and worked as expected. Thank you!
