### ISSUE TITLE
Style help please

### ISSUE THREAD

**Issue by quintonv** [UXDivers/Grial-UI-Kit-Support#799]
Hi

I've been trying to fix the white space at the bottom in this screenshot. Directly after my splash this screen shows while loading my next page (it shows maybe 3 seconds then my main page RootFlyoutPage loads). What style do I need to edit to fix that white so that the image loads full.

![image](https://user-images.githubusercontent.com/30532/129434133-ed528483-3bfe-464e-acc0-ecbcaf5e6743.png)
Thanks
Quinton

**Comment by dirivero** [comment]
It looks like the NavigationPage background. You can either set a color in the App.xaml default style for NavigationPage, or set a taller navigation bar height (600 is the default):

```
<Setter Property="grial:GrialNavigationPage.BarBackgroundHeight" Value="600" />
```
