### ISSUE TITLE
ArticleViewPage + WebView

### ISSUE THREAD

**Issue by JamesPetras** [UXDivers/Grial-UI-Kit-Support#80]
Hi Guys,

I'm trying to reuse your design of the ArticleViewPage but I'm facing the following issue:

my article is HTML. If I just replace the content of Post.Body element with my source the page shows all html tags. Can you please post code which will use an instance of WebWiew for the HTML display?

I tried to replace

```
<StackLayout
						Padding="20"
						BackgroundColor="White">
						<!-- MAIN PARAGRAPH -->

						<Label
							Text="{ Binding Post.Body }"
							VerticalOptions="EndAndExpand"
							TextColor="#8a8a8a" />
					</StackLayout>
```

with
```
<StackLayout
						Padding="20"
						BackgroundColor="White">
						<!-- MAIN PARAGRAPH -->
						<WebView
							Source="http://www.uxdivers.com"
							VerticalOptions="EndAndExpand">
						</WebView>
					</StackLayout>
```
but the form doesn't show the webview at all. Any idea?

Thanks

**Comment by jpbrocca** [comment]
Hi James, did you make sure you added internet percussion for the app?
This could be the reason why you don't see the webview content.

Another things that always comes handy is to change the Background color of the element to make sure it is actually being rendered. Sometimes the layout that contains the element you want to check doesn't have enough space to render its content.

Hope that helps!

Best,
JP

**Comment by JamesPetras** [comment]
Hi JP,

I made the modification on your example project. You already have a page with webvVew there (AboutPage.xaml) pointing to http://www.uxdivers.com so I don't think it's an issue with iOS 9 and non https website.

So what I did is literally opened ArticleViewPage line 118 and inserted the following code (above the label)

```
<WebView
							Source="http://www.uxdivers.com"
							VerticalOptions="EndAndExpand"
							BackgroundColor="Maroon">
						</WebView>
```
But the webView was not displayed. 

Just to make sure that I'm modifying the right page I added a label above the webView 

```
<!-- MAIN PARAGRAPH -->
						<Label
							Text="next element should be a webView"
							VerticalOptions="EndAndExpand">
						</Label>
						<WebView
							Source="http://www.uxdivers.com"
							VerticalOptions="EndAndExpand"
							BackgroundColor="Maroon">
						</WebView>
						<Label
							Text="{ Binding Post.Body }"
							VerticalOptions="EndAndExpand"
							TextColor="#8a8a8a" />
					</StackLayout>
```
Please what I get
[https://www.dropbox.com/s/vb2p94x4lv9f520/Untitled.png?dl=0](url)

**Comment by JamesPetras** [comment]
Hi Guys,

do you have any update on this issue?

thanks in advance
James

**Comment by jpbrocca** [comment]
Hi James, sorry for the delay on this.
I tried several options but it seems this a problem on the WebView itself.

The only workaround I found was just setting the height, so that way the WebView will know its dimension and render on the place you are adding it.

Try with this:
```
<StackLayout 
	BackgroundColor="{ StaticResource BasePageColor }">


	<BoxView 
		Style="{StaticResource Horizontal1ptLineStyle}" />

	<!-- MAIN PARAGRAPH -->
	<WebView 
			HeightRequest="400"
			Source="{ StaticResource AboutPageURL }"
			VerticalOptions="FillAndExpand" />
</StackLayout>
```

**Comment by JamesPetras** [comment]
Thank you JP
