### ISSUE TITLE
How to add button like "RTL" and "Settings" icon on top of the app

### ISSUE THREAD

**Issue by turgaygncr** [UXDivers/Grial-UI-Kit-Support#800]
Hello,
I want to add button like "RTL" and "Settings" icon on top of the app. I couldn't find where to add it. Can you help me ?
I also added it as a picture on attachments.

Thanks.

![IMG_0147](https://user-images.githubusercontent.com/5506941/133942030-03382ac8-3b02-4dd1-b2df-445c7b036f4a.jpg)

**Comment by dirivero** [comment]
Hi @turgaygncr,

That's part of RTL-enabled Grial versions, check here: https://grialkit.com/download?plan=rtl

On those versions that button comes along with the customized version you download. If you need an upgrade just send me an email to drivero [at] uxdivers.com
