### ISSUE TITLE
MAUI new Architecture Support 

### ISSUE THREAD

**Issue by sajirkhan** [UXDivers/Grial-UI-Kit-Support#804]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dirivero** [comment]
Grial 4 was released a few weeks ago and it has support for .NET MAUI besides still supporting Xamarin.Forms. You can read more here:
https://grialkit.com/blog/whats-new-in-grial-ui-kit-4
