### ISSUE TITLE
App bar gradient background issue on android device orientation change

### ISSUE THREAD

**Issue by bokurev** [UXDivers/Grial-UI-Kit-Support#806]
### Description
App bar gradient background is lost when android device orientation changes.

### Steps to Reproduce
1. Download Full Grial 3.2.82.0 solution
2. Restore NuGet packages
2. Build and run it. 

### Expected Behavior
App bar gradient background is expected to be intact when device orientation is changed.

### Actual Behavior
App bar gradient background is lost when device orientation changes.

### Basic Information
- Version with issue:  
Tried 3.2.82.0 and 3.2.85.0
- Affected Devices: 
Tried on Android 10 and 11 device - same issue.

### Screenshots
![image](https://user-images.githubusercontent.com/7703654/146384249-e2f1a942-9c31-486d-983b-c1b2ee859dd0.png)
![image](https://user-images.githubusercontent.com/7703654/146384329-a0a2f210-19c1-4552-9a55-d234b4b8944a.png)

**Comment by dirivero** [comment]
We published a fix for this, can update the UXDivers.Grial nuget to version 3.2.87?

**Comment by bokurev** [comment]
Updated to 3.2.87, seems to be fixed. Thank you!
