### ISSUE TITLE
UXDivers.Artina.Shared.Droid Still reference old Xamarin.Android.Support.V7.AppCompat package

### ISSUE THREAD

**Issue by omaarmostafa** [UXDivers/Grial-UI-Kit-Support#807]
Hello,
I have updated my xamarin application to XForms 5.0.0.229 
then removed all old android support packages, and installed new androidx support packages.
after that, I upgraded my UXDivers NuGet packages to the latest version 2.7.14
but now I cant build my project because and still get the attached error !!!
and I can`t install old android support packages because it will get more conflicts.

![image](https://user-images.githubusercontent.com/36670486/148624802-98950a9e-29f3-456d-b958-535efa12e262.png)

Any help please because my app is not working anymore.

**Comment by dirivero** [comment]
I'm afraid Grial version 2 does not support AndroidX since Grial 3, its successor, has been released 3 years ago.

We can give some help if you plan to upgrade, feel free to contact me at drivero at uxdivers.com
