### ISSUE TITLE
NuGet: 401 Unauthorized

### ISSUE THREAD

**Issue by pauldupuyjr** [UXDivers/Grial-UI-Kit-Support#810]
I'm unable to connect to the private NuGet server in Visual Studio 2019 on Windows. I've followed the directions at https://docs.grialkit.com/working-locally.html#working-locally-setting-up-uxdivers-nuget-source and entered credentials with "Enable Nuget Dedicated User" checked. I can access the Nuget URL directly in a browser using the configured credentials. I'm unable to verify the credential values were entered correctly or change them to admin credentials as I can't find where/how to make changes to the cached values and there's no new prompt when re-creating the source in VS. Here's the error message:

[Grial] The V2 feed at 'http://nuget.uxdivers.com/grial/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='netstandard2.0%7Cxamarinios10%7Cmonoandroid10.0'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0' returned an unexpected status code '401 Unauthorized'.

**Comment by dirivero** [comment]
To clear or change the credentials you can go to Control Panel\User Accounts\Credential Manager 
You should see nuget.uxdivers.com there.

**Comment by pauldupuyjr** [comment]
Thanks @dirivero -- I was able to see the credential values and that there was an error. I deleted the entry from the Windows Vault. Deleted and re-added the package source in Visual Studio. Restarted the OS. ;-) I'm not prompted in Visual Studio for new credential values, still getting the "401 Unauthorized" error. Is there a cache that VS is using?

**Comment by dirivero** [comment]
You can try opening the VS package manager console and run this:

```
nuget sources update -Name <uxdivers_source_name> -Source http://nuget.uxdivers.com/grial -UserName <user> -Password <password>
```

**Comment by pauldupuyjr** [comment]
Created a package entry again in VS ("update" without existing source results in "unable to find" error), ran this command with the response "Package source "Grial" was successfully updated":

nuget sources update -StorePasswordInClearText -Verbosity detailed -Name Grial -Source http://nuget.uxdivers.com/grial -UserName <user> -Password <password>

Verified the credential values are correct in "%AppData%\NuGet\NuGet.Config".

Still getting the same 401 error when browsing with that package source.

Restarted VS and now I see the packages -- Huzzah! 

Thanks for your help @dirivero !
