### ISSUE TITLE
Themes warning Grial: Newtonsoft.Json, Version=11.0.0.0

### ISSUE THREAD

**Issue by pauldupuyjr** [UXDivers/Grial-UI-Kit-Support#811]
The following warning occurs for each project in a Grial template with a few pages:

`MSBUILD : Themes warning Grial: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.`

Version 11.0.0 is not available through NuGet; I've got the latest 13.0.1 installed and would be fine installing the indicated version if I could.

The projects compile and the app runs in Gorilla.

**Comment by dirivero** [comment]
What version of UXDivers.Grial nuget package are you using?

**Comment by pauldupuyjr** [comment]
UXDivers.Grial nuget version 3.2.87.

**Comment by dirivero** [comment]
Can you try with version 3.2.88?
