### ISSUE TITLE
Fontawesome v6

### ISSUE THREAD

**Issue by askindus** [UXDivers/Grial-UI-Kit-Support#812]
**Is your feature request related to a problem? Please describe.**
I saw that you support Fontawesome

**Describe the solution you'd like**
Is it possible to include also Fontawesome v6?

**Comment by dirivero** [comment]
Hi @askindus,
Thanks for the idea! We will include Fontawesome v6 once it goes out of beta.
I've already sent you en email with instructions on how to include it yourself.
