### ISSUE TITLE
Combining Grial Features

### ISSUE THREAD

**Issue by Dehmee** [UXDivers/Grial-UI-Kit-Support#813]
Hello, I'm trying to use Tabbed Page(top bar tabs) along with the Tab Control Custom Sample page (icons at the bottom) on my app but I get an error that I cannot set content more than once. I have the same problem using a Card/ Card View on my Tab Control Custom Sample page. Is there not a way to use multiple features of Grial on the same page? 

What I am trying to achieve is the Main Page/ Dashboard look like the Tab Control Custom Sample Page then one of the tabs, it has a top bar tab page with 2 or 3 pages. Is there a way to achieve this with Grial?

**Comment by dirivero** [comment]
In general there are no constraints on how to combine Grial features. 

That being said, the Tab your are trying to use is the TabControl from Grial. That control supports views as tab content, not pages:
https://docs.grialkit.com/tab-control.html

If you need pages with navigation bar and full navigation you have to use the TabbedPage that comes with Xamarin that, even though is less customizable, supports that structure.

**Comment by Dehmee** [comment]
Okay, thank you.
