### ISSUE TITLE
Problem styling Entry and Button

### ISSUE THREAD

**Issue by Droid91** [UXDivers/Grial-UI-Kit-Support#82]
Hi all,
i've included Grial UI Kit in my existing project! I added all DLL in PCL, Doid and iOS project but i've a problem with App.xaml !! Property like color works fine but property like border radius on button or border corner radius on Entry are completely ignored!! And more, Entry ignore AccentColor property and use the default "purple" color (i've modified that). What can i do for fix this problem? (On Android, i've don't test iOS yet)

**Comment by jpbrocca** [comment]
Hi,
I assume your comment about button is on Android. Please check the provided sample with Grial.
You should use artina:Button to have full control of the button styling on android.

I am not sure what you mean with your comments about Entry, but I guess you need artina:Entry.
Are you trying to achieve something from the sample but cannot make it?
About AccentColor did you follow the steps in the docs to compile Colores.tt file?
Regards,
JP

**Comment by Droid91** [comment]
Yes i follow all step, AccentColor work fine!! I've copy LoginPage.xaml from sample and paste it in my project. But the problem is that in my project the buttons are not rounded and entry aren't too!

**Comment by jpbrocca** [comment]
Do you see the Entry with rounded corners on Android on our sample?
That should not be displayed on Android...which devices are you trying with?

If you see differences with our sample in your project I guess there is something missing in your project.
Is hard to give you more guidance without knowing more details about or seeing your project.

**Comment by Droid91** [comment]
No i don't see Entry with rounded corners on Android on sample project but if i set BorderStyle=RoundRect property to an Entry, in my project this property is ignored!! Same result if i change value of BorderRadius property of a button! What is possible missing?? I've import shared dll in pcl project, android project and iOS project!

**Comment by jpbrocca** [comment]
Entry control does not provide rounded corner property to be styled.
Our sample shows what you can build, that means no rounded corners. 

You can implement that using custom renderers.

Best,
JP

**Comment by Droid91** [comment]
Ok thanks for the tip!! But for button?! Why if i set different value for border radius new value is ignored?

**Comment by jpbrocca** [comment]
Are you using the artina:Button or just Button?
Look at the sample on Theme > Custom renderers.
You will find the artina Button there.
Copy that to your page. That should work.
If you want ti change the corner radius you will need to find the style on app.xaml then change it.

**Comment by jpbrocca** [comment]
Keep in mind that the property on the artina:Button should be the one used on the style (in case you would like to set it directly on the control).

About custom renderers for Entry:
http://forums.xamarin.com/discussion/comment/179419/#Comment_179419

Please close the issue after you make your changes.

Regards,
JP

**Comment by Droid91** [comment]
As I stated before, I copied the Login Page.xaml from sample project to my project! In the sample buttons have rounded corner but not in my project!!
This is my (equals to sample) button:

> <ContentPage 
> 	xmlns="http://xamarin.com/schemas/2014/forms"
> 	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
> 	Title="Login"
> 	x:Class="InnHandy.Views.Login.LoginPage"
> 	xmlns:artina="clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared"
> 	xmlns:commonViews="clr-namespace:InnHandy.Views.Common;assembly=InnHandy">
> ...
> <artina:Button Style="{DynamicResource PrimaryActionButtonStyle}" Text="Login" />

And this is my App.xaml:

> <Style x:Key="PrimaryActionButtonStyle" TargetType="Button" BasedOn="{StaticResource RoundedButtonStyle}">
>         <Setter Property="BackgroundColor" Value="{StaticResource AccentColor}"/>
>         <Setter Property="TextColor" Value="{StaticResource LabelButtonColor}"/>
>         <Setter Property="HeightRequest" Value="{StaticResource BaseButtonHeight}"/>
>       </Style>
> 
>  <Style x:Key="RoundedButtonStyle" TargetType="Button">
>         <Setter Property="FontSize" Value="{StaticResource BaseFontSize}" />
>         <Setter Property="BorderRadius" Value="20" />
>         <Setter Property="HeightRequest" Value="{StaticResource BaseButtonHeight}"/>
>       </Style>

But even with these parameters the button is rectangular!!!!

**Comment by Droid91** [comment]
Can i send you my solution via email?

**Comment by jpbrocca** [comment]
Send it to jpbrocca@uxdivers.com

**Comment by Droid91** [comment]
I've sent you an email.
Thanks for your help

**Comment by tellamon** [comment]
@Droid91, Have you solved the issue?

I'm facing the same problem.The button is shown in rectangular shape even if I've used <artina:Button>

**Comment by tellamon** [comment]
I've resolved my problem with following codes in AssemblyInfo.cs of andoird project
`
// Custom renderer definition.

[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Artina.Shared.ArtinaEntryRenderer))]
[assembly: ExportRenderer(typeof(Editor), typeof(UXDivers.Artina.Shared.ArtinaEditorRenderer))]
[assembly: ExportRenderer(typeof(Label), typeof(UXDivers.Artina.Grial.CustomFontLabelRenderer))]
[assembly: ExportRenderer(typeof(Switch), typeof(UXDivers.Artina.Shared.ArtinaSwitchRenderer))]
[assembly: ExportRenderer(typeof(ActivityIndicator), typeof(UXDivers.Artina.Shared.ArtinaActivityIndicatorRenderer))]
[assembly: ExportRenderer(typeof(ProgressBar), typeof(UXDivers.Artina.Shared.ArtinaProgressBarRenderer))]
[assembly: ExportRenderer(typeof(Slider), typeof(UXDivers.Artina.Shared.ArtinaSliderRenderer))]
[assembly: ExportRenderer(typeof(SwitchCell), typeof(UXDivers.Artina.Shared.ArtinaSwitchCellRenderer))]
[assembly: ExportRenderer(typeof(TextCell), typeof(UXDivers.Artina.Shared.ArtinaTextCellRenderer))]
[assembly: ExportRenderer(typeof(ImageCell), typeof(UXDivers.Artina.Shared.ArtinaImageCellRenderer))]
[assembly: ExportRenderer(typeof(ViewCell), typeof(UXDivers.Artina.Shared.ArtinaViewCellRenderer))]
[assembly: ExportRenderer(typeof(EntryCell), typeof(UXDivers.Artina.Shared.ArtinaEntryCellRenderer))]
[assembly: ExportRenderer(typeof(SearchBar), typeof(UXDivers.Artina.Shared.ArtinaSearchBarRenderer))]
[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.Button), typeof(UXDivers.Artina.Shared.ArtinaButtonRenderer))]
`
