### ISSUE TITLE
Parallax Header Article in VS not matching iOS demo

### ISSUE THREAD

**Issue by DimPD** [UXDivers/Grial-UI-Kit-Support#822]
### Description
Running a build from the supplied project file has a mismatched animation on the "Parallax Header Article".

### Steps to Reproduce
1. Run latest Grial demo on iOS and open "Parallax Header Article" page.
2. Swipe up and down to view Parallax Effect.
3. Run latest Grial package supplied from the admin site.
3. Swipe up and down in the emulator or mobile build and view Parallax effect.

## Expected Behavior
The expectation is that the build would match the parallax effect on iOS.

### Actual Behavior
The behaviour on the VS version does not match the demo on iOS. The animation on iOS is a better representation of the effect that is wanted. 

### Basic Information

- Version with issue: 4.0.56.0 
- Target Frameworks:
  - iOS:  4.0.26

### Screenshots
iOS Demo:
![IMG_3467](https://user-images.githubusercontent.com/112465150/187587426-e8c03ed3-e848-49dd-bb6d-56921a567b9f.PNG)

VS Build:
![Simulator Screen Shot - iPhone 13 Pro - 2022-08-31 at 13 40 22](https://user-images.githubusercontent.com/112465150/187587611-a8e0281f-159d-4597-ab3a-d1e241066b17.png)

**Comment by dirivero** [comment]
I think the difference is due to the Navigation Bar that in .NET MAUI is not transparent. We are working on migrating that behavior and will be available soon. You can follow the feature comparison between XF and MAUI [here](https://grialkit.com/compare-xf-maui).

**Comment by dirivero** [comment]
Transparent navbar is part of Grial for MAUI now. Take a look at version 4.0.84:
https://grialkit.com/blog/grial-ui-kit-4-for-net-maui-february-update
