### ISSUE TITLE
Dependency injection problems in .net maui grial ui kit

### ISSUE THREAD

**Issue by marketdevsoft** [UXDivers/Grial-UI-Kit-Support#823]
I have throubles when try to using dependency injection with .net maui grial ui kit 4

### Description

When i try to use it in model constructor (for example, IConnection), it doesn't inject the instance of object!!!

### Steps to Reproduce

1.  Register maui api, for example: builder.Services.AddSingleton<IConnectivity>(Connectivity.Current);
2.  In MyViewModel try to inject the object:  public MyViewModel(IConnectivity connectivity) 
3.  The connectivity object is null!

### Expected Behavior

This is very important feautures, and we need it for our powerfull app!

### Actual Behavior

Why the object can't be injected into mvvm constructor? 
In our other .net maui app without Greal i can do it in easy way and work very well!

### Basic Information

- Version with issue:  Grial UI Kit 4
- Last known good version: 
- IDE: 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by dirivero** [comment]
Grial don't do anything against .NET MAUI DI mechanism. If should work as in any other App. 

Have you followed the steps here?
https://learn.microsoft.com/en-us/dotnet/architecture/maui/dependency-injection

**Comment by marketdevsoft** [comment]
Yes it work correctly !

Best regards

Raffaele
