### ISSUE TITLE
.NET MAUI MaterialCommunityIconsFont Example

### ISSUE THREAD

**Issue by marketdevsoft** [UXDivers/Grial-UI-Kit-Support#824]
Hi, 

is possible insert a MaterialCommunityIconsFont icon in a .net maui xaml page ? For example MaterialCommunityIconsFont.Numeric1BoxOutline 

Can someone post a simple example?

Best Regards

Raffaele

**Comment by marketdevsoft** [comment]
And if possible some other example for use  Line Awesome Icons in xaml .... thanks!

**Comment by dirivero** [comment]
You need to declare the font in the MauiProgram next to the other font declarations:

`fonts.AddFont("materialdesignicons-webfont.ttf", "MaterialDesignIcons");`

And use it like this:

```
<Label
  FontFamily-"MaterialDesignIcons"
  Text="{ x: Static local:MaterialCommunityIconsFont.AccessPoint }" />
```
