### ISSUE TITLE
iOS is not reading my production license

### ISSUE THREAD

**Issue by EdzonBolivar11** [UXDivers/Grial-UI-Kit-Support#826]
Yesterday I uploaded my app in testflight, after that I changed to production mode my license. Then when I replaced it on my solution, all of sudden stopped to work only in iOS, in Android is working good. I already check names, bundle name, app name, identifier, etc. but is still not working.

What can I do?

This is the error that I have in AppDelegate.cs file

<img width="1242" alt="Screen Shot 2022-10-27 at 17 47 30" src="https://user-images.githubusercontent.com/51150676/198412125-e212ed00-8421-484e-82f9-768bfff4d747.png">

My structure of the project

<img width="283" alt="Screen Shot 2022-10-27 at 17 47 37" src="https://user-images.githubusercontent.com/51150676/198412142-52db376d-20fd-469e-b7fd-3a661939f83a.png">

The info.plist file
<img width="566" alt="Screen Shot 2022-10-27 at 17 47 55" src="https://user-images.githubusercontent.com/51150676/198412178-babd0385-5a4b-4951-ad39-8ddf4ad36663.png">

These are the info that grial says that I need to have

![Screen Shot 2022-10-27 at 17 48 06](https://user-images.githubusercontent.com/51150676/198412217-f1ad06c5-edfc-4aed-8673-02324cae0a49.png)

Thank you so much

**Comment by dirivero** [comment]
Can you double-check that the build action of the license file is set to EmbeddedResource?

**Comment by EdzonBolivar11** [comment]
thank you, that was the problem
