### ISSUE TITLE
Mentioned Supported Platforms are not accurate.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [UXDivers/Grial-UI-Kit-Support#829]
Supported Platforms mentioned on https://docs.grialkit.com/overview#supported-platforms
are different from mentioned on https://github.com/UXDivers/Grial-UI-Kit-Support/blob/master/Details.md#supported-platforms

Please help me to understand the difference.

**Comment by dirivero** [comment]
The docs in github were old. The correct platforms and information are in the first of your links. Thanks!
