### ISSUE TITLE
Android Alert has two titles

### ISSUE THREAD

**Issue by NVentimiglia** [UXDivers/Grial-UI-Kit-Support#83]
![image](https://cloud.githubusercontent.com/assets/125889/18419708/98153a66-7815-11e6-995e-b8c6e2dee293.png)

My Window.Alert dialogs have two titles on android. I assume its an android xml setting. how can I fix this.

**Comment by jpbrocca** [comment]
Hi @NVentimiglia, how are you?
Please refer to this link:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/75

Best,
JP

**Comment by NVentimiglia** [comment]
thanks, thats it.
