### ISSUE TITLE
OrientationLock

### ISSUE THREAD

**Issue by viamatt** [UXDivers/Grial-UI-Kit-Support#834]
Is there any documentation on how to lock the orientation of a Grial based app to portrait, I see the usual ios method GetSupportedInterfaceOrientations is wired up to a Grial method so assume somewhere I can set the apps allowed orientation mask?

**Comment by dirivero** [comment]
Hi! You can do this:
```
DependencyService.Get<IOrientationLockService>().LockOrientation(OrientationLock.Portrait);
```
