### ISSUE TITLE
Error NU1101: Unable to find package UXDivers.Grial. No packages exist with this id in source

### ISSUE THREAD

**Issue by turgaygncr** [UXDivers/Grial-UI-Kit-Support#837]
Hello,

I wasn't building my app about 6 of them. Now when I try to compile I get this error. I get the same error when I download the KickOff project in Grial Admin.

/Users/turgaygencer/Downloads/Grial/Gencerp/Gencerp.csproj: Error NU1101: Unable to find package UXDivers.Grial. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org (NU1101) (Gencerp)

Colud you help me please ?

Licence: Grial 3 Pro 
OS: macOS Ventura
IDE: Visual Studio for Mac (17.4.5)

![Ekran Resmi 2023-02-22 14 47 20](https://user-images.githubusercontent.com/5506941/220611493-a4b74e48-3e31-439b-b6a0-ff3647004092.png)

**Comment by chinochuy** [comment]
Same issue here

**Comment by dirivero** [comment]
Hi @chinochuy,
Are you in mac? Do you have multiple Visual Studios installed? A local nuget.config file maybe? Did it work previously? 
You can contact me at drivero [at] uxdives.com and I will help you diagnose the issue.
