### ISSUE TITLE
Grial UI Kit 3 Floating Menu Control

### ISSUE THREAD

**Issue by raymond-dillon** [UXDivers/Grial-UI-Kit-Support#838]
**Is your feature request related to a problem? Please describe.**

Menu control on Grial UI Kit 3

**Describe the solution you'd like**

Is there a floating menu control on Grial UI Kit 3 similar to what is advertised on UI Kit 4?

**Comment by dirivero** [comment]
Hi Raymond,
I'm afraid we added the floating menu in Grial 4 so it's not available in Grial 3.
