### ISSUE TITLE
Binding warnings with RepeaterItem

### ISSUE THREAD

**Issue by ritesh-burn** [UXDivers/Grial-UI-Kit-Support#839]
Warnings are logged when binding to a Repeater Item Template.

### Description
Warnings are logged when binding to a Repeater Item Template.

### Steps to Reproduce
I'm trying to use Grial Repeater to show dates in a horizontal list for selection

Here's the XAML:
```
        <grial:Repeater ItemsSource="{Binding DateRange}"
                        ScrollBarVisibility="Never"
                        Spacing="0"
                        Padding="0"
                        ScrollPadding="10"
                        HeightRequest="100"
                        Grid.Row="3"
                        Margin="0,0,0,10"
                        SelectionMode="Single"
                        InitialSelection="First"
                        SelectedItem="{Binding CurrentDate, Mode=TwoWay}"
                        ItemSelectedCommand="{Binding HandleDateSelectedCommand}"
                        AutomationId="DateRangeRepeater">
            <grial:Repeater.ItemTemplate>
                <DataTemplate x:DataType="models:DateHolder">
                    <VerticalStackLayout Margin="0,10" WidthRequest="55">
                        <Label Text="{Binding Date, StringFormat='{0:ddd}'}"
                               Style="{StaticResource InvertedLabel}"
                               TextTransform="Uppercase"
                               Margin="0,3,0,0"
                               FontSize="12"
                               HorizontalTextAlignment="Center" />
                        <Label Text="{Binding Date, StringFormat='{0:dd}'}"
                               WidthRequest="30"
                               HeightRequest="30"
                               Style="{StaticResource InvertedLabel}"
                               FontFamily="OpenSansSemibold"
                               FontSize="15"
                               Margin="0,14,0,0"
                               HorizontalTextAlignment="Center"
                               FontAttributes="Bold" />
                    </VerticalStackLayout>
                </DataTemplate>
            </grial:Repeater.ItemTemplate>
            <grial:Repeater.SelectedItemTemplate>
                <DataTemplate x:DataType="models:DateHolder">
                    
                </DataTemplate>
            </grial:Repeater.SelectedItemTemplate>
        </grial:Repeater>
```
The ItemsSource is bound to an `ObservableRangeCollection<DateHolder>`
DateHolder is defined as:

```
public class DateHolder
{
    public DateHolder(DateTime date)
    {
        Date = date;
    }

    public DateTime Date { get; set; }
}
```

Everything works fine when the screen is loaded, except a whole bunch of warnings are logged:

`Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Date' property not found on 'UXDivers.Grial.Repeater+RepeaterItem', target property: 'Microsoft.Maui.Controls.Label.Text'`

Is there anything that I'm doing wrong or is there something wrong with the Repeater control causing this?

BTW the only reason to use a DateHolder here is because the `SelectedItem` wasn't working if I use a `ObservableRangeCollection<Date>` directly. The SelectedItemTemplate was never applied if I changed the `CurrentDate` in the ViewModel.

### Expected Behavior
No warnings should be logged.

### Actual Behavior
Warnings logged for each item in the bound list:
```
Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'Date' property not found on 'UXDivers.Grial.Repeater+RepeaterItem', target property: 'Microsoft.Maui.Controls.Label.Text'
```

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?): .NET Maui
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: 13 (API Level 33)
- Nuget Packages: UXDivers.GrialMaui v4.0.84
- Affected Devices: Google Pixel 3XL, iPhone 14 Pro

### Screenshots
n/a

**Comment by dirivero** [comment]
Hi! 
We couldn't see the warnings you mentioned, but we fixed the need for the DataHolder in version 4.0.88.0. Can you try with that one?
