### ISSUE TITLE
Walkthrough close button (label) not working on iOS

### ISSUE THREAD

**Issue by DotControlNB** [UXDivers/Grial-UI-Kit-Support#84]
Hi there,

I thought I made a mistake with maybe missing piece of code, but it turns out that in the sample the  walkthrough page gesturerecognizer is also not working on this 'close' label. (I debugged it with breakpoints in VS2015).

It works on Android though, any idea what is going wrong here?

**Comment by jpbrocca** [comment]
Hi @DotControlNB,

try replacing your "WalkthroughStepItemTemplate.xaml" file with this:

```
<!--LAYOUT-->
		<Grid Padding="20" 
			AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
			AbsoluteLayout.LayoutFlags="All">

			<Grid.RowDefinitions>
				<RowDefinition Height="40" />
				<RowDefinition Height="*" />
				<RowDefinition Height="80" />
			</Grid.RowDefinitions>
			
			<!--CLOSE ICON-->
			<Label 
				Grid.Row="0"
				FontSize="30"
				Text="&#xf00d;"
				HorizontalOptions="End"
				VerticalOptions="Start"
				TextColor="White"
				HeightRequest="30"
				WidthRequest="30"
				Style="{StaticResource FontIcon}">
				<Label.GestureRecognizers>
					<TapGestureRecognizer Tapped="OnCloseButtonClicked" />
				</Label.GestureRecognizers>
			</Label>
```

Just in case here is the diff:

![image](https://cloud.githubusercontent.com/assets/15996999/18455838/d73581a2-7922-11e6-8b3b-7fe75e7fdb9d.png)

Best,
JP

**Comment by DotControlNB** [comment]
Unfortunately this results in a wrong layout, the next button appears at the top of the screen. I removed the button temporarily, but that doesn't make the close button work either. (Android still works this way though)

**Comment by jpbrocca** [comment]
Hi @DotControlNB,
I think I missed some part of the diff, sorry about that.

Can you send me an email with your name and your oder number so I can send you the merged file?

Please write to:
jpbrocca@uxdivers.com

Regards and thanks,
JP

**Comment by DotControlNB** [comment]
Your emailed merged file works fine on iOS and Android :)

I did some comparison myself and had to fix the code behind a bit. So the problem had to do with the labels used in the animation?

**Comment by jpbrocca** [comment]
Glad to gear that :)
If you want you can send me your code behind so I can take a look.

Please dont't forget to close this issue.

Best
JP
