### ISSUE TITLE
 Unable to load the service index for source https://nuget.uxdivers.com/grial

### ISSUE THREAD

**Issue by AnaGarciaP** [UXDivers/Grial-UI-Kit-Support#841]
### Description
I'am trying to use the solution in another instance of Visual Studio

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?): .NET Maui
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android 13 API 33
- Nuget Packages: https://nuget.uxdivers.com/grial
- Affected Devices:

**Comment by dirivero** [comment]
Not sure what was happening, but the source is working fine. Please reopen if you find any trouble.
