### ISSUE TITLE
Floating menu not responding after appearing when build with .Net8-RC1 and -RC2

### ISSUE THREAD

**Issue by tentom** [UXDivers/Grial-UI-Kit-Support#845]
### Description
When built targeting net8.0-ios using the .net8-RC1 or .net8-RC2 the floating menu appears as normal but then nothing is responsive. Menu items appear to not trigger the bound command, and the menu will not close when the close item is taped. Tapping outside of the menu does not help so the app will get stuck with an open menu. 

### Steps to Reproduce
1. Download Explorer List page from the Grial admin page
2. Change target to net8.0-ios
3. Comment out <OnPlatform> statement in the Theme files (due to regression in net8).
4. Add Microsoft.Maui.Controls package as instructed by the compilation warning.
5. Run on device and tap the (+) item of the floating menu.
6. Try to tap anywhere to get response.

### Expected Behavior
Menu opens, closes and triggers the actions from the menu items when tapped

### Actual Behaviour
Menu opens but then the ui becomes unresponsive.

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?): .NET MAUI 
- IDE: Visual Studio for Mac 17.6.5
- Platform Target Frameworks: net8.0-ios
  - iOS: Xamarin.iOS Version: 16.4.0.18 
- Nuget Packages: Default + Microsoft.Maui.Controls
- Affected Devices: iPhone 6s (iOS 15.7.9) &  iPad 5th generation (iPad os 16.7) probably more devices

**Comment by samhouts** [comment]
If this is new to NET 8, then it is probably not 16622. 

If you're not using embedding, it is probably not 17948.

If you are using static methods to bind to your commands, it is probably https://github.com/dotnet/maui/issues/18165.

Please confirm. Thanks!

**Comment by Santiago5050** [comment]
@tentom 
Hi, we found a fix for the issue. Please send an email to drivero [at] uxdivers.com, and he will send you an internal version of the nuget with the fix.  

@samhouts   
Hi, thanks for the comments! The problem was that we use an internal visual tree that doesn’t add the views to the maui visual tree, so without the parent set, the gestures didn’t work in the views. (Because the new version of the gesture recognizers requires that the views have the Window property set).

**Comment by PureWeen** [comment]
@Santiago5050 on your updated build to add the views to the maui visual tree, are you using "AddLogicalChild" ? If you use Add/RemoveLogicalChild that should wire everything up and more for you. This will also make everything work with Hot Reload and Live Visual Tree

**Comment by tentom** [comment]
Hi, forgot to reply to this issue, the latest release fixes this issue so I'm closing it. Feel free to reopen it if you guys use it internally to track some sort of progress that I am not aware of :)
