### ISSUE TITLE
grial:Drawer control draw not showing as full width on iOS

### ISSUE THREAD

**Issue by viamatt** [UXDivers/Grial-UI-Kit-Support#846]
### Description
We are using Draw control on a number of screens in a Maui app and often on iOS the draw control is initially rendered only taking up 30% or so of the screen width.  often opening the drawer fully will make the drawer spring back to full width and can then be used.

This seems to impact some pages with drawers on them, but not all.

Previously used this control on Xamarin and did not observe this issue.

This has been observed with IOS 16 and 17 on a number of devices, but not on Android

### Steps to Reproduce
XAML can be shared directly if needed, please contact.

### Expected Behavior
Drawer should render at full width.

### Actual Behavior
Darwer renders at 
### Basic Information

- Version with issue .NET Maui
- IDE: VS 17.17.5
- Platform Target Frameworks: 
  - iOS:  14.2
- Nuget Packages: GrialMaui 4.0.92
- Affected Devices:

### Screenshots
Video showing UI can be found here: https://1drv.ms/v/s!AhQxB7s8zoHPje4UqZ264x-21ll4Tg?e=9Lw91T

**Comment by dirivero** [comment]
Hi @viamatt,
Can you send me the XAML to drivero [at] uxdivers.com so we can review it?

**Comment by viamatt** [comment]
Done

**Comment by dirivero** [comment]
The layout issue was caused by this issue: 
https://github.com/dotnet/maui/issues/18160

Adding empty `<Rectangles />` as workaround fixed it.
