### ISSUE TITLE
Recurso não está visível como no app de venda ou Exemplo de Venda

### ISSUE THREAD

**Issue by gabrielalfa** [UXDivers/Grial-UI-Kit-Support#847]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Captura de tela 2023-10-20 083117](https://github.com/UXDivers/Grial-UI-Kit-Support/assets/8473925/7d73e07f-d314-46a1-8bb1-9aada0cf6de7)

**Comment by gabrielalfa** [comment]
O seach personalizado descrito no app de exemplo de venda não consta nas pages para download.
Isso no Brasil se chama propaganda enganosa 

Na home page do app de exemplo como mostrado na imagem acima, ou seja, no frame central da imagem tem um search que ao clicar ele mostra uma page toda personalizada que foi o motivo de me fazer comprar o Grial, porém ao baixar o feature completo ele não aparece mais e isso me deixou me desagradado com a compra. 
Estou me sentindo lesado com isso


The personalized search described in the sales example app is not included in the download pages.
In Brazil, this is called false advertising.

On the home page of the example app as shown in the image above, that is, in the central frame of the image there is a search that, when clicked, shows a completely personalized page, which was the reason for making me buy Grial, but when downloading the full feature It no longer appears and that made me unhappy with the purchase.

I feel hurt by this

**Comment by dirivero** [comment]
Hi @gabrielalfa,

I'm sorry that you had this experience with Grial. The full list of available pages is both described in the [download page](https://grialkit.com/download) and the list of every screenshot is available in the admin portal available before purchasing.

That being said, I understand the confusion and that's why I will offer a full refund if you want to. Please contact me: drivero at uxdivers.com

**Comment by gabrielalfa** [comment]
Obrigado pelo seu retorno, mas eu não quero o dinheiro devolta, e sim a pagina de exemplo com da home do app de venda que vcs colocaram como exemplo de venda. Voce compreende do que estou falando?

Thank you for your feedback, but I don't want the money back, but rather the example page with the sales app's home page that you provided as a sales example. Do you understand what I'm talking about?

Don't get me wrong, perhaps I exaggerated in the initial description and I am willing to withdraw what I said above, so as not to cause problems with your clients.

Different from what I described, we are very happy to have found your company to help us and we are enjoying the good things you have to offer, but these points that I am describing here have to be answered

I apologize for any misunderstanding
