### ISSUE TITLE
Grial Studio Extension Not allowing me to add content

### ISSUE THREAD

**Issue by jstun** [UXDivers/Grial-UI-Kit-Support#850]
After creating a new .NET MAUI solution in VS 2022, I'm not able to add new content. I get an error that the content is locked.

### Steps to Reproduce
1. Create a new .NET MAUI project in VS 2022
2. After project is created, open the Grial Studio extension
3. Click Add Content button
4. 

### Expected Behavior
Expected content to be added to project

### Actual Behavior
Received an error that content is locked

### Basic Information

- Version with issue: .NET Maui
- IDE: VS 2022 17.9 Preview 1
- Platform Target Frameworks: .net8.0
  - iOS:  11.0
  - Android: 21.0
- Nuget Packages: Micorosoft.Maui.Controls
- Affected Devices: Windows 11

### Screenshots
![image](https://github.com/UXDivers/Grial-UI-Kit-Support/assets/21327045/6e3f38eb-ee5d-43b7-afed-277b52692cc8)

**Comment by dirivero** [comment]
Hi @jstun !
If you don't have a license, just filter the content form the "All Content" dropdown on top. You can select the "Basic Bundle" option to see the FREE stuff!

**Comment by jstun** [comment]
Thanks @dirivero, I filtered down to the Basic Bundle and was able to select a page. After clicking the save button I see the progress bar but it does not take me to the Changes Preview screen. And it does not add the pages to my solution. As I was watching the video, I wanted to make sure that you weren't running as Administrator. I see that you weren't.

I'll start from scratch and follow the video step by step. If it doesn't work after that I'll create a new ticket.

By the way, this is a great feature, thanks for providing this. This will really help a lot.

**Comment by jstun** [comment]
@dirivero, I noticed that you guys uploaded a new version of the extension. I was able to download and was able to get the pages added to my solution. But after creating another solution I ran into the same issue as before where the Changes Preview pages doesn't show.

Also, you might want to mention in future videos that this does not work for target frameworks Mac Catalysts and Windows. If they are included the compiler will throw all types of errors about the UXDivers namespace cannot be resolved.

**Comment by dirivero** [comment]
Are the changes empty? or the window is not opened at all?

You are right about mac and win, they are not supported right now.  

Thanks!

**Comment by jstun** [comment]
@dirivero, yes the window is not displayed. It just takes me back to the solution without including the changes.

**Comment by dirivero** [comment]
Can you try opening manually from Tools -> Changes Preview and try again?

**Comment by jstun** [comment]
Ok. Get back with you.

**Comment by jstun** [comment]
Ok. So here's what I did:
* I closed VS and reopened.
* Reopened an existing project that I created earlier
* Added the content pages and I was able to get the Changes Preview page to display.

Maybe there's a flag that is not reset if you create multiple project using the same VS instance.

**Comment by dirivero** [comment]
That scenario should work, it does at least in the environments that we tested. 
I suspect that the files are downloaded correctly but VS is not honoring the command of opening / selecting the "Changes Preview" tool widow. 

Where is the Changes Preview spatially located in your Visual Studio? It should default to the right vertical area.

Can you send the logs located in `C:\Users\<user_name>\AppData\Local\Grial\logs` to drivero [at] uxdivers.com ?

**Comment by jstun** [comment]
Yes. Changes Preview window is docked on the right side.

Ok. I'll get the logs to you.

**Comment by jstun** [comment]
Sent the log files over. Heading out soon. I'll check back later if you need anything else. Thanks for your help.
