### ISSUE TITLE
Dificuldades em Publicar o APP

### ISSUE THREAD

**Issue by gabrielalfa** [UXDivers/Grial-UI-Kit-Support#853]
### Description
I strictly followed all the rules in the documentation
https://docs.grialkit.com/grial_web_admin/license_setup#license-modes
The project works perfectly in development, but when publishing on Google Console the project closes without any warning
I sent you an invitation to test the app

### Steps to Reproduce

1. to access the app under test: https://play.google.com/store/apps/details?id=com.tornfy

### Basic Information

- Version with issue (.NET Maui):
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android:  
- Nuget Packages:
- API 33:

### Screenshots progrando que o app funciona em produção 

![Screenshot_20231204_092821](https://github.com/UXDivers/Grial-UI-Kit-Support/assets/8473925/e3344890-580f-44ec-ae91-0feb315d638f)

This is return of google play Pre_launch
The tests return this:

FATAL EXCEPTION: main
Process: com.tornfy, PID: 22349
java.lang.NoSuchFieldError: no "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" field "AES256_SIV" in class "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" or its superclasses

**Comment by gabrielalfa** [comment]
This is return of google play Pre_launch
The tests return this:

FATAL EXCEPTION: main
Process: com.tornfy, PID: 22349
java.lang.NoSuchFieldError: no "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" field "AES256_SIV" in class "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" or its superclasses



https://github.com/UXDivers/Grial-UI-Kit-Support/assets/8473925/7cd83f2e-a4d8-445e-a5f2-646f3d6ad2df

[logcat.txt](https://github.com/UXDivers/Grial-UI-Kit-Support/files/13559116/logcat.txt)

**Comment by dirivero** [comment]
Hi Gabriel,
I'm adding the link to the solution here for other people to found:
https://github.com/dotnet/maui/issues/13413#issuecomment-1456759398
