### ISSUE TITLE
Need Assistance with one of our Licenses (Optix Enroll)

### ISSUE THREAD

**Issue by madonnacampbell** [UXDivers/Grial-UI-Kit-Support#855]
Our client has decided to utilize a different web developer name for their app and therefore, we need to delete the current license and re-assign to another developer.  The app will still be called Optix Enroll.

Our team is having an issue with how to make this transfer / update with the GRIAL license used for Optix Enroll.  Please advise.

Thanking you in advance,

**Comment by dirivero** [comment]
Hi @madonnacampbell 
I've contacted you directly on your email.
Thanks!

**Comment by madonnacampbell** [comment]
Hi Diego,

Thank you very much for your response.  I've forwarded it on to our tech team, I will advise shortly.

Thanks again,


[cid:3e013bd1-4080-4aec-a539-69b9444a1200]

Madonna Campbell | Chief Operating Officer

simpliConnect

O:  647.284.8745                    W:  www.simpliconnect.ca<http://www.simpliconnect.ca/>
E:  ***@***.******@***.***>









________________________________
