### ISSUE TITLE
Access to Grial Nuget Feed Returns 401 Unauthorized

### ISSUE THREAD

**Issue by canperk** [UXDivers/Grial-UI-Kit-Support#856]
I am using a Mac Air M2 and trying to build my project. However, I cannot authenticate to Grials' nuget source. 
### Description
This the Nuget.Config file both in project and in global nuget config at ~/.nuget/Nuget/Nuget.config
`
<?xml version="1.0" encoding="utf-8"?>
     <configuration>
         <packageSources>
           <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
           <add key="Grial" value="https://nuget.uxdivers.com/grial" />
         </packageSources>
         <packageSourceCredentials>
            <Grial>
               <add key="Username" value="grialuser@mail.com" />
               <add key="ClearTextPassword" value="MyLovelyPassword" />
               <add key="ValidAuthenticationTypes" value="basic" />
             </Grial>
         </packageSourceCredentials>
     </configuration>
`

### Steps to Reproduce
1. Open Project Directory in Terminal with a Mac
2. Run dotnet restore --interactive
3. Restore failed

### Expected Behavior
Project Builds

### Actual Behavior
Restore failed with error: 
Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.GrialMaui'&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?): MAUI 
- IDE: VS Code and dotnet CLI
- Platform Target Frameworks: IOS, Android
  - iOS:  15.0
  - Android: 30
- Nuget Packages: Grial Packages
- Affected Devices:

**Comment by DarqueWarrior** [comment]
I am in the same boat. No matter what I do I get a 401. I wanted to try it out today for the first time and can't seem to get anything to work.

**Comment by dirivero** [comment]
To access the feed you need to have a paid license. Is that your case? 
The free content doesn't use nuget packages from there.
