### ISSUE TITLE
.Net MAUI project navigation bar stays the same name

### ISSUE THREAD

**Issue by Fatihpk** [UXDivers/Grial-UI-Kit-Support#859]
He there, when i download the .Net MAUI project with some selected pages there is something wrong with the navigation and the bar. 

**I am using Version 4**

When I select another page with the humburger icon the navigation bar does not change (also with another Title of that page). 

I think there is something wrong with the navigation. 

![screenshot1](https://github.com/UXDivers/Grial-UI-Kit-Support/assets/20399409/504aabd5-8b71-47e8-a97a-a15f958f44a2)

![screenshot2](https://github.com/UXDivers/Grial-UI-Kit-Support/assets/20399409/50ba8f25-b49e-499d-84a7-c28d161665ca)

**Comment by Santiago5050** [comment]
Hi @Fatihpk,

Thanks for reporting the issue. We've reproduced it and our team is actively working on a fix. 

We appreciate your patience.

Regards,
Santiago.

**Comment by viamatt** [comment]
Is there any update on this issue? It impacts both the title and toolbaritems and is blocking a release for us.

**Comment by Santiago5050** [comment]
Hi @viamatt,

We have published a new version of the Grial NuGet package with a fix for this issue. You can review this and more changes in our release notes (https://docs.grialkit.com/release_notes/maui#version-421100-nuget-update).

Best regards,
Santiago

**Comment by viamatt** [comment]
Thanks @Santiago5050, confirmed as working building under release build and current Maui version.

**Comment by Fatihpk** [comment]
Thank you the last update ([version-421100-nuget-update]) did the job
