### ISSUE TITLE
Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by kepbem** [UXDivers/Grial-UI-Kit-Support#86]
HI,

Has anyone got a version of maps and its dependencies working with the Grial, if so could you please give share you configuration?

I am running into all sorts of areas trying to marry up versions and that are generating errors stemming from the SDK version then resulting in errors with Nuget package installer itself.

Any help would be great.

Thanks in advance,

Paul McCauley

**Comment by jpbrocca** [comment]
Hi @kepbem,

Did you finally succeed with Tawfik's help?

If that is the case please close this issue.
Best,
JP
