### ISSUE TITLE
Can´t install Grial Studio in Visual Studio OSX (mac) (No forum for issues, but related to Grial UI Kit)

### ISSUE THREAD

**Issue by mexmarv** [UXDivers/Grial-UI-Kit-Support#860]
### Issue
Grial Studio new plugin for MS Visual Studio (not code) on MAC (OSX) can´t be installed with current .vsix extension download from your page. 

### Description
Downloads of the project in web admin  is now unavailable and sends us to use Grial Studio. Do not know if you can modify contents or plugin extension fo VS Studio Mac (you can install extensions if extension and .json package is correct I believe), but we can´t get this to run. All our programmers do use VStudio in MAC for .NET / .MAUI and .XAMARIN programming to no avail, so  would truly need a workaround to get this working.

### Steps to Reproduce

1.  On a Mac, using the VS Studio latest (17.6.9 build 415)
2.  Menus VS > Extensions > Install from file...
3.  Cant use .vsix extension, tried .zip neither, and then was able to UNZIP on directory of extensions and point to it, but correct catalog .json is not included

### Expected Behavior
Able to run from Tools > Grial Studio

### Actual Behavior
Can´t use extension on VS Mac, can´t download files from web admin either.

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?):
- IDE: MAUI and Xamarin.Forms
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Nuget Packages:
- Affected Devices:

**Comment by dirivero** [comment]
Hi @mexmarv,

Grial Studio is only available in VS Windows. If you have a license you can always configure and download Grial from admin.grialkit.com

We have no plans to support VS Mac since MS announced its retirement.
