### ISSUE TITLE
SelectableWrapPanel throws exception when try to select any item on iOS

### ISSUE THREAD

**Issue by smartestimatorapp** [UXDivers/Grial-UI-Kit-Support#867]
![35cef961-2635-479b-9346-875f0b40ef5a](https://github.com/user-attachments/assets/7bae09fd-7705-4b9d-bba1-40abcae27ebe)
[report-2516795330540009999-dd74d284-83e8-4c4d-842b-04d37e509a1a.txt](https://github.com/user-attachments/files/16501411/report-2516795330540009999-dd74d284-83e8-4c4d-842b-04d37e509a1a.txt)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?):
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Nuget Packages:
- Affected Devices:

**Comment by Santiago5050** [comment]
Hi @smartestimatorapp,

Thank you for reporting this issue. The crash you're experiencing with the SelectableWrapPanel inside a PopupPage is related to the Mopups library, as described in this [issue](https://github.com/LuckyDucko/Mopups/issues/97).

To prevent the app from crashing, please add the following workaround code to your MauiProgram.cs file when the app is being created:

```csharp
//Workaround for: https://github.com/LuckyDucko/Mopups/issues/97
#if IOS
    Mopups.Platforms.iOS.PopupPageHandler.Mapper.AppendToMapping("FixingMopupCrash", (handler, view) =>
    {
        (view as Page).Appearing += (s, e) =>
        {
            var eventName = "DescendantRemoved";
            var eventInfo = typeof(Element).GetEvent(eventName);
            var descendantRemovedEvent = typeof(Element).GetField(eventName, BindingFlags.Static | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (descendantRemovedEvent.GetValue(view) is not Delegate eventDelegate)
            {
                return;
            }

            foreach (var d in eventDelegate.GetInvocationList())
            {
                eventInfo.RemoveEventHandler(view, d);
            }
        };
    });
#endif
```
Let us know if you have any questions!

Best regards
