### ISSUE TITLE
Tasks Flow Related Screens in .Net MAUI

### ISSUE THREAD

**Issue by akashcms** [UXDivers/Grial-UI-Kit-Support#868]
**Is your feature request related to a problem? Please describe.**
I would like to use the 3 screens related to Tasks Flow in .Net MAUI project. Currently they are only available for Xamarin forms

**Describe the solution you'd like**
I would like to use the 3 screens related to Tasks Flow in .Net MAUI project.

**Describe alternatives you've considered**
Would be good time saver since I am considering similar functionality

**Additional context**

**Comment by akashcms** [comment]
The screens are named as Performance Dashboard/ Employee Performance Dashboard/ Employee Profile Dashboard

**Comment by dirivero** [comment]
Hi! The Task Flow support on .NET MAUI was released yesterday. Take a look here:
https://grialkit.com/blog/grial-ui-kit-datagrid-control-2024-4-update
