### ISSUE TITLE
License verification fails if Android Package Name and iOS Bundle Identifier are different in Maui

### ISSUE THREAD

**Issue by ninoue-lisa-system** [UXDivers/Grial-UI-Kit-Support#869]
### Description
I was making a Xamarin app using Grial UI Kit.
I am trying to migrate this app to MAUI and have downloaded the Grial UI Kit MAUI's KICKOFF SOLUTION.
However, when I run this solution on iOS, it says "License verification failed".

My app uses an underscore in its Android package name and a hyphen in its iOS bundle identifier.
So I set

```
<ApplicationId Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">xxx-xxx</ApplicationId>
```
in the csproj file, or set "xxx-xxx" to CFBundleIdentifier in Info.plist, but when I do that, I get the message "License varification failed".

If I use "xxx_xxx" as the iOS Bundle Identifier, the message is not displayed. 
However, since my app is already published on the App Store, I cannot change the iOS Bundle Identifier.

### Basic Information

- Version with issue (.NET Maui or Xamarin.Forms?):
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Nuget Packages:
- Affected Devices:

**Comment by dirivero** [comment]
This has been already resolved.
