### ISSUE TITLE
Using ProductsGridPage Layout - many items

### ISSUE THREAD

**Issue by rogeriorrodrigues** [UXDivers/Grial-UI-Kit-Support#87]
I used the layout but when you bind with something around 250 items he gave outofmemory. any solution to use the same layout in a listview?

<img width="1154" alt="captura de tela 2016-09-14 as 21 31 27" src="https://cloud.githubusercontent.com/assets/6625448/18534568/fcf443f0-7ac2-11e6-93fb-4e4eba9f1ae7.png">

**Comment by kepbem** [comment]
I ran into a similiar problem and I had to increase the heap size to 1Gb.

right click on your android project > properties > Android Options > Advanced Tab > Java Max Heap size

Hope that helps, visual studio is an absolute mine field!

**Comment by jpbrocca** [comment]
@rogeriorrodrigues,
Showing 250 items at once could be too much, specially for old android devices.
A few tips:
- try to somehow paginate data, showing a few items each time.
- you need to create smaller images by all means or you will run out of memory soon. Alternatively you could use the great FFImageLoading library.

Regards,
JP
