### ISSUE TITLE
Error running Grial 1.5 sample Error java.lang.UnsupportedClassVersionError:

### ISSUE THREAD

**Issue by kepbem** [UXDivers/Grial-UI-Kit-Support#88]
HI,
I am trying to launch the sample to app to cross reference NuGet versions with my own app that is causing havok with visual studio.
I get this error after cleaning, restart visual studio, rebuild solution, deploy
"Error	java.lang.UnsupportedClassVersionError: com/android/dx/command/Main  :  Unsupported major.minor version 52.0	Grial.Droid"	

Is it to do with the android SDK or  tools versions ?

Thanks,

Paul

**Comment by jpbrocca** [comment]
Hi Paul,
It seems this is a problem with tour installed Java version:

https://forums.xamarin.com/discussion/62664/error-java-lang-unsupportedclassversionerror-com-android-dx-command-main-createdatabasewithadonet

Regards,
JP
