### ISSUE TITLE
Tabs Swipe

### ISSUE THREAD

**Issue by Reinarte** [UXDivers/Grial-UI-Kit-Support#89]
Hello,

I am trying to implement the same swipe gesture on my tabbed pages as you did in the "tabs" example but I can't find how you did it in the code.

Could you please help me?

Best Regards

**Comment by jpbrocca** [comment]
Hi, 
I am not sure what you want to achieve, but our sample just uses default TabbedPage from Xamarin Forms. That means that we didn't add any swipe gesture, this is the default behaviour for tabs on Android.

Regards,
JP

**Comment by jpbrocca** [comment]
I am closing this issue since it seems it was some misunderstanding by the user.
@Reinarte in case you need help you can re open.
Thanks
JP
