### ISSUE TITLE
Problem using Grial in my own project.

### ISSUE THREAD

**Issue by denvercoder** [UXDivers/Grial-UI-Kit-Support#90]
I can run the sample project just fine but I created a new project and I've followed your setup guide word for word and I am having trouble getting it to build.

First Issue:

*Error on both of these lines*
"The name 'ExportedColors' does not exist in the current context"

public static UIColor AccentColor = ExportedColors.AccentColor.ToUIColor();
public static UIColor TextColor = ExportedColors.InverseTextColor.ToUIColor();

Second Issue:

/Users/dev/Projects/grialTest/Droid/obj/Debug/android/manifest/AndroidManifest.xml(0,0): Error APT0000: No resource found that matches the given name (at 'theme' with value '@style/AppTheme'). (APT0000) (grialTest.Droid)

Am I just supposed to copy the entire folders over and take out what I don't need? There should be clear cut instructions. 

Also, I'm on macOS Sierra with XCode 8 if that matters.

**Comment by jpbrocca** [comment]
I am closing this issue since I answered this user by email.

**Comment by motion-work** [comment]
Had the same problem... What's the solution for that?

**Comment by jpbrocca** [comment]
HI @motion-work,
this seems to happen with android packages conflicts.

Are you on Visual or Xamarin Studio?

Check if your Android Packages are OK.
Sometimes you need to manually remove them and add them manually...more info here:
https://developer.xamarin.com/guides/xamarin-forms/troubleshooting/

Let me know how it goes.

Best,
JP
