### ISSUE TITLE
Gorilla Player 

### ISSUE THREAD

**Issue by DarkAulius** [UXDivers/Grial-UI-Kit-Support#91]
with your sample in  Grial 1.5.0, Gorilla Player preview on smartphone the views are not displayed correctly

**Comment by jpbrocca** [comment]
Hi @DarkAulius,
in order to preview Grial and its custom renderers, etc. you need to embed the Gorilla SDK.

More info here:
https://github.com/UXDivers/Gorilla-Player-Support/wiki/Gorilla-SDK

Regards,
JP
