### ISSUE TITLE
PushModalAsync is redirecting to home page 

### ISSUE THREAD

**Issue by mostafamarji** [UXDivers/Grial-UI-Kit-Support#92]
Iam using this code to open a modal page Navigation.PushModalAsync(new NavigationPage(new WelcomePage())); ,and Iam using PushModalAsync () to close it but instead of previewing last page in the navigation stack its closing all the views and it opens home page .

**Comment by jpbrocca** [comment]
Hi @mostafamarji,
This seems not to be caused by Grial.
I suggest you take a look at this article which will help you to understand how navigation works on Xamarin:
http://blog.adamkemp.com/2014/09/navigation-in-xamarinforms_2.html

Best,
JP
