### ISSUE TITLE
Xml error in Colors.tt file in XF Android project.

### ISSUE THREAD

**Issue by noelfernandes** [UXDivers/Grial-UI-Kit-Support#95]
So I am using Grial UI Kit with my Xamarin Forms App. I am following the instructions [mentioned here](https://github.com/UXDivers/Grial-UI-Kit-Support/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files) for both iOS & Android. It works pretty well for iOS. For Android however it throws an error on Line 2 of the Colors.tt file.

The Colors.tt file has the below code:

	<#@ template language="C#" hostspecific="True" #>
	<#@ output extension=".xml" #>
	<#@ assembly name="System.Core" #>
	<#@ assembly name="System.Drawing" #>
	<#@ assembly name="System.Xml" #>
	<#@ import namespace="System.Linq" #>
	<#@ import namespace="System.Text" #>
	<#@ import namespace="System.Collections.Generic" #>
	<#@ import namespace="System.Xml" #>
	<#@ import namespace="System.Drawing" #>
	<#@ import namespace="System.Globalization" #>
	<#@ import namespace="System.Text.RegularExpressions" #>
	<#@ assembly name="System.Windows" #>
	<#@ import namespace="System.Windows" #>
	<# 
	string path = Host.ResolvePath("../../../PCLFolderName/App.xaml");
	XmlDocument doc = new XmlDocument();
	doc.Load(path);

	Dictionary<string, Color> knownColors = new Dictionary<string, Color> ();
	List<string> exports = new List<string> ();

	XmlNamespaceManager nsmgr = new XmlNamespaceManager(doc.NameTable);
	nsmgr.AddNamespace("artina", "clr-namespace:UXDivers.Artina.Shared;assembly=UXDivers.Artina.Shared");
	nsmgr.AddNamespace ("xamarin", "http://xamarin.com/schemas/2014/forms");

	XmlNode resources = doc.DocumentElement.SelectSingleNode("/xamarin:Application/xamarin:Application.Resources/xamarin:ResourceDictionary", nsmgr);

	if (resources != null) {
		foreach (XmlNode node in resources.ChildNodes) {
			if (node.NodeType == XmlNodeType.Comment) {
				var comment = node.InnerText.Trim (); 

				Match match = Regex.Match(comment, @"Export\s([A-Za-z0-9\-]+)$", RegexOptions.IgnoreCase);

				if (match.Success)
				{
					exports.Add (match.Groups[1].Value);
				}
			}
			else if (node.Name == "Color") {
				string colorName = null;

				foreach (XmlAttribute attribute in node.Attributes) {
					if (attribute.LocalName == "Key") {
						colorName = attribute.Value;
						var colorDefinition = node.InnerText.Trim ();
						Color color;

						if (colorDefinition.StartsWith ("#")) {
							if (colorDefinition.Length == 7) {
								colorDefinition = "FF" + colorDefinition;
							}

							int argb = Int32.Parse (colorDefinition.Replace ("#", ""), NumberStyles.HexNumber);
							color = Color.FromArgb (argb);
						} else {
							color = Color.FromName (colorDefinition);
							string colorString = string.Format("#FF{0:X2}{1:X2}{2:X2}",
							color.R, color.G, color.B);

							color = System.Drawing.ColorTranslator.FromHtml(colorString);
						}

						knownColors.Add (colorName, color);
					}
				}
			}
		}
	}               
	if (exports.Count > 0){
	#>
	<?xml version="1.0" encoding="utf-8" ?>
	<resources>
		
	<#
	  foreach(var name in exports){ 
		 Color color;

		 if (knownColors.TryGetValue(name, out color)){
	#>
		<color name="<#= name #>">#<#= color.A.ToString("X2") #><#= color.R.ToString("X2") #><#= color.G.ToString("X2") #><#= color.B.ToString("X2") #></color>
	<#
		 }
	  }
	#>
	</resources>
	<#
	}
	#>

The Colors.xml file has the following xml:

	<?xml version="1.0" encoding="utf-8" ?>
	<resources>
		
		<color name="AccentColor">#FFDA125F</color>
		<color name="InverseTextColor">#FFFFFFFF</color>
	</resources>

The error is thrown on line# 2: <#@ output extension=".xml" #>. The error message is:
**Error parsing XML: not well-formed (invalid token)**

Any solutions or comments are greatly appreciated.

Thanks. 
Noel

PS:
- Development is done using VS2015 + Xamarin VS + Windows 10 on a Mac.
- All SDK's have been updated.

**Comment by jpbrocca** [comment]
Hi @noelfernandes,
This is causes by recent changes on VS and XS parsing of T4 templates.

The solución is simple actually:

Just open the Colors.XML on Android project and replace the colores values to match the ones you ser on App.xaml (AccentColor).

You should be able to normally compile and fun your app.

Remember to closr this issue after you make the change, and of course if you still have issues ley us know.

Best,
JP

**Comment by noelfernandes** [comment]
Hi @jpbrocca 
Thanks for your response.

The original lines are commented and I have the following in my App.xaml

    
    
    <Color x:Key="AccentColor">#e25e14</Color>
    
    <Color x:Key="InverseTextColor">White</Color>

I used the same color codes in the colors.xml file in the Android project as shown below:

	<?xml version="1.0" encoding="utf-8" ?>
	<resources>
	  
	  <color name="AccentColor">#e25e14</color>
	  <color name="InverseTextColor">White</color>
	</resources>

I still get the same error while compiling.

Regards
Noel

**Comment by kunjal29** [comment]
If I remember correctly, I fixed this by changing the build action on the colors.tt file to None.

Regards,
Kunjal

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Sep 29, 2016 at 7:14 PM +0300, "noelfernandes" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jpbrocca<https://github.com/jpbrocca>
Thanks for your response.

The original lines are commented and I have the following in my App.xaml



<Color x:Key="AccentColor">#e25e14</Color>

<Color x:Key="InverseTextColor">White</Color>


I used the same color codes in the colors.xml file in the Android project as shown below:

<?xml version="1.0" encoding="utf-8" ?>
<resources>
  
  <color name="AccentColor">#e25e14</color>
  <color name="InverseTextColor">White</color>
</resources>


I still get the same error while compiling.

Regards
Noel

-

**Comment by jpbrocca** [comment]
Hi @noelfernandes,

Are you getting an error while compiling/running your app for Android or you mean trying to compile the Colors.cc file?
If it is the second case, then you should not compile anymore.
If it is the first case, you could delete that file since you won't be using it anymore. Alternatively you can try with @kunjal29 solution.

Let me know how it goes.
Best,
JP

**Comment by jpbrocca** [comment]
Hi @noelfernandes,

any update on this ?

Regards and thanks,
JP

**Comment by noelfernandes** [comment]
Hi @jpbrocca,

Sorry for the delayed response.

It is actually a colors.tt file with a '.xml' output extension.

I was able to compile it by following @kunjal29's resolution.

Thanks @kunjal29

Thanks n regards
Noel

**Comment by jpbrocca** [comment]
Hi @noelfernandes,
no worries!
Regards and thanks!
JP
