### ISSUE TITLE
SyncFusion integration

### ISSUE THREAD

**Issue by dmalach** [UXDivers/Grial-UI-Kit-Support#96]
I purchased Grail UI kit a few days ago, and as I am designing my app I'd like to add a chart to it, and SyncFusion looks like a good Xamarin Forms system. I am just having a hard time getting it running with your Grail UIKit sample project.  Do you have any examples of adding a SyncFusion chart to your Grailkit UI sample app?

**Comment by jpbrocca** [comment]
Hi @dmalach,
No, we currently do not have any sample integrating Syncfusion to Grial.

However, if you would like to share your project we could take a look and let you know if there are any workaround or anything that could make this run -if possible-.

You can write me to:
jpbrocca@uxdivers.com

Best,
JP

**Comment by garymedina** [comment]
@dmalach  I am starting the same thing. I plan on using the calendar to start but will use more later. How has your progress been?

**Comment by dirivero** [comment]
I’m closing this issue because it has been inactive for a couple of years.
