### ISSUE TITLE
KitKat Android 4.4 API 19

### ISSUE THREAD

**Issue by EmreAbi** [UXDivers/Grial-UI-Kit-Support#97]
Hi, 

On phsical device when I run Grial project I am having this error. Any one familier with this ?

Android.Content.Res.Resources+NotFoundException: File res/layout/fragment_bread_crumb_item.xml from color state list resource ID #0x1090059

**Comment by jpbrocca** [comment]
Hi @EmreAbi,

Which version of xamarin forms are you using ?

Best,
JP

**Comment by crakhi** [comment]
I am also facing this issue. Even when I installed your **demo app from PlayStore** on a device(Galaxy S3) with android 4.4.4 its failing to load!

**Comment by jpbrocca** [comment]
Hi guys.
If you send me an email to:

jpbrocca@uxdivers.com

With your purchase details I will send you the fix for this issue.

Best
JP

**Comment by crakhi** [comment]
Sent my details!
