### ISSUE TITLE
Close button on walkthrough  does not work in iOS10

### ISSUE THREAD

**Issue by scorpio2000** [UXDivers/Grial-UI-Kit-Support#99]
Hello,

We are having an issue with the walkthrough screens in Grial sample in iOS10. The close button on the top right does not close the walkthrough. Once the user starts it, the only option is to go to the end and close it from the finish option.

**Comment by jpbrocca** [comment]
Hello @scorpio2000, how are you?

Is this only happening on IOS10 -real or emulated device-? 
Do you get any error/exception?

Best regards,
JP

**Comment by scorpio2000** [comment]
Juan, the new file from your email worked. Thanks a lot.

**Comment by K232** [comment]
I've downloaded Grial UI Kit yesterday but Close-Button is also not working for me. Is it possible to get the modified files? Problem also exists with Grial UI Kit Demo downloaded from AppStore.

**Comment by jpbrocca** [comment]
Hi @K232,
can you send me an email with your purchase detail (your name, order number, date, etc.) so I can send you the updated file?

Thanks
JP

**Comment by K232** [comment]
To hello@uxdivers.com?

**Comment by jpbrocca** [comment]
Hi @K232,

Send it to jprocca@uxdivers.com ;)

Best,
JP
